### ISSUE TITLE
Conflicting weak symbol definitions when linking windows-macros on Github CI

### ISSUE THREAD

**Issue by qdot** [microsoft/windows-rs#1006]
When bringing in windows-macros in a crate and compiling it on Github Actions CI, I'm getting the following linking error:

```libwindows_gen-474a14e06a135143.rlib(windows_gen-474a14e06a135143.windows_gen.3qcf9mth-cgu.3.rcgu.o) : fatal error LNK1227: conflicting weak extern definition for '_RNvXININtNtCsdw1U8rBUA7W_11windows_gen6squote9to_tokenss1_0pEINtNtCs3E5rcf10EnF_5alloc5boxed3BoxpENtB5_8ToTokens9to_tokensB9_'.  New default '.weak._RNvXININtNtCsdw1U8rBUA7W_11windows_gen6squote9to_tokenss1_0pEINtNtCs3E5rcf10EnF_5alloc5boxed3BoxpENtB5_8ToTokens9to_tokensB9_.default._RINvMNtCstYrKh3qYsp_4core5sliceSNtNtCs3E5rcf10EnF_5alloc6string6String13get_uncheckedINtNtNtB5_3ops5range9RangeFromjEECsdw1U8rBUA7W_11windows_gen' conflicts with old default '.weak._RNvXININtNtCsdw1U8rBUA7W_11windows_gen6squote9to_tokenss1_0pEINtNtCs3E5rcf10EnF_5alloc5boxed3BoxpENtB5_8ToTokens9to_tokensB9_.default._RINvMNtCstYrKh3qYsp_4core5sliceSRe13get_uncheckedINtNtNtB5_3ops5range9RangeFromjEECsdw1U8rBUA7W_11windows_gen' in libwindows_gen-474a14e06a135143.rlib(windows_gen-474a14e06a135143.windows_gen.3qcf9mth-cgu.11.rcgu.o)```

CI Status Link: https://github.com/deviceplug/btleplug/runs/3164475302?check_suite_focus=true

I can't seem to repro this on my local machine, so it may be something in our CI setup, but I'm not particularly sure what. We aren't caching anything that I'm aware of, so I don't think this is a conflict between versions or anything.

**Comment by kennykerr** [comment]
Weird. We run a lot of CI builds across windows-rs and windows-samples-rs and I've not seen this before. Perhaps @rylev or @ricobbe recognize something.

**Comment by danielframpton** [comment]
I think the issue is not with the particular crate but a general issue with coverage instrumentation as also seen in rust-lang/rust#85461.

The conflict appears to be between different codegen units in the same rlib, so you may have success setting `-Ccodegen-units=1` as well as `-Zinstrument-coverage` for that build.

**Comment by qdot** [comment]
Well, after another change to the macOS code (and therefore not even touching WinRT code), everything builds fine on our CI, so I'm gonna chalk this up to us getting assigned a weird builder and close out. Thanks for the coverage insight though, will keep that knowledge around just in case I get more scary error messages. 😃
