### ISSUE TITLE
Is there a method called GetShortPathName?

### ISSUE THREAD

**Issue by dobefore** [microsoft/windows-rs#1013]
In crate `winapi` ,there is a similar method [GetShortPathNameW](https://docs.rs/winapi/0.3.9/winapi/um/fileapi/fn.GetShortPathNameW.html):
```
pub unsafe extern "system" fn GetShortPathNameW(
    lpszLongPath: LPCWSTR, 
    lpszShortPath: LPWSTR, 
    cchBuffer: DWORD
) -> DWORD
```
yet it seems it's no implemenation or I 'm not familiar with it.
Is there a way to impl this method ,or some related instructions about it?
any advice would be appreciated

**Comment by sabbyX** [comment]
Not sure what you're exactly asking.

If you're asking whether `GetShortPathName` exists in windows-rs, yes it does, `Windows::Win32::Storage::FileSystem::GetShortPathNameW`.

Or you are worried about suffix `W`
> The A functions use Ansi (not ASCII) strings as input and output, and the W functions use Unicode string instead (UCS-2 on NT4 and earlier, UTF-16 on W2K and later)

[official docs](https://docs.microsoft.com/en-us/windows/win32/learnwin32/working-with-strings#unicode-and-ansi-functions)

**Comment by kennykerr** [comment]
You can see its [Rust definition here](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Storage/FileSystem/fn.GetShortPathNameW.html).

**Comment by dobefore** [comment]
@sabbyX  @kennykerr ,thank you very much.this hepled me a lot!
