### ISSUE TITLE
IAsyncOperationWithProgress<IBuffer, u32> does not implement Future

### ISSUE THREAD

**Issue by Enigmatrix** [microsoft/windows-rs#1015]
Seems that `IAsyncOperationWithProgress<IBuffer, u32>` does not implement `Future`? (ignore the fact that it doesn't implement `Default`)
```rust
let w: IAsyncOperationWithProgress<IBuffer, u32> = Default::default();
let w1 = w.await?;
```
gives the error
```
error[E0277]: `IAsyncOperationWithProgress<IBuffer, u32>` is not a future
  --> src\engine\platform\src\info\app_info.rs:23:22
   |
23 |             let w1 = w.await?;
   |                      ^^^^^^^ `IAsyncOperationWithProgress<IBuffer, u32>` is not a future
````

**Comment by sabbyX** [comment]
> `IAsyncOperationWithProgress<IBuffer, u32>` does not implement `Future`

It does implement `Future`: https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Foundation/struct.IAsyncOperationWithProgress.html#impl-Future

Do you import `IAsyncOperationWithProgress` directly?

**Comment by Enigmatrix** [comment]
> Do you import IAsyncOperationWithProgress directly?

🤦 after including `Windows::Foundation::*` it works:
```rust
    windows::build! {
        ...
        Windows::Foundation::*,                                 // IAsyncOperationWithProgress's Future
    };
```
