### ISSUE TITLE
How do I disable the terminal from opening up when executing my Rust code?

### ISSUE THREAD

**Issue by Joe23232** [microsoft/windows-rs#1016]
Hey guys, so on Windows normally when you compile your code it generates an executable, so when I click on it it always opens up a temrinal window. I want to disable it showing a terminal window. I tried adding this to the beginning of my code:

`#![windows_subsystem = "windows"]`

I am using this but like it still shows the terminal window and in some cases it would open up multiple ones but this time with no output. I am not too sure why this is happening and if there is a way to stop the terminal from completely showing up at all?

From this [post](https://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window) I have tried to even use this code:

```rust
fn hide_console_window() {
    use std::ptr;
    use winapi::um::wincon::GetConsoleWindow;
    use winapi::um::winuser::{ShowWindow, SW_HIDE};

    let window = unsafe {GetConsoleWindow()};
    // https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
    if window != ptr::null_mut() {
        unsafe {
            ShowWindow(window, SW_HIDE);
        }
    }
}
```
Which appeared to have not done much. Any ideas/suggestions?

**Comment by riverar** [comment]
Can you provide a sample program that reproduces the issue?

**Comment by Joe23232** [comment]
@riverar Sure mate.

So this is `main.rs`
```rust
// Disable terminal
#![windows_subsystem = "windows"]

use std::process::Command;

fn main()
{
    hide_console_window();
    
    let output = 
    Command::new("cmd.exe")
    .arg("/c")
    .arg("ping")
    .arg("www.google.com")
    .output()
    .unwrap();

    let output = output.status.to_string();

    //println!("{}", output);
}

fn hide_console_window()
{
    use std::ptr;
    use winapi::um::wincon::GetConsoleWindow;
    use winapi::um::winuser::{ShowWindow, SW_HIDE};

    let window = unsafe {GetConsoleWindow()};
    // https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
    if window != ptr::null_mut()
    {
        unsafe
        {
            ShowWindow(window, SW_HIDE);
        }
    }
}
```

And this is my cargo dependences:

`cargo.toml`
```toml
[dependencies]
winapi = {version = "0.3", features = ["wincon", "winuser"]}
```

**Comment by riverar** [comment]
Think you got the wrong repository. This repository covers the `windows` crate, while you're using the `winapi` crate. You'll want to file this at https://github.com/retep998/winapi-rs/issues.

**Comment by Joe23232** [comment]
Yes I understand, but like I was originally trying this out and it failed so I wanted to know what is the solution using `windows-rs`? @riverar

**Comment by aWeinzierl** [comment]
@riverar I can confirm that works.
However, is there a way to keep an appearing console window open?

I am trying to debug an UWP app (based on the sample app) and a stacktrace is printed to the console window, which closes so fast you cannot really examine its contents.

**Comment by riverar** [comment]
@aWeinzierl You can cheat and just add `std::io::stdin().read(&mut [0]);` somewhere near the _end_ of your app. (This waits for a byte to be produced on the stdin stream, e.g. waiting for someone to hit [Enter].

**Comment by aWeinzierl** [comment]
I got my hopes up to early: doesn't really change anything. 
Even if I try to catch the panic in the main.
And, if no panic happens, the console doesn't close, and I never reach the read statement either.
Of course, directly catching the panic where the panic happens works.
```
#[implement(
    extend Windows::UI::Xaml::Application,
    override OnLaunched,
    override OnActivated,
)]
struct MyApp();

#[allow(non_snake_case)]
impl MyApp {
    fn OnLaunched<'a>(&self, _: &Option<LaunchActivatedEventArgs>) -> Result<()> {
        Ok(())
    }

    fn OnActivated<'a>(&self, _: &Option<IActivatedEventArgs>) -> Result<()> {
        // let result = panic::catch_unwind(|| { // prevents program crash 
            panic!("print stacktrace and close terminal window");
        // });
        let window = Window::Current()?;
        window.SetContent(TextBox::new()?)?;
        window.Activate()?;
        self.OnLaunched(&None)
    }
}

fn main() -> Result<()> {
    unsafe {
        CoInitializeEx(std::ptr::null_mut(), COINIT_MULTITHREADED)?;
    }

    let result = panic::catch_unwind(|| { // doesn't stop it from closing on panic
        Application::Start(ApplicationInitializationCallback::new(|_| {
            MyApp().new()?;
            Ok(())
        }));
    });
    println!("{:?}", result);
    std::io::stdin().read(&mut [0]); // doesn't stop it from closing on panic
    Ok(())
}
```
