### ISSUE TITLE
Overloaded members IDCompositionVisual2::SetOffsetX assigned to wrong vtable slots?

### ISSUE THREAD

**Issue by emtenet** [microsoft/windows-rs#1017]
Whilst playing around with this crate I encountered an unexplained E_INVALIDARG whilst calling IDCompositionVisual2::SetOffsetX(&self, offsetx: f32)

I prepared a few short self contained projects to compare this behaviour with other compilers and crates.
See the following [Gist](https://gist.github.com/emtenet/89b0facd11e5b90f6f6df5b5bad2c505).

My guess is that the call to:

- `HRESULT IDCompositionVisual2::SetOffsetX(float)`

uses the wrong vtable slot and ends up calling this instead:

- `HRESULT IDCompositionVisual2::SetOffsetX(IDCompositionAnimation*)`

When a float of `0.0` is passed it returns E_INVALIDARG complaing about a null animation pointer.
When other float values are passed it crashes.

The `winapi` crates seems to have the two overloaded `SetOffsetX` members ordered in vtable slots opposite to this crate.

- Microsoft Windows 10 Pro
- 10.0.19043 N/A Build 19043
- rustc 1.52.1 (9bc8c42bb 2021-05-09)
- Microsoft Visual Studio Community 2019 Version 16.10.4

**Comment by riverar** [comment]
Hm, at a glance, not seeing anything wrong with the bindings. What version of the crate are you using? Can you create a minimum repro project so we can run it through the debugger?

This is from `dcomp.h`:
```cpp
DECLARE_INTERFACE_IID_(IDCompositionVisual, IUnknown, "4d93059d-097b-4651-9a60-f0f25116e2f3")
{
    // Changes the value of OffsetX property
    STDMETHOD(SetOffsetX)(THIS_
        float offsetX
        ) PURE;

    // Animates the value of the OffsetX property.
    STDMETHOD(SetOffsetX)(THIS_
        _In_ IDCompositionAnimation* animation
        ) PURE;

   // ...
```

The generated bindings look like:

```rust
pub struct IDCompositionVisual(::windows::IUnknown);
impl IDCompositionVisual {
    pub unsafe fn SetOffsetX(&self, offsetx: f32) -> ::windows::Result<()> {
        (::windows::Interface::vtable(self).3)(
            ::windows::Abi::abi(self),
            ::std::mem::transmute(offsetx),
        )
        .ok()
    }
    pub unsafe fn SetOffsetX2<'a>(
        &self,
        animation: impl ::windows::IntoParam<'a, IDCompositionAnimation>,
    ) -> ::windows::Result<()> {
        (::windows::Interface::vtable(self).4)(
            ::windows::Abi::abi(self),
            animation.into_param().abi(),
        )
        .ok()
    }

// ...
```

**Comment by riverar** [comment]
I just realized you said `IDCompositionVisual2`, my mistake. Let me review how that's handled.

**Comment by riverar** [comment]
Looks okay there too. A repro at this point would be handy, thanks!

```rust
impl IDCompositionVisual2 {
    pub unsafe fn SetOffsetX(&self, offsetx: f32) -> ::windows::Result<()> {
        (::windows::Interface::vtable(self).3)(
            ::windows::Abi::abi(self),
            ::std::mem::transmute(offsetx),
        )
        .ok()
    }
    pub unsafe fn SetOffsetX2<'a>(
        &self,
        animation: impl ::windows::IntoParam<'a, IDCompositionAnimation>,
    ) -> ::windows::Result<()> {
        (::windows::Interface::vtable(self).4)(
            ::windows::Abi::abi(self),
            animation.into_param().abi(),
        )
        .ok()
    }

   // ...
```

**Comment by emtenet** [comment]
I have prepared some sample projects in the following repository https://github.com/emtenet/set-offset-x
Start with the rust project in the `issue` directory.
I have updated it to use the latest 0.18.0 version of the windows crate.

**Comment by emtenet** [comment]
My guess is that methods that are overloaded (same name, different parameter types) are not laid out in the vtable in the same order that they appear in the C++ header files.

This issue is looking at the two overloaded methods named `SetOffsetX`. In the header file they are in the following order:

- `SetOffsetX(float)`
- `SetOffsetX(IDCompositionAnimation*)`

Compare that with how the [winapi](https://crates.io/crates/winapi) crate places those two methods in the vtable, they are reversed.

- https://github.com/retep998/winapi-rs/blob/0.3/src/um/dcomp.rs#L163-L169

My sample repository contains two additional projects implementing equivilent logic to the `issue` project.

The `ok_rust` project uses the `winapi` crate and runs successfully.

The third project `ok_cpp` is written in C++ using Visual Studio 2019 and also runs successfuly.

I have compared the assembly output of the three sample projects to confirm that the project using the `winapi` crate matches the C++ project in the vtable slot they use to call the `SetOffsetX(float)` method. I can provide further detail on how I did this comparison if you need it.

**Comment by riverar** [comment]
Agreed. Looks like an upstream SDK/metadata bug. Nice find @emtenet!

I filed a bug on win32metadata for you. https://github.com/microsoft/win32metadata/issues/600.

Will close this out as the crate is working properly but feel free to ping us if you have any further issues/questions/etc.

```diff
0:001> dps dcomp!Windows::UI::Composition::InteropVisual::Api::`vftable'
 00007ff8`4ddd6c20  00007ff8`4dcc2390 dcomp![...]::QueryInterface
 00007ff8`4ddd6c28  00007ff8`4dcd8f00 dcomp![...]::AddRef
 00007ff8`4ddd6c30  00007ff8`4dcbe6f0 dcomp![...]::Release
-00007ff8`4ddd6c38  00007ff8`4dd61980 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX
//                  ^^^^^^^^^^^^^^^^^ slot 3 = SetOffsetX(IDCompositionAnimation*)
 00007ff8`4ddd6c40  00007ff8`4dcce450 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX
 00007ff8`4ddd6c48  00007ff8`4dd61a20 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetY
 00007ff8`4ddd6c50  00007ff8`4dc96d00 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetY
 00007ff8`4ddd6c58  00007ff8`4dccf970 dcomp!Windows::UI::Composition::InteropVisual::Api::SetTransform
 00007ff8`4ddd6c60  00007ff8`4dd61de0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetTransform
 00007ff8`4ddd6c68  00007ff8`4dd61fe0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetTransformParent
 00007ff8`4ddd6c70  00007ff8`4dcd15e0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetEffect
 00007ff8`4ddd6c78  00007ff8`4dcd5c30 dcomp!Windows::UI::Composition::InteropVisual::Api::SetBitmapInterpolationMode
 00007ff8`4ddd6c80  00007ff8`4dcd6850 dcomp!Windows::UI::Composition::InteropVisual::Api::SetBorderMode
 00007ff8`4ddd6c88  00007ff8`4dd617a0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetClip
 00007ff8`4ddd6c90  00007ff8`4dcd4690 dcomp!Windows::UI::Composition::InteropVisual::Api::SetClip
 00007ff8`4ddd6c98  00007ff8`4dcc85f0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetContent
0:001> x /v dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX*
 prv func   00007ff8`4dcce450   6c dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX (void)
-pub func   00007ff8`4dd61980    0 dcomp!Windows::UI::Composition::InteropVisual::Api::SetOffsetX (public: virtual long __cdecl Windows::UI::Composition::InteropVisual::Api::SetOffsetX(struct IDCompositionAnimation *))
//          ^^^^^^^^^^^^^^^^^
```

**Comment by riverar** [comment]
@emtenet We grab metadata periodically and check it in @ https://github.com/microsoft/windows-rs/tree/master/crates/reader/default

I'll check up on this particular interface tomorrow; @kennykerr and I were recently chatting about testing this fix too, so good timing.

If you'd like to try the latest metadata in the meantime, and see if it Just Works™️, grab the latest winmd from https://github.com/microsoft/win32metadata/raw/master/scripts/BaselineWinmd/Windows.Win32.winmd.
