### ISSUE TITLE
README example does not compile

### ISSUE THREAD

**Issue by jlkiri** [microsoft/windows-rs#1020]
I am getting the following error just by copy-pasting the README example. What should I do?

```
error: proc macro panicked
 --> bindings\build.rs:2:5
  |
2 | /     windows::build!(
3 | |         Windows::Data::Xml::Dom::*,
4 | |         Windows::Win32::Foundation::CloseHandle,
5 | |         Windows::Win32::System::Threading::{CreateEventW, SetEvent, WaitForSingleObject},
6 | |         Windows::Win32::UI::WindowsAndMessaging::{MessageBoxA, MB_OK},
7 | |     );
  | |______^
  |
  = help: message: Could not find namespace `Windows.Win32.Foundation`

error: aborting due to previous error

error: could not compile `bindings`
```

Windows 10, Build tools including Windows SDK installed

**Comment by jlkiri** [comment]
I noticed that I was using the 0.9.1 version of the crate from the official tutorial, 0.18.0 made it work, but I still get an error importing MB_OK from `Windows::Win32::UI::WindowsAndMessaging`. For now I managed to use `0.into()` for a simple OK but I think something might be broken.

**Comment by jlkiri** [comment]
To report further: changing the import to `Windows::Win32::UI::WindowsAndMessaging::*` made MB_OK work too!

**Comment by riverar** [comment]
Can you share your sample? The README doesn't direct you to create a bindings\ folder so it's not clear what your layout is. I just went through the README and it works fine.

**Comment by kennykerr** [comment]
That's an old version of the readme. The current version works fine.

**Comment by riverar** [comment]
Closing as it's working as-is. @jlkiri let us know if you're still having trouble.
