### ISSUE TITLE
HKEY and PartialEq

### ISSUE THREAD

**Issue by galenb-msft** [microsoft/windows-rs#1023]
I have a function that uses match to convert an HKEY root/hive into a string:

match hive {
	HKEY_CURRENT_USER => "HKCU:".to_string(),
	HKEY_LOCAL_MACHINE => "HKLM:".to_string(),
	_ => "UNKNOWN:".to_string(),
}

Rust analyzer complains, and compilation fails with "unreachable pattern" errors:

to use a constant of type `HKEY` in a pattern, `HKEY` must be annotated with `#[derive(PartialEq, Eq)]`rustc
unreachable patternrustc(unreachable_patterns)
windows_bindings::Windows::Win32::System::Registry
pub const HKEY_CURRENT_USER: HKEY

I went to the crate docs for HKEY and found that PartialEq is implemented, and that allowed me to change my match to a less idiomatic if/else if/else expression.

It seems that rust really wants the HKEY struct, and likely others, to use the derive macro instead pf impl PartialEq for HKEY et al...

It seems that doing PartialEq support using the derive macro would allow more idiomatic usage.

**Comment by kennykerr** [comment]
This was recently fixed.
