### ISSUE TITLE
Invalid code generated for `IWICBitmap::CopyPixels`

### ISSUE THREAD

**Issue by sabbyX** [microsoft/windows-rs#1039]
Generated Code:
```rust
pub unsafe fn CopyPixels(
    &self,
    prc: *const WICRect,
    cbstride: u32,
    cbbuffersize: u32,
) -> ::windows::Result<u8> {
    let mut result__: <u8 as ::windows::Abi>::Abi = ::std::mem::zeroed();  // <--- invalid, it should be a buffer
    (::windows::Interface::vtable(self).7)(
        ::windows::Abi::abi(self),
        ::std::mem::transmute(prc),
        ::std::mem::transmute(cbstride),
        ::std::mem::transmute(cbbuffersize),
        &mut result__,
    )
        .from_abi::<u8>(result__)
}
```
calling it causes the obvious `access violation`. The generated return value is supposed to be `pbBuffer`, which is pointer to the buffer that should should recieve the pixel data.

[from docs
](https://docs.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicbitmapsource-copypixels)
> pbBuffer
>
>Type: BYTE*
>
>A pointer to the buffer.

**Comment by kennykerr** [comment]
I just applied a fix for this: https://github.com/microsoft/windows-rs/pull/1040
