### ISSUE TITLE
utf-8 and ansi PSTR to rust string

### ISSUE THREAD

**Issue by shangjiaxuan** [microsoft/windows-rs#1043]
There is an implementation of converting rust string to null terminated PSTR types for use in windows-api functions. The implementation converts directly by appending a null.

This will not work for most systems' default which is not utf-8 (which is still somewhat experimental), and the app specifying a utf-8 execution supported via the manifest only available after a certain build of win10.

Converting ansi PSTR results of MultiByteToWideChar to rust string is guaranteed to panic when working in rust with them.

This may be better if the documentation is clearer, and recommend using the W version of the functions which automatically does the conversion.

**Comment by kennykerr** [comment]
Using UTF-8 strings with the ANSI version of APIs is certainly a gotcha to keep in mind. Some of them deal with UTF8 but that is certainly not universal yet. This has been a longstanding issue with the Windows API. Certainly, using the wide version of APIs is the recommended solution to overcome this problem, but that's up the developer to make that determination.
