### ISSUE TITLE
Is it possible to get a function address

### ISSUE THREAD

**Issue by TrueBers** [microsoft/windows-rs#1051]
As I understand, every binding function is a wrapper that calls actual `extern "system" fn`. Am I right?

So, when I'm trying to get an address of, i.e. `System::Threading::GetCurrentProcessId`, it returns an address of that wrapper instead of the actual function in the mapped `Kernel32.dll`.

Is it possible to get such addresses from bindings or should I declare it manually with `extern` every time?

**Comment by kennykerr** [comment]
You'd have to declare it yourself. Why do you need the address?
