### ISSUE TITLE
Issue wih Windows::Win32::System::Diagnostics::Debug::IMAGE_FILE_CHARACTERISTICS size

### ISSUE THREAD

**Issue by pickjob** [microsoft/windows-rs#1052]
IMAGE_FILE_CHARACTERISTICS uesed in IMAGE_FILE_HEADER is declared as  u32, which I thing it should be u16. Is it right?

**Comment by riverar** [comment]
Hey @pickjob, this is being tracked already via microsoft/win32metadata#601. Going to close this issue in favor of that one.
