### ISSUE TITLE
WinRT array parameters need to be constrained more carefully

### ISSUE THREAD

**Issue by bdbai** [microsoft/windows-rs#1057]
Inspired by [tests/implement/tests/generic_default.rs](https://github.com/microsoft/windows-rs/blob/d1a697339c2590186184415bd19d0546eb61561d/tests/implement/tests/generic_default.rs), I was trying to implement a simple `IVectorView`. The `GetMany` function inside `IVectorView` has a out param [`items`](tests/implement/tests/generic_default.rs), which is an WinRT array. The generated shim code looks like:

```rust
        unsafe extern "system" fn abi5(
            this: ::windows::RawPtr,
            startindex: u32,
            items_array_size: u32,
            items: *mut ::windows::RawPtr,
            result__: *mut u32,
        ) -> ::windows::HRESULT {
            let this = (this as *mut ::windows::RawPtr).sub(2 + 1usize) as *mut Self;
            match (*this)
                .implementation
                .GetMany(startindex, ::std::mem::transmute_copy(&items))
            {
                ::std::result::Result::Ok(ok__) => {
                    *result__ = ::std::mem::transmute_copy(&ok__);
                    ::std::mem::forget(ok__);
                    ::windows::HRESULT(0)
                }
                ::std::result::Result::Err(err) => err.into(),
            }
        }
```
Here, the `transmute_copy` does not put any constraints on the return type, meaning the implementation can declare a data type as large as possible without using `unsafe` keyword, like:
```rust
fn GetMany(&self, start_index: u32, items: [u8; 256]) -> Result<u32>
```
and eventually compiles successfully. This may allow runtime security problems if the implementation puts a data type other than a fat pointer.

AFAIK the parameter types of arrays could be hard-coded as `&[T]` for input and `&mut [MaybeUninit<T>]` for output. Any suggestions on this?

**Comment by kennykerr** [comment]
Yes, this isn't quite done yet. If it helps, here's how `IVectorView`'s `GetMany` method should work:

The `GetMany` method has two logical parameters and a return value. The first is the start index from which to copy, the second is the array to copy them into. This array is a logical slice, a pointer and a size. The return value reports the actual number of elements copied. 

The `GetMany` ABI has four parameters: start index, size of input slice, pointer to slice, and elements copied.

So that's the ABI requirements and semantics, but yes this still needs to be constrained a little more carefully.

**Comment by bdbai** [comment]
@kennykerr thanks for the explanation! However, I still have a concern about out parameters. I am not sure whether WinRT (or COM) requires pointees of out parameters properly initialized. If not, then we’d better mark out parameters with `MaybeUninit` to prevent accidental reads of uninitialized data.

**Comment by kennykerr** [comment]
Yes, the first thing the GetMany ABI needs to do is zero out the memory of the incoming array. This needs to happen before the call into the Rust implementation provided by the developer and at that point you know its default initialized.

**Comment by bdbai** [comment]
@kennykerr your answer perfectly addresses my concern. One last question, why is `item_array_size` unused?

**Comment by kennykerr** [comment]
That's simply because I haven't finished implementing this yet. As an example, here's how this is (correctly) implemented in cppwinrt:

```C++
int32_t __stdcall GetMany(uint32_t startIndex, uint32_t __itemsSize, arg_out<T> items, uint32_t* winrt_impl_result) noexcept final try
{
    zero_abi<T>(items, __itemsSize);
    typename D::abi_guard guard(this->shim());
    *winrt_impl_result = detach_from<uint32_t>(this->shim().GetMany(startIndex, array_view<T>(reinterpret_cast<T*>(items), reinterpret_cast<T*>(items) + __itemsSize)));
    return 0;
}
catch (...) { return to_hresult(); }
```

**Comment by bdbai** [comment]
In Rust we have [`from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html) and [`from_raw_parts_mut`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts_mut.html). I guess this issue can be solved by using these functions?

**Comment by kennykerr** [comment]
Yep, Rust makes this relatively easy. I just need to get to around to finishing this. Thanks for the nudge! I'll try to get this wrapped up very soon. 😉 

It would be great to finally have a working implementation of the WinRT collections in Rust.

**Comment by bdbai** [comment]
@kennykerr thanks for your great work!

**Comment by kennykerr** [comment]
Just reviewing this old issue and I think I covered this issue when I completed stock collection support back in https://github.com/microsoft/windows-rs/releases/tag/0.46.0

Will close this one, but let me know if you have any further issues.
