### ISSUE TITLE
Is there a `STILL_ACTIVE` constant?

### ISSUE THREAD

**Issue by zhiburt** [microsoft/windows-rs#1064]
According to the doc [GetExitCodeProcess](https://docs.microsoft.com/en-gb/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess?redirectedfrom=MSDN) there have to be a corresponding constant `STILL_ACTIVE`.

But as I see in the docs https://microsoft.github.io/windows-docs-rs/doc/bindings/index.html?search=STILL_ACTIVE
there's no any.

Note that winapi crate have it https://docs.rs/winapi/0.3.9/winapi/um/minwinbase/constant.STILL_ACTIVE.html

thank you

**Comment by riverar** [comment]
Hi @zhiburt! `STILL_ACTIVE` is not really a constant. It's a older-than-dirt macro. Use `STATUS_PENDING` instead. (This is what minwinbase.h does.) I'll add an issue to upstream metadata for discussion.

**Comment by riverar** [comment]
Ref: https://github.com/microsoft/win32metadata/issues/616
