### ISSUE TITLE
Incorrect representation of IMAGE_NT_HEADERS

### ISSUE THREAD

**Issue by MrElectrify** [microsoft/windows-rs#1066]
The representation of `IMAGE_NT_HEADERS` is incorrect. This is due to 4 separate incorrect representations:
- `IMAGE_FILE_CHARACTERISTICS` in `IMAGE_FILE_HEADER` is treated as `u32`. This is incorrect, as per MSDN it is `WORD`, or `u16`.
  Reference: https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Diagnostics/Debug/struct.IMAGE_FILE_CHARACTERISTICS.html
  https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_file_header
- `IMAGE_OPTIONAL_HEADER_MAGIC` in `IMAGE_OPTIONAL_HEADER32/64` is treated as `u32`. This is incorrect, as per MSDN it is `WORD`, or `u16`.
  Reference: https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Diagnostics/Debug/struct.IMAGE_OPTIONAL_HEADER_MAGIC.html
  https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_optional_header32
- `IMAGE_SUBSYSTEM` in `IMAGE_OPTIONAL_HEADER32/64` is treated as `u32`. This is incorrect, as per MSDN, it is `WORD`, or `u16`.
  Reference: https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Diagnostics/Debug/struct.IMAGE_SUBSYSTEM.html
  https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_optional_header32
- `IMAGE_DLL_CHARACTERISTICS` in `IMAGE_OPTIONAL_HEADER32/64` is treated as `u32`. This is incorrect, as per MSDN, it is `WORD`, or `u16`.
  Reference: https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Diagnostics/Debug/struct.IMAGE_DLL_CHARACTERISTICS.html
  https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-image_optional_header32

This makes working with NT headers impossible without defining custom structures, as the alignment of these values and their size creates a corrupted view of the headers. I think this is an issue with the representation in the metadata, but am not sure where else to create an issue for this.

Thanks

**Comment by riverar** [comment]
Hey @MrElectrify, yep good catch. This is already being tracked/worked on upstream https://github.com/microsoft/win32metadata/issues/601. Will close this one in favor of that one.
