### ISSUE TITLE
How to determine a windows machines is 64bit or 32bit ?

### ISSUE THREAD

**Issue by hustclf** [microsoft/windows-rs#1072]
When I run  `wmic OS get OSArchitecture` in powershell, I can get the right result. 
```
PS C:\Users\Administrator> wmic OS get OSArchitecture
>>
OSArchitecture
64-bit
```

Which api in windows-rs can get the same result?  thanks.

**Comment by kennykerr** [comment]
This isn't really a question specific to the Windows crate. Such questions are more suitable for https://stackoverflow.com/. 

Anyway, it depends on what problem you're trying to solve. I would probably just query the following environment variable:

```rust
fn main() {
    println!("{:?}", std::env::var("PROCESSOR_ARCHITECTURE"))
}
```
