### ISSUE TITLE
`#[implement(IClassFactory)]` ignores CreateInstance?

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#1080]
```rs
#[implement(Windows::Win32::System::Com::IClassFactory)]
struct ClassFactory {}

#[allow(non_snake_case)]
impl ClassFactory {
    // Error: associated function is never used: `CreateInstance`rustc(dead_code)
    pub unsafe fn CreateInstance<'a>(
        &self,
        punkouter: &Option<windows::IUnknown>,
    ) -> windows::Result<IUnknown> {
        Err(E_NOTIMPL.ok().unwrap_err())
    }
    pub unsafe fn LockServer<'a>(&self, _flock: BOOL) -> windows::Result<()> {
        E_NOTIMPL.ok()
    }
}
```

LockServer is properly referenced but CreateInstance is ignored. Omitting it does not cause compiler errors. Not sure why 🤔

**Comment by riverar** [comment]
Looks like a false positive hit on the detection of a `QueryInterface` signature. COM impl support is very much a work in progress! (You can hack out the checks if you're just playing around, but will probably cause explosions elsewhere.)

cc: @kennykerr 

https://github.com/microsoft/windows-rs/blob/8b8869d625d32a9860664ac42e755b9501a7f675/crates/gen/src/win32.rs#L118-L121

https://github.com/microsoft/windows-rs/blob/8b8869d625d32a9860664ac42e755b9501a7f675/crates/reader/src/method_signature.rs#L26-L43

**Comment by kennykerr** [comment]
Yep, as Rafael pointed out, I'm still working on a few of those signatures. I covered the majority of them but a few still remain and those are highlighted by the unimplemented macro. I hope to get those wrapped up very soon.

**Comment by kennykerr** [comment]
Finally getting around to this again. This is tricky because while I would like to ensure the calling and implementing signatures essentially mirror each other, for functions with the "QueryInterface" pattern this doesn't really make sense. The caller is best served with a generic function that deduces the `Guid` while the implementer is best served with an explicit `Guid` parameter so that it can implement all queries in a single function. So I'm leaning toward having the implement macro expect a signature like this for the IClassFactory example:

```rust
pub fn CreateInstance(&self, outer: &Option<IUnknown>, iid: &Guid) -> Result<IUnknown> {
    // ...
}
```

**Comment by riverar** [comment]
In the general case you refer to, would that then involve returning a `IUnknown::NULL` or similar?

**Comment by kennykerr** [comment]
Have a look at the PR for an example: https://github.com/microsoft/windows-rs/pull/1163

Basically, the query-like behavior will only be treated specially on the calling side.

**Comment by saschanaz** [comment]
Not sure about `IUnknown::NULL`, it seems the function I want to port tries querying and returns E_NOINTERFACE when failed. https://github.com/microsoft/Windows-classic-samples/blob/67a8cddc25880ebc64018e833f0bf51589fd4521/Samples/IME/cpp/SampleIME/SampleIME.cpp#L22

**Comment by kennykerr** [comment]
Yes, the PR supports that.

**Comment by riverar** [comment]
I was just throwing out `IUnknown::NULL` as a possible _magic_ value that would get used internally to satisfy a theoretical implementation that needed to return `S_OK` but set the hidden `result` to `nullptr`:

```rust
pub fn CreateInstance(&self, outer: &Option<IUnknown>, iid: &Guid) -> Result<IUnknown> {
    Ok(IUnknown::Null) // Or something similar that conveys
                       // result = nullptr; return S_OK;
}
```

But this starts to get weird quickly. I think Kenny's proposed change is simpler to understand.
