### ISSUE TITLE
awaiting IAsyncOperation causing "`IAsyncOperation<HSTRING>` is not a future"

### ISSUE THREAD

**Issue by TTTPOB** [microsoft/windows-rs#1082]
my code here, I was trying to make use of windows clipboard in rust and wrote a test project like this, but I got 
```rust
mod bindings{
    windows::include_bindings!();
}
use std::convert::TryFrom;

use bindings::{
    Windows::ApplicationModel::DataTransfer::{
        Clipboard,
        DataPackage,
        DataPackageView,
        IDataPackage,
        IDataPackageView
    },
};

#[tokio::main]
async fn main() -> windows::Result<()>{
    let clip_content = Clipboard::GetContent()?.GetTextAsync()?.await?;
    println!("{}", String::try_from(clip_content)?);

    Ok(())
}
```
and error
![image](https://user-images.githubusercontent.com/19909103/130383362-6aba2d2a-7a16-4c17-af33-276e378bcd3e.png)

What is wrong with my code?

**Comment by riverar** [comment]
@TTTPOB You're missing `Windows::Foundation::IAsyncOperation` in your build macro / use declarations. (Afterwards, you'll need to fix the compilation error on your `String::try_from`.

**Comment by riverar** [comment]
Also, note: This API requires a UI thread. I suggest considering a simpler approach/API, i.e. `Windows::Win32::System::DataExchange::GetClipboardData`.

See also: #187 #317

**Comment by TTTPOB** [comment]
Ah! Thank you for pointing that out, I am totally new to windows api
