### ISSUE TITLE
Identical main.rs and an example file behaves differently

### ISSUE THREAD

**Issue by zhiburt** [microsoft/windows-rs#1084]
Hey there, thank you for this crate and your job.

### Agenda

I am using a ConPTY to create a process and interact with this. (At least trying.... see PS section 😄)

I noticed a weird behaviour at the beginning I was thinking it something else.
But I was shorting a list of possible issues and I made a reproducible example.

https://github.com/zhiburt/conpty/tree/example_vs_main_issue

### Issue

We have a library with function `spawn`.
And we call this function in an example file and in `main.rs` file.

Files are equal. They just call `spawn` function.

```rust
pub fn main() {
    conpty::spawn().unwrap()
}
```

* When run `cargo run`

It prints what ping execution provides it with and stuck. (Both of these actions are actually not clear to me  as I wouldn't expect this behaviour I would expect that nothing will be printed and the process will be finished. But it's a different story).

* When run `cargo run --example ping`

It prints nothing and spawns, endlessly, ping process and Co host process.

I may assume that there's some sort of memory corruption here, but I wasn't able to find it.

Thank you one more time.

_____

PS: (not related) Maybe anyone knows why ReadFile on ConPTY pipe doesn't get notified as a process exits, and how to bypass it? 😥 (https://github.com/microsoft/terminal/issues/4564)

**Comment by kennykerr** [comment]
This question seems unrelated to the `Windows` crate. You may have better luck posting your question on https://stackoverflow.com/

**Comment by zhiburt** [comment]
@kennykerr it may be in case I did something wrong, but the code is pretty plain and it seems fine? (You can take a look on the reference)

I wen't through it a couple of times (trust me) 😄 

But do you think the differences in `cargo run` vs `cargo run --example ping` is dictated by a error in my code?

**Comment by kennykerr** [comment]
Sorry I wasn't clear - I did have a look at the repo but nothing jumps out at me as an obvious issue.

**Comment by zhiburt** [comment]
The same goes from me 😄

**Comment by zhiburt** [comment]
I shortened a code to reproduce an issue to just call of `CreateProcessW`

```rust
pub fn spawn() -> windows::Result<()> {
    let mut startup_info = STARTUPINFOEXW::default();
    startup_info.StartupInfo.cb = size_of::<STARTUPINFOEXW>() as u32;

    let mut proc_info = PROCESS_INFORMATION::default();
    unsafe {
        CreateProcessW(
            PWSTR::NULL,
            "ping",
            null_mut(),
            null_mut(),
            false,
            PROCESS_CREATION_FLAGS::default(),
            null_mut(),
            PWSTR::NULL,
            &mut startup_info.StartupInfo,
            &mut proc_info,
        )
        .ok()
        .unwrap()
    };

    std::thread::sleep_ms(5000);

    Ok(())
}
```

**Comment by zhiburt** [comment]
By the way I found the problem :tada: 

It was usage of `**void` instead of `*void` :smile:
