### ISSUE TITLE
Support metadata generation

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1093]
Dedicating an issue to this topic. Originally part of #81 (huge thread).

**Comment by kennykerr** [comment]
Getting back to authoring (#1094) and metadata generation as originally described in #81 I'd like to support a `define` macro that would take the place of using MIDL and instead let you define your metadata directly in Rust as follows:

```rust
fn main() {
    define! {
        mod Microsoft {
            mod Windows {
                struct StructType { x: i32, y: i32 }

                interface IInterfaceType {
                    fn Method(&self) -> StructType;
                }

                class ClassType : IInterfaceType;
            }
        }
    }
}
```

The `define` macro would typically be called by a build script to generate the component or project's .`winmd` file to `OUT_DIR/project.winmd` and a corresponding set of Rust bindings for the implementation to use to `OUT_DIR/project.rs`. The project can then use that along with the `implement` macro to provide the implementation.

**Comment by Alovchin91** [comment]
MIDL 3.0 is pretty simple, very well documented and is rather powerful. Do you think it would make sense to support both ways of defining runtime classes (so also in an .idl file)?

**Comment by kennykerr** [comment]
MIDL also has a lot of problems. Of course, nothing prevents you from using MIDL if you prefer. Fundamentally, the winmd format is the canonical representation for metadata. How you get to that is up to you. I'm just working on a way to do it organically in Rust so that MIDL would not be required, but first I'm working out a few minor issues to make sure that developers can start using MIDL in the short term. Basically, the same issues you run into in your sample project and just making sure is streamlined.

**Comment by hmyan90** [comment]
Thanks, Kenny for putting this together and super helpful to provide a validated short-term solution. For MIDL define, personally I also don't mind defining it, it can particularly serve as a document purpose that can share with the team who will consume it, we can add notes/comments on it. But if we define in Rust macro, it's hard to share it with another team, I think. But sure we can choose the option!

**Comment by mominshaikhdevs** [comment]
@kennykerr is the work on the "complete metadata generator" aka "the riddle tool" complete yet? or is it in backlog?
