### ISSUE TITLE
yml build's `windows_fmt` cannot run in parallel

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1102]
...as it can cause other parallel tasks to fail. 

https://github.com/microsoft/windows-rs/pull/1101/checks?check_run_id=3466610127

@MarijnS95 @riverar

**Comment by MarijnS95** [comment]
@kennykerr This was partly why I had the "complicated" `read -> make modifications -> pipe through `rustfmt` -> undo renaming modifications -> write to disk` chain initially. It won't prevent against concurrent reads and writes in the last step, but at least it doesn't write the botched for-formatting-only `use format_build_macro::{` to disk anywhere, at any time.

**Comment by kennykerr** [comment]
Hmm, I reran the build and it doesn't save the failed run. Lame. Anyway, it failed two other builds because those builds picked up the transient `format_build_macro` replacement used by the `windows_fmt` tool.

**Comment by MarijnS95** [comment]
@kennykerr NP, I still have the tab open with the old logs:

```log
    Updating crates.io index
 Downloading crates ...
  Downloaded const-sha1 v0.2.0
  Downloaded proc-macro2 v1.0.29
  Downloaded syn v1.0.75
  Downloaded unicode-xid v0.2.2
  Downloaded quote v1.0.9
   Compiling proc-macro2 v1.0.29
   Compiling syn v1.0.75
   Compiling unicode-xid v0.2.2
   Compiling windows_reader v0.19.0 (D:\a\windows-rs\windows-rs\crates\reader)
   Compiling windows_quote v0.19.0 (D:\a\windows-rs\windows-rs\crates\quote)
   Compiling const-sha1 v0.2.0
    Checking windows_writer v0.19.0 (D:\a\windows-rs\windows-rs\crates\writer)
   Compiling windows_gen v0.19.0 (D:\a\windows-rs\windows-rs\crates\gen)
    Checking windows_fmt v0.0.0 (D:\a\windows-rs\windows-rs\crates\fmt)
   Compiling quote v1.0.9
    Checking windows_macros v0.19.0 (D:\a\windows-rs\windows-rs\crates\macros)
   Compiling windows v0.19.0 (D:\a\windows-rs\windows-rs)
    Checking windows_bindings v0.0.0 (D:\a\windows-rs\windows-rs\crates\bindings)
   Compiling test_winrt_simple v0.0.0 (D:\a\windows-rs\windows-rs\tests\winrt\simple)
   Compiling test_weak v0.0.0 (D:\a\windows-rs\windows-rs\tests\legacy\weak)
error[E0433]: failed to resolve: use of undeclared crate or module `format_build_macro`
 --> tests\legacy\weak\build.rs:2:9
  |
2 |     use format_build_macro::{
  |         ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `format_build_macro`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `test_weak`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Process completed with exit code 1.
```

**Comment by kennykerr** [comment]
Thanks! Perhaps there's a simple way we can run it before any other task or after all other tasks have completed to avoid complicating the tool itself.

**Comment by kennykerr** [comment]
But yes, otherwise doing it on a temp file might be more reliable.

**Comment by MarijnS95** [comment]
https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#creating-dependent-jobs Yes, you can use the `needs:` property to let other jobs wait on the formatting job, for example.

**Comment by MarijnS95** [comment]
> But yes, otherwise doing it on a temp file might be more reliable.

I personally find the pipe solution the easiest, it's the least round-trips to disk while only requiring a few more lines of code. That code already exists anyway, right before 171fe9fd0e67fb8e66a16b218df59ef321cb2ccd.

**Comment by kennykerr** [comment]
Thanks for looking, I may bring back something like that. 

Looks like in this case it was my fault. https://github.com/microsoft/windows-rs/pull/1101/commits/a3b5a71c25e32f60750262a6c1cf8367946e0f58

I'll keep an eye on it and whether we should make it more robust.

**Comment by MarijnS95** [comment]
> Thanks for looking, I may bring back something like that.
> 
> Looks like in this case it was my fault. [a3b5a71](https://github.com/microsoft/windows-rs/commit/a3b5a71c25e32f60750262a6c1cf8367946e0f58)

Did the formatter crash halfway through and leave the bogus file in place?

**Comment by kennykerr** [comment]
I don't think it crashed. It looks like I must have committed locally before it completed.
