### ISSUE TITLE
Issue with MouseMoved event

### ISSUE THREAD

**Issue by Furry** [microsoft/windows-rs#1106]
Hiya! I'm trying out some code to familiarize myself with the windows API in rust a bit, but ran into an issue. I wasn't able to find anything online about how to get past this, rather only found an occurrence of it in C#.

```rs
use bindings::Windows::Devices::Input::{MouseDevice, MouseEventArgs};
use bindings::Windows::Foundation::TypedEventHandler;

fn main() {
    let x = MouseDevice::GetForCurrentView().unwrap();
    x.MouseMoved(
        TypedEventHandler::new(|_sender, args: &Option<MouseEventArgs>| {
            let arg = args.clone().unwrap();
            let delta = arg.MouseDelta().unwrap();
            println!("X: {}, Y: {}", delta.X, delta.Y);
            Ok(())
        })
    ).unwrap();
}
```

This is throwing the error `{ code: 0x8000001D, message: "Activating a single-threaded class from MTA is not supported" }` on the unwrap statement for my x.MouseMoved function call. What am I doing wrong, or how should I better approach this?

**Comment by kennykerr** [comment]
I suspect that this API only works in the context of an app that uses the `Windows::UI::*` APIs to create a view (window). The error is perhaps a bit misleading because those UI APIs require that most calls are made on the STA that the UI framework created. By default, most apps start off either with no apartment or an MTA.

**Comment by riverar** [comment]
Re-opening this briefly as I'm checking right now if there's an interop helper for this particular path. Will follow up in a few moments.

Like Kenny said, generally anything with a `GetForCurrentView` will have an implicit dependency on `CoreWindow` which isn't available to non-"UWP" apps.

**Comment by riverar** [comment]
(Continued assumption: You are not running in a "UWP" context.)

Sadly `MouseDevice` doesn't have an interoperability helper for you to use this outside "UWP" scenarios. So you'll need deal with `WM_MOUSEMOVE` and friends directly, see https://docs.microsoft.com/en-us/windows/win32/learnwin32/module-4--user-input for additional guidance.

I'll file a bug on the Windows App SDK folks to get interop plumbing for the input types as it would be much nicer to use.
