### ISSUE TITLE
Delegates now generated with return bound to static lifetime, is that right?

### ISSUE THREAD

**Issue by riverar** [microsoft/windows-rs#1110]
My Rust lifetime foo is weak so be gentle.

[A recent change](https://github.com/microsoft/windows-rs/blob/master/crates/gen/src/delegate.rs#L161) was made to delegate generation; delegates now appear to be generated with a return that is bound to `'static` lifetime.

```rust
quote! { F: FnMut(#(#params),*) -> ::windows::Result<#return_sig> + 'static }
```

Is this right? If so, why?

This change appears to make it almost impossible to create a closure for things like `RoutedEventHandler` that reference, say, `self` with an implicit anonymous lifetime, e.g. consider:

```rust
fn OnLaunched(&mut self, _: &Option<LaunchActivatedEventArgs>) -> windows::Result<()> {
...
  button.Click(RoutedEventHandler::new(|sender, args| {
      self.ButtonClicked(...)
  }))?;
}
```

0.19 will err with ``error[E0759]: `self` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement``. Removing the explicit lifetime in delegate.rs (the line above) unblocks me, but I haven't fully thought through the implications here and would love another set of brains on it.

**Comment by kennykerr** [comment]
Was it not `static` before? I was consolidating a lot of similar code and may have overly restricted this case in the process. 

But the lifetime here is a bit tricky. The handler must capture either strong or weak references and `self` is neither. The delegate may outlive (in theory) the object surrounding `self`. In C++/WinRT I introduced the `make_weak` and `make_strong` helpers to turn `this` into something that can be carried along with a handler. We probably need something similar for Rust.

**Comment by Paul-Dempsey** [comment]
This issue is painfully limiting in the app I'm trying to write. I'm not a rust guru, so looking for a viable strategy to be able to &mut self in event handlers.

**Comment by riverar** [comment]
@Paul-Dempsey Here's a pattern I've used since my original issue:

```rust
struct App {
  _object: RefCell<Option<ObjectTypeFoo>>
  // ...
}

impl App {
  fn new() -> Self { _object: RefCell::new(None) }
  // ...
}

impl IFoo for App {
  fn OnLaunched(&self, ...) {
    *self._object.borrow_mut() // <-- Do something with mutable borrow here
  }
}

**Comment by Paul-Dempsey** [comment]
Thank you, River. A concrete example with TypedEventHandler that compiles would be more helpful (this code doesn't compile, and a bit abstract for a newbie). What's an ObjectTypeFoo? I'd love to see a version of the rust\windows-rs\crates\samples\device_watcher\ that shows how to reference self from the handler (e.g. dynamically maintain a list of devices by name as they are added and removed), rather than trivial context-free handlers that print something.

**Comment by MRahilly** [comment]
@Paul-Dempsey This version or core_app may be of use to you:

[package]
name = "blocks"
version = "0.0.0"
edition = "2021"

[dependencies]

[dependencies.windows]
version = "0.43"
features = [
    "implement",
    "ApplicationModel_Core",
    "UI_Core",
    "Win32_System_Com",
    "Foundation_Numerics",
    "UI_Composition",
    "Foundation",
    "UI_Input",
    "Foundation_Collections",
]

#![windows_subsystem = "windows"]

use windows::{
    core::{HSTRING, implement, Result},
    ApplicationModel::Core::{CoreApplication, CoreApplicationView, IFrameworkView, IFrameworkView_Impl, IFrameworkViewSource, IFrameworkViewSource_Impl},
    Foundation::{
        Numerics::{Vector2, Vector3},
        TypedEventHandler,
    },
    Win32::System::Com::{CoInitializeEx, COINIT_MULTITHREADED},
    UI::{
        Core::{CoreProcessEventsOption, CoreWindow, PointerEventArgs},
        Composition::{CompositionBrush, CompositionTarget, Compositor, Visual, VisualCollection},
        Color,
    },
};

use std::{
    ptr::null_mut,
    sync::{
        Arc,
        Mutex
    }
};

#[implement(IFrameworkViewSource)]
struct App();

#[allow(non_snake_case)]
impl IFrameworkViewSource_Impl for App {
    fn CreateView(&self) -> Result<IFrameworkView> {
        // TODO: need self query `self.into()` to support implementing both IFrameworkViewSource and IFrameworkView on the same object.
        Ok(AppView{
            m_view_state: Arc::new(Mutex::new(AppViewState {
                m_target: None,
                m_visuals: None,
                m_selected: None,
                m_offset: None,
                m_last: 0,
            })) }.into())
    }
}

#[implement(IFrameworkView)]
struct AppView {
    m_view_state: Arc<Mutex<AppViewState>>,
}

struct AppViewState {
    m_target: Option<CompositionTarget>,
    m_visuals: Option<VisualCollection>,
    m_selected: Option<Visual>,
    m_offset: Option<Vector2>,
    m_last: usize,
}

#[allow(non_snake_case)]
impl IFrameworkView_Impl for AppView {
    fn Initialize(&self, _: &Option<CoreApplicationView>) -> Result<()> {
        Ok(())
    }

    fn Load(&self, _: &HSTRING) -> Result<()> {
        Ok(())
    }

    fn Uninitialize(&self) -> Result<()> {
        Ok(())
    }

    fn Run(&self) -> Result<()> {
        let window = CoreWindow::GetForCurrentThread()?;
        window.Activate()?;

        let dispatcher = window.Dispatcher()?;
        dispatcher.ProcessEvents(CoreProcessEventsOption::ProcessUntilQuit)?;

        Ok(())
    }

    fn SetWindow(&self, window: &Option<CoreWindow>) -> Result<()> {
        let compositor = Compositor::new()?;
        let root = compositor.CreateContainerVisual()?;
        let target = compositor.CreateTargetForCurrentView()?;

        self.m_view_state.lock().unwrap().m_target = Some(target);

        self.m_view_state.lock().unwrap().m_target.as_ref().unwrap().SetRoot(&root)?;
        self.m_view_state.lock().unwrap().m_visuals = Some(root.Children()?);
        let view_state = Arc::clone(&self.m_view_state);
        window.as_ref().unwrap().PointerPressed(&TypedEventHandler::<CoreWindow, PointerEventArgs>::new(move |_, args|
            {
                let args = args.as_ref().unwrap();
                let currentpoint = args.CurrentPoint().unwrap();
                let point = currentpoint.Position().unwrap();

                let mut view_state = view_state.lock().unwrap();
                let visuals = view_state.m_visuals.as_ref().unwrap();
                
                let mut visual: Visual;
                let mut offset: Vector3;
                let mut size: Vector2;
                let iter = visuals.First().unwrap();
                while iter.HasCurrent().unwrap() {
                    visual = iter.Current().unwrap();
                    offset = visual.Offset().unwrap();
                    size = visual.Size().unwrap();

                    if point.X >= offset.X && point.X < offset.X + size.X && point.Y >= offset.Y && point.Y < offset.Y + size.Y {
                        view_state.m_selected = Some(visual);
                        view_state.m_offset = Some(Vector2 { X: offset.X - point.X, Y: offset.Y - point.Y });
                    }
                    iter.MoveNext()?;
                }

                if view_state.m_selected != None {
                    let selected = view_state.m_selected.as_ref().unwrap();
                    let visuals = view_state.m_visuals.as_ref().unwrap();
                    visuals.Remove(selected)?;
                    visuals.InsertAtTop(selected)?;
                } else {
                    let visuals = view_state.m_visuals.as_ref().unwrap();
                    let compositor = visuals.Compositor()?;
                    let visual = compositor.CreateSpriteVisual()?;

                    static COLORS: [Color; 4] = [
                        Color { A: 0xDC, R: 0x5B, G: 0x9B, B: 0xD5 },
                        Color { A: 0xDC, R: 0xED, G: 0x7D, B: 0x31 },
                        Color { A: 0xDC, R: 0x70, G: 0xAD, B: 0x47 },
                        Color { A: 0xDC, R: 0xFF, G: 0xC0, B: 0x00 },
                    ];

                    view_state.m_last = view_state.m_last + 1;
                    let next: usize = view_state.m_last % 4;
                    visual.SetBrush(&CompositionBrush::from(compositor.CreateColorBrushWithColor(COLORS[next])?))?;

                    const BLOCK_SIZE: f32 = 100.0;

                    visual.SetSize(
                        Vector2 {
                            X: BLOCK_SIZE,
                            Y: BLOCK_SIZE,
                        }
                    )?;

                    visual.SetOffset(
                        Vector3 {
                            X: point.X - BLOCK_SIZE / 2.0,
                            Y: point.Y - BLOCK_SIZE / 2.0,
                            Z: 0.0,
                        }
                    )?;

                    let visuals = view_state.m_visuals.as_ref().unwrap();
                    visuals.InsertAtTop(&visual)?;

                    let visual = visual.clone();
                    view_state.m_selected = Some(Visual::from(visual));

                    view_state.m_offset = Some(Vector2 {
                        X: -BLOCK_SIZE / 2.0,
                        Y: -BLOCK_SIZE / 2.0,
                    });
                }

                Ok(())
            }
        ))?;

        let view_state_arc = Arc::clone(&self.m_view_state);
        window.as_ref().unwrap().PointerMoved(&TypedEventHandler::<CoreWindow, PointerEventArgs>::new(move |_, args|
            {
                let view_state = view_state_arc.lock().unwrap();
                if view_state.m_selected != None {
                    let args = args.as_ref().unwrap();
                    let currentpoint = args.CurrentPoint().unwrap();
                    let point = currentpoint.Position().unwrap();

                    let selected = view_state.m_selected.as_ref().unwrap();
                    selected.SetOffset(
                        Vector3 {
                            X: point.X + view_state.m_offset.unwrap().X,
                            Y: point.Y + view_state.m_offset.unwrap().Y,
                            Z: 0.0,
                        }
                    )?;
                }

                Ok(())
            }
        ))?;

        let view_state_arc = Arc::clone(&self.m_view_state);
        window.as_ref().unwrap().PointerReleased(&TypedEventHandler::<CoreWindow, PointerEventArgs>::new(move |_, _|
            {
                let mut view_state = view_state_arc.lock().unwrap();
                view_state.m_selected = None;

                Ok(())
            }
        ))?;

        Ok(())
    }
}

fn main() -> Result<()> {
    unsafe {
        CoInitializeEx(Some(null_mut()), COINIT_MULTITHREADED)?;
    }

    let app: IFrameworkViewSource = App().into();
    CoreApplication::Run(&app)?;

    Ok(())
}

**Comment by riverar** [comment]
Closing as the patterns really do help you write better multithreaded COM code (https://github.com/microsoft/windows-rs/issues/2304#issuecomment-1402679783).

@Paul-Dempsey Here's the sample you requested. I suspect there are several other Rust idiomatic approaches you can probably take here.

```rust
use std::sync::{Arc, Mutex};
use windows::{Devices::Enumeration::DeviceInformation, Foundation::TypedEventHandler};

fn main() -> windows::core::Result<()> {
    let state = Arc::new(Mutex::from(0));

    let clone = state.clone();
    let watcher = DeviceInformation::CreateWatcher()?;
    watcher.Added(&TypedEventHandler::new(move |_, _info| {
        let mut state = clone.lock().unwrap();
        *state += 1;
        Ok(())
    }))?;
    watcher.Start()?;

    std::thread::sleep(std::time::Duration::new(3, 0));
    println!("Devices added: {}", state.lock().unwrap());

    Ok(())
}

```
