### ISSUE TITLE
D2D `ID2D1SolidColorBrush` does not implement `IntoParam<'_,ID2D1Brush>`

### ISSUE THREAD

**Issue by JCBurnside** [microsoft/windows-rs#1111]
So I am trying to create a simple D2D window and fill a rect with a black solid color brush following [this tutorial](https://docs.microsoft.com/en-us/windows/win32/direct2d/getting-started-with-direct2d). Well I get to step 5 and they do 
```cpp
pRT->BeginDraw();

pRT->DrawRectangle(
    D2D1::RectF(
        rc.left + 100.0f,
        rc.top + 100.0f,
        rc.right - 100.0f,
        rc.bottom - 100.0f),
        pBlackBrush);

HRESULT hr = pRT->EndDraw();  
```
 and translating that to rust and adding the optional params gives me
 ```rs
let rt = factory.as_ref().unwrap().CreateHwndRenderTarget(&renderProps, &hwndRenderProps).expect("Couldn't create the render target");
            let black = D2D1_COLOR_F { r:0.0, g:0.0, b:0.0, a:1.0 };
            let black_brush = rt.CreateSolidColorBrush(&black,std::ptr::null()).expect("Failed to create Brush");
            rt.BeginDraw();
            let target = D2D_RECT_F {
                left : (rc.left + 100) as f32,
                top : (rc.top + 100) as f32,
                right : (rc.right - 100) as f32,
                bottom : (rc.bottom - 100) as f32,
            }; 
            rt.DrawRectangle(&target as *const _, &black_brush, 10.00, None);
            rt.EndDraw(std::ptr::null_mut(), std::ptr::null_mut()).expect("what?");
```
however when i go to compile it results in this message from cargo
```
error[E0277]: the trait bound `&ID2D1SolidColorBrush: IntoParam<'_, ID2D1Brush>` is not satisfied
  --> rui_windows_rendering_engine\src\lib.rs:60:16
   |
60 |             rt.DrawRectangle(&target as *const _, &black_brush, 10.00, None);
   |                ^^^^^^^^^^^^^ the trait `IntoParam<'_, ID2D1Brush>` is not implemented for `&ID2D1SolidColorBrush`

For more information about this error, try `rustc --explain E0277`.
```
 attached is full code
[lib.txt](https://github.com/microsoft/windows-rs/files/7110030/lib.txt)

**Comment by JCBurnside** [comment]
The docs even state it should be implemented [here](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Graphics/Direct2D/struct.ID2D1SolidColorBrush.html#impl-IntoParam%3C%27a%2C%20ID2D1Brush%3E)

**Comment by riverar** [comment]
No compilation errors on my end. Are you using the latest `windows` crate? If you keep having trouble, please provide a fully compliable crate (e.g. a sample repository on GitHub). Thanks!

**Comment by JCBurnside** [comment]
Interestingly it seems to have resolved itself.  not sure what the issue was but it is now working properly.
