### ISSUE TITLE
ID2D1Factory::CreateHwndRenderTarget never returns.

### ISSUE THREAD

**Issue by JCBurnside** [microsoft/windows-rs#1112]
I am simply trying to create an ID2D1HwndRenderTarget using [this function](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Graphics/Direct2D/struct.ID2D1Factory.html#method.CreateHwndRenderTarget) but it never returns and the process exits with code `0xc000041d`.  However it never returns the Result.  I have tested with [this repo](https://github.com/JCBurnside/RustWindowsD3DErrorSample).

**Comment by kennykerr** [comment]
I have not used this particular function from Rust but I wrote a fairly comprehensive Direct2D sample here:

https://github.com/microsoft/windows-samples-rs/tree/master/direct2d

Generally, the DirectX APIs don't report meaningful errors programmatically but you can turn on debug modes for both Direct2D and Direct3D to get richer error information when a debugger is attached. The sample above illustrates how to set up `D2D1_DEBUG_LEVEL_INFORMATION` and `D3D11_CREATE_DEVICE_DEBUG` for this purpose. Following that, running the code within a debugger should trace out more information about how you might be using various APIs incorrectly.

**Comment by kennykerr** [comment]
I also have a few articles and courses that cover how to use Direct2D (including this function):

https://kennykerr.ca/articles/
https://kennykerr.ca/courses/

**Comment by JCBurnside** [comment]
I am sorry but I was following and translating from c++ to rust this:

https://docs.microsoft.com/en-us/windows/win32/direct2d/getting-started-with-direct2d

Regardless there is still a bug here in the fact it returns a result. So I expect if there is an error it would return Err but instead throws.  And running after enabling the `D2D1_DEBUG_LEVEL_INFORMATION` gives me `Exception thrown at 0x00007FF71F4327BB in WindowsD2DErrorSample.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF` which is still not helpful.

**Comment by JCBurnside** [comment]
I should add it throws that on `(::windows::Interface::vtable(self).14)(` inside the windows crate.

**Comment by kennykerr** [comment]
> Regardless there is still a bug here in the fact it returns a result

Perhaps, but whether the bug is in your code, the Windows crate, or Direct2D itself is something you'll need to discover.

**Comment by JCBurnside** [comment]
as I pointed out it is in fact inside the windows-rs crate.  I ran my simple app with the debugger attached and it crashes on 
```rs
(::windows::Interface::vtable(self).14)(
                            ::windows::Abi::abi(self),
                            ::std::mem::transmute(rendertargetproperties),
                            ::std::mem::transmute(hwndrendertargetproperties),
                            &mut result__,
                        )
                        .from_abi::<ID2D1HwndRenderTarget>(result__)
```
which is an windows-rs internal. If I could point to a specific line I would but it appears to be in a generated file.

**Comment by JCBurnside** [comment]
And still by returning a `Result` I expect the code to not panic or throw but instead return `Err` if it was called incorrectly.  Instead it throws an Access violation which makes it appear as though the vtable is not being populated correctly.

**Comment by kennykerr** [comment]
Thanks I'll see if I can track it down when I get a moment.

**Comment by JCBurnside** [comment]
Small update.  Tracked it down to how i was creating my factory.  
```rs
let mut factory : Option<ID2D1Factory> =None;
            let options = {
                let mut options = D2D1_FACTORY_OPTIONS::default();
                options.debugLevel = D2D1_DEBUG_LEVEL_INFORMATION;
                options
            };
            let factory = D2D1CreateFactory(
                D2D1_FACTORY_TYPE_SINGLE_THREADED,
                &ID2D1Factory::IID,
                &options,
                factory.set_abi(),
            ).map(|()| factory.unwrap());
```
ended up fixing the issue.  So the factory believed it was in a valid state when it wasn't.  this is why I dislike `void*`

**Comment by kennykerr** [comment]
Yep, unfortunately this function doesn't follow the normal convention of providing a trailing `GUID*,void**` pair otherwise the Windows crate would have turned that into a generic function that would be much safer to use.

**Comment by riverar** [comment]
Closing, doesn't sound like there's a crate issue here. Feel free to re-open if that's not the case.
