### ISSUE TITLE
SERVICE_NOTIFY consts missing

### ISSUE THREAD

**Issue by cherryleafroad** [microsoft/windows-rs#1113]
Hello,

I'm trying to use some [`SERVICE_NOTIFY`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Services/struct.SERVICE_NOTIFY.html) constants such as `SERVICE_NOTIFY_CREATED`, and `SERVICE_NOTIFY_DELETED` listed [here](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-notifyservicestatuschangea) in MSDocs.

As `SERVICE_NOTIFY` is listed as  type `struct SERVICE_NOTIFY(pub u32)`, and [`SERVICE_NOTIFY_DELETED`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Services/constant.SERVICE_NOTIFY_DELETED.html) is listed as `SERVICE_NOTIFY_DELETED: SERVICE_NOTIFY` under `bindings::Windows::Win32::System::Services::SERVICE_NOTIFY_DELETED`, I'd expect the following code to work, but for some reason they are not found

```Rust
fn main() {
    windows::build!(
        Windows::Win32::{
            System::Services::{
                SERVICE_NOTIFY_CREATED,
                SERVICE_NOTIFY_DELETED
            }
        }
    );
}
```

**Comment by riverar** [comment]
`SERVICE_NOTIFY_CREATED`, etc. are value types defined in the `SERVICE_NOTIFY` enumeration.

From the metadata:
```csharp
[Flags]
public enum SERVICE_NOTIFY : uint
{
	SERVICE_NOTIFY_CREATED = 0x80u,
	SERVICE_NOTIFY_CONTINUE_PENDING = 0x10u,
	SERVICE_NOTIFY_DELETE_PENDING = 0x200u,
	SERVICE_NOTIFY_DELETED = 0x100u,
	SERVICE_NOTIFY_PAUSE_PENDING = 0x20u,
	SERVICE_NOTIFY_PAUSED = 0x40u,
	SERVICE_NOTIFY_RUNNING = 0x8u,
	SERVICE_NOTIFY_START_PENDING = 0x2u,
	SERVICE_NOTIFY_STOP_PENDING = 0x4u,
	SERVICE_NOTIFY_STOPPED = 0x1u
}
```

So you want to bring in the enum `SERVICE_NOTIFY`.

```rust
    windows::build!(
        Windows::Win32::System::Services::SERVICE_NOTIFY
    );
```

**Comment by cherryleafroad** [comment]
I originally tried to pull in `SERVICE_NOTIFY` and access it as an enum `SERVICE_NOTIFY::SERVICE_NOTIFY_CREATED`, but I get this error 
` no associated item named `SERVICE_NOTIFY_DELETED` found for struct `SERVICE_NOTIFY``

Am I doing it wrong?

**Comment by riverar** [comment]
Sorry for the confusion, this is definitely a confusing area.

These constants are defined as enum members of the `SERVICE_NOTIFY` enum _in the Windows Metadata_. It looks like this:
```csharp
[Flags]
public enum SERVICE_NOTIFY : uint
{
	SERVICE_NOTIFY_CREATED = 0x80u,
	SERVICE_NOTIFY_CONTINUE_PENDING = 0x10u,
	SERVICE_NOTIFY_DELETE_PENDING = 0x200u,
	SERVICE_NOTIFY_DELETED = 0x100u,
	SERVICE_NOTIFY_PAUSE_PENDING = 0x20u,
	SERVICE_NOTIFY_PAUSED = 0x40u,
	SERVICE_NOTIFY_RUNNING = 0x8u,
	SERVICE_NOTIFY_START_PENDING = 0x2u,
	SERVICE_NOTIFY_STOP_PENDING = 0x4u,
	SERVICE_NOTIFY_STOPPED = 0x1u
}
```

The `windows` creates a corresponding struct and creates constant instances of said struct for each member. In other words, it spits out:

```rust
pub struct SERVICE_NOTIFY(pub u32);
pub const SERVICE_NOTIFY_CREATED: SERVICE_NOTIFY = SERVICE_NOTIFY(128u32);
pub const SERVICE_NOTIFY_CONTINUE_PENDING: SERVICE_NOTIFY = SERVICE_NOTIFY(16u32);
pub const SERVICE_NOTIFY_DELETE_PENDING: SERVICE_NOTIFY = SERVICE_NOTIFY(512u32);
pub const SERVICE_NOTIFY_DELETED: SERVICE_NOTIFY = SERVICE_NOTIFY(256u32);
pub const SERVICE_NOTIFY_PAUSE_PENDING: SERVICE_NOTIFY = SERVICE_NOTIFY(32u32);
pub const SERVICE_NOTIFY_PAUSED: SERVICE_NOTIFY = SERVICE_NOTIFY(64u32);
pub const SERVICE_NOTIFY_RUNNING: SERVICE_NOTIFY = SERVICE_NOTIFY(8u32);
pub const SERVICE_NOTIFY_START_PENDING: SERVICE_NOTIFY = SERVICE_NOTIFY(2u32);
pub const SERVICE_NOTIFY_STOP_PENDING: SERVICE_NOTIFY = SERVICE_NOTIFY(4u32);
pub const SERVICE_NOTIFY_STOPPED: SERVICE_NOTIFY = SERVICE_NOTIFY(1u32);
```

So the workflow is:
  1. Tell `windows::build!` that you want to bring in the `SERVICE_NOTIFY` enumeration _as defined in Windows Metadata_:
      ```rust
      windows::build!(
          Windows::Win32::System::Services::SERVICE_NOTIFY
      );
      ```
  
  2. Use the newly created constant items in your code:
      ```rust
      #[test]
      fn sample() {
          let x = bindings::Windows::Win32::System::Services::SERVICE_NOTIFY_CREATED;
          assert!(x.0 == 0x80);
      }
      ```

Hope that helps!

**Comment by cherryleafroad** [comment]
Ahhh, after seeing that output, it makes sense now what's happening. Thanks for the clarification!

A quick question, but is there a way I can see the bindings generated output so that I can avoid such a simple problem later on? Since these are bindings, there's no intellisense code completion, and no source code to refer to. I saw an issue somewhere else on here to use the doc generator for completions, but it seems a ways off for now.

**Comment by riverar** [comment]
@cherryleafroad What I do is open `target\debug\build\bindings-xxxxx\out\windows.rs` in a tab. It _should_ remain stable between incremental builds (and refresh automatically, if your IDE supports that) until a `cargo clean` is performed.

**Comment by cherryleafroad** [comment]
Thanks for your patience! :smile: That should be sufficient for now until we get completions :blush:
