### ISSUE TITLE
Having trouble getting started with Process Threads API

### ISSUE THREAD

**Issue by mries92** [microsoft/windows-rs#1123]
Hello, I am just starting out and trying to make some calls to `Processthreadsapi.h`, but no matter what I do I can't seem to use this portion of the API. I have tried various names. I'm not exactly clear on how to find the exact "path" I need to specify.

build.rs
```rs
fn main() {
  tauri_build::build();
  windows::build! {
    // same as below
  };
}
```
main.rs
```rs
mod bindings {
  windows::include_bindings!();
}

use bindings::{
  Windows::Win32::System::{OpenProcess},                              // Neither of these work =[
  Windows::Win32::ProcessThreadsApi::{OpenProcess},
};
```

Thanks in advance for any help!

**Comment by kennykerr** [comment]
Close. 😉 

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Threading/fn.OpenProcess.html

**Comment by mries92** [comment]
Ohh I see now thank you! I was browsing the documentation [here](https://docs.rs/windows/0.19.0/windows/), but I see the updated links on the github readme.
