### ISSUE TITLE
Exporting AddRef/Release for manual reference count management.

### ISSUE THREAD

**Issue by agausmann** [microsoft/windows-rs#1125]
There are some APIs that require manually managing reference counts. For example, [`IMMDeviceEnumerator::{Un}RegisterEndpointNotificationCallback`](https://docs.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immdeviceenumerator-registerendpointnotificationcallback) requires the caller to manage the reference count of the `IMMNotificationClient` it receives:

> The client is responsible for maintaining the reference count of the **IMMNotificationClient** object. The client must increment the count if the **RegisterEndpointNotificationCallback** call succeeds and release the final reference only after calling **UnregisterEndpointNotificationCallback** or implement some other mechanism to ensure that the object is not deleted before **UnregisterEndpointNotificationCallback** is called.

But because AddRef/Release don't seem to be made public in the `windows-rs` API, that is difficult to do correctly.

Ideally, I would want code that looked something like this:

```rust
let notifier = IMMNotificationClient::from(MyNotifier::new(/* ... */));
unsafe { device_enumerator.RegisterEndpointNotificationCallback(&notifier)? };
// Reference count is not automatically updated on success:
unsafe {
    notifier.AddRef()?;
    // or, if IUnknown methods can not be made available on every interface type,
    // at least make them available on IUnknown:
    // notifier.cast::<IUnknown>()?.AddRef()?;
}
```

But there is no `IUnknown::AddRef` to be found anywhere.

There are a couple of workarounds to manually call `AddRef`, my favorite option is using `forget`: (though in the past, I also directly constructed `MyNotifier_box` and used its associated `AddRef` method)

```rust
std::mem::forget(notifier.clone());
```

 But using these ways, there is still no trivial way to safely call `Release` later. Maybe one way (though unsafe and somewhat dubious) is to make and drop a copy of the pointer when unregistering:
```rust
let notifier: IMMNotificationClient = /* ... */;
unsafe { device_enumerator.UnregisterEndpointNotificationCallback(&notifier)? };
// Reference count is not automatically updated:
let copy = unsafe { ((&notifier) as *const IMMNotificationClient).read() };
std::mem::drop(copy);
```

**Comment by kennykerr** [comment]
That just means that the API will not keep the object alive so that's your job. As long as you don't drop it there should be a valid reference. If you ever need to artificially bump the reference count you can also clone the object. But there's rarely any need to call AddRef/Release directly.

**Comment by agausmann** [comment]
That makes sense. I was stuck in the mindset of "I'm giving ownership of this object to (or sharing ownership with) the COM runtime." The idea was that I could drop my own reference and let the callback run in the background, since I never wanted/needed to explicitly unregister the callback. (Which is fine for most other callback interfaces in Core Audio, like `IAudioEndpointVolumeCallback`, `IAudioSessionNotification`, and `IAudioSessionEvents`)

**Comment by agausmann** [comment]
Looking more closely at `IAudioSessionEvents`, it looks like the COM runtime will never implicitly release those callbacks, though I assumed it would whenever the related audio session is disconnected. So that is a mistake on my end.

(Reference: [`IAudioSessionControl::RegisterAudioSessionNotification`](https://docs.microsoft.com/en-us/windows/win32/api/audiopolicy/nf-audiopolicy-iaudiosessioncontrol-registeraudiosessionnotification))

> Before the client releases its final reference to the **IAudioSessionEvents** interface, it should call **UnregisterAudioSessionNotification** to unregister the interface. Otherwise, the application leaks the resources held by the **IAudioSessionEvents** and **IAudioSessionControl** objects. ... If the client errs by releasing its reference to the **IAudioSessionEvents** interface before calling **UnregisterAudioSessionNotification**, the session manager never releases its reference to the **IAudioSessionEvents** interface
