### ISSUE TITLE
Windows-rs panics when calling an unsupported method.

### ISSUE THREAD

**Issue by roblabla** [microsoft/windows-rs#1140]
Currently, when calling methods, windows-rs generates code such as this one:

```rust
mod Windows {
    // ...
    mod ApplicationModel {
        // ...
        impl Package {
            // ...
            pub fn InstalledPath(&self) -> ::windows::Result<::windows::HSTRING> {
                let this = &::windows::Interface::cast::<IPackage8>(self).unwrap();
                unsafe {
                    let mut result__: <::windows::HSTRING as ::windows::Abi>::Abi =
                        ::std::mem::zeroed();
                    (::windows::Interface::vtable(this).9)(::windows::Abi::abi(this), &mut result__)
                        .from_abi::<::windows::HSTRING>(result__)
                }
            }
        }
    }
}
```

The `Package::InstalledPath` function, however, is only available on windows 10 Build 19041, Build 20348, Build 22000 (Preview). Executing the InstalledPath method on a lower version of windows will cause the thread to panic with 

`panicked at 'called Result::unwrap() on an Err value: Error { code: 0x80004002, message: "No such interface supported" }', /ramdisk/target/x86_64-pc-windows-msvc/release/build/windows-bindings-2ba1babb4d4d9d13/out/windows.rs:5369:75
`

Why is the cast's error not getting bubbled up? The errors are compatible as far as I can tell.

**Comment by kennykerr** [comment]
Indeed, I need to make that recoverable. I'll get that fixed.

**Comment by kennykerr** [comment]
The Windows crate unwraps in various places partly because `TryFrom` and `TryInto` weren't stable when I started this project. Now that they are, I can get rid of most/all of that.

**Comment by riverar** [comment]
Think we should also file an issue on metadata; the interface should really have a supported OS attribute. Although, I don't think we read that yet in the crate.

**Comment by kennykerr** [comment]
This is WinRT metadata, which uses contract versioning. There are attributes in the metadata for this, but the most practical way to handle that is via feature detection e.g. cast/query to determine whether the feature is supported, hence the desire for `Result<T>` to bubble up the failure.
