### ISSUE TITLE
[Question/Bug?] My HwndRenderTarget won't draw a rectangle. 

### ISSUE THREAD

**Issue by JCBurnside** [microsoft/windows-rs#1150]
so I have [this project](https://github.com/JCBurnside/D2DExperiments/) but for some reason the `target.DrawRectangle(&rect, self.brush.as_ref().unwrap(), 1000.0, None);` won't draw a rectangle.  I can confirm d2d is infact working as the clear call does in fact set the window to the color I selected.

**Comment by riverar** [comment]
@JCBurnside Your call to `CreateSolidColorBrush` is passing in a zero-initialized `D2D1_BRUSH_PROPERTIES` which means its `opacity` member is set to `0.0f`.

```diff
pub fn create_brush(target: &ID2D1HwndRenderTarget) -> windows::Result<ID2D1SolidColorBrush> 
+   let props = D2D1_BRUSH_PROPERTIES { opacity:1.0, transform:Matrix3x2::default() };
-   unsafe { target.CreateSolidColorBrush(&Color::RGB(0.0, 1.0, 0.0).into(), &Default::default()) }
+   unsafe { target.CreateSolidColorBrush(&Color::RGBA(0.0, 1.0, 0.0, 1.0).into(), &props) }
}
```

Hope that helps.

**Comment by JCBurnside** [comment]
I see. Thank you!  I think what threw me off was there was no equalivent call this the `CreateSolidColorBrush(D2D1_COLOR_F,ID2D1SolidColorBrush **)` overload doesn't use a zero init one.
