### ISSUE TITLE
ver.0.20.0 missing virtual key code definitions

### ISSUE THREAD

**Issue by ZCWorks** [microsoft/windows-rs#1152]
ver.0.20.0 missing virtual key code (VK_*) definitions
(btw api document has them)

**Comment by riverar** [comment]
VK_* are loose constants in the `Windows.Win32.UI.WindowsAndMessaging` namespace. (You'll see them also referred to as unscoped enum values.)

So to import these, use:
```rust
windows::build! {
    // ...
    Windows::Win32::UI::WindowsAndMessaging::*,
};
```

```rust
#[test]
fn issue_1152() {
    assert_eq!(WindowsAndMessaging::VK_PLAY, 250u32);
}
```

**Comment by kennykerr** [comment]
If you want all the constants without importing the entire namespace you can also import the type of the constant e.g. `VIRTUAL_KEY`.

**Comment by tim-weis** [comment]
It looks like the constants [have moved](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/UI/KeyboardAndMouseInput/constant.VK_PLAY.html) into the `Windows.Win32.UI.KeyboardAndMouseInput` namespace.

**Comment by kennykerr** [comment]
Right, the win32 metadata was updated as part of the 0.20.0 release.
