### ISSUE TITLE
Window title displays incorrectly when using CreateWindowExW

### ISSUE THREAD

**Issue by MrGibus** [microsoft/windows-rs#1153]
## General
- Versions tested: 0.19, 0.20, and current repo state
- Platform: Windows 10 Pro
- Reproduceable code: [repo](https://github.com/MrGibus/windows-rs-issue)

## Issue
Passing a &str or String into ```CreateWindowExW()``` ->  ```lpWindowName``` field in general window creation results in the window title only displaying the first character.

Conversely when the same is performed with ```CreateWindowExA()``` the window title appears as expected.

**Comment by riverar** [comment]
You're passing everything through an ANSI DefWindowProc:

```diff
unsafe {
    match message as u32 {
        // ...
-        _ => DefWindowProcA(window, message, wparam, lparam),
+        _ => DefWindowProcW(window, message, wparam, lparam),
    }
}
```

Easy fix, hope that helps!
