### ISSUE TITLE
ver 0.20.0 removed set_abi on Option?

### ISSUE THREAD

**Issue by JCBurnside** [microsoft/windows-rs#1154]
this segment previously worked and no longer does?
```rs
let mut result : Option<ID2D1Factory1> = None;
    unsafe {
        D2D1CreateFactory(
            D2D1_FACTORY_TYPE_SINGLE_THREADED,
            &ID2D1Factory1::IID,
            &options,
            result.set_abi(),
        )
        .map(move |()| result.unwrap())
    }
```

**Comment by kennykerr** [comment]
I've update the samples to use version 0.20.0 and they provide examples of this. In particular, `set_abi` was just hiding an unsafe transmute operation so I removed that in favor of letting the caller be explicit about this operation.

https://github.com/microsoft/windows-samples-rs/blob/54ec3b27687fcf8426a023538b37aa77d62cff48/direct2d/src/main.rs#L514-L524

I hope to still find a way to make this call not require unsafe casts, but that's something I'm still noodling on.

**Comment by JCBurnside** [comment]
I see.

**Comment by JCBurnside** [comment]
the transmute isn't even necessary.
```rs
let mut result: Option<ID2D1Factory1> = None;
    unsafe {
        D2D1CreateFactory(
            D2D1_FACTORY_TYPE_SINGLE_THREADED,
            &ID2D1Factory1::IID,
            &options,
            &mut result as *mut _ as *mut *mut _,
        )
        .map(move |()| result.unwrap())
    }
    ``` this works just as well
