### ISSUE TITLE
WebView2 crashes on v0.20.0

### ISSUE THREAD

**Issue by lujjjh** [microsoft/windows-rs#1155]
Reproducible repository: https://github.com/microsoft/windows-samples-rs/tree/master/webview2_win32
OS: Windows 10

```
> cargo run
...
error: process didn't exit successfully: `target\debug\sample.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

I did a bisect and found this was caused by e53eeeae091f6e55ac93ded162b7fb616.

Callstack:

```
[0x0]   sample!windows::interfaces::unknown::impl$1::clone + 0x3f   
[0x1]   sample!bindings::Microsoft::Web::WebView2::Win32::impl$1100::clone + 0x13   
[0x2]   sample!core::option::impl$10::clone<bindings::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment> + 0x3c   
[0x3]   sample!sample::callback::impl$7::convert<bindings::Microsoft::Web::WebView2::Win32::ICoreWebView2Environment> + 0xe   
[0x4]   sample!sample::callback::CreateCoreWebView2EnvironmentCompletedHandler::Invoke + 0xb0   
...
```

**Comment by kennykerr** [comment]
Seems to be crashing in the callback generators. @wravery any ideas?

**Comment by wravery** [comment]
I just started looking into that last night (in another repo). Something is wrong with the `Option<ICoreWebView2Environment>` parameter, when it calls `IUnknown::clone()` it gets this access violation. It's not null, so that's not the problem.

**Comment by kennykerr** [comment]
I think it has to do with a faulty assumption the `InvokeArg` makes about the signature of input parameters. For interfaces, it should be `Option<&T>` rather than `&Option<T>`.

**Comment by kennykerr** [comment]
The bigger problem is that the `implement` macro transmutes the arguments without any type checking where this should be a compiler error instead of a run time error - that's what I plan to address.

**Comment by wravery** [comment]
> I think it has to do with a faulty assumption the `InvokeArg` makes about the signature of input parameters. For interfaces, it should be `Option<&T>` rather than `&Option<T>`. This admittedly is not very well baked and I'm planning to write a few tests for this next.

I tried `Option<&T>`, it looks like it crashes in the same place.

**Comment by wravery** [comment]
Not sure if this is accurate, but I tried `cargo-expand`, and it says that it's trying to transmute a `RawPtr`, not a strongly typed interface:

```rust
        unsafe extern "system" fn abi1(
            this: ::windows::RawPtr,
            errorcode: ::windows::HRESULT,
            createdenvironment: ::windows::RawPtr,
        ) -> ::windows::HRESULT {
            let this = (this as *mut ::windows::RawPtr).sub(2 + 0usize) as *mut Self;
            (*this)
                .implementation
                .Invoke(
                    ::std::mem::transmute_copy(&errorcode),
                    ::std::mem::transmute_copy(&createdenvironment),
                )
                .into()
        }
```

**Comment by riverar** [comment]
Looking in a debugger, appears we lost a layer of pointer indirection somewhere, perhaps on that _this_ parameter when we went from `::windows::Abi::abi(self)` to `::std::mem::transmute_copy(self)`, so `vtable()` ends up dereferencing one too many times.

**Comment by wravery** [comment]
> Not sure if this is accurate, but I tried `cargo-expand`, and it says that it's trying to transmute a `RawPtr`, not a strongly typed interface:

The previous version also takes a `RawPtr`, but instead of the transmute it has a cast chain to stronger `Abi` types ending with a `.into()` which apparently would do the trick.

**Comment by kennykerr** [comment]
The webview2_win32 sample has now been fixed. https://github.com/microsoft/windows-samples-rs/pull/32
