### ISSUE TITLE
CLSID_ShellLink missing

### ISSUE THREAD

**Issue by jacob-pro** [microsoft/windows-rs#1157]
I haven't been able to find a definition for `CLSID_ShellLink`, although there do seem to be many other CLSIDs in the crate:

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/?search=CLSID_

By defining it myself I was able to get `CoCreateInstance` to work (values from https://github.com/retep998/winapi-rs/issues/986#issuecomment-818749293):

```
const CLSID_SHELLLINK: Guid = Guid::from_values(
    0x00021401,
    0x0000,
    0x0000,
    [0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46],
);
```

But it would be good to have the definition in this crate?

**Comment by kennykerr** [comment]
It appears to exist here: 

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/UI/Shell/constant.ShellLink.html

**Comment by jacob-pro** [comment]
Ah I see - yeah that's the right one, sorry that I missed it!
