### ISSUE TITLE
Missing `Windows::Win32::System::SystemServices::LARGE_INTEGER` union

### ISSUE THREAD

**Issue by sabbyX** [microsoft/windows-rs#1158]
It seems windows-rs is not generating `LARGE_INTEGER` union. Cant find em in [docs](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/SystemServices/index.html#unions) neither able to generate it.

Although it's present in Windows.Win32.winmd:
![image](https://user-images.githubusercontent.com/61574665/133959960-172a601f-5292-44ff-973d-25e0da835358.png)

**Comment by kennykerr** [comment]
These types are replaced with `i64` and `u64` in the Rust bindings.

https://github.com/microsoft/windows-rs/blob/298d078d9026232a100999e06497d652570f6327/crates/reader/src/type_reader.rs#L338-L339
