### ISSUE TITLE
0.20.0 removed `PSTR::NULL`

### ISSUE THREAD

**Issue by roblabla** [microsoft/windows-rs#1159]
The latest version of windows-rs removed the `PSTR::NULL`, among others. I believe they were removed as part of the move towards a better api for `HANDLE` types, but `PSTR` is not a handle! As a result, the only way to null-check a `PSTR` is through a tuple access, e.g. `s.0.is_null()`. It'd be nice to restore the `PSTR::NULL` const (and `PWSTR::NULL`) to re-enable ergonomic null-checking - or alternatively, provide `is_null` function on those types.

**Comment by kennykerr** [comment]
The metadata puts types like `PSTR` in the same category as `HANDLE` but I agree that this isn't very meaningful. After [porting the samples to 0.20](https://github.com/microsoft/windows-samples-rs), I would agree the `is_null` function should be restored.
