### ISSUE TITLE
Use `Option` for nullable COM pointers as return values

### ISSUE THREAD

**Issue by mwcampbell** [microsoft/windows-rs#1167]
In some COM methods that have a COM pointer as a retval, it's normal to return a result of `S_OK` but set the retval to null. An example is the `IRawElementProviderSimple::GetPatternProvider` method in UI Automation. So it seems to me that in the Rust bindings for these methods, the return value should be, for example, `Result<Option<IUnknown>>`, not `Result<IUnknown>`.

**Comment by mwcampbell** [comment]
Based on some test code under `tests/legacy`, it looks like the current way of returning a null COM pointer with an `HRESULT` of `S_OK` is to return `Err(Error::OK)`. Is this the intended long-term solution? If so, a FAQ entry for this would be helpful.

**Comment by kennykerr** [comment]
Yes, thus far that has proved to be the best solution. The `Result<Option<IUnknown>>` approach penalizes most API usage that expects non-null values.

**Comment by kennykerr** [comment]
An FAQ would be nice but I'm not very good at maintaining it so I'm probably going to expand [the samples repo](https://github.com/microsoft/windows-samples-rs) with more specific examples that can illustrate things like this and also be validated by the build. That should age better than markdown.
