### ISSUE TITLE
Generated WinRT/COM implementations lack weak reference support

### ISSUE THREAD

**Issue by mwcampbell** [microsoft/windows-rs#1171]
Unless I'm missing something, the WinRT/COM implementations generated by the `implement` macro don't appear to have support for `IWeakReferenceSource` and `IWeakReference`.

**Comment by kennykerr** [comment]
Weak references are supported. Here are some tests for reference:

https://github.com/microsoft/windows-rs/tree/master/tests/winrt/weak

**Comment by mwcampbell** [comment]
Oh, I get it. I was looking for references to `IWeakReferenceSource` or `IWeakReference` in the code for the `implement` macro itself. But now I see that those interfaces are implemented by `WeakRefCount`, and I just found the `test_implement` test function. Apologies for my mistake.
