### ISSUE TITLE
Extending an existing bindings crate

### ISSUE THREAD

**Issue by wravery** [microsoft/windows-rs#1174]
Maybe there's a simpler way to handle this that I'm missing, but an issue I ran into with the `webview2-com-sys` crate (https://github.com/wravery/webview2-rs) is that in order to share types in various downstream consumers, I had to keep adding new bindings to `webview2-com-sys` until I had the union of all possible APIs that those crates or any consumers of their public interfaces using those types might need.

What I'd really like to do is to only generate extra bindings that I need at each layer, but have it inherit any existing bindings from shared upstream crates and extend them. I think that would require changes to the `windows::build!` macro (or a new macro that specializes it) and the underlying generator to pull in the upstream bindings crate/modules instead of generating them. It could take an extra argument listing the symbol paths to inherit instead of generating, or if it could figure that out automatically, e.g. by adding some metadata or `const` variables to the upstream crate, even better.

**Comment by kennykerr** [comment]
Possibly related to #432

**Comment by wravery** [comment]
Yup, I didn't see that one searching for "extend" or "inherit." Feel free to close this one if you want to just track it there.
