### ISSUE TITLE
Are you planning to support ARM64 architecture ? 

### ISSUE THREAD

**Issue by mshaikhcool** [microsoft/windows-rs#1175]
Since there is no discussion tab here in this repo, I had to create an issue. 
neither did I find any issues regarding arm64. Forgive me if I missed it.
`\.windows\` directory contains only x64 and x86 compiler bindings, are you planning to support ARM64 ?

**Comment by riverar** [comment]
`Arm64` is a fully supported target. The files you're seeing in `.windows` are simply to support crate development/test.

**Comment by kennykerr** [comment]
ARM32 and ARM64 should work. The absence of those folders is only because GitHub doesn't support ARM CI builds as far as I can tell. 

If you have your own ARM components you can certainly use them with the Windows crate.

https://github.com/microsoft/windows-rs/blob/3a378f1e5ec5405437debcae6447565ab4d67e4d/crates/gen/src/build.rs#L68-L71

**Comment by mshaikhcool** [comment]
Both @riverar & @kennykerr thank you very much 👍

**Comment by Berrysoft** [comment]
@kennykerr It doesn't work now. According to the code,

https://github.com/microsoft/windows-rs/blob/58094dcf52d6cfdd16ae69dc2cdb6b1f8d5d051d/crates/tools/msvc/src/main.rs#L8-L13

ARM64 is unknown platform.

**Comment by riverar** [comment]
@Berrysoft Thanks, will get that fixed up asap.

**Comment by kennykerr** [comment]
@Berrysoft Arch-specific support spans a few different scenarios. That code snippet is about generating libs. The one I mentioned is about build macro support for copying existing libs to the target folder. There is also arch-specific API definitions that I'm working on now. @riverar is working on the ARM64 libs. We should be able to land it all pretty soon.
