### ISSUE TITLE
Missing git tag for 0.20.0 and 0.20.1

### ISSUE THREAD

**Issue by roblabla** [microsoft/windows-rs#1178]
The latest git tag is for 0.19.0. Could we have a tag for the latest two release?

The SHAs:

- 0.20.0: f1c0282de8659339506de87ea855f262d3de55b2 (from https://docs.rs/crate/windows/0.20.0/source/.cargo_vcs_info.json)
- 0.20.1: e4bc9e32508a5de57c771d58274f74568d52a822 (from https://docs.rs/crate/windows/0.20.1/source/.cargo_vcs_info.json)

**Comment by riverar** [comment]
Should actually be

```
git tag 0.20.1 e4bc9e32508a5de57c771d58274f74568d52a822
git tag 0.20.0 5cbe2bebfb8af7578bd554dafe2c831f1f2a8638
git push --tags
```

**Comment by riverar** [comment]
And It Is So.

(I know you're probably wondering why it's out of sync with vcs_info. Suspect a history rewrite occurred after release.)
