### ISSUE TITLE
GetModuleFileNameW receives PWSTR instead of `IntoParam<PWSTR>`

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#1179]
SHGetKnownFolderPath correctly receives `IntoParam<PWSTR>` but GetModuleFileNameW does not.

The difference between them is that [the former receives `PWSTR*`](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) while [the latter receives `LPWSTR`](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew), but since `LPWSTR` is just `PWSTR*`, I think they should behave same.

**Comment by sabbyX** [comment]
```csharp
GetModuleFileNameW([Optional][In] HINSTANCE hModule, [Out][NativeArrayInfo(CountParamIndex = 2)] PWSTR lpFilename, [In] uint nSize);
```
`lpFilename` is an out param, its not supported yet — #595

**Comment by saschanaz** [comment]
Doesn't SHGetKnownFolderPath also use out param?

**Comment by sabbyX** [comment]
Right, I best guess would be SHGetKnownFolderPath returns `HRESULT`, it's mapped to `Result<>`, and the only out param is wrapped in it. The latter one returns a `DWORD`, which needs to be preserved for the caller.

**Comment by saschanaz** [comment]
But it does not wrap it to Result 👀

**Comment by sabbyX** [comment]
Maybe I missing something? [docs says so](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/UI/Shell/fn.SHGetKnownFolderPath.html)
```rust
pub unsafe fn SHGetKnownFolderPath<'a>(
    rfid: *const Guid, 
    dwflags: u32, 
    htoken: impl IntoParam<'a, HANDLE>
) -> Result<PWSTR>
```

**Comment by saschanaz** [comment]
Oh, you are right, I'm the confused one here! 😬

Thanks, probably should wait for #595.

**Comment by kennykerr** [comment]
Yes, `IntoParam` is only used for convertible input parameters.
