### ISSUE TITLE
Mismatched naming of COM property getters for consumption and implementation

### ISSUE THREAD

**Issue by mwcampbell** [microsoft/windows-rs#1182]
When consuming a COM interface, the name of a property getter method is `get_Foo`. But when implementing a COM interface using the `implement` macro, the implementation of that same method has to be called simply `Foo`. Is this intentional?

**Comment by kennykerr** [comment]
Do you have an example? The renaming is intentional, but the discrepancy is not. I'll get that fixed up. 

https://github.com/microsoft/windows-rs/blob/83e7d68b970db73918072fd2ac369b96dfb9316c/crates/reader/src/tables/method_def.rs#L37-L44

**Comment by mwcampbell** [comment]
Yes. See `IRawElementProviderSimple::get_ProviderOptions` in UI Automation. The consumer-side projection is called `get_ProviderOptions`, but when I implement the interface, i have to call the function simply `ProviderOptions`.
