### ISSUE TITLE
Publicly expose delay loading

### ISSUE THREAD

**Issue by mwcampbell** [microsoft/windows-rs#1185]
Delay loading is useful not only for libraries or functions that might not be available on all supported versions of Windows, but for libraries that are only sometimes needed at runtime, such as UI Automation (on the provider side). At minimum, `windows::runtime::delay_load` should be publicly exported. It would be great if the bindings generator could be told to automatically implement delay loading for some or all functions that aren't in kernel32. (Delay-loading all functions not in kernel32 is desirable to me because I want to make one of my crates available as a static library that has minimal link dependencies, to remove all possible barriers to adoption.)

**Comment by kennykerr** [comment]
See #1425 for a possible solution.
