### ISSUE TITLE
How to use Xaml::Controls::NavigationView?

### ISSUE THREAD

**Issue by qalcifer** [microsoft/windows-rs#1195]
Hello, I just want to recreate basic example of usage xaml [NavigationView](https://docs.microsoft.com/en-us/windows/apps/design/controls/navigationview#code-example). I tried to create empty NavigationView:
```rust
#[allow(non_snake_case)]
impl App {
    fn OnLaunched(&self, _: &Option<LaunchActivatedEventArgs>) -> Result<()> {
        let window = Window::Current()?;

        let navigation_view = NavigationView::new()?;

        window.SetContent(navigation_view)?;

        window.Activate()
    }
}
```
and it compiled successfully, but default NavigationView didn't present (empty window):
 ![image](https://user-images.githubusercontent.com/62159436/135601908-9fba42b1-b27b-41c9-9b01-71d99a7f9edb.png)

Is that possible to create NavigationView using windows-rs?
example project placed [here](https://github.com/qalcifer/winui-example)

Thanks

**Comment by kennykerr** [comment]
You should be able to call any Xaml APIs using the Windows crate, but I don't know anything about this specific control to tell you how to use it. You may want to try https://stackoverflow.com/ or [the Xaml team](https://github.com/microsoft/microsoft-ui-xaml).

**Comment by riverar** [comment]
This particular control may also require working XAML type mapping mechanics (e.g. IXamlMetadataProvider), which in turn requires a bunch of other things. This is an area I'm slowly working on; Friendly warning, this is a hairy area and you may want to consider using something else for UI at this time.
