### ISSUE TITLE
"Text" and "Caption" in MessageBoxA API display in ASNI encoding format as default

### ISSUE THREAD

**Issue by zhanglun** [microsoft/windows-rs#1197]
Hey guys:

I'm a newbie to Windows application development and Rust.

My file is UTF-8 encoding, here is my code

```rust
 MessageBoxA(None, "标题", "你好，微软", MB_OK);
```

And this is  what the box look like:

![image](https://user-images.githubusercontent.com/3086358/135785646-40d047a6-971d-46b3-bc70-0b7ae9ba5a51.png)

I hope the box can show Chinese friendly, What should I do? Am I missed some API?

**Comment by robmikh** [comment]
You should try the MessageBoxW variant. You'll need to make sure your strings are null terminated and encoded as utf16. You can take a look at this file from Minesweeper:

https://github.com/robmikh/minesweeper-rs/blob/master/src/wide_string.rs

**Comment by riverar** [comment]
Yep, as @robmikh mentioned, you need to use the Unicode or "wide" variant of the APIs that typically end with a `W` (e.g. MessageBoxW).
