### ISSUE TITLE
C header-only functions and functional macros not getting translated

### ISSUE THREAD

**Issue by roblabla** [microsoft/windows-rs#1205]
Currently, windows-rs is missing a handful of APIs that only exists in the Win32 SDK in the form of header-only static functions or function-like macros. While this is to be expected on a certain level, since windows-rs works through codegen, it'd be nonetheless nice to bring some of this functionality, as some of them are really useful.

Two examples that's come up multiple times already while using windows-rs:

- The `IsWindows*OrGreater` functions from `um/VersionHelpers.h`
- The `HRESULT_FROM_WIN32` macro from `shared/winerror.h`

Is there any plans to allow them in windows-rs, either in the form of "manual" implementations, or maybe through more involved codegen?

**Comment by ryancerium** [comment]
@roblabla I opened this ticket too, #921 .  You can't do it with metadata as-is, but you might be able to contribute to the win32metadata project to generate it.
