### ISSUE TITLE
Safer pointer passing by taking ownership the link to value

### ISSUE THREAD

**Issue by Zymlex** [microsoft/windows-rs#1207]
This allows use the lifetime check mechanism for pointers (with some restrictions!).

Structure field that expecting the pointer. also taking ownership the link to target value.

Of course, this does not remove the responsibilities from the programmer to track the lifetime of objects, but maybe it can a help in this and make more safe moments, where the object shouldn't live longer than a function call.

Similar is used in std as [`Unique<T>`](https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/ptr/unique.rs#L36)
https://doc.rust-lang.org/nomicon/phantom-data.html at the bottom

Something like:

```rust
use std::os::raw::c_char;
use std::ffi::CStr;

#[repr(transparent)]
pub struct ConstCStrPtr<'a> {
    ptr: *const c_char,
    _marker: std::marker::PhantomData<&'a CStr>
}

impl<'a> ConstCStrPtr<'a> {
    pub const fn new(refer: &'a CStr) -> Self {
        Self {
            ptr: refer.as_ptr(),
            _marker: std::marker::PhantomData
        }
    }
}
```
or
```rust
#[repr(transparent)]
pub struct ConstPtr<'a, Y: 'a> {
    ptr: *const Y,
    _marker: std::marker::PhantomData<&'a ()>
}

impl<'a, Y: 'a> ConstPtr<'a, Y> {
    pub const fn new<T: 'a + ?Sized>(refer: &'a T) -> Self {
        Self {
            ptr: (refer as *const T).cast::<Y>(),
            _marker: std::marker::PhantomData
        }
    }
}
```

**Comment by kennykerr** [comment]
I think the recently introduced `Borrowed` type should help here. It provides the lifetime tracking you're alluding to.  It is already used for parameters, but I do need to still apply it to struct fields. I'll close this in favor of #1896. Thanks for the suggestions!
