### ISSUE TITLE
Ergonomics improvements for generated enums and flags

### ISSUE THREAD

**Issue by yoshuawuyts** [microsoft/windows-rs#1210]
## Introduction

After our conversation in https://github.com/yoshuawuyts/miow/pull/47 I kept thinking about ways we might be able to improve we handle C-style enums, while remaining true to the desire to keep the memory representation of values consistent with other programming languages. The Windows metadata makes a distinction between flags and enums, and in this issue I'm outlining potential designs we could use to improve the ergonomics of our generated code for both.

## Designing Flags

Given the following metadata definition:

```c++
using System;

[Flags]
public enum FILE_FLAGS_AND_ATTRIBUTES : uint
{
	FILE_ATTRIBUTE_READONLY = 0x1u,
	FILE_ATTRIBUTE_HIDDEN = 0x2u,
	FILE_ATTRIBUTE_SYSTEM = 0x4u,
	...
}
```
We're currently generating the following code:

```rust
#[derive(Default, PartialEq, Eq, Copy, Clone, Debug)]
#[repr(transparent)]
pub struct FILE_FLAGS_AND_ATTRIBUTES(pub u32);
pub const FILE_ATTRIBUTE_READONLY: FILE_FLAGS_AND_ATTRIBUTES =
    FILE_FLAGS_AND_ATTRIBUTES(1u32);
pub const FILE_ATTRIBUTE_HIDDEN: FILE_FLAGS_AND_ATTRIBUTES =
    FILE_FLAGS_AND_ATTRIBUTES(2u32);
pub const FILE_ATTRIBUTE_SYSTEM: FILE_FLAGS_AND_ATTRIBUTES =
    FILE_FLAGS_AND_ATTRIBUTES(4u32);
```
With usage requiring we know that these are indeed bitwise flags, and using combining them using bitwise operators.
```rust
use windows::win32::FileSystem::{FILE_ATTRIBUTE_READONLY, FILE_ATTRIBUTE_HIDDEN, FILE_ATTRIBUTE_SYSTEM};

let mut flags = FILE_ATTRIBUTE_READONLY | FILE_ATTRIBUTE_HIDDEN | FILE_ATTRIBUTE_SYSTEM;
```

However, the manifest provides us with enough data that we could instead create a singular flags option, with methods on it to toggle the various options:

```rust
#[derive(Default, PartialEq, Eq, Copy, Clone, Debug)]
#[repr(transparent)]
struct FileFlagsAndAttributes(u32);
impl FileFlagsAndAttributes {
    const fn file_attribute_readonly(&mut self) -> bool { ... }
    const fn set_file_attribute_readonly(&mut self, enable: bool) { ... }
    ...
}
```

Usage could then be a lot easier to use for folks less familiar with bitwise manipulation, and overall feel more ergonomic to use:

```rust
let mut flags = FileFlagsAndAttributes::default();
flags.set_file_attribute_readonly(true);
flags.set_file_attribute_hidden(true);
flags.set_file_attribute_system(true);
```

## Designing Enums

Similarly, enums could also be adapted to be more ergonomic in Rust. Given the following metadata definition:

```c++
// Windows.Win32.Networking.WinSock.WSA_ERROR
public enum WSA_ERROR
{
	WSA_IO_PENDING = 997,
	WSA_IO_INCOMPLETE = 996,
	WSA_INVALID_HANDLE = 6,
        ...
}
```
We're currently generating the following code:
```rust
#[derive(Default, PartialEq, Eq, Copy, Clone, Debug)]
#[repr(transparent)]
pub struct WSA_ERROR(pub i32);
pub const WSA_IO_PENDING: WSA_ERROR = WSA_ERROR(997i32);
pub const WSA_IO_INCOMPLETE: WSA_ERROR = WSA_ERROR(996i32);
pub const WSA_INVALID_HANDLE: WSA_ERROR = WSA_ERROR(6i32);
```
Creating instances of this is not that hard. But figuring out which type was returned to us requires importing a fair few types:
```rust
use Windows::Win32::Networking::WinSock::{WSA_INVALID_HANDLE, WSA_IO_INCOMPLETE, WSA_INVALID_HANDLE, WSAGetLastError};

match unsafe { WSAGetLastError() } {
    WSA_IO_PENDING => { ... },
    WSA_IO_INCOMPLETE => { ... },
    WSA_INVALID_HANDLE=> { ... },
    _ => { ... }
}
```

The solution for this is often to just use globs; but that's not ideal as it over-imports types. Instead, it seems like the metadata provides us with enough information to create first-class Rust enums that have zero overhead compared to their C counterparts:

```rust
#[derive(Default, PartialEq, Eq, Copy, Clone, Debug)]
#[non_exhaustive]
#[repr(i32)]
pub enum WsaError {
    WsaIoPending = 997,
    WsaIoIncomplete = 996,
    ...
}
```
Handling errors would then just be matter of importing the right error type into scope, and calling `match`:
```rust
use Windows::Win32::Networking::WinSock::{WsaError, WSAGetLastError};

match unsafe { WSAGetLastError() } {
    WsaError::WsaIoPending => { ... },
    WsaError::WsaIoIncomplete => { ... },
    WsaError::WsaInvalidHandle => { ... },
    _ => { ... }
}
```

## Conclusion

In this issue I've shared ergonomic improvements we could make for our generated flags and enums by leveraging the Windows metadata. One of the most important design considerations for Windows-rs's enum/flags representation appears to be compatibility with C/C++, and these designs stay true to that. Both proposed designs remain byte-for-byte compatible with C/C++, but would be nicer to use by better integrating with Rust language features.

I hope this is helpful, and I'm keen to get your thoughts on this!

**Comment by kennykerr** [comment]
Feel free to reopen if you'd like to discuss further. 

I try not to leave issues open that don't have actionable work and haven't received an update in a few days, just to keep the issue count under control.
