### ISSUE TITLE
I want to know how to pass a callback function ????

### ISSUE THREAD

**Issue by cxping** [microsoft/windows-rs#1212]
### I need to do this to be right?
I want to know how to pass a callback function,But the parameter type is `windows::IntoParam<'a, Foundation::TypedEventHandler<DeviceWatcher, DeviceInformation>> ` trait 

```
bindings::Windows::Devices::Enumeration::DeviceWatcher
pub fn Added<'a, Param0>(&self, handler: Param0) -> ::windows::Result<super::super::Foundation::EventRegistrationToken>
where
    Param0: ::windows::IntoParam<'a, super::super::Foundation::TypedEventHandler<DeviceWatcher, DeviceInformation>>,

```

**Comment by Nerixyz** [comment]
You wrap your callback in the `TypedEventHandler`.

In this case the code to listen to the `Added` event would look something like this:

```rust
watcher.Added(TypedEventHandler::new(|sender: &Option<DeviceWatcher>, args: &Option<DeviceInformation>| {
    if let Some(args) = args {
        println!("Added: {:?} {:?}", args.Name(), args.Kind());
    }
    Ok(())
}))?;
```

Or, you can do the same as done in the [`WebView2` example](https://github.com/microsoft/windows-samples-rs/blob/54ec3b27687fcf8426a023538b37aa77d62cff48/webview2/src/main.rs#L316-L322).
