### ISSUE TITLE
Possible to implement Microsoft Store purchase functionality?

### ISSUE THREAD

**Issue by ndarilek** [microsoft/windows-rs#1218]
I have a Rust game I'm trying to add to the Microsoft Store. Currently it seems to correctly determine when it is running as a free trial, but I'm having trouble figuring out how to implement the purchase flow.

The solution seems to be documented here: https://docs.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#desktop Specifically:

1. I can use `IInitializeWithWindow` in my app, but I'm not sure a) how to cast `StoreContext` to that and set the main window handle, or even if I can.
2. I need the main window handle, but am not sure how to retrieve it from the Rust bindings. I searched for `MainWindowHandle` as per this line in the sample code:

`initWindow.Initialize(System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle);`

I know implementing COM interfaces isn't supported yet, but I'm not sure if that's what I need to pull this off. I'd really appreciate knowing whether or not this is even possible. :)

Thanks.

**Comment by kennykerr** [comment]
You can use the [cast method](https://docs.rs/windows/0.21.1/windows/trait.Interface.html#method.cast) to query for an interface. 

> I know implementing COM interfaces isn't supported yet

Support for implementing COM interfaces is now available.

**Comment by ndarilek** [comment]
This is a Bevy game, running in a window presumably created by WGPU.

I have this code which seems to correctly detect if my game is a trial or not. Ignore the bit about the demo feature--that is used to enable demo functionality outside the Microsoft Store, which gets the full non-demo version and should upgrade via IAP.

```
pub fn is_demo() -> bool {
    if cfg!(feature = "demo") {
        return true;
    }
    #[cfg(windows)]
    {
        if let Ok(context) = StoreContext::GetDefault() {
            if let Ok(license) = context.GetAppLicenseAsync() {
                if let Ok(license) = license.get() {
                    if let Ok(trial) = license.IsTrial() {
                        trial
                    } else {
                        false
                    }
                } else {
                    false
                }
            } else {
                false
            }
        } else {
            false
        }
    }
    #[cfg(not(windows))]
    false
}
```

Yeah, can certainly be optimized, but I kind of expected it not to work so wrote it verbosely. :)

Then this code makes the purchase when a button is clicked, but doesn't work:

```
pub fn purchase_upgrade() {
    #[cfg(windows)]
    {
        if let Ok(context) = StoreContext::GetDefault() {
            if let Err(e) = context.RequestPurchaseAsync(MICROSOFT_STORE_ID) {
                eprintln!("Error purchasing product: {:?}", e);
            }
        }
    }
}
```

But that code fails to run. Unfortunately I'm having a tough time debugging this because I essentially have to round-trip through approval and certification to test this in a store context, my last version used `error!`, and I'm speculating that perhaps error logging isn't set up in release builds. I'll see if this eprintln triggers instead. But for the time being I'm speculating that perhaps the window handle needs to be registered. I'm new enough to the win32 APIs to not be sure whether or not this failure case is relevant to me.

As an aside, I can apparently link locally built apps to their store installations and, after installing the store version once, debug issues like this in local builds. What should I google to figure out how to do that outside of a Visual Studio context? Is there a command line incantation to link a local appxmanifest/executable with the same version of that app installed through the store? I've searched, but don't even know what keywords to try and nothing has sent me anywhere useful.

Thanks.

**Comment by ndarilek** [comment]
Hitting a snag with 0.23.0:

```
[dependencies.windows]
version = "0.23"
features = [
    "Foundation",
    "Services_Store",
    "Win32_UI",
    "Win32_UI_KeyboardAndMouseInput",
    "Win32_UI_Shell",
]
```

error[E0432]: unresolved import `windows::Win32::UI::KeyboardAndMouseInput::GetActiveWindow`                                         
  --> src\iap.rs:18:17                                                                                                               
   |                                                                                                                                 
18 |     Win32::UI::{KeyboardAndMouseInput::GetActiveWindow, Shell::IInitializeWithWindow},                                          
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `GetActiveWindow` in `Win32::UI::KeyboardAndMouseInput`               
                                                                                                                                     
error[E0599]: no method named `Initialize` found for struct `IInitializeWithWindow` in the current scope                             
   --> src\iap.rs:116:53                                                                                                             
    |                                                                                                                                
116 | ...                   if unsafe { interop.Initialize(GetActiveWindow()) }.is_ok() {                                            
    |                                           ^^^^^^^^^^ method not found in `IInitializeWithWindow`                               
 
What features am I missing? Would be great if the docs included the needed feature for a given module/name. If they do then I'm missing it--at least in search results.

Thanks!

**Comment by riverar** [comment]
@ndarilek What you need for `GetActiveWindow` is `["Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse" ]`. The general workflow is:
1. find the features tied to the method/type you're using
2. find the features tied to the containing module

The pre-generated code lives at https://github.com/microsoft/windows-rs/tree/master/src/Windows

Bubbling up all the required features via docs is something def on the radar and being worked on as you read this.
