### ISSUE TITLE
Some functions do not enable with their corresponding feature

### ISSUE THREAD

**Issue by ok-nick** [microsoft/windows-rs#1246]
A lot of exports from the `Win32::Storage::CloudFilters` do not export with the `Win32_Storage_CloudFilters` feature enabled.
ex: `CfExecute`
```rs
#[cfg(all(
    feature = "Win32_Foundation",
    feature = "Win32_Storage_FileSystem",
    feature = "Win32_System_SystemServices"
))]
pub unsafe fn CfExecute(
```

**Comment by riverar** [comment]
@ok-nick Can confirm need all four features.

Sample: https://github.com/riverar/wrs-repros/tree/master/issue-1246

The workflow is super awkward right now, but I'd say generally you want a union of features from:
1. dependent features tied to the method/type you're using
  e.g. https://github.com/microsoft/windows-rs/blob/6aa142c2b748c56b6486a8728f48cbd428fbcaca/src/Windows/Win32/Storage/CloudFilters/mod.rs#L4300-L4305

2. features tied to the containing module
  e.g. https://github.com/microsoft/windows-rs/blob/6aa142c2b748c56b6486a8728f48cbd428fbcaca/src/Windows/Win32/Storage/mod.rs#L12-L13

Going to close this as everything looks to be in order. But we're definitely going to work on the dev experience here.

**Comment by kennykerr** [comment]
The docs have now been updated to indicate which features a particular API requires:

https://microsoft.github.io/windows-docs-rs/doc/windows/
