### ISSUE TITLE
Annoyance: use Win32::System::Diagnostics::Debug::* and None

### ISSUE THREAD

**Issue by qrnch-jan** [microsoft/windows-rs#1263]
When `use`:ing `Win32::System::Diagnostics::Debug::*` `None` (a `const` `JsDebugReadMemoryFlags`) gets imported and overrides `Option::None`.  An easy workaround is to explicitly use `Option::None` as needed.  I vote for renaming `Win32::System::Diagnostics::Debug::None` instead, if possible.

Digression: This isn't the first time I encountered something like this; I want rust to support exclusionary `use` syntax: `use Win32::System::Diagnostics::Debug::{*, !None}` to handle these types of situations.

**Comment by riverar** [comment]
Thanks @qrnch-jan, we hit this recently too. Just filed an issue on metadata so we can get this fixed. Will leave this open/blocked for now.

**Comment by riverar** [comment]
Fixed in metadata a few days ago https://github.com/microsoft/win32metadata/commit/253d225b02b7f0dceb9b7062a93b455b58805e40

As soon as the new metadata comes out, we'll update the crate. Thanks for reporting!
