### ISSUE TITLE
`RoOriginateError` not implemented in wine

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#1287]
We're currently migrating our D3D12 crates from winapi to windows-rs thanks to the much improved API characteristics and generally being better maintained and everything :star_struck: !

However, I'm mainly a Linux user so my only options are rebooting to Windows all the time, or cross-compiling our application with MinGW and running it in wine + vkd3d-proton, which works surprisingly well except for one caveat:
D3D12 APIs require the use of error codes such as `Dxgi::DXGI_ERROR_NOT_FOUND`, but the wrapper calls like `EnumAdapters1` convert that from `HRESULT` to `Error`, invoking `RoOriginateError` in the process. This makes wine abort:

```
wine: Call from 000000007B0122DE to unimplemented function combase.dll.RoOriginateError, aborting
```

I haven't found a straightforward way to tell wine to ignore instead of abort on certain function calls, but is there something windows-rs can do to not (or optionally) call this function behind ones back?

**Comment by kennykerr** [comment]
Thanks for bringing this up. This API was introduced in Windows 8, so its been around for quite some time, but I have plans to trim down the base functionality `windows::runtime::*` to the bare minimum and I can certainly see about making this work.

**Comment by kennykerr** [comment]
Just to be clear, the Windows crate already handles the case where the function is not exported at all - to support older versions like Windows 7 - but what you describe is unlike any version of Windows. In your scenario, the function is exported and implemented in such a way as to abort. Ideally, wine would try a little harder to behave like _some_ version of Windows. 😉 

In this particular case, I don't think we should be calling `RoOriginateError` so aggressively and am busy cleaning that up but in general this is not something we can guard against.

**Comment by MarijnS95** [comment]
> In your scenario, the function is exported and implemented in such a way as to abort. Ideally, wine would try a little harder to behave like _some_ version of Windows.

Exactly, hence the hopes for an easy way (environment variable) to disable this behaviour (for a single function) in wine if at all possible - but I haven't found it yet. Otherwise I'd have to modify and recompile wine to do so.

In fact, `RoOriginateError` seems to be a good canditate for becoming a no-op anyway:

> Reports an error and an informative string to an attached debugger.

That doesn't seem like anything that should cause an abort when called - just the usual `fixme` message in `wine` logs is enough.

> In this particular case, I don't think we should be calling `RoOriginateError` so aggressively and am busy cleaning that up but in general this is not something we can guard against.

It seems helpful so I'm not fully sure what's best, I'll leave that up to you :)

**Comment by MarijnS95** [comment]
@kennykerr It's gone now. Looks like that must have been https://github.com/microsoft/windows-rs/commit/82a4a4dbc1059b9c5190f09d01c72d71fa157b93#diff-e5b6e3900317a9af7b5af07e937b95d2176e13ce700f73561f119ebebb45bceaR130 not calling `Error::new()` anymore. Thanks!
