### ISSUE TITLE
Implement macro: generated `From<&mut Foo> for IFoo` implementation seems sketchy

### ISSUE THREAD

**Issue by samlh** [microsoft/windows-rs#1290]
This generated impl looks sketchy - what happens if you call it on a value that isn't wrapped in the `..._box`?

https://github.com/microsoft/windows-rs/blob/c604d64d065eb615c7085eb64ca11fb96ee3cb9b/crates/deps/macros/src/implement.rs#L160

e.g.
```rust
#[implement(Windows::UI::Xaml::Data::ICustomProperty)]
pub struct CustomProperty {
  bar: ()
}
```

Generates:
```rust
impl< > ::std::convert::From< &mut CustomProperty:: < > >for Windows::UI::Xaml::Data::ICustomProperty {
  fn from(implementation: &mut CustomProperty:: < >) -> Self {
    unsafe {
      let mut ptr = (implementation as*mut_as*mut::windows::runtime::RawPtr).sub(2+1)as*mut CustomProperty_box:: < > ;
      (*ptr).count.add_ref();
      ::std::mem::transmute_copy(& ::std::ptr::NonNull::new_unchecked(&mut(*ptr).vtables.0 as*mut_as_))
    }
  }
}
```

Mistaken usage:
```rust
let foo = CustomProperty { bar: () };
ICustomProperty::from(foo).DoSomething();      // OK
ICustomProperty::from(&mut foo).DoSomething(); // Out-of-bounds access?
```

Happily, I've never actually needed this conversion, but if it is kept, I recommend making it unsafe like the to_impl method.

**Comment by kennykerr** [comment]
This trait is no longer being generated. Let me know if there any other concerns with the new `implement` macro. #1345

**Comment by samlh** [comment]
Thanks for the update!

I've updated to using the new trait-based implement macro, and I'm quite happy with the results.

Thanks for the hard work - the windows crate just keeps getting better!
