### ISSUE TITLE
Ability to create independent generated source

### ISSUE THREAD

**Issue by Zymlex** [microsoft/windows-rs#1293]
Sometimes I wish to have all required in one file (with ability to remove crate).

**Comment by riverar** [comment]
Why? Just trying to understand the use case, not judging you.

**Comment by Zymlex** [comment]
The reasons may be different:
to turn off the crate when there is no longer a need to generate.
manual source editing for improving code and removing unnecessary.

**Comment by riverar** [comment]
Got it, thanks @Zymlex.

**Comment by kennykerr** [comment]
You can use the `generate` macro as follows:

https://github.com/microsoft/windows-rs/blob/master/crates/tools/bindings/src/main.rs

**Comment by Zymlex** [comment]
@kennykerr Why the `generate` macro not used by default? What do I lose when using it?
