### ISSUE TITLE
STATUS_ENTRYPOINT_NOT_FOUND error after updating to v0.25

### ISSUE THREAD

**Issue by gyk** [microsoft/windows-rs#1294]
Our application fails to launch with the error message "process didn't exit successfully (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)" after updating windows-rs from v0.21.1 to v0.25. Dependency walker shows it has missing import `GetWindowSubclass` in `COMCTL32.dll`.

You can see from the screenshots below that `GetWindowSubclass` used to be imported by ordinal (411) but now it is imported by name:

**Before**

![GoodImport](https://user-images.githubusercontent.com/4338714/140728361-c4a8efef-97d5-45f2-8a2e-d202f1ab40fd.png)

**After**

![BadImport](https://user-images.githubusercontent.com/4338714/140728426-5e7e2bd9-df5a-44a2-ad11-f265295c5291.png)

Our project also depends on `winapi` and `native-windows-gui` crates so it is a bit hard to pin down the actual cause.
However, the most remarkable change is that there is no longer a `build.rs` script.

The OS version is Windows 11 Insider Preview 22489.1000.

**Comment by kennykerr** [comment]
Its possible the functions are only exported by ordinal and not by name. Rust supports this, but the metadata would need to reflect that so that we can generate the appropriate lib or link attribute. We'll have to confirm either way.

**Comment by riverar** [comment]
`GetWindowSubclass` is a function present in [Common Controls 6.0 and above](https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-getwindowsubclass#:~:text=Comctl32.lib-,dll,-Comctl32.dll%20(version). The OS inbox version is stuck at 5.x for backwards compatibility reasons. Your app will need to [embed/deploy the appropriate manfiest](https://docs.microsoft.com/en-us/windows/win32/controls/cookbook-overview?WT.mc_id=WD-MVP-5002756#using-comctl32-version-6-in-control-panel-or-a-dll-that-is-run-by-rundll32exe) to load in 6.0+.

As a quick fix, create a file on disk next to `yourapp.exe`, name it `yourapp.exe.manifest`, and put this inside:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity
    version="1.0.0.0"
    processorArchitecture="*"
    name="app"
    type="win32"
/>
<dependency>
    <dependentAssembly>
        <assemblyIdentity
            type="win32"
            name="Microsoft.Windows.Common-Controls"
            version="6.0.0.0"
            processorArchitecture="*"
            publicKeyToken="6595b64144ccf1df"
            language="*"
        />
    </dependentAssembly>
</dependency>
</assembly>
```

**Comment by kennykerr** [comment]
Looks like the "correct" way to use this API is via a manifest as described here https://github.com/microsoft/windows-rs/issues/1294#issuecomment-963417891

More background here: https://github.com/microsoft/win32metadata/issues/734

Failing that you should still be able to call the API using `LoadLibrary`/`GetProcAddress`.

**Comment by gyk** [comment]
Thank you for investigating!

I don't actually call `GetWindowSubclass` in my code, the call seems to originate from `native-windows-gui`. What makes things tricky is that NWG uses some hack to implement visual style without embedding a manifest file ([doc](https://gabdube.github.io/native-windows-gui/native-windows-docs/helper.html)). I also tried to make a minimal reproducible example by using windows-rs v0.25, NWG and winapi together but without success.

Fortunately I am able to work around this by manually including a manifest with `embed-resource`, and our application can launch as usual.

**Comment by riverar** [comment]
Closing for now, just a very unfortunate situation where this API wasn't supposed to be callable in comctl32 5.x to begin with. I will continue to grumble about this behind the scenes in your honor.
