### ISSUE TITLE
How to use LookupAccountSidW?

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#1296]
I can't figure out how to use this function in rust, i always get access denied.

Here is a snippet of my one of my attempts:

```
 let sid = unsafe { (*(pAce as *const ACCESS_DENIED_ACE)).SidStart } as isize;
            let sid_name: PWSTR = unsafe { PWSTR(LocalAlloc(LMEM_ZEROINIT, 256) as *mut u16) };
            let domain_name: PWSTR = unsafe { PWSTR(LocalAlloc(LMEM_ZEROINIT, 256) as *mut u16) };

            let mut length = 256 as u32;
            let mut dlength = 256 as u32;
            let mut name_in_use = SID_NAME_USE::default();
            let psid = PSID(sid as isize);
            unsafe {
                LookupAccountSidW(
                    None,
                    psid,
                    sid_name,
                    &mut length,
                    domain_name,
                    &mut dlength,
                    &mut name_in_use,
                )
                .unwrap()
            };
```

I am guessing i am doing something wrong with sid/domain_name and the access denied comes from the function trying to write to the memory wrong.

**Comment by kennykerr** [comment]
For API usage questions I suggest you check the docs or ask questions on https://stackoverflow.com/ - if that doesn't yield a solution you could open an issue on https://github.com/microsoft/windowsappsdk.

**Comment by Zerowalker** [comment]
Will do, sorry!

**Comment by kennykerr** [comment]
No worries - let me know if you don't get an answer and I can poke around some more.
