### ISSUE TITLE
`IntoParam<'a, PWSTR>` implicitly null-terminates

### ISSUE THREAD

**Issue by ok-nick** [microsoft/windows-rs#1301]
This behavior looks intentional, but I'm trying to call `CfCreatePlaceholders` with an `OsStr` and `IntoParam` is implicitly null-terminating it. I could work around this limitation by manually encoding the `OsStr`, although this is definitely a problem.

I'd assume the win32 metadata doesn't supply indicators to whether or not a string should be null-terminated (maybe I should also leave an issue there?) but it was rather confusing to solve this issue.

**Comment by kennykerr** [comment]
Most Windows APIs expect strings to be terminated. Is that not the case for this function? Just trying to understand the problem.

**Comment by ok-nick** [comment]
Yes, that was the issue, although I think I'm wrong. I had different results when the string was non-null-terminated, but it turns out I had the parameter incorrect anyways? I'm not sure, I'll have to do a little more digging and I'll open this issue back up if that's not the case.

**Comment by riverar** [comment]
@ok-nick Sorry to bug you here but seems there was a mixup and I can no longer access the Discord server.

**Comment by riverar** [comment]
@ok-nick Sorry to bug you here but seems there was a mix-up and I can no longer access the Discord server. Can we connect on Discord (WithinRafael#7014)? (Will delete this in a few days.)
