### ISSUE TITLE
Add `strz!` and `wstrz!` macros for creating compile-time null-terminated string literals

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1307]
For use with APIs expecting `PSTR`/`PWSTR`/`HSTRING` parameters (or struct fields) that will work with no-std and avoid allocations.

Also should be able to construct `PSTR` from `&[u8]` with assert for terminator.

**Comment by MaulingMonkey** [comment]
Prior art worth noting:
* [`wchar::wchz!`](https://docs.rs/wchar/latest/wchar/macro.wchz.html)
* [`abistr::cstr!` / `abistr::cstr16!`](https://docs.rs/abistr/0.2.0-rc1/abistr/index.html#macros)

> Also should be able to construct PSTR from &[u8] with assert for terminator.

Specific prior art:
* [`std::ffi::CStr::from_bytes_with_nul`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_with_nul)
* [`abistr::CStrPtr<T>::from_units_with_nul`](https://docs.rs/abistr/0.2.0-rc1/abistr/struct.CStrPtr.html#method.from_units_with_nul)
* [`abistr::CStrNonNull<T>::from_units_with_nul`](https://docs.rs/abistr/0.2.0-rc1/abistr/struct.CStrNonNull.html#method.from_units_with_nul)

With the caveats:
* They return a Result, so you need to unwrap to panic
* They also check for interior `\0`s which would cause the string to unexpectedly terminate early
* `std::ffi::CStr` is currently a fat type, so one must [`as_ptr`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.as_ptr) it back down to a single pointer before passing it along.  `abistr::CStr*` doesn't suffer this limitation.

**Comment by kennykerr** [comment]
Playing with an implementation of this here: https://github.com/microsoft/windows-rs/compare/utf16?expand=1

**Comment by kennykerr** [comment]
Closing as duplicate of #581.
