### ISSUE TITLE
Change of semantics?

### ISSUE THREAD

**Issue by 1Dragoon** [microsoft/windows-rs#1312]
In 0.17.0 of the windows crate, I was able to do something like this:

```rust
let searcher: IDirectorySearch = ADsOpenObject(
  "LDAP://contoso.com\0",
  PWSTR::default(),
  PWSTR::default(),
  ADS_SECURE_AUTHENTICATION
).unwrap()
```

Now it seems to have gone back to requiring a variant of the previous behavior of much earlier versions of the crate:

```rust
let mut searcher = IDirectorySearch as *mut *mut std::ffi::c_void;
let mut dom = String::from("LDAP://contoso.com\0").encode_utf16().collect::<Vec<u16>>();

ADsOpenObject(
  PWSTR(dom.as_mut_ptr()),
  PWSTR::default(),
  PWSTR::default(),
  ADS_SECURE_AUTHENTICATION,
  &IADs::IID,
  searcher
).unwrap();

let searcher: IDirectorySearch = std::mem::transmute(searcher);
```

Was this change intentional? I think it happened somewhere between version 0.17.x and 0.21.x

**Comment by kennykerr** [comment]
I've been making some improvements to support `no_std` libraries and part of that affected whether parameters are bound implicitly for string literals. There was a concern about hiding implicit allocations. If you are using the pre-packaged APIs you can just add the "std" feature to re-enable this in version 0.26. The next version will make this a little simpler and give you more control: https://github.com/microsoft/windows-rs/pull/1309

**Comment by 1Dragoon** [comment]
Ah nice, ok that makes sense

**Comment by riverar** [comment]
Closing as it sounds like you're good to go. Feel free to re-open if that's not correct. Thanks!
