### ISSUE TITLE
Implement macro not working with paths starting with "windows"

### ISSUE THREAD

**Issue by AhmadAlHallak** [microsoft/windows-rs#1317]
I am trying to use IUIAutomation::AddFocusChangedEventHandler, but in order to use it I need to implement the IUIAutomationFocusChangedEventHandler interface, which I am at a lose on how to do in rust

It seems that I have to define a struct and use the implement macro on it: 

```rust
#[implement(windows::Win32::UI::Accessibility::IUIAutomationFocusChangedEventHandler)]
struct A{}
``` 
But I am getting 
> IUIAutomationFocusChangedEventHandler is not a class or interface 

I tried searching the examples on how to use ```#[implement()``` but no matter what I try to implement I still get the same "* is not a class or interface"

**Edit: I found the cause for the problem, see the comment below.**

**Comment by AhmadAlHallak** [comment]
I seem to have found where the problem is 
The implement macro has not been updated to use paths starting with "windows" instead of "Windows",
so just adding 

```rust
use windows as Windows;
```
and using paths starting with "Windows" seems to fix the problem.

**Comment by kennykerr** [comment]
Yes, that's the current workaround. I have plans to revamp the `implement` macro and get rid of such limitations and quirks. Hope to get to that soon.

**Comment by kennykerr** [comment]
New macro tracked here: #1345
