### ISSUE TITLE
How to register a window class?

### ISSUE THREAD

**Issue by oldoldman** [microsoft/windows-rs#1321]
I'm trying ```RegisterClassA```, but I don't know how to set the ```lpfnWndProc``` field , can some body give me an example? Many thanks!

**Comment by riverar** [comment]
Example:

```rust
use windows::runtime::*;
use windows::Win32::Foundation::PSTR;
use windows::Win32::UI::WindowsAndMessaging::*;

fn main() -> Result<()> {
    unsafe {
        let attributes = WNDCLASSA {
            lpszClassName: PSTR(b"Foo\0".as_ptr() as _),
            ..Default::default()
        };

        println!("Class atom: {}", RegisterClassA(&attributes));
    }

    Ok(())
}
```

For future usage questions, please try https://stackoverflow.com/ or the [Rust Programming Language Community Server](https://discord.com/invite/rust-lang-community). We use GitHub issues to track problems that directly impact the crate. Thanks!

**Comment by oldoldman** [comment]
but the application crashed when I create window from this class . It seems because of the null ```lpfnWndProc```

**Comment by kennykerr** [comment]
Here's an example: https://github.com/microsoft/windows-samples-rs/blob/master/create_window/src/main.rs

**Comment by oldoldman** [comment]
it works. thanks.
