### ISSUE TITLE
Introduce helper methods for core `windows-sys` types to improve ergonomics

### ISSUE THREAD

**Issue by yoshuawuyts** [microsoft/windows-rs#1322]
Right now the `windows-sys` crate compiles significantly faster than its `windows` sibling, but unfortunately falls somewhat short in terms of ergonomics. Especially when it comes to passing strings, declaring bools, or dealing with pointers. I'm opening up this issue to explore some improvements to ergonomics we can make without sacrificing the goals we have for the crate.

## `windows-sys` today

It's probably best to work from example, so let's look at the `windows-rs` example presented in [https://github.com/microsoft/windows-rs/pull/1314](https://github.com/microsoft/windows-rs/pull/1314):

```rust
use windows_sys::{Win32::Foundation::*, Win32::System::Threading::*, Win32::UI::WindowsAndMessaging::*};

fn main() {
    unsafe {
        let event = CreateEventW(std::ptr::null_mut(), BOOL(1), BOOL(0), PWSTR(std::ptr::null_mut()));
        SetEvent(event);
        WaitForSingleObject(event, 0);
        CloseHandle(event);

        MessageBoxA(HWND(0), PSTR(b"Text\0".as_ptr() as _), PSTR(b"Caption\0".as_ptr() as _), MB_OK);
    }
}
```

A lot of the API patterns here are very C-like, and will feel unfamiliar to Rust programmers (e.g. I'm generalizing my own experience here). Here are some points people might run into:

1. `BOOL(1)` and `BOOL(0)` match to `true` and `false` respectively, but the knowledge that `1` is true and `0` is false is not encoded anywhere, meaning folks will either need to guess or find an example of `BOOL` in use.
2. Creating a none/empty `PWSTR` requires passing a null pointer to the `PWSTR`. This feels scary.
3. Creating a `PSTR` requires knowing to null-terminate a string, convert it to a pointer, and then convert it once more to a byte pointer. That's a lot of steps to remember, and none of those are encoded as part of the `PSTR` type.
4. The `MB_OK` constant is part of the `Win32::UI::WindowsAndMessaging::MESSAGEBOX_STYLE` flag type in the Windows metadata, but in the generated code it's exposed as a standalone type. We need to infer from the `MB_` prefix which values are valid, which can feel like guesswork.

## Prior art

I believe the design principles of `windows-sys` can be summarized as follows:

1. Generate complete bindings to the windows APIs from the windows metadata.
2. Focus on compile performance over ergonomics.
3. There should be no lower-level bindings possible than `windows-sys`.

These goals feel similar in nature to other `-sys` bindings in the Rust ecosystem. I think the Webassembly bindings in particular make for a great analogue of what we're doing. In that ecosystem there are two main binding crates:

- `web-sys` provides generated bindings to all of the browser's DOM APIs, which number in the thousands.
- `js-sys` provides hand-authored core types such as "JavaScript string" and "JavaScript error" that can be converted to Rust equivalents. These are used in the API boundaries of `web-sys`.

The nice thing about this approach is that this compiles really quickly, and makes the raw `web-sys` bindings significantly easier to use without requiring each of the `web-sys` bindings to have individual wrappers. The conversion logic simply lives in the shared `js-sys` types.

## Improving the ergonomics of `window-sys`

I'm not sure whether we would want to expose a counterpart to `js-sys` as-is; but I think we can 

```rust
use windows_sys::{Win32::Foundation::*, Win32::System::Threading::*, Win32::UI::WindowsAndMessaging::*};

fn main() {
    unsafe {
        let event = CreateEventW(std::ptr::null_mut(), true.into(), false.into(), PWSTR::NULL);
        SetEvent(event);
        WaitForSingleObject(event, 0);
        CloseHandle(event);

        let flags = MESSAGEBOX::MB_OK;
        MessageBoxA(HWND(0), PSTR::from_str("Text").unwrap(), PSTR::from_str("Caption").unwrap(), flags);
    }
}
```

The changes made here are:

1. `BOOL` can convert from and to Rust's `Bool` type by implementing the `From` and `Into` traits.
2. `PWSTR` exposes a `NULL` constant for APIs where `PWSTR` is optional.
3. `MB_OK` is available as a constant from its logical `MESSAGEBOX` group.
4. `PSTR` implements `FromStr` and `Display` to convert to and from Rust strings.

These changes should all be fairly minimal, have little impact on compile times, but make it a lot easier to use the APIs by people who are not necessarily familiar with the Windows API.

## `windows` and `windows-sys`

There is a legitimate question of what the `windows` crate is for if we improve the bindings of `windows-sys`. I don't have a precise answer for this yet, but I think the root of it is: "The `windows` crate is able to trade compilation performance for ergonomic improvements in a way that `windows-sys` cannot."

This can take many shapes, and will depend on what we think is important, and we can support. For example it could be like [nix](https://docs.rs/nix/0.23.0/nix/) / [rustix](https://docs.rs/rustix/0.26.2/rustix/) is to [libc](https://docs.rs/libc/0.2.107/libc/), keeping API names as-is and mostly improving the type signatures. Or it could attempt to go further, and be like [localghost](https://docs.rs/localghost/0.2.1/localghost/) is to [web-sys](https://docs.rs/web-sys/0.3.55/web_sys/), creating ergonomic interfaces to collections of library calls.

Figuring this out is out of scope for this issue, but as `windows-sys` and `windows` might get closer to each other, I do think it's worth thinking about who the target audience is of each crate.

## Conclusion

I think with some minimal effort we can vastly improve the ergonomics of using the `windows-sys` APIs with minimal cost to compile-time performance. The only thing I'm not sure about is whether it would make sense to have a windows equivalent of `js-sys`, but other than that I'm somewhat confident this general direction would be in line with the goals we have for the crate.

Keen to hear thoughts on this!

cc/ @kennykerr @sivadeilra

**Comment by kennykerr** [comment]
Thanks for your thoughts! Here’s [how I introduced](https://github.com/microsoft/windows-rs/pull/1310) the `windows-sys` crate:

> Analyzing compile time indicates that most of the time building the `windows` crate is spent parsing function bodies. Those functions provide support for a more idiomatic developer experience. Even though those function bodies essentially compile away to nothing, the extra compile time makes adoption of the `windows` crate prohibitive in some cases. The `windows-sys` crate will simply have function declarations (externs), structs, and constants, and not include any function bodies. This is essentially the underlying ABI for the Windows API.
> 
> Today, the `windows` crate "inlines" this ABI and hides it from the developer. With the introduction of the `windows-sys` crate, the `windows` crate will instead defer to the `windows-sys` crate for those declarations. A developer can then choose to use the `windows` crate directly for convenience, safety, and productivity, or use the underlying `windows-sys` crate for no-compromise compile time when that matters most.

I introduced the `windows-sys` crate to combat the impression that the windows crate has significant compile time cost. While this impression is partly true, I am focused on reducing the compile time of the `windows` crate and plan to continue to bring it down further. Nevertheless, I think that the `windows-sys` crate offering the lowest-level API definitions along with the absolute best compile time will continue to be relevant for some scenarios. 

To that end, I would like to keep the distinction between the two very clear and am very reluctant to add bells and whistles to the `windows-sys` crate. If you desire more productivity or idiomatic bindings, then the `windows` crate is your best bet. If all you want is the function declarations, structs, and constants then the `windows-sys` crate is for. It is always tempting to add what seems like a simple and obvious helper here and there but deciding what merits adornment is very subjective. You might think `PSTR` and `BOOL` are important. The next person will say no `BSTR` and `VARIANT` are critical. The next will say something else and before you know it there’s a whole crate’s worth of helpers and the `windows-sys` crate just ends up looking more and more like the `windows` crate.

So, I see that as the role of higher-level crates. The `windows` crate being one of them but more importantly other crates that spring up to offer more targeted support for things like windowing, networking, web, and so on. At the end of the day, I believe the `windows` crate itself can get much, much better and also much, much faster to compile. I would like to keep the focus on improving the `windows` crate while offering the `windows-sys` crate as the zero-overhead fallback for the most demanding situations.

**Comment by riverar** [comment]
@yoshuawuyts Generally agree, but I feel like these improvements should target the `windows` crate, leaving `windows-sys` to continue serving as raw building material for aforementioned reasons.

> 1. `BOOL(1)` and `BOOL(0)` match to `true` and `false` respectively, but the knowledge that `1` is true and `0` is false is not encoded anywhere, meaning folks will either need to guess or find an example of `BOOL` in use.

Just wanted to point out here that BOOL is a Win32 API type that does not necessarily represent a Boolean at all. Surprise! [GetMessage](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessage#return-value) is a great example of how _fantastic_ BOOLs can be. 😂

**Comment by Zingam** [comment]
> A lot of the API patterns here are very C-like, and will feel unfamiliar to Rust programmers (e.g. I'm generalizing my own experience here). Here are some points people might run into:
 audience is of each crate.

Just a random thought here: Wasn't `windows-sys` conceived for C-lang-able users?

**Comment by kennykerr** [comment]
The difference between `windows` and `windows-sys` has now been largely settled, the former providing convenience helpers for greater ergonomics and safety while the latter providing only the raw bindings with no additional adornments. Since the original issue was created, the `windows-sys` crate has also been streamlined to simplify such examples as well. I don't see any more actionable work here so I'm going to close this issue.
