### ISSUE TITLE
Expose helper function to receive `IUnknown*` from C++ user code?

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#1323]
I'm currently using cbindgen to expose a `pub extern "C"` function to C++, and it needs to receive `IUnknown*`. AFAIK `IUnknown` in windows-rs behaves as `IUnknown*` and the `implement` macro has some magic to convert a raw pointer to `&Option<IUnknown>`. Could it be exposed as a helper function?

**Comment by kennykerr** [comment]
Yes, `IUnknown` and `Option<IUnknown>` have the same memory layout as `IUnknown*` in C++. You could transmute them.

**Comment by saschanaz** [comment]
So the parameter should be `void*` instead of `IUnknown*` and that void pointer can be transmuted to either `IUnknown` or `Option<IUnknown>`, and should be `core::mem::forget`-ed after use to prevent excessive drop, right?

I think at least a FAQ item can be helpful, but it's still before 1.0, so maybe not...

**Comment by kennykerr** [comment]
Yes... it depends on who owns the `IUnknown*` and which way you're moving/copying the reference. I plan to do an FAQ to cover stuff like this closer to 1.0 stabilization.
