### ISSUE TITLE
Can't call InjectMouseInput from InputInjector due to only allowing IIterable parameter

### ISSUE THREAD

**Issue by Corallus-Caninus** [microsoft/windows-rs#1326]
InjectMouseInput in windows::UI::Input::Preview::Injection::* only allows IIterables as its parameter but I cannot initialize Collections such as Vector due to a private constructor.

I would like to contribute but am worried I may  be doing something incorrect and noticed that vec! and collections from rust have been mentioned here before in several issues but have yet to be patched. 

I can think of 3 distinct solutions:
1. Should InjectMouseInput be overloaded to accept a single InjectedInputMouseInfo param 2. should collections be allowed (either to be constructed vicariously or 3. coerced from native rust collections)?

Thanks I can't wait to write more Rust on Windows.

**Comment by saschanaz** [comment]
A quick search gave me this, does this help?

https://github.com/microsoft/windows-rs/blob/b6a5c2051f6125baf65142e7582c3acdb387d827/crates/tests/legacy/implement/tests/into_impl.rs#L61

**Comment by Corallus-Caninus** [comment]
Thanks but I am having difficulty reproducing the derived implementation of IIterable for Iterable. It seems to build using test dependencies. Is there any other way to create IIterable from vec?

**Comment by Corallus-Caninus** [comment]
closing this in favor of #1340. In conclusion: use Array for generic type heap allocated collection for now since it is in core, I believe it may be easier to derive traits on this allocatable data structure but am not familiar enough with the Windows API to make such a design decision.
