### ISSUE TITLE
windows-rs support for Microsoft DIA SDK (Debug Interface Access)

### ISSUE THREAD

**Issue by jeanga** [microsoft/windows-rs#1327]
Hi !

I am willing to port existing code from C++ to Rust.
However, windows::Win32::System::Diagnostics::Debug exposes the dbghelp interfaces, I could not find the [Microsoft DIA SDK (Debug Interface Access)](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2022) interfaces.

Is there any plan to add these to windows-rs?
If so, how can I help?
If not, is #81 the only way to go?

Many thanks for windows-rs, it is precious to Windows developers switching to Rust.

**Comment by riverar** [comment]
@jeanga This should work today, if you drop in DIA SDK metadata. Let me write you a sample tomorrow, standby.

**Comment by riverar** [comment]
@jeanga Got most of a sample written today after overcoming some metadata challenges. Will share tomorrow, thanks for your patience.

**Comment by riverar** [comment]
Thanks for your patience @jeanga.

Check out this sample: https://github.com/microsoft/windows-samples-rs/pull/40

The high level overview is:
* [Microsoft.Windows.WinmdGenerator](https://www.nuget.org/packages/Microsoft.Windows.WinmdGenerator/0.2.118-preview) reads in raw DIA SDK idl/headers and outputs Windows Metadata
* The `windows` crate takes in this metadata and generates the appropriate Rust code
* The `sample` app then simply adds the appropriate `use` statements and uses DIA SDK APIs

What this sample doesn't show:
* Use of DIA SDK's NoRegCreate path (to avoid having to register msdia*.dll)
* Use of the pre-generated Windows APIs that come with the `windows` crate (currently blocked on #1338, will update asap)

Going to close this for now, but feel free to continue the discussion. Thanks!

**Comment by riverar** [comment]
Now uses pre-generated bindings. https://github.com/microsoft/windows-samples-rs/pull/40/commits/53ddb4fb052db1052db22c6c920ecc1f14042b92

**Comment by jeanga** [comment]
Just checked the sample! Thank you sooo much for the quick answer!
You ROCK!
