### ISSUE TITLE
Sample coding style

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#1328]
Is it the case that selectively mixing wide call and ANSI calls requires less traits to be implemented which then shortens the code listings? Or is it because the crate is still a work in progress and at some point in the future, it will be easy to have either all wide or all ANSI calls?

**Comment by riverar** [comment]
Hey @MRahilly, can you maybe elaborate a bit more on this? I'm not exactly following. I _think_ your question is: Why does the crate contain both -A and -W API variants?

**Comment by MRahilly** [comment]
I am happy with the need for -A and -W API call variants. I was wondering why many of the samples have mixed -A and -W calls when I would have expected samples to favor either one or the other. I am thinking of Win32 samples which typically use all -W calls except where occasionally necessary such as dealing with multi byte character sets.

**Comment by riverar** [comment]
@MRahilly Oh I understand now. In a sample, we're typically showcasing a particular pattern or feature and want to reduce the supporting code to a bare minimum. This may involve using simpler API variants in some spots.

On the topic of A variant APIs -- they are making a comeback! They are now used in Windows to support **UTF-8** character encoding https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page?WT.mc_id=WD-MVP-5002756 which could simplify Rust/Windows interop in some cases.

If you see a sample that you feel is particularly misrepresentative of the real world, or just bugs you, feel free to open a new issue. Thanks!

**Comment by MRahilly** [comment]
> @MRahilly Oh I understand now. In a sample, we're typically showcasing a particular pattern or feature and want to reduce the supporting code to a bare minimum. This may involve using simpler API variants in some spots.

That suggests a small note for beginners - "How to choose the -A or the -W variant to reduce lines of code".
