### ISSUE TITLE
the trait `IntoParam<'_, HSTRING>` is not implemented for `&str` 

### ISSUE THREAD

**Issue by ndarilek** [microsoft/windows-rs#1329]
How am I supposed to fix this *today*? Emphasis because *yesterday's* fix was apparently to add the "std" feature in 0.26. Now, the same code:

`context.RequestPurchaseAsync(&*config.microsoft_store_id)`

where `microsoft_store_id` is a `String`, no longer works.

As an aside, I'm not sure if I should be trying to keep up with this active churn. I'm hesitant to get too far behind because I have built and am hoping to build more crates that wrap some of this functionality, and having to make lots of significant changes at once in multiple crates is a bit daunting. I don't see this marked as preview any longer. Might it make sense to keep a changelog/migration guide for something this complex? The extensive use of features makes it hard to know if I'm missing a function call somewhere, missing a feature, etc.

Thanks.

**Comment by kennykerr** [comment]
Sorry for the confusion. The [changelog](https://github.com/microsoft/windows-rs/blob/master/.github/changelog.md) calls out [this change](https://github.com/microsoft/windows-rs/pull/1309). Initial `no_std` support assumed that `std` was required for all the string conversions but this is not the case. Still, some developers were concerned about implicit allocations so I added the `alloc` feature to enable those. So you will need to add the `alloc` feature. 

The PR where I [updated all of the samples to 0.27](https://github.com/microsoft/windows-samples-rs/pull/38) also illustrates the necessary changes. 

Sorry for the back and forth.

**Comment by ndarilek** [comment]
Oh wow, I missed the changelog. I didn't realize it was under .github/. Apologies. Any chance that might be moved to the top of the repo? I looked there, but didn't think to dig deeper.

Thanks.
