### ISSUE TITLE
Generated `windows-sys` pathnames are capitalized which is unexpected

### ISSUE THREAD

**Issue by yoshuawuyts** [microsoft/windows-rs#1346]
We had a customer provide feedback via Twitter on the `windows-sys` bindings. We currently generate capitalized module names, which conflicts with the naming guidelines outlined in [RFC 430](https://rust-lang.github.io/rfcs/0430-finalizing-naming-conventions.html). They appear to be a Rust programmer coming from `winapi`, and for them this appears to be odd enough to call out:

> why are all the module names camelcase?! this is non-conformant per rfc 430. i used to use the autogen bindings but this was changed at some point and it makes rust-analyzer very unhappy (not to mention the huge amount of disk space it eats up) so i switched back to winapi

_source: [@jc0f0116 on Twitter](https://twitter.com/jc0f0116/status/1461817011152072705)_

As I understand it we currently use capitalized path names because that matches the metadata. I do agree with the customer that it does feel somewhat out of place though, in part also because `winapi` has chosen to keep submodule paths lowercased.

I feel like it would be to our benefit if we can help make the transition from `winapi` to `windows-sys` as smooth as possible. This could be a relatively easy improvement for users trying out `windows-sys` for the first time. Is this something we can consider changing?

**Comment by kennykerr** [comment]
This was previously attempted but ultimately rejected. More info: https://github.com/microsoft/windows-rs/pull/646

**Comment by crlf0710** [comment]
Just want to leave a note here that in the current status quo improper capitalization also causes inferior error message and possible autofix diagnostic information supressed. Though this should be fixed in rustc-side.

For an example see https://github.com/rust-lang/rust/issues/82140 .

**Comment by yoshuawuyts** [comment]
I see, that reasoning makes sense. Thanks all!
