### ISSUE TITLE
Phasing out `build` and `generate` macros

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1347]
I'm starting to limit use of proc macros as much as possible. Part of that includes phasing out and ultimately removing the `build` and `generate` macros. With the introduction of pre-packaged APIs for both the `windows` and `window-sys` crates, the need for these macros is substantially reduced. I will probably refactor the `windows_gen` crate that handles all of the code to be more user friendly and can then be used directly as a library crate to support generation of bindings both for the `windows` and `window-sys` crates as well as for thirdy party components.

**Comment by yoshuawuyts** [comment]
> I will probably refactor the `windows_gen` crate that handles all of the code to be more user friendly and can then be used directly as a library crate to support generation of bindings both for the `windows` and `window-sys` crates as well as for third party components.

I've reserved the [`windows-bindgen`](https://crates.io/crates/windows-bindgen) name for exactly this purpose. When we publish `windows_gen` as its own crate, can we also consider renaming it? That would put it in good company with some of the other `bindgen` crates:

- [bindgen](https://crates.io/crates/bindgen) - FFI bindings to C  libraries for Rust
- [cbindgen](https://crates.io/crates/cbindgen) - FFI bindings to Rust libraries for C
- [wasm-bindgen](https://crates.io/crates/wasm-bindgen) - FFI bindings between WASM modules and JavaScript

**Comment by kennykerr** [comment]
Yes, that makes sense. The `windows_gen` crate is today just an implementation detail of the `windows` crate. The new "gen" crate I'm working on will be something that can be used directly so I can adopt the `windows-bindgen` crate name for that.
