### ISSUE TITLE
Add `alloc` feature to `std` feature 

### ISSUE THREAD

**Issue by ok-nick** [microsoft/windows-rs#1351]
https://github.com/microsoft/windows-rs/blob/23ff38bbbf46fb52460a9078b6292e250fb18157/Cargo.toml#L54

**Comment by kennykerr** [comment]
Thanks for the detailed explanation. 😅

This is intentional. Projects may need to use std features but not want to allow implicit allocations. Discussion here: https://github.com/microsoft/windows-rs/issues/1343
