### ISSUE TITLE
IPolicyConfigVista SetDefaultEndpoint is not implemented

### ISSUE THREAD

**Issue by yan0lovesha** [microsoft/windows-rs#1355]
The API in PolicyConfig.h which shown in below sample code is not implemented. 

```cpp
#include "Mmdeviceapi.h"
#include "PolicyConfig.h"
#include "Propidl.h"
#include "Functiondiscoverykeys_devpkey.h"
HRESULT SetDefaultAudioPlaybackDevice( LPCWSTR devID )
{
    IPolicyConfigVista *pPolicyConfig;
    ERole reserved = eConsole;

    HRESULT hr = CoCreateInstance(__uuidof(CPolicyConfigVistaClient), 
        NULL, CLSCTX_ALL, __uuidof(IPolicyConfigVista), (LPVOID *)&pPolicyConfig);
    if (SUCCEEDED(hr))
    {
        hr = pPolicyConfig->SetDefaultEndpoint(devID, reserved);
        pPolicyConfig->Release();
    }
    return hr;
}
```

**Comment by riverar** [comment]
PolicyConfig/SetDefaultAudioPlaybackDevice are not supported/documented APIs. Was something I added to my app EarTrumpet 6 or so years ago then became "documented" 😂.

You can certainly CoCreateInstance/QI for these manually but this is not a `windows` crate issue. Closing.

**Comment by yan0lovesha** [comment]
Just left my implementation here in case any others get to this issue.
https://github.com/yan0lovesha/AudioSwitch
