### ISSUE TITLE
core_app example crash: The Application Object must initially be accessed from the multi-thread apartment

### ISSUE THREAD

**Issue by helsus** [microsoft/windows-rs#1357]
Hello!

The [core_app](https://github.com/microsoft/windows-samples-rs/tree/master/core_app) example crashes and constantly relaunches

Environment:

- `windows-rs`: `0.27` and `0.28`
- `rustc`: `1.56.1`
- ` Windows 11`: `10.0.22000.0 (insiders, release preview channel)`

Steps to reproduce:
1) `git clone https://github.com/microsoft/windows-samples-rs.git`
2) `cd core_app`
3) Build & register app via `.\register.cmd`
4) Run app from the Start menu
5) The app constantly relaunches

`Exception thrown at 0x00007FFD01F2478C (KernelBase.dll) in sample.exe: WinRT originate error - 0x8001010E : 'The Application Object must initially be accessed from the multi-thread apartment.'.`

After some research (https://docs.microsoft.com/en-us/windows/win32/com/multithreaded-apartments) and looking other examples I've found that adding following lines fixes the crash. But I'm not familiar with the win32 and I'm not sure that that is a correct solution.

```rust
unsafe {
    CoInitializeEx(std::ptr::null_mut(), COINIT_MULTITHREADED)?;
}
```

**Comment by kennykerr** [comment]
Yep, that's the correct fix. Feel free to contribute otherwise I'll get it updated soon.
