### ISSUE TITLE
Improvements to documentation for `windows-sys`

### ISSUE THREAD

**Issue by yoshuawuyts** [microsoft/windows-rs#1358]
I've been integrating `windows-sys` in a few projects, and by far the most important thing I'm missing is the ability to [reference the docs on docs.rs](https://docs.rs/windows-sys/0.28.0/windows_sys/). I would be incredibly helpful if we could improve the following:

1. **Publish to docs.rs:** Build the docs with all features enabled on docs.rs so we can have an online reference. I believe this may be more feasible for `windows-sys` than it is for `windows`, but we'll have to verify whether this is possible.
2. **Build docs locally:** Provide a convenient way to build with all features enabled locally. Perhaps an `all` feature flag could be an option here? I was looking how to do this, and couldn't figure it out.
3. **Document per-type feature flags:** Document which features are required for a particular type to compile, just like with the `windows` crate.

There is probably more polish that could be applied after this, but these are some of the improvements we most clearly need. I'd be happy to take some of these on if we agree this would be a welcome addition. Thanks!

**Comment by kennykerr** [comment]
Yep, I've been meaning to publish the docs. You can use the `--all-features` flag to build and document everything. For windows-sys it's pretty quick and shouldn't be a problem to host on docs.rs. I'm just in the middle of overhauling the gen crate but feel to get the windows-sys crate ready for doc publishing.

**Comment by kennykerr** [comment]
#1369 fixes this as well - the next published update should include docs.

**Comment by yoshuawuyts** [comment]
@kennykerr amazing! :tada:
