### ISSUE TITLE
BSTR problem

### ISSUE THREAD

**Issue by dqtsth** [microsoft/windows-rs#1360]
Hi I find BSTR has problem. I put bad address in and call safe function and it crashes. I hope issue helps you. Sorry for my english

```
use windows::Win32::Foundation::BSTR;

fn main() {
    let x = BSTR(12345usize as _);
    dbg!(x.len());
}
```

```
error: process didn't exit successfully: `target\debug\bstr.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION
```

**Comment by kennykerr** [comment]
Yes, it's easy to misuse the string-related structs. Planning to fix this.

**Comment by kennykerr** [comment]
The BSTR field is now private.
