### ISSUE TITLE
`IsWindows10OrGreater` and similar are not exposed

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#1361]
Function is documented here: https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindows10orgreater

The same happens for all functions like `IsWindows<version>OrGreater`

**Comment by riverar** [comment]
Thanks for filing this. These are inline functions defined in the VersionHelpers.h header file, hence no metadata describing them and no crate representation. I can see a case for spinning out a `microsoft-version-helpers` or similar crate though. I'll ping you if/when that's available. (Doesn't sound difficult.)

Closing for now as there's no action for the `windows` crate, but feel free to continue the discussion

**Comment by poliorcetics** [comment]
We wrote internal helpers from available functions in `windows-rs`, but a blessed crate from Microsoft would be welcome indeed, though probably not high priority.

Thanks for the quick responses though !

**Comment by wmmc88** [comment]
@riverar was an official `microsoft-version-helpers` crate or similar ever published?

**Comment by riverar** [comment]
@wmmc88 No, sorry about that! Is this something you're looking for as well?

**Comment by wmmc88** [comment]
Yes. It would be nice to just have something in the windows crate that provides this, rather than needing to reimplement the logic.
