### ISSUE TITLE
`Handle::is_invalid` is incorrect for pseudo-handles

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#1363]
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocess says the returned `HANDLE` can have a value of `-1` and be correct.

Having `is_invalid` return `true` on such a handle seems wrong. Is this a bug or am I misunderstanding something in the docs ?

**Comment by poliorcetics** [comment]
Ah well https://devblogs.microsoft.com/oldnewthing/20040302-00/?p=40443, that won't be easy to fix

**Comment by kennykerr** [comment]
The `is_invalid` method just does a best effort at detecting run time failure from some API, but pseudo handles like those returned by `GetCurrentProcess` will never be "invalid" so there shouldn't be a need to validate them at run time. I don't consider this a bug just the quirky reality of the Win32 API.

**Comment by poliorcetics** [comment]
Yeah, I don't know of a way to distinguish them without creating a new type and that would be way more painful for API use than `is_invalid` being wrong once on a specific method.

**Comment by riverar** [comment]
There are a number of other pseudo handles across the Windows API surface, such as GetCurrentThread, GetCurrentProcessToken, and GetCurrentThreadEffectiveToken. It may be useful to have a `PseudoHandle` type that can provide the correct `is_invalid` result (or not offer the method at all), and impl `From<PseudoHandle> for Handle` for API compatibility.

**Comment by riverar** [comment]
Reflecting on this, perhaps an alternative is to just remove `is_invalid` altogether, as `-1` has been demonstrated to be semantically ambiguous. This would align with our efforts to keep the crate lean, and shouldn't cost developers much--they can replace legitimate `is_invalid` calls with a comparison to `INVALID_HANDLE_VALUE` and prune others. Thoughts?

**Comment by poliorcetics** [comment]
If you (maintainers) are willing to introduce `PseudoHandle` (and have the necessary information for it in metadatas), the `windows-rs` crate could then implement `IntoParam<HANDLE> for PseudoHandle`, `impl Handle for PseudoHandle` and `impl From<PseudoHandle> for HANDLE`. More use cases will probably pop up over time as the crate becomes more widely used, but I don't see other needed traits for now.

**Comment by kennykerr** [comment]
Yes, if `is_invalid` is causing any `confusion` I'd be inclined to just remove it as @riverar suggested. I'm in the process of aligning the `windows` and `windows-sys` code gen more closely so this may be where I land on this as the `windows-sys` crate doesn't have such adornments.

**Comment by poliorcetics** [comment]
Or maybe have both `is_invalid` and `is_null`, with clear documentation of what they test for ? One of them is needed at least, for easy checking, both would be nice.

**Comment by kennykerr** [comment]
Most Win32 handles now use their underlying types as of 0.29 so you can just use whatever types the documentation recommends for checking the validity of a handle.

**Comment by matthiasg** [comment]
Is there any example on how to use e.g. GetCurrentThreadEffectiveToken  ?

**Comment by kennykerr** [comment]
The `GetCurrentThreadEffectiveToken` function is defined as follows:

```C++
FORCEINLINE HANDLE GetCurrentThreadEffectiveToken(VOID)
{
    return (HANDLE)(LONG_PTR) -6;
}
```

Since the [win32 metadata](https://github.com/microsoft/win32metadata) ignores C++ functions (functions with bodies), it will not show up in the Rust bindings. But as you can see, this function just returns a constant so you can just write your own constant as a replacement.
