### ISSUE TITLE
Missing docs for `IntoParam`

### ISSUE THREAD

**Issue by fenhl** [microsoft/windows-rs#1365]
#1081 implemented `IntoParam<'_, PWSTR>` for `&OsStr`, but when I tried to use one as the first argument for [`GetFullPathNameW`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/fn.GetFullPathNameW.html) I got an error saying it's not implemented. The `IntoParam` trait is also not a link in the docs for that function, so I had to dig through the source to figure out that the `std` feature is needed to enable this implementation.

**Comment by kennykerr** [comment]
Thanks for the feedback. #1343 should simplify this.

**Comment by Halkcyon** [comment]
It looks like `IntoParam` _used_ to have docs, but they've since been moved/removed?

https://github.com/microsoft/windows-rs/pull/690

**Comment by kennykerr** [comment]
This should no longer be an issue as the `std` feature has been removed from the `windows` crate.

**Comment by fenhl** [comment]
It seems like `IntoParam` is still undocumented.

**Comment by kennykerr** [comment]
The source of this issue was what I fixed here. For docs you can track this issue: #1499
