### ISSUE TITLE
A Tic-Tac-Toe example for consideration

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#1366]
[tic_tac_toe.zip](https://github.com/microsoft/windows-rs/files/7612466/tic_tac_toe.zip)

**Comment by riverar** [comment]
@MRahilly This doesn't really make sense for the `windows` crate but perhaps makes more sense as a Pull Request (not an issue) to https://github.com/microsoft/windows-samples-rs/? 

Closing for now, but feel free to continue discussing here. Thanks!

**Comment by MRahilly** [comment]
Thanks @riverar. I was using the issue as an upload device for a possible beginners example. I must try and figure out Pull Requests.
