### ISSUE TITLE
Checking LSTATUS and creating PWSTR?

### ISSUE THREAD

**Issue by flatwound** [microsoft/windows-rs#1367]
Hi,

maybe a bit silly questions, I've only just started using Rust, 
1. is this the correct way to check an LSTATUS? Seems a bit verbose with the adding of .0 and casting to i32 for ERROR_SUCCES.  
2. Although this works, returning a PWSTR from the new_pwstr function looks to me like the vec would be dropped at the end of the function, leaving a dangling pointer in the PWSTR?
3. Is there a specific Windows-RS discord channel or forum where I could post more beginner questions that are not exactly issues with this crate?

```rust
use windows::Win32::System::Registry;
use windows::Win32::Foundation::ERROR_SUCCES;
fn main() {
    let h_key = Registry::HKEY_CURRENT_USER;
    let mut subkey = Registry::HKEY::default();
    let subkey_path: PWSTR = new_pwstr("Console\\Git Bash");
    let status =
        unsafe { Registry::RegOpenKeyExW(&h_key, subkey_path, 0, Registry::KEY_READ, &mut subkey) };

    if status.0 != ERROR_SUCCESS.0 as i32 {
        panic!("Could not open regsitry")
    }
    println!("Hello, world, I found {} subkeys and {} values in {:?}",subkey_count, value_count, subkey_path);
}
fn new_pwstr(str: &str) -> PWSTR {
    let mut vec: Vec<u16> = std::ffi::OsStr::new(str)
        .encode_wide()
        .chain(std::iter::once(0))
        .collect();
    PWSTR {
        0: vec.as_mut_ptr(),
    }
}
```

**Comment by MarijnS95** [comment]
Yes there are many issues about being able to safely create and use (ie. dereference) strings with raw pointers, without attaching the lifetime: https://github.com/microsoft/windows-rs/issues/1360, https://github.com/microsoft/windows-rs/issues/1353, https://github.com/microsoft/windows-rs/issues/1307, https://github.com/microsoft/windows-rs/issues/1207, https://github.com/microsoft/windows-rs/issues/1342 and probably many more.

Kenny mentioned that's on the to-do list but looks to be preoccupied with other issues, so I'll probably take a stab at implementing the desired safety guards akin to `&str` APIs and the `widestring` crate people have come accustomed to.

**Comment by kennykerr** [comment]
Note that if you specify the `alloc` feature you can just pass a literal to functions like `RegOpenKeyExW` e.g.: 

`RegOpenKeyExW(&h_key, "Console\\Git Bash", ...)`

**Comment by kennykerr** [comment]
Regarding the LSTATUS, that's probably more a question for the win32 metadata folks. Opened this issue:

https://github.com/microsoft/win32metadata/issues/760

**Comment by flatwound** [comment]
Thanks for the quick response! I'll keep an eye on the issue you opened for the LSTATUS. For now my questions have been answered, so I'll close this issue. I was pointed to the windows-rs channel on the rust-lang-community discord server over at: https://discord.gg/rust-lang-community. I'll use that to ask more beginner questions.

**Comment by riverar** [comment]
@flatwound I'm there too (WithinRafael#7014) 👋
