### ISSUE TITLE
`Error::win32_error` is difficult to use

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#1370]
[`Error::win32_error()`](https://microsoft.github.io/windows-docs-rs/doc/windows/runtime/struct.Error.html#method.win32_error) returns an `Option<u32>` but the type [`WIN32_ERROR`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.WIN32_ERROR.html) cannot be compared against `u32`s. This leads to code such as:

```rust
match error.win32_error() {
    Some(code) if code == ERROR_SOME_WIN32_ERROR.0 => ...
    Some(code) if code == ERROR_OTHER_WIN32_ERROR.0 => ...
    Some(_) | None => ...
    // Or `_ => ...` instead of the line above
}
```

Is it possible to return `Option<WIN32_ERROR>` or to provide a simple way to convert from one to the other ? `WIN32_ERROR` is gated behind a feature flag (for understandable reasons) so simply changing the return type may not be possible but instead providing something like:

```rust
impl Error {
    #[cfg(Win32_Foundation)]
    fn win32_error(&self) -> Option<WIN32_ERROR> { /* ... */ }
    
    fn raw_win32_error(&self) -> Option<u32> { /* ... */ }
}
```

**Comment by AlyoshaVasilieva** [comment]
To convert from `Option<u32>` to `Option<WIN32_ERROR>` you can do `theoption.map(WIN32_ERROR::from)` or just `theoption.map(WIN32_ERROR)`

**Comment by poliorcetics** [comment]
Less cumbersome than what I did before, thanks ! Still, `WIN32_ERROR` is used a lot in Windows APIs so having a helper may be worth it.
