### ISSUE TITLE
Documentation seems to be two versions out-of-date

### ISSUE THREAD

**Issue by danutsu** [microsoft/windows-rs#1373]
The docs at https://microsoft.github.io/windows-docs-rs/ cover version 0.26, but we're at 0.28. There have been some meaningful changes in the mean time, such as moving a bunch of stuff from `runtime` to `core`, that make it difficult to code against the 0.26 docs. Any chance they could be updated?

**Comment by kennykerr** [comment]
Thanks for the reminder - I plan to get that updated for both `windows` and `windows-sys` in the coming update. It's not automated at the moment because `docs.rs` cannot handle the size of the `windows` crate docs.

**Comment by kennykerr** [comment]
With the publication of 0.29 of both the `windows` and `windows-sys` crates, the docs have been updated and published for both:

windows: https://microsoft.github.io/windows-docs-rs/
windows-sys: https://docs.rs/windows-sys
