### ISSUE TITLE
Why is Abi hidden in the docs?

### ISSUE THREAD

**Issue by estokes** [microsoft/windows-rs#1375]
I'm a somewhat new user of this crate, and I've just finished using it to build an RTD server for Excel. One major thing that tripped me up during that process is that I had to extract the `IDispatch` interface for a callback object from a `VARIANT` that Excel passed me (the `IRTDUpdateEvent` object). In the union type of `VARIANT_0_0_0` it's a `RawPointer`, and it took me quite a while, and a trip to the source code, to figure out that I needed to call `Com::IDispatch::from_abi(ptr)` in order to get a proper `IDispatch` interface from this `RawPointer`. So I guess I have two questions.

- Am I doing something wrong? It does work, but maybe that's luck and I'm missing something huge. If I'm doing it wrong, then how am I supposed to get an `IDispatch` from a `VARIANT`?
- If I'm not doing it wrong, then why hide from me that `IDispatch` implements `Abi`? If there is some good reason it must remain hidden, then maybe a helper function in `VARIANT_0_0_0` that gets an `IDispatch` directly instead of a `RawPointer`?

**Comment by kennykerr** [comment]
The `Abi` trait is hidden as it is a low-level implementation detail needed for certain generic scenarios within the `windows` crate but should not be used directly. It's little more than a transmute though and I'd suggest you simply transmute yourself if you're casting from a pointer. The `VARIANT` struct is very difficult to use directly and really needs a hand-written wrapper. #539

**Comment by estokes** [comment]
Casting the pointer, my initial solution, caused a crash. I guess I need to
read exactly what abi does in the case of an interface and figure out what
it does differently.

On Tuesday, December 7, 2021, Kenny Kerr ***@***.***> wrote:
> The Abi trait is hidden as it is a low-level implementation detail needed
for certain generic scenarios within the windows crate but should not be
used directly. It's little more than a transmute though and I'd suggest you
simply transmute yourself if you're casting from a pointer. The VARIANT
struct is very difficult to use directly and really needs a hand-written
wrapper. #539
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci6.googleusercontent.com/proxy/emGw57kaz2zQdFNnfNxrLGJ2w7aDZRI0H5DuUkNNcwTyTC6wdXJHRtOMgl1AuDFMCp9nrnUSU8wCLNTaX_ZHgXJxYg8DVkAqRaIs6Hpgfzu7vYFEHLFnyTKvOeVj5UpZTpwNnIBLrUpOkD5QW522NK1NrqlU8dKyDS6g-1VvAODog29W-upv2aabmD-R7b76gWNe475MBpxDU_IJ7vIsHKLXG5bPXu6wcXik5Fe4Xw=s0-d-e1-ft#https://github.com/notifications/beacon/ABWJHLFQZVHIX4P553P6CBLUPZF37A5CNFSM5JO7G24KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHLTCXNI.gif>

**Comment by estokes** [comment]
In any case if you're planning to build a wrapper for VARIANT that solves my issue. Thanks!
