### ISSUE TITLE
Allow `In` parameters to skip the need for `Option` in implements methods.

### ISSUE THREAD

**Issue by luqmana** [microsoft/windows-rs#1376]
For a concrete example, I have:

```rust
#[implement(Windows::ApplicationModel::Background::IBackgroundTask)]
pub struct MyBackgroundTask;

impl MyBackgroundTask {
    fn Run(&self, task: &Option<IBackgroundTaskInstance>) -> Result<()> {
        ...
    }
}
```

The implements macro wants me to use an Option for the task argument to `Run` but afaik the metadata already marks it as an `[In]` (and not `unique`) parameter which I thought meant it wasn't allowed to be null.

For now, I'm just sticking something like this at the top but feels a little overly verbose:
```rust
let task = task.as_ref().ok_or(Error::from(E_UNEXPECTED))?;
```

**Comment by chwarr** [comment]
I thought the [`[unique]`](https://learn.microsoft.com/windows/win32/midl/unique) and [`[ptr]`](https://learn.microsoft.com/windows/win32/midl/ptr) attributes vs. the [`[ref]`](https://learn.microsoft.com/windows/win32/midl/ref) attribute were what one used to indicate nullability of pointers in COM (and by extensions WinRT?). And the default is `[ref]` which does not allow null.

In the case of `IBackgroundTask`, I don't see `[unique]` or `[ref]` on the `task` parameter. So, AFAICT, `task` does not allow null. And there's no [`[pointer_default]`](https://learn.microsoft.com/windows/win32/midl/pointer-default) that I can find, but I might now be looking in the right place.

Is the issue that this metadata is "advisory" without enforcement in all languages?
