### ISSUE TITLE
Add `HStringReference` wrapper to skip the normal HString drop impl

### ISSUE THREAD

**Issue by luqmana** [microsoft/windows-rs#1377]
I was playing around with making a runtime class implemented with windows-rs activatable. I have it working but ran into one small wart. My `DllGetActivationFactory` gets called appropriately but using the `windows::core::HSTRING` type means that it's Drop impl will run when it goes out of scope thus freeing the string. But unfortunately the caller will also try to free the string leading to a double-free. For now I'm just using `std::mem::forget` to skip the Drop on the Rust side but was wondering if it would be worth it to have a wrapper for this kind of situation that doesn't invoke Drop.

```rust
#[no_mangle]
pub unsafe extern "system" fn DllGetActivationFactory(
    activatableClassId: HSTRING,
    factory: *mut Option<IActivationFactory>,
) -> HRESULT {
    ...
}
```

**Comment by kennykerr** [comment]
That's not what HSTRING references are for. 

If you are declaring your own ABI type/signature then what you really want to use is `ManuallyDrop<HSTRING>` as that would be compatible with the ABI requirements for the `DllGetActivationFactory` function.

**Comment by luqmana** [comment]
Ah, that makes sense & `ManuallyDrop<HSTRING>` fits perfectly. Thanks!
