### ISSUE TITLE
RaiseException should return !

### ISSUE THREAD

**Issue by lzybkr** [microsoft/windows-rs#1382]
### Motivation

I want to raise an exception from a `alloc_error_handler` so my callers can optionally return `E_OUTOFMEMORY` if they don't want to exit.

The error handler in Rust is defined to return `!` (doesn't return), so it would seem like I could just call `RaiseException`.

As things are now, I have to call `core::intrinsics::abort` in my handler.

**Comment by kennykerr** [comment]
This is blocked on https://github.com/microsoft/win32metadata/issues/764

**Comment by kennykerr** [comment]
The metadata now includes the necessary attribute to indicate such functions and #1485 brings support to Rust.

**Comment by kennykerr** [comment]
`0.32.0` has now been published and includes this change.
