### ISSUE TITLE
SC_HANDLE missing is_null()

### ISSUE THREAD

**Issue by Huntragon** [microsoft/windows-rs#1385]
I was updating a project that uses this crate to register and run an executable as a service in windows, and I ran into the issue that SC_HANDLE (returned from OpenServiceA) does not implement is_null() to see if the call executed successfully (which it did in the version I had before, 0.18.0).
As a workaround, I tried to do what the windows API says, to check if the return value is NULL (in which case it's not a valid handle). I've checked to see if there is a NULL constant defined somewhere and couldn't find it, so I'm guessing for now I have to use 0 directly (which I assume is what NULL means in the windows API, I don't have much experience with the API directly, only through the Rust crate)

**Comment by kennykerr** [comment]
`SC_HANDLE` is now just a type alias for `isize` consistent with the underlying Win32 definition. You can therefore just compare against `0` as that is the equivalent of `NULL`.

**Comment by travispaul** [comment]
For future travelers as of 0.30 SC_HANDLE has an `is_invalid()` method 🚀

**Comment by tim-weis** [comment]
This is true for the `windows` crate ([`SC_HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Security/struct.SC_HANDLE.html)) that restored newtypes for handles as of #1423 with version 0.30.0. In the `windows-sys` crate [`SC_HANDLE`](https://docs.rs/windows-sys/latest/windows_sys/Win32/Security/type.SC_HANDLE.html) remains a type alias for `isize` and Kenny's comment above still applies here.
