### ISSUE TITLE
Many types now missing Debug implementations in v0.29

### ISSUE THREAD

**Issue by qdot** [microsoft/windows-rs#1392]
Similar to #1391, tried to compile https://github.com/deviceplug/btleplug with no changes, got a bunch of places where we expect Debug implementations that are now missing with no code changes other than updating from v0.28.

```
error[E0277]: `GattCommunicationStatus` doesn't implement `std::fmt::Debug`
  --> src\winrtble\ble\characteristic.rs:69:67
   |
69 |                 format!("Windows UWP threw error on write: {:?}", result).into(),
   |                                                                   ^^^^^^ `GattCommunicationStatus` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `GattCommunicationStatus`
   = note: this error originates in the macro `$crate::__export::format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `GattReadResult` doesn't implement `std::fmt::Debug`
  --> src\winrtble\ble\characteristic.rs:88:66
   |
88 |                 format!("Windows UWP threw error on read: {:?}", result).into(),
   |                                                                  ^^^^^^ `GattReadResult` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `GattReadResult`
   = note: this error originates in the macro `$crate::__export::format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `BluetoothConnectionStatus` doesn't implement `std::fmt::Debug`
  --> src\winrtble\ble\device.rs:47:42
   |
47 |                     trace!("state {:?}", sender.ConnectionStatus());
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^ `BluetoothConnectionStatus` cannot be formatted using `{:?}` because it doesn't implement `std::fmt::Debug`
   |
   = help: the trait `std::fmt::Debug` is not implemented for `BluetoothConnectionStatus`
   = note: this error originates in the macro `format_args` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by qdot** [comment]
Ok I just saw in the v0.29 Changelog that Debug is no longer implemented by default in the new generator. Is there a flag to turn that back on somehow if needed?

**Comment by kennykerr** [comment]
Yes, the `Debug` trait is not provided by the new `bindgen` crate. Is that something that I should preserve? I'm trimmed it down to the basics as far as traits go as it all adds up to the expense of building with the `windows` crate but it would help to understand whether this is something that is just a convenience or is really needed.

**Comment by poliorcetics** [comment]
Deriving `Debug` on pretty much everything is something we do by default internally, it would be really nice to have it for `windows` types, manually implementing it is cumbersome.

**Comment by roblabla** [comment]
IMO, Debug should really be implemented on everything. It is part of the Rust API Guidelines: https://rust-lang.github.io/api-guidelines/debuggability.html?highlight=debug#all-public-types-implement-debug-c-debug and are a huge help when debugging issues, as they allow quickly printing the contents of a structure. The problem with not implementing debug is that it causes a cascade of problems: Structures containing windows-rs structs will themselves not be able to derive debug, neither will their parent structures, etc... This makes working with crates that don't implement debug *incredibly* painful.

I really hope that this is reverted, or at least that a compile-time option to enable Debug is provided.

**Comment by kennykerr** [comment]
Good feedback. Much appreciated.

**Comment by qdot** [comment]
Thanks for being so responsive on this! :)
