### ISSUE TITLE
 Build errors moving up from 0.28.0 to 0.29.0 

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#1394]
HWND(0)
leads to error[E0423] expected function, struct or tuple variant, found type alias `HWND`

**Comment by riverar** [comment]
Hi @MRahilly, please use the bug issue template.

**Comment by tim-weis** [comment]
With version 0.29 tuple-like structs (like `HWND`) were replaced with type aliases. In this specific case you would probably use `0` in place of `HWND(0)` to solve the immediate issue. This change is being discussed in #1393.

**Comment by MRahilly** [comment]
That sounds good. Thank you Tim.
