### ISSUE TITLE
Which channel should I use stable or nightly with crate windows?

### ISSUE THREAD

**Issue by onlymaresia** [microsoft/windows-rs#1400]
I tried to compile the example in crates.io and got the following error:

```
error[E0658]: use of unstable library feature 'bool_to_option'
  --> C:\Users\r410c\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.29.0\src\core\weak_ref_count.rs:18:119
   |
18 | ...   self.0.fetch_update(Ordering::Relaxed, Ordering::Relaxed, |count_or_pointer| (!is_weak_ref(count_or_pointer)).then(|| count_or_poin...
   |                                                                                                                     ^^^^
   |
   = note: see issue #64260 <https://github.com/rust-lang/rust/issues/64260> for more information
```

Maybe it's a bug if the intention is to use the stable channel but I'm not sure if I should use stable or nightly when developing with this crate.

First time I open an issue, I don't know if I flag it as a bug.

**Comment by mominul** [comment]
I think you are using an earlier version of Rust. Can you try compiling the codes using the latest stable version of the Rust compiler?

**Comment by onlymaresia** [comment]
> I think you are using an earlier version of Rust. Can you try compiling the codes using the latest stable version of the Rust compiler?

You're right, I upgraded to 1.57.0 now, sorry for my lack of attention.
