### ISSUE TITLE
Bug: Docs for DirectX 12 appear messed up in Chrome

### ISSUE THREAD

**Issue by Zingam** [microsoft/windows-rs#1401]
### Which crate is this about?

windows-*

### Crate version

0.29.0

### Summary

https://docs.rs/windows-sys/0.29.0/windows_sys/Win32/Graphics/Direct3D12/index.html
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Direct3D12/index.html
![Screenshot 2021-12-25 141603](https://user-images.githubusercontent.com/3337419/147384672-a7b31b3f-aa87-428e-9ac2-2f61680a0d97.png)

**Comment by kennykerr** [comment]
This is a `rustdoc` bug that I believe has been reported (I've seen mention of it before) but I can't find the specific issue. Anyway, you can search for it here:

https://github.com/rust-lang/docs.rs/issues
