### ISSUE TITLE
Bug: constant C++ pointer generates mutable Rust pointer

### ISSUE THREAD

**Issue by kaivol** [microsoft/windows-rs#1402]
### Which crate is this about?

windows

### Crate version

0.29.0

### Summary

Constant pointer in a C++ struct (`const T*`) generates a mutable Rust pointer (`*mut T`).
Occurs in CF_OPERATION_INFO ([source](https://docs.microsoft.com/en-us/windows/win32/api/cfapi/ns-cfapi-cf_operation_info), [Rust](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/CloudFilters/struct.CF_OPERATION_INFO.html))

### Expected behavior

[CF_OPERATION_INFO ](https://docs.microsoft.com/en-us/windows/win32/api/cfapi/ns-cfapi-cf_operation_info) in cfapi.h 
````cpp
typedef struct CF_OPERATION_INFO {
  ULONG                    StructSize;
  CF_OPERATION_TYPE        Type;
  CF_CONNECTION_KEY        ConnectionKey;
  CF_TRANSFER_KEY          TransferKey;
  const CORRELATION_VECTOR *CorrelationVector;
  const CF_SYNC_STATUS     *SyncStatus;
  CF_REQUEST_KEY           RequestKey;
} CF_OPERATION_INFO;
````

should generate

````rust
pub struct CF_OPERATION_INFO {
    pub StructSize: u32,
    pub Type: CF_OPERATION_TYPE,
    pub ConnectionKey: CF_CONNECTION_KEY,
    pub TransferKey: i64,
    pub CorrelationVector: *const super::super::System::CorrelationVector::CORRELATION_VECTOR,
    pub SyncStatus: *const CF_SYNC_STATUS,
    pub RequestKey: i64,
}
````

### Actual behavior

Actual generated [definition](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/CloudFilters/struct.CF_OPERATION_INFO.html):

````rust
pub struct CF_OPERATION_INFO {
    pub StructSize: u32,
    pub Type: CF_OPERATION_TYPE,
    pub ConnectionKey: CF_CONNECTION_KEY,
    pub TransferKey: i64,
    pub CorrelationVector: *mut super::super::System::CorrelationVector::CORRELATION_VECTOR,
    pub SyncStatus: *mut CF_SYNC_STATUS,
    pub RequestKey: i64,
}
````

### Additional comments

Maybe I misunderstood how C++ pointers correspond to Rust pointer?

**Comment by AhmadAlHallak** [comment]
I don't use C++ much, but I think that you are incorrect in your understanding of the syntax for `const` in C++.
`const T* ptr` declares a pointer `ptr` to a constant value of type `T`, not a constant pointer to `T`
To declare a constant pointer you would do it like: ` T * const ptr`. This declares a constant pointer `ptr` to a value of type T.

So I believe that this is working as intended.

**Comment by MarijnS95** [comment]
@AhmadAlHallak `T * const ptr` makes `ptr` immutable (you cannot make it point to something else), but keeps the thing `T` that it points to mutable (ie. you can mutate fields of `T` and call non-`const` functions on it).

Rust doesn't have the concept of (im)mutable fields in a struct. Whenever you have a mutable borrow to a `CF_OPERATION_INFO`, you can update the pointers `CorrelationVector` and `SyncStatus` to point to something else. In other words, there's no way to tell `T * const ptr` apart from `T * ptr`.

The reporter is however asking about `const T * ptr` (a non-`const` pointer-value to a `const` object of type `T`). In Rust, this is represented as `*const T` (which is the other way around from C(++)) so that it reads from left-to-right: "this type is a _pointer_, to _something that cannot be mutated_, of type `T`".

**Comment by AhmadAlHallak** [comment]
@MarijnS95 Yeah I believe you are right. The statement "`Constant pointer in a C++ struct (const T*)`" in the summary threw me off. of the actual problem, I should've gone over the actual problem more thoroughly instead of just focusing on the summary itself. 
Thanks for pointing  my error.

**Comment by MarijnS95** [comment]
Yeah I guess `constant pointer` has always had this ambiguous meaning.

**Comment by kennykerr** [comment]
The win32 metadata now includes additional information to capture this const-ness. I should be able to plumb this through to Rust:

```C#
public struct CF_OPERATION_INFO
{
	public uint StructSize;

	public CF_OPERATION_TYPE Type;

	public CF_CONNECTION_KEY ConnectionKey;

	public LARGE_INTEGER TransferKey;

	[Const]
	public unsafe CORRELATION_VECTOR* CorrelationVector;

	[Const]
	public unsafe CF_SYNC_STATUS* SyncStatus;

	public LARGE_INTEGER RequestKey;
}
```

**Comment by kennykerr** [comment]
`0.32.0` has now been published and includes this change.
