### ISSUE TITLE
InputStreamOptions flags enum no longer supports BitOr in 0.29.0

### ISSUE THREAD

**Issue by mattico** [microsoft/windows-rs#1403]
Not sure if this was an intentional part of the generator simplification.

`Windows.Storage.Streams.InputStreamOptions` no longer supports `BitOr` which makes certain code much less ergonomic:

```diff
- reader.SetInputStreamOptions(InputStreamOptions::Partial | InputStreamOptions::ReadAhead)?;
+ reader.SetInputStreamOptions(InputStreamOptions(InputStreamOptions::Partial.0 | InputStreamOptions::ReadAhead.0))?;
```

Presumably other `[Flags]` enums are similar but I haven't checked since the generated documentation is still for 0.28.0.

**Comment by kennykerr** [comment]
Yes, this is a regression in the new generator. I'll get this fixed up.
