### ISSUE TITLE
No way to implement GetRuntimeClassName

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-rs#1405]
### Motivation

`ActivationFactory` [documentation](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/activationfactory-class?view=msvc-170#getruntimeclassname) states that `GetRuntimeClassName` should return “ the runtime class name of the object that the current `ActivationFactory` instantiates.”

Currently, this is not possible to do using `windows-rs` crate.

### Drawbacks

None

### Rationale and alternatives

This makes [authoring WinRT components](https://github.com/Alovchin91/winrt-component-rs) incomplete and potentially error-prone.

**Comment by kennykerr** [comment]
Yes, this is on my radar for the revamped implement macro.

**Comment by kennykerr** [comment]
The trait-based `implement` macro (#1345) will now implement `GetRuntimeClassName` automatically (here's [an example](https://github.com/microsoft/windows-rs/blob/master/crates/tests/implement_identity/tests/test.rs)).

Note that this is currently limited to interfaces. Classes (and exclusive interfaces) are on the way (#1094).

**Comment by Alovchin91** [comment]
Thanks! 🙂 I guess it's still impossible to implement it for `IActivationFactory`, right? Would it be useful to have an ability to override a default implementation?

**Comment by kennykerr** [comment]
For most scenarios that shouldn't matter, but yes I plan to support activation factories directly, so you won't have to think about implementing that. I also considered providing an option to override the default implementation using a trait if needed, but I'm not there yet.
