### ISSUE TITLE
Specify input .winmd files in windows-bindgen

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-rs#1406]
### Motivation

Currently `windows-bindgen` crate seems to always look for .winmd files in .windows subdirectory. There should be a way to specify input files/directories.

### Drawbacks

The need to specify input path, or a more complex logic selecting defaults

### Rationale and alternatives

When generating a .winmd file (see [WinRT component sample](https://github.com/Alovchin91/winrt-component-rs)), I would like to put it into cargo’s `$OUT_DIR` and then generate a projection from it.

**Comment by kennykerr** [comment]
Yes, the underlying reader used by the bindgen crate is shared by the older gen crate. Once I've finally removed the gen crate this should be simpler and I expect the bindgen crate simply to rely on procedural input to declare winmd files.
