### ISSUE TITLE
Bug: `mismatched types: ManuallyDrop<PROPVARIANT>`

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#1408]
### Which crate is this about?

windows

### Crate version

0.29.0

### Summary

```rust
#[implement(
    Windows::Win32::UI::Shell::PropertiesSystem::IInitializeWithStream,
    Windows::Win32::UI::Shell::PropertiesSystem::IPropertyStore,
    Windows::Win32::UI::Shell::PropertiesSystem::IPropertyStoreCapabilities
)]
#[derive(Default)]
pub struct Foo {
}
```

### Expected behavior

No "mismatched types", only "no method" errors.

### Actual behavior

```
mismatched types
expected fn pointer `unsafe extern "system" fn(_, _, *mut PROPVARIANT) -> HRESULT`
      found fn item `unsafe extern "system" fn(_, _, *mut ManuallyDrop<PROPVARIANT>) -> HRESULT {Foo_box::abi4}`rustcE0308
properties.rs(142, 1): parentheses are required to parse this as an expression: `(`, `)`
mismatched types
expected fn pointer `unsafe extern "system" fn(_, _, *const PROPVARIANT) -> HRESULT`
      found fn item `unsafe extern "system" fn(_, _, *const ManuallyDrop<PROPVARIANT>) -> HRESULT {Foo_box::abi5}`rustcE0308
properties.rs(142, 1): parentheses are required to parse this as an expression: `(`, `)`
```

### Additional comments

```
features = [
  "alloc",
  "build",
  "Win32_Graphics_Imaging",
  "Win32_Foundation",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_LibraryLoader",
  "Win32_System_SystemServices",
  "Win32_UI_Shell",
  "Win32_UI_Shell_PropertiesSystem",
]
```

**Comment by kennykerr** [comment]
The implement macro still relies on the old gen crate. I'm planning to revamp that based on traits and that should fix this kind of issue.

**Comment by knopp** [comment]
I think this also applies to [`IDataObject`](https://github.com/microsoft/windows-rs/blob/b6a5c2051f6125baf65142e7582c3acdb387d827/crates/tests/legacy/data_object/tests/test.rs). Any timeline on this? It means we're stuck on 0.28 and there are quite large code generation changes in 0.29.

**Comment by knopp** [comment]
Nevermind, I found https://github.com/microsoft/windows-rs/issues/1345.

**Comment by kennykerr** [comment]
Yep, I hope to have the new `implement` macro available for the 0.31 release.

**Comment by knopp** [comment]
> Yep, I hope to have the new `implement` macro available for the 0.31 release.

Thanks! I think the biggest change for us in 0.29 was handle types changed to isize, which seems to be reverted in 0.30 (happy to see that happening), so I don't mind staying on 0.28 longer.

**Comment by kennykerr** [comment]
This was recently fixed with the introduction of the trait-based `implement` macro (#1345). 

I have added a test to confirm this particular repro works (#1461).

Note that the new implementation support currently requires a `nightly` compiler. Let me know whether that's a big problem in the short term. Getting it to work with `stable` isn't very practical until Rust gets a few small upgrades...

https://github.com/microsoft/windows-rs/blob/84737273a50ca3699d3f0a23ac89e1e2cce653b7/crates/libs/windows/src/lib.rs#L5-L6

**Comment by knopp** [comment]
Requiring nightly is a pretty significant issue. We're using windows-rs in a library crate and thus can't really force nightly for users. That means we would be stuck with 0.28 until these stabilize.

**Comment by kennykerr** [comment]
There's a very messy workaround that I'm trying to avoid, so I've enlisted some help to speed these nightly features along.

**Comment by saschanaz** [comment]
It sounds reasonable to me since the version of this library is still 0.x.
