### ISSUE TITLE
Bug: Failed to build windows-sys v0.28 for UWP targets

### ISSUE THREAD

**Issue by bdbai** [microsoft/windows-rs#1411]
### Which crate is this about?

windows-sys

### Crate version

0.28.0

### Summary

```toml
[package]
name = "testlib"
version = "0.1.0"
authors = ["bdbai <bdbaiapp@163.com>"]
edition = "2021"

[dependencies]
windows-sys = { version = "0.28", features = ["Foundation_Collections"] }
```
```rust
fn main() {
    #[allow(unused_imports)]
    use windows_sys;
}
```
```powershell
cargo build -Z build-std=std,panic_abort --target x86_64-uwp-windows-msvc
```

### Expected behavior

The program compiles successfully.

### Actual behavior

   Compiling testlib v0.1.0 (D:\proj\testrs\testlib)
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "D:\\soft\\vs2022\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX64\\x64\\link.exe" "/LIBPATH:D:\\soft\\vs2022\\VC\\Tools\\MSVC\\14.30.30705\\lib\\x64\\store" "/NOLOGO" "/APPCONTAINER" "mincore.lib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.12vmw4gj9nfwec88.rcgu.o" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.1j1n6no1c99akr0j.rcgu.o" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.1jk4kivmwworo4w.rcgu.o" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.27gpty3m03fap44q.rcgu.o" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.4232um37ftko5bak.rcgu.o" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.52aknw0u11xqg9o0.rcgu.o" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.3y3ebs8hltnhz6at.rcgu.o" "/LIBPATH:D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps" "/LIBPATH:D:\\proj\\testrs\\testlib\\target\\debug\\deps" "/LIBPATH:C:\\Users\\bdbai\\.rustup\\toolchains\\nightly-2022-01-01-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-uwp-windows-msvc\\lib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libwindows_sys-83302516282eaf16.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libstd-887136ed81f7457d.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libpanic_unwind-0c7692820fe96ff7.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libstd_detect-121b5eaf2b92134f.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\librustc_demangle-64710a2d26a0f79a.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libhashbrown-d723a7a0db3770a4.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\librustc_std_workspace_alloc-c1810ac5ca88d78b.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libunwind-012d9bb6d5e8961d.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libcfg_if-9d3295dd49b34d62.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\liblibc-3e453c293f500f34.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\liballoc-7100162ff8163776.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\librustc_std_workspace_core-ca4d8718395fe3fa.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libcore-f5e35ad5f4b3cb6d.rlib" "D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\libcompiler_builtins-358995a960b47c60.rlib" "windows.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\bdbai\\.rustup\\toolchains\\nightly-2022-01-01-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-uwp-windows-msvc\\lib" "/OUT:D:\\proj\\testrs\\testlib\\target\\x86_64-uwp-windows-msvc\\debug\\deps\\testlib.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\bdbai\\.rustup\\toolchains\\nightly-2022-01-01-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\bdbai\\.rustup\\toolchains\\nightly-2022-01-01-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\bdbai\\.rustup\\toolchains\\nightly-2022-01-01-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\bdbai\\.rustup\\toolchains\\nightly-2022-01-01-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: LINK : fatal error LNK1181: cannot open input file 'windows.lib'

error: could not compile `testlib` due to previous error

### Additional comments

Seems like `windows_x86_64_msvc` was not picked for `x86_64-uwp-windows-msvc` target, and the build script for the targets did not recognize `x86_64-uwp-windows-msvc` as well.

https://github.com/microsoft/windows-rs/blob/dfc25285a289847ad88cbd206d169f7697be0dd4/crates/targets/x86_64_msvc/build.rs#L2

**Comment by kennykerr** [comment]
We should be able to use the same lib for uwp targets.

**Comment by riverar** [comment]
One note, `x86_64-uwp-windows-msvc` is a tier 3 toolset (read: could be broken at any time). And with UWP investment gone, I wonder if it'll see any further work / is worth worrying about.

**Comment by kennykerr** [comment]
Yes, I don't expect to add much/any support beyond simply unblocking the x86_64_msvc target to work with UWP (not introducing any new targets).

**Comment by kennykerr** [comment]
Feel free to jump in and update this. It's mostly just about updating the toml files for windows and windows-sys to add the appropriate target dependencies and ensuring the msvc targets include uwp targets in their build.rs checks.
