### ISSUE TITLE
IP Forward Table, row count fixed at 1

### ISSUE THREAD

**Issue by milesgranger** [microsoft/windows-rs#1417]
Hello,

Regarding [`MIB_IPFORWARDTABLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/NetworkManagement/IpHelper/struct.MIB_IPFORWARDTABLE.html), the row count is fixed at 1. The corresponding C++ docs indicate this can be of any size [ref](https://docs.microsoft.com/en-us/windows/win32/api/ipmib/ns-ipmib-mib_ipforwardtable). This also applies to [`MIB_IPFORWARD_TABLE2`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/NetworkManagement/IpHelper/struct.MIB_IPFORWARD_TABLE2.html).

Apologies if I've misunderstood anything here. :)

**Comment by kennykerr** [comment]
Yes, this is an issue I still need to work on. #443

**Comment by kennykerr** [comment]
Closing the duplicate.
