### ISSUE TITLE
Cross-platform WinRT components?

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-rs#1419]
Hi @kennykerr,

I remember the good ol' times when Xlang project appeared and there were some plans to make it a cross-platform cross-language technology.

Do you think it's still possible with Rust and custom authored WinRT components?

Maybe this is just my brainfart, but I didn't notice too much WinAPI usage in `windows::core`, and I suppose without `Win32` features it's probably rather easy to achieve?

**Comment by kennykerr** [comment]
While there are no plans to support this, it's probably a little simpler than cppwinrt to hack together, mostly because Rust only has a single compiler to contend with. 😉
