### ISSUE TITLE
Feature request: possibility to generate dynamic bindings for WLAN API

### ISSUE THREAD

**Issue by ancwrd1** [microsoft/windows-rs#1425]
### Motivation

On certain Windows installations (e.g. cloud instances) WLAN API is not available by default and an attempt to run the application linked statically to wlanapi.dll causes it to crash due to a missing DLL.
This effectively prevents any real-world applications from using WLAN bindings in the current form.

### Drawbacks

More complicated binding generator.

### Rationale and alternatives

The workaround we use currently in our code is to make a manual wrapper which uses `libloading` crate (and eventually LoadLibrary). This wrapper attempts to load wlanapi.dll and returns `Result<WlanApi, WindowsError>`.

In the impl block the wrapper contains the functions which just forward the request to the dynamically gotten entry points from the loaded DLL.

This approach, however, is not ideal as WLAN API is quite rich and duplicating all methods is a lot of work.

Code example:

```rust

fn wlan_result<F, T>(code: DWORD, f: F) -> Result<T, SystemError>
where
    F: FnOnce() -> T,
{
    if code != ERROR_SUCCESS {
        Err(SystemError::WlanError(code))
    } else {
        Ok(f())
    }
}

pub struct WlanApi {
    lib: Library,
    handle: HANDLE,
}
impl WlanApi {
    pub fn new() -> Result<Self, SystemError> {
        unsafe {
            let lib = Library::new("wlanapi.dll")?;

            let func: Symbol<WlanOpenHandleFunc> = lib.get(b"WlanOpenHandle")?;

            let mut version = 0;
            let mut handle = ptr::null_mut();
            let rc = func(2, ptr::null_mut(), &mut version, &mut handle);

            wlan_result(rc, move || WlanApi { lib, handle })
        }
    }

    pub fn enum_interfaces(&self) -> Result<WlanRef<WLAN_INTERFACE_INFO_LIST>, SystemError> {
        unsafe {
            let func: Symbol<WlanEnumInterfacesFunc> = self.lib.get(b"WlanEnumInterfaces")?;

            let mut intf_list = ptr::null_mut();
            let rc = func(self.handle, ptr::null_mut(), &mut intf_list);

            wlan_result(rc, move || WlanRef::new(intf_list, self))
        }
    }
```

### Additional context

It can be perhaps also implemented as a separate crate `wlan-rs` or similar.

**Comment by kennykerr** [comment]
Have you tried using [delay-loading](https://docs.microsoft.com/en-us/cpp/build/reference/linker-support-for-delay-loaded-dlls?view=msvc-170)? This is specific to MSVC but does exactly that. You can hook it up in Rust by adding the following to your `build.rs` file:

```rust
fn main() {
    println!("cargo:rustc-link-arg=/DELAYLOAD:wlanapi.dll");
    println!("cargo:rustc-link-lib=static=delayimp");
}
```

**Comment by ancwrd1** [comment]
The problem with delayed loading is the recovery code. As far as I know this requires writing a compiler-specific low level C using structured exceptions and then interfacing it via FFI (in case the library cannot be loaded). And simply checking for DLL presence in advance is not reliable I guess (WinSxS, etc).
But I'll give it a try anyway, thanks for the idea.

**Comment by kennykerr** [comment]
I've never tried to "recover" from delay load failure. Rather I would do some kind of version check *before* calling the delay loaded imports. This can be an OS version check or a call to LoadLibrary or whatever way you think reliably tells you whether the functions are available. You could write a simple helper function that returns true if LoadLibrary/GetProcAddress succeeds for a single function and then call the API directly via the windows crate and let delay loading take care of the rest.

**Comment by damyanp** [comment]
Often [IsApiSetImplemented](https://docs.microsoft.com/en-us/windows/win32/apiindex/detect-api-set-availability) can be used for this as well.
