### ISSUE TITLE
Feature request: validate README.md samples

### ISSUE THREAD

**Issue by yoshuawuyts** [microsoft/windows-rs#1429]
### Motivation

Right now we're not testing these, but they show up as the readme on crates.io

**Comment by kennykerr** [comment]
You can add this to the `windows` crate's `lib.rs` file to enable testing:

```rust
#[cfg(doctest)]
#[doc = include_str!("../../../../.github/readme.md")]
pub struct TestReadme;
```

The trouble is that `rustdoc` doesn't know to enable the necessary crate features to allow the code to build successfully so it fails, and I haven't found a way to tell `rustdoc` which features to enable.

**Comment by kennykerr** [comment]
Hey @jyn514 do you happen to know if there's a simple way to do this? Here's the readme:

https://github.com/microsoft/windows-rs/blob/master/.github/readme.md

As you can see, for each example there are various features that need to be enabled.

**Comment by jyn514** [comment]
I am no longer on the rustdoc team. You can ask on Zulip if you like.

**Comment by jyn514** [comment]
but in this case you probably want `cfg_attr(feature = "xxx", include_str!("..."))`

**Comment by kennykerr** [comment]
Thanks @jyn514 I'll give that a try - sorry to bother you. 😊

**Comment by kennykerr** [comment]
Haven't found a way to automate this testing. Will continue to test manually for the time being.
