### ISSUE TITLE
Feature request: add a WinMain option?

### ISSUE THREAD

**Issue by LollipopFt** [microsoft/windows-rs#1433]
### Motivation

i noticed that there is no WinMain function, but there is in C++.

### Additional context

Don't you need a WinMain function to draw a basic window?

**Comment by kennykerr** [comment]
`WinMain` is merely the conventional name of an application's entry point function and is not strictly required even in C++. Here's a window example:

https://github.com/microsoft/windows-samples-rs/tree/master/direct2d

**Comment by LollipopFt** [comment]
oh i see, thank you!

**Comment by LollipopFt** [comment]
@kennykerr sorry, but i can't find where winmain struct is used in the example...

**Comment by riverar** [comment]
@LollipopFt The entrypoint in that sample is `main()`. He was showing you that a WinMain is not strictly required.

**Comment by LollipopFt** [comment]
oh ok, so i don't need the winmain struct.

**Comment by tim-weis** [comment]
A bit of technical background:

Win32 applications can target the CONSOLE or WINDOWS subsystem. This is controlled through the [/SUBSYSTEM](https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem) linker option. The only noteworthy difference here is that the system automatically allocates a console when targeting the CONSOLE subsystem. Other than that there is no difference with respect to capabilities or system services available to either one. In particular, a CONSOLE application can create a GUI.

By default, Rust targets the CONSOLE subsystem on Windows. This can be changed using the [`windows_subsystem`](https://doc.rust-lang.org/reference/runtime.html#the-windows_subsystem-attribute) attribute. Irrespective of the subsystem targeted the user-provided entry point of a Rust program is always called `main`, and doesn't take any arguments (see [reference](https://doc.rust-lang.org/stable/reference/crates-and-source-files.html#main-functions)).

Compared to a C program targeting the WINDOWS subsystem with a standard [`WinMain`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-winmain) entry point there is loss of information. This information, however, can always be recovered from within a Rust program:

* `hInstance`:  
  The base address of the executing module. `GetModuleHandleW( std::ptr::null_mut() )` returns this value.
* `hPrevInstance`:  
  Always zero (a left-over from 16-bit Windows).
* `lpCmdLine`:  
  The command line for the application, excluding the program name. The full command line can be queried using `GetCommandLineA` or `GetCommandLineW`. It can then be parsed by calling [`CommandLineToArgvW`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw). Although it's easier to just use Rust's [`env::args_os`](https://doc.rust-lang.org/stable/std/env/fn.args_os.html).
* `nShowCmd`:  
  Controls how the window is to be shown. This value and whether it should be used is available through the [`STARTUPINFOW`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow)'s `wShowWindow` and `dwFlags` fields. The structure is available through [`GetStartupInfoW`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getstartupinfow).
