### ISSUE TITLE
Feature request: Bluetooth classic API

### ISSUE THREAD

**Issue by vit1251** [microsoft/windows-rs#1434]
### Motivation

Using COM in classic application on Rust is so tiresome

### Drawbacks

Use socket API or similar reuse API

**Comment by kennykerr** [comment]
There are [Win32](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Devices/Bluetooth/index.html) and [WinRT](https://microsoft.github.io/windows-docs-rs/doc/windows/Devices/Bluetooth/index.html) APIs for Bluetooth. The latter should be a lot easier to use.

**Comment by vit1251** [comment]
It's not about the easies of use, but the about of small count work examples of BT (LE) with the subsystem. The collection of information takes place in small pieces, often in very bloated documentation discussing many details at once, possibly useless in the first steps. Which makes development in general very expensive and as a result very expensive for both the developers and the customer (except of course using C#). Thus, the initiative to port the inventions of COM, WinRT, etc. seems to be a great undertaking. I hope for continuation and integration into popular technologies Golang, Python and etc.
