### ISSUE TITLE
error[E0433]: failed to resolve: could not find 'build' in 'windows' 

### ISSUE THREAD

**Issue by ArtemZHR** [microsoft/windows-rs#1435]
Does not compile for Windows 7 Ultimate.
What is missing is a "clean" system for correct work.
I will be very grateful for your help.

![image](https://user-images.githubusercontent.com/60423272/149619922-1bb36383-0df0-497b-82e4-38ed423c3898.png)

**Comment by riverar** [comment]
Hi @ArtemZHR, not enough information here. Can you provide the contents of Cargo.toml and/or provide details on what you're trying to compile?

**Comment by kennykerr** [comment]
The `build` macro also moved into the `windows::core` module a while back.

**Comment by crisprss** [comment]
> 



> The `build` macro also moved into the `windows::core` module a while back.

Hi ,When I use this module(windows::core::build!) it still tells me this error:
![image](https://user-images.githubusercontent.com/55953931/149712188-065ea365-ecae-4dfb-b380-8c55354ac7fd.png)

**Comment by ArtemZHR** [comment]
> The `build` macro also moved into the `windows::core` module a while back.

Thanks for the reply, I found that I used the guide not to the current version. Perhaps you can also tell me where you can see more detailed work with Bitmap in Rust?

**Comment by ArtemZHR** [comment]
> The `build` macro also moved into the `windows::core` module a while back.


See the examples described in this repository, maybe this will help you.
https://github.com/microsoft/windows-samples-rs

**Comment by crisprss** [comment]
> > The `build` macro also moved into the `windows::core` module a while back.
> 
> See the examples described in this repository, maybe this will help you. https://github.com/microsoft/windows-samples-rs

Thks for that!

**Comment by varunkamra** [comment]
I am having same issue with windows::build, could you tell me how to fix it?

**Comment by ArtemZHR** [comment]
`window::build` 
This is for older versions use examples to properly configure in your application.
In my case, it helped.

https://github.com/microsoft/windows-samples-rs

**Comment by tim-weis** [comment]
Samples have gone full circle and are now published through this repository again: https://github.com/microsoft/windows-rs/tree/master/crates/samples (as noted in the [README](https://github.com/microsoft/windows-rs/blob/master/.github/readme.md)).
