### ISSUE TITLE
Feature request: Some types are still aliases when they were newtypes in 0.28

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#1436]
### Motivation

See #1393

### Additional context

I'm seeing 

- [`MESSAGEBOX_STYLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/type.MESSAGEBOX_STYLE.html)
- [`WIN32_ERROR`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/type.WIN32_ERROR.html)
- [`GET_FILE_VERSION_INFO_FLAGS`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/type.GET_FILE_VERSION_INFO_FLAGS.html)

There may be others.

**Comment by poliorcetics** [comment]
Also:

- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/NetworkManagement/NetManagement/type.USER_PRIV.html
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/NetworkManagement/NetManagement/type.USER_ACCOUNT_FLAGS.html
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/type.VS_FIXEDFILEINFO_FILE_FLAGS.html
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/type.VS_FIXEDFILEINFO_FILE_OS.html
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/type.VS_FIXEDFILEINFO_FILE_TYPE.html
- https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/type.VS_FIXEDFILEINFO_FILE_SUBTYPE.html

**Comment by kennykerr** [comment]
#1423 was concerned with handle types. These are all C-style enums. I'm less convinced these benefit greatly from being unique types at the expense of all the extra code gen required.

**Comment by poliorcetics** [comment]
- [`VS_FIXEDFILEINFO_FILE_TYPE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/type.VS_FIXEDFILEINFO_FILE_TYPE.html)
- [`VS_FIXEDFILEINFO_FILE_SUBTYPE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/type.VS_FIXEDFILEINFO_FILE_SUBTYPE.html)

These are both `i32`s behind the scene and *very* easy to get wrong because of autocompletion or just using the wrong type.

Since we have `windows-sys` for "very raw" bindings, I think `windows` should be much more type-heavy. It would become a choice of compilation speed vs type safety, and I'm ready to lose seconds for the safety when I choose to use `windows`.

Other people may not have this opinion, have there been opposite opinions to this elsewhere ?

**Comment by poliorcetics** [comment]
Thank you very much, both for working on this and for your swift responses !

**Comment by kennykerr** [comment]
`0.32.0` has now been published and includes this change.
