### ISSUE TITLE
README changelog link is broken?

### ISSUE THREAD

**Issue by cmyr** [microsoft/windows-rs#1440]
*this space left blank*

**Comment by yoshuawuyts** [comment]
Hi, thanks for raising this! We indeed deprecated the CHANGELOG.md file in the last release. We'll need to update the link in the README to point to the [releases](https://github.com/microsoft/windows-rs/releases) page instead.

**Comment by cmyr** [comment]
Okay, thanks!

**Comment by kennykerr** [comment]
Yep, thanks for catching that - I've updated the link.
