### ISSUE TITLE
Prefer `&T` to `*const T` for Win32 input parameters that aren't optional

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1441]
For example, the `CoCreateInstance` function's first parameter should be of type `&GUID` rather than `*const GUID`. Callers aren't much affected by this, but implementations are bit more tedious.

**Comment by GamePad64** [comment]
Also, prefer `Option<&T>` for optional params

**Comment by kennykerr** [comment]
@GamePad64 - as you wish! 😜 #1939
