### ISSUE TITLE
Feature request: add GET_X_LPARAM and GET_Y_LPARAM

### ISSUE THREAD

**Issue by jminer** [microsoft/windows-rs#1445]
### Motivation

These macros are available from C, and it would be convenient to have them available in Rust. `winapi` provides them:

https://github.com/retep998/winapi-rs/blob/0.3/src/shared/windowsx.rs

### Drawbacks

None

**Comment by kennykerr** [comment]
The windows-rs project is focused on producing Rust bindings based on Windows metadata. The metadata lacks definitions for such macros. You could bring this up on the https://github.com/microsoft/win32metadata repo but I doubt the metadata will include such definitions, so you may be better off using a library crate with hand-written alternatives for such macros.

**Comment by ryancerium** [comment]
Duplicate of my issue, 921.
