### ISSUE TITLE
Missing structure `MEM_ADDRESS_REQUIREMENTS`

### ISSUE THREAD

**Issue by Zymlex** [microsoft/windows-rs#1446]
Missing structure `MEM_ADDRESS_REQUIREMENTS` or `_MEM_ADDRESS_REQUIREMENTS`:
https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-mem_address_requirements

I think this is related to `win32metadata`, so I created a task:
https://github.com/microsoft/win32metadata/issues/776

**Comment by kennykerr** [comment]
It seems to be present here:

windows crate: https://microsoft.github.io/windows-docs-rs/doc/windows/?search=MEM_ADDRESS_REQUIREMENTS

windows-sys crate: https://docs.rs/windows-sys/latest/windows_sys/?search=MEM_ADDRESS_REQUIREMENTS

**Comment by mikebattista** [comment]
Yes it's there. I will move it to the System.Memory namespace though.

**Comment by mikebattista** [comment]
Fixed with https://github.com/microsoft/win32metadata/commit/c08265ec0c9e86d96f4fc4e129a4d6d234909932.

**Comment by Zymlex** [comment]
@kennykerr It's strange, I don't find it here:
https://github.com/microsoft/windows-rs/search?q=MEM_ADDRESS_REQUIREMENTS
