### ISSUE TITLE
Bug: Application is linked to winspool.dll instead of winspool.drv

### ISSUE THREAD

**Issue by ancwrd1** [microsoft/windows-rs#1447]
### Which crate is this about?

windows

### Crate version

master branch

### Summary

Attempt to use any winspool functions (e.g. `SetDefaultPrinterW`) results in application linking to `winspool.dll` instead of `winspool.drv` and it fails to start.

### Expected behavior

The `winspool.drv` DLL name must be used for imported functions.

### Actual behavior

The `winspool.dll` DLL name is used for imported functions which is missing.

**Comment by kennykerr** [comment]
@riverar I thought you already opened a bug for this on win32metadata but I can't find it.

**Comment by riverar** [comment]
Related to https://github.com/microsoft/win32metadata/issues/714
