### ISSUE TITLE
incompatible type `windows::Win32::Foundation::HANDLE` and `std::os::windows::io::RawHandle`

### ISSUE THREAD

**Issue by djdisodo** [microsoft/windows-rs#1448]
`windows::Win32::Foundation::HANDLE` and `std::os::windows::io::RawHandle`
are incompatible, how should i use RawHandle in windows-rs?

**Comment by kennykerr** [comment]
They have the same memory layout - the `std` handle types are generally `*mut c_void` whereas the `windows` crate uses a `struct` with a single field of whatever type is defined in metadata but the field is public so you can easily assign/extract/cast it as needed.

**Comment by djdisodo** [comment]
so can i just simply transmute it? @kennykerr

**Comment by kennykerr** [comment]
> so can i just simply transmute it?

Yes.
