### ISSUE TITLE
Creating an archive

### ISSUE THREAD

**Issue by ArtemZHR** [microsoft/windows-rs#1451]
Tell me if this module `windows::Win32::Storage::Compression` allows you to create an archive, or does it act like a `compact` command for `cmd`? If possible, maybe you have the opportunity to share an example.

**Comment by tim-weis** [comment]
The members of the `windows::Win32::Storage::Compression` module represent the [Compression API](https://docs.microsoft.com/en-us/windows/win32/cmpapi/-compression-portal). It exposes compression algorithms only. There is no support for packaging compressed data into archives.
