### ISSUE TITLE
Feature request: Handle UTF-8 mode

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#1454]
### Motivation

Rust works with strings in UTF-8, so supporting it would make &str work natively(?) as long as a null terminator is added.
https://docs.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

### Drawbacks

It's only supported on Windows 10, and as far as i understand it requires extra steps in order to activate it,
so it can't just be a "feature" i believe, at least not in how it all works atm.

### Rationale and alternatives

It would go hand in hand with string in Rust,
the alternatives are either &[u8] which is somewhat easy to work with, but limited to ANSI,
the other is &[u16] which is not that easy to work with and requires helper methods etc to be friendly.

**Comment by riverar** [comment]
Note: Unfortunately this requires **both** the app and the OS to opt-in, making this effectively unreliable and unavailable (from a targeting user machines standpoint).

**Comment by kennykerr** [comment]
Note that if you specify the `alloc` feature, you can pass `&str` (UTF-8) values to Windows APIs with `PWSTR` parameters and it will perform the conversion for you.

**Comment by Zerowalker** [comment]
Yeah really unfortunate that it's opt in, but thought i might as well bring it up to see what the great minds had to say haha:P
And true, it will behave mostly "rust"ly with alloc, thanks.
