### ISSUE TITLE
Bug: Interface cast crashes on Windows 10 Builds < 20H2

### ISSUE THREAD

**Issue by qdot** [microsoft/windows-rs#1464]
### Which crate is this about?

windows

### Crate version

0.28

### Summary

First off: This is in 0.28, because I'm still waiting for some fixes in 0.31. If this is invalid for the new library, feel free to close and yell at me to upgrade. :)

We've been getting reports of .unwrap()'s panicking on Windows 10 builds older than 20H2 (which I realize are past lifetime, though we've got someone on an LTS complaining now too).

Specifically, this line in the generated code.

```rust
            let this =
              &::windows::Interface::cast::<IBluetoothLEAdvertisementReceivedEventArgs2>(self)
                .unwrap();
```

### Expected behavior

Either no crashes for users on Windows 10 < 20H2, or else some sort of warning/error versus a full panic.

### Actual behavior

Crashes on 20H2

**Comment by kennykerr** [comment]
Whether the cast succeeds depends on whether the object implements the requested interface. The `windows` crate has nothing to do with that. That's up to the particular OS you're running on. 

Whether it crashes is also up to you - you can handle it more gracefully by avoiding the `unwrap`, which is [designed to panic](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap), and instead query the `Result`, perhaps with something like `if let Ok(value) = object.cast::<IBlaBla>() { ... }`.

**Comment by qdot** [comment]
The code block above isn't our code. That's from the out/windows.rs file created by the windows-rs crate, hence the inability to avoid the .unwrap(). That's why I was saying this might also be invalid, because I know the code gen stuff changed in v0.29.

**Comment by qdot** [comment]
Here's the full context, from the generated windows.rs file: 

```rust
          pub fn BluetoothAddressType(&self) -> ::windows::Result<super::BluetoothAddressType> {
            let this =
              &::windows::Interface::cast::<IBluetoothLEAdvertisementReceivedEventArgs2>(self)
                .unwrap();
            unsafe {
              let mut result__: <super::BluetoothAddressType as ::windows::Abi>::Abi =
                ::std::mem::zeroed();
              (::windows::Interface::vtable(this).6)(::windows::Abi::abi(this), &mut result__)
                .from_abi::<super::BluetoothAddressType>(result__)
            }
          }
```

**Comment by kennykerr** [comment]
Ah! 😄 

Yes, that has been fixed. You should already see the fix if you switch from the `build` macro to the pre-generated APIs using the `Devices_Bluetooth_Advertisement` crate feature in the current 0.30 version. 

Notably, the `build` macro will no longer be available in 0.31. 

Sorry for the confusion.

**Comment by kennykerr** [comment]
Here's what that looks like in the generated bindings:

https://github.com/microsoft/windows-rs/blob/f06b0bb3e88bffc1ce18cd1ea65f1bcbe587afa7/crates/libs/windows/src/Windows/Devices/Bluetooth/Advertisement/mod.rs#L1110-L1117

**Comment by qdot** [comment]
Awesome, thanks! I'll go ahead and close this out then, and will get to testing against master while waiting for 0.31 ('cause I need #1438).

Thanks for answering questions this late. :)

**Comment by 107295472** [comment]
> windows::core::Interface::cast

windows::core::Interface::cast  Cast can't be found

**Comment by robmikh** [comment]
You can find it in the [ComInterface](https://microsoft.github.io/windows-docs-rs/doc/windows/core/trait.ComInterface.html) trait now.
