### ISSUE TITLE
Make it easier to capture non-static non-Send variables in a delegate

### ISSUE THREAD

**Issue by ghost** [microsoft/windows-rs#1465]
See the answer at the end of
https://stackoverflow.com/questions/70786125/should-i-try-to-access-self-in-a-pointerpressed-event-handler-for-a-coreapp-in-t

**Comment by kennykerr** [comment]
It's a fair question. WinRT delegates are challenging to model in Rust due to the lifetime and concurrency constraints that Rust formalizes. It's something I'm still working on improving.

**Comment by MRahilly** [comment]
In the meantime, if time allowed, a pointerpressed event handler on core_app would be great.

**Comment by kennykerr** [comment]
Related to https://github.com/microsoft/windows-rs/issues/313

**Comment by MRahilly** [comment]
Apologies for the ghost.

**Comment by kennykerr** [comment]
Just closing out some old issues I'm unlikely to get to. I think that in general this is not something we can guarantee is correct. Feel to chime in if you disagree.
