### ISSUE TITLE
Bug: Cannot find WNDCLASSW and friends even though Win32_UI_WindowsAndMessaging is enabled

### ISSUE THREAD

**Issue by rick-de-water** [microsoft/windows-rs#1472]
### Which crate is this about?

windows-sys

### Crate version

0.30.0

### Summary

With `windows-sys` referenced like this:
```toml
[dependencies.windows-sys]
version = "0.30.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging"
]
```

The following will fail:
```rust
use windows_sys::{
    Win32::UI::WindowsAndMessaging::{WNDCLASSW}
};
```

```
error[E0432]: unresolved import `windows_sys::Win32::UI::WindowsAndMessaging::WNDCLASSW`
 --> xxx.rs:2:38
  |
2 |     Win32::UI::WindowsAndMessaging::{WNDCLASSW}
  |                                      ^^^^^^^^^ no `WNDCLASSW` in `Windows::Win32::UI::WindowsAndMessaging`

```

Even though [this list](https://docs.rs/windows-sys/latest/windows_sys/all.html) defines them as:
```rust
Win32::UI::WindowsAndMessaging::WNDCLASSA
Win32::UI::WindowsAndMessaging::WNDCLASSEXA
Win32::UI::WindowsAndMessaging::WNDCLASSEXW
Win32::UI::WindowsAndMessaging::WNDCLASSW
```

It will however work when adding `Win32_Graphics_Gdi` as a feature to cargo.

### Expected behavior

Enabling the feature `Win32_UI_WindowsAndMessaging` should bring in all items from `Win32::UI::WindowsAndMessaging`.

### Actual behavior

It secretly also requires `Win32_Graphics_Gdi`.

**Comment by kennykerr** [comment]
> Enabling the feature Win32_UI_WindowsAndMessaging should bring in all items from Win32::UI::WindowsAndMessaging.

The problem with that approach is that it negatively impacts build time even if you never need to use the particular struct that has a dependency on other modules. To mitigate this, I added doc comments that tell you exactly which features you need to enable to use a particular type. For example, here is the documentation for `WNDCLASSW` in `windows-sys`:

https://docs.rs/windows-sys/latest/windows_sys/Win32/UI/WindowsAndMessaging/struct.WNDCLASSW.html

<img width="824" alt="image" src="https://user-images.githubusercontent.com/9845234/151617023-5ed8295f-795d-4381-9cc2-f8864ea14aa9.png">

**Comment by rick-de-water** [comment]
I did not notice that part of the documentation, that should avoid confusion in the future. Thanks!
