### ISSUE TITLE
Feature request: Add GetCurrentFiber and GetFiberData

### ISSUE THREAD

**Issue by rick-de-water** [microsoft/windows-rs#1481]
### Motivation

`GetCurrentFiber` and `GetFiberData` are header only functions, but are very important for fiber usage. In order to use them now I have to add a compilation step to my build that wraps the header only function into an exported function just so I can use them. It would be very useful if the package did this work for me.

It would probably be good to identify any other header only functions add those as well.

### Drawbacks

 - It is probably non trivial to find a solution that isn't a hack.
 - Fibers specifically are not used that often.

### Rationale and alternatives

The alternative is for everyone that requires a header only function to add a C build step to their build.

**Comment by kennykerr** [comment]
The windows crate generates bindings from metadata. You can find the metadata here: https://github.com/microsoft/win32metadata

These functions are not included in metadata because they are functions definitions instead of just function declarations. This is an intentional choice by the win32 metadata project. 

> In order to use them now I have to add a compilation step to my build that wraps the header only function into an exported function just so I can use them. 

I don't really understand why you need extra build steps when you could just define such functions yourself and call them directly.

**Comment by riverar** [comment]
I suspect the build script was used to access to intrinsics that tap into F and G segment registers (e.g. __readgsqword).

**Comment by kennykerr** [comment]
Sure. It sounds like fibers would require some special handling, but I don't think that's something the Windows crate should get involved in necessarily. Fibers are also not something we generally encourage.

**Comment by rick-de-water** [comment]
So should I take it up with the meta data project then?

**Comment by riverar** [comment]
> So should I take it up with the meta data project then?

No, the functions are just helpers that live solely in the C headers; It's not possible for metadata to describe these functions.

Fibers have been [deemed useless by the community](https://devblogs.microsoft.com/oldnewthing/20191011-00/?p=102989), so doubt you'll see much traction going forward.

I don't want to leave you empty handed though. Keep an eye on related thread-local stabilization work underway for Rust (https://github.com/rust-lang/rust/issues/29594). It might provide some reusable components for CPU register access that could replace any C interop you're currently using. 

Good luck! 🦀

**Comment by rick-de-water** [comment]
> Fibers have been deemed useless by the community, so doubt you'll see much traction going forward.
They're actually quite useful to get out of pesky windows message loops that never exit because the user is resizing the window.

But I guess I'll compile some C for now 🤷‍♂️

**Comment by riverar** [comment]
@rick-de-water Hah, fair enough and sorry we don't have anything better for you at the moment. I'll keep this in my head just in case I come across something relevant. (The [Rust Programming Language Discord](https://discord.gg/rust-lang-community) channel #windows-dev might have other ideas too.)
