### ISSUE TITLE
Feature request: Provide bitness-independent mappings where available

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#1493]
### Motivation

64-bit Windows introduced a number of new APIs to accommodate for increased pointer type widths. A prominent example being the [`[Get|Set]WindowLongPtr[A|W]`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlongptra) family of functions. They supersede the [`[Get|Set]WindowLong[A|W]`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlonga) functions, but aren't available on 32-bit Windows.

As a consequence, code that needs to be compatible with 32-bit Windows as well as 64-bit Windows must conditionally pull in the required dependencies. C and C++ developers using the Windows SDK have this solved: They can unanimously use the `*-Ptr`-variants and rely on the preprocessor to transform their code as needed.

Rust developers using the `windows` or `windows-sys` crates, on the other hand, will not find themselves in as comfortable a situation. Getting code to compile across architectures with differing pointer widths usually involves a fair amount of conditional code (see the [Direct2D sample](https://github.com/microsoft/windows-samples-rs/blob/2e6c5578a2d6199eeabd9d49389290c4ced68f3c/direct2d/src/main.rs#L638-L660) for an example).

Ideally, clients should be able to just call `GetWindowLongPtrA` and have their code compile across architectures.

### Drawbacks

I'm not aware of any adverse effects in providing this.

### Rationale

The developer experience for clients of `windows` and `windows-sys` should be on par with that of C and C++ developers using the Windows SDK. This feature request addresses an issue where this is not the case.

### Alternatives

The alternative is propagating the responsibility for writing bitness-adaptive code to clients or crate authors.

### Prior art

The [`winapi`](https://crates.io/crates/winapi) crate solves this by [re-exporting](https://github.com/retep998/winapi-rs/blob/5b1829956ef645f3c2f8236ba18bb198ca4c2468/src/um/winuser.rs#L5049-L5056) the `*-Ptr`-variants as aliases for 32-bit platforms, e.g.

```rust
#[cfg(target_pointer_width = "32")]
pub use self::GetWindowLongA as GetWindowLongPtrA;
```

### Unresolved questions

- Are there other API calls that fit this category?
- Should a solution be metadata-driven or would a hand-crafted implementation (akin to what `winapi` does) be manageable enough?

**Comment by kennykerr** [comment]
Thanks Tim. I don't think there will be any metadata to link them together, but I would like to simplify this if possible.

**Comment by kennykerr** [comment]
Sorry for the delay - let me know what you think of #1932.
