### ISSUE TITLE
GetClassNameW function argument mutability

### ISSUE THREAD

**Issue by CentricStorm** [microsoft/windows-rs#1496]
With version 0.32.0 the `GetClassNameW` function now accepts a `PWSTR` containing a `*const` to an immutable string buffer even though the string buffer could be written to.

There may need to be separate types `PCWSTR` (`*const`) and `PWSTR` (`*mut`) to address this.

**Comment by kennykerr** [comment]
This is related to #479 as the metadata includes the `[NativeArrayInfo(CountParamIndex = 2)]` attributes that isn't currently being handled by the `bindgen` crate.

**Comment by kennykerr** [comment]
I've been avoiding distinguishing between `PCWSTR` and `PWSTR`, because the win32 metadata doesn't make that distinction, but I'm starting to think that this is inevitable and that I need to introduce first class `const` versions of pointer typedefs like `PWSTR` and `PSTR`.
