### ISSUE TITLE
COM interface traits using `&mut self` may not be sound

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1497]
Without the `implement` macro (or supporting shims) providing additional protection, COM methods implemented with `&mut self` may not be sound due to aliasing rules and result in miscompilation. We have a few potential options:

* Use something like `this: *mut Self` to make it clear to the developer and the compiler that all bets are off. 
* Provide automatic locking of some kind behind the scenes.
* Use `&self` as the default, if that can be determined to be safe from miscompilation. 

(Based on some internal feedback from the compiler team)

**Comment by rylev** [comment]
We had a long debate about this for [com-rs](https://github.com/microsoft/com-rs), and it was determined that the use of `&self` was most likely correct though I think it would be worth talking through the details again. 

`&mut self` is definitely not correct and should be removed - it is very possible for com interfaces to not have exclusive access.
