### ISSUE TITLE
Possible API signature change

### ISSUE THREAD

**Issue by kmanc** [microsoft/windows-rs#1498]
### Which crate is this about?

windows

### Crate version

0.32.0

### Summary

processinformationclass no longer accepts an integer as an argument. The following worked in 0.30.0 but doesn't in 0.32.0

```rust
if let Err(error) = unsafe { NtQueryInformationProcess(processhandle, 0, processinformation, processinformationlength, returnlength) } {
        panic!("Could not get the entry point with ZwQueryInformationProcess: {error}");
}
```

### Expected behavior

I might have missed something in the changelog that explains why this is the case, but I would expect the above code to compile assuming all of the other arguments are correct

### Actual behavior

Compiler returns " ^ expected struct `PROCESSINFOCLASS`, found integer"

### Additional comments
EDIT - I said the wrong type
_No response_

**Comment by kennykerr** [comment]
It likely changed here: https://github.com/microsoft/windows-rs/pull/1482

Mentioned in the release notes here: https://github.com/microsoft/windows-rs/releases/tag/0.32.0

Here are the docs for the `NtQueryInformationProcess` function in the `windows` crate: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Threading/fn.NtQueryInformationProcess.html

**Comment by kennykerr** [comment]
Oh, I don't think the API signature has changed. `PROCESSINFOCLASS` was previously a type alias for the underlying type (`'i32`) but is now a new type. #1393 and #1436

**Comment by kmanc** [comment]
Ahh ok, yeah that would explain it! I just changed my code to actually use the struct but was a bit confused at first when suddenly code that hadn't been changed was throwing an error at compile time. Thank you :)

**Comment by kennykerr** [comment]
Great, sorry for any confusion. 😊
