### ISSUE TITLE
`IntoParam` is not documented leading to some confusion

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1499]
e.g. https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Threading/fn.CreateProcessA.html

It was suggested elsewhere that a `where` clause might make it a bit more readable (as well as documented `IntoParam`).

**Comment by kennykerr** [comment]
I'm planning to simplify the whole `Param` / `IntoParam` pattern and then document what remains, but it should be a lot more intuitive.

**Comment by ibigbug** [comment]
keen to see this - having issue w `lpcommandline` in `CreateProcessW` as passing in `&str` doesn't satisfy the type

**Comment by ibigbug** [comment]
looks like `impl<'a> ::windows::IntoParam<'a, PWSTR> for &str` [was implemented](https://github.com/microsoft/windows-rs/pull/1081/files#diff-b5def1e56ab703fd326a70bc9e9e43574cbf642364e807878e031d9e2b782deb) but go removed somehow? 

not what's the correct way to pass in `PWSTR` for functions like `CreateProcessW`

**Comment by kennykerr** [comment]
It's hiding behind the alloc feature.

**Comment by ibigbug** [comment]
ty @kennykerr - only saw it for `PWCSTR` https://github.com/microsoft/windows-rs/blob/0.37.0/crates/libs/windows/src/core/pwstr.rs

not for `PWSTR` though - is it missed ?

**Comment by topia** [comment]
I don't know why CreateProcessW wants PWSTR for lpcommandline, but PWSTR (mutable string) can't determine its buffer length automatically. so should be by design.

**Comment by ibigbug** [comment]
ty @topia - could you point me why it's an issue to do so if the size is undetermined ?

**Comment by topia** [comment]
Could you show me an example?

In my knowledge, we usually need to allocate some (sized) memory and pass it and its length to the Win32 API function.
windows-rs accepts `&mut [u16]` as that `PWSTR` case, such as [GetWindowTextW](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/fn.GetWindowTextW.html).

**Comment by ibigbug** [comment]
given the `&str` we should be able to get the size/length and supply to Win32 API.

for the `GetWindowText` which asks for a string pointer, without asking for the length, I'd assume inside the function it has some rules to detect the "end" of the string, i.e. the NULL terminator stuff, so it should still work right.

**Comment by topia** [comment]
In general, Win32 API uses PWSTR to return string from API.
For that case, we allocate some (not-zeroed or zeroed) memory and pass it and its length to the function.
[GetWindowTextW in rust](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/fn.GetWindowTextW.html) accepts `&mut [u16]`, then converts to pointer and length (rust `&[u16]` has length), pass them to [GetWindowTextW in Win32 API](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowtextw) as lpString and nMaxCount.

`lpCommandLine` of [CreateProcessW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) is defined as `[in, out, optional]`. For API parameters defined as in and out, generally, we need some fixed (defined by API) length buffer, copy some string to it, call the function, and read its result from the buffer.
If we implement `IntoParam` between `PWSTR` and `&str`, as described above, we should allocate a fixed-length buffer, but we can't do it without such metadata. We can allocate a string-sized buffer, but if Win32 API expects a larger buffer than we allocated, it may lead to a buffer overrun security vulnerability. In addition, we can't read the result.

I think we need another metadata or pseudo datatype for `CreateProcessW` case: "passes as mutable string, but will not get the result and accepts string-sized buffer."

**Comment by tim-weis** [comment]
[`CreateProcessW`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) is just an awkward API. Its `lpCommandLine` parameter is semantically an `in` parameter, and *should* be of type `PCWSTR`. In reality it is of type `PWSTR`, not because the primary purpose of this API is to produce a value that's useful to clients, but rather because someone in the 1980's made a poor decision (see [Why does the CreateProcess function modify its input command line?](https://devblogs.microsoft.com/oldnewthing/20090601-00/?p=18083)).

I'm not aware of any other API that has the same or similar semantics, and I doubt there's a lot of merit in having the `windows` crate (and the `Win32Metadata` project) take on the burden of providing data and custom implementations that are useful literally for a single API call.

**Comment by topia** [comment]
I completely agree that it's an awkward API. But for windows-rs, I think we should have any solution against current behavior (convert `&str` to `UTF-16 null-terminated string` and borrow as `PWSTR` by oneself) for the process creation in the future.

**Comment by kennykerr** [comment]
Closing in favor of #1811.

**Comment by passcod** [comment]
Seems that the "document IntoParam" part was lost in between all the issues? It's still the case that there's plenty of `IntoParam<T>` bounds and it's not documented, and indeed doesn't link or seem to exist in the rustdoc output.

**Comment by rustybrooks** [comment]
> Seems that the "document IntoParam" part was lost in between all the issues? It's still the case that there's plenty of `IntoParam<T>` bounds and it's not documented, and indeed doesn't link or seem to exist in the rustdoc output.

I'm sure feeling stuck on having to implement it for something (IntoParam<IWbemObjectSink>)

**Comment by kennykerr** [comment]
I'll reopen to make sure this gets some form of documentation. Keep in mind that you don't need to implement this. A blanket implementation is provided so that you can pass `None` or `&T` for such parameters. It also supports converting from derived types. 

There are also lots of tutorials and samples here:

* https://kennykerr.ca/rust-getting-started/
* https://github.com/microsoft/windows-rs/tree/master/crates/samples

**Comment by passcod** [comment]
```rust
#[doc(hidden)]
pub trait IntoParam<T: TypeKind, C = <T as TypeKind>::TypeKind>: Sized
where
    T: Type<T>
```

Is there a reason why you couldn't remove this `#[doc(hidden)]` so rustdoc at the very least generates (probably unfriendly, but better than nothing) docs for the type?

https://github.com/microsoft/windows-rs/blob/master/crates/libs/core/src/param.rs#L27

**Comment by riverar** [comment]
@passcod What's the motivation here? You shouldn't need to work with this directly, but maybe we're missing a scenario?

**Comment by passcod** [comment]
I want to know which exact types I can pass in to any arbitrary API I happen to wish to use at some time, without trying things at a guess and then getting frustrated when they don't work.

**Comment by passcod** [comment]
For better or worse your APIs are full of this IntoParam thing, the least you can do is not hide it from the docs, rendering it an opaque type from a user perspective. Put a "you shouldn't implement this" mention on it, whatever, I'm not looking to do that, I'm looking for your docs not to go "lol no you can't see what this api accepts for these arguments go away" for half your functions. That's all.

**Comment by riverar** [comment]
@passcod It's a bit awkward, agreed.

Just to make sure we're on the same page--when looking at the docs, you can essentially ignore IntoParam. So, using [CloseHandle](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/fn.CloseHandle.html) as an example:

```rust
pub unsafe fn CloseHandle<P0>(hobject: P0) -> Result<()>
where
    P0: IntoParam<HANDLE>,
```

You can pass in a `HANDLE` here.

**Comment by passcod** [comment]
Cool. For the next people or likely me in six months: take that sentence, write it as a doc comment on IntoParam, and remove doc(hidden).

Like what's the issue here? Genuinely. The git blame says the hiddens were added as a "minor polish to docs". That seems really weak justification for the tradeoff.

**Comment by rustybrooks** [comment]
> I'll reopen to make sure this gets some form of documentation. Keep in mind that you don't need to implement this. A blanket implementation is provided so that you can pass `None` or `&T` for such parameters. It also supports converting from derived types.
> 
> There are also lots of tutorials and samples here:
> 
> * https://kennykerr.ca/rust-getting-started/
> * https://github.com/microsoft/windows-rs/tree/master/crates/samples

The rust compiler is telling me I have to implement IntoParam.  I downloaded the repo and looked at the existing implementations and I think it's because my struct is missing some traits that `impl<T, U> IntoParam<T, ReferenceType> for &U` wants, notably I didn't have Clone (easy enough) but also I need CanInto<T> which I haven't really looked into.

The deal here is that I need to pass a "query sink" object into `ExecNotificationQueryAsync`.  I haven't really found good docs or examples for this, but I think I've puzzled out most of it.

I haven't checked out kennykerr.ca - I will do so now.  But I don't think the samples in this repo have anything like I'm trying to do.  if they do, let me know.

This is getting off track for this ticket - based on your comments I think I don't have a problem with the IntoParam docs so much as I do a problem (documentation or otherwise) with implementing this query sink thing.  What's an appropriate place to ask/post about that?  It's not a bug or issue so probably not here?

My goal with this little project was to convert this example to Rust using the windows crate
https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/WmiSdk/example--receiving-event-notifications-through-wmi-.md

I'd be happy to share the code I have wherever it's appropriate

**Comment by riverar** [comment]
@rustybrooks

So in that specific case, it looks like you're want an event sink. https://kennykerr.ca/rust-getting-started/how-to-implement-com-interface.html is relevant here.

Following that, you'd implement the interface on, say, a struct...

```rust
#[implement(IWbemObjectSink)]
struct Sink;

impl IWbemObjectSink_Impl for Sink {
    fn Indicate(
        &self,
        lobjectcount: i32,
        apobjarray: *const ::core::option::Option<IWbemClassObject>,
    ) -> ::windows_core::Result<()> {
        todo!()
    }

    fn SetStatus(
        &self,
        lflags: i32,
        hresult: ::windows_core::HRESULT,
        strparam: &::windows_core::BSTR,
        pobjparam: ::core::option::Option<&IWbemClassObject>,
    ) -> ::windows_core::Result<()> {
        todo!()
    }
}
```

Then box it up so it behaves like a COM object...

```rust
let sink: IWbemObjectSink = Sink.into();
```

And call your method...

```rust
some_object_that_impl_wbem_services::ExecNotificationQueryAsync(..., &sink);
```

**Comment by tim-weis** [comment]
I feel there are two issues here: A genuine lack of documentation and a compiler getting confused. @rustybrooks is in the latter camp, and the compiler's suggestion to implement `IntoParam` or `CanInto` isn't part of the solution.

The documentation, however, could be improved. A specific issue that keeps coming up is the set of transformations the `windows` crate applies (as opposed to the raw `windows-sys` bindings). Describing the full set of transformations in a prominent location would build the foundation to eventually explain what `IntoParam` is for (and why you should not need to implement it).

**Comment by rustybrooks** [comment]
> So in that specific case, it looks like you're want an event sink. https://kennykerr.ca/rust-getting-started/how-to-implement-com-interface.html is relevant here.
> 
> Following that, you'd implement the interface on, say, a struct...

OK so that's exactly what I did, but missing the boxing part.  I was trying to pass my `Sink` object directly and it was, fairly enough, wanting me to give it a method to turn it into a param.  I'll try your suggestion and see how that goes

**Comment by rustybrooks** [comment]
Hm I just end up here now
```
119 |         let sink: IWbemObjectSink = EventSink.into();
    |                                               ^^^^ the trait `From<EventSink>` is not implemented for `Wmi::IWbemObjectSink`
```

my EventSink is more or less like what you have above, i.e. 

```
#[implement(IWbemEventSink)]
pub struct EventSink;

impl EventSink {
    fn new() -> EventSink {
        EventSink
    }
}

#[allow(unused_variables)]
impl IWbemObjectSink_Impl for EventSink {
    fn Indicate(&self, lobjectcount: i32, apobjarray: *const Option<IWbemClassObject>) -> Result<()> {
        println!("Indicate!");
        Ok(())
    }

    fn SetStatus(&self, lflags: i32, hresult: HRESULT, strparam: &BSTR, pobjparam: Option<&IWbemClassObject>) -> Result<()> {
        println!("todo - SetStatus");
        Ok(())
    }
}

#[allow(unused_variables)]
impl IWbemEventSink_Impl for EventSink {
    fn GetRestrictedSink(&self, lnumqueries: i32, awszqueries: *const PCWSTR, pcallback: Option<&IUnknown>) -> Result<IWbemEventSink> {
        todo!();
    }

    fn IsActive(&self) -> Result<()> {
        println!("todo - IsActive");
        Ok(())
    }

    fn SetBatchingParameters(&self, lflags: i32, dwmaxbuffersize: u32, dwmaxsendlatency: u32) -> Result<()> {
        println!("todo - SetBatchingParameters");
        Ok(())
    }

    fn SetSinkSecurity(&self, lsdlength: i32, psd: *const u8) -> Result<()> {
        println!("todo - SetSinkSecurity");
        Ok(())
    }
}
```

**Comment by rustybrooks** [comment]
Ignore me, I had a bit of a typo/brain fart, I have it compiling now.

**Comment by riverar** [comment]
Think you're missing IWbemObjectSink here:

```diff
-#[implement(IWbemEventSink)]
+#[implement(IWbemEventSink, IWbemObjectSink)]
pub struct EventSink;
```

Oh sounds like you discovered that, nice! Glad to see you're up and running now.
