### ISSUE TITLE
Expose cast method in docs and update documentation on Interface trait

### ISSUE THREAD

**Issue by vthib** [microsoft/windows-rs#1502]
I want to use QueryInterface in a safe way to get a derived interface from a base COM interface. From what i've seen, the cast method in the Interface trait is exactly that, and works perfectly. However:
- finding it is not easy as the interface module is hidden from the documentations (but the cast method itself is not doc(hidden), which seems to indicate it is intended to be exposed).
- The Interface trait is documented with this sentence:
```
/// This trait is automatically used by the generated bindings and should not used directly.
```
which seems to indicate that this method should not be used.

AFAICT this cast method is intended to be the documented, official way to use QueryInterface (and if it isn't, it should be :) ). So the doc should probably be updated:
- removing the doc hidden from the interface module in core
- removing this "should not be used directly" comment from the trait documentation, and moving it to all the doc(hidden) methods of the trait.

I can do a PR for this if you are OK with those changes.

**Comment by kennykerr** [comment]
Yep, this is just a doc issue left over from when the crate only supported WinRT types. `IID`, `cast`, and `downgrade` are all for public consumption. 

Feel free to send me a PR - thanks!
