### ISSUE TITLE
`windows-sys` doesn't distinguish between `LPCWSTR` and `LPWSTR`

### ISSUE THREAD

**Issue by maroider** [microsoft/windows-rs#1504]
Crate version: 0.32.0

This is similar to #1490, but perhaps a bit more specific.

`windows-sys` doesn't distinguish between mutable and immutable string pointers, so all functions get whatever `LPWSTR` is aliased to (used to be `*mut u16`, now it's `*const u16`). With `type LPWSTR = *const u16`, APIs like `GetWindowTextW` now take a `*const u16` where they should take a `*mut u16`, which is a problem.

There's a similar issue with `ImmSetCompositionWindow`, where the function is documented [on MSDN](https://docs.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immsetcompositionwindow) as taking an `LPCOMPOSITIONFORM` (`*mut COMPOSITIONFORM`), but `windows-sys` says it takes a `*const COMPOSITIONFORM`.

**Comment by kennykerr** [comment]
This is the same signature issue as #1496.

**Comment by kennykerr** [comment]
Note that this applies to `GetWindowTextW` (same as #1496). It's less clear to me that there's anything wrong with the way `ImmSetCompositionWindow` is defined. The docs and metadata say that it has input parameters and I don't see anything that could be used to infer that it needs to be mutable.

**Comment by kennykerr** [comment]
#1550 adds first-class types for `PCSTR` and `PCWSTR`.
