### ISSUE TITLE
docs.rs -> limit targets to windows-targets 

### ISSUE THREAD

**Issue by syphar** [microsoft/windows-rs#1507]
While @Nemo157 was tracking down a performance regression with the `windows-sys` crate we saw that the docs are built for every default target, including linux and mac targets. Does the crate officially support these? 

When not, setting the `targets` option in the [docs.rs metadata](https://docs.rs/about/metadata) could improve the build-time for the docs vastly. For example: the `windows-sys` crate docs contain around 2 million files over 5 targets. And when these are duplicates or for actually unsupported platforms we don't have to build these.

**Comment by kennykerr** [comment]
Something like this? https://github.com/microsoft/windows-rs/pull/1508

**Comment by syphar** [comment]
yep, that's it, thanks! 

Are other pure windows crates missing this too?

**Comment by kennykerr** [comment]
I've applied the same to the remaining lib crates: https://github.com/microsoft/windows-rs/pull/1508/commits/b1c134801c63c7f8e64699176d9a8a85bba6516a
