### ISSUE TITLE
`const_fn_fn_ptr_basics` and `const_fn_trait_bound` will soon be stable

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1523]
@eholk is pushing these features over the finish line to get them stabilized: https://github.com/rust-lang/rust/pull/93827

Once that's complete, we can remove the following:

https://github.com/microsoft/windows-rs/blob/440a66eaa22434a8110d3b3af9b11b8702646c46/crates/libs/windows/src/lib.rs#L5-L6

**Comment by mwcampbell** [comment]
Just to make sure I understand correctly, is it a known issue right now that the "implement" feature in the current version of windows-rs requires a nightly toolchain? If so, do you know what the timeframe for resolving this is? In the meantime, we can keep using a previous version of windows-rs.

**Comment by kennykerr** [comment]
That's right, [stabilization has now been approved](https://github.com/rust-lang/rust/pull/93827#issuecomment-1059422496). I think this means it should show up in the next stable release.

**Comment by eholk** [comment]
Once the [PR](https://github.com/rust-lang/rust/pull/93827) merges, which should be soon, the features will become stable in 1.61. It's technically two stable releases away since 1.60 is in beta right now.

**Comment by kennykerr** [comment]
#1591 removed these features. Now we just need 1.61 to be released, but there is no more work for the `windows` crate so I'm closing this issue.

**Comment by harry1453** [comment]
FAQ.md needs to be updated to reflect that nightly is no longer required.

**Comment by kennykerr** [comment]
Thanks for the reminder! #1929
