### ISSUE TITLE
Feature request: audio example for windows and windows-sys

### ISSUE THREAD

**Issue by LollipopFt** [microsoft/windows-rs#1525]
### Motivation

Looking at all the examples, there is no use of any audio libraries, such as `DirectSound` or `XAudio2`, or any sound at all. it would help me immensely to see an implementation of this.

### Drawbacks

Time consuming?

### Rationale and alternatives

Impact: Less knowledge on how to use the audio crates.

**Comment by tim-weis** [comment]
You can take a look at the [Direct2D sample](https://github.com/microsoft/windows-rs/tree/master/crates/samples/direct2d). It demonstrates how to use (nano) COM with the `windows` crate. DirectSound and XAudio2 are based on (nano) COM as well, and I wouldn't expect their API use to be substantially different. If this isn't the case that would make a good point for providing this sample.

Regarding `windows-sys`, as I understand it, there is virtually no practical COM support, and I'm not aware of any plans to bring this closer to `windows`. If you need a code sample that illustrates how you'd use COM with `windows-sys` you can inspect the generated code in the `windows` crate. That is essentially what you'd be writing.

**Comment by kennykerr** [comment]
Yep, sorry I'm not familiar with the audio APIs and thus am not in a position to write such a sample. Provided they're mostly COM-based APIs, Tim's suggestion is a good one. 😊
