### ISSUE TITLE
Way to cast to IUnknown from an `#[implement]`ed object without passing the ownership?

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#1528]
[ITFSource::AdviseSink](https://docs.microsoft.com/en-us/windows/win32/api/msctf/nf-msctf-itfsource-advisesink) receives an IUnknown:

```cpp
hr = pSource->AdviseSink(IID_ITfCompartmentEventSink, this, &_dwCookie);
```

In the above example, Windows will later call `ITfCompartmentEventSink::OnChange` of `this`, which means the ownership is now shared with the system.

Implementing this in Rust is not straightforward to me since the `From` implementation generated by `#[implement]` requires consuming ownership. I can't just do `.AdviseSink(&ITfCompartmentEventSink::IID, self.into())` because of that.

Is there a way to do that?

**Comment by kennykerr** [comment]
The consuming `From` traits are for boxing the implementation to begin with. You can use the `cast` method within a boxed implementation to query for any interface that you have implemented. I still need to make this less brittle (https://github.com/microsoft/windows-rs/issues/1183).

**Comment by saschanaz** [comment]
Boxing requires `.into()` per https://github.com/microsoft/windows-rs/issues/1183#issuecomment-927361310, but that consumes the ownership, right?

**Comment by kennykerr** [comment]
The boxing via `into` consumes ownership of the implementation object but that object is now owned by the COM implementation in which it lives. That COM implementation is reference-counted and references to the COM object may be freely shared. Each time you hand out a reference, typically via `QueryInterface`, that represents another COM interface pointer that keeps the implementation alive and may call into your implementation. The `cast` method just wraps `QueryInterface`, essentially producing another COM interface pointer to `self`.

**Comment by saschanaz** [comment]
Thanks! So that means I indeed can't just pass `self.into()`. I guess I can try refactoring that. 👍

**Comment by kennykerr** [comment]
Right, inside the implementation `self.into()` won't work. Instead you'll want to use something like this:

```rust
let unknown: IUnknown = self.cast()?;
```

Then you can pass that to whatever API is expecting an interface to `self`.

**Comment by saschanaz** [comment]
Hmm, so after boxing I only have the COM interface (in this case `ITfCompartmentEventSink`), how can I access the internal implementation after that? No way?
