### ISSUE TITLE
Feature request: WinPixEventRuntime

### ISSUE THREAD

**Issue by polymonster** [microsoft/windows-rs#1529]
### Motivation

I am having great fun using Direct3D12 with rust, everything has been working like a dream I  just ran into the issue that `ID3D12GraphicsCommandList::SetMarker` and friends are not supposed to be called directly and instead you need to use:
[WinPixEventRuntime](https://devblogs.microsoft.com/pix/winpixeventruntime/)

This is the same in the C++ API but it doesn't seem to have the extensions present in windows-rs. 

### Drawbacks

WinPixEventRuntime is an optional module with the C++ API as well so it could probably well be considered out of the scope of windows-rs as the API / ABI linked to PIX.

### Rationale and alternatives

This alternative rust Direct3D12 [wrapper](https://crates.io/crates/rusty-d3d12) provides optional feature to use WinPixEventRuntime... so I could try using just that just for `PIXSetMarker` but it also uses alternative dependencies for Win32 FFI bindings. I haven't tried it yet but just feels like it would be nicer to have this all in one place.

I also would prefer in general just to be able to use the `ID3D12GraphicsCommandList::SetMarker` calls without having to use an external dependency... I understand the need for supporting backward compatibility and to support extendability for PIX but would be nice if the format was a bit more open.

**Comment by kennykerr** [comment]
This package seems to contain a small C++ library and not just exports from a DLL. It seems like this would be better served as a dedicated library crate (e.g. winpix-rs) that complements and builds on the `windows` crate. Perhaps the Direct3D team (@damyanp) would like to offer something like that but it's probably out of scope for the `windows` crate itself.

**Comment by damyanp** [comment]
Yup, most of the WinPixEventRuntime implementation is in the header file, to allow the compiler to inline (or compile out) calls.  It is designed this way as it's expected to be used in performance sensitive code

The dll itself does export some functions that may meet your needs.  See the "ABI Usage" section on https://devblogs.microsoft.com/pix/winpixeventruntime/ for more information here.

Longer term it'd be great to have an optimized implementation for rust that supports the same functionality as you get in C++.  It'd be an interesting project!  If anyone wanted to tackle this before we get to it, I'd be happy to review and help come up with testing strategies.

**Comment by polymonster** [comment]
Thanks for the responses. I managed to get it working using the ABI, importing the Library and Procs with `LoadLibrary` and `GetProcAddress` 

I made a simple [gist](https://gist.github.com/polymonster/28896d761c3592bab48a94924c0d7406) with how to set it up, in case anyone else was interested.

Had a little trouble figuring out how to get a raw pointer from the `ID3D12CommandList` but it's all working now.

Cheers!

**Comment by Alovchin91** [comment]
Hi @polymonster,

FYI you can link C/C++ code directly into the Rust binary, see [sysinfo-rs project](https://github.com/FillZpp/sys-info-rs) project for an example. This way you can use the header-only library semi-directly.

Alternatively, instead of doing manual LoadLibrary / GetProcAddress, you can use the usual [Rust FFI](https://doc.rust-lang.org/nomicon/ffi.html) with a [linker /delayload flag](https://docs.microsoft.com/en-us/cpp/build/reference/delayload-delay-load-import?view=msvc-170) if you need.

**Comment by polymonster** [comment]
> Hi @polymonster,
> 
> FYI you can link C/C++ code directly into a Rust binary, see [sysinfo-rs project](https://github.com/FillZpp/sys-info-rs) for an example. This way you can use the header-only library somewhat directly.
> 
> Alternatively, instead of doing manual LoadLibrary / GetProcAddress, you can use the usual [Rust FFI](https://doc.rust-lang.org/nomicon/ffi.html) with a [linker /delayload flag](https://docs.microsoft.com/en-us/cpp/build/reference/delayload-delay-load-import?view=msvc-170) if you need.

Thanks for the info, I will take a look at these other options when I get a chance.
