### ISSUE TITLE
How do I create COM interface (for example to talk to PowerPoint)

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [microsoft/windows-rs#1539]
Is it possible, using windows-rs, to connect to Applications, like PowerPoint, using the MS COM Interface?

I see the example for IUIAutomation:

```
let automation: IUIAutomation = CoCreateInstance(&CUIAutomation, None, CLSCTX_ALL).unwrap();
```

But IUIAutomation is already defined in the windows-rs, and its a huge definition.
Can I do the same for PowerPoint (or other Interfaces) and which steps are nessary?

**Comment by kennykerr** [comment]
I don't know what APIs are available to talk to PowerPoint. You may want to search for documentation to that effect. This crate provides APIs for Windows.
