### ISSUE TITLE
pri file format

### ISSUE THREAD

**Issue by dvc94ch** [microsoft/windows-rs#1541]
I'm working on a crate to build msix packages for windows. I've got most of it done, including signing, but I'm still missing a parser/generator for pri files. There seems to be no documentation published online. I've been able to figure out the basic structure of the format but haven't been able to figure out the format for the `decn_info`, `pridescex`, `hschemaex` or the `resmap2` sections. Was wondering if you had some access to documentation you could share with me. That would save me a lot of time and work. Thanks.

**Comment by kennykerr** [comment]
Sorry, I don't know what the PRI format is. Perhaps these guys know where the PRI file format docs may be found. @jonwis @stevewhims @riverar @sotteson1

**Comment by riverar** [comment]
It's not an open specification; ideally you would just rely on makepri.exe as it gets serviced with the SDK. If you want to continue down the Hackerman™️ path, perhaps a peek at [PriTools](https://github.com/chausner/PriTools/blob/master/PriFormat/PriDescriptorSection.cs) is in order.

**Comment by dvc94ch** [comment]
Great pointer thanks. It's for a Linux cross compile toolchain, MakePri doesn't work in wine, but even then using wine isn't a very nice solution.

**Comment by jonwis** [comment]
Also @huichen123 and @axelandrejs

**Comment by axelandrejs** [comment]
The code to generate PRI files is not currently open source, but the code to read them is: https://github.com/microsoft/WindowsAppSDK/tree/main/dev/MRTCore/mrt/mrm

Alternatively, if makepri.exe doesn't work for you, there is a DLL-based version: https://docs.microsoft.com/en-us/windows/win32/menurc/pri-indexing-reference . Not sure if that works in WINE, but it does have fewer dependencies.
