### ISSUE TITLE
`SystemTimeToTzSpecificLocalTime` fails with `InvalidInput` for certain SYSTEMTIME

### ISSUE THREAD

**Issue by annmarie-switzer** [microsoft/windows-rs#1549]
The [`SystemTimeToTzSpecificLocalTime`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Time/fn.SystemTimeToTzSpecificLocalTime.html) function fails with `InvalidInput` for certain SYSTEMTIME structs.

The specific one that's failing appears to be a date of Jan. 1, 1601. [According to the documentation](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-systemtime), that's a valid date, and I would think the API should be able to successfully convert it.

Why would the function fail with the second value, but not the first? 

```rust
use std::{io, mem};
use windows::Win32::System::Time::*;
use windows::Win32::Foundation::FILETIME;

fn main() {
    // works - 132790361186042732
    // fails - 147221225472

    let t = 147221225472 as u64;

    let ft = FILETIME {
        dwLowDateTime: t as u32,
        dwHighDateTime: (t >> 32) as u32,
    };

    unsafe {
        let mut utc = mem::zeroed();
        let mut local = mem::zeroed();

        FileTimeToSystemTime(&ft, &mut utc);

        dbg!(&utc.wYear); // 1601
        dbg!(&utc.wMonth); // 1
        dbg!(&utc.wDayOfWeek); // 1 (Monday)
        dbg!(&utc.wDay); // 1
        dbg!(&utc.wHour);
        dbg!(&utc.wMinute);
        dbg!(&utc.wSecond);
        dbg!(&utc.wMilliseconds);

        SystemTimeToTzSpecificLocalTime(0 as *const _, &mut utc, &mut local);
        dbg!(io::Error::last_os_error());
    }
}
```
Error:
```bash
[src\main.rs:33] io::Error::last_os_error() = Os {
    code: 87,
    kind: InvalidInput,
    message: "The parameter is incorrect.",       
}
```

**Comment by kennykerr** [comment]
Sorry, I'm not that familiar with this particular API function. Please ask questions about the Windows API on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-api.html) or [stackoverflow](https://stackoverflow.com/).

**Comment by riverar** [comment]
Depending on where you are in the world, the specified date/time value **after correcting for your local time zone** may fall behind the supported begin date of January 1, 1601. Try adding a few hours to verify. (A null TIME_ZONE_INFORMATION means use local time, not UTC.)

I'll submit a revised snippet in a moment.

**Comment by riverar** [comment]
```diff
use std::{io, mem};
use windows::Win32::System::Time::*;
use windows::Win32::Foundation::FILETIME;

fn main() {
    // works - 132790361186042732
    // fails - 147221225472

    let t = 147221225472 as u64;

    let ft = FILETIME {
        dwLowDateTime: t as u32,
        dwHighDateTime: (t >> 32) as u32,
    };

    unsafe {
+       // HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\UTC
+       // TZI (REG_BINARY) = [00 00 00 00 00 ..]
+       let tz = mem::zeroed();
        let mut utc = mem::zeroed();
        let mut local = mem::zeroed();

        FileTimeToSystemTime(&ft, &mut utc);

        dbg!(&utc.wYear); // 1601
        dbg!(&utc.wMonth); // 1
        dbg!(&utc.wDayOfWeek); // 1 (Monday)
        dbg!(&utc.wDay); // 1
        dbg!(&utc.wHour);
        dbg!(&utc.wMinute);
        dbg!(&utc.wSecond);
        dbg!(&utc.wMilliseconds);

-       SystemTimeToTzSpecificLocalTime(0 as *const _, &mut utc, &mut local);
+       SystemTimeToTzSpecificLocalTime(&tz, &mut utc, &mut local);
        dbg!(io::Error::last_os_error());
    }
}
```

**Comment by kennykerr** [comment]
😄 I got curious and did the same experiment, after poking at the OS code and noticing that the only reason this function will set the last error is if the time zone cutover information could not be calculated.

**Comment by annmarie-switzer** [comment]
Thanks! This solves it for us.
