### ISSUE TITLE
question on samples.

### ISSUE THREAD

**Issue by LollipopFt** [microsoft/windows-rs#1555]
hi, in your examples,
https://github.com/microsoft/windows-rs/blob/32c7eea14faabd083f5d3e6f0f03530a38ba2113/crates/samples/create_window_sys/src/main.rs#L10-L20
why is `lpszMenuName` a `null_mut()` in the docs? `PSTR` is a `*const u8`, so shouldn't it be a `null()` instead? is there a difference between these two `null`s?

note: i found the issue. in your repository, `PSTR` is
https://github.com/microsoft/windows-rs/blob/32c7eea14faabd083f5d3e6f0f03530a38ba2113/crates/libs/sys/src/core/mod.rs#L19
however, `lpszMenuName` in `WNDCLASSA` in [`docs.rs`](https://docs.rs/windows-sys/0.32.0/windows_sys/Win32/UI/WindowsAndMessaging/struct.WNDCLASSA.html) shows a `PSTR` which leads me to a [`*const u8`](https://docs.rs/windows-sys/0.32.0/windows_sys/Win32/Foundation/type.PSTR.html). which is correct?

**Comment by tim-weis** [comment]
`PSTR` used to be a type alias for `*mut u8`, that was subsequently changed to `*const u8` in an attempt to more closely reflect mutability. There has been a fair bit of change around mutability with the `PSTR`/`PWSTR` types, prior to #1555 adding first-class support to their const variants.

The sample in question used to be correct at the time it was published. If you want to be more strict you can pass `core::ptr::null()` or `std::ptr::null()` in place of `null_mut()`. I believe this will continue to be correct when #1555 is deployed.
