### ISSUE TITLE
Getting raw pointer out of a COM interface?

### ISSUE THREAD

**Issue by chyyran** [microsoft/windows-rs#1556]
I'm trying to convert an `ID3D11ShaderResourceView` struct into a `usize` handle for use with ImGui textures. The equivalent C++ code is 

```cpp
ID3D11ShaderResourceView* srv = ...;
...
ImGui::Image((void*)srv, ImVec2(width, height));
```

However, I can't cast the Rust projection of `ID3D11ShaderResourceView`  into `*const ()`. 

Are any of these approaches correct? None of them seem exactly right to me.

1. Coerce the reference of an `ID3D11ShaderResourceView` to a pointer then to usize

```rust
let tex_ptr = &srv as *const ID3D11ShaderResourceView as usize
imgui::Image::new(TextureId::new(tex_ptr), &[width, height]);
```

2. `transmute` the `ID3D11ShaderResourceView` to a pointer (??)

```rust
let tex_ptr : *const () = std::mem::transmute(srv);
imgui::Image::new(TextureId::new(tex_ptr as usize), &[width, height]);
```

What would be the correct approach to take here?

**Comment by kennykerr** [comment]
`transmute_copy` will give you the pointer value without stealing the ownership. 

```rust
let ptr: usize = std::mem::transmute_copy(&srv);
```

**Comment by rylev** [comment]
Just to push back a bit: `transmute` and `transmute_copy` are extremely unsafe and can at times be hard to use correctly. Your suggestion here is correct, but it does seem strange that the official way to get a raw pointer from what is essentially a new type around a raw pointer would be to use these highly unsafe functions when adding a method is pretty low cost. This is why com-rs provided `as_raw` methods which are safe to use and allow users to turn their COM pointers into raw pointers in a safe way.

**Comment by kennykerr** [comment]
Sure, I'm not opposed to adding a helper to the `Interface` trait for example. I'm just generally concerned about making this operation appear less dangerous than it is because while it is safe from Rust's perspective it's a pretty dangerous thing to do from COM's perspective.
