### ISSUE TITLE
Bug: List View notification messages are missing

### ISSUE THREAD

**Issue by gyk** [microsoft/windows-rs#1557]
### Which crate is this about?

windows

### Crate version

0.32

### Summary

The constants listed on [this page](https://docs.microsoft.com/en-us/windows/win32/controls/bumper-list-view-control-reference-notifications) have not been defined.

**Comment by tim-weis** [comment]
The constants are missing from the metadata. I filed an [issue](https://github.com/microsoft/win32metadata/issues/810#issue-1145743017) to get this resolved.

**Comment by kennykerr** [comment]
Thanks!
