### ISSUE TITLE
WMI (MI_xxx) functions - where are they?

### ISSUE THREAD

**Issue by vpopescu** [microsoft/windows-rs#1572]
It looks like the crate wraps the MI library for WMI, in namespace windows::Win32::System:Wmi. This is great, however I only see one function defined, [MI_Application_InitializeV1](https://docs.microsoft.com/en-us/windows/win32/api/mi/nf-mi-mi_application_initializev1).

At least from my exposure to this MI library via C, I would need additional functions, such as:

- [MI_Application_NewSession](https://docs.microsoft.com/en-us/windows/win32/api/mi/nf-mi-mi_application_newsession)
- [MI_Application_NewInstance](https://docs.microsoft.com/en-us/windows/win32/api/mi/nf-mi-mi_application_newinstance)
- and others

Is this an omission, or is the usage model different than C, and I'm missing something obvious? How would I create a [MI_Session](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Wmi/struct.MI_Session.html)?

Ref: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Wmi/index.html#functions

**Comment by riverar** [comment]
Hey @vpopescu. Those functions are unfortunately header-only functions, found in `mi.h`. You'll have to manually port the logic to use the `ft` member hanging off the `MI_Application` object that's returned after calling `MI_Application_InitializeV1`.

```cpp
MI_INLINE MI_Result MI_Application_NewSession(
    _In_     MI_Application *application,
    ...)
{
    if (application && application->ft)
    {
        return application->ft->NewSession(application, protocol, destination, options, callbacks, extendedError, session);
    }
    // ...
```

Going to close this for now as it's not a crate issue, but feel free to continue the discussion or re-open if needed.

**Comment by vpopescu** [comment]
Depends on what the goal of the crate is. If someone is doing Rust only and had no exposure to doing this in C, how are they supposed to create WMI applications?

**Comment by riverar** [comment]
One of the goals of the crate is to give you access to Windows APIs. MI_* APIs are not Windows APIs but rather belong to Windows Management Infrastructure (MI). Use of these APIs also requires the Windows Management Framework redistributable to be installed.

That said, I did try to write a quick sample for you but had to stop abruptly due to the unfortunate way the `MI_ApplicationFT` struct is represented (just a bunch of `isize`-d pointers). I'll file an issue on the Win32 metadata side of things to see if we can improve that so we can at least move forward.

**Comment by vpopescu** [comment]
Thanks for looking into it. I kinda got stuck around the same place you got stuck as well.   Yes, I think it needs a little TLC, it's either unusable, or beyond my Rust skills at the moment. 

I *think* MI has been included in the OS since Win8 (?) -- of course, with available downloadable updates. 

There is a third party WMI crate (https://crates.io/crates/wmi) but I don't think it supports executing methods. However it doesn't depend on MI. It's pretty good if all you need is to read WMI.

**Comment by vpopescu** [comment]
@riverar Could you link the WIn32 metadata issue here, so we can track an open issue?

**Comment by riverar** [comment]
@vpopescu Will do momentarily.

**Comment by CrendKing** [comment]
Hope you guys can add the functions to some crate, if not this one. Currently I have to handcraft my own function signature, then transmute the `isize` to function pointer.
```
pub type MI_Application_NewSession = extern "system" fn(
    application: *const MI_Application,
    protocol: *const u16,
    destination: *const u16,
    options: *const MI_DestinationOptions,
    callbacks: *const MI_SessionCallbacks,
    extendederror: *mut *mut MI_Instance,
    session: *mut MI_Session,
) -> MI_Result;

let mut application: MI_Application;
let mut session: MI_Session;

MI_Application_InitializeV1(0, null(), null_mut(), &mut application);
std::mem::transmute::<_, MI_Application_NewSession>((*application.ft).NewSession)(&application, null(), null(), null(), null(), null_mut(), &mut session);

```
