### ISSUE TITLE
Feature request: allow passing ptr::null() in place where PCSTR is required

### ISSUE THREAD

**Issue by ThreadedStream** [microsoft/windows-rs#1575]
### Motivation

Consider the following scenario:
```rust
static mut MUTEX: windows::Win32::Foundation::HANDLE = unsafe {
    windows::Win32::System::Threading::CreateMutexA(
        ptr::null_mut(),
        false,
        windows::core::PCSTR::default(),
    )
};
```

Here, I wish to initialize a static mutex object by calling CreateMutexA function. The last parameter expects the PCSTR type, and, as I don't really want to give it a name, the call to PCSTR::default() is initiated. The caveat is that compiler won't allow me to do this, justifying its objection by presenting the following message
```rust
error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
  --> src\windows.rs:40:9
   |
40 |         windows::core::PCSTR::default(),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Rationale and alternatives

In order to alleviate that, I've created the <a href="https://github.com/microsoft/windows-rs/pull/1574">following</a> pull request

**Comment by tim-weis** [comment]
Assuming this is about the `windows` crate (as opposed to the `windows-sys` crate), the final argument should really be `None` in this case, as `IntoParam` is implemented for `Option<T>`. Once that is changed, things still won't compile with the following diagnostic:

```rust
error[E0015]: calls in statics are limited to constant functions, tuple structs and tuple variants
 --> src\main.rs:4:14
  |
4 |     unsafe { CreateMutexA(std::ptr::null(), false, None) };
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`CreateMutexA` isn't (and cannot be) a constant function. Neither the existing implementation nor this PR can change that. Unless I'm missing something here, the proposed PR doesn't solve the immediate issue.

**Comment by ThreadedStream** [comment]
Thank you @tim-weis for clarification. What alternative would you suggest then? I need to initialize this mutex statically.

**Comment by tim-weis** [comment]
I believe [lazy_static](https://crates.io/crates/lazy_static) may be a viable option, or [once_cell](https://crates.io/crates/once_cell). The README of the latter lists a number of alternatives as well.

**Comment by ThreadedStream** [comment]
I'll definitely try it. Thanks for suggestion.
