### ISSUE TITLE
`AddPrintDeviceObject` takes 1 or 2 parameters

### ISSUE THREAD

**Issue by qarmin** [microsoft/windows-rs#1581]
### Which crate is this about?

Looks that both `windows-sys` and `windows``

### Crate version

0.33.0

### Summary

I'm not sure about this issue, but looks that 
https://github.com/microsoft/windows-rs/blob/32c7eea14faabd083f5d3e6f0f03530a38ba2113/crates/libs/sys/src/Windows/Win32/Graphics/Printing/mod.rs#L33-L35
takes 2 arguments but (search for `AddPrintDeviceObject`) 
https://raw.githubusercontent.com/microsoft/windows-rs/32c7eea14faabd083f5d3e6f0f03530a38ba2113/crates/libs/windows/src/Windows/Win32/Graphics/Printing/mod.rs 
takes 1 argument.

I'm not sure if  this is bug or not, but 2 functions with same name usually takes same set of arguments(if one function is internal, maybe it is better to rename one?)

I found this when creating fuzzer

**Comment by cherryleafroad** [comment]
If you take a look at the official winapi definition, it takes one input (hPrinter), and gives one output back (phDeviceObject).
```c
HRESULT AddPrintDeviceObject(
  [in]  HANDLE hPrinter,
  [out] HANDLE *phDeviceObject
);
```

Seeing by the definition of the function, it takes the hprinter input, creates the HANDLE to output the value in, then returns it in a result. So, if you just unwrap() it, you'll get the second output. It's just syntactic sugar.
```rust
fn AddPrintDeviceObject<...>(hprinter: Param0) -> ::windows::core::Result<super::super::Foundation::HANDLE> 

let mut result__: super::super::Foundation::HANDLE = ::core::mem::zeroed();
AddPrintDeviceObject(hprinter.into_param().abi(), ::core::mem::transmute(&mut result__)).from_abi::<super::super::Foundation::HANDLE>(result__)
```

**Comment by kennykerr** [comment]
Right, the `windows-sys` crate provides only the raw bindings, similar to `winapi`. The `windows` crate provides more idiomatic transformations for convenience. You can compare the docs for the `AddPrintDeviceObject` function [here](https://docs.rs/windows-sys/0.33.0/windows_sys/Win32/Graphics/Printing/fn.AddPrintDeviceObject.html) and [here](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Printing/fn.AddPrintDeviceObject.html).
