### ISSUE TITLE
Feature request: Async/await example (Future) for IAsyncOperation

### ISSUE THREAD

**Issue by aguynamedben** [microsoft/windows-rs#1586]
### Motivation

I wish there was an example that shows an IAsyncOperation being awaited using Rust's async/await feature.

I'm using windows-rs + Neon Bindings. I'd like to await the result of `Launcher::LaunchUriWithOptionsAsync`, which returns a Result that unwraps an instance of IAsyncOperation.

For now, I'm calling `op.get()`, which I believe blocks, but it'd be really cool to see an async/await example.

```rs
fn windows_launch_uri_async(mut cx: FunctionContext) -> JsResult<JsBoolean> {
    let in_uri = cx.argument::<JsString>(0)?;
    let in_uri_string = in_uri.value(&mut cx);
    let uri = Uri::CreateUri(in_uri_string).expect("Failed to create URI");

    let options = LauncherOptions::new().expect("Failed to create LauncherOptions");
    options.SetDisplayApplicationPicker(false).expect("Failed to disable application picker");

    let op = Launcher::LaunchUriWithOptionsAsync(uri, options).expect("Failed to start launching URI");
    // TODO: Use async/await syntax for IAsyncOperation? https://github.com/microsoft/windows-rs/pull/251
    // WARN: The line below blocks for a short moment... I think?
    let result = op.get().expect("Failed to get result");
    Ok(cx.boolean(result))
}
```

Sorry if this is a dumb question, I'm a Rust noob.

**Comment by aguynamedben** [comment]
Hmm it looks like maybe there are some examples in this PR: https://github.com/microsoft/windows-rs/pull/251

If anybody has any experience doing fancy async stuff with Rust, windows-rs, and Neon Bindings, let me know!

I'll close this if I get those examples in the PR working... otherwise feel free to close if this isn't appropriate. Thank you for making windows-rs, it's making me love Windows again along with a Dell XPS 13 😍

**Comment by kennykerr** [comment]
Hi Ben, check out the [samples](https://github.com/microsoft/windows-rs/tree/master/crates/samples) folder.

In particular, [the OCR sample](https://github.com/microsoft/windows-rs/blob/master/crates/samples/ocr/src/main.rs) might be a good starting point.

**Comment by kennykerr** [comment]
@aguynamedben and glad to hear you like it! 😉
