### ISSUE TITLE
Feature request: show hex code for NTSTATUS

### ISSUE THREAD

**Issue by daladim** [microsoft/windows-rs#1588]
### Motivation

Printing an `NTSTATUS` with `{:?}` shows `NTSTATUS(-1073741772)`.

The [official doc](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55) for NTSTATUS lists these codes as hex, this would save me a conversion. This would be good that NTSTATUS would implement Debug, and that would show them as hex (and possibly also as decimal, since googling them is also useful sometimes?)

I haven't checked, but maybe the same could be done for HRESULT and win32 error codes.

I'm relatively new to the windows-rs crate, I hope these suggestions make sense.
Thanks

**Comment by daladim** [comment]
Thanks :)

**Comment by kennykerr** [comment]
This is now published as part of [0.34.0](https://github.com/microsoft/windows-rs/releases/tag/0.34.0).
