### ISSUE TITLE
Get Handle of Window

### ISSUE THREAD

**Issue by aWeinzierl** [microsoft/windows-rs#1596]
Hi,

I need to access the [HWND](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HWND.html) of a [Window](https://microsoft.github.io/windows-docs-rs/doc/windows/UI/Xaml/struct.Window.html).

For C++ I found the following solution: https://github.com/microsoft/microsoft-ui-xaml/issues/5230#issuecomment-865486003
I would have tried to cast the window to a INativeWindow, however I couldn't find it in the docs, so I assume its solved differently in Rust.
How?

Background: I ran into [this issue](https://stackoverflow.com/questions/57161258/invalid-window-handle-error-when-using-fileopenpicker-from-c-sharp-net-framwo). Likely, because Tokio threw me onto a different thread. It seems like I can't use async directly in callbacks (yet?), so I need to call it from somewhere else.

**Comment by riverar** [comment]
`Windows.UI.Xaml.Window` type windows don't follow the traditional Win32 HWND model; these windows may or may not have HWNDs associated with them, hence why it's very difficult to get one. That said, Microsoft does provide interop functionality here by way of [ICoreWindowInterop](https://docs.microsoft.com/en-us/windows/win32/api/corewindow/nn-corewindow-icorewindowinterop?WT.mc_id=WD-MVP-5002756). Unfortunately, for whatever reason, interop functions are not emitted in the standard Windows metadata.

I filed an issue in the upstream Windows metadata repo to see what others think about including interop metadata https://github.com/microsoft/win32metadata/issues/830

If you want to continue down this road, your work is certainly cut out for you!

You'll need to:
1. Get [`ICoreWindowInterop`](https://docs.microsoft.com/en-us/windows/win32/api/corewindow/nn-corewindow-icorewindowinterop?WT.mc_id=WD-MVP-5002756) defined in Rust
2. Get the active `CoreWindow` for the current thread (i.e. `let core_window = CoreWindow::GetForCurrentThread()?;`)
3. Query the core window for a peek at its native interface (ICoreWindowInterop) side (i.e. `let interop:ICoreWindowInterop = core_window.cast();`)
4. Use the window handle property/method provided by the interface

For future usage questions, please try https://stackoverflow.com/ or the [Rust Programming Language Community Server](https://discord.com/invite/rust-lang-community). We use GitHub issues to track problems that directly impact the crate. I'll close this issue now but feel free to continue the discussion. Thanks!

**Comment by kennykerr** [comment]
Reminded me of this old piece I wrote some 10 years ago. 

https://kennykerr.ca/2012/11/09/windows-8-whered-you-put-my-hwnd/

**Comment by kennykerr** [comment]
Note that once #1594 completes, you should be able to use the `interface` macro to locally define such missing interfaces.

**Comment by kennykerr** [comment]
Note also that sadly, `IWindowNative` used by [WinUI](https://github.com/microsoft/microsoft-ui-xaml) is different to `ICoreWindowInterop` used by `CoreWindow` apps.

**Comment by riverar** [comment]
@aWeinzierl I sent in a PR to upstream metadata and that should be merged today. If all goes well, this might all become much easier in the next `windows` crate release. I'll keep you updated.

**Comment by riverar** [comment]
@aWeinzierl Thanks for your patience. The latest Win32 metadata has been merged into master. You can now super easily do what you want by adding the `Win32_System_WinRT` feature and writing a few lines of code:

```rust
let interop:ICoreWindowInterop = window.cast()?;
unsafe {
    let hwnd = interop.WindowHandle()?;
    // ...
}
```

**Comment by aWeinzierl** [comment]
Surprisingly in my case that fails already at step 1:
```
[src\main.rs:17] Window::Current()?.cast::<ICoreWindowInterop>() = Err(
    Error {
        code: 0x80004002,
        message: Interfaz no compatible
        ,
    },
)
```

Code:
```
#![allow(non_snake_case)]

use windows::core::*;
use windows::ApplicationModel::Activation::LaunchActivatedEventArgs;
use windows::ApplicationModel::Package;
use windows::UI::Xaml::*;
use windows::Win32::Foundation::HWND;
use windows::Win32::System::Com::{COINIT_MULTITHREADED, CoInitializeEx};
use windows::Win32::System::WinRT::ICoreWindowInterop;
use windows::Win32::UI::WindowsAndMessaging::{MB_ICONSTOP, MB_OK, MessageBoxW};

#[implement(IApplicationOverrides)]
struct App ();
impl IApplicationOverrides_Impl for App {
    fn OnLaunched(&self, _: &Option<LaunchActivatedEventArgs>) -> Result<()> {
        dbg!(Window::Current()?.cast::<ICoreWindowInterop>()); Ok(())
    }
}
fn main() -> Result<()> {
    unsafe {
        CoInitializeEx(std::ptr::null(), COINIT_MULTITHREADED)?;
        if let Err(result) = Package::Current() {
            MessageBoxW(
                HWND::default(),
                "This sample must be registered (via register.cmd) and launched from Start.",
                "Error",
                MB_ICONSTOP | MB_OK,
            );
            return Err(result);
        }
    }
    Application::Start(ApplicationInitializationCallback::new(move |_| {
        Application::compose(App())?;
        Ok(())
    }))
}
```
🤔
(Thanks for all the info btw, very interesting!)

**Comment by riverar** [comment]
Hey @aWeinzierl,

`ICoreWindowInterop` hangs off `CoreWindow`. Here's a quick tweak to the sample you provided:

```diff
#[implement(IApplicationOverrides)]
struct App ();
impl IApplicationOverrides_Impl for App {
    fn OnLaunched(&self, _: &Option<LaunchActivatedEventArgs>) -> Result<()> {
+       dbg!(Window::Current()?.CoreWindow()?.cast::<ICoreWindowInterop>()); Ok(())
-       dbg!(Window::Current()?.cast::<ICoreWindowInterop>()); Ok(())
    }
}

```

**Comment by aWeinzierl** [comment]
that worked, thank you very much!
