### ISSUE TITLE
Reduce usage of `unsafe` in `implement` and `interface` macros

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#1616]
*Note: This is an issue that touches basically the entirety of the windows-rs ecosystem, but I'd like to limit the discussion now just to the `implement` and `interface` macros for now.*

The usage of `unsafe` in these macros is unavoidable. After all, we're effectively just dealing with pointers to vtables. However, this is all the more reason to be very diligent about the usage of `unsafe`. By limiting it's usage we do the following (which is basically just a enumeration of the benefits of `unsafe` in Rust in general):
* Make auditing of the correct usage of `unsafe` easier (i.e., the less it's used the easier it is to verify those usages)
* Make changes easier (i.e., if almost everywhere uses unsafe instead of a few strategic locations, changing code *always* requires keeping the unsafe invariants in your head instead of a few strategic locations)
* Make reading easier (i.e., unsafe code is just harder to understand because it requires reasoning beyond the local scope. By reducing the amount of unsafe usage it becomes easier for users and maintainers to understand what's happening)

**Proposal**: I propose auditing the usage of `unsafe` in the above macros and using them as a means to try out strategies for reducing the number of lines inside of `unsafe` blocks.

### Example 

As an example, take the `From<$IMPL> for $INTERFACE` implementations produced by the `implement` macro;

```rust
impl <#constraints> ::core::convert::From<#original_ident::<#(#generics,)*>> for #interface_ident {
    fn from(this: #original_ident::<#(#generics,)*>) -> Self {
        unsafe {
            let this = #impl_ident::<#(#generics,)*>::new(this);
            let ptr = ::std::boxed::Box::into_raw(::std::boxed::Box::new(this));
            ::core::mem::transmute_copy(&::core::ptr::NonNull::new_unchecked(
                &mut (*ptr).vtables.#offset as *mut _ as _,
            ))
        }
    }
}
```

A few notes:
* The `unsafe` block contains code that is perfecting safe such as instantiating the implementation through its `new` associated function. We should try to limit the amount of completely safe code inside of safe blocks.
* We turn the boxed implementation into a raw pointer only to then dereference the raw pointer. Presumably, we are turning the box into a raw pointer so that we don't call its drop function at the end of the function. Instead we could use `Box::leak` (a safe function) to accomplish the same.
* We're casting to `*mut c_void` which means we lose any of the remaining type safety we had
* We use `transmute_copy` which is a very sharp knife and can easily be used wrong. We should prefer more direct conversions that allow the compiler to better understand our intent and give us an error if we do something wrong.
* We convert to `NonNull` for really no reason

With all of these in mind, I would propose something like the following:

```rust
impl <#constraints> ::core::convert::From<#original_ident::<#(#generics,)*>> for #interface_ident {
    fn from(this: #original_ident::<#(#generics,)*>) -> Self {
        let this = #impl_ident::<#(#generics,)*>::new(this);
        let mut this = ::std::boxed::Box::new(this);
        let vtable_ptr = &mut this.vtables.#offset as *mut #interface_ident::VTbl;
        let _ = ::std::boxed::Box::leak(this);
        unsafe { #interface_ident::from_raw(vtable_ptr) }
    }
}
```

Note:
* `unsafe` is limited to one line. All we need to do to verify the safety of this function is understand this one line and whether the invariants document by `Interface::from_raw` are upheld. 
* Each line very clearly self describes what it's doing (e.g., use of `Box::leak` is much more self evident than the use of `Box::into_raw`
* It's less code 

### Next steps

So the next steps I propose are to open up some PRs that reduce the reliance on `unsafe` inside of the code generated by these macros.

**Comment by kennykerr** [comment]
Great feedback - I like the proposed change!

**Comment by kennykerr** [comment]
Related: #1183

**Comment by kennykerr** [comment]
Any more work to do here @rylev or can we close this?

**Comment by rylev** [comment]
While there's more work to do here, I think it would be more helpful to outline that work in individual issues rather than in a generic issue like this.
