### ISSUE TITLE
Interface macro not usable on stable

### ISSUE THREAD

**Issue by cherryleafroad** [microsoft/windows-rs#1617]
The new `interface` macro requires a user to use nightly, because errors about missing features are output. Originally required these features (below), although they were stabilized on 1.61.0. Still though however they will not work without a beta/nightly until 1.61.0 is officially released.

I'm unsure if this is worthy of a bug report, especially since these were stabilized (albeit in a future edition). <ins>**If this is a "won't-fix" kind of thing, then I suppose it would be nicer if it was documented perhaps. You can close this issue otherwise - I just wanted to make a note about this behavior in case it was undesirable**</ins>

Workaround: Install latest nightly
Features:
```rust
#![feature(const_fn_fn_ptr_basics)]
#![feature(const_fn_trait_bound)]
```

Errors:
```
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
    --> C:\Users\<user>\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.34.0\src\Windows\Win32\System\Wmi\impl.rs:3564:63
     |
3564 |     pub const fn new<Identity: ::windows::core::IUnknownImpl, Impl: IWbemEventSink_Impl, const OFFSET: isize>() -> IWbemEventSink_Vtbl {        
     |                                                               ^^^^
     |
     = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
error[E0658]: function pointer casts are not allowed in constant functions
    --> C:\Users\user>\.cargo\registry\src\github.com-1ecc6299db9ec823\windows-0.34.0\src\Windows\Win32\System\Wmi\impl.rs:3593:30
     |
3593 |             SetSinkSecurity: SetSinkSecurity::<Identity, Impl, OFFSET>,
     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
```

Reproduce: use this in cargo.toml with 1.59.0
```toml
[dependencies.windows]
version = "0.34.0"
features = [
    "interface",
    # workaround https://github.com/microsoft/windows-rs/pull/1612
    "implement"
]
```

**Comment by kennykerr** [comment]
Thanks for the feedback. I have clarified this further in #1523 and pinned that issue so that it is more easily discoverable.
