### ISSUE TITLE
Using LPARAM from a pointer

### ISSUE THREAD

**Issue by MTRNord** [microsoft/windows-rs#1621]
Hi, I am currently trying to convert a winapi-rs to windows-rs, and I am hitting uncountable issues with it :/

One I in particular struggling with is this:

`SendMessageTimeoutA` in winapi was able to take a pointer in the lparam field.
windows-rs wants the LPARAM struct.

So I am wondering how I would migrate this line https://github.com/apoloval/fsuipc-rs/blob/c750e306c95d0738f1e318b90cc284ddd1e4d6c8/src/local.rs#L93 over to windows-rs. 

As docs don't exist for this crate and it in general feels like nobody cares about usability, I thought I might as well ask before I just stick with winapi.

**Comment by MTRNord** [comment]
Figured it out

**Comment by kennykerr** [comment]
Hi Marcel, something like `LPARAM(buff as _)` should work.

We care deeply about usability, but this project is still in early development, so we have a long way to go. If you have any practical suggestions to improve usability, please do share them. 

Thank you for your patience. ❤️

**Comment by riverar** [comment]
> As docs don't exist for this crate [...] in general feels like nobody cares about usability

[API-level docs](https://microsoft.github.io/windows-docs-rs/doc/windows/) do exist (listed in the README). If you're looking for best practices and whatnot, yeah you're right. That's definitely on the TODO.

Creating a great developer experience (usability) is a top priority for the `windows` crate. If you run into any frustrating bits, please do open issues / share them here. Apologies for the frustration.

**Comment by kennykerr** [comment]
No worries, also keep in mind that we offer both the [windows](https://crates.io/crates/windows) crate and the [windows-sys](https://crates.io/crates/windows-sys) crate. There are pros and cons for sure and some confusion to boot. If you're coming from the `winapi` crate, you may find the `windows-sys` crate more natural. 

For example, the `windows-sys` crate defines [LPARAM as a type alias](https://docs.rs/windows-sys/latest/windows_sys/Win32/Foundation/type.LPARAM.html) and its definition of [SendMessageTimeoutA](https://docs.rs/windows-sys/latest/windows_sys/Win32/UI/WindowsAndMessaging/fn.SendMessageTimeoutA.html) is pretty straightforward to understand. 

By contrast, the `windows` crate defines [LPARAM as a struct](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.LPARAM.html) and its definition of [SendMessageTimeoutA provides polymorphism](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/fn.SendMessageTimeoutA.html) that can be useful for more advanced APIs.
