### ISSUE TITLE
I/O Safety

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1622]
Just a reminder to consider how we might integrate or leverage the concepts behind the I/O Safety RFC.

https://github.com/rust-lang/rust/issues/87074

**Comment by kennykerr** [comment]
I had a brief look, but I don't think there's any relevant work for the windows-rs project at this time.

**Comment by sunfishcode** [comment]
The I/O safety feature has features intended to be useful in this use case, so I'm curious about whether you're thinking this isn't relevant at this time, or whether you see a reason they won't be a good fit in the future either.

It is at least the case that the I/O safety APIs aren't stable yet. They are currently expected to be stable in Rust 1.63 which won't be released until next month. And of course, even when it's stable, there will be MSRV concerns. But other than those, I'm curious if there are other concerns here.

**Comment by kennykerr** [comment]
No concerns just don't really see an obvious application at this level, but time will tell. The `windows` and `windows-sys` crates also have pretty low-level abstractions for handles and a lot more handle types than what this RFC covered last I checked. Of course, I haven't looked too deeply so if you have suggestions, I'm happy to hear them.

**Comment by sunfishcode** [comment]
As a few examples, Rust's internal FFI bindings are using [`HandleOrInvalid`](https://doc.rust-lang.org/stable/std/os/windows/io/struct.HandleOrInvalid.html) to describe [the return value of `CreateFileW`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/c.rs#L1017), which is either a handle or `INVALID_HANDLE_VALUE`, and [`HandleOrNull`](https://doc.rust-lang.org/stable/std/os/windows/io/struct.HandleOrNull.html) to describe [the return value of `CreateThread`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/c.rs#L914), which is either a handle or `NULL`. Also it uses [`BorrowedHandle`](https://doc.rust-lang.org/stable/std/os/windows/io/struct.BorrowedHandle.html) to describe [`ReadFile`'s handle argument](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/c.rs#L979), as well as a few others.

**Comment by ChrisDenton** [comment]
windows-rs recently gained a generic `Borrowed<'a, T>` which I think aims to fulfill a similar role to `BorrowedHandle<'a>` but is intended to be more general.

You wouldn't normally want to return `HandleOrInvalid` in a public API (converting to a `Result` is better). Maybe in windows-sys? But that tends to use more primitive types and has to be `no_std` compatible. I'm also unsure if the metadata says precisely which value is documented invalid for each value.

**Comment by sunfishcode** [comment]
`ReadFile` in the windows crate doesn't use `Borrowed<'a, T>`; it currently looks [like this](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/fn.ReadFile.html):
```rust
pub unsafe fn ReadFile<'a, Param0: IntoParam<'a, HANDLE>>(
    hfile: Param0, 
    lpbuffer: *mut c_void, 
    nnumberofbytestoread: u32,
    lpnumberofbytesread: *mut u32, 
    lpoverlapped: *mut OVERLAPPED
) -> BOOL
```

It looks like functions like this could use `AsHandle` in place of `IntoParam`, which would have the advantage of being directly usable with `std::fs::File` and more as the ecosystem starts adopting `AsHandle`.

In window-sys, `ReadFile` looks [like this](https://docs.rs/windows-sys/latest/windows_sys/Win32/Storage/FileSystem/fn.ReadFile.html):
```rust
pub unsafe extern "system" fn ReadFile(
    hfile: HANDLE,
    lpbuffer: *mut c_void, 
    nnumberofbytestoread: u32,
    lpnumberofbytesread: *mut u32, 
    lpoverlapped: *mut OVERLAPPED
) -> BOOL
```
Except for the `no_std` requirement, it looks like functions like this could use `BorrowedHandle` in place of `HANDLE`.

One option would be to add a "std" feature where the std types are used, and then have windows-sys define its own version of the types in `no_std` mode. The [io-lifetimes](https://github.com/sunfishcode/io-lifetimes/) crate has implementations that would be pretty easy to copy, if there's interest. Granted, this has tradeoffs, but I'm interested in learning how the tradeoffs look here.

> I'm also unsure if the metadata says precisely which value is documented invalid for each value.

I [have this concern too](https://github.com/rust-lang/rust/issues/87074#issuecomment-1074131719). It may not have this information now, but this might be something worth thinking about. `INVALID_HANDLE_VALUE` vs. `NULL` is [notoriously error-prone](https://devblogs.microsoft.com/oldnewthing/20040302-00/?p=40443). It looks like most things in the windows crate that return a handle check for both `NULL` and `INVALID_HANDLE_VALUE`; that could be simplified if the metadata had this information.

**Comment by kennykerr** [comment]
The metadata does indeed include this information, which is where the windows crate gets it from.

**Comment by ChrisDenton** [comment]
I thought the generic `is_invalid` was used for functions like `CreateFileW` that return win32 handles? Which is likely fine because it tests for both -1 and 0.

**Comment by kennykerr** [comment]
There's no generic `is_invalid` method. They're all generated from metadata.

https://github.com/microsoft/windows-rs/blob/56f779976a2300e1a5895bbca19ee846e4443383/crates/libs/bindgen/src/handles.rs#L25-L56

For example, here's the metadata for `Windows.Win32.Foundation.HANDLE`:

```C#
[RAIIFree("CloseHandle")]
[InvalidHandleValue(-1L)]
[InvalidHandleValue(0L)]
[NativeTypedef]
public struct HANDLE
{
	public IntPtr Value;
}
```

**Comment by ChrisDenton** [comment]
Sorry, I worded that badly. The `Handle::is_invalid` method is used rather than anything specific to `CreateFileW`, which only documents -1 as being the error condition.

 `HandleOrInvalid` could not possibly be used in this situation even if it was wanted because the metadata doesn't say that.

**Comment by ChrisDenton** [comment]
To put it another way, for `CreateFileW` the return type is documented as:

> If the function succeeds, the return value is an open handle to the specified file, device, named pipe, or mail slot.
> 
> If the function fails, the return value is `INVALID_HANDLE_VALUE`. To get extended error information, call `GetLastError`.

But this information is not in the metadata:

```csharp
[DllImport("KERNEL32", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows5.1.2600")]
public unsafe static extern HANDLE CreateFileW([In][Const] PWSTR lpFileName, [In] FILE_ACCESS_FLAGS dwDesiredAccess, [In] FILE_SHARE_MODE dwShareMode, [Optional][In] SECURITY_ATTRIBUTES* lpSecurityAttributes, [In] FILE_CREATION_DISPOSITION dwCreationDisposition, [In] FILE_FLAGS_AND_ATTRIBUTES dwFlagsAndAttributes, [Optional][In] HANDLE hTemplateFile);
```

So windows-rs essentially tests both `0` and `-1` (via `is_invalid`) as this will work for all fallible functions that return a `HANDLE`.

The [`HandleOrInvalid`](https://doc.rust-lang.org/std/os/windows/io/struct.HandleOrInvalid.html) type is intended for cases where you know the function uses `-1` to indicate an error. But the metadata does not tell you which functions those are.

**Comment by riverar** [comment]
> But this information is not in the metadata

That function returns a HANDLE, which is annotated with that information. The InvalidHandleValue attribute indicates which values are considered invalid. You should not be comparing that to docs.

If CreateFile had incompatible sentinel values, it would have had its return type changed in metadata so that we could annotate it correctly.

**Comment by ChrisDenton** [comment]
I did not express such a belief. Again, I'm trying to explain why windows-rs could not use [`HandleOrInvalid`](https://doc.rust-lang.org/std/os/windows/io/struct.HandleOrInvalid.html).

I'm sorry, but I'm unsure how else to state this more clearly.
