### ISSUE TITLE
How do I create child controls on a window? like pushbutton

### ISSUE THREAD

**Issue by iquanxin** [microsoft/windows-rs#1631]
```
extern "system" fn wndproc(window: HWND, message: u32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    unsafe {
        match message as u32 {
            WM_CREATE => {
                println!("WM_CREATE");
                // create button
                let instance = GetModuleHandleA(None);
                CreateWindowExA(
                    Default::default(),
                    "button",
                    "btn",
                    WS_CHILD | WS_VISIBLE | WINDOW_STYLE(1),
                    0,
                    0,
                    80,
                    30,
                    window,
                    HMENU(1),
                    instance,
                    std::ptr::null(),
                );
                LRESULT(0)
            }
            WM_PAINT => {
                println!("WM_PAINT");
                ValidateRect(window, std::ptr::null());
                LRESULT(0)
            }
            WM_DESTROY => {
                println!("WM_DESTROY");
                PostQuitMessage(0);
                LRESULT(0)
            }
            _ => DefWindowProcA(window, message, wparam, lparam),
        }
    }
}
```
Do not display button controls in the window

**Comment by MRahilly** [comment]
The following example creates buttons as child windows:
// Charles Petzold's HexCalc example rewritten in Rust

use windows::{
    core::*,
    Win32::{
        Foundation::*,
        System::{
            LibraryLoader::GetModuleHandleA,
            Threading::Sleep,
            Diagnostics::Debug::MessageBeep,
            SystemServices::MAXDWORD,
        },
        Graphics::Gdi::{
            HBRUSH, WHITE_BRUSH, GetStockObject,
        },
        UI::{
            WindowsAndMessaging::*, Input::KeyboardAndMouse::*
        },
        Globalization::*,
    },
};

fn main() -> Result<()> {
    unsafe {
        let hinstance = GetModuleHandleA(None);
        debug_assert!(hinstance.0 != 0);

        let window_class = "HexCalc";

        let wc = WNDCLASSA {
            style: CS_HREDRAW | CS_VREDRAW,
            lpfnWndProc: Some(wnd_proc),
            hInstance: hinstance,
            hCursor: LoadCursorA(None, PCSTR(IDC_ARROW.0 as _)),
            hbrBackground: HBRUSH(GetStockObject(WHITE_BRUSH).0),
            lpszClassName: PCSTR(b"HexCalc\0".as_ptr() as _),
            ..Default::default()
        };

        let atom = RegisterClassA(&wc);
        debug_assert!(atom != 0);

        let hwnd = CreateWindowExA(
            Default::default(),
            window_class,
            "Hex Calculator",
            WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_BORDER,
            CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT,
            None,
            None,
            hinstance,
            std::ptr::null_mut(),
        );

        ShowWindow(hwnd, SW_SHOW);

        let mut msg = MSG::default();
        while GetMessageA(&mut msg, HWND(0), 0, 0).into() {
            TranslateMessage(&mut msg);
            DispatchMessageA(&mut msg);
        }

        Ok(())
    }
}

extern "system" fn wnd_proc(hwnd: HWND, message: u32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    static mut NEW_NUMBER: bool = true;
    static mut OPERATION: CHAR = CHAR('=' as u8); // for ANSI
    static mut NUMBER: u32 = 0;
    static mut FIRST_NUMBER: u32 = 0;

    unsafe {
        match message as u32 {
            WM_CREATE => {
                let hinstance = GetModuleHandleA(None);

                struct Button {
                    label: &'static str,
                    id: i32,
                    x: i32, y: i32, nwidth: i32, nheight: i32
                }
        
                const SIZE: usize = 29;
        
                let buttons: [Button; SIZE] = [
                    Button{label: "0",      id:  27, x:  52, y:   8, nwidth: 100, nheight: 28},
                    Button{label: "D",      id:  68, x:  16, y:  48, nwidth:  28, nheight: 28},
                    Button{label: "E",      id:  69, x:  52, y:  48, nwidth:  28, nheight: 28},
                    Button{label: "F",      id:  70, x:  88, y:  48, nwidth:  28, nheight: 28},
                    Button{label: "+",      id:  43, x: 124, y:  48, nwidth:  28, nheight: 28},
                    Button{label: "&&",     id:  38, x: 160, y:  48, nwidth:  28, nheight: 28},
                    Button{label: "A",      id:  65, x:  16, y:  80, nwidth:  28, nheight: 28},
                    Button{label: "B",      id:  66, x:  52, y:  80, nwidth:  28, nheight: 28},
                    Button{label: "C",      id:  67, x:  88, y:  80, nwidth:  28, nheight: 28},
                    Button{label: "-",      id:  45, x: 124, y:  80, nwidth:  28, nheight: 28},
                    Button{label: "|",      id: 124, x: 160, y:  80, nwidth:  28, nheight: 28},
                    Button{label: "7",      id:  55, x:  16, y: 112, nwidth:  28, nheight: 28},
                    Button{label: "8",      id:  56, x:  52, y: 112, nwidth:  28, nheight: 28},
                    Button{label: "9",      id:  57, x:  88, y: 112, nwidth:  28, nheight: 28},
                    Button{label: "*",      id:  42, x: 124, y: 112, nwidth:  28, nheight: 28},
                    Button{label: "^",      id:  94, x: 160, y: 112, nwidth:  28, nheight: 28},
                    Button{label: "4",      id:  52, x:  16, y: 144, nwidth:  28, nheight: 28},
                    Button{label: "5",      id:  53, x:  52, y: 144, nwidth:  28, nheight: 28},
                    Button{label: "6",      id:  54, x:  88, y: 144, nwidth:  28, nheight: 28},
                    Button{label: "/",      id:  47, x: 124, y: 144, nwidth:  28, nheight: 28},
                    Button{label: "<",      id:  60, x: 160, y: 144, nwidth:  28, nheight: 28},
                    Button{label: "1",      id:  49, x:  16, y: 176, nwidth:  28, nheight: 28},
                    Button{label: "2",      id:  50, x:  52, y: 176, nwidth:  28, nheight: 28},
                    Button{label: "3",      id:  51, x:  88, y: 176, nwidth:  28, nheight: 28},
                    Button{label: "%",      id:  37, x: 124, y: 176, nwidth:  28, nheight: 28},
                    Button{label: ">",      id:  62, x: 160, y: 176, nwidth:  28, nheight: 28},
                    Button{label: "0",      id:  48, x:  16, y: 208, nwidth:  28, nheight: 28},
                    Button{label: "Back",   id:   8, x:  52, y: 208, nwidth:  64, nheight: 28},
                    Button{label: "Equals", id:  61, x: 124, y: 208, nwidth:  64, nheight: 28}
                ];
        
                for i in 0..SIZE {
                    CreateWindowExA(Default::default(), "BUTTON",
                        buttons[i].label,
                        WS_CHILD | WS_VISIBLE | WS_TABSTOP | WINDOW_STYLE(BS_PUSHBUTTON as u32),
                        buttons[i].x, buttons[i].y, buttons[i].nwidth, buttons[i].nheight,
                        hwnd, HMENU(buttons[i].id as isize), hinstance, std::ptr::null_mut()
                    );
                }

                LRESULT(0)
            }
            WM_SIZE => {
                let mut rect = RECT{left: 0, top: 0, right: 204, bottom: 244};
                AdjustWindowRect(&mut rect, WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_BORDER, false);
                SetWindowPos(hwnd, HWND(0), 0, 0, rect.right - rect.left, rect.bottom - rect.top, SWP_NOMOVE);

                LRESULT(0)
            }
            WM_SETFOCUS => {
                LRESULT(0)
            }
            WM_KEYDOWN => {
                if wparam == WPARAM(VK_LEFT.0 as usize) { // send VK_LEFT as WM_CHAR
                    SendMessageA(hwnd, WM_CHAR, WPARAM(VK_BACK.0 as usize), LPARAM(0)); // WPARAM(VK_BACK.0 as usize), LPARAM(0)
                }

                LRESULT(0)
            }
            WM_CHAR => {
                let mut ch = CharUpperA(PSTR(wparam.0 as _)).0 as u8;
                if ch == VK_RETURN.0 as u8 {
                    ch = '=' as u8;
                }

                let hwnd_button = GetDlgItem(hwnd, wparam.0 as i32);
                if hwnd_button != HWND(0) {
                    SendMessageA(hwnd_button, BM_SETSTATE, WPARAM(1), LPARAM(0));
                    Sleep(250); // 0.25s button press
                    SendMessageA(hwnd_button, BM_SETSTATE, WPARAM(0), LPARAM(0));
                }
                else {
                    MessageBeep(0);
                }

                SendMessageA(hwnd, WM_COMMAND, WPARAM(ch as usize), LPARAM(0));

                LRESULT(0)
            }
            WM_COMMAND => {
                let id = wparam.0 as u16;

                SetFocus(hwnd);

                if id == VK_BACK.0 {                    // backspace
                    NUMBER /= 16;
                    show_number(hwnd, NUMBER);
                }
                else if id == VK_ESCAPE.0 {             // escape
                    NUMBER = 0;
                    show_number(hwnd, NUMBER);
                }
                else if u_isxdigit(id as i32) == 1 {
                    if NEW_NUMBER {
                        FIRST_NUMBER = NUMBER;
                        NUMBER = 0;
                    }
                    NEW_NUMBER = false;

                    if NUMBER <= MAXDWORD >> 4 {
                        let offset = if u_isdigit(id as i32) != 0 {'0' as u8} else {'A' as u8 - 10};
                        let offset = offset as u32;
                        NUMBER = 16 * NUMBER + id as u32 - offset;
                        show_number(hwnd, NUMBER);
                    }
                    else {
                        MessageBeep(0);
                    }
                }
                else {                                  // operation
                    if !NEW_NUMBER {
                        NUMBER = calculate(FIRST_NUMBER, OPERATION, NUMBER);
                        show_number(hwnd, NUMBER);
                    }
                    NEW_NUMBER = true;
                    OPERATION = CHAR(id as u8);
                }

                LRESULT(0)
            }
            WM_DESTROY => {
                PostQuitMessage(0);

                LRESULT(0)
            }
            _ => DefWindowProcA(hwnd, message, wparam, lparam),
        }
    }
}

fn show_number(hwnd: HWND, number: u32) {
    unsafe {
        let buffer = format!("{:X}\0", number);
        SetDlgItemTextA(hwnd, VK_ESCAPE.0 as i32, PCSTR(buffer.as_ptr() as _));
    }
}

fn calculate(first_number: u32, operation: CHAR, number: u32) -> u32 {
    const EQU: CHAR = CHAR('=' as u8);
    const ADD: CHAR = CHAR('+' as u8);
    const SUB: CHAR = CHAR('-' as u8);
    const MUL: CHAR = CHAR('*' as u8);
    const AND: CHAR = CHAR('&' as u8);
    const OR:  CHAR = CHAR('|' as u8);
    const POW: CHAR = CHAR('^' as u8);
    const SHL: CHAR = CHAR('<' as u8);
    const SHR: CHAR = CHAR('>' as u8);
    const DIV: CHAR = CHAR('/' as u8);
    const MOD: CHAR = CHAR('%' as u8);
    
    match operation {
        EQU => {
            number
        }
        ADD => {
            first_number + number
        }
        SUB => {
            first_number - number
        }
        MUL => {
            first_number * number
        }
        AND => {
            first_number & number
        }
        OR => {
            first_number | number
        }
        POW => {
            first_number ^ number
        }
        SHL => {
            first_number << number
        }
        SHR => {
            first_number >> number
        }
        DIV => {
            if number != 0 {first_number / number} else {MAXDWORD}
        }
        MOD => {
            if number != 0 {first_number % number} else {MAXDWORD}
        }
        _ => 0,
    }
}

**Comment by iquanxin** [comment]
@MRahilly thanks, I found the problem.
