### ISSUE TITLE
Bug: IDXGISwapChain3::ResizeBuffers1 generated with very restrictive interface

### ISSUE THREAD

**Issue by nathanvoglsam** [microsoft/windows-rs#1638]
### Which crate is this about?

windows

### Crate version

0.34

### Summary

Currently `IDXGISwapChain3::ResizeBuffers1` currently has a very restrictive interface.

It looks like the compile time checks introduced in #1570 that, as far as I can tell from the discussion, were supposed to be reverted (?) made it through into the release.

`IDXGISwapChain3::ResizeBuffers1` in most non trivial cases will be called with a non compile-time value for `BufferCount` as this number needs to vary user driven configuration of the swap chain for enabling/disabling v-sync. Currently that's not really possible without special casing each value for `BufferCount`, which will at least almost always be 2 or 3.

See current docs [here](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Dxgi/struct.IDXGISwapChain4.html#method.ResizeBuffers1)

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc 
rustup home:  C:\Users\Nathan\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)  
nightly-2019-04-06-x86_64-pc-windows-msvc
nightly-2021-06-15-x86_64-pc-windows-msvc
nightly-2021-09-29-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)  
rustc 1.59.0 (9d1b2106e 2022-02-23)

### Reproducible example

```rust
Code-gen issue
```

### Crate manifest

```toml
[package]
name = "aleph-windows"
version = "0.1.0"
authors = ["Nathan Voglsam <nathanvoglsam420@gmail.com>"]
description = "The aleph-engine windows interface"
license = "MIT"
repository = "https://github.com/nathanvoglsam/aleph"
documentation = "https://docs.rs/aleph-windows/"
readme = "README.md"
## TODO: keywords = ["engine", "graphics", "directx", "game"]
## TODO: categories = ["game-engines"]
edition = "2021"

[badges]
azure-devops = { project = "nathanvoglsam420/Aleph", pipeline = "nathanvoglsam.aleph", build = "1" }

[dependencies.once_cell]
version = "1"

[target.'cfg(not(target_vendor = "uwp"))'.dependencies.windows]
version = "0.34"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_Memory",
    "Win32_System_Services",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
    "Win32_System_WindowsProgramming",
    "Win32_Storage_StructuredStorage",
    "Win32_Security",
]

[target.'cfg(target_vendor = "uwp")'.dependencies.windows]
version = "0.34"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D12",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_Memory",
    "Win32_System_Services",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
    "Win32_System_WindowsProgramming",
    "Win32_Storage_StructuredStorage",
    "Win32_Security",
    "System",
]
```

### Expected behavior

Fully exposed API that doesn't hide BufferCount

### Actual behavior

Very painful interface that makes calling the function impossible for values that are only known at runtime.

### Additional comments

As a work-around in the mean time at least the raw function can be called by copy pasting and modifying the implementation of the wrapper function. Calling this directly works
```rs
(windows::core::Interface::vtable(&self.0)
    .base
    .ResizeBuffers1)(
    ::core::mem::transmute_copy(&self.0),
    ::core::mem::transmute(buffer_count),
    ::core::mem::transmute(width),
    ::core::mem::transmute(height),
    ::core::mem::transmute(format),
    ::core::mem::transmute(flags),
    ::core::mem::transmute(p_creation_node_mask),
    ::core::mem::transmute(pp_present_queue),
)
```

**Comment by kennykerr** [comment]
The improvements in #1570 just limited the array transformations further to a much smaller set of scenarios, primarily disabling the transformation in cases where any array parameters are optional. I see in this case that the two array paramaters share the length parameter but they're both required so I assumed that would still be callable. 

```C#
unsafe HRESULT ResizeBuffers1([In] uint BufferCount, [In] uint Width, [In] uint Height, [In] DXGI_FORMAT Format, [In] uint SwapChainFlags, [In][Const][NativeArrayInfo(CountParamIndex = 0)] uint* pCreationNodeMask, [In][NativeArrayInfo(CountParamIndex = 0)] IUnknown* ppPresentQueue);
```

Can you provide a simple example of the calling pattern that you think should be possible for this particular function that is not possible with 0.34? 

FYI @samlh @chyyran @damyanp

**Comment by chyyran** [comment]
Seems like the issue is that `pcreationnodemask`  and `pppresentqueue` require const length of size `PARAM0`, this is what @samlh was talking about with `ID3D12CommandQueue::UpdateTileMappings` in #1570

**Comment by kennykerr** [comment]
Well, all that's left is to remove *all* support for array parameters that share a length parameter. All such methods would require explicit arguments for length and pointers. I'll get a PR ready.

**Comment by kennykerr** [comment]
Have a quick look at #1641 if you could. You can see that `ResizeBuffers1` is no longer transformed.

**Comment by kennykerr** [comment]
[0.35.0](https://github.com/microsoft/windows-rs/releases/tag/0.35.0) is published and includes this fix.
