### ISSUE TITLE
Question: how are supported API added in the windows-rs crate?

### ISSUE THREAD

**Issue by Nariod** [microsoft/windows-rs#1639]
Hello,

Thanks so much for this crate, the binaries I compile are 5 or 6 times lighter using windows-rs than using the previous winapi/ntapi crates. That's a pretty huge quality of life improvement!
There are API that are not implemented in this crate but are implemented in the ntapi crate ([ntcreatesection](https://docs.rs/ntapi/0.3.7/ntapi/ntmmapi/fn.NtCreateSection.html) is an example). Does this crate aim to implement all the win32 API? Is there a roadmap we can follow somewhere to check the latest implementations and the coming ones?

Cheers!

**Comment by kennykerr** [comment]
Thanks, glad you like it! 

The APIs are derived from metadata produced by projects like [win32metadata](https://github.com/microsoft/win32metadata), which in turn derives them from the Windows SDK. The `ntapi` crate appears to include undocumented APIs, which are not included in the Windows SDK. You can bring it up on the `win32metadata` repo but I suspect that they won't be included as they're undocumented. 

Of course, if someone were to produce metadata for these APIs then `windows-rs` would happily generate bindings for them.
