### ISSUE TITLE
Feature request: Add WinSock conversion utilities

### ISSUE THREAD

**Issue by GamePad64** [microsoft/windows-rs#1650]
### Motivation

Rust has its own network library in std::net, which has its own IpAddr types and SocketAddr types.
So, there would be a good feature to add From and Into traits for matching WinSock structs, so other devs don't have to do it by hand.

```
IN_ADDR <-> Ipv4Addr
IN6_ADDR <-> Ipv6Addr
SOCKADDR_IN <-> SocketAddrV4
SOCKADDR_IN6 <-> SocketAddrV6
SOCKADDR_INET <-> SocketAddr
```

### Drawbacks

None

**Comment by kennykerr** [comment]
Related to #760
