### ISSUE TITLE
Feature request: Implement WinSock endianness conversion using simple safe bit shifts without invoking WinSock function

### ISSUE THREAD

**Issue by GamePad64** [microsoft/windows-rs#1651]
### Motivation

Implement `hton*` and `ntoh*` functions as Rust-native safe implementations. This will give a little performance benefit and allows using these functions in unsafe-free code.

### Rationale and alternatives

This design supports inlining, which can give a little bonus to performance

**Comment by ryancerium** [comment]
Network byte order is big endian, and the built-in [i32::to_be](https://doc.rust-lang.org/std/primitive.i32.html#method.to_be) and [i32::from_be](https://doc.rust-lang.org/std/primitive.i32.html#method.from_be) functions do that. There are implementations for all the primitive types already.

**Comment by GamePad64** [comment]
Good point! Maybe, add some sort of recommendation (compile warning?) for these functions so hard-core C switchers could use built-in functions instead?

**Comment by kennykerr** [comment]
The `windows` and `windows-sys` crates are generated from metadata that spans many thousands of APIs. There are bound to be overlaps with the Rust standard library, but the goal of these crates is to faithfully provide direct access to these Windows APIs. Making recommendations is not really in scope or practical for us to do in general. As a rule of thumb, developers should consider the Rust standard library before looking for Windows-specific APIs when searching for a solution.
