### ISSUE TITLE
Soundness of PCWSTR::drop_param

### ISSUE THREAD

**Issue by kaivol** [microsoft/windows-rs#1652]
Crate: windows (version 0.34.0)

### Summary 

When passing a `&str` to a function expecting a `IntoParam<PCWSTR>`, the `IntoParam<PCWSTR>::into_param` implementation for `&str` creates a clone of the string on the heap, which is then converted into a `Box<[u16]>` and again into a raw pointer to construct the `PCWSTR`. When the `Param` is dropped later, in the `Abi::drop_param` function a `Box` is recreated using the pointer in `PCWSTR`, but the argument to `Box::from_raw` is just a `*mut u16` as the length of the string is not (directly) known at this point. Doesn't this violate the requirements of `Box::from_raw` and lead to a memory leak?
I am not very familiar with the inner workings of this library, so please correct me if there are any misunderstandings on my side.

**Comment by kennykerr** [comment]
Yes, this seems a little fishy. It's not immediately clear what the solution is, given that `from_raw` would presumably need a slice to reconstruct a boxed representation and that would require the length, which isn't stored in the `PCSTR` / `PCWSTR`.

**Comment by kennykerr** [comment]
I'll probably just switch to using the same heap allocator I use for `HSTRING`.

**Comment by kennykerr** [comment]
[0.35.0](https://github.com/microsoft/windows-rs/releases/tag/0.35.0) is published and includes this fix.
