### ISSUE TITLE
Should `as_ptr_or_null` really convert empty slices to null?

### ISSUE THREAD

**Issue by ducklin5** [microsoft/windows-rs#1653]
### Context
I'm currently trying to create an application that uses windows graphics capture. 
This apparently requires that I use the `D3D11CreateDevice` function: [alexchandel/screenshot-rs](https://github.com/alexchandel/screenshot-rs)
According to the C++ API, this function accepts `pFeatureLevels` as a pointer (to an array) : [D3D11CreateDevice C++ API]( https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-d3d11createdevice)
```C++
HRESULT D3D11CreateDevice(
  [in, optional]  IDXGIAdapter            *pAdapter,
                  D3D_DRIVER_TYPE         DriverType,
                  HMODULE                 Software,
                  UINT                    Flags,
  [in, optional]  const D3D_FEATURE_LEVEL *pFeatureLevels,
                  UINT                    FeatureLevels,
                  UINT                    SDKVersion,
  [out, optional] ID3D11Device            **ppDevice,
  [out, optional] D3D_FEATURE_LEVEL       *pFeatureLevel,
  [out, optional] ID3D11DeviceContext     **ppImmediateContext
);
```
If the pointer is null then it will use some system defined default set of features (this is what I want).

### Problem
However in rust this function currently only takes `pFeatureLevels` as a slice: [D3D11CreateDevice Rust binding](https://github.com/microsoft/windows-rs/blob/3376a148f56c1de3aff2d7a000ec9941dec3e68f/crates/libs/windows/src/Windows/Win32/Graphics/Direct3D11/mod.rs#L7) (View raw Line 7)
**_It's not intuitively clear how to set it to null._** 
I even tried `std::ptr::null()` and `*std::ptr::null()` as arguments. But the former doesn't compile, the latter gives unexpected behaviour.

Digging into the code, I realized the slice was being converted to a ptr for the C API using `as_ptr_or_null`:  [D3D11CreateDevice Rust binding](https://github.com/microsoft/windows-rs/blob/3376a148f56c1de3aff2d7a000ec9941dec3e68f/crates/libs/windows/src/Windows/Win32/Graphics/Direct3D11/mod.rs#L7) (View raw Line 14)

And `as_ptr_or_null` is defined as:
https://github.com/microsoft/windows-rs/blob/3376a148f56c1de3aff2d7a000ec9941dec3e68f/crates/libs/windows/src/core/mod.rs#L103-L109

So according to this if I want to pass a nullptr to the underlying C function, I just have to pass an empty array to the rust function. Yay problem solved?? Yes but....

What if the intention was to pass in an empty array of features? There would be no way to do that from rust because that would be interpreted as null and a null value triggers the default feature list? Since `as_ptr_or_null` is a core function... I imagine there are other functions that use it this way. 

### Solution?
Wouldnt it be better to use something like `Option<&[T]>` for array arguments than can also be null?

**Comment by kennykerr** [comment]
Does `D3D11CreateDevice` actually behave differently in C++ depending on whether you pass an empty list or a null pointer? Just trying to understand whether this is an actual limitation or just a hypothetical question.

**Comment by ducklin5** [comment]
I made a small test program.
```c++
// main.cpp
#include <d3d11.h>
#include <iostream>
#include <stdlib.h>

using namespace std;

bool InitializeD3D11(const D3D_FEATURE_LEVEL *levels, int lvl_count) {
	D3D_FEATURE_LEVEL valid_feature_level;

	IDXGIAdapter *adapter = nullptr;
	ID3D11Device *dev = nullptr;
	ID3D11DeviceContext *ctx = nullptr;
	HRESULT hr = D3D11CreateDevice(adapter, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0,
			levels, lvl_count, D3D11_SDK_VERSION, &dev,
			&valid_feature_level, &ctx);

	if (dev) return true;
	return false;
};

int main() {

	cout << "D3D11 with feature_levels = nullptr."
		<< "\n\tSuccess: "
		<< InitializeD3D11(nullptr, 0) << "\n";

	D3D_FEATURE_LEVEL empty[] = {};
	cout << "D3D11 with feature_levels = {}. "
		<< "\n\tSuccess: "
		<< InitializeD3D11(empty, 0) << "\n";

	D3D_FEATURE_LEVEL feature_levels[] = {
		D3D_FEATURE_LEVEL_11_1,
		D3D_FEATURE_LEVEL_11_0,
	};
	cout << "D3D11 with feature_levels = "
		<< "{D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0}."
		<< "\n\tSuccess: "
		<< InitializeD3D11(feature_levels, std::size(feature_levels)) << "\n";
}
```
``` sh
~/dev/temp/d3d11test$ g++ main.cpp -o d3d11test -ld3d11
~/dev/temp/d3d11test$ ./d3d11test.exe
D3D11 with feature_levels = nullptr.
        Success: 1
D3D11 with feature_levels = {}.
        Success: 0
D3D11 with feature_levels = {D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0}.
        Success: 1
```

Turns out no device is created if an empty array is passed it. So in this case I suppose `as_ptr_or_null` is harmless.
But there is still the issue that the rust binding behaves slightly different from official documentation and there is no way to know how to pass a "null" unless you find the rust definition of the function.

**Comment by kennykerr** [comment]
In practice, it has been quite challenging to find a happy medium between the APIs and the metadata when it comes to array parameters. I've already scaled back the win32 array support substantially. If you find an API where the bindings don't allow the API to be used correctly, do let us know.

**Comment by ducklin5** [comment]
Sounds good. I'll be sure to make an issue if I run into any blockers. Thanks for all the awesome work and your speedy reply.
I'll go ahead and close this since my question has been answered.
