### ISSUE TITLE
`IDataTransferManagerInterop.GetForWindow` cannot infer first generic argument

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1656]
This method has an explicit generic argument to indicate the interface to query for but if this is provided, Rust fails to infer the type of the first generic argument. This is a collision between the use of the `IntoParam` trait (which should be inferred) and the `Interface` trait (which should be explicit).

**Comment by rylev** [comment]
Does `interface.GetForWindow<_, IMyInterface>(window)` work?

**Comment by kennykerr** [comment]
Yes, that works but it's not very intuitive especially with more complex API signatures where there might be multiple convertible parameters. Here's an example:

```
[dependencies.windows]
version = "0.35"
features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
]
```

```rust
use windows::{core::*, Win32::Foundation::*, Win32::UI::Shell::*};

fn main() -> Result<()> {
    unsafe {
        let interop: Option<IDataTransferManagerInterop> = None;

        if let Some(interop) = interop {
            let _ = interop.GetForWindow::<_, IDataObjectProvider>(HWND(0))?;
        }

        Ok(())
    }
}
```

This particular API isn't a train smash - just hoping we could remove this wart for the sake of more complex APIs.

**Comment by kennykerr** [comment]
Closing as nothing comes to mind.
