### ISSUE TITLE
Working blocks sample attached - for 0.34

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#1661]
@kennykerr
[blocks 0.34.zip](https://github.com/microsoft/windows-rs/files/8419207/blocks.0.34.zip)

**Comment by kennykerr** [comment]
Looks like you ported [my C++/WinRT composition](https://github.com/microsoft/cppwinrt/blob/master/vsix/ProjectTemplates/VC/Windows%20Universal/CoreApp/App.cpp) sample. 😉 

Feel free to contribute a PR to update the [core_app](https://github.com/microsoft/windows-rs/tree/master/crates/samples/core_app) sample.

**Comment by MRahilly** [comment]
I did try but when it comes to Pull Requests I am at None rather than Some.

**Comment by MRahilly** [comment]
Maybe core_app2 alongside core_app. 

Seperately, would it make any sense to have an C++/WinRT sample referenced from here that boils XAML down to a component DLL that Rust apps could load?
