### ISSUE TITLE
Bug: 0.35.0 clears GetLastError on somewhere

### ISSUE THREAD

**Issue by topia** [microsoft/windows-rs#1664]
### Which crate is this about?

windows

### Crate version

0.35.0

### Summary

I called QueryDosDeviceW with `&str` and `Vec<u16>`.
with 0.34.0, I can get LastError (with `Error::from_win32`) if the function returns 0, but with 0.35.0 returns No error only.

### Toolchain version/configuration

efault host: x86_64-pc-windows-msvc
rustup home:  D:\data\depot\rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
aarch64-apple-ios
aarch64-unknown-linux-gnu
nvptx64-nvidia-cuda
wasm32-unknown-unknown
wasm32-wasi
x86_64-apple-darwin
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.59.0 (9d1b2106e 2022-02-23)

### Reproducible example

```rust
use windows::{
    Win32::Storage::FileSystem::QueryDosDeviceW,
    core::Error,
};

fn main() {
    let mut buf: Vec<u16> = vec![0; 20 as usize];
    let out_chars = unsafe {
        QueryDosDeviceW("C:", &mut buf)
    };
    let err = Error::from_win32();
    println!("out-chars: {}", out_chars);
    if out_chars == 0 {
        println!("error: {:?}", err);
    } else {
        buf.truncate(out_chars as usize);
        println!("out: {:?}", String::from_utf16_lossy(&buf));
    }
}
```

### Crate manifest

```toml
[dependencies.windows]
version = "0.35.0"
features = [
    "alloc",
    "Win32_Storage_FileSystem"
]
```

### Expected behavior

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\windows-rs-0-35-bug.exe`
out-chars: 0
error: Error { code: 0x8007007A, message: The data area passed to a system call is too small.
 }

Process finished with exit code 0
```

### Actual behavior

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\windows-rs-0-35-bug.exe`
out-chars: 0
error: Error { code: 0x00000000, message: The operation completed successfully.
 }

Process finished with exit code 0
```

### Additional comments

(update) I believe it is caused by BSTR handling.

Windows Version (if curious): Windows 11 21H2 (Build 22000.593)

**Comment by topia** [comment]
I slightly changed my code to avoid alloc:
```rust
    let drive: Vec<u16> = "C:\0".encode_utf16().collect();
    let drive_pcwstr = PCWSTR(drive.as_ptr());
    let out_chars = unsafe {
        QueryDosDeviceW(drive_pcwstr, &mut buf)
    };
```
and I got the correct error:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\windows-rs-0-35-bug.exe`
out-chars: 0
error: Error { code: 0x8007007A, message: The data area passed to a system call is too small.
 }
```

So, this regression should be caused by [this change](https://github.com/microsoft/windows-rs/commit/ea1a99141e58508c6409ad54b41a0600ca9cc86c#diff-35d3cb2c8c81e5bf67c14670aaf33faa75ddc052228e8474fb3a40309d4c7152).

**Comment by kennykerr** [comment]
Well spotted! Indeed, it turns out that `SysFreeString` clears the last error on success. I will have to use a different allocator that doesn't call `SetLastError`.

**Comment by kennykerr** [comment]
#1665 fixes this issue - thanks for the feedback!

**Comment by topia** [comment]
Thanks for fixing it! I'll check it on the next release, but the new test case covers my problem perfectly.

**Comment by kennykerr** [comment]
[0.36.0](https://github.com/microsoft/windows-rs/releases/tag/0.36.0) has now been reased and includes this fix.

**Comment by topia** [comment]
Thanks! I confirmed that (with my test case).

By the way, I used that method in the loop (to handle `ERROR_INSUFFICIENT_BUFFER`), and through research about this bug, I realized that it requires memory allocation by design.
So I temporarily rewrote my code with `Vec<u16>` utf-16 conversion by myself and `PCWSTR(vec.as_ptr())`. I'll look for a more suitable solution later.
