### ISSUE TITLE
`PCWSTR` and `PCSTR` should not have public constructors

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#1671]
In order to ensure safety and correctness `PCWSTR` and `PCSTR` need to maintain several invariants such as being null terminated. However, the constructors for these types are public, allowing users to put any pointer they want inside without having to call `unsafe`. Instead, we should offer an `unsafe` constructor function that at least draws the user's attention to the invariants that they must be upholding.

**Comment by kennykerr** [comment]
Yes, this is a general problem affecting other types as well. I was thinking of adding a `from_raw` method inspired by `Box`. Something to keep in mind is that sometimes the raw value held by these types won't be null terminated or even a string at all.

**Comment by kennykerr** [comment]
This was largely addressed by #1897 and other recent improvements.
