### ISSUE TITLE
How does in the world does this work?

### ISSUE THREAD

**Issue by timleg002** [microsoft/windows-rs#1676]
```rust
let immde: IMMDeviceEnumerator = CoCreateInstance(&MMDeviceEnumerator, None, CLSCTX_ALL)?;
let imm = immde.GetDefaultAudioEndpoint(EDataFlow(0 /*eRender*/), ERole(1 /*multimedia*/))?;
let mut iae: Option<IAudioEndpointVolume> = None;
imm.Activate(
       &IAudioEndpointVolume::IID, 
      CLSCTX_INPROC_SERVER, 
      &PROPVARIANT::default(),
      &mut iae as *mut _ as *mut _
)?;
iae.unwrap().SetMasterVolumeLevelScalar(0.6, &GUID::default())?;
```

This works. I just wanna know how. I got this code directly from the CoCreateInstance function, since it "knows" how to directly return the object. Maintainer did a pretty great job hiding away all the ugliness, but this one I wonder how it even works. Casting an `enum`? Casting it as `*mut _` twice? Probably the `_` signifies two different types.

**Comment by tim-weis** [comment]
This can be confusing indeed. After all, an [`Option`](https://doc.rust-lang.org/std/option/enum.Option.html) is an enum, a discriminated union where the compiler usually synthesizes a hidden field that records the variant currently stored. That is, unless things get special.

Looking at the code you'll find that `IAudioEndpointVolume` is defined as

```rust
#[repr(transparent)]
pub struct IAudioEndpointVolume(::windows::core::IUnknown);
```

and the contained `IUnknown`

```rust
#[repr(transparent)]
pub struct IUnknown(core::ptr::NonNull<core::ffi::c_void>);
```

The `#[repr(transparent)]` attribute marks a type as having the same layout as its enclosed type. It is purely used by the compiler during semantic analysis. As far as code generation goes, a transparent type completely vanishes, leaving just the inner type behind. You could thus think of `IAudioEndpointVolume` as being equivalent to

```rust
type IAudioEndpointVolume = core::ptr::NonNull<core::ffi::c_void>;
```

So essentially you have an `Option<NonNull<T>>`, and it is [`NonNull`](https://doc.rust-lang.org/std/ptr/struct.NonNull.html) that nudges `Option` into special mode:

> Unlike `*mut T`, the pointer must always be non-null, even if the pointer is never dereferenced. This is so that enums may use this forbidden value as a discriminant – `Option<NonNull<T>>` has the same size as `*mut T`.

In this case, the compiler will no longer introduce a dedicated field to serve as the discriminant; it is using the stored value instead, where zero maps to `None` and a non-zero value to `Some`. This yields a type that's binary compatible with a raw pointer, but has `Option`-semantics in the type system, making it hard to accidentally dereference a null pointer.

This explains why reinterpreting the `Option` here as if it were a pointer is fine. The subsequent two casts are required to first turn the reference into a raw pointer, and then change the raw pointer to a pointer of the appropriate type.

**Comment by timleg002** [comment]
> This can be confusing indeed. After all, an [`Option`](https://doc.rust-lang.org/std/option/enum.Option.html) is an enum, a discriminated union where the compiler usually synthesizes a hidden field that records the variant currently stored. That is, unless things get special.
> 
> Looking at the code you'll find that `IAudioEndpointVolume` is defined as
> 
> ```rust
> #[repr(transparent)]
> pub struct IAudioEndpointVolume(::windows::core::IUnknown);
> ```
> 
> and the contained `IUnknown`
> 
> ```rust
> #[repr(transparent)]
> pub struct IUnknown(core::ptr::NonNull<core::ffi::c_void>);
> ```
> 
> The `#[repr(transparent)]` attribute marks a type as having the same layout as its enclosed type. It is purely used by the compiler during semantic analysis. As far as code generation goes, a transparent type completely vanishes, leaving just the inner type behind. You could thus think of `IAudioEndpointVolume` as being equivalent to
> 
> ```rust
> type IAudioEndpointVolume = core::ptr::NonNull<core::ffi::c_void>;
> ```
> 
> So essentially you have an `Option<NonNull<T>>`, and it is [`NonNull`](https://doc.rust-lang.org/std/ptr/struct.NonNull.html) that nudges `Option` into special mode:
> 
> > Unlike `*mut T`, the pointer must always be non-null, even if the pointer is never dereferenced. This is so that enums may use this forbidden value as a discriminant – `Option<NonNull<T>>` has the same size as `*mut T`.
> 
> In this case, the compiler will no longer introduce a dedicated field to serve as the discriminant; it is using the stored value instead, where zero maps to `None` and a non-zero value to `Some`. This yields a type that's binary compatible with a raw pointer, but has `Option`-semantics in the type system, making it hard to accidentally dereference a null pointer.
> 
> This explains why reinterpreting the `Option` here as if it were a pointer is fine. The subsequent two casts are required to first turn the reference into a raw pointer, and then change the raw pointer to a pointer of the appropriate type.

Thank you for this explanation. Well in the future, I certainly hope that this would be handled in a more beautiful manner, as in more clearly visible of what's being done "behind the scenes".
