### ISSUE TITLE
Bug: Generated VTable method calls drop() on potentially uninitialized value

### ISSUE THREAD

**Issue by michaelwoerister** [microsoft/windows-rs#1680]
### Which crate is this about?

windows

### Crate version

0.35.0

### Summary

I use the `#[implement]` macro to implement [IStringDisplayableConcept](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/struct.IStringDisplayableConcept.html). The `ToDisplayString()` method there is a callback that gets called from C++. The C++ side does *not initialize* the `BSTR` that the `BSTR* displayString` out parameter points to, so the following code generated by windows-rs will call `SysFreeString()` on an uninitialized value:

```rust
#[cfg(feature = "Win32_Foundation")]
impl IStringDisplayableConcept_Vtbl {
    pub const fn new<Identity: ::windows::core::IUnknownImpl, Impl: IStringDisplayableConcept_Impl, const OFFSET: isize>() -> IStringDisplayableConcept_Vtbl {
        unsafe extern "system" fn ToDisplayString<Identity: ::windows::core::IUnknownImpl, Impl: IStringDisplayableConcept_Impl, const OFFSET: isize>(this: *mut ::core::ffi::c_void, contextobject: ::windows::core::RawPtr, metadata: ::windows::core::RawPtr, displaystring: *mut super::super::super::Foundation::BSTR) -> ::windows::core::HRESULT {
            let this = (this as *mut ::windows::core::RawPtr).offset(OFFSET) as *mut Identity;
            let this = (*this).get_impl() as *mut Impl;
            match (*this).ToDisplayString(::core::mem::transmute(&contextobject), ::core::mem::transmute(&metadata)) {
                ::core::result::Result::Ok(ok__) => {
                    *displaystring = ::core::mem::transmute(ok__); // <--- THIS WILL TRY TO DROP THE POINTEE BEFORE OVERWRITING
                    ::windows::core::HRESULT(0)
                }
                ::core::result::Result::Err(err) => err.into(),
            }
        }
        Self { base__: ::windows::core::IUnknownVtbl::new::<Identity, OFFSET>(), ToDisplayString: ToDisplayString::<Identity, Impl, OFFSET> }
    }
    pub fn matches(iid: &windows::core::GUID) -> bool {
        iid == &<IStringDisplayableConcept as ::windows::core::Interface>::IID
    }
}
```
(from https://github.com/microsoft/windows-rs/blob/f00461914705ff1673606d38dba8e3a31730775d/crates/libs/windows/src/Windows/Win32/System/Diagnostics/Debug/impl.rs)

The bug is not hit when calling `IStringDisplayableConcept::ToDisplayString()` from Rust because the wrapper there properly initializes the `BSTR` being pointed to.

### Toolchain version/configuration

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (directory override for '...')
rustc 1.62.0-nightly (306ba8357 2022-04-05)

### Reproducible example

```rust
// NOTE: I was not able to reproduce this from pure Rust code. 
//       The following is an example implementation of IStringDisplayableConcept, 
//       but ToDisplayString() is not called with an uninitialized value.

use windows::{
    core::implement,
    Win32::{
        Foundation::BSTR,
        System::Diagnostics::Debug::{
            IKeyStore, IModelObject, IStringDisplayableConcept, IStringDisplayableConcept_Impl,
        },
    },
};

#[implement(IStringDisplayableConcept)]
struct Foo;

impl IStringDisplayableConcept_Impl for Foo {
    fn ToDisplayString(
        &self,
        _: &Option<IModelObject>,
        _: &Option<IKeyStore>,
    ) -> windows::core::Result<BSTR> {
        Ok(BSTR::from("bar"))
    }
}

fn main() {
    let foo: IStringDisplayableConcept = Foo.into();
    let _ = unsafe { foo.ToDisplayString(None, None) };
}
```

### Crate manifest

```toml
[package]
name = "windows-rs-drop-repro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
version = "0.35.0"
features = [
    "alloc",
    "interface",
    "implement",
    "Win32_System_Diagnostics_Debug",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_Kernel",
]
```

### Expected behavior

I expected the potentially uninitialized value being pointed to not to be touched, e.g. by using [std::ptr::write](https://doc.rust-lang.org/std/ptr/fn.write.html):

```rust
#[cfg(feature = "Win32_Foundation")]
impl IStringDisplayableConcept_Vtbl {
    pub const fn new<Identity: ::windows::core::IUnknownImpl, Impl: IStringDisplayableConcept_Impl, const OFFSET: isize>() -> IStringDisplayableConcept_Vtbl {
        unsafe extern "system" fn ToDisplayString<Identity: ::windows::core::IUnknownImpl, Impl: IStringDisplayableConcept_Impl, const OFFSET: isize>(this: *mut ::core::ffi::c_void, contextobject: ::windows::core::RawPtr, metadata: ::windows::core::RawPtr, displaystring: *mut super::super::super::Foundation::BSTR) -> ::windows::core::HRESULT {
            let this = (this as *mut ::windows::core::RawPtr).offset(OFFSET) as *mut Identity;
            let this = (*this).get_impl() as *mut Impl;
            match (*this).ToDisplayString(::core::mem::transmute(&contextobject), ::core::mem::transmute(&metadata)) {
                ::core::result::Result::Ok(ok__) => {
                    std::ptr::write(displaystring, ok__); // <--- Use std::ptr::write() 
                    ::windows::core::HRESULT(0)
                }
                ::core::result::Result::Err(err) => err.into(),
            }
        }
        Self { base__: ::windows::core::IUnknownVtbl::new::<Identity, OFFSET>(), ToDisplayString: ToDisplayString::<Identity, Impl, OFFSET> }
    }
    pub fn matches(iid: &windows::core::GUID) -> bool {
        iid == &<IStringDisplayableConcept as ::windows::core::Interface>::IID
    }
}
```

### Actual behavior

Heap corruption 😃 

### Additional comments

The support for implementing COM interfaces in windows-rs is already much more ergonomic than going via com-rs. Thanks for all your hard work!

**Comment by rylev** [comment]
Good catch. I believe the proper thing to do here is to use [`std::ptr::write`](https://doc.rust-lang.org/stable/std/ptr/fn.write.html) which does not drop what the destination pointer is originally pointing out and is specifically noted as being the correct thing to use for "for initializing uninitialized memory". We should be making sure we use `std::ptr::write` anywhere where we might be trying to write to uninitialized memory.

If we move to `std::ptr::write` though, we will potentially leak memory if the out pointer points to initialized memory which has a drop implementation that frees resources. Safe Rust does not rely on `drop` being run so this is *safe*, but it might introduce some potential footguns. However, I think in this particular case, the likelihood of the out pointer leaking memory if it doesn't have its `drop` impl run is pretty low.

**Comment by michaelwoerister** [comment]
This looks relevant too: https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#out-pointers

The docs there also suggest `std::ptr::write()` and discourage using `std::mem::zeroed()`.

**Comment by kennykerr** [comment]
Note that the vtable functions should not use types that implement `Drop` - for the most part they don't - this is something I have been meaning to fix more holistically.

**Comment by michaelwoerister** [comment]
I think the pattern described at https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#out-pointers is the recommended way of dealing with out-pointers to potentially uninitialized values.
