### ISSUE TITLE
NonNull<c_void> cannot be shared between threads safely

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#1682]
@kennykerr 
The issue more than likely my coding but this might be related to #1391

[xaml_code 0.35 wip.zip](https://github.com/microsoft/windows-rs/files/8473959/xaml_code.0.35.wip.zip)
.

**Comment by kennykerr** [comment]
Please include a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with your issue (no zip files) or head on over to https://stackoverflow.com/
