### ISSUE TITLE
Problems constructing debug callback interfaces

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/windows-rs#1690]
methods such as `windows::Win32::System::Diagnostics::Debug::IDebugClient5::SetEventCallbacks` takes an `IntoParam<'a, IDebugEventCallbacks>`, the problem is I don't have any way to construct a `IDebugEventCallbacks`. What is the correct way to create this?

After some searching I have discovered `windows::Win32::System::Diagnostics::Debug::IDebugEventCallbacks_Impl` (which `IDebugEventCallbacks` does not implement - should it?).

I assume there is some way to convert a struct which implements this `impl` trait into an instance of `IDebugEventCallbacks` but I'm not sure how..? Based on the struct definition it looks like it might be a tuple struct wrapping a pointer to a `dyn IDebugEventCallbacks` but that's just an educated guess, so I might be able to create this struct using a transmute from a pointer..?

Another option is I might be misunderstanding what `IntoParam` does..? It's undocumented so I don't really have an idea, but it seems that it's manually implemented for certain types but it doesn't seem to be implemented for this type from any other type...

**Comment by kennykerr** [comment]
As we discussed offline, you need to use the `implement` feature to unlock the `implement` macro (along with any other features required by any required traits) that you can then use to implement the desired COM interface.
