### ISSUE TITLE
Crate documentation not up to date

### ISSUE THREAD

**Issue by varunkamra** [microsoft/windows-rs#1698]
WIndows build macro has probably been deprecated but there is no indication given on windows crate version 0.35.0. Please update the crate docs so that it is easier to find an alternative on the docs. Currently I am trying to search online and getting nowhere.

https://docs.rs/windows/0.6.0/windows/macro.build.html

**Comment by tim-weis** [comment]
Code generation has been pulled out of the `windows` crate and moved into the [`windows-bindgen`](https://crates.io/crates/windows-bindgen) crate. There's [documentation](https://docs.rs/windows-bindgen/0.35.0), too, even if it doesn't explain a whole lot at this time. The [bindings tool](https://github.com/microsoft/windows-rs/tree/master/crates/tools/bindings) implementation is more educational in this respect.

**Comment by kennykerr** [comment]
Crate documentation can be found here:
* [windows](https://microsoft.github.io/windows-docs-rs/)
* [windows-sys](https://docs.rs/windows-sys)

The `build` macro is no longer needed as these crates are pre-generated.
