### ISSUE TITLE
Bug: Accidentally clears win32 last error

### ISSUE THREAD

**Issue by wtokuno** [microsoft/windows-rs#1714]
### Which crate is this about?

windows

### Crate version

0.35.0

### Summary

In some cases, accidentally clears win32 last error.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc  
rustup home:  C:\Users\wtokuno\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.60.0 (7737e0b5c 2022-04-04)

### Reproducible example

```rust
use std::ptr;

use windows::Win32::{
    Foundation::{GetLastError, INVALID_HANDLE_VALUE},
    System::Memory::{CreateFileMappingW, PAGE_READWRITE},
};

fn main() {
    let name = "Global\\MyFileMappingObject";
    unsafe {
        // Example 1.
        let _ = dbg!(CreateFileMappingW(
            INVALID_HANDLE_VALUE,
            ptr::null(),
            PAGE_READWRITE,
            0,
            256,
            name,
        ));
        // expected error result of ERROR_ACCESS_DENIED since the process doesn't have the "SeCreateGlobalPrivilege" privilege,
        // but got: Err(Error { code: 0x00000000, message: The operation completed successfully })
        dbg!(GetLastError());
    }

    unsafe {
        // Exmaple 2.
        let _ = dbg!(CreateFileMappingW(
            INVALID_HANDLE_VALUE,
            ptr::null(),
            PAGE_READWRITE,
            0,
            256,
            name,
        ));
        dbg!(GetLastError());

        let _ = dbg!(CreateFileMappingW(
            INVALID_HANDLE_VALUE,
            ptr::null(),
            PAGE_READWRITE,
            0,
            256,
            name,
        ));
        dbg!(GetLastError());
        // expected ERROR_ALREADY_EXISTS alongside Ok(HANDLE), but got NO_ERROR
    }
}
```

### Crate manifest

```toml
[dependencies.windows]
version = "0.35.0"
features = [
    "alloc", 
    "Win32_Foundation", 
    "Win32_Security",
    "Win32_System_Memory", 
    "Win32_System_SystemServices",
]
```

### Expected behavior

Example 1: error result of `ERROR_ACCESS_DENIED`
Example 2: `ERROR_ALREADY_EXISTS` alongside `Ok(HANDLE)`

### Actual behavior

Example 1: error result of `NO_ERROR`
Example 2: `NO_ERROR` alongside `Ok(HANDLE)`

### Additional comments

This is because the function `SysFreeString` clears win32 last error; the `SysFreeString` is called when `Param<PCWSTR>` is dropped.

**Comment by kennykerr** [comment]
[0.36.0](https://github.com/microsoft/windows-rs/releases/tag/0.36.0) has now been reased and includes this fix.
