### ISSUE TITLE
Bug: Inherited interface members are not generated for XAML controls

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#1715]
### Which crate is this about?

windows

### Crate version

0.35.0

### Summary

For Windows Runtime types, inherited interface members should show up for `coclass`es that derive from those interfaces. This doesn't appear to work (any more) for stock UWP XAML controls.

### Reproducible example

```rust
use windows::{
    core::{IInspectable, Result},
    UI::Xaml::Controls::Button,
};

fn main() -> Result<()> {
    let btn = Button::new()?;
    btn.SetContent(IInspectable::try_from("🦀")?)?;

    Ok(())
}
```

### Crate manifest

```toml
[package]
name = "itf_inheritance"
version = "0.0.0"
edition = "2021"

[dependencies.windows]
version = "0.35.0"
features = [
    "UI_Xaml_Controls",
]
```

### Expected behavior

The code should compile.

### Actual behavior

The compiler issues the following error:

```
error[E0599]: no method named `SetContent` found for struct `Button` in the current scope
 --> src\main.rs:8:9
  |
8 |     btn.SetContent(IInspectable::try_from("🦀")?)?;
  |         ^^^^^^^^^^ method not found in `Button`
```

Looking into the generated `impl Button` block it seems that only the immediate [`Button`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button) members are generated. None of the derived interface members show up.

### Additional comments

This used to work as expected in the past (such as 0.18.0, using the `build!` macro). It also appears to work with the Windows App SDK/WinUI 3 (as illustrated in [this sample](https://github.com/microsoft/windows-app-rs/blob/8bb7a82f99327303725cf35420c233853a2f3206/crates/samples/xamlapp/src/main.rs#L63-L73)). It just doesn't work with the stock UWP XAML controls (I haven't checked WinUI 2).

**Comment by tim-weis** [comment]
That's unfortunate, even if understandable. I suppose there's my motivation to move to WinUI 2 then.

Still, is this something that should be added to the FAQ, or is XAML with native code such a niche topic that only a handful of users would even ask?

**Comment by kennykerr** [comment]
The Xaml team have been silent on https://github.com/microsoft/microsoft-ui-xaml/issues/2488 so it's understandable that there might be some confusion, so an FAQ entry seems appropriate. As you know, C++ struggles with Xaml for various reasons. Rust basically has all of the same issues except that its compiler is many times slower than the C++ compiler, making it even less appealing.
