### ISSUE TITLE
please mark crate windows_reader as deprecated/replaced

### ISSUE THREAD

**Issue by liigo** [microsoft/windows-rs#1719]
It toke me a long time to realize that, the old crate `windows_reader` has been replaced with `windows_matadata`. I didn't get a tip information from the following links:

https://crates.io/crates/windows_reader
https://docs.rs/windows_reader/0.30.0

I'd like to suggest releasing a new version of windows_reader and put something into README.md.

**Comment by kennykerr** [comment]
Can do.

**Comment by kennykerr** [comment]
I've published a new version of those old crates with a link back to the repo. Note that these crates are currently only meant to support the generation of the primary `windows` and `windows-sys` crates and are still very much unstable.
