### ISSUE TITLE
docs.rs failed to build `windows-sys`

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1721]
https://docs.rs/crate/windows-sys/latest

It might have run out of memory, although I'm not sure. We may have to host the docs elsewhere, as we already do for the `windows` crate. 😢

**Comment by rylev** [comment]
The [logs](https://docs.rs/crate/windows-sys/0.36.0/builds/548347) don't show anything super useful. It looks like the builder killed the rustdoc (with `SIGKILL`). I guess running out of memory or it taking longer than the 15 minute allotted time could be to blame.

**Comment by kennykerr** [comment]
It's likely memory because when I run it locally it uses about 3.5GB and the docs.rs limits is 3GB. 

<img width="968" alt="image" src="https://user-images.githubusercontent.com/9845234/165555148-68417896-d2a5-42a1-bc32-266570b694a5.png">

`rustdoc` just can't handle large crates at all. Even when it compiles, the resulting HTML isn't designed for a large amount of content. May have to explore our own doc generator or see about rolling Rust docs into http://docs.microsoft.com/

**Comment by riverar** [comment]
Resolved. New docs are up. https://docs.rs/windows-sys/latest/windows_sys/

**Comment by kennykerr** [comment]
It's unfortunate that we had to "hack" docs.rs to fix this but that will have to do for now. 😬
