### ISSUE TITLE
Bug: impossible to get successful HRESULT code from functions returning Result<()>

### ISSUE THREAD

**Issue by ancwrd1** [microsoft/windows-rs#1728]
### Which crate is this about?

windows

### Crate version

0.36.1

### Summary

Windows API functions which return `HRESULT` are curently wrapped into the inline functions returning `Result<()>`.
This has an unpleasant consequence that it is impossible to get the exact successful HRESULT code which is necessary in many cases, for example `InitializeSecurityContextW`.

### Toolchain version/configuration

Default host: x86_64-pc-windows-gnu
rustup home:  C:\Users\testuser\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.60.0 (7737e0b5c 2022-04-04)

### Additional comments

The Rust's `Result<>` does not play well with HRESULT, perhaps the functions should just return a plain HRESULT.

**Comment by kennykerr** [comment]
I transferred the original issue you created here: https://github.com/microsoft/win32metadata/issues/910

Closing this as a duplicate.

**Comment by ancwrd1** [comment]
Ah, I thought there was some problem with the first issue I created because I couldn't find it anymore.
Sorry for the duplicate.
