### ISSUE TITLE
Bug: Named constants not working in descriptors

### ISSUE THREAD

**Issue by hntd187** [microsoft/windows-rs#1741]
### Which crate is this about?

windows

### Crate version

0.36.1

### Summary

If I write 

```rust
let desc = D3D11_BUFFER_DESC {
            ByteWidth: mem::size_of::<VertexConstantBuffer>() as _,
            Usage: D3D11_USAGE_DYNAMIC,
            BindFlags: D3D11_BIND_CONSTANT_BUFFER,
            CPUAccessFlags: D3D11_CPU_ACCESS_WRITE,
            MiscFlags: 0,
            StructureByteStride: 0
};
```
This does not compile even though `D3D11_BIND_CONSTANT_BUFFER` and `D3D11_CPU_ACCESS_WRITE` are both `#[repr(transparent)]`

```
    |
364 |             BindFlags: D3D11_BIND_CONSTANT_BUFFER,
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found struct `D3D11_BIND_FLAG`
```

I know I can just `D3D11_BIND_CONSTANT_BUFFER.0`, but that somewhat defeats the purpose does it not?

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\shcar\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.60.0 (7737e0b5c 2022-04-04)

### Reproducible example

```rust
use windows::Win32::Graphics::Direct3D11::*;
pub fn main() {
  let desc = D3D11_BUFFER_DESC {
            BindFlags: D3D11_BIND_CONSTANT_BUFFER,
            CPUAccessFlags: D3D11_CPU_ACCESS_WRITE,
            ..Default::default()
  };
}
```

### Crate manifest

```toml
[dependencies]
windows = { version = "0.36", features = [
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation"
] }
```

### Expected behavior

The code compiles.

### Actual behavior

```
    |
364 |             BindFlags: D3D11_BIND_CONSTANT_BUFFER,
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found struct `D3D11_BIND_FLAG`
```

**Comment by ryancerium** [comment]
The metadata for that field has it as a `UInt32`: 
 https://github.com/marlersoft/win32json/blob/main/api/Graphics.Direct3D11.json#L4163

Open a ticket in the [win32metadata project](https://github.com/microsoft/win32metadata/issues) letting them know what type it should actually be.  If you list as many places as possible it's wrong all at once it'll help you out.

These are the structs that Ctrl+F for `BindFlags` found:

```
D3D11_TEXTURE2D_DESC1
D3D11_TEXTURE3D_DESC1
D3D11_BUFFER_DESC
D3D11_TEXTURE1D_DESC
D3D11_TEXTURE2D_DESC
D3D11_TEXTURE3D_DESC
```

**Comment by hntd187** [comment]
@ryancerium I think the issue here is not that the type is wrong but that `#[repr(transparent)]` should allow this to be a drop in replacement. But it does not. I'm a bit confused why this happens.

**Comment by kennykerr** [comment]
That's not what `#[repr(transparent)]` means. This attribute just tells the compiler that the two types will be guaranteed to have the same layout for ABI compatibility, not that they are type aliases.

**Comment by hntd187** [comment]
Okay, I misunderstood what it did. I'll file a ticket with the metadata project, sorry for the misunderstanding.

**Comment by kennykerr** [comment]
No worries, we're all learning here. 😉

**Comment by kennykerr** [comment]
Thanks for opening the metadata issue!
