### ISSUE TITLE
Bug: Type discrepancy with `DrvEnablePDEV`

### ISSUE THREAD

**Issue by Razordor** [microsoft/windows-rs#1743]
### Which crate is this about?

windows, windows-sys

### Crate version

0.34.0

### Summary

[PFN_DrvEnablePDEV](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Devices/Display/type.PFN_DrvEnablePDEV.html#) is documented as a function pointer type.
This is a discrepancy because [DrvEnablePDEV](https://docs.microsoft.com/en-us/windows/win32/api/winddi/nf-winddi-drvenablepdev) is actually a function.

**Comment by tim-weis** [comment]
That doesn't appear to be a bug. A driver implements a function that matches the signature of `DrvEnablePDEV`<sup>1</sup> and communicates its address (of type `PFN_DrvEnablePDEV`) to the system in its implementation of [`DrvEnableDriver`](https://docs.microsoft.com/en-us/windows/win32/api/winddi/nf-winddi-drvenabledriver). By populating a [`DRVENABLEDATA`](https://docs.microsoft.com/en-us/windows/win32/api/winddi/ns-winddi-drvenabledata) structure the system subsequently knows where, in memory, to find the function to call for function index `INDEX_DrvEnablePDEV`.

While I'm not sure how useful `PFN_DrvEnablePDEV` is in Rust code, seeing that the [`DRVFN`](https://docs.microsoft.com/en-us/windows/win32/api/winddi/ns-winddi-drvfn)s get reinterpreted as a different function pointer type, the generated code accurately reflects the system header files.

---

<sup>1</sup> *`DrvEnablePDEV` is really just a placeholder name, useful for documentation. A driver can choose any arbitrary name in its place. The system-facing interface consists solely of a function address alongside the respective function index.*

**Comment by riverar** [comment]
Re-opened briefly so I could add extra context from Discord to potentially help others.

Developer was attempting to get device-dependent color space chromaticity coordinates/endpoints and found themselves in a bad neighborhood 😆. They are in user-mode, so calling a driver's specific `DrvEnablePDEV` impl. to get `COLORINFO` (by way of `GDIINFO`) was not needed.

Suggested instead establishing a device context and calling the Windows Color System APIs (GetColorSpace, GetLogColorSpace, etc.). We're in the process of validating this. (I'll edit this afterwards.)
