### ISSUE TITLE
Feature request: use primitives from standard library

### ISSUE THREAD

**Issue by Razordor** [microsoft/windows-rs#1745]
### Motivation

I believe it would be more consistent with rust to make use of the resources in [`std::os::windows`](https://doc.rust-lang.org/nightly/std/os/windows/index.html). This includes [`std::os::windows::raw::HANDLE`](https://doc.rust-lang.org/nightly/std/os/windows/raw/type.HANDLE.html) and [`std::os::windows::raw::SOCKET`](https://doc.rust-lang.org/nightly/std/os/windows/raw/type.SOCKET.html).
This would make use of the standard library with windows-rs crate easier by making use of compatibility between them.

### Drawbacks

None that I can see yet.

### Alternatives

A possible alternative is to take the current [`HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HANDLE.html) in windows-rs and apply a trait to it such as [`std::os::windows::io::AsRawHandle`](https://doc.rust-lang.org/nightly/std/os/windows/io/trait.AsRawHandle.html) to convert back to the standard library types.

### Additional context
This is related to #760.

**Comment by kennykerr** [comment]
The challenge with the first approach is that Windows has many handle types whereas the standard library only defines HANDLE and SOCKET and even those it defines in a somewhat questionable way (handles aren't necessarily pointers and sockets are pointer-sized integers). I would however be open to exploring implementing the second alternative of implementing the standard library trait. Also related to #1622.

**Comment by riverar** [comment]
Right, `std::os::windows::raw::HANDLE` doesn't appear to be valid. There's a handle discussion here you might find fun to read #1643.

**Comment by ryancerium** [comment]
The pointer provenance stuff was the first thing that crossed my mind as well @riverar .

**Comment by kennykerr** [comment]
Thanks for the reminder. Closing in favor of those other conversations.
