### ISSUE TITLE
Online documentation still shows version 0.35.0 (current version is 0.36.1)

### ISSUE THREAD

**Issue by michaelwoerister** [microsoft/windows-rs#1754]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/1825894/167852751-8a8144fc-b686-4848-971c-4af59629b40c.png">

**Comment by kennykerr** [comment]
Yep, updating the `windows` crate docs is a tedious manual process that I still need to streamline somehow. docs.rs can't handle the `windows` crate because `rustdoc` is such a memory hog. I'll publish another cut of the docs next week when I publish 0.37 of the `windows` crate.

**Comment by kennykerr** [comment]
I published 0.37 this morning. Over three hours later, I'm still waiting for docs to build. 😢 

<img width="343" alt="image" src="https://user-images.githubusercontent.com/9845234/169368650-f27ec8b8-acda-43b9-bc2c-21b547f2a1a8.png">

**Comment by kennykerr** [comment]
The `windows` crate docs have now been updated to 0.37.

**Comment by michaelwoerister** [comment]
> I published 0.37 this morning. Over three hours later, I'm still waiting for docs to build. 😢

That seems excessive indeed :/
