### ISSUE TITLE
How to convert String/str/OsString/OsStr to PCWSTR?

### ISSUE THREAD

**Issue by shirshak55** [microsoft/windows-rs#1759]
Initially, I tried 

```rust
  let folderInfo = OsString::from("Please choose directory").;

    let lpbi = BROWSEINFOW {
        lpszTitle: PCWSTR(folderInfo.into()),
        ..Default::default()
    };
```

My main issue is I am unable to convert String or OsString into PCWSTR. I tried to look for examples, but I couldn't find any. Is it possible to do without fiddling bits?

After that, I tried to browse docs and I was helpless there.  I looked at the issue and I couldn't find so, I am creating this issue.

I tried to be smart, but alas I failed miserably.

```rust
fn main() {
    unsafe {
        let lpbi = BROWSEINFOW {
            lpszTitle: pcwstr_from("Pleasexxx choosexx folder"),
            ..Default::default()
        };
        let pidl = windows::Win32::UI::Shell::SHBrowseForFolderW(&lpbi);
    }
}

fn pcwstr_from<'a>(t: impl IntoParam<'a, PCWSTR>) -> PCWSTR {
    unsafe { t.into_param().abi() }
}

```
Sorry if it is an inappropriate question. Feel free to close it.

**Comment by rylev** [comment]
Thanks for the report! Unfortunately, the story around strings in the windows crate is not great. I hope to have an RFC open at some point to improve this. 

Until we improve this, I think you want something like the following;
```rust
let mut str = std::mem::ManuallyDrop::new("some string".encode_utf116().collect::<Vec<_>>());
str.push(0);
let len = str.len();
let capacity = str.capacity();
let str = PCWSTR(str.as_mut_ptr());
```

However, you'll need to remember that `PCWSTR` does not "own" it's memory so it will not be free on drop. So once you're done with `str`, you'll need to drop the memory:

```rust
let _ = Vec::<u16>::from_raw_parts(str.0, len, capacity);
```

There might be a simpler way to do this that I'm not thinking of off the top of my head, but it's clear we need to improve the story here.

There is some code in the windows crate that does this:
```rust
let hstring = core::mem::ManuallyDrop::new(windows::core::HSTRING::from("some string"));
let str = PCWSTR(hstring.as_wide().as_ptr());
```

But I believe this is a bug since `as_wide` does not include the trailing null byte which PCWSTR is supposed to include.

**Comment by riverar** [comment]
Agree with @rylev, strings need work. I think this was also on the FAQ docket.

But I would strongly suggest you not use `SHBrowseForFolder`. It opens an awful dialog with no text box, etc. and is generally hated by users. The remarks in the docs suggest this as well.

Instead, consider using FileOpenDialog as such. (The need for `str_from_pwstrz` or Ryan's helper is unfortunate indeed.)

```rust
use windows::{
    core::PWSTR,
    Win32::{
        Foundation::HWND,
        System::Com::{
            CoCreateInstance, CoInitializeEx, CLSCTX_INPROC_SERVER, COINIT_MULTITHREADED,
        },
        UI::Shell::{FileOpenDialog, IFileOpenDialog, SIGDN_FILESYSPATH},
    },
};

fn main() -> windows::core::Result<()> {
    unsafe {
        CoInitializeEx(std::ptr::null(), COINIT_MULTITHREADED)?;

        let dialog: IFileOpenDialog =
            CoCreateInstance(&FileOpenDialog, None, CLSCTX_INPROC_SERVER)?;
        dialog.SetTitle("https://github.com/microsoft/windows-rs/issues/1759")?;
        dialog.Show(HWND::default())?;
        let result = dialog.GetResult()?;
        let path = result.GetDisplayName(SIGDN_FILESYSPATH)?;

        println!("Selected file: {}", str_from_pwstrz(&path));
    }

    Ok(())
}

fn str_from_pwstrz(pwstr: &PWSTR) -> String {
    let mut ptr = pwstr.0;
    unsafe {
        loop {
            if ptr.read() == 00_00 {
                break;
            }
            ptr = ptr.add(1);
        }
        let len = ptr.offset_from(pwstr.0) as usize;
        return String::from_utf16_lossy(std::slice::from_raw_parts(pwstr.0, len));
    }
}
```

```toml
[package]
name = "app"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.windows]
version = "*"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_UI_Shell",
]
```

![image](https://user-images.githubusercontent.com/475132/168345289-1e3b0d0d-c600-4661-bd25-f74dff34b8a7.png)

**Comment by shirshak55** [comment]
@riverar thanks :) Also, I am rosy that windows-rs will have better docs & many examples like this.
