### ISSUE TITLE
C++/WinRT as() and try_as()

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#1764]
as() in C++/WinRT is cast()? in the Rust crate for Windows. It is not obvious what the equivalent of try_as() is. Thanks.

**Comment by riverar** [comment]
The `.cast()` impl. calls QueryInterface and returns a Result. It doesn't throw, so there's no need for a `try_as` equivalent.

**Comment by MRahilly** [comment]
Many thanks, I should have figured that.
