### ISSUE TITLE
SetWindowLongPtr is still missing

### ISSUE THREAD

**Issue by codecheck01** [microsoft/windows-rs#1774]
### Which crate is this about?

windows, windows-sys

### Crate version

0.37.0 windows / 0.36.1 windows-sys

### Summary

(https://github.com/microsoft/windows-rs/issues/644) was supposed to fix this problem, but it appears to still be missing.

**Comment by robmikh** [comment]
I see SetWindowLongPtrA and SetWindowLongPtrW. They require the Win32_UI_WindowsAndMessaging and Win32_Foundation features. Do you have both features enabled?

**Comment by codecheck01** [comment]
I have both features enables, it is 100% missing, I have to use SetWindowLongA/SetWindowLongW instead, but this is not the solution.

**Comment by codecheck01** [comment]
And to be sure, you just have to search from the [windows-rs git repo](https://github.com/microsoft/windows-rs/search?q=SetWindowLongPtr), 0 references found.

**Comment by robmikh** [comment]
Not sure what's going on with GitHub's search, I can see it here:
https://github.com/microsoft/windows-rs/blob/f30c1434e83af7b49abef1657e863f365ce3ce22/crates/libs/windows/src/Windows/Win32/UI/WindowsAndMessaging/mod.rs#L13698-L13729

Additionally, the [clock](https://github.com/microsoft/windows-rs/blob/f30c1434e83af7b49abef1657e863f365ce3ce22/crates/samples/direct2d/src/main.rs#L503-L525) sample and [minesweeper-rs](https://github.com/robmikh/minesweeper-rs/blob/09c395fbb44ccba350365adc3a20e56b11fb5f08/src/window.rs#L184-L214) both use the Set/GetWindowLongPtr variants. Are you targeting a 64-bit architecture?

**Comment by codecheck01** [comment]
No, I am targeting **i686-pc-windows-msvc**

> Not sure what's going on with GitHub's search, I can see it here:
> 
> https://github.com/microsoft/windows-rs/blob/f30c1434e83af7b49abef1657e863f365ce3ce22/crates/libs/windows/src/Windows/Win32/UI/WindowsAndMessaging/mod.rs#L13698-L13729
> 
> Additionally, the [clock](https://github.com/microsoft/windows-rs/blob/f30c1434e83af7b49abef1657e863f365ce3ce22/crates/samples/direct2d/src/main.rs#L503-L525) sample and [minesweeper-rs](https://github.com/robmikh/minesweeper-rs/blob/09c395fbb44ccba350365adc3a20e56b11fb5f08/src/window.rs#L184-L214) both use the Set/GetWindowLongPtr variants. Are you targeting a 64-bit architecture?

No, I am targeting **i686-pc-windows-msvc**

**Comment by robmikh** [comment]
SetWindowLongPtr is not available on 32-bit architectures:

(from winuser.h)
```cpp
#ifdef _WIN64
// ...
WINUSERAPI
LONG_PTR
WINAPI
SetWindowLongPtrW(
    _In_ HWND hWnd,
    _In_ int nIndex,
    _In_ LONG_PTR dwNewLong);
// ...
#else  /* _WIN64 */
// ...
#define GetWindowLongPtrW   GetWindowLongW
// ...
#endif /* _WIN64 */
```

**Comment by codecheck01** [comment]
> SetWindowLongPtr is not available on 32-bit architectures:
> 
> (from winuser.h)
> 
> ```c++
> #ifdef _WIN64
> // ...
> WINUSERAPI
> LONG_PTR
> WINAPI
> SetWindowLongPtrW(
>     _In_ HWND hWnd,
>     _In_ int nIndex,
>     _In_ LONG_PTR dwNewLong);
> // ...
> #else  /* _WIN64 */
> // ...
> #define SetWindowLongPtrW   SetWindowLongW
> // ...
> #endif /* _WIN64 */
> ```

Thank you very much for the assistance, indeed this is my bad.

I was looking at [**SetWindowLongPtrW function (winuser.h)**](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptrw):

> Note  To write code that is compatible with both 32-bit and 64-bit versions of Windows, use SetWindowLongPtr. When compiling for 32-bit Windows, SetWindowLongPtr is defined as a call to the [SetWindowLong](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowlonga) function.

**Comment by riverar** [comment]
Looks like this is resolved, closing. If I missed something, let me know.

**Comment by kennykerr** [comment]
Related to #1493
