### ISSUE TITLE
C++/WinRT xaml_typename() utility function

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#1775]
Is there an equivalent of this function available on the rust crate for windows?

**Comment by riverar** [comment]
No. Looks like it's a cppwinrt helper to support XAML https://github.com/microsoft/cppwinrt/blob/master/strings/base_xaml_typename.h. Skimming over it, you should be able to translate that over using Rust primitives.

**Comment by MRahilly** [comment]
Makes sense. Thanks.
