### ISSUE TITLE
How to use ` D3D_COMPILE_STANDARD_FILE_INCLUDE`?

### ISSUE THREAD

**Issue by Discreater** [microsoft/windows-rs#1789]
I want to use [`D3D_COMPILE_STANDARD_FILE_INCLUDE`](https://docs.microsoft.com/en-us/windows/win32/api/d3dcompiler/nf-d3dcompiler-d3dcompilefromfile#parameters) as the third parameter of  `windows::Windows::Win32::Graphics::Direct3D::Fxc::D3DCompileFromFile`.

But the type of `D3D_COMPILE_STANDARD_FILE_INCLUDE` is `u32`, rather than `ID3DInclude`.

**Comment by kennykerr** [comment]
Yes, that's a scary API. 😜 You could try transmuting the value (1) to `&ID3DInclude` and then pass that to the method.

**Comment by Discreater** [comment]
Sorry, I still have problem. After I transmuting it to `&ID3DInclude`, the program crashed at `D3DCinoukeFromFile`.
```rust
let d3d_include = std::mem::transmute::<_,&ID3DInclude>(D3D_COMPILE_STANDARD_FILE_INCLUDE as u64);
D3DCompileFromFile(
    hlsl_path,
    null(),
    d3d_include,
    "VSMain",
    "vs_5_0",
    compile_flags,
    0,
    &mut vertex_shader,
    &mut error,
)?;
```
I found it always crasches at `pinclude.into_param().abi()`.  Is my transmuting wrong?
