### ISSUE TITLE
How to access method pointers

### ISSUE THREAD

**Issue by ghost** [microsoft/windows-rs#1790]
Hello,

I know I am still not very experienced with Rust, and I am learning a lot every day, but after many attempts, I am still not able to resolve this.

I am trying to access method pointers with the **windows crate**, but I am crashing, it was fine before with the **winapi crate**.

**Working** (winapi crate):
```rust
if (*device).GetCreationParameters(&mut creation_params) != 0 {
    return 0;
};
```

**Not working** (windows crate):
```rust
if (*device).GetCreationParameters(&mut creation_params).is_ok() {
    return 0;
}
```

Another question, is it, in some way, possible to access method pointers with the **windows-sys crate**?

**Comment by rylev** [comment]
Can you provide a minimal reproducible example? It's hard to tell what's happening without seeing a full example that reproduces the issue.

**Comment by kennykerr** [comment]
If `device` is a regular COM interface then you can just call it (with the `windows` crate) like a regular method e.g. `object.Method(params)`. The Direct3D and Direct2D samples provide many examples to follow.

https://github.com/microsoft/windows-rs/tree/master/crates/samples

**Comment by codecheck01** [comment]
@rylev @kennykerr Sorry for not answering in time, I fixed my problem by using transmute. (I was accessing a null pointer)
