### ISSUE TITLE
Thanks to this awesome project!

### ISSUE THREAD

**Issue by ibigbug** [microsoft/windows-rs#1792]
Wanted to say a big thank to this awesome project!

I've been learning Rust and finally I was able to fully reimplement one of my projects from C# to Rust: https://github.com/Watfaq/PowerSession

During the reimplementation I got a lot help from this community from basic Rust knowledge to detailed windows-rs API usage, without which I won't be able to make it!

This project touches couple of areas of Win32 API (ConPty, Process, etc.). I know there are a lot good samples under https://github.com/microsoft/windows-rs/tree/master/crates/samples , hopefully this could add extra sample usages and can benefit other Rust/windows-rs beginners like me.

special thanks to @kennykerr / @riverar / @MarijnS95

**Comment by kennykerr** [comment]
So glad to hear of your success - keep it up!
