### ISSUE TITLE
Optimize `Tree`'s `flatten` method to avoid allocations

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1795]
Here's another related case:

https://github.com/microsoft/windows-rs/blob/04217210a2525810e50b29daffe290b42f5b8551/crates/libs/metadata/src/reader/tree.rs#L21-L24

_Originally posted by @kennykerr in https://github.com/microsoft/windows-rs/issues/1794#issuecomment-1145060538_

**Comment by AronParker** [comment]
It seems that this code is only used during build/code generation time, so reducing allocations should not be a top priority or am I mistaken? However, I tried an attempt in #1800 anyway, I believe the iterative approach will be the only way as flat_map requires IntoIterator, which given the nested structure of the layout should be quite difficult.

**Comment by kennykerr** [comment]
Code gen performance matters to those of us working on this project as we rely on it heavily. Notably, the `flatten` method exists to allow the tree to be regenerated concurrently via `rayon`.

**Comment by rylev** [comment]
I'be opened up an issue on the Rust compiler repo based on this: https://github.com/rust-lang/rust/issues/97686. It looks like there are legitimate reasons why doing this without allocation is not possible, but the error message is not very good.

**Comment by AronParker** [comment]
> I'be opened up an issue on the Rust compiler repo based on this: https://github.com/rust-lang/rust/issues/97686. It looks like there are legitimate reasons why doing this without allocation is not possible, but the error message is not very good.

That's what I tried at first too and got the same error, thanks for filing the issue.

**Comment by kennykerr** [comment]
Sounds like there's no easy answer. I did a quick test on performance and the non-release results show there's no value in optimizing `flatten` so simplest wins. 

```
File::new 7ms
Reader::new 110ms
reader.tree 2ms
tree.flatten 0ms
```
