### ISSUE TITLE
Test cross compilation in CI

### ISSUE THREAD

**Issue by est31** [microsoft/windows-rs#1799]
When skimming over the github actions CI, I couldn't see any build hosts on ubuntu or mac OS. So right now, even though #638 is closed, it could regress any time. Therefore, it would be good to test cross compilation in the CI.

The reason for filing is that I'm getting PRs by people trying to switch from `winapi` to `windows-rs` but I want people to still be able to target the windows platform from their non-windows computers. Thanks!

**Comment by kennykerr** [comment]
I don't have any experience with cross-compilation in Rust but happy to review a PR with a separate yml script that provides basic cross-compilation testing.

**Comment by est31** [comment]
@kennykerr I suppose such a PR requires a CLA?

**Comment by kennykerr** [comment]
Yes, I think all the Microsoft repos require a CLA.

**Comment by est31** [comment]
@kennykerr we will have to wait for someone else to do it then, as I don't sign away copyrights without receiving money back. It's great news though that you welcome a PR to fix this issue :).

**Comment by riverar** [comment]
I can poke at this over the weekend; I'm looking forward to @est31 sponsoring me/that work! 😆 🤑

I think we're still going to have an issue with the lack of umbrella libs (onecoreuap) in non-msvc toolchains. Guess we'll find out soon enough.

**Comment by est31** [comment]
@riverar that offer is very kind of you, but I have to politely decline. I don't receive sponsorships for my OSS work, so can't take some of that money to give it to you, and it is getting personal, but in my current employment in academia I don't have a lot of disposable income available either. I don't need it for my job, but so that I can switch OSS projects I'm maintaining to this crate (which seems to be better maintained than winapi). Maybe there is someone who can sponsor you instead, but it won't be me. I hope you understand.

**Comment by riverar** [comment]
@est31 Added the start of a workflow for this. i686 is a challenge due to mingw being a mess across platforms but it's on my ``// TODO` list. I also recognize these are not true tests as we don't execute the output on a Windows machine but that's coming next. (I have manually verified macOS and Ubuntu generated executables run on Windows.)

**Comment by est31** [comment]
@riverar that's very amazing, thank you!

**Comment by tim-weis** [comment]
@riverar I'm curious, do you have a better way to test GitHub actions other than pushing any changes upstream, waiting for GitHub to report success/error, and start over from there?

**Comment by riverar** [comment]
@tim-weis Not really, I just try to hide the mess in my own fork first. I haven't gotten around to building/hosting the agents locally [1]--I think GitHub Actions team could do better at making these more accessible. 

[1] https://github.com/actions/virtual-environments/tree/main/images
