### ISSUE TITLE
build script of `component` test fails on local PC

### ISSUE THREAD

**Issue by kaivol** [microsoft/windows-rs#1815]
Running `cargo test -p test_component` on my machine fails with 
```
error: failed to run custom build command for `test_component v0.0.0 (***\windows-rs\crates\tests\component)`                        

Caused by:
  process didn't exit successfully: `***\windows-rs\target\debug\build\test_component-db536ffeb1b9cbb3\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=src/component.idl

  --- stderr
  Microsoft (R) 32b/64b MIDLRT Compiler Engine Version 10.00.0231
  Copyright (c) Microsoft Corporation. All rights reserved.
  64 bit MIDLRT Processing ***\windows-rs\crates\tests\component\src\component.idl
  component.idl
  midlrt : error MIDL1001 : [msg]cannot open input file [context]winrtbase.idl
```
Since the tests pass in the GitHub Actions, the error must be in my device configuration. 
Are the prerequisites to run the build script specified somewhere?

### Versions: 

Crate version: latest version from GitHub (0.37.0)

Windows Version: 22621.1

MIDLRT version:
```
CommandType     Name           Version    Source
-----------     ----           -------    ------
Application     midlrt.exe     10.0.231.1 C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\midlrt.exe    
```

**Comment by kennykerr** [comment]
Looks like you might have an incomplete SDK installation. `winrtbase.idl` should be somewhere here:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.xxxxx.0\winrt\WinRTBase.idl
```

The latest I have installed is 10.0.22572.0, so perhaps there's something missing in the version you have.

**Comment by kaivol** [comment]
It looks like my SDK installation was indeed incomplete. After I reinstalled the SDK, the test works.
I think only the reference to `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt` in the PATH variable was missing, though.

Thanks for the help!

**Comment by Muon** [comment]
I've just encountered the same issue. `midlrt` stops complaining if I actually run it within `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\winrt`, but the Cargo build fails. This is with a fresh install of the Windows SDK. Any idea why it's searching in the working directory and not anywhere else?
