### ISSUE TITLE
min_xaml

### ISSUE THREAD

**Issue by uhuntu** [microsoft/windows-rs#1818]
I realized that crates\tools\windows\src\main.rs has this line "gen.min_xaml = true;", can someone explain why this setting, can I turn it off for example "gen.min_xaml = false;"

**Comment by tim-weis** [comment]
See related issue [here](https://github.com/microsoft/windows-rs/issues/1715#issue-1215565979). In short, if you need the `bindgen` crate to generate the `Windows.UI.Xaml` namespace, set `min_xaml` to `false`.
