### ISSUE TITLE
Feature request: Appx Packaging APIs

### ISSUE THREAD

**Issue by demberto** [microsoft/windows-rs#1821]
### Motivation

The Win32 Metadata project already has bindings for this interface, so why not?

### Additional context

Microsoft is promoting appx everywhere but the only language its APIs exists for is C/C++.

**Comment by demberto** [comment]
I find this quite interesting. Look at the official repo's ILSpy demonstration [pic](https://github.com/microsoft/win32metadata/raw/main/images/ILSpyWithWinmd.png). You can see **Windows.Win32.AppxPackaging** right there. But I checked the latest `winmd` file myself in ILSpy, it doesn't have `AppxPackaging` bindings. Why would they remove it?

**Comment by riverar** [comment]
These APIs are now under `Windows.Win32.Storage.Packaging`.

Docs: https://microsoft.github.io/windows-docs-rs/doc/windows/?search=Appx

**Comment by demberto** [comment]
Uhh, my bad, Weird choice to put it under Storage though
