### ISSUE TITLE
Feature request: Add Constructor to Windows.Storage.Streams.DataWriter

### ISSUE THREAD

**Issue by mattelkinsTC** [microsoft/windows-rs#1828]
### Motivation

The WinRT docs indicate that Windows.Storage.Streams.DataWriter has two constructors, a basic `new()` and an overload: `public DataWriter(IOutputStream outputStream);` This second constructor is missing from the windows crate. It would be handy when wanting to create a DataWriter based on an IOutputStream.

### Drawbacks

Some amount of time to implement, slightly more code to maintain.

### Rationale and alternatives

I'm sure there are workarounds and alternatives, but it seems simplest to parallel WinRT as much as possible.

### Additional context

This might be a metadata concern rather than a windows crate concern directly; I am uncertain.

**Comment by robmikh** [comment]
The second constructor is available as [`DataWriter::CreateDataWriter`](https://microsoft.github.io/windows-docs-rs/doc/windows/Storage/Streams/struct.DataWriter.html#method.CreateDataWriter).

**Comment by mattelkinsTC** [comment]
I don't know how I missed that. Thanks!

**Comment by kennykerr** [comment]
> but it seems simplest to parallel WinRT as much as possible.

Unfortunately, WinRT relies on method and constructor overloading, which Rust doesn't support, so we replace those overloads with explicit names derived from metadata.
