### ISSUE TITLE
Generate `QueryInterface`-like helper function for callbacks

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#1835]
It'd be great to have helper functions for callbacks with nicer signatures in the `windows` crate, just like "normal function" wrappers. For starters, when doing this to `Query` (or `QueryOptional`) callbacks, code can be written as follows:

```rust
let lib = unsafe { Library::new(dxcompiler_lib_name()) }.unwrap();
let create: Symbol<DxcCreateInstanceProc> = unsafe { lib.get(b"DxcCreateInstance\0") }.unwrap();

let compiler: IDxcCompiler2 = unsafe { DxcCreateInstanceProc(&create, &CLSID_DxcCompiler) }?;
let library: IDxcLibrary = unsafe { DxcCreateInstanceProc(&create, &CLSID_DxcLibrary) }?;
```

Without this we'd have to replace the last two lines with this atrocity (using `transmute` for lack of a non-verbose way to put together all the pointer casts):

```rust
let mut compiler = None::<IDxcCompiler2>;
let mut library = None::<IDxcLibrary>;

unsafe { (create.unwrap())(&CLSID_DxcCompiler, &IDxcCompiler2::IID, std::mem::transmute(&mut compiler)).ok()? };
unsafe { (create.unwrap())(&CLSID_DxcLibrary, &IDxcLibrary::IID, std::mem::transmute(&mut library)).ok()? };

let compiler = compiler.unwrap();
let library = library.unwrap();
```

There are currently 517 hits for `pub type PFN_` and there must be some that behave like `QueryInterface` (i.e. D3D10/11/12 `CREATE_DEVICE`). I'd like to get #747 reopened for this to make it in, but one major blocker was not having any (test) code that actively practices this system.

### Reasons to not do this

1. There currently doesn't seem to be any use of this "external symbol loading" for Windows, only when loading an external library like DXC (which can supposedly also be linked from `"windows"` directly if `#[link = "windows"]` on `DxcCreateInstance` is to be believed);
2. Since writing this code/example, `windows-rs` is [now more strict in requiring `_COM_Outptr_` SAL](https://github.com/microsoft/windows-rs/pull/1088#issuecomment-907808506) before marking functions/callbacks as `SignatureKind::Query`. This has been worked around for `DxcCreateInstance(2)` in https://github.com/microsoft/win32metadata/pull/890, but not for the `*Proc` function types (this will be PR'd to DXC soon™).

---

_Originally posted by @MarijnS95 in https://github.com/microsoft/windows-rs/issues/747#issuecomment-1160435284_

**Comment by kennykerr** [comment]
Here's a quick query looking for callbacks with query-like signatures:

```rust
fn main() {
    use windows_metadata::reader::*;

    let files = vec![
        File::new("/git/windows-rs/crates/libs/metadata/default/Windows.Win32.winmd").unwrap(),
    ];

    let reader = &Reader::new(&files);

    let root = reader.tree("Windows.Win32", &[]).unwrap();

    for tree in root.flatten() {
        for def in reader.namespace_types(tree.namespace) {
            if reader.type_def_kind(def) == TypeKind::Delegate
                && !reader.type_def_flags(def).winrt()
            {
                let method = reader.type_def_invoke_method(def);
                let signature = reader.method_def_signature(method, &[]);
                let kind = reader.signature_kind(&signature);

                if matches!(
                    kind,
                    SignatureKind::Query(_) | SignatureKind::QueryOptional(_)
                ) {
                    println!("{}", reader.type_def_name(def));
                }
            }
        }
    }
}
```

It only returns three results:

```
PFN_D3D12_CREATE_DEVICE
PFN_D3D12_GET_DEBUG_INTERFACE
PFN_D3D12_GET_INTERFACE
```

**Comment by MarijnS95** [comment]
I totally agree with stricter tests - it just seems like we have some work to do fixing up the headers and/or temporary overrides in `win32metadata`.

Do you still think it's worth pursuing this helper then? Are there other kinds of syntactic sugar that may be beneficial for `function` typedefs?

**Comment by kennykerr** [comment]
While this would be convenient for experimenting, I don't think there is enough demand for such a capability to warrant including all the extra code gen needed to make it happen.

**Comment by MarijnS95** [comment]
Also here, wrong close reason. You should close it as "not planned" etc.

**Comment by kennykerr** [comment]
Ah, I never noticed the close drop-down before - thanks!

**Comment by kennykerr** [comment]
Also in my defense, I used this drop-down to bulk close the issues tagged as questions. 😁 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/9845234/180487939-90aacae9-e89f-4fa1-80b4-710d7c8f54ef.png">

**Comment by MarijnS95** [comment]
> Ah, I never noticed the close drop-down before - thanks!

It's "new" (±2 months old IIRC). Feel free to reopen and close with the right status.


> Also in my defense, I used this drop-down to bulk close the issues tagged as questions.

I see, questions have no place on this repo?

**Comment by kennykerr** [comment]
I'm happy to try and answer questions but they're not actionable and thus get closed pretty quickly. If there's valuable information in the Q&A then we can create a PR to capture that information in the FAQ.

**Comment by MarijnS95** [comment]
I should apply that technique to my repos :smiling_imp:

**Comment by MarijnS95** [comment]
Hi @kennykerr! This still only applies to the original 3 delegates found in https://github.com/microsoft/windows-rs/issues/1835#issuecomment-1162491607, but I do have a few custom metadata bindings where these helpers are relevant too. And they'll be even more relevant when (if?) we can get the SAL annotation fixes for DirectXShaderCompiler working: https://github.com/microsoft/DirectXShaderCompiler/pull/4524. Should we re-discuss whether it is worth adding this helper again?

I still have a branch open and it mostly works: https://github.com/MarijnS95/windows-rs/compare/callback-query-interface-2, there's just one incompatibility. Currently parameters for the type alias are generated as follows:

https://github.com/microsoft/windows-rs/blob/2e7f99d9ca80bb8f1216db7964062daf42e80158/crates/libs/bindgen/src/delegates.rs#L25-L29

Watch what happens to `pouter`:

```rust
pub type PFNMagic = ::core::option::Option<
    unsafe extern "system" fn(
        pouter: ::core::option::Option<::windows_core::IUnknown>,
        // pouter: *mut ::core::ffi::c_void,
        riid: *const ::windows_core::GUID,
        ppvobject: *mut *mut ::core::ffi::c_void,
    ) -> ::windows_core::HRESULT,
>;
```

The function call arguments generated by `win32_args()` and `win32_params()` expect to be compatible with a `*mut c_void` type instead:

https://github.com/microsoft/windows-rs/blob/2e7f99d9ca80bb8f1216db7964062daf42e80158/crates/libs/bindgen/src/functions.rs#L198-L206

```rust
pub unsafe fn PFNMagic<P0, T>(
    func: &PFNMagic,
    pouter: P0,
) -> ::windows::core::Result<T>
where
    P0: ::windows_core::IntoParam<::windows_core::IUnknown>,
    T: ::windows::core::ComInterface,
{
    let mut result__ = ::std::ptr::null_mut();
    (func.unwrap())(
        pouter.into_param().abi(), // <------------- Boom. This *mut c_void is not compatible with Option<IUnknown>.
        &<T as ::windows_core::ComInterface>::IID,
        &mut result__,
    )
    .from_abi(result__)
}
```

What is the desired solution for this? Custom argument/input handling to match the target type of a delegate type alias, or adjust the argument type of that delegate type alias? And what if the metadata didn't annotate the pointer with `_In_opt_`?

---

On a closely related note (perhaps worth creating a new issue for) the `IntoParam<IUnknown>` argument is rather useless as it cannot be used to pass any COM object to the function. `ComInterface` would be a better trait as that guarantees (see `as_unknown()`) it is always castable to `IUnknown` (though, borrows vs owned moves have to be considered!). We could solve this even more generically by more broadly exposing `CanInto` (currently behind some `#[doc(hidden)]`) for "free" upcasts to known COM object interfaces in the hierarchy. I ran into the necessity for such a cast/hack in a few more places, but would have to look up where exactly to give more concrete use-case examples.
