### ISSUE TITLE
How to use MONITORINFOEX with GetMonitorInfoA?

### ISSUE THREAD

**Issue by SageSudo** [microsoft/windows-rs#1837]
Hi,

According to the Microsoft documentation for [GetMonitorInfo](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfow#parameters), the function's second parameter can be either a [MONITORINFO](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-monitorinfo) or [MONITORINFOEX](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-monitorinfoexa), however, in the windows-rs documentation for [GetMonitorInfoA](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Gdi/fn.GetMonitorInfoA.html), the function only accepts MONITORINFO as a second parameter.

Is there something I have to do to make MONITORINFOEX work with GetMonitorInfoA?

This is how I've went about trying GetMonitorInfoA:
```
use windows::Win32::{
    Foundation::POINT,
    Graphics::Gdi::{
        GetMonitorInfoA, MonitorFromPoint, MONITORINFO, MONITORINFOEXA, MONITOR_DEFAULTTONULL,
    },
    UI::WindowsAndMessaging::GetCursorPos,
};

fn main() {
    unsafe {
        let mut point = POINT::default();
        GetCursorPos(&mut point);

        let hmonitor = MonitorFromPoint(point, MONITOR_DEFAULTTONULL);

        let mut monitor_info = MONITORINFO {
            cbSize: std::mem::size_of::<MONITORINFOEXA>() as u32,
            ..MONITORINFO::default()
        };

        let mut monitor_info_ex = MONITORINFOEXA {
            monitorInfo: monitor_info,
            ..MONITORINFOEXA::default()
        };

        GetMonitorInfoA(hmonitor, &mut monitor_info_ex); //<-- Not possible.
    }
}
```

**Comment by riverar** [comment]
Hi @SageSudo, pass in `monitor_info_ex.monitorInfo`. It starts at the same offset as the extended structure and cleanly gets you around this funky API.

**Comment by kennykerr** [comment]
That's likely because you didn't initialize the `MONITORINFOEXA` with its size. It is the `cbSize` field that tells the `GetMonitorInfoA` function which structure you actually passed in. Here's a complete example:

```rust
use windows::{Win32::Foundation::*, Win32::Graphics::Gdi::*};

fn main() {
    unsafe {
        EnumDisplayMonitors(None, std::ptr::null(), Some(callback), LPARAM(0));
    }
}

extern "system" fn callback(handle: HMONITOR, _: HDC, _: *mut RECT, _: LPARAM) -> BOOL {
    unsafe {
        let mut info = MONITORINFOEXA::default();
        info.monitorInfo.cbSize = std::mem::size_of::<MONITORINFOEXA>() as _;
        GetMonitorInfoA(handle, &mut info.monitorInfo);
        let slice = std::slice::from_raw_parts(info.szDevice.as_ptr() as _, info.szDevice.len());
        println!("{}", std::str::from_utf8_unchecked(slice));
        BOOL(1)
    }
}
```

And here's what I get:

```
\\.\DISPLAY1
\\.\DISPLAY2
```

Check the docs for `GetMonitorInfoA` for more information: 

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa
