### ISSUE TITLE
Move `BSTR` (and `NTSTATUS`+`BOOL`) out of `bindgen` `replacements`, into `core`

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#1843]
I've discussed/requested this long ago, as it's typically easier to work with static code (read: `rust-analyzer` parsing it) when it's defined directly in a crate file instead of going through a `TokenStream` despite being static content (not dependent on any variables).

It seems this system is already implemented for the various other types like `P*STR`, and then simply have the new location emitted in `Gen::type_name()`.

Is there any particular reason why this isn't yet done for `BSTR`/`NTSTATUS`/`BOOL`? Both `BOOL` and `BSTR` are required for the core `bindings.rs` yet _also_ end up in `Windows::Win32::Foundation` as duplicate?

**Comment by kennykerr** [comment]
There's a tax for every type that we pull out of metadata and into `core`, as your attempt illustrates. 

Note that `bindings.rs` inside the `windows` crate is just for internal use to implement support for the generated code - `BSTR` is needed for implementing `windows::core::Error`. I would like to eventually replace `bindings.rs` with a dependency on `windows-sys` but that still lacks support for COM. So the fact that `BSTR` appears in `bindings.rs` is just because the internal implementation requires it.

**Comment by MarijnS95** [comment]
The diff is conflated with changes for `link(name = "windows")` so that I can run `tool_*` on Linux. There's no extra tax here, it's only moving around logic that was mostly already there (additional confusing logic on `TypeKind::Struct`).

It may be for internal use only, but it's still duplicated and compiled twice when the user enables `Win32_Foundation` (another way to interpret "tax"). IMHO this is both mental (in `bindgen`) and compiletime (in `windows` duplication) tax.

**Comment by kennykerr** [comment]
The tax I was referring to is mainly when you rip a type out of metadata and add it to the `Type` enum you then have to treat it specially all over the place inside the compiler.

**Comment by MarijnS95** [comment]
Right, that's what I was alluding to in my first paragraph. It's explicit this way rather than having a bunch of loose `Struct && type == BSTR` littered all over the place.

**Comment by rylev** [comment]
I think I might agree with @MarijnS95. @MarijnS95, can you rebase your branch such that the changes to non-generated code are isolated in one commit? This would allow a much more straightforward view of the required changes and allow an easier way to judge the "maintenance burden".

**Comment by MarijnS95** [comment]
@rylev I repushed the branch, the manual changes are now isolated into https://github.com/MarijnS95/windows-rs/commit/83c2e9c1cb4470913582a66bdcade3abc8d92e78.
