### ISSUE TITLE
Feature request: sample showing reads from EventLog through Win32 API

### ISSUE THREAD

**Issue by rwaweber** [microsoft/windows-rs#1850]
### Motivation

Show some examples between win32 C++ Eventlog code and what a rust-based example would look like(if possible).

Looking to see if some of the code [here](https://docs.microsoft.com/en-us/windows/win32/eventlog/querying-for-event-source-messages) could be translated to rust, and shown as a sample.

### Drawbacks

Since its more along the lines of a _sample_ request than a feature, the following is just speculation on possible reasons:
- Not enough time
- Outside the scope of this project
- The resulting sample is too large to include as a sample

### Rationale and alternatives

Having tried to work through some of the initial translation, I became overwhelmed pretty quickly. I have a feeling that someone more seasoned with Win32 _and_ rust would be able to make pretty quick work out of this example.

**Comment by kennykerr** [comment]
I'm not opposed to including a sample, but I don't know if anyone's got time to write such a sample. We also already have Win32-style API samples so there's sufficient examples to follow to figure things out. I generally just want to make sure there's a sample for each kind of API and we've already covered COM, WinRT, Win32, and more.
