### ISSUE TITLE
Bug: IPropertyBag->Read expects an optional IErrorLog as an input instead of 'output'?

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#1855]
### Which crate is this about?

windows

### Crate version

0.38.0

### Summary

When using `Read` on `IPropertyBag` it expects an optional `IErrorLog` as an input.
But from what i gather it's supposed to be an optional output, meaning it will create an `IErrorLog` for you.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\dev\\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc (default)
nightly-i686-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

arm-unknown-linux-gnueabihf
armv7-unknown-linux-gnueabihf
i686-pc-windows-msvc
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)

### Reproducible example

```rust
use std::ptr::null_mut;
use windows::{
    core::{Interface, GUID},
    Win32::{
        Media::DirectShow::{
            ICreateDevEnum, CDEF_DEVMON_CMGR_DEVICE, CDEF_DEVMON_FILTER, CDEF_DEVMON_PNP_DEVICE,
        },
        System::{
            Com::{
                CoCreateInstance, CoInitialize, IEnumMoniker, IMoniker,
                StructuredStorage::IPropertyBag, CLSCTX_INPROC_SERVER, VARIANT,
            },
            Ole::{VariantClear, VariantInit},
        },
    },
};

fn use_prop_bag(moniker: &IMoniker) {
    // I think this can be improved to be handled more implicitly, not sure how to post an issue about it though
    let prop_bag = {
        let mut _prop_bag: std::mem::MaybeUninit<IPropertyBag> = std::mem::MaybeUninit::zeroed();
        unsafe {
            moniker.BindToStorage(
                None,
                None,
                &IPropertyBag::IID,
                _prop_bag.as_mut_ptr() as *mut *mut _,
            )
        }
        .unwrap();
        unsafe { _prop_bag.assume_init() }
    };

    let mut var = VARIANT::default();
    unsafe {
        VariantInit(&mut var);
        // HERE: it expects you to provide an optional ErrorLog
        prop_bag.Read("FriendlyName", &mut var, None).unwrap();

        let _friendly_name = var.Anonymous.Anonymous.Anonymous.bstrVal.to_string();
        println!("{}", _friendly_name);
        VariantClear(&mut var).unwrap();
    };
}

fn main() {
    unsafe { CoInitialize(null_mut()) }.unwrap();
    // true = Video, false = Audio
    let dev_input_cat: GUID = if false {
        ::windows::core::GUID::from_u128(0x860BB310_5D01_11d0_BD3B_00A0C911CE86)
    } else {
        ::windows::core::GUID::from_u128(0x33d9a762_90c8_11d0_bd43_00a0c911ce86)
    };

    let clsid_system_device_enum =
        ::windows::core::GUID::from_u128(0x62BE5D10_60EB_11d0_BD3B_00A0C911CE86);
    // Create the System Device Enumerator.
    let device_enum: ICreateDevEnum =
        unsafe { CoCreateInstance(&clsid_system_device_enum, None, CLSCTX_INPROC_SERVER) }.unwrap();

    let mut enum_moniker: Option<IEnumMoniker> = None;
    // Create an enumerator for the category.
    unsafe {
        device_enum.CreateClassEnumerator(
            &dev_input_cat,
            &mut enum_moniker,
            CDEF_DEVMON_FILTER | CDEF_DEVMON_PNP_DEVICE | CDEF_DEVMON_CMGR_DEVICE,
        )
    }
    .unwrap();

    // Just print the names of the video/audio devices in order to use IPropertyBag
    if let Some(enum_moniker) = enum_moniker {
        if let Some(moniker) = {
            let mut _moniker: Vec<Option<IMoniker>> = vec![None];
            unsafe { enum_moniker.Next(&mut _moniker, null_mut()) }
                .ok()
                .unwrap();
            _moniker.remove(0)
        } {
            use_prop_bag(&moniker);
        }
    }
}
```

### Crate manifest

```toml
[target.'cfg(windows)'.dependencies]
windows = {version = "0.38.0", features = [
  "alloc",
  "Data_Xml_Dom",
  "Win32_System_Com",
  "Win32_Media_DirectShow",
  "Win32_Foundation",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Ole",
]}
```

### Expected behavior

You should be able to receive an optional IErrorLog.

### Actual behavior

You are expected to give an optional IErrorLog

### Additional comments

I might be missing something as usual but giving it a shot.
Sorry for the crappy reproducible example, it's the only one I used it with.

**Comment by tim-weis** [comment]
The actual behavior is correct, according to the [documentation](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-ipropertybag-read):

> `pErrorLog`: The address of the **caller's** error log in which the property bag stores any errors that occur during reads. This can be NULL; in which case, the caller does not receive errors.

It allows clients of the `IPropertyBag` interface to request additional error information, logged to an object implementing the [`IErrorLog`](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nn-oaidl-ierrorlog) interface of their choosing. `IPropertyBag::Read` does not create one for you. (If it did it would be largely useless; the only member of `IErrorLog` is `AddError`.)

**Comment by Zerowalker** [comment]
Oh, thought i made sure i read it correctly, but clearly missed that very obvious part with `caller's`.
Sorry for wasting your time.
