### ISSUE TITLE
how to convert PWSTR to String

### ISSUE THREAD

**Issue by yalishandar** [microsoft/windows-rs#1857]
i'm using `ReadProcessMemory` to get PEB `ProcessParameters`   information.
and i get the return like below
![image](https://user-images.githubusercontent.com/108073828/176225563-42a270ad-6736-4dfc-b571-b7b9deab7638.png)
but when i want convert PWSTR to String it will return garbled  message .

here is my code

```rust
pub unsafe fn convert_pwstr_to_string(pwstr:PWSTR,len:u16){
    let s = std::slice::from_raw_parts(pwstr.0, len as _);
    println!("{}",String::from_utf16_lossy(s));
}
```

```rust
pub unsafe fn get_proc_params(pid:u32){
    use std::mem::MaybeUninit;
    use windows::Win32::Foundation::{BOOL,GetLastError};
    use windows::Win32::System::Diagnostics::Debug::ReadProcessMemory;
    use windows::Win32::System::Threading::{PROCESS_VM_READ,PROCESS_QUERY_INFORMATION,RTL_USER_PROCESS_PARAMETERS,PEB,PROCESSINFOCLASS,NtQueryInformationProcess,OpenProcess,PROCESS_QUERY_LIMITED_INFORMATION,PROCESS_BASIC_INFORMATION};

    let _  = match OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ,BOOL(0),pid) {
        Ok(h) => {
            let   pc = zeroed::<PROCESSINFOCLASS>();
            let mut pbi =MaybeUninit::<PROCESS_BASIC_INFORMATION>::uninit();
            let _ = match  NtQueryInformationProcess(h, pc, pbi.as_mut_ptr() as _, size_of::<PROCESS_BASIC_INFORMATION>() as _, null_mut()){
                Ok(_) => {
                    let pbi = pbi.assume_init();
                    let mut peb = MaybeUninit::<PEB>::uninit();
                    if ReadProcessMemory(h, pbi.PebBaseAddress as _, peb.as_mut_ptr() as _, size_of::<PEB>(), null_mut()).as_bool(){
                        let peb = peb.assume_init();
                        let mut proc_params = MaybeUninit::<RTL_USER_PROCESS_PARAMETERS>::uninit();
                        if ReadProcessMemory(h, peb.ProcessParameters as _, proc_params.as_mut_ptr() as _, size_of::<RTL_USER_PROCESS_PARAMETERS>(), null_mut()).as_bool(){
                            let proc_params = proc_params.assume_init();
                            let lenth = proc_params.CommandLine.MaximumLength;
                            let buffer = proc_params.CommandLine.Buffer;
                            convert_pwstr_to_string(buffer, lenth);

                        }else{
                            println!("cant read process mem 2");
                        }
                    }else{
                        println!("can't read process mem 1");
                    }
                },
                Err(_) => println!("query process information failed"),
            };
        },
        Err(_) => println!("can't open process handle"),
    };
}
```

**Comment by rylev** [comment]
It seems like your passing a pointer to `RTL_USER_PROCESS_PARAMETERS` as the third argument to `ReadProcessMemory` , but according to the docs, `ReadProcessMemory`'s third param is an `LPVOID` and "A pointer to a buffer that receives the contents from the address space of the specified process." Are you sure you're using that API correctly?

**Comment by kgv** [comment]
If "garbled" message it is right message and some random chars at the end, then in my opinion - error in this line:
`let lenth = proc_params.CommandLine.MaximumLength;` -> `let lenth = proc_params.CommandLine.Length;`

**Comment by yalishandar** [comment]
i found the value of `PWSTR` every time are the same one address . but the value of this address pointed are different everytime.
![image](https://user-images.githubusercontent.com/108073828/176345096-d4365b99-8be7-44d8-a673-783b1fdff07e.png)

**Comment by kgv** [comment]
What process memory are you reading to get the PWSTR value? (`pid` or current)
You have to call `ReadProcessMemory` again. In your case `ReadProcessMemory` has to be called 3 times: once to read PEB, once to read RTL_USER_PROCESS_PARAMETERS and once to read UNICODE_STRING's buffer.

**Comment by yalishandar** [comment]
> What process memory are you reading to get the PWSTR value? (`pid` or current) You have to call `ReadProcessMemory` again. In your case `ReadProcessMemory` has to be called 3 times: once to read PEB, once to read RTL_USER_PROCESS_PARAMETERS and once to read UNICODE_STRING's buffer.

dude , you are right ，it works !  thanks a lot !!!

**Comment by yalishandar** [comment]
https://github.com/microsoft/windows-rs/issues/1857#issuecomment-1169512410

this is the right way to solve this problems
