### ISSUE TITLE
Parsing portable pdb/ECMA-335

### ISSUE THREAD

**Issue by loewenheim** [microsoft/windows-rs#1858]
At Sentry we want to be able to parse [portable pdb files](https://github.com/dotnet/runtime/blob/main/docs/design/specs/PortablePdb-Metadata.md) for symbolication purposes. As the spec says, the portable pdb format is an extension of [ECMA-335](https://www.ecma-international.org/publications-and-standards/standards/ecma-335/). We were considering building on top of the [winmd](https://github.com/microsoft/winmd-rs) crate, but it's been archived. Can you give some insight into the state of the art in portable pdb/ECMA-335 parsing? How is it used in this repository?

**Comment by loewenheim** [comment]
Cool, thank you very much. We'll give it a shot and report back :)

**Comment by loewenheim** [comment]
We've created a new `symbolic-ppdb` subcrate of `symbolic`. Parts of it, most notably the table sizing logic, are very directly inspired by `windows-metadata`—having it as a template has been invaluable. `symbolic-ppdb` is actually very limited in terms of information it can extract from portable pdbs for now; our focus was on sequence points, which we need to symbolicate C# functions.

https://github.com/getsentry/symbolic/pull/621

**Comment by kennykerr** [comment]
Sweet - glad you got it working!

**Comment by kennykerr** [comment]
Thanks for the feedback. Happy to take contributions and improvements. The metadata reader continues to be a critical part of the windows-rs project. Its development has been driven purely by the need to parse Win32 and WinRT metadata files, so I have left a lot unimplemented for expediency. I am now focusing on the metadata writer, which is also leading me down the path of improving the quality of the reader to ensure I can perform reliable roundtrip testing.

**Comment by Swatinem** [comment]
Hi @kennykerr,

Just to close the loop here, I had a brief discussion with @rylev at eurorust conference this week, if it would make sense to create a more general purpose crate for ECMA-335 parsing.

Conclusion was basically that it would be a fun project, but likely neither of us would have the resources to support this long term as a proper open source project that extends past our own respective use-cases.
Which would be parsing runtime metadata from PE/COFF files, vs parsing debug data from plain portable pdb files.
