### ISSUE TITLE
Guard `windows::ffi::OsStringExt` usage behind `#[cfg(windows)]` for WSL and Linux support

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#1860]
### Motivation

We'd like to run - _run_, **not cross-compile** - `DirectXShaderCompiler` directly on Linux. At the same time, @riverar found a case to run [`dxcore` inside WSL](https://github.com/microsoft/windows-rs/issues/1842#issuecomment-1164681869), which is also a Linux target.

The `windows` crate doesn't compile _for_ / run _on_ non-Windows targets currently, as `std::os::windows::ffi::OsStrExt` isn't available on `target_os != "windows"`.

A proposed fix guards all trait implementations containing `std::os::windows::ffi::OsStrExt` behind a `#[cfg(windows)]` flag. If needed, followup PRs can introduce Linux-specific implementations for these conversion traits (but read on for a 32-bit wchar caveat).

### Drawbacks

Extra complexity for a "purely Windows-oriented" crate. We can solve that by build-testing _for_ Linux - in addition to cross-compiling _from_ it.

### Rationale and alternatives

Impact: Not supporting `windows-rs` on Linux and WSL while at the same time [deprecating `com-rs`](https://github.com/microsoft/com-rs/pull/238) leaves users with no alternative for [_cross-platform COM bindings_ into libraries like `DirectXShaderCompiler`](https://github.com/Traverse-Research/hassle-rs/blob/main/src/ffi.rs).

### Additional context

Prior art: https://github.com/microsoft/windows-rs/issues/1842#issuecomment-1164681869

### Caveat

Furthermore, non-Windows targets use 32-bit widechars instead of 16-bit:

https://en.cppreference.com/w/cpp/language/types#Character%20types:~:text=wchar_t,a%20distinct%20type.

> 32 bits on systems that support Unicode. A notable exception is Windows, where wchar_t is 16 bits and holds UTF-16 code units

This should be addressed in a separate issue, and seems to be trivially implementable using Rust's `char` type. This is also how https://docs.rs/widestring implements it.

**Comment by riverar** [comment]
Yep, my approach was just to make those helpers unavailable to non-Windows targets. But if we can maintain those APIs and just rewrite the impls to work across platforms, even better. 👍

**Comment by MarijnS95** [comment]
@riverar Yeah I'd start out with just that, don't think I need it for my DXC wrapper anyway.

I would've let you do the honors to make a PR since it was your suggestion, but I had to make them myself to build-test the `windows` crate so I might as well submit what I have :)
