### ISSUE TITLE
NTQuerySystemInformation returns Result<()> instead of NTSTATUS

### ISSUE THREAD

**Issue by ke1satsu** [microsoft/windows-rs#1864]
Hi!

While attempting to use NTQuerySystemInformation I noted that the documentation as well as rust-analyzer states that the return type is a Result<()>.

According to the function signature in https://github.com/microsoft/windows-rs/blob/5ea7a5456c413d7dfbb307f8d38d41df7bc5635b/crates/libs/sys/src/Windows/Win32/System/WindowsProgramming/mod.rs
and Microsofts documentation at https://docs.microsoft.com/en-us/windows/win32/api/winternl/nf-winternl-ntquerysysteminformation it should be a NTSTATUS. Am I misunderstanding something or is this a bug?

**Comment by kennykerr** [comment]
The `windows` crate will by default translate functions that return `HRESULT` / `NTSTATUS` into functions returning `windows::core::Result<()>` to provide a more idiomatic developer experience (e.g. being able to use `NTQuerySystemInformation(...)?`. You can still retrieve the error code from the `Result` if needed.

The `windows-sys` crate doesn't apply a transformation at all and just gives you the raw bindings.

**Comment by ke1satsu** [comment]
Oh I see, I'll keep tinkering then. Thank you for the quick response!
