### ISSUE TITLE
Feature request: generate types for api functions

### ISSUE THREAD

**Issue by kgv** [microsoft/windows-rs#1868]
### Motivation

Generate types for api functions will be useful for dynamic exploration. For example when using `GetModuleHandleW` and `GetProcAddress`. `GetProcAddress` return `FARPROC` which we need to transmute into a function. To do this, we need to know the type of the function.

### Drawbacks

Perhaps there is some way to get [function pointer type](https://doc.rust-lang.org/reference/types/function-pointer.html) from [function pointer](https://rust-lang.github.io/unsafe-code-guidelines/layout/function-pointers.html). But I don't know this.

### Rationale and alternatives

A similar macro solves the problem, but not for the case with static variable. For statics, you must explicitly specify the type.

```rust
pub macro export {
    ($module:expr, $target:ty) => {
        GetProcAddress($module, stringify!($target)).map(|source| transmute::<_, $target>(source))
    },
    ($module:expr, $target:ident) => {
        GetProcAddress($module, stringify!($target)).map(|source| {
            #[allow(unused_assignments)]
            let mut target = &$target;
            target = transmute(source);
            *target
        })
    },
}
```

### Additional context

See [func-types](https://docs.rs/ntapi/0.3.7/ntapi/#features) feature in [ntapi](https://crates.io/crates/ntapi) ([Implementation](https://github.com/MSxDOS/ntapi/blob/8e551443caa56adf56046367bdaf38c525ec6a08/src/macros.rs#L14-L15)).

**Comment by Zerowalker** [comment]
out of interest, what size differences are we talking about, 20%, 100%, 500%?

**Comment by kennykerr** [comment]
Code size, build time, maintainability. All factors to consider. There are a lot of API functions in the `windows` crate. I just have to try it and see how practical it is.

**Comment by kennykerr** [comment]
While this would be convenient for experimenting, I don't think there is enough demand for such a capability to warrant including all the extra generated code needed to make it happen.
