### ISSUE TITLE
implement struct add lifetime 

### ISSUE THREAD

**Issue by gityoog** [microsoft/windows-rs#1885]
```rust
#[implement(DWebBrowserEvents2)]
pub struct BrowserEvent<'a> {
    parent: &'a Browser,
    on_complete: Box<dyn Fn() + 'a>,
}
``` 

i want to add a lifetime for BrowserEvent, but
![QQ截图20220711175510](https://user-images.githubusercontent.com/36879029/178239103-36013293-0195-42c8-9bf1-7ef7f0a95f1e.png)

**Comment by kennykerr** [comment]
That isn't supported and I'm not sure whether we can or should support it for objects with COM lifetime, but @rylev should have a better idea of that.

**Comment by kennykerr** [comment]
Unless someone can offer a compelling reason for this feature, I'm going to close this issue as unsupported. Freel free to chime in with suggestions.

**Comment by gityoog** [comment]
> Unless someone can offer a compelling reason for this feature, I'm going to close this issue as unsupported. Freel free to chime in with suggestions.

I want to do something in `Invoke`, such as triggering callback or using ref of other structs, which all need to declare the life cycle

expamle:
```rust
// when the life cycle is not supported, i can only use SendMessage or raw pointer
pub struct BrowserEvent<'a> {
    browser: &'a Browser
    js_callback:  RefCell<HashMap<String, Box<dyn Fn(*const DISPPARAMS) -> Option<VARIANT> + 'a>>>
}
impl IDispatch_Impl for BrowserEvent {
    // ...
    fn Invoke(
        &self,
        dispidmember: i32,
        _riid: *const windows::core::GUID,
        _lcid: u32,
        _wflags: u16,
        pdispparams: *const DISPPARAMS,
        _pvarresult: *mut VARIANT,
        _pexcepinfo: *mut EXCEPINFO,
        _puargerr: *mut u32,
    ) -> windows::core::Result<()> {
        match dispidmember as u32 {
            DISPID_BEFORENAVIGATE2 => unsafe {
                // (*pdispparams).rgvarg.write(val);
                let url = (*(*(*pdispparams).rgvarg.add(5))
                    .Anonymous
                    .Anonymous
                    .Anonymous
                    .pvarVal)
                    .Anonymous
                    .Anonymous
                    .Anonymous
                    .bstrVal
                    .to_string();
                // need to get allow list from &browser
                if !url.eq("about:blank") {
                    (*(*(*pdispparams).rgvarg).Anonymous.Anonymous)
                        .Anonymous
                        .pboolVal
                        .write(-1);
                    println!("{} [block]", url);
                }
            },
           //...
            _ => {}
        };
        Ok(())
    }
}

```

**Comment by kennykerr** [comment]
Right, I'm wondering whether this can be achieved in some other way. If `Browser` is a COM object, then it should be stored by value. Is static lifetime sufficient? 

I'd love to see a minimal example (not using any particular API) that illustrates how having lifetimes with COM object implementations would be beneficial. That could then shape or influence how this feature might be implemented.

**Comment by gityoog** [comment]
Sorry.I think I should close this issue.
when into `IDispatch` or `IUnknown`, it has been out of the scope of rust lifecycle. I should not use life cycle.
Sorry for the inconvenience

**Comment by rylev** [comment]
Late to this issue, but I agree that it should be closed. COM objects don't have statically determinable lifetimes so the only references they can hold on to must be guaranteed to live longer than them (i.e., have static lifetimes). So, adding a lifetime that is not `'static` does not make sense.
