### ISSUE TITLE
Bug: CreateFileW and Others Incorrectly Check for Multiple Handle Error Values

### ISSUE THREAD

**Issue by mattelkinsTC** [microsoft/windows-rs#1901]
### Which crate is this about?

windows

### Crate version

0.37

### Summary

Several APIs such as CreateFileW, LoadImageW, and others return HANDLE or HANDLE-like values. These are checked against both 0 and -1 (NULL and INVALID_HANDLE_VALUE) to determine success or failure. However, each of these APIs is only documented on MSDN as having a single specific error return value. 

For example, CreateFileW is documented as returning INVALID_HANDLE_VALUE on failure, so NULL should be considered a success case. But the windows crate would report this as a failure, which can result in spurious failures in the system as well as resource leaks (since the HANDLE would never get closed). For other APIs NULL is the correct value to check against, according to the documentation and [this Raymond Chen article](https://devblogs.microsoft.com/oldnewthing/20040302-00/?p=40443).

Would it be possible to go back to just returning the raw HANDLE instead of a Result and letting the higher-level code check it? If not, could the raw value be returned in the Err variant so the higher-level code can work with it?

### Toolchain version/configuration

<n/a>

### Reproducible example

```rust
<n/a>
```

### Crate manifest

```toml
<n/a>
```

### Expected behavior

<n/a>

### Actual behavior

<n/a>

**Comment by kennykerr** [comment]
Do you have an actual issue or are you just concerned that it _might_ be wrong? We've spent a lot of time working on how these types and handles are represented and believe this is a sound representation. Also, this comes straight from the Win32 metadata for the Windows API. The `windows` crate merely honors the behavior described in metadata. If you really want to have no translation, then you can of course use the `windows-sys` crate directly and deal with the API calls and error codes directly.

**Comment by mattelkinsTC** [comment]
I have not reproduced an actual bug from this, no; that would require the API to actually return a specific handle value, which I have no control over. 

I'm not completely sure what is implied by it being pulled from the metadata project; does this mean the metadata project is asserting that for all types of HANDLEs from any API, both INVALID_HANDLE_VALUE and NULL definitely indicate a failure? If that is true, that is good enough for me! Makes life much more convenient, and I'm happy to be wrong. It just isn't what is indicated by MSDN or the Raymond Chen article (which is admittedly dated), and those were all I had to go on.

As a follow-up: does this mean the metadata project should, in general, be considered more reliable than MSDN when they conflict?

**Comment by kennykerr** [comment]
The Win32 metadata and implementation in the `windows` crate are compatible with Raymond's description. For what it's worth, Raymond and I are both on the Windows team together and agree on how such handles behave. The documentation can be confusing and libraries like the `windows` crate do try to take some of the mystery out of using these APIs correctly. That's where the metadata help by providing machine-readable definitions of what would otherwise just be English documentation that can often be misleading or just plain wrong.

**Comment by riverar** [comment]
The upstream win32metadata project asserts the invalid handle values https://github.com/microsoft/win32metadata/blob/main/generation/WinSDK/autoTypes.json#L18-L24. This is a relatively new addition (from yours truly 😙) as of March this year (https://github.com/microsoft/win32metadata/pull/859).

`CreateThread` and `CreateFileW` both return generically-typed HANDLEs and do appear to have different _documented_ invalid handle semantics (0 vs -1). (I believe we dug into the various implementations, which had their own version of the facts.) The metadata-defined invalid handle values aren't perfect, so if you do see inconsistencies like this, don't be shy and file an issue at https://github.com/microsoft/win32metadata.

Assuming a metadata change needs to occur here... considering the two example functions above, we'd probably need to first create metadata types FileHandle and ThreadHandle, each with their own invalid handle values. Then we'd tweak the metadata for CreateThread and CreateFile to return those types. This crate would then consume that new metadata and magic happens 🪄.

I'll move this to the win32metadata repo for further discussion/fix.

**Comment by kennykerr** [comment]
I'll also just point out that the `windows` crate doesn't actually do anything with these invalid values. It just provides the `is_invalid` helper for those handle types that include this metadata. 

So I'll go ahead and close this issue but feel free to open a new issue if you encounter a problem.

**Comment by riverar** [comment]
Was reflecting on this some more with @kennykerr and yep, I remember we covered this topic a million times over, looked at the data, turned the APIs inside out, etc. and landed on two default invalid values (0, -1) to cover all the HANDLE returning APIs without negative effect.

If you come across an API where those values cause problems, please do file a bug on win32metadata. 👍
