### ISSUE TITLE
COM interfere IAxWinHostWindow 

### ISSUE THREAD

**Issue by gityoog** [microsoft/windows-rs#1906]
I want to declare an COM Interface
```rust
pub struct IAxWinHostWindow(IUnknown);

impl IAxWinHostWindow {
    pub unsafe fn SetExternalDispatch<'a, Param0: IntoParam<'a, IUnknown>>(
        &self,
        pdisp: Param0,
    ) -> Result<()> {
        (Interface::vtable(self).SetExternalDispatch)(
            Interface::as_raw(self),
            pdisp.into_param().abi(),
        )
        .ok()
    }
}

unsafe impl Interface for IAxWinHostWindow {
    type Vtable = IAxWinHostWindow_Vtbl;
    const IID: GUID = GUID::from_u128(0xb6ea2050_048a_11d1_82b9_00c04fb9942e);
}

pub struct IAxWinHostWindow_Vtbl {
    pub SetExternalDispatch: unsafe extern "system" fn(
        this: *mut ::core::ffi::c_void,
        pdisp: *mut ::core::ffi::c_void,
    ) -> HRESULT,
}
```

It gave me an error when I called the SetExternalDispatch
```rust
let wnd = host.cast::<IAxWinHostWindow>().unwrap();
wnd.SetExternalDispatch(&disp).unwrap(); // Error { code: 0x80004002, message: ...
}
```
Is it missing any steps

**Comment by kennykerr** [comment]
You need to use the `interface` macro to declare an interface - @rylev we should probably add a simple sample illustrating the `interface` macro. For now, you can look at the following example for how to use the `interface` macro.

https://github.com/microsoft/windows-rs/blob/master/crates/tests/interface/tests/com.rs

**Comment by gityoog** [comment]
> You need to use the `interface` macro to declare an interface - @rylev we should probably add a simple sample illustrating the `interface` macro. For now, you can look at the following example for how to use the `interface` macro.
> 
> https://github.com/microsoft/windows-rs/blob/master/crates/tests/interface/tests/com.rs

Thank you! it's worked
