### ISSUE TITLE
Borrowed types include non-borrowed types

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#1910]
The concept of a borrowed type defined by `type_is_borrowed` includes types like `BSTR` and `HSTRING`. The trouble is that this is used to apply `InParam` which implies convertibility and optionality, which neither of those typically are in the way that `IUnknown` typically is. 

We need to distinguish between types that are passed by reference and neither optional nor convertible and those that are borrowed, optional, and convertible.

**Comment by rylev** [comment]
> InParam which implies convertibility and optionality, which neither of those typically are

I'm not sure I really understand this fully. For convertibility: `HSTRING` allows many conversions from other types. As for optionality, that's a shame as I thought we explicitly discussed that all IN params should be treated as optional.

**Comment by kennykerr** [comment]
I'm busy working through those `signature_param_maybe_xxx` and `signature_param_is_xxx` functions to ensure they model the type system correctly. 

`HSTRING` is not convertible in the same way that say `IUnknown` is convertible. Sure, you can have a `String` and convert it to an `HSTRING` but that's not quite the same thing so I just want to avoid potentially conflating different concepts here.

For option, we can effectively treat in parameters as optional on the ABI (e.g. `zeroed`) but at the projection layer some types like `HSTRING` don't have distinct optional semantics. The `zeroed` representation of an `HSTRING` is an empty string, not a null pointer. So again, this is more about clarifying semantics and modeling types correctly.
