### ISSUE TITLE
memory api is where?ReadProcessMemory

### ISSUE THREAD

**Issue by aadog** [microsoft/windows-rs#1916]
memory api is where?
ReadProcessMemory
WriteProcessMemory

**Comment by Nerixyz** [comment]
From [searching in the documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/?search=ReadProcessMemory):

> ReadProcessMemory

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/fn.ReadProcessMemory.html

> WriteProcessMemory

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/fn.WriteProcessMemory.html

**Comment by aadog** [comment]
This should be a bug, Win32_System_Diagnostics_Debug is not imported correctly

**Comment by aadog** [comment]
![image](https://user-images.githubusercontent.com/18098725/179397976-d7018af0-9f4a-451c-b9f0-6d510ba5a0b9.png)

**Comment by aadog** [comment]
![image](https://user-images.githubusercontent.com/18098725/179397987-a8494236-df1c-47c5-8fc4-d31c43b74712.png)

**Comment by Nerixyz** [comment]
Can you compile the code though? It might be that intellij-rust doesn't see the function.

**Comment by aadog** [comment]
yes，compile ok

**Comment by aadog** [comment]
![image](https://user-images.githubusercontent.com/18098725/179398792-598a77eb-6869-4a7f-b4c3-b2a6a4bd1aba.png)

**Comment by aadog** [comment]
All smart tips for this module are disabled

**Comment by Nerixyz** [comment]
> yes，compile ok

Then you should report this with a minimal reproducible example on intellij-rust/intellij-rust (search for an existing issue first).

Though keep in mind that intellij [has a limit on filesize that it includes when scanning code](https://www.jetbrains.com/help/clion/configuring-file-size-limit.html), if you haven't set this yet.

**Comment by ChrisDenton** [comment]
Yes, it worth keeping in mind that the largest files in windows-rs are around 3 to 8 megabytes.
