### ISSUE TITLE
what is current win2d support status

### ISSUE THREAD

**Issue by milyin** [microsoft/windows-rs#1927]
Could you please clarify how to access win2d library at this moment? The existing win2d sample is obsolete (https://github.com/microsoft/windows-samples-rs/tree/master/win2d) and there is no win2d sample in https://github.com/microsoft/windows-rs/tree/master/crates/samples anymore. I tried https://github.com/microsoft/windows-app-rs, but it seems that win2d is not accessible from it too

**Comment by kennykerr** [comment]
Win2D is not a Windows API, but you should be able to use the `bindgen` crate to generate bindings for it. The `metadata`/`bindgen` crates basically provides a library-based alternative to the old `build` macro used by the old Win2D sample. You can see them in action in the `component_client` test here:

https://github.com/microsoft/windows-rs/blob/master/crates/tests/component_client/build.rs

**Comment by kennykerr** [comment]
I haven't looked at Win2D in a while, but I'll take a look to see whether it is a practical alternative for Rust developers.

**Comment by milyin** [comment]
@kennykerr thank you for answer! 
I use Win2D for drawing text in my 2048 game - https://github.com/milyin/game2048-rs. Now I'm working on async GUI library based on composition UI - https://github.com/milyin/wag and planning to rewrite this 2048 game with this library. The main thing I need Win2D for is to to write text on GUI elements

**Comment by kennykerr** [comment]
Neat! Have you considered using DirectWrite? That's what basically all the higher-level UI frameworks use for text and you avoid the big Win2D redistributable.

**Comment by milyin** [comment]
> Neat! Have you considered using DirectWrite? That's what basically all the higher-level UI frameworks use for text and you avoid the big Win2D redistributable.

Thank you, I considered it. but I thought it's not available in rust. Maybe I was mistaken, will look at it again. Is it accessible from windows-rs or from windows-app-rs?

**Comment by kennykerr** [comment]
DirectWrite is part of the OS and as such is available directly via the `windows` crate. You can find it under the `Win32_Graphics_DirectWrite` feature.
