### ISSUE TITLE
Bug: Unresolved import for IClassFactory_Impl

### ISSUE THREAD

**Issue by leonardder** [microsoft/windows-rs#1944]
### Which crate is this about?

Windows

### Crate version

0.39.0

### Summary

I'm trying to implement IClassFactory, but I can't seem to import IClassFactory_Impl

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc                                                                                    
rustup home:  C:\Users\<user>\.rustup                                                                         
                                                                                                                        
stable-x86_64-pc-windows-msvc (default)                                                                                 
rustc 1.62.1 (e092d0b6b 2022-07-16)                                                                                     

### Reproducible example

```rust
use windows::{
    core::implement,
    Win32::System::Com::{IClassFactory, IClassFactory_Impl},
};

#[implement(IClassFactory)]
struct ClassFactory();

impl IClassFactory_Impl for ClassFactory {}
```

### Crate manifest

```toml
...
[dependencies.windows]
version = "0.39.0"
features = [
    "implement",
    "Win32_System_RemoteDesktop",
    "Win32_System_Com",
]
```

### Expected behavior

Working import of IClassFactory_Impl

### Actual behavior

error[E0432]: unresolved import `windows::Win32::System::Com::IClassFactory_Impl`                                       
 --> src\class_factory.rs:3:41                                                                                          
  |                                                                                                                     
3 |     Win32::System::Com::{IClassFactory, IClassFactory_Impl},                                                        
  |                                         ^^^^^^^^^^^^^^^^^^                                                          
  |                                         |                                                                           
  |                                         no `IClassFactory_Impl` in `Windows::Win32::System::Com`                    
  |                                         help: a similar name exists in the module: `IClassFactory_Vtbl`

**Comment by riverar** [comment]
Hi @leonardder. Those methods are tied to feature `Win32_Foundation` (https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Com/struct.IClassFactory.html#implementations). Adding that should get you back on your feet.

**Comment by leonardder** [comment]
Thanks a lot for pointing this out. I'm slightly struggling with the docs as it turns out. This works for me.
