### ISSUE TITLE
Feature request: Error from Lsa functions should be converted with LsaNtStatusToWinError beforehand

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#1945]
### Motivation

When receiving a Result the error should provide useful information that's expected to be obtained if said function fails.

### Drawbacks

An extra step behind the scenes, but that's already done for any error as far as I know cause that's just how it works.

### Rationale and alternatives

It would fit how `Err` is currently used in functions.
You call a function that returns a `Result`, if it fails it will display the error message, like say `Access Denied`.
If it were just to give you error code, it makes sense if that's always the case for consistency (unless there's no error message to be retrieved, if that's a thing).

### Additional context

Currently one has to do something like this as far as I can tell:

```rust
        LsaRegisterLogonProcess(&string, &mut lsa_handle, &mut _sec_mode).or_else(|f| {
            let nt_status = LsaNtStatusToWinError(NTSTATUS(f.code().0));
            WIN32_ERROR(nt_status).ok()
        }).unwrap();
```

**Comment by Zerowalker** [comment]
hmm looking at these functions i notice that some expects `HANDLE` others `LsaHandle`?
Also this particular function `LsaRegisterLogonProcess` seems to not specify any type at all, but it internally expects LsaHandle?
It's generated as this:

```rust
pub unsafe fn LsaRegisterLogonProcess(logonprocessname: *const super::super::super::System::Kernel::STRING, lsahandle: *mut , securitymode: *mut u32) -> ::windows::core::Result<()> {
    #[cfg_attr(windows, link(name = "windows"))]LsaHandle
    extern "system" {
        fn LsaRegisterLogonProcess(logonprocessname: *const super::super::super::System::Kernel::STRING, lsahandle: *mut LsaHandle, securitymode: *mut u32) -> super::super::super::Foundation::NTSTATUS;
    }
    LsaRegisterLogonProcess(::core::mem::transmute(logonprocessname), ::core::mem::transmute(lsahandle), ::core::mem::transmute(securitymode)).ok()
}
```
while `` is generated like this:

```rust
pub unsafe fn LsaDeregisterLogonProcess<'a, P0>(lsahandle: P0) -> ::windows::core::Result<()>
where
    P0: ::std::convert::Into<LsaHandle>,
{
    #[cfg_attr(windows, link(name = "windows"))]
    extern "system" {
        fn LsaDeregisterLogonProcess(lsahandle: LsaHandle) -> super::super::super::Foundation::NTSTATUS;
    }
    LsaDeregisterLogonProcess(lsahandle.into()).ok()
}
```
```toml
name = "windows"
version = "0.39.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "f1c4bd0a50ac6020f65184721f758dba47bb9fbc2133df715ec74a237b26794a"
dependencies = [
 "windows_aarch64_msvc",
 "windows_i686_gnu",
 "windows_i686_msvc",
 "windows_x86_64_gnu",
 "windows_x86_64_msvc",
]
```

The first one looks like something is wrong, as this line looks odd:
`#[cfg_attr(windows, link(name = "windows"))]LsaHandle`

**Comment by riverar** [comment]
Can you create a new issue with the second part? Doesn't look related to the feature request. Then I can transfer it over to the right spot.

**Comment by Zerowalker** [comment]
@riverar will do

**Comment by kennykerr** [comment]
The `windows` crate already transforms the `LsaRegisterLogonProcess` function such that it returns a `Result<()>` for convenience while the `windows-sys` crate intentionally returns the underlying error code without any transformation. 

This is by design. If you'd prefer to convert the error code into a `WIN32_ERROR` value then you can always do so yourself.
