### ISSUE TITLE
Can't keep a reference to a COM object when passed to a method on an implemented object and no lifetime is specified

### ISSUE THREAD

**Issue by leonardder** [microsoft/windows-rs#1951]
I'm trying to implement the [Dynamic Virtual Channel APIs](https://docs.microsoft.com/nl-nl/windows/win32/termserv/dvc-client-apis). When calling [IWTSPlugin::Initialize](https://docs.microsoft.com/en-us/windows/win32/api/tsvirtualchannels/nf-tsvirtualchannels-iwtsplugin-initialize), a reference to [IWTSVirtualChannelManager](https://docs.microsoft.com/en-us/windows/desktop/api/TsVirtualChannels/nn-tsvirtualchannels-iwtsvirtualchannelmanager) is passed which I want to save on the plugin instance. However, I'm really stuck with that. 

Here is a small skeleton code snippet:

```rust
#[implement(IWTSPlugin)]
pub struct RdPipePlugin();

impl RdPipePlugin {
    pub fn new() -> RdPipePlugin {
        RdPipePlugin()
    }
}

impl IWTSPlugin_Impl for RdPipePlugin {
    fn Initialize(&self, pchannelmgr: &Option<IWTSVirtualChannelManager>) -> Result<()> {
        if pchannelmgr.is_none() {
            return Err(Error::from(E_UNEXPECTED));
        }
        Ok(())
    }
}
```

Now in initialize, I want to save the channel manager.

I can get a reference to IWTSVirtualChannelManager, but its lifetime is anonymous. So, this doesn't work:
`let manager: &'static IWTSVirtualChannelManager = pchannelmgr.as_ref().unwrap();`
Neither can I store the VirtualChannelManager in a RWLock on the RdPipePlugin struct this way. I also read that a named lifetime like `'a` isn't going to work for COM.
How should I proceed?

**Comment by leonardder** [comment]
Update. It turns out that I can clone the com object in which case I can store it by value. However, I assume that increases the reference count on the COM object. I guess the intention of these methods (i.e. Initialize providing an instance of IWTSVirtualChannelManager) is that they can safely store the provided instance, either by value or by reference with a static lifetime. Shouldn't it be allowed to de-reference them safely?

**Comment by rylev** [comment]
Anonymous lifetimes in Rust are the same as regular lifetimes - they're just not explicitly stated. That means:

```rust
// The following are equivalent
fn Initialize(&self, pchannelmgr: &Option<IWTSVirtualChannelManager>) -> Result<()>;
fn Initialize<'a>(&'a self, pchannelmgr: &'a Option<IWTSVirtualChannelManager>) -> Result<()>;
```

So, `pchannelmgr` is only guaranteed to live as long as the *borrow* of self. Story the reference to `pchannelmgr` past that point would risk that reference becoming invalid which Rust does not allow. 

You correctly point out that the right thing to do is clone the COM object so you have a new handle on it which can live as long as you want.

**Comment by leonardder** [comment]
Thanks for pointing this out. I will stick with cloning.
