### ISSUE TITLE
Bug: UB in `as_wide` of `core::strings::*`

### ISSUE THREAD

**Issue by seritools** [microsoft/windows-rs#1963]
### Which crate is this about?

windows

### Crate version

0.39.0

### Summary

Quoting the [documentation of `slice::from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html#safety):

> data must be non-null and aligned even for zero-length slices. One reason for this is that enum layout optimizations may rely on references (including slices of any length) being aligned and non-null to distinguish them from other data. You can obtain a pointer that is usable as data for zero-length slices using [NonNull::dangling()](https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.dangling).

`core::strings::{HSTRING, PSTR, PWSTR, PCSTR, PCWSTR}::as_wide` all do not account for this, and at least [`HSTRING`s one](https://github.com/microsoft/windows-rs/blob/c55af265f2e3c75e973946230fe6e60a20961ed9/crates/libs/windows/src/core/strings/hstring.rs#L32) is not marked as unsafe, and provides a [safe `Display` implementation](https://github.com/microsoft/windows-rs/blob/c55af265f2e3c75e973946230fe6e60a20961ed9/crates/libs/windows/src/core/strings/hstring.rs#L135) using this.

### Reproducible example

```rust
use windows::core::HSTRING;

fn main() {
    let s = HSTRING::new();
    println!("{s}");
}
```

### Additional comments

It seems that all these string wrappers could maybe benefit from using `Option<NonNull<T>>` instead of a raw pointer. (Still `#[repr(transparent)]`-compatible)

**Comment by ChrisDenton** [comment]
Hm, I think it's the new implementation that is wrong here? In other cases HSTRINGs should always be valid so there's no need for the null case. Rather than use a null pointer in new, why not point to a static HSTRING header?

But I do agree that either way, using `NonNull` instead of a raw pointer would help guard against mistakes.

**Comment by rylev** [comment]
Thanks for the report! So, I don't believe this is an actual issue in practice and instead we're just missing some documentation.

For all non-`HSTRING` types accessing the underlying pointer can only happen through `unsafe`. We don't document the requirements here very well, but we certainly expect the user to ensure that the pointer is properly aligned. 

For `HSTRING`, the inner pointer is only set in three places: [as a null pointer](https://github.com/microsoft/windows-rs/blob/c55af265f2e3c75e973946230fe6e60a20961ed9/crates/libs/windows/src/core/strings/hstring.rs#L13) - which we never pass to `from_raw_parts`, in [`from_wide_iter`](https://github.com/microsoft/windows-rs/blob/c55af265f2e3c75e973946230fe6e60a20961ed9/crates/libs/windows/src/core/strings/hstring.rs#L83), and in [`Clone::clone`](https://github.com/microsoft/windows-rs/blob/c55af265f2e3c75e973946230fe6e60a20961ed9/crates/libs/windows/src/core/strings/hstring.rs#L111).

Those last two transitively require that `Header::alloc` returns an aligned pointer. This function ultimately calls into [`HeapAlloc`](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heapalloc#remarks) which will be either aligned on 16-bit or 8-bit offsets. The alignment of `Header` is 8 which means any pointer to `Header` aligned to addresses at 16 or 8 bit offsets will be aligned. 

I believe this means that there is non-UB here. However, this should be much more closely documented and perhaps even some `debug_asserts!` can be added to make sure this stays true in the future. 

Let me know if my thinking here seems correct!

**Comment by seritools** [comment]
Oh I'm sorry, while trying out a few things around this I missed one additional function call, so seems to be safe!

The call to `HSTRING::as_ptr()` within `as_wide` doesn't just do `self.0` of course, but checks everything internally and returns a pointer to a const zero [u16; 1]
```rs
const EMPTY: [u16; 1] = [0];
EMPTY.as_ptr()
```

so the resulting slice is valid!

Sorry for the noise and thank you for the quick responses ❤️
