### ISSUE TITLE
Test (cross-compilation) actions fail on this repository

### ISSUE THREAD

**Issue by glandium** [microsoft/windows-rs#1969]
The error message is:
> actions/cache@v3 is not allowed to be used in microsoft/windows-rs. Actions in this workflow must be: within a repository that belongs to your Enterprise account or matching the following: actions/checkout@v2.

**Comment by riverar** [comment]
Where are you seeing this? Can you link to the particular test run? I don't see any failures in recent commits.

**Comment by glandium** [comment]
https://github.com/microsoft/windows-rs/actions

**Comment by riverar** [comment]
I walked right into that one, thanks.

**Comment by kennykerr** [comment]
Need to figure out why its not failing the CI validation for PRs - and then we should be able to add the necessary action.

**Comment by kennykerr** [comment]
I allowed that cache action but it still seems to fail:

https://github.com/microsoft/windows-rs/actions/runs/2873464088

Might need to revert https://github.com/microsoft/windows-rs/pull/1883 until we can figure this out.

**Comment by mati865** [comment]
Oh, that's unfortunate but probably there is no other choice.
It'd be nice if https://github.com/microsoft/windows-rs/pull/1961 could be reconsidered instead before next release.

**Comment by riverar** [comment]
Last build seemed to pass https://github.com/microsoft/windows-rs/actions/runs/2905093873, looks okay now.

**Comment by kennykerr** [comment]
The build passed but it still skipped the cross compilation workflow.

**Comment by kennykerr** [comment]
OK, I was looking at an older build that should also have succeeded but at least the latest build seems green. 👍

**Comment by kennykerr** [comment]
So, I'll close this now - the fix was to enable the cache action (which I did) and the CI build finally seems to have caught up to that fact. 😜
