### ISSUE TITLE
Bug: There are two libraries with a GetDeviceID symbol

### ISSUE THREAD

**Issue by glandium** [microsoft/windows-rs#1970]
### Which crate is this about?

windows-sys

### Crate version

master

### Summary

Both `Win32::Media::Audio::DirectSound` and `Win32::System::TpmBaseServices` contain a `GetDeviceID` function. Because all symbols are linked via a single import library (windows.lib/libwindows.a), the linker is unable to pick one of them depending which one appears first in the import library. In practice, this means currently, the `GetDeviceID` from `dsound.dll` is used for both.

**Comment by glandium** [comment]
To clarify, in the best situation, it would be possible to link against each of them, but not both. Currently, it's only possible to link against the dsound.dll one.

**Comment by riverar** [comment]
Hm, good catch. Looks like a TPM Base Services header/lib bug (in not having a tbsi_ prefix). I believe @kennykerr is also exploring breaking up windows.lib to address similar issues.

**Comment by kennykerr** [comment]
Yes, I've known about this function. To my knowledge its the only function with a name collision. 

We could address it with distinct libs - that's the solution I was shooting for if the `raw-dylib` feature was not going to land any time soon, but that's a lot of extra work that would be thrown away when `raw-dylib` is available. @dpaoliello

**Comment by kennykerr** [comment]
Closing for now - if `raw-dylib` doesn't land in the next few months we can revisit.
