### ISSUE TITLE
Bug: tool_msvc produces a broken i686_msvc import library

### ISSUE THREAD

**Issue by glandium** [microsoft/windows-rs#1972]
### Which crate is this about?

other (please share in the comments)

### Crate version

master

### Summary

Do the following:
- Follow the instructions from crates/tools/msvc/readme.md (only for x86, that's the only one that is outdated)
- `cargo test -p test_win32`

It fails to link because the @num suffixes in the refreshed library are wrong. example: GetErrorInfo@8 becomes GetErrorInfo@32.

Incidentally, the version of windows.lib in the repository is also wrong for a smaller number of symbols, like _EapHostPeerInvokeIdentityUI@60 instead of _EapHostPeerInvokeIdentityUI@64.

**Comment by glandium** [comment]
> Incidentally, the version of windows.lib in the repository is also wrong for a smaller number of symbols, like _EapHostPeerInvokeIdentityUI@60 instead of _EapHostPeerInvokeIdentityUI@64.

The i686_gnu has differently broken entries. For the example above, it has _EapHostPeerInvokeIdentityUI@61.

**Comment by kennykerr** [comment]
This is troubling and even more motivation to get `raw-dylib` up and running - checking in the libs is very problematic as they're not reproducible and verifiable by the CI build. @dpaoliello

**Comment by kennykerr** [comment]
Thanks for reporting! Here's the fix while we wait for `raw-dylib`. 😉 

#1979
