### ISSUE TITLE
Feature request: Improve `Debug` output for FFI-ed enums

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#1981]
### Motivation

When wrapping a C enum(-like) construct in Rust, the correct way to do it is to declare a transparent struct with the correct type inside like this (the `u32` can be replaced by the appropriate unsigned integer):

```rust
#[repr(transparent)]
#[derive(Copy, Clone, PartialEq, Eq, Hash)] // PartialOrd, Ord too if relevant for the enum
pub struct c_enum_t(pub u32);

impl c_enum_t {
    pub const VARIANT_A: Self = Self(0);
    pub const VARIANT_B: Self = Self(1);
}
```

Notice I didn't implement `Debug` here. That's because the default implementation would print something like `c_enum_t(0)`. I would like to have something like `c_enum_t::VARIANT_A(0)`.

This can be done by matching on the constants in the `Debug` impl, usually generated via a macro (like I proposed in #1956)

```rust
impl std::fmt::Debug for c_enum_t {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // With one allocation for the name, probably more efficient in term of literals in windows-rs
        let variant = match self {
            Self::VARIANT_A => "::VARIANT_A",
            Self::VARIANT_B => "::VARIANT_B",
            other => "",
        };
        f.debug_tuple(&format!("c_enum_t{}", variant)).field(&self.0).finish()

        // Without allocations for the name, probably less efficient in term of literals in windows-rs

        // let variant = match self {
        //     Self::VARIANT_A => "c_enum_t::VARIANT_A",
        //     Self::VARIANT_B => "c_enum_t::VARIANT_B",
        //     other => "c_enum_t",
        // };
        // f.debug_tuple(variant).field(&self.0).finish()

        // Without allocations for the name, but without octal/hexa reprs

        // f.write_str("c_enum_t")?;
        // match self {
        //     Self::VARIANT_A => f.write_str("::VARIANT_A(0)"),
        //     Self::VARIANT_B => f.write_str("::VARIANT_B(0)"),
        //     other => f.write_fmt(format_args!("({})", self.0)),
        // }
    }
}
```

This produces a nice `Debug` output and can be easily be adapted to account for hexadecimal and octal representations (in the first two forms, the third cannot be as efficient except for computing the values during generation), which is a useful bonus.

### Drawbacks

One drawback is that it adds a lot of string literals to the library. That's entirely true but most of them, especially in a crate like `windows-rs` will be ignored: most enums are never `Debug` printed outside of development (the very common ones are errors, like `WIN32_ERROR` and `HRESULT`) and final binaries are often stripped, reducing the final load even more.

Still, that make `windows-rs` as library bigger. I do not have figures because I don't know how to regenerate the crates from a macOS machine. I someone does, please try out #1956 to report it.

### Another Debug repr

I don't have any in mind but there may be.

### Not doing this change

Possible but not ergnomic at all IMO. `windows-sys` is there for the barebone use case, and cannot use this solution since it does like the `libc` crate: `pub type c_enum_t = u32;`. So users of the `windows-sys` crate, which are notably `tokio` and `parking-lot`, are not negatively affected.

### 

### Additional context

- I have seen it in other open source projects, e.g. https://github.com/sunriseos/SunriseOS/blob/c42cf3f2efe2c3e96510200c78b5c12e2acea006/libutils/src/lib.rs#L90.
- [`num_enum`](https://crates.io/crates/num_enum) declares a regular enum so the `Debug` impl is already useful
- [`enum-primitive-derive`](https://crates.io/crates/enum-primitive-derive) does the same
- [`tartan_c_enum`](https://docs.rs/tartan-c-enum/1.0.0/src/tartan_c_enum/lib.rs.html#97-232) use a solution similar to what I proposed but with more macro calls which I think can be eliminated

**Comment by kennykerr** [comment]
> I do not have figures because I don't know how to regenerate the crates from a macOS machine.

It should work. Just run `cargo run -p tool_windows` from the root of the workspace.

**Comment by poliorcetics** [comment]
Ok I have numbers ! 

With the following `Debug` impl:

```rust
impl std::fmt::Debug for c_enum_t {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let variant = match *self {
            Self::VARIANT_A => "c_enum_t::VARIANT_A",
            Self::VARIANT_B => "c_enum_t::VARIANT_B",
            other => "c_enum_t",
        };
        f.debug_tuple(variant).field(&self.0).finish()
}
```

In our work binary, which is 28M unstripped, with the following features for `windows`:

```toml
features = [
    "ApplicationModel",
    "Foundation_Collections",
    "Management_Deployment",
    "Storage",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Networking_ActiveDirectory",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_NetworkManagement_NetManagement",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Security_Credentials",
    "Win32_Storage_FileSystem",
    "Win32_Storage_InstallableFileSystems",
    "Win32_System_ApplicationInstallationAndServicing",
    "Win32_System_Com",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_Ole",
    "Win32_System_Memory",
    "Win32_System_Power",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_RemoteDesktop",
    "Win32_System_Rpc",
    "Win32_System_SecurityCenter",
    "Win32_System_Services",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_TaskScheduler",
    "Win32_System_Threading",
    "Win32_System_Time",
    "Win32_System_WindowsProgramming",
    "Win32_System_WinRT",
    "Win32_System_Wmi",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]
```

We go from (in `release` mode, for Windows 64 bit)

- Short `Debug` impl: 28 602 880 bytes
- Verbose `Debug` impl: 28 862 464 bytes

Difference: **259 584 bytes**, or **~ 2.5kiB**. That's more than acceptable to us, and we use `Debug`-printing in lots of logs to have the value when something goes wrong so the strings are preserved. I expect stripping and less `Debug`-printing would reduce this a lot.

## Idea

There could be a `verbose-enum-debug` feature in `windows` that would activate those `Debug` implementations and the default would still be the short one. This feature would be documented as "Only activate it in binaries, libraries should not force users to pay for features of `windows` they won't use in their binary".

**Comment by kennykerr** [comment]
Can you share the following for the `windows` crate:

* Impact on compile time using all features
* Impact on lines of code
* Impact on package size

**Comment by kennykerr** [comment]
Yeah, that's still tends of thousands of extra lines of code. I'm just anxious to drop the line count rather than push it up at this stage. There's still much to do to shrink the `windows` crate and this just doesn't seem worth the extra cost. 

You might consider using the `windows-bindgen` crate to generate a debug-specific side crate that you can use as a debugging aid to provide richer debugging text. Folks can then opt into using that.

**Comment by poliorcetics** [comment]
> You might consider using the windows-bindgen crate to generate a debug-specific side crate that you can use as a debugging aid to provide richer debugging text. Folks can then opt into using that.

As in, generating a crate with some trait `VerboseDebug` implemented for all those ? Or with a free function for each type ?

**Comment by kennykerr** [comment]
Yes, there are a few ways you could solve it but a unique trait that you can generate implementations for seems like a good candidate. You'll have to experiment to see what works best.
