### ISSUE TITLE
Feature request: Provide replacements/ergonomics for `BOOLEAN`

### ISSUE THREAD

**Issue by seritools** [microsoft/windows-rs#1990]
### Motivation

For `BOOL` the `windows` crate already provides super useful helpers like conversion to Rust's `bool` and conversion into a `Result` with the last Win32 error populated (see [`bool32.rs`](https://github.com/microsoft/windows-rs/blob/044ab37c78a4be0edd3ce7d832ebc15d9ee221cd/crates/libs/bindgen/src/replacements/bool32.rs)).

It would be nice to have the same for the 8-bit `BOOLEAN` type that is also used with many APIs. The implementation should be pretty much the same.

### Drawbacks

I don't think there are any?

**Comment by kennykerr** [comment]
Yep, sounds reasonable - I'd like to add this - just need to move things around a little but should be able to get this plumbed in soon.

**Comment by tim-weis** [comment]
There's also [`VARIANT_BOOL`](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-oaut/7b39eb24-9d39-498a-bcd8-75c38e5823d0), so might want to address that, too.

**Comment by kennykerr** [comment]
You may want to open a new issue for `VARIANT_BOOL` on the Win32 metadata repo if you think that type is significant as I don't see any mention of it in the metadata. It seems to just decay to `short`.
