### ISSUE TITLE
Use `HSTRING`s for static strings where appropriate

### ISSUE THREAD

**Issue by ChrisDenton** [microsoft/windows-rs#2002]
### Motivation

For example, take the `MS_PLATFORM_CRYPTO_PROVIDER`, which is defined as:

```rust
pub const MS_PLATFORM_CRYPTO_PROVIDER: &str = "Microsoft Platform Crypto Provider";
```

This is used in the `NCryptOpenStorageProvider` function, which has the definition:

```rust
pub unsafe fn NCryptOpenStorageProvider<'a, P0>(
    phprovider: *mut NCRYPT_PROV_HANDLE,
    pszprovidername: P0,
    dwflags: u32
) -> Result<()> where
    P0: Into<PCWSTR>, 
```

As you can see the constant is a `&str` but the function takes an `Into<PCWSTR>`. This necessitates manually performing the conversion.

Ideally the constant would use the equivalent of the `w!` macro to get a `HSTRING`.

### Drawbacks

This may not be easy to implement. It may not be obvious how/where a constant is used. In some cases there may also be conflicting requirements (e.g. using `A` vs. `W` APIs).

### Rationale and alternatives

Doing this would improve the ergonomics of using some string constants and not require the user to perform a conversion to a wide string.

The main alternative is the status quo, e.g. manually using `HSTRING::from(...)` to perform the conversion.

### Additional context

* How to handle conflicting string requirements (if any)? E,g, maybe choosing a default type.
* Is this technically possible atm?

**Comment by kennykerr** [comment]
Hey Chris, I created this issue to deal with this problem: https://github.com/microsoft/win32metadata/issues/1008

I believe if we can have the metadata capture the original encoding, then we can subsequently declare the constants in Rust accordingly so that these APIs would "just work".

**Comment by ChrisDenton** [comment]
Oh, that's great! I'll close this then as it isn't needed.
