### ISSUE TITLE
unresolved import

### ISSUE THREAD

**Issue by LukasKarer** [microsoft/windows-rs#2005]
I am trying to import the Module [`windows::Security::Credentials`](https://microsoft.github.io/windows-docs-rs/doc/windows/Security/Credentials/index.html) with the following statement into my Tauri application:
```
use windows::{
    Win32::Security::Credentials::*,
};
```

The following code is my full main.rs file: 

```
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

use windows::{
    Win32::Security::Credentials::*,
};

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[tauri::command]
fn checkWindowsHello() -> String {
    let result = KeyCredentialManager::IsSupportedAsync();
    if (result) {
        let authenticationResult = KeyCredentialManager::RequestCreateAsync("login", KeyCredentialCreationOption::ReplaceExisting);
        if (authenticationResult.Status == KeyCredentialStatus::Success) {
            format!("User is logged in");
        } else {
            format!("Login error: {}", authenticationResult.Status);
        }
    }
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

My error:
```
--> src\main.rs:7:22
  |
7 |     Win32::Security::Credentials::*,
  |                      ^^^^^^^^^^^ could not find "Credentials" in "Security"`
```

I am new to rust, can anyone help me on my issue?

**Comment by riverar** [comment]
Hi @LukasKarer, can you post your `Cargo.toml`? Sounds like you forgot to add the `Security_Credentials` feature as listed in the docs.

**Comment by LukasKarer** [comment]
This is my `Cargo.toml`: `[package]
name = "pdfViewer"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0", features = ["api-all"] }

[dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Security"
]

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
`

Do I need to add `Security_Credentials` to the features list of `dependencies.windows`?

**Comment by riverar** [comment]
Three backticks (```) are needed for code blocks. And yep, you can cut/paste what's needed in the docs you linked.

![image](https://user-images.githubusercontent.com/475132/188344576-e73d3052-6b96-4954-b5d5-94bab9dfdf08.png)

**Comment by LukasKarer** [comment]
Thank you for your quick help. It is working now.
Also thanks for giving the tip with the Three backticks (```).
