### ISSUE TITLE
Consider consolidating the msvc and gnullvm target import libs

### ISSUE THREAD

**Issue by glandium** [microsoft/windows-rs#2018]
> It looks like the gnullvm targets are still there. Should they be removed now?

_Originally posted by @kennykerr in https://github.com/microsoft/windows-rs/issues/2016#issuecomment-1244668853_

There are two ways to go about this:
- Make the gnullvm targets use the msvc target crates (as in #1961)
- Make the msvc targets use the gnullvm target crates (which in essence would amount to the same thing as having rust auto-generate the import libraries via raw-dylib)

An advantage of the latter is that it allows the generation of all the import libraries through a single command (vs. at least 4 right now, 3 of which are with 3 different Visual Studio environments).

The difference between the gnullvm and msvc import libraries are outlined in https://github.com/microsoft/windows-rs/issues/1964#issuecomment-1227046538.

**Comment by mati865** [comment]
You mean per arch?

Technically yes if we use legacy import lib format (like the one used by gnu).
To use short import libraries (like LLVM and MSVC does) we'd need to workaround issue recently fixed on Binutils master: https://github.com/bminor/binutils-gdb/commit/46bbc1c071ca5ceb1d6cfcd38e65eef28f27283c
But using common library for LLVM and MSVC and second one for GNU is achievable.

**Comment by kennykerr** [comment]
Interesting. As `raw-dylib` is nearing stabilization, I don't see a compelling reason to push this much further but we probably need to be able to support a few more releases with explicit libs. We haven't published a release in a few months, so I'd like to settle on something pretty quickly. It looks like we've resolved all the linker issues for APIs, but the repo is not in a happy state as the gnullvm targets are still present but the tool to generate them was removed in #2016. 

In the short term we could just remove the orphaned gnullvm targets, publish a release, and then consolidate them somehow.

**Comment by glandium** [comment]
> So we could support gnu/gnullvm/msvc all with a single lib per target?

Technically, that's possible, but I was more thinking about two libs per cpu-type: gnu/msvc or gnu/gnullvm.

> As `raw-dylib` is nearing stabilization

`raw-dylib` may be near stabilization, but it's not desirable to use it as soon as it is stable, as that would mean a forced MSRV that many prospective users of the crate would not appreciate.

**Comment by glandium** [comment]
> You mean per arch?
> 
> Technically yes if we use legacy import lib format (like the one used by gnu). To use short import libraries (like LLVM and MSVC does) we'd need to workaround issue recently fixed on Binutils master: [bminor/binutils-gdb@46bbc1c](https://github.com/bminor/binutils-gdb/commit/46bbc1c071ca5ceb1d6cfcd38e65eef28f27283c) But using common library for LLVM and MSVC and second one for GNU is achievable.

Does this imply binutils actually supports short import libs, provided the archive members are named a different way?

**Comment by mati865** [comment]
> Does this imply binutils actually supports short import libs, provided the archive members are named a different way?

Binutils have sort of supported short import libs for quite some time, it just had multiple bugs. So this would require some testing with oldest Binutils version that `windows-rs` wants to support but it might be possible to make it work that way. Not sure if it's work the hassle though.

**Comment by riverar** [comment]
> To use short import libraries (like LLVM and MSVC does) we'd need to workaround issue recently fixed on Binutils master: [bminor/binutils-gdb@46bbc1c](https://github.com/bminor/binutils-gdb/commit/46bbc1c071ca5ceb1d6cfcd38e65eef28f27283c)

This code incorrectly assumes libs always point to ".dlls" when they can also point to .cpl, .ax, etc. We may want to reach out and get this fixed.

**Comment by kennykerr** [comment]
> raw-dylib may be near stabilization, but it's not desirable to use it as soon as it is stable, as that would mean a forced MSRV that many prospective users of the crate would not appreciate.

For `windows-sys` that is unfortunately the reality as it is geared toward systems libraries. For `windows` we generally push the language as fast as practical as adoption is generally more focused on applications rather than libraries and already requires pretty recent features necessitating a MSRV of 1.61 at present. 

But yes, I would expect we have to keep supporting libs for some time to come if only for `windows-sys`.

**Comment by mati865** [comment]
> > To use short import libraries (like LLVM and MSVC does) we'd need to workaround issue recently fixed on Binutils master: [bminor/binutils-gdb@46bbc1c](https://github.com/bminor/binutils-gdb/commit/46bbc1c071ca5ceb1d6cfcd38e65eef28f27283c)
> 
> This code incorrectly assumes libs always point to ".dlls" when they can also point to .cpl, .ax, etc. We may want to reach out and get this fixed.

I don't have contacts within Binutils so feel free to reach out to them.

**Comment by kennykerr** [comment]
Sounds like the tooling's not quite there yet. Can we close this issue?

**Comment by mati865** [comment]
Binutils issue prevents windows-rs from using single import lib for each arch but reducing to 2 import libs per arch is doable (gnu + gnullvm/msvc) if @glandium wants to continue working on this.

**Comment by kennykerr** [comment]
I'm not sure I'm ready to ditch the msvc tooling entirely if that's what is required. It's clunky but it is probably the only one the Visual Studio team officially supports for our internal customers.

**Comment by mati865** [comment]
Do you mean you want to keep generating import libraries in target crates `{arch}_msvc` with MSVC instead of LLVM?
I think LLVM would be as safe option as MSVC especially considering the fact Rust already uses LLVM to generate import libraries when using `raw-dylib` feature with MSVC targets but naturally you are the maintainer here.

There is also option for using `{arch}_msvc` crates (perhaps with adjusted name?) for `gnullvm` targets which according to https://github.com/microsoft/windows-rs/issues/1964#issuecomment-1227046538 shouldn't cause problems.

**Comment by kennykerr** [comment]
Part of my reluctance has to do with the current experience for generating the gnu/llvm libs using mingw which I have not been able to run successfully and is not very Windows-friendly. Agreed that LLVM itself is part of the toolchain so I don't have a problem with that in itself. Happy to continue to make progress here - just a little cautious I suppose. 😉

**Comment by kennykerr** [comment]
Closing for now. Feel free to keep the conversation going - love the improvements thus far!
