### ISSUE TITLE
Bug:samples direct2d can not be complile, the error is expected *-ptr, found enum `Option`

### ISSUE THREAD

**Issue by RubyKiss** [microsoft/windows-rs#2025]
### Which crate is this about?

windows

### Crate version

version = "0.39.0"

### Summary

cargo 1.62.1   

 --> src\main.rs:114:28
    |
    |             target.EndDraw(None, None)?;
    |                            ^^^^ expected *-ptr, found enum `Option`
    |
    = note: expected raw pointer `*mut u64`
                      found enum `Option<_>`

**Comment by kennykerr** [comment]
Does this readme help? https://github.com/microsoft/windows-rs/tree/master/crates/samples#readme
