### ISSUE TITLE
Documentation and release process: ensure the documentation pointed to by the README is always up-to-date

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#2032]
Right now, `windows-rs 0.40.0` has been released three days ago and the online documentation is not up to date.

It would be nice if the documentation and crates.io release could be synced in some way (e.g., ensuring the doc is ready before the release and swapping it a few minutes after the release is made).

**Comment by kennykerr** [comment]
The docs have now been updated to match the latest version of the `windows` crate.

**Comment by Rapptz** [comment]
Sorry to necro this, but the docs are now at 0.41.0 but the latest version is 0.43.

**Comment by kennykerr** [comment]
Yes, I'm having a hard time getting rustdoc to work properly on such a large crate.

**Comment by kennykerr** [comment]
I might try to generate a skeleton version of the `windows` crate just for docs generation.

**Comment by eddyb** [comment]
> I might try to generate a skeleton version of the `windows` crate just for docs generation.

@kennykerr If you can find a subset that works well, I wonder if specifying them in [`docs.rs` metadata](https://docs.rs/about/metadata) would make them succeed there too? Oh heh you already use some other features of that metadata:
https://github.com/microsoft/windows-rs/blob/773f19970b225668d4e314c35e5cc76d0220d6af/crates/libs/windows/Cargo.toml#L14-L16

**Comment by kennykerr** [comment]
I don't know that it'll ever be small enough for `docs.rs` without substantial work on their end, but @riverar just published updated docs on https://microsoft.github.io/windows-docs-rs/doc/windows/ so I'll close this issue for now.
