### ISSUE TITLE
Handling `Option<&mut Option<IWbemClassObject>>` InParams

### ISSUE THREAD

**Issue by Soul85** [microsoft/windows-rs#2040]
I am attempting to use `IWbemServices::GetObject` in order to subsequently call `IWbemClassObject::{GetMethod, SpawnInstance, Put}` in an effort to call WMI methods. Below is my current attempt with the issue being it feels extremely clunky trying to handle `pObject` or just do anything with it period. `GetObject` doesn't seem to be returning the object to me and I'm attempting to do this as closely as I did in `winapi` where my existing code is working, to no avail. What am I doing wrong?
```rs
unsafe {
    let mut pObject = ptr::null_mut::<Option<IWbemClassObject>>();
    services.GetObject(
        &BSTR::from("Win32_Process"),
        0,
        InParam::null(),
        pObject.as_mut(),
        None
    )?;
}
```
**Note:** This is the signature of `GetObject`:
```rs
GetObject<'a, P0>(&self, strobjectpath: &::windows::core::BSTR, lflags: i32, pctx: P0, ppobject: ::core::option::Option<&mut ::core::option::Option<IWbemClassObject>>, ppcallresult: ::core::option::Option<&mut ::core::option::Option<IWbemCallResult>>) -> ::windows::core::Result<()>
where
    P0: ::std::convert::Into<::windows::core::InParam<'a, IWbemContext>>
```

**Comment by kennykerr** [comment]
Does this help: https://github.com/microsoft/windows-rs/pull/2041

It takes advantage of some improvements to the `windows` crate since the 0.40 release, so you'll have to use a git dependency until 0.41 is released.

**Comment by kennykerr** [comment]
OK, I see using the WMI API in this way is overly complicated. Let me get that fixed and update the sample.

**Comment by kennykerr** [comment]
Yes, I tried simplifying your example but the `VARIANT` is definitely the main challenge. The rest seems to be just that WMI is hard to use. Here's a slightly simpler version, avoiding all the `zeroed` in your example:

```rust
let mut object = None;
server.GetObject(&BSTR::from("Win32_Service"), 0, None, Some(&mut object), None)?;

if let Some(object) = object {
    let mut in_params = None;
    let mut out_params = None;

    object.GetMethod(w!("ChangeStartMode"), 0, &mut in_params, &mut out_params)?;

    let in_params = if let Some(in_params) = in_params { Some(in_params.SpawnInstance(0)?) } else { None };

    if let Some(in_params) = &in_params {
        let mut value = VARIANT::default();
        (*value.Anonymous.Anonymous).vt = VT_BSTR;
        *(*value.Anonymous.Anonymous).Anonymous.bstrVal = BSTR::from("Manual");

        in_params.Put(w!("StartMode"), 0, &value, 0)?;
        VariantClear(&mut value)?;

        server.ExecMethod(&BSTR::from("Win32_Service.Name=\"Fax\""), &BSTR::from("ChangeStartMode"), 0, None, in_params, None, None)?;
    }
}
```

I hope to get to `VARIANT` soon. #539

**Comment by kennykerr** [comment]
Didn't realize the PR closed this issue. Let me know if there's anything I can do to help.
