### ISSUE TITLE
How to use IStorageProviderItemPropertySource::GetItemProperties

### ISSUE THREAD

**Issue by tangp3** [microsoft/windows-rs#2042]
[The IStorageProviderItemPropertySource struct](https://github.com/microsoft/windows-rs/blob/13d006259d56becd6337fb4592c1af78d04c53d4/crates/libs/windows/src/Windows/Storage/Provider/mod.rs#L379) doesn't have a constructor to use, I need to fetch and verify item property done by [SetAsync](https://github.com/microsoft/windows-rs/blob/13d006259d56becd6337fb4592c1af78d04c53d4/crates/libs/windows/src/Windows/Storage/Provider/mod.rs#L1835), I guess that's the right method to use.

Should I convert another type instance to IStorageProviderItemPropertySource first, or the expectation is that I need to implement my own struct of [this trait: IStorageProviderItemPropertySource_Impl](https://github.com/microsoft/windows-rs/blob/cbc54970034445e0e50ae548ab8d93768548a4fb/crates/libs/windows/src/Windows/Storage/Provider/impl.rs#L31), can I find some sample code/documentation anywhere ?

Thanks

**Comment by kennykerr** [comment]
For API questions, please visit: https://docs.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by tangp3** [comment]
@kennykerr, actually, I was [directed to here from the windows-api forum](https://learn.microsoft.com/en-us/answers/questions/1011885/how-to-use-istorageprovideritempropertysourcegetit.html)

**Comment by kennykerr** [comment]
Nice. 😬

Well I would

**Comment by kennykerr** [comment]
Nice. 😬

Well, I would still suggest using that forum but perhaps asking the question more generally about the API and not specifically about how to use it from Rust. Once you know how to use the API, translating that to Rust should be easy (and we can help). 

FYI @jonwis in case he can point you in the right direction.

**Comment by tangp3** [comment]
that's sounds a good point, thanks.
