### ISSUE TITLE
Unexpected mutability error with 0.40

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#2045]
DrawTextA(
    hdc,
    "Hello, Windows 10!".as_bytes(),    // error [E0308] expected mutable reference &mut [u8]
     &mut rect,
     DT_SINGLELINE | DT_CENTER | DT_VCENTER
);

Why would the string need to be mutable?

**Comment by riverar** [comment]
Per the [docs](https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-drawtexta):
> [in, out] lpchText
>
> A pointer to the string that specifies the text to be drawn. If the nCount parameter is -1, the string must be null-terminated.
>
> If uFormat includes DT_MODIFYSTRING, the function could add up to four additional characters to this string. The buffer containing the string should be large enough to accommodate these extra characters.

**Comment by MRahilly** [comment]
0.39 has lpchtext: &[u8] for DrawTextA() and it seems strange that would change to &mut [u8] for 0.40
But if is the case then I need to find out how to generate a &mut [u8] from a string literal.

**Comment by MRahilly** [comment]
This works:
let mut s: Vec<u8> = b"Hello, Windows 10!".to_vec();
DrawTextA(
          hdc,
          //"Hello, Windows 98!", // std::string::String
          //"Hello, Windows 98!".as_bytes(),
          &mut s,
          //-1,
          &mut rect,
          DT_SINGLELINE | DT_CENTER | DT_VCENTER
);

**Comment by rylev** [comment]
Please note that if the vector `v` does not have the capacity for the additional bytes, this might cause writing to memory that is not writable. To be sure, you should probably manually ensure the correct amount of capacity with `Vec::with_capacity` or something similar.

**Comment by MRahilly** [comment]
Thanks.
