### ISSUE TITLE
`CoSetProxyBlanket`/Authentication Issues

### ISSUE THREAD

**Issue by Soul85** [microsoft/windows-rs#2055]
Hi, in my efforts to modify the common `CoSetProxyBlanket` settings seen in most any code you will find, I realized how sparse the explanation of the various options are. I am looking to use the DELEGATE impersonation level in hopes to pass through my identity to a process I am spawning with `Win32_Process::Create` (Unrelated: any tips here would help. My current remote process doesn't have correct permissions it needs).

In doing so, I have run into nothing short of errors for an improperly configured proxy. It seems two potentially crucial constants are missing from this crate: `COLE_DEFAULT_PRINCIPAL` and `COLE_DEFAULT_AUTHINFO`. I believe part of my issue to be the fact that I am passing my server principal name as `w!("COLE_DEFAULT_PRINCIPAL")` when the `winapi` crate has it specified as `-1isize as *mut OLECHAR` meaning the API is likely confused by my value. All around, there just seems to be gaps preventing someone from easily connecting the dots.

**Comment by riverar** [comment]
Summary for others:

Dev is attempting to create a remote process using WMI + delegation/impersonation and hitting some roadblocks. Sample is in order.

> It seems two potentially crucial constants are missing from this crate: COLE_DEFAULT_PRINCIPAL and COLE_DEFAULT_AUTHINFO.

Good catch, filed https://github.com/microsoft/win32metadata/issues/1271 for you.
