### ISSUE TITLE
Bug: `Display` impl for `windows::core::Error` is sometimes empty

### ISSUE THREAD

**Issue by udoprog** [microsoft/windows-rs#2059]
### Which crate is this about?

windows

### Crate version

0.40.0

### Summary

The default conversion to `windows::core::Error` uses `HRESULT::ok`, which only includes a code without `info`. It *seems* like the message conversion for `code` (which is handled by `HRESULT::message`) results in empty messages.

The specific error I'm getting right now is a call to `IAudioClient::Initialize` (https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Media/Audio/struct.IAudioClient.html#method.Initialize).

And the error I'm seeing is:
```
Error { code: 0x88890008, message:  }
```
I believe this corresponds to [AUDCLNT_E_UNSUPPORTED_FORMAT](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Media/Audio/constant.AUDCLNT_E_UNSUPPORTED_FORMAT.html) and for whatever reason the internal call to [`HRESULT::message`](https://github.com/microsoft/windows-rs/blob/master/crates/libs/windows/src/core/hresult.rs#L85) results in a blank message.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\udoprog\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
beta-x86_64-pc-windows-msvc (default)
nightly-2019-08-10-x86_64-pc-windows-msvc
nightly-2021-03-24-x86_64-pc-windows-msvc
nightly-2021-05-01-x86_64-pc-windows-msvc
nightly-2021-05-04-x86_64-pc-windows-msvc
nightly-2021-08-27-x86_64-pc-windows-msvc
nightly-2022-01-12-x86_64-pc-windows-msvc
nightly-2022-06-21-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-msvc
nightly-x86_64-unknown-linux-gnu
local
system
1.37.0-x86_64-pc-windows-msvc
1.38.0-x86_64-pc-windows-msvc
1.39.0-x86_64-pc-windows-msvc
1.40.0-x86_64-pc-windows-msvc
1.45.0-x86_64-pc-windows-msvc
1.45.2-x86_64-pc-windows-msvc
1.49.0-x86_64-pc-windows-msvc
1.51.0-x86_64-pc-windows-msvc
1.52.0-x86_64-pc-windows-msvc
1.61.0-x86_64-pc-windows-msvc

active toolchain
----------------

beta-x86_64-pc-windows-msvc (default)
rustc 1.65.0-beta.1 (2a65764f2 2022-09-19)

### Crate manifest

```toml
[dependencies.windows]
version = "0.40.0"
features = [
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_System_Com_StructuredStorage",
    "Win32_Security",
    "Win32_System_WindowsProgramming",
    "Win32_System_Com",
    "Win32_Media_Audio",
    "Win32_Media_KernelStreaming",
    "Win32_Media_Multimedia",
]
```

### Expected behavior

It would be an improvement if the `Display` implementation at least ensured that the code is printed.

**Comment by kennykerr** [comment]
`windows::core::HRESULT` provides a `message` method that attempts to produce an error message for the `HRESULT` by calling `FormatMessageW`. Unfortunately, `AUDCLNT_E_UNSUPPORTED_FORMAT` doesn't appear to have a system error message. 

What you're seeing is `windows::core::Error` and its `Debug` output where it displays both the `HRESULT` value and any associated value. It goes to some length to retrieve a message from different sources but eventually gives up as there's nothing to display in this case. Here's an example:

```rust
fn main() {
    use windows::{core::*, Win32::Media::Audio::*};

    println!("message: {}", AUDCLNT_E_UNSUPPORTED_FORMAT.message());
    println!("{:?}", AUDCLNT_E_UNSUPPORTED_FORMAT);

    let error: Error = AUDCLNT_E_UNSUPPORTED_FORMAT.into();
    println!("{:?}", error);
}
```

**Comment by udoprog** [comment]
Ah. To be clear, I'm using the Debug impl just to demonstrate the output of the message and the presence of the error code.

The `std::fmt::Display` implementation for `windows::core::Error` does still result in an empty message which I think should be considered an issue. What I'm requesting is that it should mention that there is no human readable message available and the error code. Otherwise the standard way of formatting an error in Rust (using the `Display` implementation) won't be usable in these instances.

**Comment by udoprog** [comment]
Actually I see that the original bug report failed to mention that it was the use of `std::fmt::Display` that was the issue. My bad 😅.

**Comment by kennykerr** [comment]
Thanks for clarifying. 😊 Yes, I agree the `Display` output should also include the error code otherwise that's certainly a little confusing.

**Comment by kennykerr** [comment]
@udoprog let me know what you think of this: #2075
