### ISSUE TITLE
Feature request: Run rustfmt on the generated codebase

### ISSUE THREAD

**Issue by fgimian** [microsoft/windows-rs#2064]
### Motivation

Often I go to definition to view the windows-rs definitions and the code is quite hard to read due to very long lines.  Using rustfmt would appropriately wrap long lines and make it much easier to read the windows-rs generated source code.

### Drawbacks

I guess it may make diffs a little more difficult?

### Rationale and alternatives

- It makes it harder to read the windows-rs codebase when troubleshooting or looking at implementation details while developing
- The main alternative is to use word wrap when reading the code, but this is not ideal as it doesn't ensure correct indentation of wrapped lines nor does it split the lines at logical points

**Comment by fgimian** [comment]
Here's a before / after example of one of the function definitions I was just looking at:

Current definition:

```rust
#[doc = "*Required features: `\"Win32_System_Power\"`, `\"Win32_System_Registry\"`*"]
#[cfg(feature = "Win32_System_Registry")]
#[inline]
pub unsafe fn PowerReadFriendlyName<'a, P0>(rootpowerkey: P0, schemeguid: ::core::option::Option<*const ::windows::core::GUID>, subgroupofpowersettingsguid: ::core::option::Option<*const ::windows::core::GUID>, powersettingguid: ::core::option::Option<*const ::windows::core::GUID>, buffer: ::core::option::Option<*mut u8>, buffersize: *mut u32) -> u32
where
    P0: ::std::convert::Into<super::Registry::HKEY>,
{
    #[cfg_attr(windows, link(name = "windows"))]
    extern "system" {
        fn PowerReadFriendlyName(rootpowerkey: super::Registry::HKEY, schemeguid: *const ::windows::core::GUID, subgroupofpowersettingsguid: *const ::windows::core::GUID, powersettingguid: *const ::windows::core::GUID, buffer: *mut u8, buffersize: *mut u32) -> u32;
    }
    PowerReadFriendlyName(rootpowerkey.into(), ::core::mem::transmute(schemeguid.unwrap_or(::std::ptr::null())), ::core::mem::transmute(subgroupofpowersettingsguid.unwrap_or(::std::ptr::null())), ::core::mem::transmute(powersettingguid.unwrap_or(::std::ptr::null())), ::core::mem::transmute(buffer.unwrap_or(::std::ptr::null_mut())), ::core::mem::transmute(buffersize))
}
```

Formatted definition:

```rust
#[doc = "*Required features: `\"Win32_System_Power\"`, `\"Win32_System_Registry\"`*"]
#[cfg(feature = "Win32_System_Registry")]
#[inline]
pub unsafe fn PowerReadFriendlyName<'a, P0>(
    rootpowerkey: P0,
    schemeguid: ::core::option::Option<*const ::windows::core::GUID>,
    subgroupofpowersettingsguid: ::core::option::Option<*const ::windows::core::GUID>,
    powersettingguid: ::core::option::Option<*const ::windows::core::GUID>,
    buffer: ::core::option::Option<*mut u8>,
    buffersize: *mut u32,
) -> u32
where
    P0: ::std::convert::Into<super::Registry::HKEY>,
{
    #[cfg_attr(windows, link(name = "windows"))]
    extern "system" {
        fn PowerReadFriendlyName(
            rootpowerkey: super::Registry::HKEY,
            schemeguid: *const ::windows::core::GUID,
            subgroupofpowersettingsguid: *const ::windows::core::GUID,
            powersettingguid: *const ::windows::core::GUID,
            buffer: *mut u8,
            buffersize: *mut u32,
        ) -> u32;
    }
    PowerReadFriendlyName(
        rootpowerkey.into(),
        ::core::mem::transmute(schemeguid.unwrap_or(::std::ptr::null())),
        ::core::mem::transmute(subgroupofpowersettingsguid.unwrap_or(::std::ptr::null())),
        ::core::mem::transmute(powersettingguid.unwrap_or(::std::ptr::null())),
        ::core::mem::transmute(buffer.unwrap_or(::std::ptr::null_mut())),
        ::core::mem::transmute(buffersize),
    )
}
```

This leads to a significant improvement in readability.

**Comment by kennykerr** [comment]
Thanks for the feedback. We do in fact run `rustfmt` on the generated code. We just use a custom `rustfmt.toml` that sets the `max_width` as follows:

https://github.com/microsoft/windows-rs/blob/d0ab3b55d39a525e5b9d16a994d14ec5b46c69ae/rustfmt.toml#L2

That explains the long lines. The reason we do this is because it significantly reduces the size of the resulting binary crate. This is regrettable but necessary until we find a way to further reduce the size of the crate.

**Comment by fgimian** [comment]
> Thanks for the feedback. We do in fact run `rustfmt` on the generated code. We just use a custom `rustfmt.toml` that sets the `max_width` as follows:
> 
> https://github.com/microsoft/windows-rs/blob/d0ab3b55d39a525e5b9d16a994d14ec5b46c69ae/rustfmt.toml#L2
> 
> That explains the long lines. The reason we do this is because it significantly reduces the size of the resulting binary crate. This is regrettable but necessary until we find a way to further reduce the size of the crate.

Thank you so much for the reply, that indeed makes sense. 😄
