### ISSUE TITLE
Bug: IDropSource needs to return Ok values

### ISSUE THREAD

**Issue by littleBugHunter** [microsoft/windows-rs#2080]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

IDropSource implements two functions [IDropSource::GiveFeedback](https://learn.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-idropsource-givefeedback) and [IDropSource::QueryContinueDrag](https://learn.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-idropsource-querycontinuedrag)
Both return an OK Value other than S_OK, but their rust signature simply returns Result<()> eating up the actual HRESULT code.
This way the DragDrop Operation never finishes because DRAGDROP_S_DROP is never returned.

As far as my understanding goes this is a problem with the metatadata similar to: #1512 

I've opened microsoft/win32metadata#1291 with a request to add the PreserveSig metadata to the two functions.

### Expected behavior

return DRAGDROP_S_DROP from [IDropSource::QueryContinueDrag](https://learn.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-idropsource-querycontinuedrag) to finish the Drag Drop operation and return DRAGDROP_S_USEDEFAULTCURSORS from [IDropSource::GiveFeedback](https://learn.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-idropsource-givefeedback) in order to update the cursor style.

### Actual behavior

Nothing happens and App freezes while the drag drop operation never finishes

**Comment by kennykerr** [comment]
Thanks for opening the win32metadata issue - once that's fixed, we can automatically update the `windows` crate.
