### ISSUE TITLE
Should CreateFileA return a handle rather than an error?

### ISSUE THREAD

**Issue by a-roach** [microsoft/windows-rs#2081]
Hi,

I am probably missing something here as obvious as the nose on my face. 

I am calling CreateFileA to create and open a file for writing. The file is created, but when I call CreateFileA it returns a Result, not a file handle. Even though the file is created, the Result is an error, specifically Error code: 0x00000000, aka: "The operation completed successfully." Is this the expected behaviour, or should it return the handle? 

Also is there a way to get the handle still even though it is returning an error?

**Comment by Nerixyz** [comment]
Could you share your code?

This code works fine for me:

```rust
use windows::{
    s,
    Win32::{
        Foundation::{CloseHandle, HANDLE},
        Storage::FileSystem::{
            CreateFileA, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, FILE_GENERIC_READ, FILE_SHARE_DELETE,
        },
    },
};

fn main() -> windows::core::Result<()> {
    unsafe {
        let h = CreateFileA(
            s!("foo.txt"),
            FILE_GENERIC_READ,
            FILE_SHARE_DELETE,
            None,
            CREATE_ALWAYS,
            FILE_ATTRIBUTE_NORMAL,
            HANDLE(0),
        )?;
        dbg!(h);
        assert!(CloseHandle(h).as_bool());
    }
    Ok(())
}
```

**Comment by a-roach** [comment]
This is what I have:

let hFile = CreateFileA(
        s!("test.xxx"), 
        FILE_GENERIC_WRITE, 
        FILE_SHARE_MODE(0), 
        None, 
        CREATE_NEW, 
        FILE_ATTRIBUTE_NORMAL, 
        None);

    if let Ok(x) = hFile {
        println!("it is working");
        CloseHandle(x);
     }

I updated the windows dependency to 0.42.0, and it has stopped throwing the "operation completed successfully error", which is great. The handle, unlike the stand alone example above, is within a Result, but at least I can get to it now.

**Comment by Nerixyz** [comment]
> The handle, unlike the stand alone example above, is within a Result, but at least I can get to it now.

That's good though. Otherwise you'd need to check the handle yourself every time. In application code you'd wrap the handle in a newtype struct or similar and implement `Drop` on it. This way you make sure you always close the handle.

**Comment by riverar** [comment]
Going to close this as there's no work to be done here, but feel free to continue the discussion. Thanks @a-roach @Nerixyz!
