### ISSUE TITLE
`PCWSTR`'s `From<&HSTRING>` implementation may lead to dangerous code

### ISSUE THREAD

**Issue by num3ric** [microsoft/windows-rs#2082]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

Failure on (debug) launch in visual studio code with the automatically generated configuration:

```
         {
            "type": "lldb",
            "request": "launch",
            "name": "Debug executable 'sample_direct3d12'",
            "cargo": {
                "args": [
                    "build",
                    "--bin=sample_direct3d12",
                    "--package=sample_direct3d12"
                ],
                "filter": {
                    "name": "sample_direct3d12",
                    "kind": "bin"
                }
            },
            "args": [],
            "cwd": "${workspaceFolder}"
        },
```

Resulting error:
`Error: Error { code: HRESULT(0x80004005), message: "Unspecified error" }`

In stepping through the code, it looks like the failure stems from the first `D3DCompileFromFile` call in `create_pipeline_state`.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\num3ric\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

### Expected behavior

Successful launch.

### Actual behavior

`Error: Error { code: HRESULT(0x80004005), message: "Unspecified error" }`

**Comment by riverar** [comment]
```
#[test]
fn test()
{
    let s = "abcd";
    let pcwstr = PCWSTR::from(&s.into());
    unsafe { assert_eq!(pcwstr.as_wide(), [97, 98, 99, 100, 0]); }
}
```

@kennykerr  Not clear if the sample should be null terminating or if `&str -> &HSTRING` should be producing a null-terminated string.

**Comment by riverar** [comment]
There also appears to be an issue with a temporary value getting dropped here as we end up in `d3dcompiler_47!D3DCompileFromFile` with `rcx` pointing to nothing useful.

https://github.com/microsoft/windows-rs/blob/6d45cc6924209746a2a12b2df9bd760eef016265/crates/samples/direct3d12/src/main.rs#L429-L432

**Comment by kennykerr** [comment]
The problem is here:

https://github.com/microsoft/windows-rs/blob/3054d4065dbe11345608fdf2787fe614f96ec2f9/crates/libs/windows/src/core/strings/pcwstr.rs#L62-L66

The `PCWSTR` is not limited to the lifetime of the `HSTRING`.

**Comment by num3ric** [comment]
Glad I asked! Thanks, that did it.
