### ISSUE TITLE
Feature request: debugapi.h

### ISSUE THREAD

**Issue by youyuanwu** [microsoft/windows-rs#2089]
### Motivation

I want to use [IsDebuggerPresent ](https://learn.microsoft.com/en-us/windows/win32/api/debugapi/nf-debugapi-isdebuggerpresent) win32 API but it is missing in this crate.

winapi crate does have this function: https://docs.rs/winapi/latest/winapi/um/debugapi/fn.IsDebuggerPresent.html

Please support debugapi.h functions.

**Comment by riverar** [comment]
IsDebuggerPresent is available (https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/fn.IsDebuggerPresent.html).

Make sure you add the "Win32_System_Diagnostics_Debug", "Win32_Foundation" features to Cargo.toml.

Example usage:
```rust
while IsDebuggerPresent().as_bool() == false {
    std::thread::sleep(std::time::Duration::from_millis(1000));
}
```
