### ISSUE TITLE
Bug:utf-8中文encoded bug

### ISSUE THREAD

**Issue by zhengxingjian** [microsoft/windows-rs#2091]
### Which crate is this about?

windows

### Crate version

[dependencies.windows] version = "0.42.0" features = [     "Data_Xml_Dom",     "Win32_Foundation",     "Win32_Security",     "Win32_UI_WindowsAndMessaging", "Win32_Foundation",     "Win32_System_Threading",     "Win32_UI_WindowsAndMessaging", ]

### Summary

MessageBoxA(None, s!("NOT FOUND Notepad"), s!("消息"), MB_OK);

### Reproducible example

```rust
fn main() {
    // unsafe { on_exec(); }
    unsafe { close_notepad(); }
}

use windows::core::PCWSTR;
use windows::{s, w};
use windows::Win32::Foundation::{LPARAM, WPARAM};
use windows::Win32::System::Threading::WinExec;
use windows::Win32::UI::WindowsAndMessaging::{FindWindowA, MB_OK, MessageBoxA, SW_SHOW, WM_CLOSE, WM_NULL};
use windows::Win32::UI::WindowsAndMessaging::SendMessageA;

unsafe fn close_notepad() {
    // let h_wnd = FindWindowA(s!("Regedit"), None);
    let h_wnd = FindWindowA( None,s!("regedit"),);
    if h_wnd.0 == 0 {

        MessageBoxA(None, s!("NOT FOUND Notepad"), s!("消息"), MB_OK);
        return;
    }
    SendMessageA(h_wnd, WM_CLOSE, WPARAM::default(), LPARAM::default());
}

unsafe fn on_exec() {
    WinExec(s!("regedit.exe"), SW_SHOW.0);
}
```

**Comment by tim-weis** [comment]
You have to opt-in to UTF-8 support when using the ANSI versions of API calls. [Use UTF-8 code pages in Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page) explains how to do that.

**Comment by zhengxingjian** [comment]
MessageBoxW(None, w!("NOT FOUND Notepad"), w!("消息"), MB_OK);
OK!W and w! macro,A and s! macro
