### ISSUE TITLE
Tests should run with Application Verifier

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#2095]
Just a reminder to figure out how to get the CI build to execute all tests with Application Verifier turned on for test executables.

https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier

**Comment by kennykerr** [comment]
App Verifier doesn't have a great "driver" so I may just leave this for app developers who can run it manually...

**Comment by riverar** [comment]
I have this mostly done, can chat offline. I'm not convinced App Verifier error reporting works properly however.
