### ISSUE TITLE
Code generation should distinguish between mutable and const pointer input parameters

### ISSUE THREAD

**Issue by lunaryorn** [microsoft/windows-rs#2096]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

`FindMimeFromData` crashes the process with `STATUS_ACCESS_VIOLATION`

Using the code below makes the process crash.  I understand this is unsafe code and crashes are to be expected, but I don't understand what I'm doing wrong.  The types all line up, and the code looks like how I'd use the function in C 🤔 

### Reproducible example

```rust
use std::error::Error;

pub fn get_mimetype_for_buffer(buffer: &[u8]) -> Result<String, Box<dyn Error>> {
    use std::ffi::c_void;
    use windows::core::PWSTR;

    let mut ret = PWSTR::null();
    unsafe {
        // SAFETY: We pass a proper null pointer as return value, and an initialized
        // buffer with corresponding length as data buffer.
        windows::Win32::System::Com::Urlmon::FindMimeFromData(
            None,
            None,
            Some(buffer.as_ptr() as *const c_void),
            buffer.len().try_into().unwrap(),
            None,
            0,
            &mut ret,
            0,
        )?;
    }

    if !ret.is_null() {
        let mime_type = unsafe {
            // SAFETY: We explicitly check that ret is not null, and thus can safely convert its content>
            ret.to_string()?
        };
        Ok(mime_type)
    } else {
        Err(std::io::Error::new(
            std::io::ErrorKind::Other,
            "No mime type returned by FindMimeFromData",
        )
        .into())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mime_type_of_png_image() {
        let image_data = include_bytes!("test.png");

        let mime_type = get_mimetype_for_buffer(image_data).unwrap();
        assert_eq!(mime_type, "image/png");
    }
}
```

### Crate manifest

```toml
[package]
name = "rust-windows-FindMimeFromData"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
windows = { version = "0.42.0", features = ["Win32_System_Com_Urlmon"] }
```

### Expected behavior

The process shouldn't crash.

### Actual behavior

The process crashes with `STATUS_ACCESS_VIOLATION`.

### Additional comments

I've pushed a complete crate at https://github.com/lunaryorn/rust-windows-FindMimeFromData/ and https://github.com/lunaryorn/rust-windows-FindMimeFromData/actions/runs/3251102517/jobs/5335656453#step:4:28 demonstrates the failure on Github CI.

**Comment by kennykerr** [comment]
It's a curious one. I'm not 100% sure why this crashes on Rust but I would [point out the docs](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms775107(v=vs.85)) as providing a potential clue:

> After ppwzMimeOut returns and is read, the memory allocated for it should be freed with the [operator delete](https://msdn.microsoft.com/en-us/library/Aa278231) function.

This is not a good sign, to the say the least, and implies that this API depends on specifics of the C++ compiler and standard library used to compile the API. Even if you were to call it successfully, freeing the resulting memory is not particularly portable or well defined. It's possible that this API assume some CRT initialization that doesn't happen in Rust.

**Comment by riverar** [comment]
I can reproduce this. This API appears to have a limitation on the input buffer size--255 bytes. The docs allude to this but agree, it's not as clear as it should be.

> MIME type detection, or "data sniffing," refers to the process of determining an appropriate MIME type from binary data. The final result depends on a combination of server-supplied MIME type headers, file name extension, and/or the data itself. **Usually, only the first 256 bytes of data are significant.** [...]

**Comment by riverar** [comment]
`urlmon!CContentAnalyzer::FindMimeFromData` is supposed to ignore anything beyond 256, but I suspect there's a buffer somewhere you're overrunning. It's a Microsoft bug but given this is in ancient Internet Explorer territory, very unlikely to get fixed.

**Comment by riverar** [comment]
Deleted my previous hasty theory as I took another look in the debugger... standby.

**Comment by riverar** [comment]
OK, so turns out `urlmon!CContentAnalyzer::FindMimeFromData` is trying to **write** to your buffer. Seems like `*const c_void` is not quite right here given the input metadata is `[Optional][In][MemorySize(BytesParamIndex = 3)] void* pBuffer`.

Will re-open this and @kennykerr can take a closer look. Thanks for the report!

**Comment by kennykerr** [comment]
Thanks, I'll keep this open to deal with mutable input parameters.

**Comment by kennykerr** [comment]
I had a look at this but too many win32 metadata input parameters don't specify `const` correctly so I don't think there's an actionable solution to fix this on the Rust side.
