### ISSUE TITLE
Bug:LoadImageW returned an error, but the message says "The operation completed successfully."

### ISSUE THREAD

**Issue by mumashanren** [microsoft/windows-rs#2097]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

windows::Win32::UI::WindowsAndMessaging::LoadImageW returned an error, but the message says "The operation completed successfully."

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  D:\softwares\rust\rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

### Reproducible example

```rust
use windows::Win32::System::LibraryLoader::GetModuleHandleW;
use windows::Win32::UI::WindowsAndMessaging::{LoadImageW, IMAGE_BITMAP, LR_LOADFROMFILE, LR_CREATEDIBSECTION, LR_DEFAULTSIZE};

let hinst = GetModuleHandleW(PCWSTR::null()).unwrap();
let hbitmap = LoadImageW(
    hinst,
    PCWSTR(to_wstring("test.bmp").as_ptr()),
    IMAGE_BITMAP,
    0,
    0,
    LR_LOADFROMFILE | LR_CREATEDIBSECTION | LR_DEFAULTSIZE,
);
match hbitmap {
    Ok(handle) => println!("Handle is: {:?}", handle),
    Err(error) => println!("Error is: code {:?}, msg: {:?}", error.code(), error.message())
}
```

### Crate manifest

```toml
[dependencies.windows]
version = "0.42"
features = [
    "Win32_Graphics_Printing",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_Xps",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
]
```

### Expected behavior

Return a Result.Ok

### Actual behavior

Return a Result.Error

### Additional comments

pirntln! output is "Error is: code HRESULT(0x00000000), msg: 操作成功完成。" , The message says "The operation completed successfully."

**Comment by stuntman11** [comment]
This seems to be a bug or at least an inconvenience of the Win32 Api.
I can reproduce this issue not only in Rust but in C++ as well.

Some tested scenarios that result in the same behaviour:
* Relative path or absolute path
* Function parameter _hInst_ is **NULL** or **GetModuleHandle(NULL)**
* Removal of **LR_CREATEDIBSECTION** and **LR_DEFAULTSIZE** flags

My proposal to avoid confusion would be to check for this specific case and return an unknown error.
This solution would break consistency between the rust mapping and Win32 api, so I am waiting for a confirmation.

**Comment by kennykerr** [comment]
Yes, it seems to provide error information at least in some cases:

```rust
use windows::Win32::UI::WindowsAndMessaging::*;

fn main() {
    unsafe {
        let result = LoadImageW(None, None, IMAGE_BITMAP, 0, 0, LR_CREATEDIBSECTION);
        dbg!(result);
    }
}
```

This produces an error message saying, "The specified resource name cannot be found in the image file."
