### ISSUE TITLE
Import and build macros should emit a warning or error for missing namespace/type

### ISSUE THREAD

**Issue by Eroc33** [microsoft/windows-rs#210]
## Expected behaviour:

If I import a nonexistent namespace with `not_a_real_namespace::*` syntax, or a nonexistent type with `namespace::{NotARealType}` syntax I should recieve some sort of warning or error.

## Current behaviour:

~Compilation silently continues~
Edit:
Compilation silently continues for missing types, but panics for namespaces (this is probably better than being silent)

**Comment by kennykerr** [comment]
This should be fixed as of #773 - let me know if you notice any further issues.
