### ISSUE TITLE
Cresate IXpsOMObjectFactory instance result code: 0x80040154, message: Class not registered

### ISSUE THREAD

**Issue by mumashanren** [microsoft/windows-rs#2104]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: 0x80040154, message: Class not registered }', src\main.rs:28:85
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\result.rs:1814
   3: enum$<core::result::Result<windows::Windows::Win32::Storage::Xps::IXpsOMObjectFactory,windows::core::error::Error> >::unwrap<windows::Windows::Win32::Storage::Xps::IXpsOMObjectFactory,windows::core::error::Error>             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\result.rs:1107
   4: tlps::main
             at .\src\main.rs:28
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  D:\softwares\rust\rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

### Reproducible example

```rust
fn main() {
    use windows::core::*;
    use windows::Win32::Storage::Xps::Printing::*;
    use windows::Win32::Storage::Xps::*;
    use windows::Win32::System::Com::*;
    use windows::Win32::System::Threading::*;

    unsafe {
        CoInitializeEx(None, COINIT_MULTITHREADED).unwrap();
        let event = CreateEventW(None, true, false, None).unwrap();
        let mut job = None;
        let mut stream = None;

        StartXpsPrintJob(
            PCWSTR(to_wstring("Lenovo M7208W").as_ptr()),
            None,
            None,
            None,
            event,
            &[1],
            &mut job,
            &mut stream,
            &mut None,
        )
        .unwrap();

        let _fatcory: IXpsOMObjectFactory =
            CoCreateInstance(&IXpsOMObjectFactory::IID, None, CLSCTX_INPROC_SERVER).unwrap();

        CoUninitialize();
    }
}

fn to_wstring(value: &str) -> Vec<u16> {
    use std::os::windows::ffi::OsStrExt;
    std::ffi::OsStr::new(value)
        .encode_wide()
        .chain(std::iter::once(0))
        .collect()
}
```

### Crate manifest

```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.42"
features = [
    "implement",
    "Win32_Graphics_Printing",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Storage_Xps",
    "Win32_Storage_Xps_Printing",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Imaging",
    "Win32_System_Com",
    "Win32_Storage_FileSystem", 
    "Win32_System_IO",
    "Win32_System_Threading",
    "Win32_Security"
]
```

**Comment by kennykerr** [comment]
"Class not registered" means the `CLSID` is not recognized or found on the system. The `CLSID` is the first parameter on the `CoCreateInstance` call. In this case, you're passing the `IID` (interface ID) rather than the `CLSID` (class ID). [According to the docs](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/dd372970(v=vs.85)), you should use `XpsOMObjectFactory` for the `CLSID` while `IXpsOMObjectFactory` is the resulting interface to request.

**Comment by mumashanren** [comment]
Thanks, using `&XpsOMObjectFactory` as the first parameter is working.

**Comment by kennykerr** [comment]
By the way, you can replace this line:

```rust
PCWSTR(to_wstring("Lenovo M7208W").as_ptr()),
```

With this:

```rust
w!("Lenovo M7208W"),
```

The `w!` macro produces a null-terminated wide string literal at compile time.
