### ISSUE TITLE
Question: ANSI strings are being encoded as UTF-8 which doesn't seem to work correctly?

### ISSUE THREAD

**Issue by fgimian** [microsoft/windows-rs#2107]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

I truly may be missing something so please forgive me in advance if this is the case.  After examining the `s!` macro and the `PCSTR` struct, I can see that windows-rs treats such strings as null-terminated UTF-8 strings.  However, my understanding was that these should be ANSI (Windows 1252 encoded) strings as documented [here](https://en.wikipedia.org/wiki/Windows-1252).

Just to verify this, I opened PowerShell and created a file containing a non-ASCII character `ÿ` like so:

```powershell
ni 'ÿ.txt'
```

I then attempted to open the file with `CreateFileA` as shown in the example below, but this would always fail to find the file:

```
Result: Err(Error { code: 0x80070002, message: The system cannot find the file specified. })
```

If I encode this myself using a nul-terminated byte vector, `ÿ` corresponds to `255`:

```rust
        let filename = vec![255, 46, 116, 120, 116, 0];
        let filename = PCSTR::from_raw(filename.as_ptr());
```

This works as expected.

```
Result: Ok(HANDLE(392))
```

Using a filename that only contained ASCII characters, such as `Cargo.toml` worked correctly with the current implementation (naturally because this doesn't tap into the extended character set and thus the encodings are equivalent):

e.g.

```rust
let filename = s!("Cargo.toml");
```

Of course, I always tend to use the wide versions of functions but there are several functions that don't have wide equivalents and thus I do need to ensure that ANSI strings work correctly in those circumstances.

### Toolchain version/configuration

```
Default host: x86_64-pc-windows-gnu
rustup home:  C:\Users\Fots\scoop\persist\rustup\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

### Reproducible example

```rust
use windows::{
    core::s,
    Win32::Storage::FileSystem::{
        CreateFileA, FILE_ATTRIBUTE_NORMAL, FILE_READ_DATA, FILE_SHARE_READ, OPEN_EXISTING,
    },
};

fn main() {
    unsafe {
        let filename = s!("ÿ.txt");
        let result = CreateFileA(
            filename,
            FILE_READ_DATA,
            FILE_SHARE_READ,
            None,
            OPEN_EXISTING,
            FILE_ATTRIBUTE_NORMAL,
            None,
        );
        println!("Result: {:?}", result);
    }
}
```

### Crate manifest

```toml
[package]
name = "winstrings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem"
]
```

### Expected behavior

A file containing extended 1252 characters should be possible to open with A function variants.

### Actual behavior

The strings produced by the `s!` macro don't seem to encode in the form expected by A functions.

### Additional comments

After donig a bunch more reading, I have come to understand that the meaning of ANSI can vary depending on region and thus it may not necessarily be 1252.  Thus my only guess is that the windows-rs crate essentially treats ANSI as ASCII and thus removing the ambiguity of those extra 128 characters added by the 8th bit.  However, I think if this is the case, it would optimal to see an encoding error or similar in such cases.

**Comment by kennykerr** [comment]
This is something you can configure directly. See #2091 for details.

**Comment by fgimian** [comment]
Thanks so much @kennykerr, I'll go ahead and close this one 😄

**Comment by riverar** [comment]
Reopening as the `s!` macro doesn't support characters beyond the ASCII set (e.g. ß) but still within the Windows codepage 1252 supported by narrow (A) APIs.

**Comment by fgimian** [comment]
> Reopening as the `s!` macro doesn't support characters beyond the ASCII set (e.g. ß) but still within the Windows codepage 1252 supported by narrow (A) APIs.

Thanks so much Rafael.  Perhaps there also needs to be some clarity in the docs (maybe I missed it?) about how windows-rs treats ANSI strings.

It would be ideal if one didn't need to add a manifest after the executable was built.  I searched around but it seems that the manifest is the only way but I'm hoping I'm wrong.  If this is mandatory to get reliable UTF-8 support for the A variants of functions based on a decision made by the library internals, it would be awesome if this was mentioned in any related samples and maybe the README.

Kindest Regards
Fotis

**Comment by riverar** [comment]
I think you might be better off using the wide (W) APIs for now (with UTF-16).

**Comment by fgimian** [comment]
> I think you might be better off using the wide (W) APIs for now (with UTF-16).

Totally agreed, and I do indeed use W variants for everything I can, but there are functions like [MapAndLoad](https://learn.microsoft.com/en-us/windows/win32/api/imagehlp/nf-imagehlp-mapandload) which don't appear to have wide equivalents.

It seems the majority in `imagehlp.h` don't offer wide variants.

Thanks heaps
Fotis

**Comment by kennykerr** [comment]
> Reopening as the s! macro doesn't support characters beyond the ASCII set (e.g. ß) but still within the Windows codepage 1252 supported by narrow (A) APIs.

Just a nit that I don't consider this a bug. The `s!` macro is just a Rust string literal with a trailing null terminator and Rust strings are always valid UTF-8. If we change `s!` to produce [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) strings it would be very confusing for Rust developers accustomed to UTF-8 strings. I am happy to entertain a complementary `a!` macro that produces Windows-1252 strings directly to avoid a run time conversion, but I don't know how much demand there exists for such a thing and whether it merits inclusion. But I trust @riverar to explore such a feature and its merits.

**Comment by Paul-Dempsey** [comment]
On Windows, no getting around having to learn how codepages work, and use the appropriate codepage conversion APIs. To take a UTF-8 literal to ANSI would require first converting to wide char (UTF-8 -> UTF-16), then to ANSI bytes using WideCharToMultibyte. User would need to make decisions about which codepage to use, and how to handle errors in conversion for characters not in whatever codepage you're converting to. There would be no right answers to these questions at compile time because for many use cases, it would depend on runtime variation (what system is the target code running on).

If there were an `a!` macro, assuming WIndows-1252 would be ok (generally speaking) only for systems running with a WIndows-1252 codepage, which wouldn't be the case for many parts of the world. Using current system codepage would also be problematic. Better to not do such a macro. IMO it would do more harm than good.

**Comment by riverar** [comment]
I'm okay with sweeping this under the rug, but we just need some guidance for folks trying to use APIs such as MapAndLoad, GetProcAddress, etc. and handle module names, for example, containing non-ASCII > 0x7F and < 0xFF bytes. A FAQ entry outlining the limitations of the `s!()` macro might be a good start.

**Comment by kennykerr** [comment]
An FAQ entry sounds great.

**Comment by fgimian** [comment]
I'm hoping to write a blog post on all this soon and will link it here in case you want to grab anything from it for the FAQ.  I think some general clarification about string handling would be great:

- A basic explanation about the various string types, BSTR, HSTRING, PCWSTR, PWSTR, PCSTR, PSTR (I realise these are second nature to Windows C++ developers, but you may come across people like me who are both new to Rust and the Windows SDK)
- Clarification that data in the P variants of these strings are not owned and should be backed by owned data types
- Instructions on how to create an underlying buffer / owner type for all pointer types
- A suggestion that W functions should always be favoured
- Explanation that windows-rs assumes UTF-8 for ANSI strings which requires that a manifest be used for full support
- Clarification that all P string types must be nul terminated and thus nothing in the Rust standard library may be used without modification (e.g. [encode_utf16](https://doc.rust-lang.org/stable/std/primitive.str.html#method.encode_utf16))

I personally prefer to use a crate such as `widestring` for creating PCWSTR.  Currently windows-rs offers a way to back PCWSTR with HSTRING but if we're nitpicking, HSTRING contains more data (and therefore memory) than is required for a PCWSTR so I prefer not to use that.

e.g.

```rust
use widestring::U16CString;
use windows::core::PCWSTR;
...
fn do_something(path: &str) {
    let path = U16CString::from_str(path).unwrap(); // Checks for interior nuls.
    let path = PCWSTR::from_raw(path.as_ptr());
    ...
}
```

**Comment by fgimian** [comment]
I've just published my little blog post [here](https://fgimian.github.io/blog/2022/10/23/working-with-strings-in-windows-rs/).  The source is avaliable [here](https://github.com/fgimian/fgimian.github.io/blob/source/blog/content/post/working-with-strings-in-windows-rs.md).

Feel free to take anything you like from this post and also tell me if I've missed anything 😄 

Hope this helps
Fotis
