### ISSUE TITLE
Bug: `PropertyValue::CreateEmpty()` fails with `HRESULT(0x00000000)`

### ISSUE THREAD

**Issue by kaivol** [microsoft/windows-rs#2108]
### Which crate is this about?

`windows`

### Crate version

0.42.0

### Summary

```rust
PropertyValue::CreateEmpty()
``` 
fails and returns `Err(Error { code: 0x00000000, message: [...] })`.
Apparently, [`CreateEmpty`](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.propertyvalue.createempty?view=winrt-22621) returns a `null` pointer, which `windows-rs` identifies as an invalid `IInspectable`. 

I think the same problem occurs when using `PropertySet`, e.g.
```rust
let set = PropertySet::new().unwrap();
let empty: IInspectable = unsafe { mem::transmute(ptr::null_mut::<std::ffi::c_void>()) };
set.Insert(KEY, &empty).unwrap();
let value = set.Lookup(KEY);
mem::forget(empty); // don't drop NULL IInspectable
```
also fails with `value = Err(Error { code: 0x00000000, message: [...] })`. 

### Toolchain version/configuration

```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\[...]\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
beta-x86_64-pc-windows-msvc
nightly-2022-03-18-x86_64-pc-windows-msvc
nightly-2022-09-24-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

thumbv7em-none-eabi
thumbv7em-none-eabihf
thumbv7m-none-eabi
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

### Reproducible example

```rust
use windows::Foundation::PropertyValue;

fn main() {
    let value = PropertyValue::CreateEmpty();
    println!("{value:?}");
}
```

### Crate manifest

```toml
[package]
name = "windows-rs-demo"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.42"
features = [
    "Foundation",
    "Foundation_Collections"
]
```

### Expected behavior

Unclear.

### Actual behavior

`PropertyValue::CreateEmpty()`  fails and returns `Err(Error { code: 0x00000000, message: [...] })`.

**Comment by kennykerr** [comment]
When an API returns a null COM interface pointer, the `Result<T>` needs some way to express that it did not fail but also does not contain a value for [Result](https://doc.rust-lang.org/std/result/enum.Result.html)'s `Ok` variant since interfaces like `IInspectable` are [NonNull](https://doc.rust-lang.org/std/ptr/struct.NonNull.html) in Rust. The only option is to use the `Err` variant and pass on the actual error value returned by the API which is 0x00000000, otherwise known as `S_OK`.

**Comment by rylev** [comment]
The metadata has no way of specifying that this might happen, right? If we knew ahead of time that an API were likely to return `null` on success, we could encode the return type as `windows::Result<Option<T>>` instead.

**Comment by kennykerr** [comment]
`PropertyValue` as a whole just exists to support Xaml boxing - it's used internally by language projections to box and unbox value types - but `CreateEmpty` itself is never called since it just returns a null pointer value and there's no need to call an API to create one of those.
