### ISSUE TITLE
Feature request: Consider adding interfaces such as IPropertyStore to the sys crate

### ISSUE THREAD

**Issue by fgimian** [microsoft/windows-rs#2109]
### Motivation

I personally have found the sys crate to be more natural to use in practice, and the reduced compile times are fantastic.

I think the included functionality is excellent, although with interfaces such as `IShellDispatch`, `IPropertyStore` etc. all simply being `c_void` pointers in the sys crate, it seems impossible to use related functions.

Keeping the sys crate minimal is indeed a wonderful idea, but removal of the interface definitions makes it impossible to use for certain scenarios.

A little explanation of why I find the sys crate more usable is as follows:

- It's much faster to compile
- It represents the original SDK documentation exactly
- There's less inconsistency (e.g. the main windows crate returns Result types for some of the API and BOOLs or other types for various other parts of the API)
- There are less issues with constants (e.g. the main windows crate sometimes takes a `u32` as a parameter for constant types and thus you have to use `CONSTANT.0` to pass the relevant u32).  Some examples of this are `CertAddEncodedCertificateToStore(.., dwcertencodingtype, ...)`, `SetEntriesInAclW -> u32`, `GetFileAttributesW -> u32` which we need to perform bitwise operations on with `FILE_ATTRIBUTE_*` constants.

### Drawbacks

The sys crate could grow in size a little when interfaces are added.

### Rationale and alternatives

- It will make the sys crate fully functional for all scenarios
- Other low level libraries like winapi-rs [provide implementations for most such interfaces](https://github.com/retep998/winapi-rs/blob/2f76bdea3a79817ccfab496fbd1786d5a697387b/src/um/propsys.rs#L14)

**Comment by fgimian** [comment]
I suppose this is covered in the [FAQ](https://github.com/microsoft/windows-rs/blob/master/docs/FAQ.md#how-do-i-choose-between-the-windows-and-windows-sys-crates) and so I guess this decision has been made with a lot of thought.  So if this won't be considered, feel free to close this.

I just think it would be great if the sys package could be used for all scenarios if someone wanted the lowest level API that matched that of the C++ one. 😄

**Comment by kennykerr** [comment]
> There are less issues with constants (e.g. the main windows crate sometimes takes a u32 as a parameter for constant types and thus you have to use CONSTANT.0 to pass the relevant u32). Some examples of this are CertAddEncodedCertificateToStore(.., dwcertencodingtype, ...), SetEntriesInAclW -> u32, GetFileAttributesW -> u32 which we need to perform bitwise operations on with FILE_ATTRIBUTE_* constants.

If you report such cases, they tend to be quickly fixed: https://github.com/microsoft/win32metadata/issues

**Comment by fgimian** [comment]
> 

No worries at all, I'll definitely be reporting all instances of these that I've found over the weekend.  Thanks heaps.

Is inclusion of COM interfaces in the sys crate something that's open for consideration or is it simply too much overhead to add to the sys crate?  Seeing as how the various pieces of functionality are broken up into separate crates; I was hoping that it would be an opt-in thing anyway, but I understand if it simply doesn't make sense technically.

Cheers
Fotis

**Comment by fgimian** [comment]
Thanks so much @kennykerr, I'll go ahead and close this one and focus my efforts on reporting any issues I find with the main crate so we can get it as close to perfect as possible.

Cheers
Fotis

**Comment by fgimian** [comment]
Raised the related issue for wincrypt.h [here](https://github.com/microsoft/win32metadata/issues/1323) 😄
