### ISSUE TITLE
Bug: CredEnumerateA and CredEnumerateW should take *mut *mut CREDENTIAL(A|W) instead of *mut *mut *mut CREDENTIAL(A|W)

### ISSUE THREAD

**Issue by iancormac84** [microsoft/windows-rs#2112]
### Which crate is this about?

windows, windows-sys

### Crate version

0.42.0

### Summary

According to the documentation found for [CredEnumerateW](https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credenumeratew) (and CredEnumerateA). Trying to access the CREDENTIAL(A|W) buffer returned by the function leads to consistent STATUS_ACCESS_VIOLATION errors.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\scorp\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.66.0-nightly (5c8bff74b 2022-10-21)

### Reproducible example

```rust
N/A
```

### Crate manifest

```toml
N/A
```

**Comment by riverar** [comment]
@iancormac84 Did you resolve this on your own?

I would consider filing an issue at https://github.com/microsoft/win32metadata and ask for the array retval to be specially marked as such. That would then let this crate generate an easier to work with vector type. Sound right @kennykerr?

**Comment by iancormac84** [comment]
Hello @riverar. On further perusal, it appears as though *mut *mut *mut CREDENTIAL(A|W) is indeed correct. I also got my code to work.
