### ISSUE TITLE
Bug: IStream_Vtbl's Seek wrapper can dereference null pointer

### ISSUE THREAD

**Issue by miolad** [microsoft/windows-rs#2122]
The implementation of the wrapper of `IStream::Seek` doesn't check whether `plibNewPosition` is `NULL` before writing to it, even though the [docs](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-istream-seek) state that `NULL` is indeed a valid value for that parameter.

https://github.com/microsoft/windows-rs/blob/4726348167316b4624abbe57e0b09cd05f12e0d5/crates/libs/windows/src/Windows/Win32/System/Com/impl.rs#L3804

**Comment by kennykerr** [comment]
Implementation support still needs some work. You can use the `interface` macro as a workaround in the meantime.

**Comment by kennykerr** [comment]
Tracked this down and it's rooted in a Win32 metadata bug: https://github.com/microsoft/win32metadata/issues/1005

The challenge is that this parameter is a trailing optional parameter and many such parameters are incorrectly marked as optional in metadata. Anyway, I've got a fix for this issue and hopefully the metadata will be improved shortly.

**Comment by kennykerr** [comment]
This line:

https://github.com/microsoft/windows-rs/blob/eb9d65cb21d3ac7c17952d4fa58959d8bba2f745/crates/libs/metadata/src/reader/mod.rs#L1336

Needs to include optional parameters as follows:

```rust
if flags.input() || !flags.output() || flags.optional() || param.kind.is_array() {
```

But that's blocked on: https://github.com/microsoft/win32metadata/issues/1005
