### ISSUE TITLE
Cleanup guidance when working with COM 

### ISSUE THREAD

**Issue by vpopescu** [microsoft/windows-rs#2123]
I hope this doesn't sound too generic.

Generally when working with COM in C++, there is very good guidance on what you need to do to clean up after yourself, depending on whether you are dealing with smart pointers or not.  Take for example the following snippet from MS documentation:

```
        IWbemClassObject *pObj = 0;
        hRes = pEnum->Next(0,    1,   &pObj,   &uReturned);

         /// ...
        
        pObj->Release();    // Release objects not owned.  
```

Is there guidance on how to clean up COM references such as these, when using the crate? Do we just drop(pObj)? Or does the crate implement some type of smart pointers that are automatically cleaned up when they go out of scope? Looking at the [documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Wmi/struct.IWbemObjectTextSrc.html), it doesn't really imply I need to do any cleanup.

SImilarly, coming from C++, you are used to SysAllocString/SysFreeString to work with BSTR (unless you are using smart pointers), can I assume the rust implementation is a smart pointer, since there is no specific cleanup [documented](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.BSTR.html)?

**Comment by tim-weis** [comment]
COM interface implementations in the windows crate provide automatic resource management. While not immediately apparent from the [documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Wmi/struct.IWbemObjectTextSrc.html) they transparently wrap an [`IUnknown`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.IUnknown.html) struct, which has the [`Drop`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.IUnknown.html#impl-Drop-for-IUnknown) (and [`Clone`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.IUnknown.html#impl-Clone-for-IUnknown)) traits implemented, dealing with reference counting and releasing resources as needed.

Likewise, the [`BSTR`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.BSTR.html) struct provides both [`Drop`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.BSTR.html#impl-Drop-for-BSTR) and [`Clone`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.BSTR.html#impl-Clone-for-BSTR) implementations, so resource management is supplied out-of-the-box here as well.

This crate also has a large set of [samples](https://github.com/microsoft/windows-rs/tree/master/crates/samples), such as [com_uri](https://github.com/microsoft/windows-rs/tree/master/crates/samples/com_uri) and [wmi](https://github.com/microsoft/windows-rs/tree/master/crates/samples/wmi), that illustrate proper use of the crate. The latter is also insightful in acknowledging that `VARIANT`s have [not yet](https://github.com/microsoft/windows-rs/issues/539) received resource management support.

**Comment by vpopescu** [comment]
Thank you, very useful information, it may be good to add it to the FAQ discussed in another thread, if that will still happen (or maybe it's not a "frequently" asked question.
