### ISSUE TITLE
All *GetIDsOfNames COM methods have incorrect return types/signatures

### ISSUE THREAD

**Issue by iancormac84** [microsoft/windows-rs#2141]
*GetIDsOfNames methods (found in and IDispatch and ITypeInfo and other derivations found in other COM interfaces) and DispGetIDsOfNames function are returning i32. Documentation mentions "Caller-allocated array", rather than a single ID. This applies for any interface that inherits from IDispatch etc.

Wasn't sure if the problem was on this side or with win32metadata.

**Comment by kennykerr** [comment]
I had a very brief glance, and it looks like the Rust transformation misses the array metadata on the trailing/return type. Will take a closer look.

**Comment by simonbuchan** [comment]
I noticed this too, but it seems I've managed to get away with it fine, as MSHTML only seems to ask about one at a time...
