### ISSUE TITLE
The specified datatype is invalid (StartDocPrinterA)

### ISSUE THREAD

**Issue by yooouuri** [microsoft/windows-rs#2142]
Hey,

Im trying to send raw data to a Epson TM-T20 III printer.

The following example im using is: https://learn.microsoft.com/en-us/troubleshoot/windows/win32/win32-raw-data-to-printer

The `OpenPrinterA` returns true (if I log it with `.as_bool()`) but the `StartDocPrinterA` gives me the following error:

> The specified datatype is invalid

Is `raw` not a valid datatype?

Im new to rust, so maybe there is a flaw in my code. I hope somebody can help me with this issue.

If this is not the right place for this issue, please tell me where I can ask this question!

Thanks!

```rust
use std::ffi::c_void;
use windows::Win32::Foundation::HANDLE;
use windows::Win32::Foundation::GetLastError;
use windows::Win32::Graphics::Printing::*;
use windows::core::{PCSTR, PSTR};

#[cfg(target_os = "windows")]
pub unsafe fn print_job(printer_name: &str, data: &[u8], _doc_name: &str) {
    let mut printer: HANDLE = Default::default();

    OpenPrinterA(
        PCSTR::from_raw(printer_name.as_ptr()),
        &mut printer,
        None
    );

    let mut doc_info: DOC_INFO_1A = DOC_INFO_1A::default();

    let mut doc_name = String::from("Page title");
    let mut data_type = String::from("raw");

    doc_info.pDocName = PSTR(doc_name.as_mut_ptr());
    doc_info.pOutputFile = PSTR::null();
    doc_info.pDatatype = PSTR(data_type.as_mut_ptr());

    let job = StartDocPrinterA(printer, 1, &doc_info);

    if job == 0
    {
        println!("{}", GetLastError().to_hresult().message());

        ClosePrinter(printer);

        return
    }

    let mut written_bytes: u32 = 0;

    if !WritePrinter(printer, data.as_ptr().cast_mut() as *mut c_void, data.len() as u32, &mut written_bytes).as_bool()
    {
        println!("{}", GetLastError().to_hresult().message());

        EndPagePrinter(printer);
        EndDocPrinter(printer);
        ClosePrinter(printer);

        return
    }

    if !EndDocPrinter(printer).as_bool()
    {
        ClosePrinter(printer);
    }

    ClosePrinter(printer);
}
```

**Comment by kennykerr** [comment]
I'm not familiar with this API, but the most glaring problem is that you are passing raw pointers to Windows API for the various string parameters, and they are not null terminated. Generally, Windows APIs expect null-terminated strings, but Rust strings are not necessarily null-terminated.

**Comment by kennykerr** [comment]
Now that you have an idea of how to call the API from Rust, you can use one of the following forums to get help with how to actually use the API correctly:

* https://learn.microsoft.com/en-us/answers/topics/windows-api.html
* https://stackoverflow.com/
