### ISSUE TITLE
SE_OBJECT_TYPE is not an enumeration

### ISSUE THREAD

**Issue by fsavy-tehtris** [microsoft/windows-rs#2143]
Even though `SE_OBJECT_TYPE` is defined as an enumeration in the [documentation ](https://learn.microsoft.com/en-us/windows/win32/api/accctrl/ne-accctrl-se_object_type)and in the [metadata](https://github.com/microsoft/win32metadata/blob/f86785bec72eef8aa9c9cf5a84fc6d446abe2db5/generation/WinSDK/RecompiledIdlHeaders/um/AccCtrl.h#L46-L62), its members are listed separately in `windows-rs` ([`SE_FILE_OBJECT`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Security/Authorization/constant.SE_FILE_OBJECT.html) for instance).

I thought the fix would be to update `enums.json` in `win32metadata`, but the values are not loose constants like in https://github.com/microsoft/win32metadata/issues/895, so I'm not sure what the way forward is.

**Comment by kennykerr** [comment]
C-style enums and Rust enums are very different beasts. In particular and unlike in C, it is an error for two variants to share the same discriminant, or value, in Rust. This conflicts with various enumerations in the Windows SDK. Instead, the `windows` crate models them as unique types with a set of loose constants of that same type. This is similar to unscoped enums in C++ and more closely models the way these constants were meant to be used in the first place, in the C programming language.

**Comment by fsavy-tehtris** [comment]
Thanks for the explanation!
