### ISSUE TITLE
Possible need for newtypes to represent data types that show up as VARIANT_0_0_0 fields

### ISSUE THREAD

**Issue by iancormac84** [microsoft/windows-rs#2150]
In looking at the data types represent in a VARIANT_0_0_0, I noticed that there were 3 data types that were represented by i32's, 3 represented by *mut i32's, and duplicate f64's, *mut f64's, and *mut u32's. They seem like just the use case for newtypes. Not sure if these newtypes would be created the same time as the rollout of support for the VARIANT date type tracked by issue #539.

**Comment by kennykerr** [comment]
This struct is steeped in history. I suggest you have a look at the definition of `VARIANT` in the Windows headers, you'll notice that it has a few distinct variants that all boil down to the same underlying memory layouts. For example, `LONG lVal` and `INT intVal` are both signed 32-bit integers. 

Beyond #539, I'm not really sure what you're asking for here.

**Comment by iancormac84** [comment]
My thought is that, for instance with the i32's, the `lVal` represents a plain signed 32-bit signed integer being stored in the union, while the `scode` variable represents when an `SCODE` is being stored. They would have very different use cases, and they even have their own distinct `VARENUM`s. So I'm wondering if, to avoid any problems caused by weak typing, if for example there shouldn't be a `SCode` newtype to distinguish what the 32-bit signed integer is being used for, or a `DATE` newtype to distinguish between when the double is being used to represent a date as opposed to a plain double, etc.

**Comment by kennykerr** [comment]
#539 exists to at least attempt to make it a little less unwieldy. However, that will likely be limited to various `From` implementations as well as `Clone` and `Drop` support. I'm reluctant to go much further as it can quickly become a project worthy of its own crate. 😊

**Comment by iancormac84** [comment]
I hear you! Thank you for the excellent you have been doing!
