### ISSUE TITLE
Feature request: WinUI 3 and Windows App SDK Support

### ISSUE THREAD

**Issue by JLunda** [microsoft/windows-rs#2153]
### Motivation

Thank you for your work on the windows crate! I am just learning Rust and am just curious as to the roadmap for supporting Windows App SDK and WinUI 3. I ask this because I was currently attempting to use the `Windows::UI::WindowsManagement::AppWindow` class from the windows crate, which is analogous to the UWP AppWindow.

Suggested development SDK's for new development have changed, however, and [Windows App SDK](https://learn.microsoft.com/en-us/windows/apps/develop/) and [WinUI 3](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/) are the latest SDK's to provide a common windowing library across all Windows frameworks, including Windows 11, Windows 10, and UWP applications. I am just curious what the roadmap for supporting WinUI 3 and Windows App SDK looks like for this Rust crate.

I see you've previously worked on a [winui crate](https://crates.io/crates/winui) and [Windows App SDK](https://crates.io/crates/windows-app), so maybe you're already looking into this. :)

### Drawbacks

Limited resources and the desire to first support older Windows applications, including those from Windows 10 development may be priority for this project.

### Rationale and alternatives

In the meantime, I'll keep forging ahead with the UWP classes or switch to C++/WinRT to make use of the Windows App SDK and WinUI 3. However, I really would like to learn Rust and as I get better with the language, I will look for opportunities to maybe contribute back to this effort.

### Additional context

Thank you for all that you do for Rust support for Windows!

**Comment by riverar** [comment]
Hi @JLunda,

There are no plans to support UWP XAML or WinUI XAML at this time.

See also:
https://github.com/microsoft/windows-app-rs#this-repository-has-been-archived
https://github.com/microsoft/windows-rs/issues/1818#issuecomment-1155313081
https://github.com/microsoft/windows-rs/pull/1836
