### ISSUE TITLE
Bug: Issue with using `LookupAccountSidLocalW`

### ISSUE THREAD

**Issue by Icxolu** [microsoft/windows-rs#2169]
### Which crate is this about?

windows

### Crate version

latest master

### Summary

While playing around with the windows api I noticed that `LookupAccountSidLocalW ` does not work as expected.

In a minimal example an executable is produced which crashes at runtime with `exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND`. This suggest to me that the function is not found where it was linked to. 

Furthermore by adding `crossterm = "0.25.0"` to the depencies (without actually adding any code using it) I get a linker error looking for an unresolved symbol `__imp_LookupAccountSidLocalW`

Using the very similar function `LookupAccountSidW` works as expected. So it seems something is wrong with the linking of `LookupAccountSidLocalW`.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc

active toolchain
----------------
stable-x86_64-pc-windows-msvc (default)
rustc 1.65.0 (897e37553 2022-11-02)

### Reproducible example

```rust
use windows::Win32::{Foundation::PSID, Security};

fn main() {
    let sid = PSID::default();
    let mut name_size: u32 = 256;
    let mut domain_size: u32 = 256;

    let mut name: Vec<u16> = vec![0; name_size as usize];
    let mut domain: Vec<u16> = vec![0; domain_size as usize];

    let mut peuse = Default::default();

    unsafe {
        Security::LookupAccountSidLocalW(
            sid,
            windows::core::PWSTR(name.as_mut_ptr()),
            &mut name_size,
            windows::core::PWSTR(domain.as_mut_ptr()),
            &mut domain_size,
            &mut peuse,
        )
    };
}
```

### Crate manifest

```toml
[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs", features = ["Win32_Security_Authorization", "Win32_Foundation", "Win32_System_Memory"] }
```

### Expected behavior

`LookupAccountSidLocalW` should work similar to `LookupAccountSidW`

### Actual behavior

`LookupAccountSidLocalW` crashes at runtime or produces a linker error.

**Comment by kennykerr** [comment]
This function was only very recently added here: #2166

If you sync with master (or delete your Cargo.lock) you should find it now links.

**Comment by Icxolu** [comment]
Yes, I saw it was only (very) recently added. Even with latest master (20438933dec35abe9edc0d2203cf9d3e5f6f100a) I get the behavior I described above.

**Comment by kennykerr** [comment]
I had a closer look, but I don't see a bug in the `windows-rs` definitions or libs. I do note that this function fails to load on my machine. Looking at dumpbin, it doesn't appear to be exported from `ADVAPI32.dll` as the metadata and docs suggest. 

https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lookupaccountsidlocalw

**Comment by kennykerr** [comment]
It looks like `LookupAccountSidLocalW` is exported from `sechost.dll`, not `advapi32.dll`, so either the docs are wrong or this function moved, which would be a breaking change. It looks like this was also manually [added to the metadata](https://github.com/microsoft/win32metadata/issues/950), but that doesn't appear to be correct either. 

I'm hoping someone smart like @jonwis or @oldnewthing knows what's going on. 😬

**Comment by riverar** [comment]
For what it's worth, I spot checked OSes all the back to Windows XP and this function does not appear to have ever been in advapi32. It appears to have first appeared in sechost on Windows 7. Probably a documentation bug.

**Comment by kennykerr** [comment]
That's good news, in which case we should be able to simply update the metadata (@mikebattista) and the fix will flow back into `windows-rs` automatically where new libs will be generated. cc @stevewhims for the doc bug.

**Comment by mikebattista** [comment]
Ok. I will update to sechost. Thanks for confirming @riverar.

**Comment by oldnewthing** [comment]
No, don't update to sechost. There is no sechost.lib.

The answer is that it's a macro. There is no function.

The title should be

# LookupAccountSidLocalW macro (winbase.h)

> LookupAccountSidLocal is defined as a macro that calls LookupAccountSid with NULL as the first parameter.

**Comment by kennykerr** [comment]
Thanks Raymond, in that case @mikebattista you should probably just remove them as the metadata does not include such macros.

**Comment by mikebattista** [comment]
The header is below. It says for recent OSes, the functions are no longer macros. Are the headers wrong too?

```
#if _WIN32_WINNT >= 0x0601

WINADVAPI
_Success_(return != FALSE) BOOL
WINAPI
LookupAccountNameLocalA(
    _In_     LPCSTR lpAccountName,
    _Out_writes_bytes_to_opt_(*cbSid, *cbSid) PSID Sid,
    _Inout_  LPDWORD cbSid,
    _Out_writes_to_opt_(*cchReferencedDomainName, *cchReferencedDomainName + 1) LPSTR ReferencedDomainName,
    _Inout_  LPDWORD cchReferencedDomainName,
    _Out_    PSID_NAME_USE peUse
    );
WINADVAPI
_Success_(return != FALSE) BOOL
WINAPI
LookupAccountNameLocalW(
    _In_     LPCWSTR lpAccountName,
    _Out_writes_bytes_to_opt_(*cbSid, *cbSid) PSID Sid,
    _Inout_  LPDWORD cbSid,
    _Out_writes_to_opt_(*cchReferencedDomainName, *cchReferencedDomainName + 1) LPWSTR ReferencedDomainName,
    _Inout_  LPDWORD cchReferencedDomainName,
    _Out_    PSID_NAME_USE peUse
    );
#ifdef UNICODE
#define LookupAccountNameLocal  LookupAccountNameLocalW
#else
#define LookupAccountNameLocal  LookupAccountNameLocalA
#endif // !UNICODE

WINADVAPI
_Success_(return != FALSE) BOOL
WINAPI
LookupAccountSidLocalA(
    _In_ PSID Sid,
    _Out_writes_to_opt_(*cchName, *cchName + 1) LPSTR Name,
    _Inout_  LPDWORD cchName,
    _Out_writes_to_opt_(*cchReferencedDomainName, *cchReferencedDomainName + 1) LPSTR ReferencedDomainName,
    _Inout_ LPDWORD cchReferencedDomainName,
    _Out_ PSID_NAME_USE peUse
    );
WINADVAPI
_Success_(return != FALSE) BOOL
WINAPI
LookupAccountSidLocalW(
    _In_ PSID Sid,
    _Out_writes_to_opt_(*cchName, *cchName + 1) LPWSTR Name,
    _Inout_  LPDWORD cchName,
    _Out_writes_to_opt_(*cchReferencedDomainName, *cchReferencedDomainName + 1) LPWSTR ReferencedDomainName,
    _Inout_ LPDWORD cchReferencedDomainName,
    _Out_ PSID_NAME_USE peUse
    );
#ifdef UNICODE
#define LookupAccountSidLocal  LookupAccountSidLocalW
#else
#define LookupAccountSidLocal  LookupAccountSidLocalA
#endif // !UNICODE

#else // _WIN32_WINNT >= 0x0601

#define LookupAccountNameLocalA(n, s, cs, d, cd, u) \
    LookupAccountNameA(NULL, n, s, cs, d, cd, u)
#define LookupAccountNameLocalW(n, s, cs, d, cd, u) \
    LookupAccountNameW(NULL, n, s, cs, d, cd, u)
#ifdef UNICODE
#define LookupAccountNameLocal  LookupAccountNameLocalW
#else
#define LookupAccountNameLocal  LookupAccountNameLocalA
#endif // !UNICODE

#define LookupAccountSidLocalA(s, n, cn, d, cd, u)  \
    LookupAccountSidA(NULL, s, n, cn, d, cd, u)
#define LookupAccountSidLocalW(s, n, cn, d, cd, u)  \
    LookupAccountSidW(NULL, s, n, cn, d, cd, u)
#ifdef UNICODE
#define LookupAccountSidLocal  LookupAccountSidLocalW
#else
#define LookupAccountSidLocal  LookupAccountSidLocalA
#endif // !UNICODE

#endif // _WIN32_WINNT >= 0x0601
```

**Comment by riverar** [comment]
Hm. @oldnewthing I'm seeing usage of this API in advapi32!LookupAccountName, brought in via api-ms-win-security-lsalookup-l1-1-0.dll on Windows 11 (which eventually lands in sechost.dll it appears).

sechost.dll!LookupAccountSidLocalW is exported and wraps LookupAccountSidInternal.

**Comment by kennykerr** [comment]
The function may exist, but the Windows SDK does not ship with a valid lib to call it and the docs are wrong. I also checked and the macro is consistent with the behavior of the function, so I think the most reliable path forward is to just consider it a macro and forget that the function exists.

**Comment by Icxolu** [comment]
Wow, thanks everyone for figuring this out!

>  I don't have a valid workaround for developers that want local-only resolution behavior at this time.

Thats unfortunate but at least I know now why things were not working as expected.

**Comment by mikebattista** [comment]
I've removed these functions from the metadata.

**Comment by stevewhims** [comment]
[...] @stevewhims for the doc bug.

For the doc bug, I've changed the dll to sechost.dll, and left the lib blank. That's for the A and W variants of the APIs. If that's not right, lemme know. :)

Thanks!
-Steve

**Comment by riverar** [comment]
@stevewhims We concluded sechost.dll was not correct either; it should really just be cut from the docs.

**Comment by stevewhims** [comment]
> rrect either; it should really just be cut from the d

Thanks, @riverar! :)
