### ISSUE TITLE
clippy::forget_copy and clippy::derivable_impls from generated binding files with windows_binde

### ISSUE THREAD

**Issue by hmyan90** [microsoft/windows-rs#2170]
### Which crate is this about?

windows

### Crate version

0.43.0

### Summary

repro:
Author some WinRT interface with an IDL file which has some enum defined, e.g 
```
    [flags] enum DownloaderAddDevicesDisposition {
        Ok = 0x00000000,
    };

```
use windows_bindgen to generate binding file, the generated file will raise some clippy warning for 
```
645 | / impl ::core::default::Default for DownloaderAddDevicesDisposition {
646 | |     fn default() -> Self {
647 | |         Self(0)
648 | |     }
649 | | }
    | |_^
    |
    = note: `#[warn(clippy::derivable_impls)]` on by default
    = help: try annotating `UdiApi::DownloaderAddDevicesDisposition` with `#[derive(Default)]`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
```
and

```
3297 |                     ::core::mem::forget(ok__);
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
     |
note: argument has type `UdiApi::DownloaderAddDevicesDisposition`
    --> udi-api\src\UdiApi.rs:3297:41
     |
3297 |                     ::core::mem::forget(ok__);
     |                                         ^^^^
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#forget_copy

error: calls to `std::mem::forget` with a value that implements `Copy`. Forgetting a copy leaves the original intact
```

I saw a similar issue solved for win32 interface https://github.com/microsoft/windows-rs/issues/1184 , Please also fix for self-authored interfaces, Thanks!

### Expected behavior

Generated rust code should be compliant with clippy.

**Comment by kennykerr** [comment]
Right now, it depends on the consumer of the bindings to suppress any warnings like `non_snake_case`, `non_upper_case_globals`, `non_camel_case_types`, that necessarily need to be allowed. This is what the `windows` and `windows-sys` crates do. 

But I can see how that can be a little unmanageable and will look into suppressing the warnings from within the generated code, especially the `clippy` ones that are also intentional.

**Comment by kennykerr** [comment]
@hmyan90 I want to make sure I get this right, but I can't quite repro the warning you're seeing. Do you have a minimal repro you can share?
