### ISSUE TITLE
Question: XAML bindgen?

### ISSUE THREAD

**Issue by alexculea** [microsoft/windows-rs#2176]
I'm working on a small project using the XAML namespace imperatively to setup a minimalist UI and would like to update the windows-rs dependency to the latest version. As XAML has been removed form the `windows` crate, some ideas were floating around that one could use the `.winmd` and the `bindgen` crate to generate the bindings (I'm aware of `windows-sys` but would rather not go that route for now).

I was able to generate the namespace by following the existing examples of generation from this repo however the tooling seems to assume I am trying to generate the windows-rs crate as the generated modules within the XAML namespace will attempt to import from `super::super::super`. 

Is it possible to continue using `windows-rs` for the rest of the namespaces while also making the XAML namespace to reference the `windows` crate instead of itself?

**Comment by riverar** [comment]
Hey @alexculea, I wouldn't waste your time to be honest. This is not something that will yield fruit. (I went down this road for the Windows App SDK @ https://github.com/microsoft/windows-app-rs.) XAML is too heavily tied to .NET and Visual Studio to be practically usable with Rust and other languages and toolchains.

The API crate in https://github.com/microsoft/windows-app-rs [has a bindgen flag for this scenario](https://github.com/microsoft/windows-app-rs/blob/master/crates/tools/api/src/main.rs#L187) but I think we recently removed that flag from the bindgen crate when we archived that project.

Will close this for now, but feel free to keep the discussion going if needed!

**Comment by alexculea** [comment]
Thanks for the swift response @riverar.

While the XAML coupling situation is understandable, would there be any desire to reintroduce the `windows_extern` flag? Seems like this could be very useful for consuming other APIs without regenerating the APIs already covered by the `windows` crate.

**Comment by kennykerr** [comment]
That is something we are exploring.
