### ISSUE TITLE
Bug: In D3D demo

### ISSUE THREAD

**Issue by zhouhang95** [microsoft/windows-rs#2180]
### Which crate is this about?

other (please share in the comments)

### Summary

```
    // Copy the triangle data to the vertex buffer.
    unsafe {
        let mut data = std::ptr::null_mut();
        vertex_buffer.Map(0, None, Some(&mut data))?;
        std::ptr::copy_nonoverlapping(
            vertices.as_ptr(),
            data as *mut Vertex,
            std::mem::size_of_val(&vertices),
        );
        vertex_buffer.Unmap(0, None);
    }
```
->
```
    // Copy the triangle data to the vertex buffer.
    unsafe {
        let mut data = std::ptr::null_mut();
        vertex_buffer.Map(0, None, Some(&mut data))?;
        std::ptr::copy_nonoverlapping(
            vertices.as_ptr(),
            data as *mut Vertex,
            vertices.len(),
        );
        vertex_buffer.Unmap(0, None);
    }
```
pub const unsafe fn copy_nonoverlapping<T>(src: *const T, dst: *mut T, count: usize)
Copies count * size_of::<T>() bytes from src to dst.

**Comment by zhouhang95** [comment]
std::mem::size_of_val(&vertices) == 84
vertices.len() == 3

**Comment by kennykerr** [comment]
@damyanp

**Comment by riverar** [comment]
@zhouhang95 It's a holiday here in the US starting tomorrow, so you may not receive a response until Monday. Can you also provide a small complete sample that I can run here? Thank you! / 从明天开始，这是美国的假期，所以你可能要到周一才能收到回复。您能否提供我可以在这里运行的小型完整示例？谢谢！

**Comment by zhouhang95** [comment]
> @zhouhang95 It's a holiday here in the US starting tomorrow, so you may not receive a response until Monday. Can you also provide a small complete sample that I can run here? Thank you! / 从明天开始，这是美国的假期，所以你可能要到周一才能收到回复。您能否提供我可以在这里运行的小型完整示例？谢谢！

Hello,
the total code is in crates/samples/direct3d12 demo.

**Comment by kennykerr** [comment]
Is the sample misbehaving? It seems to work fine for me. Unfortunately, I have no idea what that code is trying to do as I'm not familiar with Direct3D, but perhaps @damyanp can confirm that it is correct.

**Comment by zhouhang95** [comment]
Yes.
It copy more data than it need.
memcpy thrid param is count of byte.
std::ptr::copy_nonoverlapping thrid param is count of array len.

**Comment by damyanp** [comment]
Yup, I agree that it looks incorrect. The proposed fix looks good to me.  I'm getting my dev environment back up and running and could have a look at putting a PR together if nobody else gets to it first.
