### ISSUE TITLE
Bug: parsing target 'aarch64-pc-windows-gnullvm' failed: unknown target triple: aarch64-pc-windows-gnullvm

### ISSUE THREAD

**Issue by jmfiaschi** [microsoft/windows-rs#2181]
### Which crate is this about?

windows-sys

### Crate version

0.42

### Summary

Hello, 

I'm using `semantic-release-rust` and it check the dependancy graph during the verify condition phase. During the check, this error is raised

```
Unable to build workspace dependencies graph: Unable to parse the workspace structure starting at *******\Cargo.toml
Error: Unable to parse the workspace structure starting at ******\Cargo.toml

Caused by:
    Error while computing package graph: for package 'windows-sys 0.42.0 (registry+https://github.com/rust-lang/crates.io-index)': for dependency 'windows_aarch64_gnullvm', parsing target 'aarch64-pc-windows-gnullvm' failed: unknown target triple: aarch64-pc-windows-gnullvm
```

Example of the error : https://github.com/jmfiaschi/chewdata/actions/runs/3536503428/jobs/5935913967#step:5:43

do you have any idea ? thx

### Toolchain version/configuration

Same error in local:

Default host: x86_64-pc-windows-msvc
rustup home:  *******\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

x86_64-apple-darwin
x86_64-pc-windows-gnu

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.65.0 (897e37553 2022-11-02)

**Comment by kennykerr** [comment]
I'm not familiar with `semantic-release-rust` or what it's trying to do. I will note that `aarch64-pc-windows-gnullvm` is a tier 3 target so perhaps that tool doesn't yet support it. 

https://doc.rust-lang.org/rustc/platform-support/pc-windows-gnullvm.html

**Comment by jmfiaschi** [comment]
Finally I removed `semantic-release-rust` and use the standard rust cli command to to the same thing. Thank you for your feedback, I close the issue

**Comment by EricCrosson** [comment]
@jmfiaschi, do you happen to have an example of using the rust cli with semantic-release instead of semantic-release-rust?

**Comment by jmfiaschi** [comment]
Yes, I use `cargo-edit` in order to setup the version of my Cargo.toml and you need this : 

- Use cargo command in releaserc.json: https://github.com/jmfiaschi/chewdata/blob/beta/.releaserc.json#L16-L38
- Create a step to setup semantic release in your CI and run it : https://github.com/jmfiaschi/chewdata/blob/beta/.github/workflows/ci.yml#L119-L130

If it could help you

**Comment by EricCrosson** [comment]
Great! Thank you for the pointers :pray:
