### ISSUE TITLE
Bug: Devices_Midi: Midi(In|Out)Port::FromIdAsync return inconsistent types (MidiInPort vs IMidiOutPort)

### ISSUE THREAD

**Issue by Paul-Dempsey** [microsoft/windows-rs#2182]
### Which crate is this about?

windows

### Crate version

version = "0.43.0"

### Summary

MidiInPort::FromIdAsync returns a result-wrapped MidiInport, whereas MidiOutPort returns a result-wrapped *I*MidiOutPort.

Is this just an annoying inconsistency (I\* vs. no `I` prefix), or is there something more subtle/meaningful in that I'm missing?

```rust
// MidiInPort::
pub fn FromIdAsync(deviceid: &::windows::core::HSTRING) -> ::windows::core::Result<super::super::Foundation::IAsyncOperation<MidiInPort>>

// MidiOutPort::
pub fn FromIdAsync(deviceid: &::windows::core::HSTRING) -> ::windows::core::Result<super::super::Foundation::IAsyncOperation<IMidiOutPort>> {

```

### Toolchain version/configuration

stable-x86_64-pc-windows-msvc (default)
rustc 1.65.0 (897e37553 2022-11-02)

### Crate manifest

```toml
[dependencies.windows]
version = "0.43.0"
features = [
    "Devices_Midi",
    "Devices_Enumeration",
    "Foundation_Collections",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Devices_Enumeration",
]
```

### Expected behavior

Consistent naming of objects/interfaces.

**Comment by kennykerr** [comment]
The bindings are generated from metadata, and I can confirm the discrepancy between these two methods in the metadata. I'm not familiar with this API, so I can't comment on why it is the way it is. Have you read the docs? Perhaps there's a clue. Anyway, here's a more appropriate forum for API questions:

https://docs.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by Paul-Dempsey** [comment]
Thanks! - I was wondering where there's a better place for Q&A. I'll post a suggestion that this should be mentioned as a resource on the [https://learn.microsoft.com/en-us/windows/dev-environment/rust/rust-for-windows or](https://learn.microsoft.com/en-us/windows/dev-environment/rust/) pages.  (although I've never found the Answers site to be terribly accurate or useful). I have been reading the docs, but since they don't cover Rust and all the samples are C# UWP apps using XAML, which has been abandoned for Rust, it's challenging to figure out usage.
