### ISSUE TITLE
Why is there no `windows-sys` support for calling COM interfaces?

### ISSUE THREAD

**Issue by suleyth** [microsoft/windows-rs#2187]
Heyo, the FAQ says that "the `windows-sys` crate only includes declarations and COM and WinRT calls are far too cumbersome without the abstractions provided by the `windows` crate."

I can sort of understand that for WinRT, or for declaring/implementing COM interfaces... but is it really that cumbersome to simply call a pre-implemented interface?

I was actually able to bind to one using `windows_sys`, it just requires a lot of boilerplate:
```rs
#[allow(non_snake_case)]
struct IDirect3D9Vtbl {
    // IUnknown methods
    QueryInterface: unsafe extern "system" fn(*mut IDirect3D9, *const GUID, *mut *mut c_void) -> HRESULT,
    AddRef: unsafe extern "system" fn (*mut IDirect3D9) -> u32,
    Release: unsafe extern "system" fn (*mut IDirect3D9) -> u32,
    // IDirect3D9 methods
    RegisterSoftwareDevice: unsafe extern "system" fn(*mut IDirect3D9, *mut c_void) -> HRESULT,
    // etc..... <snip>
}

pub struct IDirect3D9 {
    vtbl: *const IDirect3D9Vtbl
}

#[allow(non_snake_case)]
impl IDirect3D9 {
    // IUnknown methods
    pub unsafe fn QueryInterface(&mut self, a: *const GUID, b: *mut *mut c_void) -> HRESULT { ((*self.vtbl).QueryInterface)(self as *mut _, a, b) }
    pub unsafe fn AddRef(&mut self) -> u32 { ((*self.vtbl).AddRef)(self as *mut _) }
    pub unsafe fn Release(&mut self) -> u32 { ((*self.vtbl).Release)(self as *mut _) }
    // IDirect3D9 methods
    pub unsafe fn RegisterSoftwareDevice(&mut self, a: *mut c_void) -> HRESULT {
        ((*self.vtbl).RegisterSoftwareDevice)(self as *mut _, a)
    }
    // etc..... <snip>
}
```
And then:
```rs
    use windows_sys::Win32::Graphics::Direct3D9::*;
    let d3d = unsafe { Direct3DCreate9(D3D_SDK_VERSION) } as *mut crate::d3d9_interfaces::IDirect3D9;
    let mut pp = unsafe { D3DPRESENT_PARAMETERS { /* etc.... <snip> */ } };
    let mut device: IDirect3DDevice9 = core::ptr::null_mut();
    unsafe { (*d3d).CreateDevice( /* etc... <snip> */ &mut pp); }
    let mut device = device as *mut crate::d3d9_interfaces::IDirect3DDevice9;
```

So my question is, wouldn't it be possible to simply generate code like the above for `windows_sys`? Given that using `windows_sys` is completely opt-in and a choice the developer makes consciously, having to do `(*interface).Method()` doesn't seem to me like a sacrifice enough to not support it alltogether. Especially because said developer can just call `.as_mut().unwrap()` to be able to do `interface.Method()` normally (I tested that this works in the code I showed)

Or is there another reason I'm missing? Feel free to close this if I am, just asking.

**Comment by kennykerr** [comment]
Good question! The `windows-sys` crate was born out of the realization that the most expensive aspect of the `windows` crate, in terms of build time, is the cost of compiling function bodies. The Rust compiler just spends a great deal of effort compiling function bodies, so a version of the `windows` crate that only includes declarations is both much smaller and faster by comparison. The trouble is that COM-style virtual function calls require extra code gen in Rust (unlike C++) and this in turn leads to slower compile times. And as soon as you add COM support, it becomes very tempting to add minor conveniences and things like implementation support or derived interfaces and before you know it, it looks a lot more like the `windows` crate. 

So, I'd prefer to focus on making the `windows` crate smaller and compile faster - making it more like the `windows-sys` crate - rather than the other way around. Hope that helps.

**Comment by suleyth** [comment]
I sorta understand that, but isn't that what separating the modules into specific features was for? The slow compile times would only be an issue if I tell the crate to compile a module with COM support to begin with, like in my example `"Win32_Graphics_Direct3D9"`. If I don't, then there's no reason why the crate would compile any slower, it wouldn't be generating any COM code. Even if it would, you could just add a `"no-com"` feature to make absolutely sure that the developer is not paying the build time cost for something they don't need.

As for it becoming very tempting to add any abstractions, well... there's no need to. If someone's using `windows-sys` it's specifically because they don't want them. So I don't see any issues with just generating a pointer to a vtable like in the code above. I actually did exactly that, I parsed the `d3d9.h` header and looped through all the interfaces to generate bindings.

**Comment by kennykerr** [comment]
So why not use the `windows` crate that does all of this?

**Comment by suleyth** [comment]
Because `windows_sys` is the only one that provides `no_std` support. I could use the old `winapi` one, but it's way harder to use and navigate through

**Comment by suleyth** [comment]
Well, if there's anything I could help with to make the `windows` crate support `no_std` again, I can try my best! I suppose my question is answered so I'm gonna close the issue, thank you!

**Comment by Muon** [comment]
@kennykerr Is generating the extra glue strictly necessary? Would it be possible to generate just the vtables for `windows-sys`? I know it's inconvenient to call them, but it would make it possible to make COM calls in a no-std environment.

**Comment by kennykerr** [comment]
@Muon it would be simpler just to support `no_std` via the `windows` crate. If that is desirable, please open an issue and include a motivation. I have yet to hear a compelling reason but I'm happy to discuss.
