### ISSUE TITLE
Feature request: MicaController for UI::Composition

### ISSUE THREAD

**Issue by paulober** [microsoft/windows-rs#2189]
### Motivation

The microsoft docs state that you can use the new Windows 11 Mica Materiall also with Win32 or WinRT apps thoght the MicaController which is not currently available in the windows crate.

**Comment by riverar** [comment]
Unfortunately, `MicaController` is a class offered by Windows App SDK, something this crate doesn't directly support
https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.systembackdrops.micacontroller?view=windows-app-sdk-1.2

Will leave this open to get you an alternative working solution using `DwmSetWindowAttribute` and others.

**Comment by kennykerr** [comment]
@robmikh is this possible with only OS APIs, `DwmSetWindowAttribute` and `Windows.UI.Composition` for example?

**Comment by robmikh** [comment]
Yes, it should be possible to recreate the MicaController using public APIs.

The most difficult part, however, will be the effect descriptions. We never shipped system implementations and leaned on Win2D. You can either implement the effect descriptions yourself or generate bindings for Win2D.

**Comment by riverar** [comment]
@paulober Yup that's a common one. Check out https://github.com/microsoft/windows-rs/issues/1110#issuecomment-1326139058 for a common pattern.

**Comment by paulober** [comment]
> @paulober Yup that's a common one. Check out [#1110 (comment)](https://github.com/microsoft/windows-rs/issues/1110#issuecomment-1326139058) for a common pattern.

Thanks again. I think this should work until windows-rs provides a more straightforward approach to this problem.
