### ISSUE TITLE
Feature request: Add license files to target-specific crates

### ISSUE THREAD

**Issue by ankane** [microsoft/windows-rs#2204]
### Motivation

Hi, it would be nice to include the license files in the target-specific crates (`windows_x86_64_msvc`, `windows_x86_64_gnu`, etc) for the same reasoning as mentioned in https://github.com/microsoft/windows-rs/issues/1587#issuecomment-1063010186.

### Drawbacks

None

**Comment by kennykerr** [comment]
Can do!

**Comment by kennykerr** [comment]
The new license tool will take care of keeping all of the crates up to date. #2207

**Comment by ankane** [comment]
Awesome, that was super fast - thanks @kennykerr!
