### ISSUE TITLE
RAII type for HANDLES?

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#2222]
Is there an RAII type for HANDLEs that'll call CloseHandle when dropped?  As far as I can tell the current HANDLE requires an explicit call to CloseHandle.

**Comment by kennykerr** [comment]
No. The Win32 metadata, which defines `HANDLE`, doesn't have a reliable way to express ownership semantics. As you know, there are many uses of `HANDLE`, sometimes with different ways to free the handle, sometimes it is merely borrowed, sometimes representing a psuedo handle, etc. Ideally, the metadata would indicate such semantics on functions like `CreateEventW` to indicate what to do with the resulting handle.

**Comment by damyanp** [comment]
Ok, good to know I wasn't missing something.  Has this already been discussed? Is this in scope for v1.0?

**Comment by kennykerr** [comment]
Ideally, the Win32 metadata can get improved support for ownership semantics. @riverar and I have discussed this at some length. He may have some thoughts as well. But I probably have to come up with some way to infer lifetime/ownership. 

This is a general problem, particularly challenging with DirectX APIs where there are structs with COM interface pointer fields and it's not always clear who owns what.

**Comment by riverar** [comment]
Metadata has quite a bit of work ahead of it to make this work, or at least get it into a state where we can start experimentation.

For example, we're still tossing around candidates for how these attributes look https://github.com/microsoft/win32metadata/issues/389. And we haven't nailed down a fix for free functions with multiple parameters https://github.com/microsoft/win32metadata/issues/423. Or how to deal with functions that return either freeable and non-freeable resources based on other inputs https://github.com/microsoft/win32metadata/issues/423#issuecomment-860187551.

**Comment by damyanp** [comment]
It seems that there are several different problems some of affecting legacy APIs while others are affecting more modern ones.  Is the idea to fix all at once, or can these be prioritized at all?

The D3D APIs I think should be pretty trivial - the COM pointers in D3D12 structs are all weak references.

**Comment by Chaoses-Ib** [comment]
Here is a simple OwnedHandle:
```rust
use windows::Win32::Foundation::{HANDLE, CloseHandle};

/// You should only use this wrapper if the handle can be closed by `CloseHandle`.
#[derive(PartialEq, Eq, Clone, Copy, Debug)]
pub struct OwnedHandle(pub HANDLE);

impl From<HANDLE> for OwnedHandle {
    fn from(handle: HANDLE) -> Self {
        Self(handle)
    }
}

impl Drop for OwnedHandle {
    fn drop(&mut self) {
        unsafe { CloseHandle(self.0) };
    }
}
```

**Comment by MarijnS95** [comment]
@Chaoses-Ib (and @Nerixyz, #3638) there is already a **stabilized** Rust type that encapsulates `HANDLE` and calls `CloseHandle()` on `drop()`: https://doc.rust-lang.org/stable/std/os/windows/io/struct.OwnedHandle.html

While it currently seems to be impossible for `windows-rs` to know when ownership transfer occurs (see above: the metadata doesn't describe this), perhaps it could at least implement some of these `std` traits such as `AsHandle` and `AsRawHandle`, and maybe an `fn into_owned_handle(self) -> OwnedHandle`?

**Comment by riverar** [comment]
Don't think we have any plans to adopt those `std` traits. Opinion: At a glance, the handle work there looks very brittle and naive.

**Comment by MarijnS95** [comment]
@riverar perhaps it is worth to voice your concerns (if you haven't already done so) upstream?

**Comment by kennykerr** [comment]
See #3013 for a solution.
