### ISSUE TITLE
use core::* should not change std::result::Result<T, E>

### ISSUE THREAD

**Issue by Mazwak** [microsoft/windows-rs#2225]
As of 0.43.0, when I "use core::*", it redefines std::result::Result<T, E> to windows::core::Result<T>.

https://github.com/microsoft/windows-rs/blob/19bd15532c21c098a520d1caa9921d98805405ac/crates/libs/windows/src/core/mod.rs#L68

I think std::result::Result is a core functionnality of Rust, and it should not be overwritten by anything, unless it is obvious it will change Result.
Like, eg, "use hresult::Result".

Not writing "use core::*" seems impossible, as it does a lot of thing.

**Comment by ChrisDenton** [comment]
> Not writing "use core::*" seems impossible, as it does a lot of thing.

I think that's a bit hyperbolic. `use std::io::*` has the [exact same issue](https://doc.rust-lang.org/std/io/type.Result.html) yet most people seem to manage without it. Could you say more about why you do this? If it's just for the trait methods then `use core::{Vtable, Interface};` would work better. If it's for particular types then importing them as needed should not be too much of a hassle?

In general, importing using `*` is rarely a good idea unless the module is specially designed for it. If this is something windows-rs wants to support then it should be a separate `prelude` module that has a more limited set of things.

**Comment by Mazwak** [comment]
My apologies, I missed a few points before reporting.

I’m trying to show a simple message dialog.

Samples use 'core::*'.
https://github.com/microsoft/windows-rs/blob/master/crates/samples/message_box/src/main.rs

If I remove 'core::*', it is not obvious what I should add. Mostly because now, it errors on something completly unrelated : I use 'master' sample, and not '0.43.0' one.

The notice to use examples to the specific version you are using should be put into every sample 'main.rs' in my opinion.
And next to the link, something like : beware, samples are for master branch, not latest release

My second point is I thought that using 'core::*' was the way to go as most (all?) samples do that.
For the message box sample, it only needs s, w and h macros.

It would be nice to only 'use' what is strictly needed in the examples.

I’m not sure if a prelude would be usefull or not.

**Comment by kennykerr** [comment]
I should probably just update the link on the readme to point to the samples for the latest published version. That way, if you click on the link on crates.io you'll always get the relevant samples.

**Comment by kennykerr** [comment]
#2226 for the samples link - that should at least help for the next published version of `windows` and `windows-sys`. 

Regarding samples and `use`, feel free to contribute improvements. I just tend to try and write the samples in the most concise manner possible to avoid distracting with unrelated details.
