### ISSUE TITLE
PartialEq implementation for structs with padding shouldn't use memcmp?

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#2229]
I'm unsure if this is by design or not, but windows-bindgen 0.43.0 has generated a struct that looks like this:

```rust
#[repr(C)]
pub struct DSTORAGE_REQUEST_OPTIONS {
    pub _bitfield1: u8,
    pub _bitfield2: u64,
}
```
This struct has 3 bytes of padding between _bitfield1 and _bitfield2.

The implementation of PartialEq is:

```rust
impl ::core::cmp::PartialEq for DSTORAGE_REQUEST_OPTIONS {
    fn eq(&self, other: &Self) -> bool {
        unsafe {
            ::windows::core::memcmp(
                self as *const _ as _,
                other as *const _ as _,
                core::mem::size_of::<DSTORAGE_REQUEST_OPTIONS>(),
            ) == 0
        }
    }
}
```

This means that test code like this fails:

```rust
    #[test]
    fn sanity_test() {
        use microsoft_directstorage::DSTORAGE_REQUEST_OPTIONS;

        let x = DSTORAGE_REQUEST_OPTIONS {
            _bitfield1: 0,
            _bitfield2: 0,
        };

        let y = DSTORAGE_REQUEST_OPTIONS {
            _bitfield1: 0,
            _bitfield2: 0,
        };

        assert_eq!(x, y);
    }
```

```
thread 'tests::sanity_test' panicked at 'assertion failed: `(left == right)`
  left: `DSTORAGE_REQUEST_OPTIONS { _bitfield1: 0, _bitfield2: 0 }`,
 right: `DSTORAGE_REQUEST_OPTIONS { _bitfield1: 0, _bitfield2: 0 }`', examples\src\bin\hello-directstorage.rs:238:9
```

**Comment by kennykerr** [comment]
I fixed this here: #2168

**Comment by damyanp** [comment]
Awesome!  Do you know how far away this is from being in a release?

**Comment by kennykerr** [comment]
Releases are now on-demand: https://github.com/microsoft/windows-rs/issues/2156#issuecomment-1323816991

As Rafael points out, best to use a git dependency until you've worked out any kinks and are ready to go. 

Once you're fairly confident that `windows-rs` provides the fixes you need, I'm happy to publish another release.

**Comment by damyanp** [comment]
Thanks guys - I've switched to the latest git version and this is indeed working for me now.
