### ISSUE TITLE
Docs: h! macro page is missing (404)

### ISSUE THREAD

**Issue by Paul-Dempsey** [microsoft/windows-rs#2231]
Go to the windows-rs docs: https://microsoft.github.io/windows-docs-rs/doc/windows/index.html#macros

Click on the h macro, and get the 404 File Not Found page

**Comment by kennykerr** [comment]
Weird - maybe @riverar knows what happened to it?

**Comment by riverar** [comment]
Strange, will take a look. cargo didn't generate the page.

**Comment by kennykerr** [comment]
This seems to work:

`cargo doc -p windows --open`

**Comment by Paul-Dempsey** [comment]
yep -- I confirmed cargo doc works fine, but the published github.io pages are missing it.

**Comment by riverar** [comment]
The docs are generated via `cargo doc -p windows --all-features --no-deps --target-dir ...` and the `h!` page doesn't get generated. Might be some sort of bug with the use of `all-features` or `no-deps`?

**Comment by kennykerr** [comment]
Woot, thanks for the fix Rafael!
