### ISSUE TITLE
The `link` macro shows up in docs when it should be hidden 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#2232]
I'm not sure why...

https://github.com/microsoft/windows-rs/blob/cc4d50e44042a8fdec07981a44373dc0b1cf1673/crates/libs/windows/src/core/mod.rs#L156-L157

**Comment by ChrisDenton** [comment]
Do you also need ` #[doc(hidden)]` on the macro itself to fully hide it?

**Comment by kennykerr** [comment]
This is sufficient for the `interface_hierarchy` macro:

https://github.com/microsoft/windows-rs/blob/cc4d50e44042a8fdec07981a44373dc0b1cf1673/crates/libs/windows/src/core/mod.rs#L120-L121

The `link` macro is slightly different in the sense that `crate::` is required to avoid the ambiguity so your suggestion is probably the way to go - just a pity I need to hide each "overload".
