### ISSUE TITLE
Bug: Can't Use IDispatch with Interface

### ISSUE THREAD

**Issue by JamesMc86** [microsoft/windows-rs#2236]
### Which crate is this about?

windows

### Crate version

0.43.0

### Summary

I'm trying to call a component provided by a vendor which is .net component with COM visibility. In the IDL it is show as inheriting (or whatever the correct term is) from IDispatch i.e.

Interface VENDORINTERFACE: IDispatch

I'm using the interface macro to create the interface locally but:

1. If I use IUnknown as the base I get a lot of crashes. I guess this makes sense as the VTable will be off?
2. If I try to use IDispatch the system won't compile with the error "cannot find trait `IDispatch_Impl` in this scope"

I'm using the full COM namespace and have the following features enabled:

`windows = { version = "0.43", features = ["interface", "Win32_System_Com", "Win32_Foundation", "Win32_System_Ole"]}`

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\JamesMcNally\.rustup

installed toolchains
--------------------

stable-i686-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)
nightly-i686-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.65.0 (897e37553 2022-11-02)

### Reproducible example

```rust
use windows::core::{IUnknown, IUnknown_Vtbl, BSTR, GUID, HRESULT};
use windows::Win32::System::Com::*;

#[windows::core::interface("DA2B5D36-F15C-4484-9496-B0415CFE0C59")]
unsafe trait DataReader: IDispatch {
    fn OpenDataFile(&self, path: *const BSTR, flag: *mut VARIANT) -> HRESULT;
    fn CloseDataFile(&self) -> HRESULT;
  
}
```

### Crate manifest

```toml
windows = { version = "0.43", features = ["interface", "Win32_System_Com", "Win32_Foundation", "Win32_System_Ole"]
```

### Expected behavior

I expect to be able to compile and run a program that accesses the interface

### Actual behavior

It fails to compile with : IDispatch or crashes with access violations with : IUnknown

**Comment by kennykerr** [comment]
Hey, did you remember to include all necessary features? It looks like `IDispatch` requires:

* `Win32_Foundation`
* `Win32_System_Com`
* `Win32_System_Ole`

**Comment by kennykerr** [comment]
Oh, apologies I see you included those already in your repro. I think you're just missing `implement`. The distinction between `interface` and `implement` is a little confusing. I'll try get that cleaned up.

**Comment by JamesMc86** [comment]
Perfect, thats made my day! Added the implement feature and now it compiles and runs.

Now to work out the errors from inside the library!
