### ISSUE TITLE
Should storage types be Sync and Send?

### ISSUE THREAD

**Issue by mbartlett21** [microsoft/windows-rs#2256]
These is the actual types, not the interfaces, so I'm not sure whether they are meant to be Sync and Send or not.

- `Windows::Storage::StorageFolder`
- `Windows::Storage::StorageFile`

The main Microsoft documentation doesn't mention anything about threading:

- https://learn.microsoft.com/en-us/uwp/api/windows.storage.storagefolder?view=winrt-22621
- https://learn.microsoft.com/en-us/uwp/api/windows.storage.storagefolder?view=winrt-22621

**Comment by kennykerr** [comment]
These types are not marked as agile in metadata and thus won't be marked `Send` and `Sync` in Rust. You can use a tool like https://github.com/icsharpcode/ILSpy to view the [metadata found here](https://github.com/microsoft/windows-rs/tree/master/crates/libs/metadata/default).
