### ISSUE TITLE
Feature request: Win32 IEnumVARIANT iterator for collections

### ISSUE THREAD

**Issue by aquacash5** [microsoft/windows-rs#2260]
### Motivation

This makes it easier to iterate though Win32 collections (eg `INetFwRules`, `INetFwServices`, ...)

### Drawbacks

At the current time, it seems that the Windows projection does not mark what structs support this kind of operation, so it would be a manual process of determining which structures this can be implemented on.

### Rationale and alternatives

It could be implemented as a separate library, but it would mean that the implementation wont be-able to use the IntoIterator trait on the objects directly

### Additional context

I have created an iterator for this kind of object. I am using it to iterate over the INetFwRules.

```rust
pub struct IEnumIterator<T: Interface>(IEnumVARIANT, PhantomData<T>);

impl<T: Interface> IEnumIterator<T> {
    fn new(i_enum: IEnumVARIANT) -> IEnumIterator<T> {
        IEnumIterator(i_enum, PhantomData)
    }
}

impl<T: Interface> Iterator for IEnumIterator<T> {
    type Item = T;

    fn next(&mut self) -> Option<Self::Item> {
        unsafe {
            let mut c_fetched: u32 = u32::default();
            let mut var = VARIANT::default();
            self.0
                .Next(slice::from_mut(&mut var), &mut c_fetched)
                .ok()
                .ok()?;
            VariantChangeType(&mut var, &var, 0, VT_DISPATCH).ok()?;
            let dispatch = var.Anonymous.Anonymous.Anonymous.pdispVal.as_ref();
            dispatch.and_then(|d| d.cast().ok())
        }
    }
}
```

**Comment by kennykerr** [comment]
Seems like a reasonable addition but would require me to finally get to #539. 😊

**Comment by kennykerr** [comment]
And there are of course many COM interfaces that follow the `IEnumXxx` pattern that could be well served by an `Iterator` implementation. Ideally, any solution here would need to cover all or most of them generically.

**Comment by kennykerr** [comment]
Just reviewing this old issue - we now have first class support for `VARIANT` and `PROPVARIANT` in `windows-core` (#2786) but there isn't enough metadata to generally support iteration of `IEnumXxx` interfaces due to all of the unique or individual semantics from one enumeration interface to another and I'm reluctant to hand-author `Iterator` for each one in the `windows` crate as that doesn't scale.
