### ISSUE TITLE
Feature request: GetMessage should returns something other than BOOL

### ISSUE THREAD

**Issue by fortunewang** [microsoft/windows-rs#2262]
Crate version: 0.42.0

[GetMessageA](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagea#return-value) and [GetMessageW](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagew#return-value) could returns -1 for invalid hwnd.

In these cases, writing:
```rust
while GetMessageW(&mut msg, hwnd, filtermin, filtermax).as_bool() {
  // ...
}
```
would not break the loop.

Maybe the return type is `BOOL` for backward compatibility, but it is not boolean actually.
Consider retuning something like `i32` or `Result<bool>` instead.

**Comment by tim-weis** [comment]
There's not much value in that. `GetMessage` will not return a value of `-1` unless you are using a non-standard message pump (see [When will GetMessage return -1?](https://devblogs.microsoft.com/oldnewthing/20130322-00/?p=4873)). If you are using a non-standard message pump and you *are* filtering by window handle, then it's very likely that your code is wrong already (see [The dangers of filtering window messages](https://devblogs.microsoft.com/oldnewthing/20050209-00/?p=36493)).

In case you do need to call `GetMessage` in a way where it can (potentially) return a value of `-1`, then you can simply use the value wrapped by the [`BOOL`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.BOOL.html) return value (it's a public `i32`), so

```rust
while GetMessageW(&mut msg, hwnd, filtermin, filtermax).0 > 0 {
  // ...
}
```

As for why `GetMessage` returns a value of `BOOL`, that's what the Windows SDK headers use, which is translated into [metadata](https://github.com/microsoft/win32metadata), that's subsequently used by the `windows` crate to generate the Rust bindings.

**Comment by kennykerr** [comment]
Yep, `BOOL` is the correct type.
