### ISSUE TITLE
Clarify license of the Windows metadata files

### ISSUE THREAD

**Issue by alvinhochun** [microsoft/windows-rs#2266]
Hi @kennykerr, is it possible to clarify the license of the winmd files inside https://github.com/microsoft/windows-rs/tree/master/crates/libs/metadata/default? I understand them to be released under the same dual-license as the rest of the repo, but the readme indicates that the file originates from NuGet packages with the Windows SDK license. There is no explicit note that they have been relicensed here, which raises some doubts when open source projects want to consider using these files. Can something be added to the readme to clarify this?

**Comment by kennykerr** [comment]
Does this help? #2267

**Comment by alvinhochun** [comment]
Thanks! It looks good to me. I will have to wait and see if others have any comments though.
