### ISSUE TITLE
Fail to run on windows 7

### ISSUE THREAD

**Issue by jason-yau** [microsoft/windows-rs#2269]
Does this crate run on windows 7 operating system?
I received an error below.:
```bash
   Compiling windows_x86_64_msvc v0.42.0
   Compiling windows v0.43.0
   Compiling windows-rs-app v0.1.0 (E:\Projects\Rust\windows-rs-app)
    Finished dev [unoptimized + debuginfo] target(s) in 6.74s
     Running `target\debug\windows-rs-app.exe`
Error: Error { code: HRESULT(0x80040111), message: "ClassFactory cannot supply requested class" }
error: process didn't exit successfully: `target\debug\windows-rs-app.exe` (exit code: 1)
```
Your guidance on solving this problem is very much appreciated.

**Comment by Cinimajig** [comment]
It's more likely you're trying to use an interface or class, that is not supportet on Windows 7.

Where in your code is the ClassFactory error comming from?

**Comment by jason-yau** [comment]
> It's more likely you're trying to use an interface or class, that is not supportet on Windows 7.
> 
> Where in your code is the ClassFactory error comming from?

I just ran the example code of the crate. It looks like a dxgi.dll linking error.
My code:
```rust
use windows::{
    core::*, Data::Xml::Dom::*, Win32::Foundation::*, Win32::System::Threading::*,
    Win32::UI::WindowsAndMessaging::*,
};

fn main() -> Result<()> {
    let doc = XmlDocument::new()?;
    doc.LoadXml(h!("<html>hello world</html>"))?;

    let root = doc.DocumentElement()?;
    assert!(root.NodeName()? == "html");
    assert!(root.InnerText()? == "hello world");

    unsafe {
        let event = CreateEventW(None, true, false, None)?;
        SetEvent(event).ok()?;
        WaitForSingleObject(event, 0);
        CloseHandle(event).ok()?;

        MessageBoxA(None, s!("Ansi"), s!("Caption"), MB_OK);
        MessageBoxW(None, w!("Wide"), w!("Caption"), MB_OK);
    }

    Ok(())
}
```

**Comment by Nerixyz** [comment]
[The documentation for `XmlDocument`](https://learn.microsoft.com/uwp/api/windows.data.xml.dom.xmldocument?view=winrt-22621#windows-requirements) says that it was introduced in Windows 10. So you can't use it on Windows 7.

**Comment by kennykerr** [comment]
Right, it depends on the API you're attempting to use.
