### ISSUE TITLE
small 0.44 issue

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#2282]
I have a sample which had a static global h! window class string which I referenced from the usual RegisterClass() and CreateWindow() calls. I see that I have to revert to local w! strings now.

**Comment by kennykerr** [comment]
There were a few sharp edges in the earlier support for `HSTRING` to `PCWSTR` conversion that have been tightened up in this release. While you can still use an `HSTRING` and `h!`, if you don't actually need an `HSTRING` as in your example then it's just simpler to use `w!` and use the resulting `PCWSTR` instead. See #2239.

**Comment by MRahilly** [comment]
"const globals rather than static globals" Perfect.
