### ISSUE TITLE
Direct3D 11 in windows-rs 0.44 is unreasonably unwieldy to use.

### ISSUE THREAD

**Issue by chyyran** [microsoft/windows-rs#2283]
Just as an example, this is what creating a deferred context looked like in windows 0.43
```rust
// pub unsafe fn CreateDeferredContext(&self, contextflags: u32) -> Result<ID3D11DeviceContext>
let current_context = {
     unsafe { device.CreateDeferredContext(0)? }
}
```

In windows 0.44, APIs like it have signatures like

```rust
pub unsafe fn CreateDeferredContext(&self, contextflags: u32, ppdeferredcontext: Option<*mut Option<ID3D11DeviceContext>>) -> ::windows::core::Result<()>
```

So to use this API safely it looks like we have to do something like the following

```rust
let deferred_context = {
    let mut context = None;
    unsafe { device.CreateDeferredContext(0, context)? };
    
    // unwrap the option
    let Some(context) = context else {
        return Err(...)
    };
    
    // check aligned and not null (using pointer_is_aligned, alignment check optional)
    if !context.is_aligned() || context.is_null() {
        return Err(...)
    }
    
    // unwrap inner pointer
    let Some(context) = unsafe { context.read() } else {
        return Err(...)
    };
    context
}
```

**Comment by MarijnS95** [comment]
I don't think you have to check the returned pointer, you have to _give it_ a pointer (borrow that coerces) to the local storage for `ID3D11DeviceContext` which the function may optionally set to a valid object (`ID3D11DeviceContext` is/holds a pointer internally). So your call site looks somewhat like:

```rust
let mut context = None;
unsafe { device.CreateDeferredContext(0, Some(&mut context)) }.expect("CreateDeferredContext failed");
let context = context.expect("CreateDeferredContext succeeded but did not return a context");
```

https://learn.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11device-createdeferredcontext doesn't explain why that pointer can be optional, though.

**Comment by kennykerr** [comment]
The reason its optional is because the metadata says its optional:

```C#
unsafe HRESULT CreateDeferredContext([In] uint ContextFlags, [Optional][Out][ComOutPtr] ID3D11DeviceContext* ppDeferredContext);
```

My understanding is that you should be able to pass a null pointer to this API and it will tell you whether a deferred context can be created, like a capability check, but without actually burning the resources to create it. Previous versions of windows-rs didn't detect the `Optional` attribute and assumed it was always required. 

@MarijnS95 is right however, your code is needlessly complicated. If the call to `CreateDeferredContext` succeeds, you can simply `unwrap` the `Option` and will be succeed.

**Comment by MarijnS95** [comment]
I think the code isn't just needlessly complicated, if I understand the API correctly (it looks like many other COM functions that behave this way...) passing an initial `context = None` means you'll _always_ end up bailing out in `let Some(context) = context else { return Err(...) };`, e.g. the code doesn't behave as expected.

It however, as @kennykerr notes, is likely to help check for compatibility/possibility without creating the object in question (common pattern as well).

**Comment by chyyran** [comment]
I mistook the new signature to mean that the call would return a raw pointer to a `ID3D11DeviceContext`.

Would this be the correct way to use this API (and APIs like it) in 0.44 then?

```rust
let mut context = None;
unsafe { device.CreateDeferredContext(0, Some(&mut context))? };
context.unwrap()
```

**Comment by MarijnS95** [comment]
@chyyran Nope, it cannot return a raw pointer _through a function argument_ if you don't give it a mutable reference to a place to store it in the first place. And it's good to know that interface structs internally hold a COM pointer :)

Indeed, your code suggestion matches what I wrote above, that should work for your case.

**Comment by chyyran** [comment]
Thanks, while upgrading my code I seem to have found a projection bug in https://github.com/microsoft/windows-rs/issues/2286 as well so I'll close this.
