### ISSUE TITLE
Importing inferfaces for non-windows com components

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [microsoft/windows-rs#2285]
I am looking at connecting to an OPC Server via COM using windows-rs.

The OPC SDK provides IDL files along with generated .c and .h files. I'm trying to work out how to get all of the interfaces into rust code. For example, one of the interfaces:

```
[
	object,
	uuid(13486D50-4821-11D2-A494-3CB306C10000),
    // async_uuid(32E8D703-A335-4fc1-8F4B-663F505C7D62),
	pointer_default(unique)
]
interface IOPCServerList : IUnknown
{
    HRESULT EnumClassesOfCategories(
        [in]                       ULONG        cImplemented,
        [in,size_is(cImplemented)] CATID        rgcatidImpl[],
        [in]                       ULONG        cRequired,
        [in,size_is(cRequired)]    CATID        rgcatidReq[],
        [out]                      IEnumGUID ** ppenumClsid
    );

    HRESULT GetClassDetails(
        [in]  REFCLSID  clsid, 
        [out] LPOLESTR* ppszProgID, 
        [out] LPOLESTR* ppszUserType
    );

    HRESULT CLSIDFromProgID(
        [in]  LPCOLESTR szProgId, 
        [out] LPCLSID   clsid
    );
};
```

According to the windows-rs FAQ, it seems like I need to do something like:

```rust
#[windows::core::interface("13486D50-4821-11D2-A494-3CB306C10000")]
unsafe trait IOPCServerList: IUnknown {
    unsafe fn EnumClassesOfCategories(&self) -> windows::core::HRESULT;
    unsafe fn GetClassDetails(&self) -> windows::core::HRESULT;
    unsafe fn CLSIDFromProgID(&self) -> windows::core::HRESULT;
}
```

But I'm unsure about converting the C types to rust types for the parameters. Is there any docs or samples for this?

Also, is there anyway of doing this automatically? 

Jeff

**Comment by kennykerr** [comment]
@riverar has an example of generating metadata for an API defined in IDL. You can then use the `windows-bindgen` crate to generate bindings for it without having to resort to the `interface` macro.

https://github.com/riverar/washington-rs

**Comment by jeffw-wherethebitsroam** [comment]
Thanks for that. I don't really understand the `Microsoft.Windows.WinmdGenerator` magic at the moment, but I was about to generate the rust types to start testing with.

It might be nice to have a link to that repo in the docs or faq?

**Comment by kennykerr** [comment]
@riverar has a nice explainer here:

https://withinrafael.com/2023/01/18/generating-metadata-for-the-windows-crate/
