### ISSUE TITLE
Bug: Linux binaries/cdylibs try to link libwindows when building a crate with windows-rs in a dependency even if no Windows API symbols are exposed

### ISSUE THREAD

**Issue by chyyran** [microsoft/windows-rs#2287]
### Which crate is this about?

windows (possibly windows-sys but I haven't tested that)

### Crate version

0.44.0

### Summary

A cdylib crate referencing `windows` in its dependencies used to be buildable on Linux on 0.43.0. As long as any Windows APIs were `cfg`'d out to be inaccessible, the crate would build and output a `.so` file.  

Even with Windows APIs accessible, the crate would build. Those APIs would find themselves in the symbol table, but symbol resolution failure would happen on `dlopen`, not build time. This is useful sometimes when `docs.rs` fails to cross-compile a crate with C dependencies as CMake scripts of third-party dependencies would try to pass MSVC flags to `cc`, to show Windows-only items. 

### Toolchain version/configuration

```
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.68.0-nightly (0b90256ad 2023-01-13)
```

### Reproducible example
Build this on Linux

```rust
#[cfg(any(
    feature = "docsrs",
    all(target_os = "windows", feature = "windows")
))]
pub mod test {
  pub use windows::Win32::Graphics::Direct3D11::ID3D11Device;
}
```

### Crate manifest

```toml
[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Graphics_Direct3D11",
]
optional = true
```

### Expected behavior

Should not link with `windows.lib` on Linux targets.

### Actual behavior

```
error: linking with `cc` failed: exit status: 1
[long list of rlibs]

 "-Wl,-Bdynamic" "-lstdc++" "-lstdc++" "-lwindows" "-lvulkan" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/f/coding/librashader/target/release/deps/liblibrashader_capi.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"

  = note: /usr/bin/ld: cannot find -lwindows: No such file or directory
          collect2: error: ld returned 1 exit status
```

**Comment by riverar** [comment]
@chyyran Do you have steps to reproduce this? I was able to `cargo build` with both `x86_64-unknown-linux-gnu` and `x86_64-pc-windows-gnu` targets.

**Comment by ChrisDenton** [comment]
I tried the example in the OP and I'm unable to reproduce this either. Maybe there's something else going on?

> The fix for this would just to detect non `pc-windows` targets and skip emitting those link arguments in `build.rs`.

I don't think this is correct. E.g. see https://github.com/microsoft/windows-rs/blob/17a5f00c6afccbc4e17ee6d17c405f15e799bbfb/crates/targets/x86_64_gnu/build.rs#L3-L5

In fact this return should never be reached in practice due to the conditional dependencies in the [windows-targets](https://github.com/microsoft/windows-rs/blob/17a5f00c6afccbc4e17ee6d17c405f15e799bbfb/crates/libs/targets/Cargo.toml) crate. And even if it did somehow bypass both of these conditions, the only thing being added is a native library directory, not the library itself: https://github.com/microsoft/windows-rs/blob/17a5f00c6afccbc4e17ee6d17c405f15e799bbfb/crates/targets/x86_64_gnu/build.rs#L9

Note that windows-rs itself does not have a build script.

**Comment by chyyran** [comment]
@riverar The crate type has to be a binary or cdylib. 

```toml
[package]
name = "windows-min-repo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
version = "0.44.0"
features = [ "Win32_Graphics_Direct3D11" ]
```

```rust
pub use windows::Win32::Graphics::Direct3D11::ID3D11Device;

pub fn add(left: usize, right: usize) -> usize {
    left + right
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let result = add(2, 2);
        assert_eq!(result, 4);
    }
}
```

Just exposing the type without using any exported functions is enough to cause cargo to attempt to link `libwindows`

```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-Wl,--version-script=/tmp/rustcbqPHuN/list" "-m64" "/tmp/rustcbqPHuN/symbols.o" "/mnt/c/coding/windows-min-repo/target/debug/deps/windows_min_repo.4n19gszde0lnet9r.rcgu.o" "/mnt/c/coding/windows-min-repo/target/debug/deps/windows_min_repo.10incn74f0xx5td9.rcgu.o" "-Wl,--as-needed" "-L" "/mnt/c/coding/windows-min-repo/target/debug/deps" "-L" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/mnt/c/coding/windows-min-repo/target/debug/deps/libwindows-8dd52889dc321c97.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-08c52b3d112d8849.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-b70a17a957b273fb.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-1e16815c933606a0.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-7dda930da173cd7f.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-7deef5f688bf2cd5.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-a1f236732a050fbb.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-2d0ddbffdb30be11.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-f85f06d123f44ee7.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-d8b255130cf77303.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-e79cc122e409037d.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-6918a62ad5cae6e0.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-7737bd6c876aa5d1.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-a755a510b6b36eb1.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-cb9ee6e5722842ca.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-a5319eed00c3264d.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-92ba89a1b07f23b1.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-522518611024dce5.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-bc012bb1dd8faba2.rlib" "-Wl,-Bdynamic" "-lwindows" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/chyyran/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/mnt/c/coding/windows-min-repo/target/debug/deps/libwindows_min_repo.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lwindows
          collect2: error: ld returned 1 exit status
```

**Comment by kennykerr** [comment]
It might have something to do with #2152. Prior to the introduction of the `link` abstraction to support `raw-dylib`, the `windows::core` module's internal bindings looked like this:

https://github.com/microsoft/windows-rs/blob/1071bdbb35bc127d0bfeedfd28c76afcd23e6a3e/crates/libs/windows/src/core/bindings.rs#L4-L7

With the introduction of the `link` macro, it now looks like this:

https://github.com/microsoft/windows-rs/blob/39a2d3df2fa5831a8ba51df03091741b8a415504/crates/libs/windows/src/core/bindings.rs#L4-L5

The `link` macro then abstracts the way that the function is imported but if you're not using `raw-dylib` then it uses this overload:

https://github.com/microsoft/windows-rs/blob/17a5f00c6afccbc4e17ee6d17c405f15e799bbfb/crates/libs/windows/src/core/mod.rs#L147-L157

Notice the lack of a `cfg` check for `windows`.

**Comment by chyyran** [comment]
Seems like a likely culprit. I assume with the cfg check added back in the previous behaviour would be restored.

**Comment by riverar** [comment]
> @riverar @ChrisDenton The crate type has to be a binary or cdylib.

Thanks, the original bug report above does not have a working repro. I was able to reproduce using the corrected code in https://github.com/microsoft/windows-rs/issues/2287#issuecomment-1385822488.
