### ISSUE TITLE
Feature request: StructuredStorage Sample

### ISSUE THREAD

**Issue by McSpidey** [microsoft/windows-rs#2288]
### Motivation

I'd like to port python code to rust for editing OLE2 files. Having examples/samples for opening/closing CompoundFiles and reading/modifying their common spec streams would help make this easier and provide more useful examples of how to interact with COM objects.

### Drawbacks

Predominantly legacy file format

### Rationale and alternatives

There's a severe lack of rust libraries for handling OLE2 file streams themselves such as reading/writing their properties.

### Additional context

Thanks for the consideration!

**Comment by kennykerr** [comment]
I don't have such a sample in mind but I have a growing collection of samples here: https://github.com/microsoft/windows-rs/tree/master/crates/samples 

APIs generally fall into a few broad categories from C-style APIs to COM APIs to WinRT APIs. You can usually find an API that is similar and adapt the example. If you get stuck, feel free to open an issue and include a minimal repro of what you've tried. There are generally a good few people who monitor issues and will step in with suggestions. 

I also recommend you start here: https://kennykerr.ca/rust-getting-started/

**Comment by McSpidey** [comment]
Thanks, those are the resources I've been using and learning from.

I'm happy for my basic setup to become the sample when it's working, should I put what I have here or start a new issue?

**Comment by kennykerr** [comment]
Happy to discuss a sample contribution - the general goal for samples is to keep the samples as concise as possible.

**Comment by McSpidey** [comment]
Here's what I have so far with the goal to be more idiomatic and read the properties out of it to get them, and save the thumbnail.

use windows::{core::*, Win32::System::Com::StructuredStorage::*, Win32::System::Com::*};

fn main() -> Result<()> {
    unsafe {
        //Init ?
        CoInitializeEx(None, COINIT_MULTITHREADED)?;

        //Open File
        let filename = w!("file.doc");
        let storage = StgOpenStorage(filename, None, STGM_READ | STGM_SHARE_EXCLUSIVE, None, 0)?;

        //Get file elements enumerator
        let mut storage_enum: Option<IEnumSTATSTG> = None;
        storage.EnumElements(0, None, 0, &mut storage_enum);
        let elements_enum = storage_enum.expect("Nothing to enumerate");

        //Print contents.
        let mut count = 0;
        loop {
            let mut storage_items = [STATSTG::default()];
            let mut fetched = 0;
            elements_enum.Next(&mut storage_items, Some(&mut fetched))?;
            if fetched == 0 {
                break;
            } else {
                // println!("{:?}", storage_items);
                let item = &storage_items[0];
                // println!("{:?}", item);
                let item_type = match item.r#type as u32 {
                    1 => "STGTY_STORAGE",
                    2 => "STGTY_STREAM",
                    3 => "STGTY_LOCKBYTES",
                    4 => "STGTY_PROPERTY",
                    _ => "Unknown type",
                };

                let item_name = item.pwcsName.to_string().unwrap();
                println!(
                    "Element ID, Type and Name: {} {} {:?}",
                    count, item_type, item_name,
                );
                count += 1;
            }
        }
        println!("Found {} elements", count);

        //Open the \u{5}SummaryInformation stream
        let stream_name: PCWSTR = w!("\u{5}SummaryInformation");
        println!("Opening Stream: {}", stream_name.to_string().unwrap());
        let mut mystream: Option<IStream> = None;
        let result = storage.OpenStream(
            stream_name,
            None,
            STGM_SHARE_EXCLUSIVE | STGM_READ,
            0,
            &mut mystream,
        )?;
        let mystream: IStream = mystream.expect("Failed to unwrap"); //Temp fix so autocomplete doesn't think this is still an option

        //Get the stream size.
        let mut stream_stat = STATSTG::default();
        mystream.Stat(&mut stream_stat, STATFLAG_NONAME)?;
        let stream_size = stream_stat.cbSize as u32;
        println!("Stream Size: {}", stream_size);

        //Read the full stream
        let mut buffer: Vec<u8> = vec![0; stream_size as usize];
        let mut bytes_read: u32 = 0;
        let pv = buffer.as_mut_ptr() as *mut std::ffi::c_void;
        let cb = stream_size;
        let pcbread = Some(&mut bytes_read as *mut u32);
        let result = mystream.Read(pv, cb, pcbread);
        match result {
            S_OK => {
                println!("Read {} bytes", bytes_read);
            }
            _ => {
                println!("Error occurred during read operation.");
            }
        }

        //Get the properties from it
        //TODO

        //Uninit ?
        CoUninitialize();

        Ok(())
    }
}
`

**Comment by tim-weis** [comment]
Just a quick comment:

> ```rust
> //Uninit ?
> CoUninitialize();
> ```

That prepares for a bug: There are still live objects with non-trivial `Drop` implementations that now run *after* the thread is no longer initialized for COM. See [this comment](https://github.com/microsoft/windows-rs/issues/1169#issuecomment-926877227), specifically:

> * Continue to spread the message: never call `CoUninitialize`

Related: [Do you know when your destructors run? Part 1.](https://devblogs.microsoft.com/oldnewthing/20040520-00/?p=39243)

**Comment by McSpidey** [comment]
Thanks, this is why I still had "?" on these to review their requirements as I'm still not sure I had all the COM objects I needed working to achieve the goals Would love some help with getting the stream properties correctly anyone has experince with that?

**Comment by kennykerr** [comment]
You're probably better off getting help with this API on https://stackoverflow.com/ - you should attract a much larger pool of developers who may have experience with this API and can help you figure out how to use it correctly.
