### ISSUE TITLE
How to use core::ManuallyDrop

### ISSUE THREAD

**Issue by Flakebi** [microsoft/windows-rs#2294]
I just updated to 0.44.0, which introduces `windows::core::ManuallyDrop` and I’m slightly confused on how this is supposed to be used.

The `std::mem::ManuallyDrop` is a container that does not call drop of the inner value, so if I understand it correctly,
```rust
// incorrect use:
{
  let nodrop = std::mem::ManuallyDrop::new(vec![0; 10]);
}
// nodrop is dropped but the contained vector is not, so memory is leaked

// correct use:
{
  let nodrop = std::mem::ManuallyDrop::new(vec![0; 10]);
  let vec: Vec<_> = std::mem::ManuallyDrop::into_inner(nodrop);
}
// vec is dropped so the memory is freed
```

So, using it for unions in the windows api makes a lot of sense for me, if the unions have memory that needs to be dropped, because the compiler has no chance to figure out which variant of the union to drop.

However, 0.44.0 introduce `core::ManuallyDrop`, which – as I currently understand it – has nothing to do with the reason and meaning behind `std::mem::ManuallyDrop`. Instead, it is just a reference (`*mut void` for things that implement `Vtable`).

I was searching for how to call drop on the contained value for a while, like one needs to do on the std ManuallyDrop, but I wasn’t able to find anything like that :)

So, two questions:
1. Why is it called `ManuallyDrop` isn’t `Borrowed` a better name?
2. If a union contains only pointers with no drop functions, can we remove the `std::mem::ManuallyDrop` wrapper?
  (E.g. for `D3D12_RESOURCE_BARRIER_0`, the example never calls `std::mem::ManuallyDrop::into_inner` anyway, which – as far as I understand – one would have to do for a correct use case)

For cross-reference, #1410 is AFAIK the reason for `core::ManuallyDrop` and #2235 is the PR that introduces ManuallyDrop.

**Comment by kennykerr** [comment]
Sorry for the late response. The answer's a bit complicated but I hope to explain the issue here soon. It's definitely something I'd like to improve but Rust is a bit unwieldy in this regard. Anyway, I'll try to summarize the issue here asap.

**Comment by kennykerr** [comment]
Looked at this some more this morning. I might be able to untangle some of the problems that necessitate a custom `ManuallyDrop`. It's all somewhat tied up in the parameter binding support that I have slowly been simplifying but I think more could be done to make this "just work".

**Comment by Lokathor** [comment]
I'm unclear what you think the purposes of the type is because the type docs stop mid-sentence, but I would *strongly* encourage you to pick a name *other than* `ManuallyDrop`.

@Flakebi: Note that Rust unions already can't contain types that need to be dropped. Example that will print the appropriate error if you try to run it: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6ca6f3794c078115767864ab1ab14070

**Comment by kennykerr** [comment]
> because the type docs stop mid-sentence

That's probably due to this typo:

https://github.com/microsoft/windows-rs/blob/721027379419bc58a9293adc51ea04a55e87e993/crates/libs/windows/src/core/manually_drop.rs#L3-L4

**Comment by Lokathor** [comment]
Ah, then I don't understand the comment because ManuallyDrop has Deref and DerefMut impls.
