### ISSUE TITLE
Release Request for windows-sys

### ISSUE THREAD

**Issue by msiglreith** [microsoft/windows-rs#2298]
Affected upstream crate: `winit`

Upstream Issue: https://github.com/rust-windowing/winit/issues/2620
Local issue (resolved): https://github.com/microsoft/windows-rs/issues/2138

## Description

`DEVMODEW` was defined incorrectly, leading to issues in upstream crates, in our case exclusive fullscreen support.

## Reproduction
`winit`:
- `cargo run --example fullscreen` 
- Press `F` to enter exclusive fullscreen mode

`windows-sys:0.42`
Crash due to unexpected failure of [`ChangeDisplaySettingsExW`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changedisplaysettingsexw)
```
Monitor: Some("\\\\.\\DISPLAY1")
Mode: 0x75 @ 0 mHz (1024 bpp)
Keys:
- Esc   Exit
- F     Toggle exclusive fullscreen mode
- B     Toggle borderless mode
- S     Next screen
- M     Next mode for this screen       
- D     Toggle window decorations       
- X     Maximize window
- Z     Minimize window
Setting mode: Some(Exclusive(VideoMode { size: (0, 75), bit_depth: 1024, refresh_rate_millihertz: 0, monitor: MonitorHandle(65537) }))
thread 'main' panicked at 'assertion failed: res != DISP_CHANGE_BADMODE', src\platform_impl\windows\window.rs:541:21
```

`window-sys:master` working as expected (https://github.com/msiglreith/winit/tree/windows-sys-0.42) 
```
Monitor: Some("\\\\.\\DISPLAY1")
Mode: 1920x1080 @ 60000 mHz (32 bpp)    
Keys:
- Esc   Exit
- F     Toggle exclusive fullscreen mode
- B     Toggle borderless mode
- S     Next screen
- M     Next mode for this screen       
- D     Toggle window decorations       
- X     Maximize window
- Z     Minimize window
Setting mode: Some(Exclusive(VideoMode { size: (1920, 1080), bit_depth: 32, refresh_rate_millihertz: 60000, monitor: MonitorHandle(65537) }))
```

**Comment by kennykerr** [comment]
Will do!

**Comment by kennykerr** [comment]
All done: https://github.com/microsoft/windows-rs/releases/tag/0.45.0
