### ISSUE TITLE
Document MSRV status/policy

### ISSUE THREAD

**Issue by djc** [microsoft/windows-rs#2300]
For chrono I got a Dependabot PR suggesting an update from windows-sys 0.42 to 0.45 (not sure why the 3-point minor version bump?). I wanted to find out if the MSRV has changed as part of this bump, so I went to check out the project on docs.rs, then the README and finally started looking for GitHub Actions workflow definitions. I think a best practice would be to document MSRV issues (ideally while mentioning that specific term so I can CTRL + F it) in the project's README.

**Comment by ChrisDenton** [comment]
It is in the Cargo.toml https://github.com/microsoft/windows-rs/blob/ddf5ebbaea8c2377cd604a3a12b9828071f16367/crates/libs/sys/Cargo.toml#L11

Though that's ignored by cargo until 1.56, which limits its (current) usefulness.

**Comment by djc** [comment]
Ahh yeah, that's good -- silly of me not to look for that. Still would be good to also document some context (for example, a policy or rough outline for how it is expected to evolve in the future) in the README, IMO.

**Comment by kennykerr** [comment]
I also added the MSRV to the docs here: https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html

**Comment by djc** [comment]
Sorry, just checking -- so why not add some language to the README?

**Comment by kennykerr** [comment]
No prob, I just prefer to keep the readme as uncluttered as possible.
