### ISSUE TITLE
A SimpleText Example

### ISSUE THREAD

**Issue by NikhilM42** [microsoft/windows-rs#2305]
Hello,

I was wondering if there is a working example of the SimpleText tutorial involving DirectWrite.
I ask because I was able to get a program started using the minesweeper example, but now I am struggling to get a simple text to appear despite following the SimpleText tutorial. I am hoping I may have just mis-understood if I can even use the compositor along side Direct2D and DirectWrite?

Thanks for your time,

**Comment by robmikh** [comment]
I don't have a complete sample to point you to, but I have some odds and ends that may be useful:

  *  [CompositionTextDemo](https://github.com/robmikh/compositiontextdemo) - A demo of using DirectWrite with Composition surfaces using C++/WinRT.
  *  [Composition Interop Helpers](https://github.com/robmikh/robmikh-common-rs/blob/main/src/universal/composition.rs) - This file should give you an idea on how to create and draw into Composition surfaces in Rust. The repo is a bit dated, but the concepts should be the same.

**Comment by robmikh** [comment]
Here's a Rust port of the CompositionTextDemo: https://github.com/robmikh/comptextdemo-rs

**Comment by NikhilM42** [comment]
Thanks Robert! I'm afk right now, but I will review the examples you have provided.
