### ISSUE TITLE
Feature request: Support debug layer for DirectX 11

### ISSUE THREAD

**Issue by vocasle** [microsoft/windows-rs#2306]
### Motivation

Hey. I would like to see all DirectX debug messages when using windows crate. I have supplied `D3D11_CREATE_DEVICE_DEBUG` flag and I do not see debug messages.

In C++ I can see debug layer messages in Visual Studio's Output window or in VSCode's Debug Console window, but with windows-rs in VSCode's Debug Console window I do not see anything.

In stdout I see only basic info such as:

The parameter is incorrect. (0x80070057)

It is very hard to find the cause of the exception without additional debug info.

### Rationale and alternatives

It is almost impossible to find the cause of exception without debug layer.

**Comment by robmikh** [comment]
It's working for me in the [displayrecorder](https://github.com/robmikh/displayrecorder) project. I validated it by arbitrarily making one of the textures smaller than another and calling `CopyResource`. I got this in the VS Code debug output:

```
D3D11 ERROR: ID3D11DeviceContext::CopyResource: Cannot invoke CopyResource when the source and destination are not the same Resource type, nor have equivalent dimensions. Src has the following dimensions: Width (2560), Height (1440), Depth (1), MipLevels (1), and ArraySize (1). Dst has the following dimensions: Width (2543), Height (1440), Depth (1), MipLevels (1), and ArraySize (1).  [ RESOURCE_MANIPULATION ERROR #284: COPYRESOURCE_INVALIDSOURCE]
```

Are you sure you've attached the debugger?

**Comment by vocasle** [comment]
Hey. Yep, I am pretty sure that I have attached the debugger. I use CodeLLDB to debug. I think that after you have pointed out that debugging is working for you, I should try to use Microsoft's C++ extensions, because it looks like VSCode on Windows does not support debugging.

**Comment by vocasle** [comment]
Indeed, if I switch from CodeLLDB to Microsoft's C/C++ extension I can see debug layer messages.
It would be nice if this info would be added somewhere and highlighted.
