### ISSUE TITLE
How to use BluetoothLEAdvertisement::SetFlags API

### ISSUE THREAD

**Issue by anayw2001** [microsoft/windows-rs#2310]
Hi,
I've been trying to figure out how to use the SetFlags API for creating a General Discoverability BluetoothLEAdvertisement, but I cannot figure out how to correctly type the parameter so the conversions are completed automatically.

I have tried:
BluetoothLEAdvertisementFlags::GeneralDiscoverabilityMode()
&BluetoothLEAdvertisementFlags::GeneralDiscoverabilityMode().into()
(&BluetoothLEAdvertisementFlags::GeneralDiscoverabilityMode()).into()

Would be much appreciated if I could receive some guidance on how to create the required InParam<IReference<BluetoothLEAdvertisementFlags>> type.

**Comment by kennykerr** [comment]
Can you share a minimal repro? Sorry, I'm not familiar with this API. 

Generally, when an API expects a `IReference<T>` parameter it means it's a nullable value type. So, it can accept either a null pointer or a boxed value (it's a C# thing). I don't yet provide a convenient way to call such APIs in Rust, but it should map to an `Option<T>` in Rust (#292). If you're desperate, you can implement `IReference<T>` with the `implement` macro but I should be able to convert such methods to expect an `Option<T>` directly.

**Comment by kennykerr** [comment]
For completeness, here's what the metadata looks like:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/9845234/214952396-166b0439-69c5-4b7b-b5ae-c267c54d06ed.png">

The `T?` syntax is C# syntax but ends up as `IReference<T>` on the ABI, which is what you get in Rust.

**Comment by anayw2001** [comment]
Would it end up looking something like in Rust then?

![Screenshot 2023-01-26 at 5 45 44 PM](https://user-images.githubusercontent.com/13932156/214967764-9d149930-db77-4110-8296-b165a508d641.png)

**Comment by kennykerr** [comment]
Yes.

**Comment by kennykerr** [comment]
Yes, when the code gen changes are done you can just use `None` or `Some(value)` for such parameters. Until then, you need to provide an `IReference<T>` implementation yourself, but that's hard. Thanks for the reminder - I'll try to get to this shortly.

**Comment by anayw2001** [comment]
Gotcha, thanks! How would I go about providing an ```IReference<T>``` implementation for now until the code gen changes are done?

**Comment by kennykerr** [comment]
As I said, this should all be automatic but for the moment here's what you'll have to do to implement `IReference<T>` yourself:

```
[dependencies.windows]
version = "0.44"
features = [
    "Devices_Bluetooth_Advertisement",
    "Foundation", 
    "implement", 
]
```

```rust

use windows::{core::*, Devices::Bluetooth::Advertisement::*, Foundation::*};

fn main() -> Result<()> {
    let blue = BluetoothLEAdvertisement::new()?;

    // Clear flags
    blue.SetFlags(None)?;

    // Read cleared flags
    assert!(blue.Flags().unwrap_err().code().is_ok());

    // Set boxed flags
    blue.SetFlags(&Reference::box_value(
        BluetoothLEAdvertisementFlags::LimitedDiscoverableMode,
    ))?;

    // Read unboxed flags
    assert!(blue.Flags()?.Value()? == BluetoothLEAdvertisementFlags::LimitedDiscoverableMode);

    Ok(())
}

#[implement(IReference<T>)]
struct Reference<T>(T)
where
    T: RuntimeType;

impl<T: RuntimeType> Reference<T> {
    fn box_value(value: T) -> IReference<T> {
        Self(value).into()
    }
}

impl<T: RuntimeType + 'static> IReference_Impl<T> for Reference<T> {
    fn Value(&self) -> Result<T> {
        Ok(self.0.clone())
    }
}

impl<T: RuntimeType + 'static> IPropertyValue_Impl for Reference<T> {
    fn Type(&self) -> Result<PropertyType> {
        todo!()
    }
    fn IsNumericScalar(&self) -> Result<bool> {
        todo!()
    }
    fn GetUInt8(&self) -> Result<u8> {
        todo!()
    }
    fn GetRect(&self) -> Result<Rect> {
        todo!()
    }
    fn GetUInt8Array(&self, _: &mut Array<u8>) -> Result<()> {
        todo!()
    }
    fn GetInt16Array(&self, _: &mut Array<i16>) -> Result<()> {
        todo!()
    }
    fn GetUInt16Array(&self, _: &mut Array<u16>) -> Result<()> {
        todo!()
    }
    fn GetInt32Array(&self, _: &mut Array<i32>) -> Result<()> {
        todo!()
    }
    fn GetUInt32Array(&self, _: &mut Array<u32>) -> Result<()> {
        todo!()
    }
    fn GetInt64Array(&self, _: &mut Array<i64>) -> Result<()> {
        todo!()
    }
    fn GetUInt64Array(&self, _: &mut Array<u64>) -> Result<()> {
        todo!()
    }
    fn GetSingleArray(&self, _: &mut Array<f32>) -> Result<()> {
        todo!()
    }
    fn GetDoubleArray(&self, _: &mut Array<f64>) -> Result<()> {
        todo!()
    }
    fn GetChar16Array(&self, _: &mut Array<u16>) -> Result<()> {
        todo!()
    }
    fn GetBooleanArray(&self, _: &mut Array<bool>) -> Result<()> {
        todo!()
    }
    fn GetStringArray(&self, _: &mut Array<HSTRING>) -> Result<()> {
        todo!()
    }
    fn GetInspectableArray(&self, _: &mut Array<IInspectable>) -> Result<()> {
        todo!()
    }
    fn GetGuidArray(&self, _: &mut Array<GUID>) -> Result<()> {
        todo!()
    }
    fn GetDateTimeArray(&self, _: &mut Array<DateTime>) -> Result<()> {
        todo!()
    }
    fn GetTimeSpanArray(&self, _: &mut Array<TimeSpan>) -> Result<()> {
        todo!()
    }
    fn GetPointArray(&self, _: &mut Array<Point>) -> Result<()> {
        todo!()
    }
    fn GetSizeArray(&self, _: &mut Array<Size>) -> Result<()> {
        todo!()
    }
    fn GetRectArray(&self, _: &mut Array<Rect>) -> Result<()> {
        todo!()
    }
    fn GetInt16(&self) -> Result<i16> {
        todo!()
    }
    fn GetUInt16(&self) -> Result<u16> {
        todo!()
    }
    fn GetInt32(&self) -> Result<i32> {
        todo!()
    }
    fn GetUInt32(&self) -> Result<u32> {
        todo!()
    }
    fn GetInt64(&self) -> Result<i64> {
        todo!()
    }
    fn GetUInt64(&self) -> Result<u64> {
        todo!()
    }
    fn GetSingle(&self) -> Result<f32> {
        todo!()
    }
    fn GetDouble(&self) -> Result<f64> {
        todo!()
    }
    fn GetChar16(&self) -> Result<u16> {
        todo!()
    }
    fn GetBoolean(&self) -> Result<bool> {
        todo!()
    }
    fn GetString(&self) -> Result<HSTRING> {
        todo!()
    }
    fn GetGuid(&self) -> Result<GUID> {
        todo!()
    }
    fn GetDateTime(&self) -> Result<DateTime> {
        todo!()
    }
    fn GetTimeSpan(&self) -> Result<TimeSpan> {
        todo!()
    }
    fn GetPoint(&self) -> Result<Point> {
        todo!()
    }
    fn GetSize(&self) -> Result<Size> {
        todo!()
    }
}
```

**Comment by anayw2001** [comment]
Awesome, thank you so much! Will close this issue as #292 seems to be the main issue.

**Comment by anayw2001** [comment]
Reopening as use of this API results in
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }', src\main.rs:23:23
```
main.rs:
```
fn advertise() {
    let advertisement = BluetoothLEAdvertisement::new().unwrap();
    advertisement.SetFlags(&reference_impl::Reference::box_value(BluetoothLEAdvertisementFlags::GeneralDiscoverableMode)).unwrap();
    let sections = advertisement.DataSections().unwrap();
    let new_section = BluetoothLEAdvertisementDataSection::new().unwrap();
    new_section.SetDataType(BluetoothLEAdvertisementDataTypes::ServiceData16BitUuids().unwrap()).unwrap();
    let data_writer =  DataWriter::new().unwrap();
    data_writer.WriteUInt16(0xF1FCu16).unwrap();
    data_writer.WriteBytes(b"hello").unwrap();
    new_section.SetData(&data_writer.DetachBuffer().unwrap()).unwrap();
    println!("# of data sections: {}", sections.Size().unwrap());
    advertisement.DataSections().unwrap().Append(&new_section).unwrap();
    println!("# of data sections: {}", sections.Size().unwrap());
    let publisher = BluetoothLEAdvertisementPublisher::Create(&advertisement).unwrap();
    publisher.Start().unwrap(); --> L23
    println!("Started advertising {:?}!", advertisement);
    sleep(Duration::from_secs(20));
    publisher.Stop().unwrap();
    println!("Stopped advertising {:?}!", advertisement);
}

```

**Comment by anayw2001** [comment]
Same issue with the SetLocalName API
```
        advertisement
            .SetLocalName(&if let Some(local_name) = name {
                HSTRING::from(local_name)
            } else {
                HSTRING::default()
            })
            .unwrap()
```

**Comment by anayw2001** [comment]
edit: Just checked the docs and it seems it's a system-reserved API so should maybe be removed instead.

**Comment by kennykerr** [comment]
The minimal, reproducible example I provided https://github.com/microsoft/windows-rs/issues/2310#issuecomment-1406625343 works without error, at least on my machine. If you think you've found an issue with windows-rs then please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Otherwise, if you have questions about how to use the API you're better off heading over to https://stackoverflow.com/ as I don't have any particular insights on how this API is meant to work in practice.

**Comment by anayw2001** [comment]
Gotcha, the problem is still reproducible, I just added 
```
    let publisher = BluetoothLEAdvertisementPublisher::Create(&blue)?;
    publisher.Start()?;
```
to your code snippet above and it errors out with
```Error: Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }```

**Comment by riverar** [comment]
Hi @anayw2001, not seeing any issues here either. This is very likely related to your Bluetooth software or hardware stack--try updating your drivers perhaps.

We can't help with Bluetooth issues here. I recommend posting on Microsoft Q&A--there are actual engineers that answer questions there. Specifically, the UWP area/tag seems apt. (https://learn.microsoft.com/en-us/answers/tags/105/windows-uwp)
