### ISSUE TITLE
Bug: Contradictory data types with `AssocQueryStringW()`

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#2314]
(`windows` crate, v0.43.0)

`AssocQueryStringW()` takes a `u32` as first argument: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/fn.AssocQueryStringW.html.

This argument can be `ASSOCF_NONE`, among others, which is defined as an `i32`: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/constant.ASSOCF_NONE.html. The other `ASSOCF_...` constants are also `i32`s as far as I checked.

This requires an `as u32` that shouldn't be required. As far as I understand, the C/C++ `enum` that defines the `ASSOCF_...` constants can be expected to be an `int` or Rust `i32`. So, `AssocQueryStringW()` needs to change, if you don't translate C enums to `u32`s.

**Comment by kennykerr** [comment]
Have you tried the latest version? I think this has been fixed.

**Comment by Enyium** [comment]
Indeed, what a coincidence. Just not documented yet.
