### ISSUE TITLE
`RmRegisterResources` uses `PWSTR` rather than `PCWSTR` for input parameters

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#2315]
The [`RmRegisterResources`](https://learn.microsoft.com/en-us/windows/win32/api/restartmanager/nf-restartmanager-rmregisterresources) API call has two input parameters of type `LPCWSTR[]` (`rgsFileNames` and `rgsServiceNames`), that are described as

```none
[Optional][In][NativeArrayInfo(CountParamIndex = ...)] PWSTR*
```

in metadata. Those get translated into

```rust
Option<&[PWSTR]>
```

for windows' implementation of [`RmRegisterResources`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/RestartManager/fn.RmRegisterResources.html).

That seems justifiable, though I had hoped for the `[In]` parameters to get converted from `PWSTR` to `PCWSTR`, as suggested [here](https://github.com/microsoft/win32metadata/issues/807#issuecomment-1049221504).

Was this transformation never implemented, did it regress at some point, or is this particular API special in some way that doesn't allow for the `PWSTR` -> `PCWSTR` transformation?

**Comment by kennykerr** [comment]
Hi Tim, this was fixed in #2227 and is available as of the 0.44.0 release of the `windows` crate.

**Comment by tim-weis** [comment]
I see. So the actual issue here was rather a duplicate of #2032. Any progress on that? Is the Rust Docs Team interested in providing a service that would have me trust into the future of Rust, or are they just going to leave it as it is now?

**Comment by kennykerr** [comment]
I think they need someone to step up and help make it more scalable. I'd like to help with that, but I'm kinda busy at the moment. 

Sorry about the docs, I'll try to get them updated shortly.

**Comment by riverar** [comment]
Updated: https://microsoft.github.io/windows-docs-rs/doc/windows/
