### ISSUE TITLE
Bug: Can not retrieve blob of IDxcOperationResult because it always returns 'Err'

### ISSUE THREAD

**Issue by chyyran** [microsoft/windows-rs#2326]
### Which crate is this about?

windows

### Crate version

windows 0.44

### Summary

I'm validating a shader like so

```
pub fn dxc_validate_shader(library: &IDxcLibrary, validator: &IDxcValidator, source: &[u8]) -> error::Result<IDxcBlob> {
    // todo: compile with dxc
    let blob = unsafe {
        library.CreateBlobWithEncodingFromPinned(
            source.as_ptr().cast(),
            source.len() as u32,
            DXC_CP(0)
        )?
    };

    unsafe {
        let result: IDxcOperationResult = validator.Validate(&blob, 0).unwrap();
        let result = result.GetResult().unwrap();

        Ok(result)
    }
}
```

The unwrap fails with 
```
called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x00000000), message: "The operation completed successfully." }
```

### Expected behavior

Should successfully unwrap with HRESULT(0).

### Actual behavior

Does not unwrap with HRESULT(0)

**Comment by kennykerr** [comment]
When an API returns an error with an `S_OK` (zero) error code it just means that the API call succeeded but that it did not return a value. So, the call to `Validate` returned a null pointer as well as an `S_OK` error code. Why it would do that is a question for the team responsible for this API.
