### ISSUE TITLE
Bug: cross compilation with the GNU toolchain doesn't work for static libs with custom StaticLibraryAttribute

### ISSUE THREAD

**Issue by wravery** [microsoft/windows-rs#2327]
### Which crate is this about?

other (please share in the comments)

### Crate version

0.44.0

### Summary

If you use a custom winmd generated with the `StaticLibrary` attribute, indicating a preferred static library along with a DLL, `windows-bindgen` can generate a static `#[link]` attribute pointing to that static library. However, this only works when building on Windows, with the MSVC toolchain. If you try to cross-compile from another host or opt-in to the GNU toolchain from Windows, it doesn't know how to link the static library. It can only handle linking against DLLs.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\wrave\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
beta-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

aarch64-pc-windows-msvc
i686-pc-windows-msvc
wasm32-unknown-unknown
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.67.0 (fc594f156 2023-01-24)

### Reproducible example

```rust
I worked around this in https://github.com/wravery/webview2-rs by patching the output of windows-bindgen to support cross-compilation: [webview2-com-sys](https://github.com/wravery/webview2-rs/blob/1861c1583c0d9f606484b17b4b1d397a8f8957d4/crates/bindings/build.rs#L390).

To reproduce this issue, you could turn it into a no-op that just returns Ok(bindings).
```

### Expected behavior

The output of `windows-bindgen` should cross-compile with the GNU toolchain.

### Actual behavior

Without the patching function in build.rs, the `#[link]` attributes all look like this:

```rust
#[link(name = "WebView2LoaderStatic", kind = "static")]
```

This works perfectly for MSVC, but it breaks with the GNU toolchain.

### Additional comments

I'm about to publish a PR with a fix, I'm just filling in background information here.

**Comment by riverar** [comment]
Hey @wravery! Can you provide a bit more detail on what you're seeing in terms of errors when it comes to static libs?

I created a repro crate that compiles successfully and demonstrates
* creating metadata w/ static lib attributes
* generating bindings using metadata
* creating a static lib (using gnu tooling)
* wiring up the static lib

 https://github.com/riverar/wrs-repros/tree/master/issue-2327

**Comment by kennykerr** [comment]
Static libs are also compiler-specific so it may be that static libs are supported but the static lib that WebView2 publishes is MSVC-specific.

**Comment by wravery** [comment]
Ah, yeah, I think that's the issue. I just remember needing to switch back to dynamic linking to enable cross-compilation for webview2-com-sys from Linux. The unfortunate side effect is that applications which are built that way must redistribute additional DLLs, but otherwise it just didn't work at all.

Would it make sense to expose a bindgen API to opt-in to the non-MSVC dynamic linking fallback instead? Or is this such a niche feature that it only really matters to my webview2-rs crates?

**Comment by kennykerr** [comment]
Yes, it seems a little too specific to this one application. We can always re-evaluate if a more generally applicable scenario emerges.
