### ISSUE TITLE
consume COM library from C# to rust

### ISSUE THREAD

**Issue by GJim** [microsoft/windows-rs#2334]
First of all thank you for this crate!

## Question Description
I want to rewrite my project from C# to rust. 
But I stuck in **Segmentation Fault** situation.
I think I misunderstood something, hope for some help.

## Rust Code
* find interface UUID
![image](https://user-images.githubusercontent.com/14807780/218402049-4b2f21f6-4996-48cc-ae91-e10d2b31676b.png)
* find CLSID
![image](https://user-images.githubusercontent.com/14807780/218403295-293d6dbf-e54f-4da0-80d8-17d9b11f5328.png)
* other id (I'm not sure shall we need it)
![image](https://user-images.githubusercontent.com/14807780/218402661-94627f8d-911d-42c2-aef1-27988698a572.png)
```
use windows::core::{GUID, HRESULT, IUnknown, IUnknown_Vtbl, interface};
use windows::Win32::System::Com::{
    COINIT_APARTMENTTHREADED, 
    CLSCTX_ALL,
    CoInitializeEx,
    CoCreateInstance};

// define interface
#[interface("288EFDEC-3CF0-4F6C-8473-4E4CD47A93C7")]
unsafe trait Inhicshisx: IUnknown {
    fn VPNGetRandomX(&self) -> HRESULT;
}

fn run() -> Result<(), anyhow::Error> {
    unsafe {
        // 2F5AECD5-B5CD-41E1-8265-E2F6AA4548CB
        const CLSID: GUID = GUID {
            data1: 0x2F5AECD5,
            data2: 0xB5CD,
            data3: 0x41E1,
            data4: [0x82, 0x65, 0xE2, 0xF6, 0xAA, 0x45, 0x48, 0xCB],
        };
        
        // initialize runtime
        CoInitializeEx(Some(ptr::null_mut() as *mut c_void), COINIT_APARTMENTTHREADED)?;
        
        // create COM object
        let hisx: Inhicshisx = CoCreateInstance(&CLSID, None, CLSCTX_ALL)?;
        
        // call object function
        let value = hisx.VPNGetRandomX();
    }
    
    Ok(())
}
```

## C# Part
* add a reference
![image](https://user-images.githubusercontent.com/14807780/218400999-d3816353-a141-41a4-aa6e-867b3c6d812e.png)
* call function
```
using CSHISXLib;
string MyStr0;
CSHISXLib.Inhicshisx CSHISXLibObj = new CSHISXLib.nhicshisx();
MyStr0 = CSHISXLibObj.VPNGetRandomX();
Console.WriteLine(MyStr0);
```
* It works.

**Comment by Cinimajig** [comment]
Could it be, that CoInitializeEx needs to be multithreaded? I don't know what CSHISX is or where to download it to replicate it.

Try: `CoInitializeEx(None, COINIT_MULTITHREADED)?`

**Comment by kennykerr** [comment]
That looks mostly correct, but you should pass `None` for the `CoInitializeEx` function's first parameter. Here's an example of how to call `CoInitializeEx` and `CoCreateInstance` correctly: 

https://github.com/microsoft/windows-rs/blob/master/crates/samples/windows/wmi/src/main.rs

Beyond that, I'd suggest https://stackoverflow.com/ for general programming questions.

**Comment by GJim** [comment]
> Could it be, that CoInitializeEx needs to be multithreaded? I don't know what CSHISX is or where to download it to replicate it.
> 
> Try: `CoInitializeEx(None, COINIT_MULTITHREADED)?`

@Cinimajig Thank you for your suggestion, but it still raise Segmentation Fault :sob:

**Comment by GJim** [comment]
> That looks mostly correct, but you should pass `None` for the `CoInitializeEx` function's first parameter. Here's an example of how to call `CoInitializeEx` and `CoCreateInstance` correctly:
> 
> https://github.com/microsoft/windows-rs/blob/master/crates/samples/windows/wmi/src/main.rs
> 
> Beyond that, I'd suggest https://stackoverflow.com/ for general programming questions.

@kennykerr Thank you for your suggestion, and sorry for that, I will raise my question on stackoverflow :pray:
