### ISSUE TITLE
Windows API for rust giving "Interface not registered" error when constructing PrintManager

### ISSUE THREAD

**Issue by Hadibeydoun8** [microsoft/windows-rs#2338]
I am attempting to use the `windows` rust crate API to print a jpeg in rust

first I import the PrintManager using `use windows::Graphics::Printing::PrintManager;`

then define the main function
`fn main() {`
and attempt to create a PrintManager using the GetForCurrentView method
`let print_manager = PrintManager::GetForCurrentView().unwrap();`
however when I run it I get the following error
```````` called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x80040155), message: "Interface not registered" } ````````

Minimally reproducible example

Cargo.toml

```cargo toml
...
[dependencies.windows]
version = "0.44.0"
features = [
    "Devices_Printers",
    "Foundation",
    "Win32_Graphics_Printing",
    "Graphics_Printing"
]
```

Main Program

```rust
use windows::Graphics::Printing::PrintManager;

fn main() {
    let print_manager = PrintManager::IsSupported();
    dbg!(print_manager)
    // this is where the error gets thrown 
    let print_manager = PrintManager::GetForCurrentView().unwrap();
    dbg!(print_manager);
}
```

I expect for the function to return a PrintManager struct that I can later use to print a JPEG however it keeps throwing this interface not registered error, I have tried running the program as an administrator with no luck.

Any help is much appreciated
Thank you so much!

**Comment by kennykerr** [comment]
I imagine the `GetForCurrentView` method fails because there is no active window in the process or associated with the calling thread. Sorry, I'm not familiar with this particular API. You can ask API questions here:

https://learn.microsoft.com/en-us/answers/tags/224/windows-api-win32

Alternatively, https://stackoverflow.com/ is usually a good venue for such questions.

**Comment by riverar** [comment]
Hi @Hadibeydoun8, take note of the caution text in the documentation https://learn.microsoft.com/uwp/api/windows.ui.viewmanagement.applicationview.getforcurrentview?view=winrt-22621

> You can call ApplicationView.GetForCurrentView only after the CoreWindow has been constructed [...]

CoreWindow is only available in specially packaged applications (commonly referred to as "UWP apps"). Typically any WinRT API you find in the Windows namespace with a `GetForCurrentView` method falls into this category. Some APIs offer a desktop app solution via a `GetForWindow` method but in this special case, PrintManager doesn't support vanilla Win32 HWNDs at all.

You'll need to find a different API (e.g. PrintDlgEx?).
