### ISSUE TITLE
Bug: ResumeThread binding returns u32, but actual ResumeThread returns i32

### ISSUE THREAD

**Issue by Hpmason** [microsoft/windows-rs#2340]
### Which crate is this about?

windows, windows-sys

### Crate version

0.44.0

### Summary

`ResumeThread`'s function definition has it returning a u32, but the official documentation states that it returns a -1 in case of an error, so shouldn't return type be an i32?

https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-resumethread

**Comment by tim-weis** [comment]
The signature in `windows` and `windows-sys` is correct. Take special note that the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-resumethread) describes the error return value as `(DWORD)-1` (**not** `-1`), i.e. an expression of type `DWORD` (an [unsigned 32-bit value](https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types)).

If you need to check for error returns in Rust you can either compare against `-1_i32 as u32` or [`u32::MAX`](https://doc.rust-lang.org/std/primitive.u32.html#associatedconstant.MAX), both representing the same value under the rules of two's complement arithmetic.

**Comment by Hpmason** [comment]
Ah gotcha. Kinda weird that we have to type cast -1 to unsigned, but I guess that's how it works. Thanks for clarifying!

**Comment by tim-weis** [comment]
> Kinda weird that we have to type cast -1 to unsigned

That's specific to Rust, as Rust doesn't provide any implicit type conversions between primitive types. But `ResumeThread()` is part of a C API, and in C (or C++) we (in)conveniently get implicit type conversions from the language, meaning that

```c
if (ResumeThread(h) == -1) {
    // Handle error
}
```

is valid code. In Rust we have to be explicit about this conversion, but that doesn't mean that we have to do it at the call site. The following works fine, and is arguably more readable, too:

```rust
const ERROR_VALUE: u32 = -1_i32 as u32;
if ResumeThread(h) == ERROR_VALUE {
    // Handle error
}
```
