### ISSUE TITLE
LoadLibraryA failed with "Cannot find the specified module" while same code success in C++

### ISSUE THREAD

**Issue by ANOLASC** [microsoft/windows-rs#2342]
Rust
```rust
let h_dll = unsafe { LoadLibraryA(windows::core::PCSTR("kernelbase.dll".as_ptr())) };
if h_dll.is_err() {
    println!("{h_dll:?}");
}
```
print ```Cannot find the specified module```

C++
```c++
HINSTANCE h_dll;
h_dll = LoadLibrary (TEXT ("kernelbase.dll"));
if h_dll == NULL {
    //print something
}
```

**Comment by kennykerr** [comment]
That's probably because you neglected to include a null terminator whereas your C++ example includes a null terminator. Rust literals aren't null terminated. You can add it to you literal or use the `s!` macro.

**Comment by ANOLASC** [comment]
> That's probably because you neglected to include a null terminator whereas your C++ example includes a null terminator. Rust literals aren't null terminated. You can add it to you literal or use the `s!` macro.

Oops, I ignored the null terminator, and after using the "s!", it no longer Err, thank you.
