### ISSUE TITLE
Feature request: Easily convert String to PCSTR

### ISSUE THREAD

**Issue by leonardder** [microsoft/windows-rs#2344]
I still find it a bit clumcy to convert a rust String to a PCST, as you have to add the null terminator yourself. Would it be possible to come up with something like this?

```Rust
let s: String = "Hello";
let ss: PCSTR = s.into();
```

**Comment by leonardder** [comment]
Ah, I've now found out that this worked in the past but was intentionally removed. As the release notes for the 0.39 release read:

> Notably, the "alloc" feature has been removed. This feature allowed string literals to be implicitly converted to null terminated strings required by some Windows APIs. While convenient, it was rather complicated and expensive at runtime. Instead, the explicit s! and w! macros are now provided to create null terminated UTF-8 and UTF-16 string literals at compile time.

While s! and w! are really convenient indeed, they only take literals. If passing a variable, I'm getting the error `no rules expected the token`. They neither support string formatting.
Therefore converting the output of a rust function that returns a &str or String is not very straight forward.
There is also some clarification in https://github.com/microsoft/windows-rs/pull/1811#issuecomment-1202360260.
IMO a solution that allows formatting on s! and w! would be most straight forward:

```rust
let hello = "hello";
    let twice_hello = w!("{} {}", hello, hello);
```

**Comment by kennykerr** [comment]
You can use `format!` for that. The `w!` and `s!` macros don't offer that capability because they produce constant (compile-time) literals. Here's an example:

```rust
use windows::core::{s, PCSTR};

const HELLO: PCSTR = s!("hello constant");

fn main() {
    let hello = format!("hello {}\0", "run time");
    let hello = PCSTR(hello.as_ptr());

    unsafe {
        println!("{}", HELLO.display());
        println!("{}", hello.display());
    }
}
```

**Comment by ShenHongFei** [comment]
It's possible, but it's still very troublesome

```rust
use windows::core::{ s, PCSTR };

use std::ffi::CString;

let text = String::new();

let text = CString::new(text).unwrap();

let pcstr = PCSTR::from_raw(text.as_ptr() as *const u8);
```

or

```rust
let text = String::new();

let text = CString::new(text).unwrap();

let pcstr = PCSTR::from_raw(text.as_bytes_with_nul().as_ptr());
```

**Comment by interpretercast** [comment]
> You can use `format!` for that. The `w!` and `s!` macros don't offer that capability because they produce constant (compile-time) literals. Here's an example:
> 
> ```rust
> use windows::core::{s, PCSTR};
> 
> const HELLO: PCSTR = s!("hello constant");
> 
> fn main() {
>     let hello = format!("hello {}\0", "run time");
>     let hello = PCSTR(hello.as_ptr());
> 
>     unsafe {
>         println!("{}", HELLO.display());
>         println!("{}", hello.display());
>     }
> }
> ```

That one worked, thanks :D

**Comment by wmmc88** [comment]
> You can use `format!` for that. The `w!` and `s!` macros don't offer that capability because they produce constant (compile-time) literals. Here's an example:
> 
> ```rust
> use windows::core::{s, PCSTR};
> 
> const HELLO: PCSTR = s!("hello constant");
> 
> fn main() {
>     let hello = format!("hello {}\0", "run time");
>     let hello = PCSTR(hello.as_ptr());
> 
>     unsafe {
>         println!("{}", HELLO.display());
>         println!("{}", hello.display());
>     }
> }
> ```

@kennykerr is this sound? My understanding is that `format!` creates a `String` which is UTF-8 encoded (i.e. variable-width characters) and `PCSTR` is stricly `ansi` (i.e. 8-bit characters). I think it works for this specific example, but in general, we cannot just assume the ptr to a `String` is valid to use for `PCSTR`

**Comment by tim-weis** [comment]
> `PCSTR` is stricly `ansi` (i.e. 8-bit characters)

ANSI is very similar to UTF-8: Code units are 8-bits but code points require one or more code units to encode. Specifically, ANSI encodings aren't guaranteed to be composed of single code units exclusively. Indeed, the proprocessor symbol to switch to the ANSI versions of the platform SDK is aptly named `MBCS`.

Unless there is an ANSI encoding where a code unit with value 0 can appear as part of a multi-byte encoding I don't see a soundness issue. [Mojibake](https://en.wikipedia.org/wiki/Mojibake) is the worst possible outcome.

**Comment by kennykerr** [comment]
Also, `PCSTR` makes no real claims about what it points to. Whether its ANSI or UTF-8 or something else is more a question for the APIs that interact with `PCSTR` than the type itself. That's why the `windows-strings` crate provide precious little in the way of safe functionality for this type.
