### ISSUE TITLE
Discrepancy in TOKEN_ALL_ACCESS value between repo and crate

### ISSUE THREAD

**Issue by rasta-mouse** [microsoft/windows-rs#2351]
I'm sorry if this issue is out of place - I don't think it belongs here but I couldn't find a better place to ask.

I've been using the latest version of the [windows crate](https://crates.io/crates/windows), (currently 0.44.0) and was having trouble with a call to DuplicateTokenEx.  Upon inspection, I found the value of TOKEN_ALL_ACCESS was `983295` (`F00FF`).

![image](https://user-images.githubusercontent.com/7346521/221169874-100b6491-ff80-4876-98c6-acb2606aa438.png)

The value I expected was `983551` (`F01FF`).  This is the value within [this repo](https://github.com/microsoft/windows-rs/blob/master/crates/libs/windows/src/Windows/Win32/Security/mod.rs#L2449), so why are they different?

**Comment by ChrisDenton** [comment]
This sounds like https://github.com/microsoft/win32metadata/issues/1410

**Comment by kennykerr** [comment]
Yep, you should see that fix in the next published version of the `windows` and `windows-sys` crates.
