### ISSUE TITLE
Feature request: Windows Encryption API

### ISSUE THREAD

**Issue by Nordgaren** [microsoft/windows-rs#2355]
### Motivation

Add to the existing API you have bound, here.

I actually have a bunch of the types and function calls mapped out, so I was wondering if I were to add this, would you take a PR?

### Drawbacks

More code to maintain, maybe?

### Rationale and alternatives

If you don't want this as a PR, I will possibly make a WinCrypt library, but I do really like your macros, so it would probably be much easier to do via macros :P

### Additional context

Thanks for your time!

If I were to add this, where would you prefer it go?

**Comment by tim-weis** [comment]
This sounds like you are asking to have custom code added to the `windows` crate. If that is the case, then that's a pretty hard sell. The code is [generated from metadata](https://kennykerr.ca/rust-getting-started/how-are-crates-built.html) almost entirely.

Given that `windows` is the largest crate (by lines of code) on crates.io it frequently runs into limits of the Rust ecosystem infrastructure already (docs.rs still cannot generate documentation, with everything stripped to the bare minimum). Any contribution that reduces its size is well appreciated. Anything that adds will need to come with a convincing value proposition.

While this reads like you have implemented a higher level abstraction over the Crypto API, what's the specific issue with having this published as its own, dedicated crate?

**Comment by kennykerr** [comment]
Also note that most of the cryptography APIs are already available:

https://docs.rs/windows-sys/0.45.0/windows_sys/Win32/Security/Cryptography/index.html

**Comment by Nordgaren** [comment]
> Also note that most of the cryptography APIs are already available:
> 
> https://docs.rs/windows-sys/0.45.0/windows_sys/Win32/Security/Cryptography/index.html

huh, My mistake. I didn't see this.

It looks like I was using the wrong crate in my project, and github search seems to have failed me (I was looking for the declaration in the source, when I couldn't find it in the crate I was using)

Thanks! Sorry about that!
