### ISSUE TITLE
Feature request: Make HRESULT::from_win32 public

### ISSUE THREAD

**Issue by leonardder** [microsoft/windows-rs#2356]
### Motivation

As far as I can see, there is currently no public way to convert a win32 error code to a HRESULT, similar to the HRESULT_FROM_WIN32 function in C. This would be helpful in a case where I'm implementing a dll function that returns HRESULT but should communicate errors that are in the win32 error code format. Converting to core::Error might be a bit too much for that.

### Additional context

As this is just the case of removing a (crate) from the current pub statement, I'm happy to provide a pr for this.

**Comment by riverar** [comment]
Not opposed to that; just throwing a note here that `from_win32` hardcodes the facility to `FACILITY_WIN32`. We may want to expose an API that allows for overriding that (e.g. `FACILITY_INTERNET`).

**Comment by kennykerr** [comment]
Note that `WIN32_ERROR` already provides convertibility to `HRESULT` and `Error`.

https://github.com/microsoft/windows-rs/blob/42963ebf439cf32921df3c15b98e0ace917f24d3/crates/libs/bindgen/src/extensions/mod/Win32/Foundation/WIN32_ERROR.rs#L32-L41

**Comment by leonardder** [comment]
@kennykerr thanks for pointing me at that. This way is a bit less obvious but certainly very helpful for my use case.
