### ISSUE TITLE
Feature request: expose `IID` COM constant and more in `windows-sys`

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#2366]
### Motivation

I'm working to update the [`sysinfo`](https://crates.io/crates/sysinfo) to `windows-sys` instead of `winapi` and I'm missing some things:

#### Missing elements

- `IID` (specifically for the `windows::Win32::System::Wmi::IWbemLocator`) is not in  `windows-sys` but is in `windows`
- [`ULARGE_INTEGER`](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-ularge_integer-r1)

### Additional context

I remember something about the COM APIs not being in windows-sys voluntarily ?

**Comment by poliorcetics** [comment]
I'm going to update the top comment with missing elements as I find them

**Comment by kennykerr** [comment]
https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html

**Comment by poliorcetics** [comment]
So necessarily using `windows`, I don't think that'll go well for compile times sadly (I understand you can't do much about this)

@GuillaumeGomez, before I go any further, would you accept an MR going from `winapi` to `windows` ?

**Comment by GuillaumeGomez** [comment]
If it provides the same functionalities with no downgrade in performance or compilation time, all good for me.

**Comment by kennykerr** [comment]
Do give it a try. I am regularly findings ways to improve `windows` crate build time. Most recently #2360.

**Comment by poliorcetics** [comment]
Thanks to you both, will do!
