### ISSUE TITLE
Not find windows::Win32::System::Diagnostics::Debug::IMAGE_OPTIONAL_HEADER64

### ISSUE THREAD

**Issue by bcdlbgm** [microsoft/windows-rs#2368]
Hi I have a qustion
I can`t find the struct "windows::Win32::System::Diagnostics::Debug::IMAGE_OPTIONAL_HEADER64" 
why?
![image](https://user-images.githubusercontent.com/45490024/223740032-065733b4-a7c4-41f2-aa34-45d4e327e776.png)

**Comment by kennykerr** [comment]
Please provide a minimal reproducible example. Here's a form that can help:

https://github.com/microsoft/windows-rs/issues/new?assignees=&labels=bug&template=bug_report.yml&title=Bug%3A

**Comment by tim-weis** [comment]
@bcdlbgm There's a documentation entry for [`IMAGE_OPTIONAL_HEADER64`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/struct.IMAGE_OPTIONAL_HEADER64.html), so I assume it does get generated. Did you specify the `"Win32_System_Diagnostics_Debug"` feature in the `[dependencies.windows]` table in your Cargo.toml?

**Comment by bcdlbgm** [comment]
> @bcdlbgm有一个文档条目[`IMAGE_OPTIONAL_HEADER64`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/struct.IMAGE_OPTIONAL_HEADER64.html)，所以我假设它确实生成了。您是否在 Cargo.toml 的表中指定了该`"Win32_System_Diagnostics_Debug"`功能？`[dependencies.windows]`

yes,i am sure specify the "Win32_System_Diagnostics_Debug" feature in the [dependencies.windows] table in my Cargo.toml。

**Comment by tim-weis** [comment]
@bcdlbgm I cannot reproduce the issue using the following:

```toml
[package]
name = "image_optional_header64"
version = "0.0.0"
edition = "2021"

[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_System_Diagnostics_Debug",
]
```

```rust
use windows::Win32::System::Diagnostics::Debug::IMAGE_OPTIONAL_HEADER64;

fn main() {
    let _ = IMAGE_OPTIONAL_HEADER64::default();
}
```

Running

```none
cargo build
```

produces the expected output:

```none
Finished dev [unoptimized + debuginfo] target(s) in 0.04s
```

Are you observing compiler errors? Linker errors? Is this an issue with your IDE's LSP integration (in that case, what's your IDE?)? What version of the `windows` crate are you targeting? What `--target` are you compiling for?

**Comment by rasta-mouse** [comment]
Not sure if it's related, but I have found that my IDE (JetBrains CLion) does not pick up any intellisense for the entire Diagnostics::Debug:: namespace.  But only with the windows-rs crate, it's fine with windows-sys.

**Comment by ChrisDenton** [comment]
I've heard of this happening before. In that case it was due to either file size or memory size (I forget which). I believe there's an option you can change to increase the limit.

**Comment by kennykerr** [comment]
It's one of the largest modules. The trick is to split those monsters into smaller namespaces in metadata. Although the Rust compiler doesn't have a big problem with it, IDEs tend to struggle. If there's some further partitioning we can do, please suggest it here: https://github.com/microsoft/win32metadata
