### ISSUE TITLE
Release Request for windows 0.46.0 

### ISSUE THREAD

**Issue by chyyran** [microsoft/windows-rs#2369]
Now that metadata was updated I'd like a release with https://github.com/microsoft/win32metadata/issues/1453 available

Thanks

**Comment by kennykerr** [comment]
Sure thing! Did you confirm this now works as expected when testing against the repo?

**Comment by chyyran** [comment]
Yes, the function signature for `ClearRenderTargetView` is correctly typed as 

```
pub unsafe fn ClearRenderTargetView(&self, rendertargetview: D3D12_CPU_DESCRIPTOR_HANDLE, colorrgba: *const f32, prects: ::core::option::Option<&[super::super::Foundation::RECT]>)
```

on master

**Comment by kennykerr** [comment]
I just have a few things to clean up before release, like docs, but should have a release ready early next week.
