### ISSUE TITLE
Ergonomics issue with D3D11_VIDEO_PROCESSOR_STREAM and ManuallyDrop

### ISSUE THREAD

**Issue by robmikh** [microsoft/windows-rs#2386]
I'm in the middle of moving [displayrecorder](https://github.com/robmikh/displayrecorder) to v0.46 of the windows crate and I'm running into something regarding the change away from `windows::core::ManuallyDrop` to `std::mem::ManuallyDrop`.

`D3D11_VIDEO_PROCESSOR_STREAM` has a member named `pInputSurface` which is a `std::mem::ManuallyDrop<Option<ID3D11VideoProcessorInputView>>`. When calling `ID3D11VideoContext::VideoProcessorBlt`, a slice of the stream structs is passed in. This combination makes using this API cumbersome, where previously it was easy to use since `windows::core::ManuallyDrop` could be created from `&T`:

https://github.com/robmikh/displayrecorder/blob/c3cba0eba3a2e5bd64835b31a4f32f34500b8692/src/video/processor.rs#L201-L219

I worked around it by moving my `ID3D11VideoProcessorInputView` member into the `D3D11_VIDEO_PROCESSOR_STREAM` struct and placing that in a vector, calling `VideoProcesorBlt`, and then moving the input view back into self before returning the result of `VideoProcesorBlt`. It feels like I'm doing something I shouldn't.

PS: If I'm holding it wrong, please let me know 🙂

**Comment by kennykerr** [comment]
The switch to `std::mem::ManuallyDrop` comes with an implicit acknowledgement that what this involves is dangerous and you best know what you're doing. 

I would do something like this:

```rust
pInputSurface: std::mem::transmute_copy(&self.video_input),
```

That would be the strict equivalence of what you would do in C++ and pass in a raw interface pointer. You can see an example of this here:

https://github.com/microsoft/windows-rs/blob/3507dcd3b183b3dc67f7658d194635c0c5c4c92b/crates/samples/windows/direct3d12/src/main.rs#L485-L502

**Comment by robmikh** [comment]
Ah, transmute_copy works much better! I didn't think of trying that one. Thanks!
