### ISSUE TITLE
Issue calling CryptSignMessage

### ISSUE THREAD

**Issue by homer-rich** [microsoft/windows-rs#2391]
I'm trying to sign some message data with a certificate that is selected in previous code.  When I do the call though, the CRYPT_ALGORITHM_IDENTIFIER is being rewritten post-call and the function is failing.  Is there any issue with the rust code here?  I've duplicated the code in C++ as a learning process and it works fine there.

```Rust
let oid = "1.2.840.113549.2.2\0".to_owned().as_mut_ptr();
let cst_oid = windows::core::PSTR::from_raw(oid);
let crypt_sign_message_para = CRYPT_SIGN_MESSAGE_PARA {
    cbSize: u32::try_from(std::mem::size_of::<CRYPT_SIGN_MESSAGE_PARA>()).unwrap(),
    dwMsgEncodingType: X509_ASN_ENCODING.0,
    pSigningCert: fresh_cert,
    HashAlgorithm: CRYPT_ALGORITHM_IDENTIFIER { 
        pszObjId: cst_oid, 
        Parameters: CRYPT_INTEGER_BLOB::default()},
    pvHashAuxInfo: ::core::mem::zeroed(),
    cMsgCert: 1,
    rgpMsgCert: &mut fresh_cert,
    cMsgCrl: 0,
    rgpMsgCrl: ::core::mem::zeroed(),
    cAuthAttr: 0,
    rgAuthAttr: ::core::mem::zeroed(),
    cUnauthAttr: 0,
    rgUnauthAttr: ::core::mem::zeroed(),
    dwFlags: 0,
    dwInnerContentType: 0};
let secret_message: PCSTR = s!("Secret Message");
let sign_me:Vec<*const u8> = vec!(secret_message.as_ptr());
let to_be_signed_sizes_array:Vec<u32> = vec!(u32::try_from(secret_message.as_bytes().len()).unwrap());
let mut data_size = 0;
// First call sets up variables to receive the size of the signed data.
let sign_success = CryptSignMessage(
    &crypt_sign_message_para,
    windows::Win32::Foundation::BOOL::from(false),
    1,
    Some(sign_me.as_ptr()),
    to_be_signed_sizes_array.as_ptr(),
    ::core::mem::zeroed(),
    &mut data_size);
```

I've been following along with this [example](https://learn.microsoft.com/en-us/windows/win32/seccrypto/example-c-program-signing-encoding-decoding-and-verifying-a-message) and this is the prep to see how big the signed message will be.  In the C++ example they leave some of the CYRPT_SIGN_MESSAGE_PARA and CRYPT_ALGORITHM_IDENTIFIER values unset, which is more in line with what the API expects.  When I set all those values to NULL the function must fail.  

Using API Monitor I can see the post call data has changed.  For example:
![image](https://user-images.githubusercontent.com/20210789/226431129-94c0ffe7-abfd-4a6b-af2f-19ef6846b5c0.png)

**Comment by tim-weis** [comment]
`let oid = "1.2.840.113549.2.2\0".to_owned().as_mut_ptr();` creates a *temporary* `String` object that gets torn down at the end of the expression, leaving a dangling pointer, presumably into the calling thread's stack.

**Comment by homer-rich** [comment]
Thank you for your help Tim!

I was struggling with wrapping my brain around how to put that into Rust code without having the compiler complain.  I was able to see the same data before and after the call so I think the pointer is no longer dangling.  If you have any input on the code, feel free to share.  

```Rust
const OID: *const u8 = "1.2.840.113549.2.2\0".as_ptr();
let oid_ptr = OID.cast_mut();
```
