### ISSUE TITLE
Release request for windows version 0.47

### ISSUE THREAD

**Issue by ohadravid** [microsoft/windows-rs#2397]
Following https://github.com/microsoft/win32metadata/issues/1506, could you release a new version of the `windows` crate with the updated metadata?

Thanks!

**Comment by kennykerr** [comment]
Sure, I'm still waiting for an update to the Win32 metadata, but I can ask them to publish another update.

**Comment by kennykerr** [comment]
OK, was able to ingest the latest version here: https://github.com/microsoft/windows-rs/pull/2400.

**Comment by kennykerr** [comment]
This update has now been published: https://github.com/microsoft/windows-rs/releases/tag/0.47.0
