### ISSUE TITLE
Sudden change in signature of Direct3D 11 functions with optional out-pointers

### ISSUE THREAD

**Issue by Muon** [microsoft/windows-rs#2398]
### Which crate is this about?

windows

### Crate version

0.46.0

### Summary

The signature of a bunch of D3D11 functions changed suddenly. (In particular, the ones I have encountered are CreateRenderTargetView, CreatePixelShader, CreateInputLayout, CreateBuffer, CreateSamplerState, CreateBlendState). They all have in common that they have optional out-pointers which now have to be explicitly passed in. Is this intentional? These calls are now very verbose indeed to use, especially with all the Option-wrapping around the pointers.

### Actual behavior

```rust
error[E0061]: this method takes 3 arguments but 2 arguments were supplied
     |
138  |         let vertex_shader = unsafe { device.CreateVertexShader(vertex_shader_bytes, None)? };
     |                                             ^^^^^^^^^^^^^^^^^^--------------------------- an argument of type `Option<*mut Option<ID3D11VertexShader>>` is missing
```

**Comment by Muon** [comment]
I see. Nonetheless, the ergonomics of actually calling these functions now leaves something to be desired. Leaving aside the breakage, it's about the same as calling the raw function, except the out-pointers also have to be wrapped in Options. Between this and #2105 I now kinda wish `windows-sys` included vtables for these interfaces so I could wrap them myself. Optionality on the out-pointers doesn't even make sense for half of these functions. E.g. [CreateSamplerState()](https://learn.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11device-createsamplerstate) doesn't say what it does or does not do when passed a null out-pointer.

**Comment by kennykerr** [comment]
While I sympathize that calling these functions isn't particularly convenient, this is something that some Direct3D developers indicated that they need. Direct3D is not primarily focused on productivity, but if you think some of these functions shouldn't be optional, you can certainly [bring that up here](https://github.com/microsoft/win32metadata).

cc @damyanp

**Comment by kennykerr** [comment]
Yep, feel free to suggest a more suitable approach to binding such parameters but I've mostly exhausted this space having spent a lot of time threading the needle between correctness and usability in this particular scenario.
