### ISSUE TITLE
Tests fail to build without extra configuration

### ISSUE THREAD

**Issue by Muon** [microsoft/windows-rs#2406]
Due to the `component` test, it is currently not possible to simply clone and build the repository without additional setup. Building that test requires `midlrt` to be on `PATH`, which then in turn requires `cl` to be on `PATH` as well. Luckily, this part is easy to debug and fix. However, `midlrt` does not set any include directories by default, and relies on the `INCLUDE` environment variable or command line arguments to be set. Without those set, it only searches for `winrtbase.idl` in the working directory, and cryptically errors out when it can't find it.

Note that the Windows SDK installer doesn't set any of these environment variables globally.

The build script for `component` should probably do some extra work to set up the environment variables appropriately, or at least issue an error message when `INCLUDE` isn't set.

**Comment by riverar** [comment]
Hi @Muon, an easy way to get unblocked here is to fire up a Visual Studio Developer Command Prompt (or by calling `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat`), modifying the path as needed.

**Comment by kennykerr** [comment]
Yes, in order to run all tests you need to use a Visual Studio developer command prompt. I'm working on eliminating the need for these tools entirely, but we're not quite there yet.

**Comment by SamB** [comment]
So, um, where is that documented?
