### ISSUE TITLE
Feature request: `windows_bindgen::standalone` should allow specifying specific enum constants

### ISSUE THREAD

**Issue by Jake-Shadle** [microsoft/windows-rs#2409]
### Motivation

Currently, `windows_bindgen::standalone` will emit _every_ constant in an enum with no way to filter to only the ones that are needed by the crate using the bindings. As a consequence `#![allow(dead_code)]` is always emitted in the generated bindings so the user doesn't get warnings for the unused constants.

### Drawbacks

In a _vast majority_ of use cases, only a small fraction of enum values are used from any particular enum, from the relatively tame [`PAGE_`](https://learn.microsoft.com/en-us/windows/win32/memory/memory-protection-constants) flags enum to the frankly insane (at the time of this writing) 3240 item [`WIN32_ERROR`](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes). While it's not the end of the world, refining the emitted items to only the ones requested by the user means less generated code and thus less code to compile.

### Rationale and alternatives

The impact of not doing this is that crates which generate enum bindings with `windows_bindgen::standalone` will almost always be compiling code they don't use. This cost will be negligible in the grand scheme of things, but there's also no reason to give the compiler more work to do if it can be avoided. It also means that if the user manually removes the items they don't use, regenerating the bindings will need manual cleanup every time rather than just having a feature to always emit bindings without a need for manual fixup.

**Comment by kennykerr** [comment]
This one's a little trickier but agreed it would be nice if this were possible.

**Comment by kennykerr** [comment]
And here's the fix for this issue: #2430
