### ISSUE TITLE
USB mass storage detection

### ISSUE THREAD

**Issue by r3dlight** [microsoft/windows-rs#2415]
Hi,
I'm trying to detect new USB mass storages added. My final goal is to verify every files signature on the USB device before showing them to the user.  File signature is not the point here but I'd like to know if it is possible using windows-rs to lock or hide files on a USB key if the signature is not present or valid and to create a background running service.

My code is really poor for now, it compiles but when running it I already get the following error:
Error: Error { code: HRESULT(0x80070057), message: "Full text search is not supported." }

```
use windows::{core::*, Devices::Enumeration::*, Foundation::*};
use windows::{Win32::UI::WindowsAndMessaging::*};
use windows::Foundation::TypedEventHandler;
use windows::Devices::Enumeration::{DeviceWatcher, DeviceWatcherEventKind};
use windows:: Devices::Enumeration::{DeviceInformation};
fn main() -> Result<()> {

    let filter = "(System.Devices.InterfaceClassGuid:=\"{53f56307-b6bf-11d0-94f2-00a0c91efb8b}\") AND (System.Devices.InterfaceEnabled:=System.StructuredQueryType.Boolean#True) AND (System.Devices.DeviceClass:=System.StructuredQueryType.String#\"USB\")";
    let filter_hstring = HSTRING::from(filter);
    let watcher = DeviceInformation::CreateWatcherAqsFilter(&filter_hstring)?;

    let handler = TypedEventHandler::<DeviceWatcher, DeviceInformation>::new(|_sender, args| {
        //unsafe {
        //    MessageBoxA(None, s!("New USB detected !"), s!("test"), MB_OK);
        //}
        println!("Kind is {:?}", args.clone().unwrap().Kind());
        Ok(())
    });
    watcher.Start()?;
    watcher.Added(&handler)?;
    Ok(())
}
```

Cargo.toml:

```
[dependencies.windows]
windows = "0.47"
features = [
    "Devices_Enumeration",
    "Foundation_Collections",
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Storage"
]
```

**Comment by kennykerr** [comment]
The `windows` crate lets you call any Windows API so if there's a way to do this with Windows APIs then you should be able to use the `windows` crate to do it. However, the particular question is better suited to one of the following forums where you can ask questions about the Windows API:

* https://stackoverflow.com/
* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
