### ISSUE TITLE
Consider transitioning `windows-implement` and `windows-interface` to use `syn@2`

### ISSUE THREAD

**Issue by LikeLakers2** [microsoft/windows-rs#2418]
Hi! I noticed that `windows-implement` and `windows-interface` (and possibly other parts of this repository) depend on `syn@1`. Perhaps you could consider updating to use `syn@2` wherever possible?

Some things worth noting for anyone who intends to take on this suggestion:
* `syn@2`'s MSRV is Rust 1.56, up from `syn@1`'s Rust 1.31. This shouldn't be a problem, since both `windows-implement` and `windows-interface` specify a MSRV of `1.64` in their respective `Cargo.toml` files.
* Updating to `syn@2` may not be as simple as swapping the version number - there are a number of breaking changes in `syn@2`, listed at <https://github.com/dtolnay/syn/releases/tag/2.0.0>.

If you do consider to transition to `syn@2`, you have my thanks! :)

**Comment by kennykerr** [comment]
I'd like to make the switch but yes, I took a quick look and there are quite a few breaking changes that I'll have to figure out first.
