### ISSUE TITLE
Cannot use `.as_impl()` from an object boxed in an `IUnknown`?

### ISSUE THREAD

**Issue by aiongg** [microsoft/windows-rs#2419]
I'm not sure if this is user error, intended, or a bug, but here's what I've got (minimal example):

```
use windows::{
    core::{implement, AsImpl, IUnknown, Result, HSTRING},
    Foundation::{IStringable, IStringable_Impl},
};

#[implement()] // IUnknown included by default
struct MyUnknown {}
impl MyUnknown {}

#[implement(IStringable)]
struct MyStringable {}

impl IStringable_Impl for MyStringable {
    fn ToString(&self) -> Result<HSTRING> {
        Ok(HSTRING::default())
    }
}

impl MyStringable {}

fn test() {
    let unk = MyUnknown {};
    let punk: IUnknown = unk.into();
    let unk = punk.as_impl(); // no method named `as_impl` found for struct `IUnknown` in the current scope method not found in `IUnknown`

    let str = MyStringable {};
    let pstr: IStringable = str.into();
    let str = pstr.as_impl(); // no problem
}
```

My application has many COM interfaces, so for the few objects I have that are not COM implementations, I can wrap them in normal `Arc`s, but it might be nice if I could just box them into an `IUnknown` for consistency throughout the code.

**Comment by riverar** [comment]
@aiongg Try `.cast()`.

**Comment by aiongg** [comment]
> Unless I read that too quickly.

You may have. IIUC `.cast()` is for going from one COM pointer to another via `QueryInterface`. This question is about boxing with `.into()` and then taking a reference to the backing impl with `.as_impl()`.

**Comment by aiongg** [comment]
Great, thanks for clarifying. Another one for the docs, eventually (TM).
