### ISSUE TITLE
Puzzling GetPixel() issue

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#2425]
GetPixel() appears to report a frozen white color value (00 ff ff ff) regardless of cursor location:

extern "system" fn wnd_proc(hwnd: HWND, message: u32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    unsafe {
        let mut clr = COLORREF::default();
        let mut clr_last = COLORREF::default();
        let mut hdc_screen = CreatedHDC::default(); // HDC::default();

        match message as u32 {
            WM_CREATE => {
                hdc_screen = CreateICA(
                    s!("DISPLAY"),
                    PCSTR(0 as _),
                    PCSTR(0 as _),
                    Some(0 as _)
                );
                SetTimer(hwnd, ID_TIMER, 100, None);

                LRESULT(0)
            }
            WM_DISPLAYCHANGE => {
                DeleteDC(hdc_screen);
                hdc_screen = CreateICA(
                    s!("DISPLAY"),
                    PCSTR(0 as _),
                    PCSTR(0 as _),
                    Some(0 as _)
                );

                LRESULT(0)
            }
            WM_TIMER => {
                let mut pt = POINT::default();
                GetCursorPos(&mut pt);
                println!("{} {}", pt.x, pt.y);
                clr = GetPixel(hdc_screen, pt.x, pt.y);
                //println!("{:?}", clr);
                let red   = clr.0 & 0x000000ff; // GetRValue(clr) is a macro
                let green = (clr.0 & 0x0000ff00) >> 8;
                let blue  = (clr.0 & 0x00ff0000) >> 16;
                println!("{:02X} {:02X} {:02X}", red, green, blue);

                if clr != clr_last {
                    clr_last = clr;
                    InvalidateRect(hwnd, None, false);
                }

                LRESULT(0)
            }

**Comment by kennykerr** [comment]
That sounds like a good question for https://stackoverflow.com/ or https://docs.microsoft.com/en-us/answers/topics/windows-api.html.

**Comment by MRahilly** [comment]
It is Petzold's WhatClr still working well in C.
