### ISSUE TITLE
Why Option of raw pointer is used?

### ISSUE THREAD

**Issue by bigdogs** [microsoft/windows-rs#2432]
hi,

When I upgrade windows-rs from `0.39` to `0.48`, there are too many errors like this:

![image](https://user-images.githubusercontent.com/20614926/230337857-83519747-3f06-4b57-8a91-2e9b93b2a008.png)

Parameters are changed form `*const c_void` to `Option<*const c_void>`,  But I didn't get why this is necessary.  AFAIK Option<*const c_void> didn't have niche optimization, because pointer in Option could still be null.  I can't see any benefit of `Option<*const c_void>` over `*const c_void`  except bigger type size :(

**Comment by kennykerr** [comment]
These parameters were subsequently marked as optional by the [win32 metadata](https://github.com/microsoft/win32metadata) project:

```C#
[DllImport("ADVAPI32.dll", ExactSpelling = true, PreserveSig = false, SetLastError = true)]
[SupportedOSPlatform("windows5.1.2600")]
public unsafe static extern BOOL CreateProcessAsUserW([Optional][In] HANDLE hToken, [Optional][In][Const] PWSTR lpApplicationName, [Optional][In][Out] PWSTR lpCommandLine, [Optional][In] SECURITY_ATTRIBUTES* lpProcessAttributes, [Optional][In] SECURITY_ATTRIBUTES* lpThreadAttributes, [In] BOOL bInheritHandles, [In] PROCESS_CREATION_FLAGS dwCreationFlags, [Optional][In] void* lpEnvironment, [Optional][In][Const] PWSTR lpCurrentDirectory, [In] STARTUPINFOW* lpStartupInfo, [Out] PROCESS_INFORMATION* lpProcessInformation);
```

That metadata is then used to generate these Rust bindings. I'm working on a plan to stabilize metadata so this sort of change should be less common, but using `Option` does make it simpler to call such APIs since you can pass `None` for many such parameters. If you prefer to use raw bindings then you may want to consider the `windows-sys` crate:

https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html

**Comment by bigdogs** [comment]
Hi, 
thanks for the quick reply, I'm not complaining about the break changes,  just wondering if  `Option<*const void>` is reasonable enough  for rust api ffi design.

For normal rust ffi,  we either have `Option<&T>` or `*const T`.   then user can use this api in rust style(Option<&T>),  or ffi style(*const T)

`Option<*const T>` seems kind of wired,   it gives the user three options (`None/Some(ptr::null())/Some(ptr::nonnull())`), but `None/Some(ptr::null)`  are actually the same, which may somehow confusing user.  


> but using `Option` does make it simpler to call such APIs since you can pass `None` for many such parameters
 `ptr::null()`  can aslo handle this case well (

At first I thought there was some special reason for this change, now I know that is caused by definition of upstream metadata

**Comment by kennykerr** [comment]
Yes, it may make more sense to use `Option<std::ptr::NonNull>` for these parameters - I'm just not sure whether that would make it a little harder to call such APIs in practice, but I can experiment with that.
