### ISSUE TITLE
Bug: `MapViewOfFile` returns an `isize` in 0.48

### ISSUE THREAD

**Issue by sunfishcode** [microsoft/windows-rs#2436]
### Which crate is this about?

windows-sys

### Crate version

0.48.0

### Summary

It appears in 0.48 that `MapViewOfFile` changed from [returning `*mut c_void`](https://docs.rs/windows-sys/0.45.0/windows_sys/Win32/System/Memory/fn.MapViewOfFile.html) to [returning `MEMORYMAPPEDVIEW_HANDLE`](https://docs.rs/windows-sys/latest/windows_sys/Win32/System/Memory/fn.MapViewOfFile.html), which is an `isize`.

According to the [`MapViewOfFile` documentation], the return type is `LPVOID` and the return value does represent an address. Representing it as a pointer would more convenient for typical use cases which use it as a pointer, and would be friendlier to strict provenance checks.

[`MapViewOfFile` documentation]: https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile

**Comment by ChrisDenton** [comment]
See also https://github.com/microsoft/win32metadata/issues/561 where this change was made

**Comment by sunfishcode** [comment]
The reasoning about strict provenance in #1643 seems to be that it's ok that handles are represented as `isize` because they're never used as pointers by applications.

However now, it seems there exists a thing which is a handle, and that is also used as a pointer by applications.

**Comment by riverar** [comment]
Looks like a metadata bug and should have never been marked as returning a handle. Will re-open that bug.

**Comment by kennykerr** [comment]
Looks like this was tweaked in the Win32 metadata https://github.com/microsoft/win32metadata/issues/561 so I'll close this - let me know if there's anything else you need.
