### ISSUE TITLE
Shell extensions?

### ISSUE THREAD

**Issue by duckfromdiscord** [microsoft/windows-rs#2451]
This is my first time working directly with the Windows API so please bear with me.

How do I make a shell extension w/ Rust and preferably `windows`? I'd rather not use `windows-sys` if I don't have to. I want to create a shell extension that can register in Windows and allow the Details page to be modified with my own values.

I am thinking I need to use this interface and function: [IPropertyStore::SetValue](https://learn.microsoft.com/en-us/windows/win32/api/propsys/nf-propsys-ipropertystore-setvalue?source=recommendations)

So I guess my question is how can I make, _with Rust_, a shell ext that will check for a certain file extension, and if it's there, use the data in that file, do something with it, and output details into the details pane?

There doesn't seem to be an example for a shell extension, so I have to start from scratch and I am kinda lost. I'm assuming I'd make a `lib.rs` and put something there?

**Comment by kennykerr** [comment]
This is more of a general programming question. I'd suggest https://learn.microsoft.com/ or https://stackoverflow.com/ to get started.
