### ISSUE TITLE
Add `#[allow(clippy::string_lit_as_bytes)]` in w! macro to silence clippy

### ISSUE THREAD

**Issue by Centri3** [microsoft/windows-rs#2453]
### Motivation

This is a false positive, as changing this b"$s" will simply convert an `&str` with the contents "$s" to bytes, not the input.

### Drawbacks

None.

### Rationale and alternatives

Using the paste macro to do this instead, but depending on something for just two lines of code is, well, a bit silly.

### Additional context

While this is allow by default, Embark's standard lints (which few copy-paste into their own, unrelated projects as the style is quite nice) has this as a warn, which requires this to be overridden below. This isn't ideal, as in many cases this lint works, and is cleaner.

**Comment by Centri3** [comment]
It also appears this is an "issue"(?) with the h! macro as well.

**Comment by kennykerr** [comment]
Thanks! I played around with non-default clippy warnings and the trouble I see is that there is a great deal that would need to be handled so I'm not sure about the wack-a-mole approach.

**Comment by Centri3** [comment]
I think I will close this here and bring it up with clippy instead, as that seems more reasonable.
