### ISSUE TITLE
Wdk_Foundation missing from 0.48.0 crate

### ISSUE THREAD

**Issue by jxy-s** [microsoft/windows-rs#2455]
Forgive me if I'm being naive but it appears there are missing features in the publicly available crate that is listed here:
https://github.com/microsoft/windows-rs/blob/master/crates/libs/sys/Cargo.toml#L25-L33

For reference:
![image](https://user-images.githubusercontent.com/11687482/232691540-3e2b0829-a992-44cb-8fbe-5d2618a32fb2.png)

I'm specifically looking to consume the WDK information, and some of it appears to be missing? Is this intentional for now or an oversight somewhere?

**Comment by jxy-s** [comment]
Thanks @kennykerr! I'll give this a try this afternoon.

I'm very interested in more windows kernel support for Rust. Is there information on how I can get involved helping exposing more APIs?

**Comment by kennykerr** [comment]
Sure, the metadata for these APIs is provided by this repo:

https://github.com/microsoft/wdkmetadata

You can get involved there in adding more API coverage.
