### ISSUE TITLE
Make using LocalFree more ergonomic with types other than HLOCAL

### ISSUE THREAD

**Issue by jrmuizel** [microsoft/windows-rs#2464]
It seems like it's relatively common for APIs to return strings that need to be freed with LocalFree.
e.g. [`FormatMessage`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage), [`ConvertSidToStringSidA`](https://learn.microsoft.com/en-us/windows/win32/api/sddl/nf-sddl-convertsidtostringsida), [`SHGetFolderPathA`](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpatha). Right now it seems like you need to go through a casting dance to get LocalFree to accept the `LPSTR`s

**Comment by mikebattista** [comment]
https://github.com/microsoft/win32metadata/issues/1540
