### ISSUE TITLE
Feature request: Win32 BOOL+GetLastError() mapping to Result

### ISSUE THREAD

**Issue by talagrand** [microsoft/windows-rs#2467]
### Motivation

It's very helpful that both HRESULT/NTSTATUS/WIN32_ERROR-returning functions are mapped to returning a Result so standard error-handling conventions can be used against them. Request the same treatment for Win32  BOOL + GetLastError()-convention functions as well.

### Drawbacks

Performance? Though there's windows-sys and HRESULTs call the error info APIs.

**Comment by kennykerr** [comment]
Last time I checked there were a few issues with the Win32 metadata that prevented this transformation, but it's been a while so I'll check again and hopefully we can turn it on.
