### ISSUE TITLE
Result handling prevents the use of positive values (S_FALSE for example).

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#2470]
When a method can return `S_FALSE` or you yourself needs to return it it's seems tricky to make it work when you return a `Result`.
When returning it yourself it seems you can do `Err(windows::core::Error::From(S_FALSE))` to make it work.
But when you receive it seems to just end up as `Ok` making it impossible to know if you got `S_OK` or `S_FALSE`.

An example is: `windows::Windows::Win32::Media::DirectShow::IEnumPins::Next`

https://learn.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-ienumpins-next
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Media/DirectShow/struct.IEnumPins.html#method.Next

Now you can make do without checking the return value by always using a `[None]` and checking if it's `None`,
or by checking the `pcfetched` value.

But there might be functions which don't have that possibility so thought it worth bringing up.

**Comment by tim-weis** [comment]
This has been discussed in #1065. If the specific API you're using slipped through, consider [opening an issue](https://github.com/microsoft/win32metadata/issues) in the [win32metadata](https://github.com/microsoft/win32metadata) repository.

**Comment by Zerowalker** [comment]
Ah will check it out and close this issue then.
Thanks!
