### ISSUE TITLE
Bug: Unneeded reference?

### ISSUE THREAD

**Issue by mominul** [microsoft/windows-rs#2473]
### Which crate is this about?

windows

### Crate version

0.48.0

### Summary

The trait binding for `ITfTextInputProcessor` is:

```rust
trait ITfTextInputProcessor_Impl {
    fn Activate(&self, ptim: Option<&ITfThreadMgr>, _tid: u32) -> Result<()>;
    fn Deactivate(&self) -> Result<()>;
}
```

But the signature of the `Activate()` method in c++ is:
```c++
HRESULT Activate(
  [in] ITfThreadMgr *ptim,
  [in] TfClientId   tid
);
```

As far as I know, `ITfThreadMgr` is itself a smart pointer, so why an additional reference is being kept? Shouldn't be this more appropriate?
```rust
fn Activate(&self, ptim: Option<ITfThreadMgr>, _tid: u32) -> Result<()>;
```

**Comment by kennykerr** [comment]
`ptim: Option<ITfThreadMgr>` would require an additional reference that would be consumed by the function whereas `ptim: Option<&ITfThreadMgr>` correctly allows the caller to pass a reference to the function without having to inject an `AddRef`/`Release` bump.

**Comment by mominul** [comment]
Thanks for the explanation! 😊
