### ISSUE TITLE
QueryContextAttributesW build OK, but not QueryContextAttributesExW

### ISSUE THREAD

**Issue by Geobert** [microsoft/windows-rs#2474]
Hi, 

I’m using windows-rs in a crate of mine to do some SPNEGO authentication.

I’m trying to get the user name attached to the SecurityContext, but `QueryContextAttributesW ` gives me `SEC_E_UNSUPPORTED_FUNCTION` error (I’m sure I’m using the latest Context returned by `AcceptSecurityContext`).

So I wanted to try QueryContextAttributesExW, but it doesn’t link.

I have to add that I’m creating a static lib to be consumed by C++ code (using cxx crate) because I tried a simple `main()` project with QueryContextAttributesExW and it builds fine.

What am I missing?

**Comment by Geobert** [comment]
Ok, I workaround it by doing something silly: using the SECPKG_ATTR_NAMES flag with `QueryContextAttributesW` and it works

**Comment by Geobert** [comment]
Thanks for your answer!

> `dumpbin`

Which command to run? I’m not familiar with `dumpbin` :)

**Comment by kennykerr** [comment]
`dumpbin` is a tool that ships with Visual Studio. I usually just use the "x64 Native Tools Command Prompt" provided by Visual Studio. Here's an example:

```
C:\>where dumpbin
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\dumpbin.exe

C:\>dumpbin /exports %windir%\System32\sspicli.dll | findstr /i QueryContextAttributes
         52   30 00022160 QueryContextAttributesA
         53   31 00009290 QueryContextAttributesExA
         54   32 00009470 QueryContextAttributesExW
         55   33 00001330 QueryContextAttributesW

C:\>dumpbin /exports %windir%\System32\secur32.dll | findstr /i QueryContextAttributes
         48   2F          QueryContextAttributesA (forwarded to SSPICLI.QueryContextAttributesA)
         49   30          QueryContextAttributesW (forwarded to SSPICLI.QueryContextAttributesW)
```

**Comment by Geobert** [comment]
running
dumpbin /exports .\libours_cxx.a | findstr /i QueryContextAttributes

gives
```
                  QueryContextAttributesW
                  QueryContextAttributesA
```
But I doubt that’s what you want :-/

**Comment by riverar** [comment]
Metadata looks okay (enough to work). Did you perhaps pass in the wrong `ulAttribute`? 

The docs state:
> SEC_E_UNSUPPORTED_FUNCTION | 0x80090302 | The function failed. The value of the ulAttribute parameter is not valid.

**Comment by Geobert** [comment]
> Metadata looks okay (enough to work). Did you perhaps pass in the wrong `ulAttribute`?
> 
> The docs state:
> 
> > SEC_E_UNSUPPORTED_FUNCTION | 0x80090302 | The function failed. The value of the ulAttribute parameter is not valid.

I was using SECPKG_ATTR_CREDS

https://learn.microsoft.com/en-us/windows/win32/api/sspi/nf-sspi-querycontextattributesw

It says supported on the server only. But I’m running from a machine which host the active directory server and is domain controller as well.

Anyway, as I said, I got the needed information using SECPKG_ATTR_NAMES which ended being documented in yet another page for the same function: https://learn.microsoft.com/en-us/windows/win32/secauthn/querycontextattributes--kerberos
