### ISSUE TITLE
Bug: GetRegisteredRawInputDevices doesn't expect an array

### ISSUE THREAD

**Issue by Godnoken** [microsoft/windows-rs#2481]
### Which crate is this about?

windows

### Crate version

0.49.0

### Summary

Hi there, according to [Microsoft Docs](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getregisteredrawinputdevices), we should expect an array of `RAWINPUTDEVICE` structures when we call `GetRegisteredRawInputDevices`, however the function in [window-rs](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Input/fn.GetRegisteredRawInputDevices.html) is set up to be a singular `RAWINPUTDEVICE`. `RegisterRawInputDevices` [seems](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Input/fn.RegisterRawInputDevices.html) to be doing this already by expecting a &[RAWINPUTDEVICE].

### Expected behavior

`GetRegisteredRawInputDevices` should expect an array of `RAWINPUTDEVICE` structures

### Actual behavior

`GetRegisteredRawInputDevices` expects a singular `RAWINPUTDEVICE`

### Additional comments

Thank you for this amazing crate!

**Comment by Godnoken** [comment]
Aha! So if I understood this correctly, the code generator spits out the wrong code because the parameter is optional. And if so, I assume there's no way for me to use the function correctly at this moment? Cheers.

**Comment by kennykerr** [comment]
No, you can still use it. You just need to use [as_mut_ptr](https://doc.rust-lang.org/stable/core/primitive.slice.html#method.as_mut_ptr) to get a mutable pointer to your array.

**Comment by kennykerr** [comment]
> the code generator spits out the wrong code

Specifically the code generator is being conservative, but it is producing correct code.

**Comment by Godnoken** [comment]
> No, you can still use it. You just need to use [as_mut_ptr](https://doc.rust-lang.org/stable/core/primitive.slice.html#method.as_mut_ptr) to get a mutable pointer to your array.

Oh, my bad. That's great, got it to compile with;


```
 let mut prawinputdevices = &mut vec![];
 let mut puinumdevices = 0;
 let cbsize = size_of::<RAWINPUTDEVICE>() as u32;

 let result = GetRegisteredRawInputDevices(prawinputdevices.as_mut_ptr(), &mut puinumdevices, cbsize);
```

However, I'm stumped by the results.

`prawinputdevices` doesn't contain anything.
`result` is returning 0.
`puinumdevices` is returning 2.

The function is supposed to return -1 if it fails and 0 or the number of `RAWINPUTDEVICE` structures written to the buffer.

How can it find two devices, yet not write anything to the buffer? I assume I'm doing something stupid or not quite understanding something here.

**Comment by riverar** [comment]
Be aware your vector has no capacity/is empty (see: `with_capacity`), and you told it you want 0 devices via the in/out `puinumdevices`. So it obliged.

**Comment by Godnoken** [comment]
Seems I spoke too soon. I'm way too green to dabble with this, hehe.

> Be aware your vector has no capacity/is empty (see: `with_capacity`), and you told it you want 0 devices via the in/out `puinumdevices`. So it obliged.

Ah. I presumed that using` vec![]` would handle the capacity on its own. I also thought that `puinumdevices` set to 0 would simply write all found devices to the buffer.

Interestingly though,

```
let mut prawinputdevices = &mut Vec::with_capacity(10);
let mut puinumdevices = 10;
```

Won't write anything to the buffer either. `result` returns 2 now, though.

**Comment by Godnoken** [comment]
It seems that it can not be a Vec at all.

`&mut [zeroed(), zeroed()]`

Works just fine. Although I believed that the function would be able to write all found raw input devices without me specifying exactly how many I expect there to be. I assume I understood it wrong.

Thank you both very much for your help.

**Comment by kennykerr** [comment]
`with_capacity` doesn't actually change the length, only the allocated capacity for efficiency. You should use something like `set_len`.

**Comment by Godnoken** [comment]
Haha, thank you once again for correcting me. This has been very helpful 😄
