### ISSUE TITLE
Generalize the `component`/`standalone` functions to support namespace/glob generation

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#2492]
### Which crate is this about?

windows-bindgen

### Crate version

0.49

### Summary

One of my custom crates based on `windows-bindgen` sets `gen.cfg = false`, resulting in no `#[cfg]`s on `windows-bindgen 0.48` (and `windows-metadata`):

https://github.com/MarijnS95/DirectX-Headers/blob/9767b2895cdfc10d4aa72df6efd4ef24d3945017/.rust/api_gen/src/main.rs#L38

After upgrading to `0.49` however, without changing anything else, the API is riddled with `#[cfg]` guards, forcing me to default-define features within my own crate to use the bindings, even if `gen.cfg = false` remains in place:

https://github.com/MarijnS95/DirectX-Headers/commit/9767b2895cdfc10d4aa72df6efd4ef24d3945017

### Toolchain version/configuration

N/A

### Reproducible example

```rust
git clone https://github.com/MarijnS95/DirectX-Headers
cd DirectX-Headers
dotnet build .metadata
cargo r -p api_gen
```

### Crate manifest

```toml
[dependencies]
windows-bindgen = "0.49"
windows-metadata = "0.49"
```

### Expected behavior

No `#[cfg]` in autogenerated code, like in `windows-bindgen 0.48`.

### Actual behavior

`#[cfg]` guards show up in autogenerated code.

**Comment by kennykerr** [comment]
Thanks, but there's a reason that `Gen` isn't documented. 😉 

https://docs.rs/windows-bindgen/

It isn't tested directly as it is a rather complex beast that is used under the hood by some of the other public APIs, which are tested. I'm trying to provide higher level abstractions that are simpler to use and support, hence the `component` and `standalone` functions. 

Anyway, I'm happy to take a quick look at this issue if you can share a minimal repro (no external dependencies) and perhaps provide more of the underlying functionality through simpler functions.

**Comment by kennykerr** [comment]
Actually, the `cfg` field is no longer used. I should just remove it.

**Comment by MarijnS95** [comment]
> Thanks, but there's a reason that `Gen` isn't documented. wink
> 
> https://docs.rs/windows-bindgen/

Is `component()` the way to go then?

> It isn't tested directly as it is a rather complex beast that is used under the hood by some of the other public APIs, which are tested. I'm trying to provide higher level abstractions that are simpler to use and support, hence the `component` and `standalone` functions.

Will `component()` remove the `cfg()`s?

> Anyway, I'm happy to take a quick look at this issue if you can share a minimal repro (no external dependencies).

That repro is about as minimal as I can make for you, it's a simple checkout and following or undoing the change to have one of the bindgen versions.

> I may be able to provide more of the underlying functionality through simpler functions.

That is appreciated, yes.

> Actually, the `cfg` field is no longer used. I should just remove it.

Heh.

**Comment by kennykerr** [comment]
I haven't looked at your repo so I don't know what you're trying to achieve. Take `component` a spin and see if it meets your needs.

**Comment by MarijnS95** [comment]
@kennykerr it's a big repo and an unnecessary as the Agility SDK headers have already been absorbed into `win32metadata`. It was however an easy place to demonstrate the issue, as I have it in another (smaller) crate which is not yet published.

I did take `component()` for a spin but it only generates for the given namespace. I'd love if it could help me recursively list and/or generate the namespaces. Other than that, no `cfg` issues and the `impl` is inlined so this is a shorter, workable solution for me (as long as I hardcode the namespaces in `File`).

**Comment by MarijnS95** [comment]
I did find one issue: the inlined `impl` is no longer behind a `cfg` too, and that requires `"implement"` to be enabled on the Windows crate as well.

**Comment by kennykerr** [comment]
Eventually, I'd like to generalize the `component`/`standalone` functions as they largely do the same thing now. I'll leave this open to deal with that.

**Comment by kennykerr** [comment]
This is now complete. Feel free to open a new issue if you encounter any problems.

**Comment by MarijnS95** [comment]
@kennykerr indeed, this seems to work now: https://github.com/Traverse-Research/amd-ext-d3d-rs/compare/riddle.

Thanks!

**Comment by kennykerr** [comment]
Sweet, looks like that simplified things for you. 👍

**Comment by MarijnS95** [comment]
@kennykerr by the way that repo is a prime example of where I'd like to apply https://github.com/microsoft/windows-rs/issues/1835 :wink:

**Comment by ChrisDenton** [comment]
I'll admit that for rustc having a lib entry point for riddle (as well as the exe) would simplify things a lot with the build system. But it's doable without.

My main concern though is having to manually sync the metadata files.

**Comment by kennykerr** [comment]
> My main concern though is having to manually sync the metadata files.

Yep, let me know if you have any suggestions. I just needed to untangle it from the metadata reader, but I'm not opposed to publishing a "latest metadata" library crate - unfortunately Rust doesn't have a binary package model that really fits.

**Comment by kennykerr** [comment]
> I'll admit that for rustc having a lib entry point for riddle (as well as the exe) would simplify things a lot with the build system. But it's doable without.

We could conceivably have a library version, but I found that everywhere it was used it invariably just got wrapped by an exe to automate code gen more easily. Now, all you need is `riddle.exe -etc bindings.txt` and you're done. But shoot me your suggestions.

**Comment by MarijnS95** [comment]
> Now, all you need is `riddle.exe -etc bindings.txt` and you're done. But shoot me your suggestions.

Indeed, this didn't cross my mind but it's much more sensible to delete the `api_gen` crate and just tell users to run `riddle -etc bindings.txt`.

Just looking of a standard way to do that though. Script in the root, or just a message in `CONTRIBUTING.md` that is also duplicated in the CI to execute the same.

**Comment by riverar** [comment]
Think after a few nit passes, it'll reduce further to `riddle @bindings.rsp` or similar so I wouldn't rush to document usage quite yet.

**Comment by MarijnS95** [comment]
@riverar having a sensible default, such as how Rust's `cargo` works, would be wonderful for this

**Comment by ChrisDenton** [comment]
> > I'll admit that for rustc having a lib entry point for riddle (as well as the exe) would simplify things a lot with the build system. But it's doable without.
> 
> We could conceivably have a library version, but I found that everywhere it was used it invariably just got wrapped by an exe to automate code gen more easily. Now, all you need is `riddle.exe -etc bindings.txt` and you're done. But shoot me your suggestions.

While this is true, it does make things more complicated. I need to either a) automatically install riddle to the build directory and run it (basically wrapping it in another exe anyway) or else b) instruct contributors how to install riddle. E.g. for reproducible results that don't interfere with the users global installs, the user would do:
```
cargo install riddle@1.0.0 --root build/host/stage1
build/host/stage1/riddle -etc library/std/src/sys/windows/c/bindings.txt
```

I'd also like to be able to add a prelude to the generated file that explains how it's auto-generated and how it should be updated. This is doable but again requires wrapping riddle in another exe.

**Comment by kennykerr** [comment]
Well it sounds like you're wrapping stuff either way. Would it help signficantly if I moved everything into a `riddle-core` library crate and had `riddle.exe` just call out to that? This library would only expose a single function like `fn riddle(args: &[&str])` to keep things simple and you'd have to still open the resulting file and prepend whatever you need. But at least you can use a regular Cargo dependency and pass riddle a text file with bindings and get most of the benefits.

**Comment by MarijnS95** [comment]
@kennykerr I'd have the argument parsing in `riddle.exe` and expect a typed, self-documenting configuration struct/enum as argument to `fn riddle()`.

**Comment by kennykerr** [comment]
That's exactly what I don't want to do. 🫠

I'm proposing a middle ground for @ChrisDenton that gives him a library to simplify his build system without putting me back in the business of maintaining a code gen library.

**Comment by ChrisDenton** [comment]
@kennykerr yeah, that'd be fine. It's just easier to manage a lib dependency in our build system than it is to build and run a third party exe. To be clear though, it's not a big deal either way. I'd figure something out.

**Comment by MarijnS95** [comment]
> That's exactly what I don't want to do. 🫠

What's so bad about having a representative struct with typed members over passing a slice of string arguments? It effectively means cutting `riddle`'s `run()` in two and have a `struct` as interface between the parsing and executing logic.
