### ISSUE TITLE
Standalone code generation depends on extension types and functions

### ISSUE THREAD

**Issue by poliorcetics** [microsoft/windows-rs#2517]
In recent commits (those after `windows-bindgen` 0.49), the `standalone` function is now able to handle `TypeKind::Class` and `TypeKind:: Interface` whereas it was `unimplemented!()` before.

I will need those for https://github.com/GuillaumeGomez/sysinfo/pull/950 

Not particularly urgent but IIRC releases are done on request for the crates here ?

**Comment by poliorcetics** [comment]
Trying it out now

**Comment by poliorcetics** [comment]
It makes bindings impossible to compile for non-sys versions because they're used in the produced bindings

**Comment by poliorcetics** [comment]
I'll push the sysinfo branch

**Comment by kennykerr** [comment]
Thanks, the minimal repro involves generating bindings for `Windows.Win32.Security.Authorization.ConvertSidToStringSidW` with `windows_bindgen::standalone_win`.

**Comment by MarijnS95** [comment]
As mentioned in https://github.com/microsoft/windows-rs/issues/1720#issuecomment-1523415504 the standalone bindings should include pretty much everything from the extension file (e.g. https://github.com/microsoft/windows-rs/blob/78a0dbea48f856b03f3e7e650e0e385047d8a10b/crates/tools/riddle/src/rust/extensions/mod/Win32/Foundation/BOOL.rs), including `From<>` implementations (but I never got to report that as standalone issue per request, sorry!).

Not sure if this is still an issue since `riddle`, though.

**Comment by poliorcetics** [comment]
This has been fixed now, I tried it

**Comment by riverar** [comment]
Thanks for following up @poliorcetics

**Comment by poliorcetics** [comment]
Thanks for fixing it !

**Comment by MarijnS95** [comment]
Yup, looks to be fixed indeed :+1:

**Comment by MarijnS95** [comment]
Hmm no, this is not true. I'm using the `git` version at 41ad38d8c and no `From<BOOL> for bool` from the extensions is generated: https://github.com/microsoft/windows-rs/blob/master/crates/libs/bindgen/src/rust/extensions/mod/Win32/Foundation/BOOL.rs.

Only this is generated:

https://github.com/MarijnS95/windows-rs/blob/bef7648ca724ea221e852f30f2cd114df6c5b3d5/crates/samples/windows/dxc/src/bindings.rs#L10-L31

There's no `BOOL::ok()` here. Bindings are generated with:

https://github.com/MarijnS95/windows-rs/blob/bef7648ca724ea221e852f30f2cd114df6c5b3d5/crates/samples/windows/dxc/bindings.txt#L1-L23

**Comment by MarijnS95** [comment]
@kennykerr ah thanks, I've overlooked that. Sure, but only for types that themselves live in `windows-core`? Is that true for every type that is currently extended?

**Comment by kennykerr** [comment]
No. There's no easy fix - that's why I'm generally cautious about adding handwritten extensions.
