### ISSUE TITLE
Why are certain structures like SYSTEM_HANDLE_INFORMATION not supported?

### ISSUE THREAD

**Issue by bcdlbgm** [microsoft/windows-rs#2531]
What I want to say is that when I use NtQuerySystemInformation, I didn't find the SYSTEM_HANDLE_INFORMATION structure to parse the pointer in the returned parameters. Why is it not supported? Do I need to manually set up such a structure to parse the parameters?

**Comment by riverar** [comment]
It's not a documented struct or in public headers.

**Comment by kennykerr** [comment]
The `windows` and `windows-sys` crates are generated from [metadata describing the public APIs](https://github.com/microsoft/windows-rs/tree/master/crates/libs/metadata/default) for the operating system. If it's not a public API then it won't be included here.

**Comment by riverar** [comment]
Want to throw out there that in these cases, you could generate your own metadata, say from [Process Hacker headers](https://github.com/winsiderss/phnt/blob/7c1adb8a7391939dfd684f27a37e31f18d303944/ntexapi.h#L1842-L1857), and use it with this Rust crate. Check out https://withinrafael.com/2023/01/18/generating-metadata-for-the-windows-crate/ for more information.
