### ISSUE TITLE
Release of 0.50 cargo crate

### ISSUE THREAD

**Issue by wbenny** [microsoft/windows-rs#2536]
Hi,

first off, huge sorry for polluting the issue tracker, but I was unable to contact you directly, @kennykerr.

My simple question is: is there an estimate on when will be 0.50 package released to crates.io? It's already marked here on github as released. My huge interest stems from the new Wdk features.

**Comment by kennykerr** [comment]
[Releases](https://github.com/microsoft/windows-rs/releases) are by request only. The [0.50 release](https://github.com/microsoft/windows-rs/releases/tag/0.50.0) was only for the `windows-core` crate. 

Note that you can simply point your project to github and take the new WDK support for a spin. That is preferred anyway, as you can kick the tires without needing a release and report any issues or missing features before publishing another release for production use. 

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
