### ISSUE TITLE
First example on GitHub project main page is not working

### ISSUE THREAD

**Issue by MBODM** [microsoft/windows-rs#2537]
1) Did `cargo init winapitest`

2) Did copy&paste code from this project´s main page (`Cargo.toml` and `main.rs`)

3) Did `cargo run` or `cargo build`

4) Output:
```
error[E0277]: the `?` operator can only be applied to values that implement `Try`
  --> src\main.rs:16:9
   |
16 |         SetEvent(event)?;
   |         ^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `BOOL`  
   |
   = help: the trait `Try` is not implemented for `BOOL`

error[E0277]: the `?` operator can only be applied to values that implement `Try`
  --> src\main.rs:17:9
   |
17 |         WaitForSingleObject(event, 0)?;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `WIN32_ERROR`
   |
   = help: the trait `Try` is not implemented for `WIN32_ERROR`

error[E0277]: the `?` operator can only be applied to values that implement `Try`
  --> src\main.rs:18:9
   |
18 |         CloseHandle(event)?;
   |         ^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `BOOL`
   |
   = help: the trait `Try` is not implemented for `BOOL`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `winapitest` due to 3 previous errors
```

5) Assumption: `Result<()>` is a type alias for `Result<(), Error>` whereas some stuff inside the used methods not fullfills the Error trait. Since i´m a bit in hurry at the moment, i had no time to check it. But nonetheless imo a simple example on the main page should work out-of-the-box.

**Comment by kennykerr** [comment]
The GitHub repo is always primed for the next release. You can for example look at the readme for the current release here:

https://github.com/microsoft/windows-rs/tree/0.48.0

Alternatively, you can find the readme for the current release here:

https://crates.io/crates/windows

**Comment by MBODM** [comment]
Hey @kennykerr,

thx for your fast reply! But i don’t really understand what you wanna say, tbh. The example on the frontpage combines example code and version into a single block which should match), since the version 0.4.8 is declared in the .toml file, which is part of the example. So the example‘s source code should match the crate‘s version, ofc.

Maybe you can further explain what you try to say, or what should best the reason why the example not works.

Best regards

**Comment by kennykerr** [comment]
It's a little confusing I understand. The samples in the readme are checked by CI against the latest in github but that isn't able to validate the toml code. That gets bumped when I prep for the next release and update all the version numbers. 

Anyway, if you need an example to get started go here:

* https://crates.io/crates/windows

If you need more samples go here:

* https://github.com/microsoft/windows-rs/tree/0.48.0/crates/samples

For general questions about Rust go here:

* https://stackoverflow.com/search?q=windows-rs

**Comment by MBODM** [comment]
> It's a little confusing I understand. The samples in the readme are checked by CI against the latest in github but that isn't able to validate the toml code. That gets bumped when I prep for the next release and update all the version numbers.
> 
> Anyway, if you need an example to get started go here:
> 
> * https://crates.io/crates/windows
> 
> If you need more samples go here:
> 
> * https://github.com/microsoft/windows-rs/tree/0.48.0/crates/samples
> 
> For general questions about Rust go here:
> 
> * https://stackoverflow.com/search?q=windows-rs

Maybe we have some miscommunication here. 😄 I totally understand that the examples in the READMEs, and the READMEs itself, are released together and fit each other. At least that’s what i get out of your answer.

But what i try to tell you: Your example code is not working.

The example in https://crates.io/crates/windows or the frontpage (it’s the same code and both target 0.4.8) is simply not working.

Steps to produce:

- Go to https://crates.io/crates/windows
- Copy first example
- Run
- Error

Best regards

**Comment by riverar** [comment]
Hey @MBODM. The GitHub Readme and the crates.io Readme are not the same. I've verified the crates.io Readme examples work. Maybe you mixed code between the two by mistake? (The GitHub Readme is meant to be used against master, not 0.48.)

Sorry for the confusion; we're currently working to improve the Readme situation.

**Comment by MBODM** [comment]
Does this matter even at all, when i use a crates.io example code, together with the crate that is listed on crates.io ?

I mean, i use
- example code of crates.io site
- corresponding crate from crates.io site (cargo command of right side menu)
- example code says 0.4.8
- actual cargo version used is 0.4.8 (cargo command of right side menu on crates.io)

and it does not work.

I understand what you said about master branch and example code on GitHub page. But when i go to crates.io, use the example code there, together with the given crate install command on right side menu…. should it not work then?

**Comment by MBODM** [comment]
![D8E8B152-FB56-41F8-94F5-801CC03D114F](https://github.com/microsoft/windows-rs/assets/19464647/cd4ae9ff-0c11-4fc0-a4dd-3e5adde0c19f)
![4EB6CEE5-9068-4F72-B614-CF9D8325353C](https://github.com/microsoft/windows-rs/assets/19464647/8a70ed83-2485-4f0f-a349-70384d62dd9d)

**Comment by riverar** [comment]
@MBODM Can you provide your `main.rs` and `Cargo.toml` so we can get a better idea of what's going on? Thanks!

**Comment by MBODM** [comment]
Btw, You say GitHub‘s example and example of crate.io differs.

![856C3691-C6D1-49D7-80E0-1D7EB6F2DFDE](https://github.com/microsoft/windows-rs/assets/19464647/53dff98f-c087-4d4d-a78f-1977fe616700)

Where? Am i blind?

**Comment by riverar** [comment]
Here's the GitHub Readme before today's changes:
https://github.com/microsoft/windows-rs/blob/97efa322720a1aa84bbd437bfc84c3c984e978dc/docs/readme.md

Here's the crates.io Readme:
https://crates.io/crates/windows

Here's the diff before today's changes:
![image](https://github.com/microsoft/windows-rs/assets/475132/71501a06-8f25-4c53-aa16-2cfe8b63e789)

---

Here's the GitHub Readme after today's changes (https://github.com/microsoft/windows-rs/pull/2538):
https://github.com/microsoft/windows-rs/blob/master/docs/readme.md

Here's the crates.io Readme:
https://crates.io/crates/windows

Here's the diff with today's changes:
![image](https://github.com/microsoft/windows-rs/assets/475132/6c6a54ec-52d9-4ac6-b459-fd7e212c165d)

---

As you can see, in both scenarios, the Readmes do not match. The current changes between the two Readmes are not breaking.

If you provide your `Cargo.toml` and `main.rs`, we can verify you have the correct code in place. Hopefully moving forward (with today's changes) this will be less confusing!

**Comment by MBODM** [comment]
As we already learned in Breaking Bad: „All bad things must come to an end.“

This seems what happened:

- I copied the very first example code yesterday from the GitHub page. (That code had NO `ok` entries.
- I ran the example and it failed.
- I did the conversation with @kennykerr here, see above.
- @kennykerr changed the GitHub page Readme file, to make it the same as at crates.io, without stating that fact here.
- AFTER that happened i compared the crates.io and Readme file to be sure, what i had tested is the same on both. Not realizing that the code i am using is no longer the same code as 8 hours before.
- I just made sure GitHub code and crates.io code is the same. And at that point in time (after @kennykerr‘s changes) it indeed was. Ofc. But ofc i assumed the code i had at that time, was the same as on crates.io, since i checked both and they were same (without realizing @kennykerr changed it). That’s why i said i use the code from crates.io. Sinve crates.io and GitHub was completely the same (at THAT time, but not 10 hours before, when i got it).

That’s what happened and why the confusion started to grow, foremost for @riverar 

So, you can close the issue. The new `ok()` version works now (ofc) and all is fine.

But let me state one last thing here, especially targeted at @kennykerr:
After 22 years of being a developer i came to the conclusion, It is NOT funny to add silent Ninja changes to the code (commit https://github.com/microsoft/windows-rs/commit/4c88d904e76125cf9576c240b283e87de531981f), without stating that while we are discussing. It just confuses peoples like me or @riverar 

But nonetheless a happy end. Thx for your patience and best wishes!

**Comment by riverar** [comment]
Happy coding and let us know if you run into other issues or if anything else is confusing!

**Comment by MBODM** [comment]
> Apologies it wasn't clear enough. I specifically tagged this issue in #2538 so that it would show up in this timeline:
> 
> <img alt="image" width="965" src="https://user-images.githubusercontent.com/9845234/246143658-0f57f6a0-bf02-49d4-b8c1-e12850e82778.png">
> Anyway, glad you figured it out!

Great! Thx a lot!
