### ISSUE TITLE
Feature request: Add Debug derives for types in windows-metadata

### ISSUE THREAD

**Issue by KarelPeeters** [microsoft/windows-rs#2541]
### Motivation

Currently debugging and figuring out how to use the `windows-metadata` crate is cumbersome, since very few of the types it returns implement `Debug`. This was most frustrating for the structs and enums in https://github.com/microsoft/windows-rs/blob/master/crates/libs/metadata/src/reader/mod.rs and `Type` in https://github.com/microsoft/windows-rs/blob/master/crates/libs/metadata/src/reader/type.rs, but it seems that many of the types in this crate are missing Debug without a good reason.

As [the std::fmt docs](https://doc.rust-lang.org/std/fmt/index.html#fmtdisplay-vs-fmtdebug) say:

> [`fmt::Debug`](https://doc.rust-lang.org/std/fmt/trait.Debug.html) implementations should be implemented for all public types. Output will typically represent the internal state as faithfully as possible. The purpose of the [`Debug`](https://doc.rust-lang.org/std/fmt/trait.Debug.html) trait is to facilitate debugging Rust code. In most cases, using `#[derive(Debug)]` is sufficient and recommended.

### Drawbacks

This could add _some_ compilation slowdown, but that's mostly a worry for auto-generated code with thousands of types. This issue is about manually adding a couple of `#[derive(Debug)]` annotations on <50 types.

**Comment by KarelPeeters** [comment]
If this would be accepted I can submit a PR for this.

**Comment by kennykerr** [comment]
The main challenge is that the reader types are really just indexes into metadata tables and those indexes by themselves only carry offsets so a formatter could not provide much visualization without an explicit reader.

**Comment by KarelPeeters** [comment]
The ones in the `Tables` macro are not _that_ useful, but seeing their indices would still be a bit useful for debugging and especially when comparing them to when they are printed as part of the compound types.

But many of them are immediately useful: `Type` can print the full type most of the time, and similarly `Interface` and its field types, `Signature` and its field types, `Value`, ... can all print a lot of useful details, all with the derived `Debug` implementation and without the need to use the reader to get more info.

**Comment by kennykerr** [comment]
Sure, as long as that's understood I have a branch with some refactoring that includes this. Coming soon.
