### ISSUE TITLE
Bug: windows_sys::Wdk::Foundation::DRIVER_OBJECT requires feature Win32_Graphics_DirectDraw

### ISSUE THREAD

**Issue by wbenny** [microsoft/windows-rs#2543]
### Which crate is this about?

windows-sys

### Crate version

0.48.0

### Summary

`windows_sys::Wdk::Foundation::DRIVER_OBJECT` requires feature `Win32_Graphics_DirectDraw`, however that feature is missing in sys/Cargo.toml

**Comment by wbenny** [comment]
The whole DirectDraw is missing in the sys crate.
For some reason, the `pub struct MDL` is expected there - and sure, in non-sys crate, the MDL struct is in there.

**Comment by kennykerr** [comment]
I first reported this issue here: https://github.com/microsoft/wdkmetadata/issues/35

It looks like it might have been fixed, but `windows-rs` hasn't taken a Win32/Wdk metadata update in a while.

**Comment by wbenny** [comment]
Ah, good to know. Thanks!

Also, there are more discrepancies in the Wdk.

For example, in Wdk/Foundation, there is:
`pub type PDRIVER_UNLOAD = ::core::option::Option<unsafe extern "system" fn() -> ()>;`

but Wdk/System/SystemServices has:
`pub type DRIVER_UNLOAD = ::core::option::Option<unsafe extern "system" fn(driverobject: *const super::super::Foundation::DRIVER_OBJECT) -> ()>;`

also, driver dispatch routine seems off in Wdk/Foundation:
`pub type PDRIVER_DISPATCH = ::core::option::Option<unsafe extern "system" fn() -> super::super::Win32::Foundation::NTSTATUS>;` - it should accept `DEVICE_OBJECT*` and `IRP*` in the parameters.

Should I create separate issue for this, or is this addressed in the wdkmetadata already as well?

**Comment by kennykerr** [comment]
Yep if you are unsure feel free to open issues on the wdk repo.

**Comment by kennykerr** [comment]
https://github.com/microsoft/windows-rs/pull/2573 updated the repo with the latest metadata. Please kick the tires and let me know if you experience any issues.

**Comment by wbenny** [comment]
Thanks! The issue with feature gate went away, though the discrepancy between PDRIVER_UNLOAD/PDRIVER_DISPATCH types is still there.

**Comment by kennykerr** [comment]
Please open an issue on the appropriate repo.
