### ISSUE TITLE
Crash triggered with Exception 0xc0000005 when trying to read contents of CREDENTIALW

### ISSUE THREAD

**Issue by iancormac84** [microsoft/windows-rs#2555]
When trying to read the CREDENTIALW's returned by a call to CredEnumerateW, a crash occurs when trying to display the contents of the PWSTR's in some structs. The crash is triggered inside the call to wcslen. Code example can be found here: https://github.com/iancormac84/wcslen_crash.git

**Comment by kennykerr** [comment]
In future, please post a minimal repro clearly illustrating the problem. For API specific questions I suggest:

* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
* https://stackoverflow.com/questions/tagged/windows-rs

**Comment by riverar** [comment]
Here's the same issue you posted back in Oct 2022 with a fix. ;)

**Comment by riverar** [comment]
@iancormac84 Your sample is missing a level of pointer indirection--recall the function is providing a _pointer to an array of pointers to credentials_. You want something like this instead:

```rust
fn main() -> windows::core::Result<()> {
    let mut count = 0;
    let mut credentials_ptr = std::ptr::null_mut();
    unsafe {
        CredEnumerateW(
            PCWSTR::null(),
            CRED_ENUMERATE_ALL_CREDENTIALS,
            &mut count,
            &mut credentials_ptr,
        )
        .ok()?;

        let credentials =
            std::slice::from_raw_parts::<&CREDENTIALW>(credentials_ptr as _, count as usize);

        for credential in credentials {
            // Do something interesting
        }
    }
```

**Comment by riverar** [comment]
@iancormac84 Following up, checked in a full sample. Hope that helps!

**Comment by iancormac84** [comment]
Thanks, yes, this helps!
