### ISSUE TITLE
any chance of a `windows-*` crate release

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#2557]
@kennykerr any chance of a `windows-*` crate release for this too? This would have been picked up in 0.50.0, but it looks like y'all declined to bump the version of the other crates.

Building packages which use `windows-targets` on MSYS2's version of `aarch64-pc-windows-gnullvm` is entirely broken by this bug, and the only alternative is to use `aarch64-pc-windows-msvc` (which only works on Windows hosts).

I haven't yet got to a point where I'm cross-compiling ARM64 binaries from a non-Windows host; but I'd strongly suspect it's broken there too when using a non-nightly build, using the MSVC toolchain isn't an option, and there's no `aarch64-pc-windows-gnu` like for `x86_64`.

It looks like this project's CI only builds `-gnullvm` with Rust `nightly`, so entirely side-steps the issue.

_Originally posted by @micolous in https://github.com/microsoft/windows-rs/issues/2515#issuecomment-1610982159_

**Comment by kennykerr** [comment]
> any chance of a windows-* crate release

Which crate specifically? 

> It looks like this project's CI only builds -gnullvm with Rust nightly, so entirely side-steps the issue.

Last I checked it only worked in nightly. Has something changed? @mati865

**Comment by mati865** [comment]
>> any chance of a windows-* crate release
>
> Which crate specifically?

I think it's about `windows_aarch64_gnullvm` and `windows_x86_64_gnullvm` that are pulled in by `windows-targets`.
The problem with releasing semver breaking version like 0.50 is it requires bumping `windows-targets` as well, Alternatively 0.48.1 could be released with https://github.com/microsoft/windows-rs/pull/2515 applied on top of it but I don't know if it's feasible and easy for you.

> > It looks like this project's CI only builds -gnullvm with Rust nightly, so entirely side-steps the issue.
> 
> Last I checked it only worked in nightly. Has something changed? @mati865

There is no stable/beta upstream compiler yet. MSYS2 provides downstream (think of it like Linux distro providing Rust in its repo) stable `aarch64-pc-windows-gnullvm` compiler but it runs only on AArch64 hardware.

**Comment by jeremyd2019** [comment]
That'd be great!  This is an example of the workaround I've had to apply to get packages using windows-targets 0.48.0 to build on aarch64-pc-windows-gnullvm: https://github.com/msys2/MINGW-packages/pull/17654.  It's been copied around to quite a few packages now.

**Comment by jeremyd2019** [comment]
> Which crate specifically?

In case that wasn't clear yet, `windows-targets`

**Comment by kennykerr** [comment]
`windows-targets` 0.48.1 has been published.

**Comment by micolous** [comment]
Thanks all, I think that's exactly what was needed.

MSYS2 ships an `aarch64-pc-windows-gnullvm` Rust compiler in "stable" mode, which means none of the "nightly" features work on it.  From what I could tell, MSYS2 cherry-picked the fix into their build scripts, which is fine for Rust MSYS2 packages, but doesn't provide a usable Rust development environment on `aarch64` machines using a native mingw toolchain.

Unlike on `x86_64`, there's no `aarch64-pc-windows-gnu` as a way out; the only alternative is the MSVC toolchain (which works fine, both cross-compiling and natively).
