### ISSUE TITLE
Mismatch of the parameter types and the number of parameter

### ISSUE THREAD

**Issue by zoo868e** [microsoft/windows-rs#2561]
It appears that there is a discrepancy between the definition of the function parameters in the source code and the accompanying documentation. To address this issue, I recommend reviewing both the source code and the documentation carefully to identify the correct definition for the parameters. It may be necessary to make adjustments to ensure consistency and accurate usage of the function. 

In [source code](https://github.com/microsoft/windows-rs/blob/master/crates/libs/windows/src/Windows/Win32/NetworkManagement/WiFi/mod.rs)

```
pub unsafe fn WlanHostedNetworkSetSecondaryKey<P0, P1, P2>(
    hclienthandle: P0,
    puckeydata: &[u8],
    bispassphrase: P1,
    bpersistent: P2,
    pfailreason: ::core::option::Option<*mut WLAN_HOSTED_NETWORK_REASON>,
    pvreserved: ::core::option::Option<*const ::core::ffi::c_void>) -> u32
where
...
```

In [document](https://docs.rs/windows-sys/latest/windows_sys/Win32/NetworkManagement/WiFi/fn.WlanHostedNetworkSetSecondaryKey.html)

```
pub unsafe extern "system" fn WlanHostedNetworkSetSecondaryKey(
    hclienthandle: HANDLE,
    dwkeylength: u32,
    puckeydata: *const u8,
    bispassphrase: BOOL,
    bpersistent: BOOL,
    pfailreason: *mut WLAN_HOSTED_NETWORK_REASON,
    pvreserved: *const c_void
) -> u32
```

**Comment by riverar** [comment]
Closing this for now, but please feel free to reach out if you run into any issues.

**Comment by Nerixyz** [comment]
You're confusing `windows` and `windows-sys`. The documentation you mentioned is for `windows-sys`. The `WlanHostedNetworkSetSecondaryKey` function can be found [here in the repo](https://github.com/microsoft/windows-rs/blob/a817607f4a48c891e4d598b40b8685c59d18743b/crates/libs/sys/src/Windows/Win32/NetworkManagement/WiFi/mod.rs#L70-L71) as @riverar said.

The documentation for `windows` can be found on [microsoft.github.io/windows-docs-rs](https://microsoft.github.io/windows-docs-rs/) - the `WlanHostedNetworkSetSecondaryKey` function for the `windows` crate is documented [here](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/NetworkManagement/WiFi/fn.WlanHostedNetworkSetSecondaryKey.html) with the signature you found in the source code.

**Comment by zoo868e** [comment]
Hi @riverar and @Nerixyz, thank you for the explanation!
