### ISSUE TITLE
Update metadata and rebuild bindings

### ISSUE THREAD

**Issue by eiderdaus** [microsoft/windows-rs#2571]
https://github.com/microsoft/wdkmetadata/pull/37 introduced some `Nt*` APIs. They are not yet available in either of `windows` or `windows-sys` crates. I guess the updated metadata needs to be imported here and the bindings regenerated.

Particularly I'd like `NtCancelIoFileEx` implemented so https://github.com/tokio-rs/mio/issues/1632 can be fixed.

**Comment by kennykerr** [comment]
https://github.com/microsoft/windows-rs/pull/2573 updated the repo with the latest metadata. Please kick the tires and let me know if you experience any issues.

**Comment by eiderdaus** [comment]
Very well, I could patch my mio to use windows-sys' new `NtCancelIoFileEx` declaration, thanks! So once new crate versions are released here, mio's aforementioned bug can be fixed.

Though it took a little longer than expected because I had to look up a few imports that changed namespace (some from Win32 to Wdk no less), corroborating my suspicion that these namespaces are based on rather arbitrary naming decisions and no actual concept, but I digress.

**Comment by kennykerr** [comment]
Yes, my focus this year is on stabilizing metadata so that these somewhat subjective changes are a thing of the past and we can begin to stabilize.
