### ISSUE TITLE
Feature request: allow handling of exceptions from IGraphicsCaptureItemInterop::CreateForWindow

### ISSUE THREAD

**Issue by mwilliamson-fourier** [microsoft/windows-rs#2572]
### Motivation

Some calls to `IGraphicsCaptureItemInterop::CreateForWindow` appear to throw an exception, resulting in the process terminating with `fatal runtime error: Rust cannot catch foreign exceptions`. Is there a way for windows-rs (or the caller?) to handle that exception and return an `Err` instead so that the caller can handle the error?

**Comment by robmikh** [comment]
This is unfortunately a real OS bug that is fixed on newer builds of Windows.

**Comment by mwilliamson-fourier** [comment]
> This is unfortunately a real OS bug that is fixed on newer builds of Windows.

Thanks, this is useful to know. I don't suppose you know what versions of Windows fix this?

> It should not throw an exception if used correctly. smirk Without a repro, we can only guess.

Perhaps there's a technical limitation here, but even in the case where the API is being used incorrectly, would it not be useful to have some way of informing the caller in what way they're using the API incorrectly (which is information I would assume, perhaps incorrectly, is contained in the exception), rather than causing the process to terminate immediately without a backtrace?

**Comment by robmikh** [comment]
The fix first shipped in Windows 11 21H2 (build 22000).

The issue is that I'm unsure if there's a good way to guard against a C++ exception in Rust. But generally, these APIs shouldn't throw like that.

**Comment by robmikh** [comment]
Actually, the fix might have been serviced down-level. On Windows 10 19045.3086 I get the proper E_INVALIDARG result. What build of Windows are you on? Settings -> System -> About should contain the build number.

**Comment by mwilliamson-fourier** [comment]
We're using Windows 10 19044.1526.

Just to give a bit of context of where we're seeing the error: our call succeeds most of the time, but sometimes fails if a window (not the one being passed to `CreateForWindow`) has been recently destroyed. Not destroying the window beforehand or waiting a few seconds before making the capture item seems to avoid the problem, although it's intermittent so I can't be sure. I'm in the middle of trying to produce a minimal test case so that we can reproduce the issue more reliably.

**Comment by robmikh** [comment]
Ah, ok that build probably does not have the fix.

This should reproduce easily if you call CreateForWindow with a clearly bogus window handle. But there shouldn't be any circumstance where using the handle of a destroyed window would work... Or am I misreading your message?

**Comment by mwilliamson-fourier** [comment]
So the situation we have is a window is destroyed, and then we create a new window, and try to create a capture item for the newly created window. It's the creation of the capture item for the new window (not the destroyed one) that sometimes fails.

**Comment by robmikh** [comment]
Thanks for clarifying! That sounds like an issue where the window creation is racing the shell's decision on if your window is capturable or not. Generally, if a window shows up in Alt+Tab then it's deemed "capturable", and being included in that list doesn't happen immediately.

**Comment by mwilliamson-fourier** [comment]
Thanks for the explanation! Is there a way to reliably detect whether the window is capturable yet or not? I tried using the code from screenshot-rs (`is_capturable_window`), but it was returning `true` in all cases, including when the creation of the capture item would fail. Or is the simplest thing to do just to retry creating the capture item until success (on a later version of Windows where this returns appropriately)?

**Comment by mwilliamson-fourier** [comment]
Okay, that's good to know. Thanks for all the help!
