### ISSUE TITLE
Unable to use QueryInterface(), into `AppDomain`

### ISSUE THREAD

**Issue by lap1nou** [microsoft/windows-rs#2575]
Hello,

I'm unable to find the `AppDomain` struct in the library for CLR Hosting, is it already implemented ? I'm trying to cast an `IUknown` COM interface to an `AppDomain`.

Here is the `AppDomain` I'm talking about: https://learn.microsoft.com/en-us/dotnet/api/system.appdomain?view=net-7.0

I'm trying to achieve something similar : https://github.com/etormadiv/HostingCLR/blob/master/HostingCLR/HostingCLR.cpp#L126.

**Comment by kennykerr** [comment]
This may help: https://kennykerr.ca/rust-getting-started/how-to-query-for-com-interface.html

**Comment by lap1nou** [comment]
Hello,

Thank you really much for your answer, if I understand correctly I should do something along the line:
```rust
...
let default_domain: IUnknown = runtime_host.GetDefaultDomain().unwrap();
let my_appdomain = default_domain.cast::<AppDomain>();
...
```

This is really nice, since it will automatically put the correct IID and call `QueryInterface` for us, but unfortunately I can't find the struct `AppDomain`, is it declared under another name maybe ?

**Comment by kennykerr** [comment]
Sorry, I don't know where that comes from. You may want to ask on:

* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
* https://stackoverflow.com/
