### ISSUE TITLE
Feature request: Please consider adding a growable buffer

### ISSUE THREAD

**Issue by Coding-Badly** [microsoft/windows-rs#2576]
### Motivation

Several API calls require a growable buffer.  The typical pattern is to start with a stack buffer that's expected to be large enough then switch to a heap buffer if it is not.

There are several variations available from the internet-at-large.  Most are reasonably good quality.  Some are poor quality.  A few have bugs.  None cover all styles of API calls.  One good version would be helpful.

[This crate](https://crates.io/search?q=grob) is a suggested starting point.

**Comment by riverar** [comment]
Can you provide the API calls you're referring to so we can get a better understanding here?

**Comment by kennykerr** [comment]
I prefer to keep the core windows-rs crates predominantly made up of generated bindings from metadata with only the absolute bare minimum supporting infrastructure. 

https://kennykerr.ca/rust-getting-started/how-are-crates-built.html

It sounds like you already have a decent solution. This is where discrete crates can provide a lot of value. 👍
