### ISSUE TITLE
Bug: microsoft document and crates.io out of date

### ISSUE THREAD

**Issue by zzwxh** [microsoft/windows-rs#2583]
### Which crate is this about?

other (please share in the comments)

### Summary

i can't find  Transform BOOL and Win32 return values #2476 in microsoft document

**Comment by tim-weis** [comment]
The latest version of the `windows` crate (0.48.0) was released on March 31st, 2023. PR #2476 was merged on April 26th, 2023.

In other words: The `BOOL`/last error code -> `Result<()>` transformation hasn't been published yet, and the documentation properly reflects the latest published version of the `windows` crate.

**Comment by tim-weis** [comment]
It's not clear from the issue what the goal is.

If you just want to take advantage of the convenience introduced by PR #2476, you can [specify a git repository dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) in your *Cargo.toml*, something like this:

```toml
[dependencies.windows]
git = "https://github.com/microsoft/windows-rs.git"
rev = "refs/pull/2476/head"
features = []
```

The `rev` table entry isn't strictly required. It locks the dependency on the specific PR that introduced this feature. It can be omitted if that is not something you need.

That works[^1], as long as you aren't planning to publish a crate with this dependency through [crates.io](https://crates.io/). If you are, you'll need to [request a new release](https://github.com/microsoft/windows-rs/issues/2156#issuecomment-1323816991), which would also update the documentation to align with the published artifacts.

[^1]: If you are fine writing code against an interface that doesn't match the published documentation.
