### ISSUE TITLE
Working example for CoCreateInstanceEx()

### ISSUE THREAD

**Issue by efendioglukdz** [microsoft/windows-rs#2584]
Hello friends,

I would like to ask if there is any working example code for the above mentioned function in windows-rs. I mean I tried to use it for my
puroposes but I am getting an:

>  misaligned pointer dereference: address must be a multiple of 0x8 but is 0x14a00000001'

# Here is my code so far :

<code>

      fn main() -> Result<()> {	
        unsafe {
            match CoInitializeEx(Some(std::ptr::null_mut()), COINIT_MULTITHREADED){
                Ok(ret) => {
                    println!("CoInitializeEx:{ret:?}");                
                },
                Err(err) => {
                    println!("CoInitializeEx:{err:?}");
				    return Err(err);
                }
            }
        }
    let mut csi :COSERVERINFO = COSERVERINFO::default();

    let my_string: String = "my-hostname".into();
    let mut my_wide_string: Vec<u16> = my_string.encode_utf16().chain(std::iter::once(0)).collect();
    let p_wstr: PWSTR = PWSTR::from_raw(my_wide_string.as_mut_ptr());

    csi.dwReserved1 = 0;
    csi.dwReserved2 = 0;
    csi.pAuthInfo = std::ptr::null_mut();
    csi.pwszName = p_wstr;

    let IID_IWMComp: *const ::windows::core::GUID = &::windows::core::GUID::from_u128(0xe36d3a63_1fce_11d3_b2ef_00104b066e1a);
   
    let mut mqi2:[MULTI_QI;1]=[MULTI_QI::default()];
    
    mqi2[0].pIID = IID_IWMComp;
    mqi2[0].pItf = ManuallyDrop::new(None);
    mqi2[0].hr = windows::core::HRESULT(0);
    unsafe{
        let mut hret = CoCreateInstanceEx(  &CLSID_WMComp ,
                                        None,
                                        CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER,
                                        Some(&csi),
                                         &mut mqi2);
       
        match hret{
            Ok(ret) => {
                println!("Ret:{ret:?}");
                if mqi2[0].hr == windows::core::HRESULT(0){
                    let mut m_comp:IWMComp = IWMComp(mqi2[0].pItf.as_mut().unwrap().clone());
                    unsafe {
                        let wmconn:IWMConn2=CoCreateInstance(&CLSID_IWMConn, None, CLSCTX_INPROC_SERVER).unwrap();
                        
                        let retd = wmconn.LoginComp( &mut m_comp);
                        let szInfo= "Info".to_string();
                        let bret = m_comp.GetInfo(&szInfo);
                    }	
				}
			},
            Err(err) => {
                println!("Error:{err:?}");
            }
		}
	}
	unsafe {
            CoUninitialize();            
        }
       Ok(())
    }
</code>

The error occurs on calling the line
> let bret = m_comp.GetInfo(&szInfo);

**LoginComp** return true.

Any suggestions due to the 
>misaligned pointer dereference

error???

Thx in advance

**Comment by kennykerr** [comment]
I don't have an example handy. You can try here:

https://stackoverflow.com/questions/tagged/windows-rs
