### ISSUE TITLE
Send Input with Mouse Event not working as expected

### ISSUE THREAD

**Issue by ratuspro** [microsoft/windows-rs#2585]
I've been playing with SendInput to simulate keystrokes as well as mouse movements and clicks.
Simulating Keyboard events is working fine. However, I'm not able to SendInput with MouseInput:
```rust
inputs.push(INPUT{
    r#type: INPUT_MOUSE,
    Anonymous: INPUT_0 { 
        mi: MOUSEINPUT{
            dx: 10,
            dy: 10,
            mouseData: 0,
            time: 0,
            dwFlags: MOUSEEVENTF_MOVE & MOUSEEVENTF_ABSOLUTE & MOUSEEVENTF_VIRTUALDESK,
            dwExtraInfo: 0
        }  
    }
});
```
and the input is sent like this: 
```rust
SendInput(&inputs, inputs.len() as i32 * (std::mem::size_of::<INPUT> as i32))
```
`GetLastError()` returns `WIN32_ERROR(87)` (ERROR_INVALID_PARAMETER 87)

I suspect that it might have something to do with the memory layout of the INPUT enum variants. Not sure if it is a bug or just a bad use of the API. Seems odd that the KeyboardInput works. 

If someone could help, I would appreciate it.

**Comment by Nerixyz** [comment]
`cbsize`, the second parameter, isn't the size of the `inputs` array, but the size of the [`INPUT`](https://learn.microsoft.com/windows/win32/api/winuser/ns-winuser-input) structure ([documentation](https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-sendinput)). So it should be `std::mem::size_of::<INPUT>`.

**Comment by ratuspro** [comment]
Thanks for the info.
The documentation on the rust crate was not clear.
