### ISSUE TITLE
Can't use BIND_OPTS3 on CoGetObject

### ISSUE THREAD

**Issue by NiiightmareXD** [microsoft/windows-rs#2587]
I created a BIND_OPTS3 struct but now when I want to use on CoGetObject it doesn't work it needs BIND_OPT is there a CoGetObject3 or something like that so I can use BIND_OPTS3 on it? can someone provide me an example of how to use BIND_OPTS3?

I think the CoGetObjec function should accept BIND_OPTS3

thanks for helping

**Comment by kennykerr** [comment]
You can probably cast the pointer with `as` - it is likely that the function will check the struct's size field. For API questions I recommend:

https://stackoverflow.com/questions/tagged/windows-rs
