### ISSUE TITLE
Feature request: riddle lib interface

### ISSUE THREAD

**Issue by Yuri6037** [microsoft/windows-rs#2593]
### Motivation

I have a low-level crate which uses currently windows-sys but imports a great set of features and uses only about 1 function for each of these features, I'm searching to optimize the bindings to only exactly what I'm using based on what feature the user enabled on the lib crate itself.

I've looked into the riddle tool which looks like it could help me but there's one big drawback of using it: it's absolute pain to setup. What I need is a way to install the riddle tool as part of build.rs script in order to generate the bindings in dev only. Forcing other people to install globally this tool is unacceptable. So the current setup will force me to make some hacky code to download (or use submodule), build and run the tool manually from build.rs.

Could you provide a simple lib interface so that I can import this tool in dev and use it from build.rs?

**Comment by kennykerr** [comment]
I've had a few suggestions for a lib. That should be doable.

**Comment by riverar** [comment]
Some dev discussion notes to refresh our memory later:
* Look at `windows-bindgen` crate as possible deployment vehicle
* Shipping _without_ metadata (add winmds to consuming crate) won't satisfy folks asking for turnkey solution
  * Dependency on winmd files needs to be added (e.g., windows-metadata default function)
  * Metadata itself is still very unstable; breakage is almost guaranteed between releases
  * May be easier to punt and explore riddle bootstrapping first

**Comment by kennykerr** [comment]
We could hide the default winmd files behind a crate feature, so they're not included if not desired. Mainly, it doesn't make sense for `riddle.exe` to include them but lib dependents may appreciate that it's all included.
