### ISSUE TITLE
MapViewofFile2 missing

### ISSUE THREAD

**Issue by Axel-Reactor** [microsoft/windows-rs#2595]
Is there a good reason why `MapViewOfFile2` is missing, but `MapViewOfFile3` is not?

It's not a big deal but `MapViewOfFile2` only requires Win 10 1703, while `MapViewOfFile3` is 1803, so it's not just a matter of calling the newer interface.

**Comment by riverar** [comment]
Yep, per docs under Remarks:
> This function is implemented as an inline function in the header and can't be found in any export library or DLL. It's the same as calling [MapViewOfFileNuma2](https://learn.microsoft.com/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffilenuma2) with the last parameter set to NUMA_NO_PREFERRED_NODE.

**Comment by Axel-Reactor** [comment]
Thanks. I looked for it in the docs and nothing showed up, so maybe this is something that could be more obvious.
