### ISSUE TITLE
Bug: SHCreateShellItemArray returns error on 'ppidl' parameter value 'None'

### ISSUE THREAD

**Issue by HJX-001** [microsoft/windows-rs#2597]
### Which crate is this about?

windows

### Crate version

0.48.0

### Summary

SHCreateShellItemArray returns error on providing 3rd paramenter 'ppidl' as 'None', works fine on providing any 'ITEMIDLIST' array, but as per msdn docs [SHCreateShellItemArray](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-shcreateshellitemarray) ppidl value can be Null(None in rust).

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  dir\to\rustup\home

stable-x86_64-pc-windows-msvc (default)
rustc 1.70.0 (90c541806 2023-05-31)

### Reproducible example

```rust
1. follwing code panics "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }', src\main.rs:28:78"

use std::{os::windows::prelude::OsStrExt, path::Path};
use windows::{
    core::PCWSTR,
    Win32::{
        Foundation::MAX_PATH,
        Storage::FileSystem::GetFullPathNameW,
        System::Com::CoInitialize,
        UI::Shell::{ILCreateFromPathW, SHCreateShellItemArray},
    },
};

fn main() {
    unsafe {
        CoInitialize(None).unwrap();

        let path_z = Path::new(".\\wallpapers")
            .as_os_str()
            .encode_wide()
            .chain(std::iter::once(0))
            .collect::<Vec<u16>>();
        let mut buff: [u16; MAX_PATH as usize] = [0; MAX_PATH as usize];
        let path_len = GetFullPathNameW(PCWSTR::from_raw(path_z.as_ptr()), Some(&mut buff), None);
        let path = buff.split_at(path_len as usize + 1).0.to_vec();

        let item_list = ILCreateFromPathW(PCWSTR::from_raw(path.as_ptr()));
        let item_array = SHCreateShellItemArray(Some(item_list), None, None).unwrap();
        println!("{item_array:?}");
    }
}
```

2. following code works and prints "IShellItemArray(IUnknown(RANDOM VALUE))"
```
use std::{os::windows::prelude::OsStrExt, path::Path};
use windows::{
    core::PCWSTR,
    Win32::{
        Foundation::MAX_PATH,
        Storage::FileSystem::GetFullPathNameW,
        System::Com::CoInitialize,
        UI::Shell::{ILCreateFromPathW, SHCreateShellItemArray},
    },
};

fn main() {
    unsafe {
        CoInitialize(None).unwrap();

        let path_z = Path::new(".\\wallpapers")
            .as_os_str()
            .encode_wide()
            .chain(std::iter::once(0))
            .collect::<Vec<u16>>();
        let mut buff: [u16; MAX_PATH as usize] = [0; MAX_PATH as usize];
        let path_len = GetFullPathNameW(PCWSTR::from_raw(path_z.as_ptr()), Some(&mut buff), None);
        let path = buff.split_at(path_len as usize + 1).0.to_vec();

        let item_list = ILCreateFromPathW(PCWSTR::from_raw(path.as_ptr()));
        let item_array = SHCreateShellItemArray(Some(item_list), None, Some(&[item_list])).unwrap();
        println!("{item_array:?}");
    }
}
```
```


### Crate manifest

```toml
[dependencies.windows]
version = "0.48.0"
features = [
	"Win32_Foundation",
	"Win32_Storage_FileSystem",
	"Win32_System_Com",
	"Win32_System_SystemServices",
	"Win32_UI_Shell",
	"Win32_UI_Shell_Common",
	"Win32_UI_WindowsAndMessaging",
]
```

**Comment by kennykerr** [comment]
The docs indicate that it is optional and so does the metadata. It may be that the docs and/or metadata are incorrect. 

I suggest you follow up in a forum where you might be able to get help with this API:

* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
* https://stackoverflow.com/

**Comment by riverar** [comment]
`SHCreateShellItemArray` accepts a folder item ID to designate as a parent and a set of folder/file item IDs to be its children. It then builds a shell item array for you. (It does not matter if this association actually exists on disk.) It can't be used as a shortcut to build up a shell item array by specifying a folder item ID.

The [documentation](https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-shcreateshellitemarray) indicates (poorly) that `ppidl` is not optional:

> [in] pidlParent
> Type: PCIDLIST_ABSOLUTE
> The ID list of the parent folder <u>**of the items specified in ppidl**</u>. If psf is specified, this parameter can be NULL. If this pidlParent is not specified, it is computed from the psf parameter using IPersistFolder2.
>
> [in] psf
> Type: IShellFolder*
> The Shell data source object that is the parent **of the child items specified in ppidl**. If pidlParent is specified, this parameter can be NULL.

I'm not sure why the documentation for `ppidl` states the value can be null. Perhaps at some point it may have worked (creating an empty parent)?

Here's an example that builds up the child item IDs (of folders) given a parent folder, which I suspect is what you really want.

```rust
use std::os::windows::prelude::OsStrExt;

use windows::{
    core::PCWSTR,
    w,
    Win32::{
        System::Com::CoInitialize,
        UI::Shell::{
            Common::ITEMIDLIST, ILCreateFromPathW, SHCreateShellItemArray, SIGDN_FILESYSPATH,
        },
    },
};

fn main() -> windows::core::Result<()> {
    unsafe {
        CoInitialize(None)?;

        let child_items: Vec<_> = std::fs::read_dir(r#"C:\Windows\Help"#)
            .unwrap()
            .filter_map(|entry| entry.ok())
            .filter(|entry| entry.path().is_dir())
            .map(|entry| {
                let wide_path: Vec<u16> = entry
                    .path()
                    .as_os_str()
                    .encode_wide()
                    .chain(std::iter::once(0))
                    .collect();
                ILCreateFromPathW(PCWSTR::from_raw(wide_path.as_ptr())) as *const ITEMIDLIST
            })
            .collect();
        debug_assert!(!child_items.is_empty());

        let parent_item = ILCreateFromPathW(w!(r#"C:\Windows\Help"#));
        debug_assert_ne!(parent_item, std::ptr::null_mut());

        let item_array = SHCreateShellItemArray(Some(parent_item), None, Some(&child_items))?;
        debug_assert!(item_array.GetCount()? > 0);

        println!(
            "Items[0] => {}",
            item_array
                .GetItemAt(0)?
                .GetDisplayName(SIGDN_FILESYSPATH)?
                .display()
        );

        // ...
        // Don't forget to free the items in child_items
        // ...
    }

    Ok(())
}

```

**Comment by riverar** [comment]
Closing as there's no crate issue here but feel free to continue the discussion.
