### ISSUE TITLE
SetDllDirectoryW  not working

### ISSUE THREAD

**Issue by rain2307** [microsoft/windows-rs#2600]
I want to load dlls in the target directory instead of add it to PATH (PATH works).
I tried to use `windows::Win32::System::LibraryLoader::SetDllDirectoryW` in build.rs and the result is `BOOL(1)`. Does this mean success? 
It still failed to find the dll when `cargo run`.
I also tried to call this func in main.rs, but the result is the same.

```
/.cargo/bin/cargo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by kennykerr** [comment]
It probably just means that the path was set successfully and it's up to you to determine whether it is valid before calling this function. For API questions I suggest:

* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
* https://stackoverflow.com/
