### ISSUE TITLE
Release request for windows-rs 0.49.0 for WDK additions.

### ISSUE THREAD

**Issue by chyyran** [microsoft/windows-rs#2603]
Requesting a new release of windows-rs for WDK additions, particularly ntifs.h headers in `Wdk_Storage_FileSystem`.

**Comment by kennykerr** [comment]
Which crate are you using?

**Comment by chyyran** [comment]
I’m using windows-rs

**Comment by kennykerr** [comment]
Thanks, have you tested against github? Happy to release an update if you've validated that the APIs you need work as expected.

**Comment by chyyran** [comment]
Tested against GitHub and it seems to be working fine with one caveat. WDK functions convert their NTSTATUS errors to HRESULT so they can return `Result<T, windows::core::Error>`. My particular use case requires the base NTSTATUS in case of errors. Could WDK functions be made to return `Result<T, NTSTATUS>` or a wrapped version such that the original NTSTATUS is recoverable where relevant? (Should I file a new issue for this?)

**Comment by tim-weis** [comment]
@chyyran [`NTSTATUS`](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/87fba13e-bf06-450e-83b1-9241dc81e781) values can be losslessly represented as `HRESULT` values. To recover the corresponding `NTSTATUS` value from a [`windows::core::Error`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.Error.html) you would call [`code()`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.Error.html#method.code) to get the `HRESULT` value, and then unset bit 4 (N).

**Comment by chyyran** [comment]
Thanks @tim-weis, in which case everything works as expected.

**Comment by riverar** [comment]
Heads up, the documentation linked above numbers the most significant bit as bit 0. Bit 4 in this case is really bit 28.

**Comment by kennykerr** [comment]
Thanks for testing. Will publish today.
