### ISSUE TITLE
0.51 samples

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#2606]
Small updates needed
        let wc = WNDCLASSA {
            hCursor: LoadCursorW(None, IDC_ARROW)?,
            //hInstance: instance,
            hInstance: instance.into(),
            lpszClassName: window_class,

            style: CS_HREDRAW | CS_VREDRAW,
            lpfnWndProc: Some(wndproc),
            ..Default::default()
        };
Also, previously discarded API call return values will now need:
        let _ = ...

**Comment by kennykerr** [comment]
All samples are validated by the CI build.

**Comment by MRahilly** [comment]
Apologies Kenny, I was sure that I had selected the correct version.
