### ISSUE TITLE
Invaid prototype of PDRIVER_UNLOAD

### ISSUE THREAD

**Issue by HoShiMin** [microsoft/windows-rs#2612]
### Which crate is this about?

windows-sys

### Crate version

0.51.0

### Summary

Is that correct that the PDRIVER_UNLOAD has no PDRIVER_OBJECT argument?  
It has the following prototype:
```rust
pub type PDRIVER_UNLOAD = ::core::option::Option<unsafe extern "system" fn() -> ()>;
```

But in C++ WDK it declared as this:
```cpp
//
// Define driver unload routine type.
//
_Function_class_(DRIVER_UNLOAD)
_IRQL_requires_(PASSIVE_LEVEL)
_IRQL_requires_same_
typedef
VOID
DRIVER_UNLOAD (
    _In_ struct _DRIVER_OBJECT *DriverObject
    );
```

And it seems like all function pointers (at least in Foundation module) have no arguments.

**Comment by HoShiMin** [comment]
And why they declared as `Option<fn()>` but not like a raw function pointer? Is it compatible with raw C pointers?

**Comment by kennykerr** [comment]
If the function signature is incorrect then we may need the Win32/WDK metadata to be updated. Here's the repo for that: 

https://github.com/microsoft/wdkmetadata

As for `Option`, that is guaranteed to be the same size:

https://doc.rust-lang.org/stable/std/option/index.html#representation
