### ISSUE TITLE
how can we check the result hwnd  of  the function FindWindowW returned is invalid?

### ISSUE THREAD

**Issue by E834159672** [microsoft/windows-rs#2616]
as the title say , how can we check the result hwnd  of  the function FindWindowW returned is invalid?

the version of windows-rs  i used is  0.51.1

sorry for my poor english. 
many thanks!

**Comment by tim-weis** [comment]
[`FindWindowW`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindoww) returns `NULL` on error. The Rust projection wraps window handles behind the [`HWND`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HWND.html) tuple struct.

To verify whether the returned `HWND` refers to an invalid window handle you can either access the wrapped value directly

```rust
if hwnd.0 == 0 {
    // Handle error
}
```

or compare it against a default constructed `HWND` value

```rust
if hwnd == HWND::default() {
    // Handle error
}
```

The error handling path can call [`from_win32()`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.Error.html#method.from_win32) to capture the specific error value.

**Comment by E834159672** [comment]
thank you!
