### ISSUE TITLE
Add warning/error if a particular `bindgen` filter has no effect

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/windows-rs#2625]
### Suggestion

I would like to use windows_bindgen internals without going through the bindgen function, which is the only one exported.

Specifically I'd like to be able to do things like bypassing the filter requirement and debug why my bindings are not appearing in the output.

Please could support be added to use this? Much appreciated :)

**Comment by kennykerr** [comment]
The internals are under active development. I'd prefer to keep it that way, at least for now, and limit support to the bindgen/riddle public interface. Feel free to create an issue to discuss specific functionality that the existing interface does not provide.

**Comment by ChrisDenton** [comment]
> Specifically I'd like to be able to do things like bypassing the filter requirement and debug why my bindings are not appearing in the output.

Maybe it could warn/error if a binding is not found?

**Comment by kennykerr** [comment]
I see you updated the original comment with a more specific request. 😊 Will reopen to discuss.

**Comment by Ben-Lichtman** [comment]
> > Specifically I'd like to be able to do things like bypassing the filter requirement and debug why my bindings are not appearing in the output.
> 
> Maybe it could warn/error if a binding is not found?

I think this would be helpful - additionally maybe there could be some API for printing all the discovered bindings / metadata?

**Comment by kennykerr** [comment]
> Maybe it could warn/error if a binding is not found?

Yes I'd like to report a warning/error if a particular filter has no effect. 

> additionally maybe there could be some API for printing all the discovered bindings / metadata

Ideally filtering can just work and not need debugging. 😊 If there's something not intuitive about it do let me know.

You can also use the `windows-metadata` library crate or the numerous winmd tools like [ILSpy](https://github.com/icsharpcode/ILSpy).

**Comment by Ben-Lichtman** [comment]
I can't really find any documentation on what windows-metadata does or how to properly use it, I can see that it's possible to extract rows out of a table, but then I'm lost.

ILSpy works fine to inspect the .winmd file, so I think that should be satisfactory for my current purposes.

**Comment by riverar** [comment]
Closing this issue for now as we've chat offline, feel free to keep the discussion going if needed.
