### ISSUE TITLE
windows-sys is missing multiple graphics APIs

### ISSUE THREAD

**Issue by ItsEthra** [microsoft/windows-rs#2626]
### Summary

Before version 0.45.0 `windows-sys` crate used to have graphics APIs such as DXGI, DirectX11, DirectX12 and others. (e.g. [0.42.0](https://docs.rs/windows-sys/0.42.0/windows_sys/Win32/Graphics/index.html) has them but the [0.45.0](https://docs.rs/windows-sys/0.45.0/windows_sys/Win32/Graphics/index.html) does not. Is there a chance of bringing them back and what was the reason behind their removal?

**Comment by riverar** [comment]
Hey @ItsEthra, these were removed in https://github.com/microsoft/windows-rs/pull/2194. I believe we removed those due to the reliance on COM (of which `windows` is better suited) and instability of the API surface due to Agility SDK churn upstream. Will defer to @kennykerr for confirmation.

**Comment by ItsEthra** [comment]
I see, but now that there is a separate `windows-core` crate which has COM, it would be possible to bring back removed APIs?

**Comment by kennykerr** [comment]
The `windows-core` crate contains the core types for COM support, not all COM interface definitions. There are supporting types and traits for each interface that is only contained in the `windows` crate. 

https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html
