### ISSUE TITLE
IMAGE_OPTIONAL_HEADER64 doesn't implement fmt::Debug

### ISSUE THREAD

**Issue by 0vercl0k** [microsoft/windows-rs#2628]
### Summary

I just noticed that `IMAGE_OPTIONAL_HEADER64` (`Win32_System_Diagnostics_Debug`) doesn't implement `fmt::Debug` but `IMAGE_OPTIONAL_HEADER32` does.

Am I missing something?

After trying to implement it myself, I realize this might be because of the following unaligned fields: `ImageBase` / `SizeOfStackReserve` / `SizeOfStackCommit` / `SizeOfHeapReserve` / `SizeOfHeapCommit` so this might be by-design.

Cheers

**Comment by kennykerr** [comment]
Yep, when the struct has explicit layout or packing then the `Debug` trait cannot be implemented. This is mostly a Rust limitation. 

```rust
#[repr(C, packed(4))]
pub struct IMAGE_OPTIONAL_HEADER64 { ... }

#[repr(C)]
pub struct IMAGE_OPTIONAL_HEADER32 { ... }
```

**Comment by 0vercl0k** [comment]
Gotcha makes sense - are you interested in considering generating manual implementations? It seems like it's as easy as creating local variables but I understand if this is not something you are open about; I will close the issue if that's the case.

Cheers!
