### ISSUE TITLE
about windows::build! 

### ISSUE THREAD

**Issue by bcdlbgm** [microsoft/windows-rs#2633]
### Suggestion

I'm sorry for the confusion. In the newer version of the windows crate (0.51), is windows::build! no longer used? I can't find a usage method in the new version, and the old usage method is no longer applicable. If it's no longer used, is there a replacement?

**Comment by kennykerr** [comment]
Back when the `build` macro was provided, the `windows` crate didn't include the pre-generated bindings as it does today. The `build` macro is essentially replaced by crate features as illustrated in the readme. 

https://crates.io/crates/windows

There is growing collection of samples here:

https://github.com/microsoft/windows-rs/tree/0.51.1/crates/samples
