### ISSUE TITLE
ShellAboutA() unwraps None

### ISSUE THREAD

**Issue by masoomshaikh** [microsoft/windows-rs#2636]
### Summary

See the title bar, is there no way to avoid Option::display()?
![image](https://github.com/microsoft/windows-rs/assets/217784/ff5e4a8e-3ecb-47a6-b59f-a8ae84a07da3)

### Crate code

```Rust
use windows_sys::Win32::{
    Foundation,
    UI::{Shell, WindowsAndMessaging::HICON},
};

fn main() {
    unsafe {
        Shell::ShellAboutA(
            Foundation::HWND::default(),
            "".as_ptr(),
            std::ptr::null(),
            HICON::default(),
        );
    }
}
```

**Comment by masoomshaikh** [comment]
issue is beyond windows-sys crate, this minimal code results in same issue.
compile with `rustc main.rs -l shell32`

```
extern "system" {
    fn ShellAboutA(hwnd: u32, szapp: *const u8, szotherstuff: *const u8, hicon: u32) -> i32;
}

fn main() {
    unsafe {
        ShellAboutA(0, "".as_ptr(), std::ptr::null(), 0);
    }
}
```

**Comment by riverar** [comment]
Hi @masoomshaikh, in the future please complete the bug form in its entirety. (You're missing the manifest above.)

Note that `ShellAboutA` requires a null-terminated string per the docs:
> A pointer to a null-terminated string that contains text to be displayed in the title bar of the ShellAbout dialog box

Your code is not passing in a null-terminated string. Here's a working copy of your code above:

```diff
+ use windows_sys::s;
  use windows_sys::Win32::{
      Foundation,
      UI::{Shell, WindowsAndMessaging::HICON},
  };
  
  fn main() {
      unsafe {
          Shell::ShellAboutA(
              Foundation::HWND::default(),
-             "".as_ptr(),
+             s!(""),
              std::ptr::null(),
              HICON::default(),
          );
      }
  }
```
