### ISSUE TITLE
StaticLibraryAttribute handling doesn't work unless it happens to be in the Windows namespace

### ISSUE THREAD

**Issue by wravery** [microsoft/windows-rs#2637]
### Summary

I'm trying to update https://github.com/wravery/webview2-rs to the latest versions of the `windows-rs` crates, and I ran into a couple of issues with `windows-bindgen`. It's evaluating these if statements in the wrong order, so anytime it does not start with the `Windows.` namespace it emits the dynamic link attribute whether or not there's a `StaticLibraryAttribute`:
```rust
    if gen.std || !gen.namespace.starts_with("Windows.") {
        let library = library.trim_end_matches(".dll");

        quote! {
            #[link(name = #library)]
            extern #abi {
                #link_name
                pub fn #ident(#(#params),*) #return_type;
            }
        }
    } else if let Some(library) = gen.reader.method_def_static_lib(signature.def) {
```

I was already working around a separate issue with the `WebView2LoaderStatic.lib` and the gnu toolchain by patching the `#[link]` attributes with a regex, so I was able to modify the regex pattern to handle this, but for any other user of `windows-bindgen` with static libraries, I don't think it's outputting the correct `#[link]` attributes anymore.

### Crate manifest

```TOML
https://github.com/wravery/webview2-rs/blob/main/crates/bindings/Cargo.toml
```

### Crate code

```Rust
https://github.com/wravery/webview2-rs/blob/main/crates/bindings/build.rs (comment out the lines where it reads the file back in, runs the contents through `patch_bindings`, and writes the file back out).
```

**Comment by kennykerr** [comment]
Hi Bill, I thought we added a test for your scenario...? If not, we really should. 😏

**Comment by wravery** [comment]
I thought I remembered there being one too, but I haven't found it yet. We might be thinking of this [sample](https://github.com/microsoft/win32metadata/blob/main/sources/GeneratorSdk/samples/WebView2Sample/WebView2Sample.proj) in the win32metadata project.

**Comment by kennykerr** [comment]
I think the issue has always been that it's too difficult to test since it requires metadata and that requires the whole win32metadata  toolchain, which is why I've been working so hard on bringing up `riddle` to handle that directly.

**Comment by kennykerr** [comment]
Seems like we can just evaluate `method_def_static_lib` before all else and it should work fine. 

https://github.com/microsoft/windows-rs/blob/101467caf5c14f051556577dea0b50744e294304/crates/libs/bindgen/src/rust/functions.rs#L228

I tried to test it but since your binding generator patches up the `link` attributes anyway, it seems a little pointless to have this in `windows-rs` at all. Thoughts?

**Comment by wravery** [comment]
That's a fair question, I think it depends on if anyone else has ever used this feature, and I'm guessing they probably haven't if I'm the only one who noticed. I'm likely the only one patching the `link` attribute as well, since this changed the output and the pattern no longer matched.

What might work even better in my scenario would be a way to pass in substitutions to `bindgen`, e.g. if a (case-insensitive) library with the specified name is about to be used in a `link` attribute, substitute this string for the entire `link` attribute. Theoretically there might be other cases where you'd want to just re-route to a shim DLL, or in my case, use more complicated `cfg_attr` attributes to embed alternate `link` attributes depending on the target.

What do you think of this approach instead, and then we could just remove all of the `StaticLibraryAttribute` handling? If this seems reasonable but you don't have time, I can try to put it in a PR.

**Comment by kennykerr** [comment]
The other challenge with standardizing this is that the use case here only covers static libs for MSVC but the attribute isn't specific about that.

**Comment by wravery** [comment]
That makes sense to me. Do you have any pointers for how to get started with `riddle` vs. `winmd` files? Is that a WinRT specific thing, or does it work with C++ headers as well?

**Comment by kennykerr** [comment]
I'm still working on `riddle` support for Win32/COM APIs. The idea is that not only will it be able to parse .winmd files but it should also be able to parse .h and .idl files so that we can produce Win32 metadata directly.
