### ISSUE TITLE
Wrong HRESULT error code if the call was made from a different facility

### ISSUE THREAD

**Issue by dergecko** [microsoft/windows-rs#2639]
### Summary

The `GetLastError` calls internally the `HRESULT::from_win32`  which set the facility bits of the `HRESULT` to 7 aka _win32_.
However the facility is not always _win32_.

In this example I call the `GetLastError` however the same holds true for functions that already return the `windows::core::Result` like `Cryptography::CryptAcquireCertificatePrivateKey`
I provided a simple example that should look for a fingerprint in the CurrentUser/Personal Cert store if the fingerprint exists.
The is maybe not the simplest version of the bug but hopefully verbose enough.

Easy solutions would be a way to specify the facility on the `GetLastError` call or provide different `windows::core::Error::from_` implementations for each facility. E.g
`windows::core::Error::from_sspi`

### Crate manifest

```TOML
[package]
name = "hresult_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
windows = { version = "0.51", features = [
    "Win32_Security_Cryptography",
    "Win32_Foundation",
] }
```

### Crate code

```Rust
use hex::FromHex;
use windows::Win32::Security::Cryptography;

// looks for a fingerprint in CurrentUser\My (Personal)
fn main() {
    let path_as_wstr = "My"
        .encode_utf16()
        .chain(Some(0))
        .collect::<Vec<_>>();
    let dwflags = Cryptography::CERT_OPEN_STORE_FLAGS(Cryptography::CERT_SYSTEM_STORE_CURRENT_USER_ID << Cryptography::CERT_SYSTEM_STORE_LOCATION_SHIFT);
    let handle = unsafe {
        Cryptography::CertOpenStore(
            Cryptography::CERT_STORE_PROV_SYSTEM_W,
            Cryptography::CERT_QUERY_ENCODING_TYPE::default(),
            Cryptography::HCRYPTPROV_LEGACY::default(),
            dwflags,
            Some(path_as_wstr.as_ptr() as _),
        )
    }.unwrap();

    let hash = <[u8; 20]>::from_hex(&"ABF777B90E01AFFDC21BCCA4BB98D7D884DF702E").unwrap();
    let fingerprint_blob = Cryptography::CRYPT_INTEGER_BLOB {
        cbData: hash.len() as _,
        pbData: hash.as_ptr() as _,
    };

    let cert_context = unsafe {
        Cryptography::CertFindCertificateInStore(
            handle,
            Cryptography::X509_ASN_ENCODING,
            0,
            Cryptography::CERT_FIND_HASH,
            Some(&fingerprint_blob as *const _ as _),
            None,
        )
    };
    assert_eq!(cert_context.is_null(), true, "the fingerprint should not be in the store");

    // wrong facility as the error is from SSPI not win32
    // let error = windows::core::Error::from_win32();
    // this is the same as it internally calls the from_win32() function
    let error = unsafe { windows::Win32::Foundation::GetLastError() }.unwrap_err();
    match error {
        // HACK: HRESULT conversion is wrong for crypto error codes
        // HACK: Add 2 to the facility
        e if e.code().0 + 0x0002_0000
            == windows::Win32::Foundation::CRYPT_E_NOT_FOUND.0 =>
        {
            println!("error codes match");
        }
        _ => {
            eprintln!("error codes did not match");
        },
    };

}
```

**Comment by kennykerr** [comment]
Right, the problem is again that the Win32 metadata assumes `GetLastError` returns an invented `WIN32_ERROR` type rather than just `DWORD`. So then when you ask the resulting `WIN32_ERROR` to convert to an `HRESULT` it naturally assumes the Win32 facility.

**Comment by dergecko** [comment]
I see you labeled this as a question how can I further help to resolve the issue?
Manually adjusting the `HRESULT` to fit the calling facility every time is not very convenient. 
Can you elaborate on how to handle this?

**Comment by riverar** [comment]
Oh that's just a tag for internal housekeeping. This is not strictly a crate bug but rather an external one.

I think we have all the info we need on this, it's just going to require a bit of work upstream in the metadata project. We'll ping this thread when there's more to report!

**Comment by kennykerr** [comment]
Today the metadata only indicates that `GetLastError` should be called on failure but not what facility should be used to convert that to an `HRESULT` if needed. Options include:

* Enrich the metadata with this information 
* Throttle back the transformations and just return the actual error code as `Result<(), u32>`
* Don't do any transformation and stick with what `windows-sys` provides

**Comment by riverar** [comment]
Agreed. I think metadata should rollback its `WIN32_ERROR` transformation and give us a raw u32. Projections can then return the error code to the user (option 2). Longer term, metadata could give us more facility context, in which projections could then do something smarter (option 1).

**Comment by ChrisDenton** [comment]
While I think it would be good to have metadata for "assume `HRESULT`", "assume `WIN32_ERROR`", etc, I'm not sure that we can ever be 100% confident that `GetLastError` returns the expected error type in all situations. For example, a `NTSTATUS` can sometimes show up where a `WIN32_ERROR` is expected.

**Comment by kennykerr** [comment]
Yep, 2 or 3 seem to be the only reliable options.

**Comment by riverar** [comment]
This is getting into the win32metadata weeds here but I was thinking we'd have something like this on APIs (perhaps starting with APIs that are today marked with SetLastError=true)

```csharp
[DllImport("KERNEL32.dll", ..., SetLastError = true)]
[LastErrorContext(Facility = Win32)]
public unsafe static extern HANDLE CreateFileW(...)
```

**Comment by kennykerr** [comment]
That would be nice, but the issue that Chris was hinting at is that as APIs are often implemented in terms of other APIs, you can get into a situation where you cannot really guarantee this is true since the error code can bubble up from some other very different layer of the stack, at least in the general case.

**Comment by kennykerr** [comment]
We can potentially improve the situation for option 2 by updating `windows::core::Error` to store either `HRESULT` or `u32` so that it still uses the same error type but in a lossless manner and thereby supporting error propagation seamlessly.

**Comment by ChrisDenton** [comment]
I do think it'd be useful for the metadata to include the expected error type. I'm less sure to what extent the `windows` crate can take advantage of the type hint but I think it'd be good for projections to at least have the option (or to maybe just display it in documentation).

**Comment by kennykerr** [comment]
I had a look at implementing this but there are just a lot of places where we have to assume some facility in order to turn the result of `GetLastError` into an `HRESULT` to the point where `HRESULT_FROM_WIN32(GetLastError())` is just a reality even if it is always the "most correct" thing to do.

**Comment by kennykerr** [comment]
In the short term I think that the best we can do is avoid the transformation on `GetLastError` so that it returns an error code rather than automatically converting it to a `Result`. That way, if you know that the result may not be a Win32 error code then at least you can make that determination yourself. In the long run we should ditch `WIN32_ERROR` altogether. 

But there will always be places where we must convert the result of `GetLastError` to an `HRESULT` and in those general cases we have to assume a Win32 facility as that is the norm.

**Comment by ChrisDenton** [comment]
Hm, the C/C++ definition of [`HRESULT_FROM_WIN32`](https://learn.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-hresult_from_win32) is:

```cpp
((HRESULT)(x) <= 0 ? ((HRESULT)(x)) : ((HRESULT) (((x) & 0x0000FFFF) | (FACILITY_WIN32 << 16) | 0x80000000)))
```

Whereas the [windows-rs definition](https://github.com/microsoft/windows-rs/blob/2ab384420f1eef0eca5229b546a00e4e2d80d263/crates/libs/core/src/hresult.rs#L96) is:

```rust
if error == 0 { 0 } else { (error & 0x0000_FFFF) | (7 << 16) | 0x8000_0000 } as i32
```

The difference is the `<= 0` vs. `== 0`. Maybe we should do the same, at least in the case of the `Error` type, then we'll be no worse than C++. We could even go further and also pass though anything `> u16::MAX` but maybe that's too extra.

**Comment by kennykerr** [comment]
> The difference is the <= 0 vs. == 0.

That's because in Rust the "last error" is `u32` whereas in C++ it's "whatever". 😉

**Comment by ChrisDenton** [comment]
I'm starting to think "returns whatever" is a fair description of `GetLastError` 😆

**Comment by kennykerr** [comment]
More seriously, the `(HRESULT)(x) <= 0` in the macro exists so that if `GetLastError` actually returns an `HRESULT` (as in the case of `CertFindCertificateInStore`) rather than a traditional Win32 error code, then the [severity bit](https://en.wikipedia.org/wiki/HRESULT) will be detected here as a negative `long` value and not reencoded. We should probably just do the same careful dance and call it a day.

**Comment by ChrisDenton** [comment]
Yes, I agree with that.
