### ISSUE TITLE
Ability to prevent linking of dlls

### ISSUE THREAD

**Issue by wmmc88** [microsoft/windows-rs#2640]
### Suggestion

I wanted to be able to only import NTSTATUS values from this crate, but doing so pulls in many dlls. The way in which the dlls are imported actually breaks my build because it forces some of my own ffi bindings to try to link against `ntdll` instead of my own dlls.

**Comment by wmmc88** [comment]
enabling `windows_raw_dylib` does prevent the linking issue! When might `windows_raw_dylib` become the default?

**Comment by kennykerr** [comment]
`raw-dylib` is finally stabilized so it's just a matter of time before the MSRV can handle it. Not sure yet when that will be.

**Comment by wmmc88** [comment]
Im not sure what you mean by "the MSRV can handle it". According to https://github.com/rust-lang/rust/issues/58713, it looks like the feature was stabilized for 1.65, so isn't it just a matter of when you decide to increase the msrv to >= 1.65? What is the policy for increasing msrv in `windows-rs` crates?

Aside: It looks like the msrvs listed in [the docs](https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html) don't match with the ones defined [in the cargo.tomls](https://github.com/microsoft/windows-rs/blob/b769fa7570f8eeaede0ed1995a7dbe1e9591a35b/crates/libs/sys/Cargo.toml#L11C1-L11C1)

**Comment by kennykerr** [comment]
I just bumped it to 1.56.0 - it will likely be a while until it gets bumped to 1.65, but your scenario is a little different so I wouldn't worry about that. 

Yes, I need to update the docs.

**Comment by kennykerr** [comment]
I have updated the docs at https://kennykerr.ca/
