### ISSUE TITLE
Maybe better to convert function param names to snake_case

### ISSUE THREAD

**Issue by stackinspector** [microsoft/windows-rs#2649]
### Suggestion

In the current bindgen, function param names are simply `to_lowercase`d. The Windows APIs uses the Hungarian notation conventions for function param names, which is basically PascalCase plus a type prefix. Perhaps it would be better to convert them to snake_case, or even consider removing type prefixes that make little sense in a Rust context.
For example, `dwFlagsAndAttributes`, directly `to_lowercase`ing turns it into unrecognizable `dwflagsandattributes`. Converting it to `dw_flags_and_attributes` would be much clearer, and removing the type prefixes to `flags_and_attributes` would be more consistent with Rust.

**Comment by riverar** [comment]
Hey @stackinspector, we talked about this before in https://github.com/microsoft/windows-rs/issues/112. Trying to change the names introduced a bunch of complexity and friction with little to no benefit. Check out that thread for more details! Closing this for now but feel free to continue the discussion if needed.

**Comment by stackinspector** [comment]
Then why not keep the names completely unchanged without `to_lowercase`?
