### ISSUE TITLE
Please provide some custom COM server and COM client example,thx.

### ISSUE THREAD

**Issue by yzytom** [microsoft/windows-rs#2650]
### Suggestion

It's difficulty to code the custom COM server and COM client due to destructive updates.

**Comment by kennykerr** [comment]
It's WinRT but it's basically the same thing, just with slightly different exports and IDL syntax:

https://github.com/microsoft/windows-rs/tree/master/crates/tests/component
https://github.com/microsoft/windows-rs/tree/master/crates/tests/component_client

I've been meaning to add COM-specific examples though.

**Comment by TsuITOAR** [comment]
Hi, can I get some help? 
I can't figure out how to generate bindings for a COM dll or an idl, seems the commands for generating the win32meta file in component build.rs don't work here. 
I successed with [winapi-tlb-bindgen](https://github.com/Arnavion/winapi-tlb-bindgen), which depends on winapi.

**Comment by TsuITOAR** [comment]
> Hi, can I get some help? I can't figure out how to generate bindings for a COM dll or an idl, seems the commands for generating the win32meta file in component build.rs don't work here. I succeeded with [winapi-tlb-bindgen](https://github.com/Arnavion/winapi-tlb-bindgen), which depends on winapi.

I made it with Microsoft.Windows.WinmdGenerator, for anyone that concerns, there is a good example: https://github.com/Traverse-Research/amd-ext-d3d-rs/tree/main/.metadata
