### ISSUE TITLE
DispatcherQueue return err The operation completed successfully.

### ISSUE THREAD

**Issue by NiiightmareXD** [microsoft/windows-rs#2652]
### Summary

This is just a simple bug, but DispatcherQueue::GetForCurrentThread() returns the error: The operation completed successfully.

**Comment by kennykerr** [comment]
According to the docs, that means "no such DispatcherQueue exists." 

https://learn.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue.getforcurrentthread?view=winrt-22621
