### ISSUE TITLE
Release request for windows 0.52

### ISSUE THREAD

**Issue by chyyran** [microsoft/windows-rs#2663]
If there aren't any new features coming down the pipeline soon, I'd like to request a release of `windows` to take advantage of https://github.com/microsoft/windows-rs/pull/2658. If it's not too much, I'd also like to request `windows-sys` to be released for some yet-to-be published projects, which add some missing WDK signatures.

I have verified my usage of `windows` against `master` in https://github.com/SnowflakePowered/winfsp-rs/pull/26, just waiting for the release to be able to publish, and `windows-sys` privately.

**Comment by riverar** [comment]
@kennykerr I'd like to get us caught up on metadata, we're quite behind. (A Rust-blocking bug in metadata was fixed, so should be smooth sailing. Will check that tonight.)

**Comment by kennykerr** [comment]
Sorry for the delay - been off the grid camping. 🏕️

**Comment by kennykerr** [comment]
I can release another update of the `windows` crate, but it sounds like we can hold on the `windows-sys` crate until you're closer to publishing those dependents. 

We also updated the metadata #2664 if you'd like to test that before I publish again.
