### ISSUE TITLE
Hide `windows-sys`'s documentation behind a feature flag?

### ISSUE THREAD

**Issue by LikeLakers2** [microsoft/windows-rs#2665]
### Suggestion

Hi! I've been building a program that uses the `bevy` game engine crate, and in the midst of this, I've found it useful to render documentation for everything via `cargo doc`.

However, I noticed that the `windows-sys` crate generates quite a lot of documentation. Unfortunately, `cargo doc` has no way to exclude certain dependencies without excluding all dependencies (the `--exclude` flag only seems to work on packages that are within the current workspace).

I don't believe this is an issue with the `windows-sys` crate, per se - it's doing its job just fine. However, unless a user is using `windows-sys` directly, they may not need to see `windows-sys`'s documentation anyways - meaning `windows-sys`'s documentation is simply wasting disk space, and worse, making `cargo clean` take a lot longer due to the mass amount of files generated.

Still, some users may need `windows-sys`'s docs, so hiding them behind a blanket `#[doc(hidden)]` may not be a good idea. Perhaps `windows-sys` could attach `#[doc(hidden)]` to most stuff, *unless* a certain feature flag (let's say `windows-sys/render_docs`) is specified?

I just think it may be useful to avoid generating so much documentation unless a user needs it.

**Comment by riverar** [comment]
So you'd like to generate docs for your crate and all dependencies except `windows-sys`, right? (Just making sure I understand, thanks!)

**Comment by LikeLakers2** [comment]
Yes. `windows-sys` generates a lot of documentation, and because I'm using the `bevy` game engine crate, I have no need to look at the `windows-sys` documentation ever. So I'd like a way to avoid generating `windows-sys` documentation.

There is https://github.com/rust-lang/cargo/issues/4049, however that was opened in 2017 with no plans to add it yet. Thus, as a stopgap, I'm hoping `windows-sys` can provide a method to skip generating so much documentation.

**Comment by kennykerr** [comment]
Hey, sorry for the delay. Been off the grid camping. 🏕️

Just catching up here but this is what I do. Is that sufficient?

```cargo doc -p package --all-features --no-deps```

**Comment by LikeLakers2** [comment]
@kennykerr It could work, but given the large number of `bevy_*` crates that I'd actually want to look at in the resulting documentation, plus the fact that I have other dependencies Id want the documentation for, specifying each wanted package isn't really something I'd be keen on doing.

I'd much rather just ask for a way to exclude certain crates (i.e. `windows-sys`) than need to include every crate I want as a command line parameter.

**Comment by kennykerr** [comment]
Fair enough. I've been meaning to reduce the overhead of doc comments for other reasons, so I'll keep this in mind for that effort.

**Comment by kennykerr** [comment]
Mainly just for me: if we add `#![doc(hidden)]` to the crate's `lib.rs` file then all docs are effectively removed, rather than having to add the attribute to each and every item individually.

**Comment by LikeLakers2** [comment]
@kennykerr If it isn't too much effort, you may still want to leave a note on the crate root so as to avoid confusion. For example, "Documentation is disabled. To view documentation, pass `--features "windows-sys/render_docs"` to cargo." or similar. That way, folks aren't confused when the documentation suddenly isn't visible.

**Comment by riverar** [comment]
Not a fan of tying docs to a feature. It's not part of the standard _cargo doc_ experience and folks will overlook it causing confusion. We should really try to lean on https://github.com/rust-lang/cargo/issues/4049 more.

**Comment by LikeLakers2** [comment]
@riverar I agree - but the reason I suggested a feature anyways is solely for the interim. Plus, given that it's been over six years since that issue was opened, and there doesn't appear to be many comments, I'm not exactly hopeful that it'll be added soon.

**Comment by kennykerr** [comment]
Sure, I wouldn't exclude docs automatically. If provided, that would be something that you would have to opt in to.

**Comment by kennykerr** [comment]
There are also cfg options.

https://github.com/microsoft/windows-rs/blob/master/.cargo/config.toml

**Comment by kennykerr** [comment]
Features are meant to be additive so that doesn't seem like a natural fit. I experimented with a [cfg option](https://github.com/microsoft/windows-rs/blob/master/.cargo/config.toml) but `rustdoc` seems to fail to handle `cfg_attr` correctly.

```rust
// lib.rs
#![cfg_attr(windows_doc_hidden, doc(hidden))]
```

This would seem like the simplest and most natural way to skip doc generation for the crate, if it worked.

**Comment by LikeLakers2** [comment]
> Features are meant to be additive so that doesn't seem like a natural fit.

I'm confused. With what I suggested, using the feature adds the documentation - and not using the feature removes it. Thus, it seems like a `windows-sys/render_docs` feature would be additive.

Could you perhaps elaborate?

**Comment by kennykerr** [comment]
I was assuming the docs feature would need to be enabled by default, but I don't suppose that is necessary.

**Comment by LikeLakers2** [comment]
Ah, okay that makes sense.

Yeah, my thought is that the vast majority of things that will rely on `windows-sys`, will rely on it indirectly - usually due to a crate somewhere in their dependency tree, which likely abstracts away stuff from `windows-sys`.

Thus, the vast majority of Rust crates will have little need for the `windows-sys` docs during development. This means that documentation could be disabled by default - only being enabled when someone actually needs the documentation, using a feature flag passed to `cargo doc` or `cargo-watch`.
