### ISSUE TITLE
Incorrect codegen for `DSTORAGE_REQUEST_OPTIONS`

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/windows-rs#2667]
### Summary

When using `windows_bindgen` on the winmd file supplied with direct storage (https://www.nuget.org/packages/Microsoft.Direct3D.DirectStorage/1.2.1) the following struct gets generated for `DSTORAGE_REQUEST_OPTIONS`

```
#[repr(C)]
pub struct DSTORAGE_REQUEST_OPTIONS {
    pub _bitfield1: u8,
    pub Reserved1: [u8; 7],
    pub _bitfield2: u64,
}
```

However this makes the struct 2x as big as it should be. The original C struct is

```
struct DSTORAGE_REQUEST_OPTIONS {
  DSTORAGE_COMPRESSION_FORMAT       CompressionFormat : 8;
  DSTORAGE_REQUEST_SOURCE_TYPE      SourceType : 1;
  DSTORAGE_REQUEST_DESTINATION_TYPE DestinationType : 7;
  UINT64                            Reserved : 48;
};
```

**Comment by riverar** [comment]
The original C struct is 

```cpp
struct DSTORAGE_REQUEST_OPTIONS {
    /// <summary>
    /// DSTORAGE_COMPRESSION_FORMAT indicating how the data is compressed.
    /// </summary>
    DSTORAGE_COMPRESSION_FORMAT CompressionFormat : 8;

    /// <summary>
    /// Reserved fields. Must be 0.
    /// </summary>
    UINT8 Reserved1[7];

    /// <summary>
    /// DSTORAGE_REQUEST_SOURCE_TYPE enum value indicating whether the
    /// source of the request is a file or a block of memory.
    /// </summary>
    DSTORAGE_REQUEST_SOURCE_TYPE SourceType : 1;

    /// <summary>
    /// DSTORAGE_REQUEST_DESTINATION_TYPE enum value indicating the
    /// destination of the request. Block of memory, resource.
    /// </summary>
    DSTORAGE_REQUEST_DESTINATION_TYPE DestinationType : 7;

    /// <summary>
    /// Reserved fields. Must be 0.
    /// </summary>
    UINT64 Reserved : 48;
};
```

**Comment by Jasper-Bekkers** [comment]
Interesting. msdn has the listing I quoted.

https://learn.microsoft.com/en-us/windows/win32/dstorage/dstorage/ns-dstorage-dstorage_request_options

**Comment by Jasper-Bekkers** [comment]
At least that means the header file and the Rust struct sizes are the same, it's still rather difficult to figure out how the struct members need to be filled out, but that's another issue.

**Comment by riverar** [comment]
Anything in the docs there will be for the OS-provided DirectStorage. The NuGet ships with its own headers. Not sure what the compatibility guarantee is between that SDK that the OS. @MarijnS95 thoughts?

Will close for now, but let's continue to chase this down!

**Comment by Jasper-Bekkers** [comment]
> Will close for now, but let's continue to chase this down!

I'll follow this up with MS as a doc bug instead, thanks for the quick pair of eyes!

**Comment by riverar** [comment]
@Jasper-Bekkers No problem! cc: @damyanp

**Comment by MarijnS95** [comment]
> Not sure what the compatibility guarantee is between that SDK and the OS. @MarijnS95 thoughts?

No clue whatsoever, for obvious reasons :wink:

**Comment by damyanp** [comment]
There is no "OS provided DirectStorage", so this isn't an issue.

**Comment by riverar** [comment]
My mistake. The docs are confusingly listed under Win32 and don't match the Microsoft.Direct3D.DirectStorage NuGet, so I incorrectly assumed Windows 11 shipped with something inbox. Looks like a docbug here then as @Jasper-Bekkers originally pointed out.

**Comment by damyanp** [comment]
Oh, I should also add that the two versions of the struct are actually the same size.  We made the change in the struct header in version 1.2.0 to make this more obvious.  

See https://github.com/microsoft/DirectStorage/issues/22.
