### ISSUE TITLE
IMAGE_LOAD_CONFIG_DIRECTORY64 should not be #[repr(packed(4))]

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/windows-rs#2669]
### Summary

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/struct.IMAGE_LOAD_CONFIG_DIRECTORY64.html

This struct currently seems to be marked as #[repr(C, packed(4))], however I don't see any documentation which claims that it should actually be packed? Is this a mistake or am I mistaken?

**Comment by ChrisDenton** [comment]
winnt.h uses `#include "pshpack4.h"` for a bunch of types. Specifically for IMAGE_LOAD_CONFIG_DIRECTORY64, see the comment on line 19968 in SDK 10.0.22621.0.

**Comment by Ben-Lichtman** [comment]
Strange that it does this for IMAGE_LOAD_CONFIG_DIRECTORY64 but not IMAGE_LOAD_CONFIG_DIRECTORY32? Also it doesn't seem to be documented anywhere...

**Comment by Ben-Lichtman** [comment]
Ir should the IMAGE_LOAD_CONFIG_DIRECTORY32 also be marked as packed(4)?

**Comment by ChrisDenton** [comment]
`IMAGE_LOAD_CONFIG_DIRECTORY32` is similarly packed in the headers but also it's naturally `packed(4)` so explicitly packing is redundant.

**Comment by Ben-Lichtman** [comment]
Oh I see. Well then since I was mistaken I'll close this issue

**Comment by Ben-Lichtman** [comment]
@ChrisDenton it seems that IMAGE_LOAD_CONFIG_DIRECTORY64 contains no padding, so shouldn't packing be unnecessary here?

**Comment by riverar** [comment]
`winnt.h` starts with a `#include "pshpack4.h"` and pushes/pops the packing stack until eventually hitting `#include "poppack.h"`, returning to the original 4 byte packing, before the definitions to `IMAGE_LOAD_CONFIG_DIRECTORY32` and `IMAGE_LOAD_CONFIG_DIRECTORY64` follow.

**Comment by ChrisDenton** [comment]
It does contain 8 byte aligned values so the struct itself will be 8 byte aligned without the `packed(4)`.

**Comment by Ben-Lichtman** [comment]
Thanks Chris, I understand it now
