### ISSUE TITLE
SendMessageW\SendMessageTimeoutW is not opening files in office app even after successfully sent message result

### ISSUE THREAD

**Issue by avijayaraghaMS** [microsoft/windows-rs#2672]
### Summary

Hi,

Below is my scenario

1. create a process using std::process::cmd  which opens a word application
2. Find the word window using "windows_sys::Win32::UI::WindowsAndMessaging::FindWindowW;"
3. Try to open a file in the word window "using windows_sys::Win32::UI::WindowsAndMessaging::SendMessageW;"

The message returns result as message sent successfuly but the word application does not open the file or do anything
Note:
1. I tried Error::last_os_error(); just after calling the sendmessageW function to catch if any error occurs
2. I have tried the process without attaching the debugger 

### Crate code

```Rust
let mut child = match Command::new(application)
        .arg("/K")
        .spawn();

let process_id = std::process::Child::id(&child);
let window_title = "Word";
let window_title_wide: Vec<u16> = OsString::from(&window_title).encode_wide().chain(Some(0)).collect();
let window_handle = unsafe { FindWindowW(null_mut(), window_title_wide.as_ptr()) };

// Send a message to the main window to open the file
let filename_wide: Vec<u16> = OsString::from(filename).encode_wide().chain(Some(0)).collect();
let lparam = filename_wide.as_ptr() as LPARAM;
let wparam = (0x7B as u32) as WPARAM;
let result = unsafe {
       SendMessageW(window_handle, WM_COMMAND, wparam, lparam,)
    };

let os_error = Error::last_os_error();
println!("After sending message last OS error: {os_error:?}");
```

**Comment by avijayaraghaMS** [comment]
FYI: I need to attach debugger to the process after opening the application. so that if any crash happens while opening file I can get the crash dumps

**Comment by kennykerr** [comment]
You may want to reach out to the Office team to find out whether this is even a supported way to automate Office tasks. Given what you're trying to do, the question seems far more specific to Office than it is to the `SendMessage` API call.

**Comment by riverar** [comment]
Hey @avijayaraghaMS!

Not sure what you're trying to do, but here's a sample that launches Word, waits a bit, then activates what I'm guessing is the `IDM_ABOUT` accelerator. (I don't have a list handy at the moment.) Tested with Word `Version 2309 (16827.20122) Preview`.

```toml
[package]
name = "app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
version = "0.51.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging"
]
```

```rust
use std::process::Command;

use windows::{
    core::w,
    Win32::{
        Foundation::{LPARAM, WPARAM},
        UI::WindowsAndMessaging::{FindWindowW, SendMessageW, WM_COMMAND},
    },
};

fn main() -> windows::core::Result<()> {
    unsafe {
        Command::new(r#"C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE"#)
            .arg("/K")
            .spawn()
            .expect("Failed to start Microsoft Word.");

        std::thread::sleep(core::time::Duration::from_secs(3));

        let hwnd = FindWindowW(None, w!("Word"));
        debug_assert!(hwnd.0 > 0);

        let _ = SendMessageW(
            hwnd,
            WM_COMMAND,
            WPARAM(0x00_08 /* Menu (0) => IDM_ABOUT */),
            LPARAM(0),
        );
    }

    Ok(())
}
```

Closing for now as there doesn't appear to be a crate bug here, but feel free to keep the discussion going!
