### ISSUE TITLE
API not found

### ISSUE THREAD

**Issue by isgxd** [microsoft/windows-rs#2677]
### Summary

I can't find the following two APIs on [windows crate](https://microsoft.github.io/windows-docs-rs/doc/windows/index.html):

- [MFGetAttributeSize](https://learn.microsoft.com/en-us/windows/win32/api/mfapi/nf-mfapi-mfgetattributesize)
- [MFSetAttributeSize](https://learn.microsoft.com/en-us/windows/win32/api/mfapi/nf-mfapi-mfsetattributesize)

Crate version: 0.51.0

**Comment by isgxd** [comment]
And this:

- MFGetAttributeUINT32
- MFGetAttributeUINT64

**Comment by Nerixyz** [comment]
If you look in `mfapi.h`, then you can see that `MFGetAttributeSize` is an inline function - a call to `MFGetAttribute2UINT32asUINT64`, which is another inline function:

```c
inline
void
Unpack2UINT32AsUINT64(UINT64 unPacked, _Out_ UINT32* punHigh, _Out_ UINT32* punLow)
{
    *punHigh = HI32(unPacked);
    *punLow = LO32(unPacked);
}

inline
HRESULT
MFGetAttribute2UINT32asUINT64(
    IMFAttributes*  pAttributes,
    REFGUID         guidKey,
    _Out_ UINT32*   punHigh32,
    _Out_ UINT32*   punLow32
    )
{
    UINT64 unPacked;
    HRESULT hr = S_OK;

    hr = pAttributes->GetUINT64(guidKey, &unPacked);
    if (FAILED(hr)) {
        return hr;
    }
    Unpack2UINT32AsUINT64(unPacked, punHigh32, punLow32);

    return hr;
}
```

This crate can't create bindings for these functions. You have to implement them yourself.

**Comment by isgxd** [comment]
That's it, thank you very much.

**Comment by tim-weis** [comment]
See [Where's my favorite macro from the Windows SDK?](https://kennykerr.ca/rust-getting-started/where-are-the-macros.html#wheres-my-favorite-macro-from-the-windows-sdk) for more information.
