### ISSUE TITLE
Type of WINDOWPLACEMENT.showCmd doesn't match with SHOW_WINDOW_CMD

### ISSUE THREAD

**Issue by psmit** [microsoft/windows-rs#2678]
### Summary

If I understand the https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-windowplacement documentation correctly, the valid values for `showCmd` in WINDOWPLACEMENT is a `SHOW_WINDOW_CMD`. Unfortunately, these are currently incompatible types.

**Comment by tim-weis** [comment]
This is unfortunate, but there isn't much the `windows` crate can do. It just follows what is defined in the Windows SDK header files, and the `WINDOWPLACEMENT` field's `showCmd` type doesn't agree with the type of `nCmdShow` passed into `ShowWindow`.

Manual conversion is required to feed one of the `SHOW_WINDOW_CMD` constants into the `WINDOWPLACEMENT` structure, e.g.,

```rust
WINDOWPLACEMENT {
    showCmd: SW_SHOW.0 as u32,
    // ...
```
