### ISSUE TITLE
Memory mapped file run-time error

### ISSUE THREAD

**Issue by redwolf-12** [microsoft/windows-rs#2681]
### Summary

Good morning and thank you for the wonderful project.
I apologize for asking for help here, but I couldn't find any forums for beginners.
I would like to know why this simple program doesn't work.
It compiles correctly, but the call to WriteFile fails at run-time during debugging with this error:

-----------------------------------
Exception thrown at 0x00007FFE338352DD (KernelBase.dll) in test01.exe: 0xC0000005: Access violation writing location

in "mod.rs" at line 3964 
{
    ::windows_targets::link!("kernel32.dll" "system" fn WriteFile(hfile : super::super::Foundation:: HANDLE, lpbuffer : *const u8, nnumberofbytestowrite : u32, lpnumberofbyteswritten : *mut u32, lpoverlapped : *mut super::super::System::IO:: OVERLAPPED) -> super::super::Foundation:: BOOL);
    WriteFile(hfile.into_param().abi(), ::core::mem::transmute(lpbuffer.as_deref().map_or(::core::ptr::null(), |slice| slice.as_ptr())), lpbuffer.as_deref().map_or(0, |slice| slice.len() as _), ::core::mem::transmute(lpnumberofbyteswritten.unwrap_or(::std::ptr::null_mut())), ::core::mem::transmute(lpoverlapped.unwrap_or(::std::ptr::null_mut()))).ok()
} 

------------------------------------------------------------------

Thanks in advance for any help you can provide me.
Best regards,
Andrea

### Crate manifest

```TOML
[package]
name = "test01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
version = "0.51"
features = [
    "Data_Xml_Dom",
    "Win32_System_Memory",
    "Win32_System_IO",
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",

]
```

### Crate code

```Rust
use windows::{
    core::*, core::w, Win32::Foundation::*, Win32::System::Memory::*,
};
use windows::Win32::Storage::FileSystem::*;
use std::os::raw::*;


fn main() {
	
	let pcwstr_name = PCWSTR::from(w!("MyFileMappingObject"));
	let BUF_SIZE = 256;
        let p_buf:MEMORY_MAPPED_VIEW_ADDRESS;
	
	//windows::Win32::System::Memory::CreateFileMappingW();
	unsafe {
		
		let file_handle = CreateFileMappingW(INVALID_HANDLE_VALUE,None,PAGE_READWRITE,0,BUF_SIZE as u32,pcwstr_name);
		if(!file_handle.is_ok()){
			println!("file_handle is broken!");
			return;
		}

		let handle = match file_handle {
			Ok(file) => file,
			Err(error) => panic!("Problem opening the file: {:?}", error),
		};

		let p_buf = MapViewOfFile(file_handle.unwrap(), FILE_MAP_ALL_ACCESS, 0, 0, BUF_SIZE);
		
                if(p_buf.Value == 0 as *mut c_void) {
	               println!("Cannot map a view!");
	               return;
                }

		let str_data = String::from("Hello world!");
		let u8_data: Option<&[u8]> = Some(str_data.as_bytes());
		let u8_len: Option<*mut u32> = Some(str_data.len() as *mut u32);
		
		let res_writefile = WriteFile(handle, u8_data, u8_len,None);

               UnmapViewOfFile(p_buf);

	       CloseHandle(handle);

	}

	let mut line = String::new();
	let b1 = std::io::stdin().read_line(&mut line).unwrap();
	
}
```

**Comment by redwolf-12** [comment]
Good morning,
I modified the relevant code lines like this:

            ...
		let str_data = String::from("Hello world!");
		let u8_data: Option<&[u8]> = Some(str_data.as_bytes());
		let mut u32_len:u32 = str_data.len() as u32;
		let raw_u32_len: *mut u32 = &mut u32_len;
		let u8_len: Option<*mut u32> = Some(raw_u32_len);
		
		let res_writefile = WriteFile(handle, u8_data, u8_len, None);
            ...

Now the call to WriteFile no longer throws exceptions. Unfortunately WiteFile now returns error code 0x80070006 (INVALID HANDLE). 
I do not understand. The handle returned by CreateFileMapping has a value, but it seems wrong for the WriteFile function. Could you kindly give me some suggestions?

Thank you very much.

**Comment by tim-weis** [comment]
A file mapping object makes a filesystem object appear as though it were a contiguous region of memory in the virtual address space of the calling process. `MapViewOfFile()` returns a pointer to the beginning of that memory. Writing to the file mapping is a matter of writing to the memory directly. You can use [`ptr::copy_nonoverlapping`](https://doc.rust-lang.org/std/ptr/fn.copy_nonoverlapping.html), for example.

You cannot, however, use the handle returned from `CreateFileMapping()` in a call to `WriteFile()`.

Keep in mind that currently there is no way to use file mapping objects safely in Rust. Errors are reported using SEH exceptions for which Rust has no provisions to deal with at this time.

**Comment by kennykerr** [comment]
> I apologize for asking for help here, but I couldn't find any forums for beginners.

For general API questions I would start with:

* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
* https://stackoverflow.com/questions/tagged/windows-rs
