### ISSUE TITLE
Provide sample on how to create a Windows service with Rust

### ISSUE THREAD

**Issue by Morotai** [microsoft/windows-rs#2691]
### Suggestion

I've seen other crates like "windows_service" that show how to create a Windows service and was wondering if you can provide a sample with this crate. Thanks.

**Comment by kennykerr** [comment]
The `windows` crate does not provide wrappers but instead provides access to the underlying APIs you need to call to implement such things. You can for example call `StartServiceCtrlDispatcher`, `RegisterServiceCtrlHandler`, and so on but you'll have to find your own abstraction for making it more convenient. If you'd like to call these functions directly, I wrote about how to create Windows services years ago...

https://asp-blogs.azurewebsites.net/kennykerr/Toward-Better-Design-in-Native-C_2B002B00_
https://learn.microsoft.com/en-us/archive/msdn-magazine/2008/launch/windows-with-c-windows-services-enhancements

**Comment by Morotai** [comment]
Thanks Kenney. Was hoping for an example like the one provided by the crate below but will take a look at the above: https://docs.rs/windows-service/latest/windows_service/

**Comment by Morotai** [comment]
Sure thing. Thanks Kenny!
