### ISSUE TITLE
EXCEPTION_CONTINUE_EXECUTION in C != Kernel::ExceptionContinueExecution.0 in Rust

### ISSUE THREAD

**Issue by vvoznesensky** [microsoft/windows-rs#2692]
### Summary

excpt.h: #define EXCEPTION_CONTINUE_EXECUTION (-1)

Kernel\mod.rs: pub const ExceptionContinueExecution: EXCEPTION_DISPOSITION = 0i32;

**Comment by ChrisDenton** [comment]
They're different things. In C, see that the `EXCEPTION_DISPOSITION` enum has `ExceptionContinueExecution`. The rust crates don't have `EXCEPTION_CONTINUE_EXECUTION` defined.

The reason for this is that the crates are generated from [metadata](https://github.com/microsoft/win32metadata), which doesn't currently have it. They should be able to add it though.

**Comment by vvoznesensky** [comment]
> They're different things. In C, see that the `EXCEPTION_DISPOSITION` enum has `ExceptionContinueExecution`. The rust crates don't have `EXCEPTION_CONTINUE_EXECUTION` defined.
> 
> The reason for this is that the crates are generated from [metadata](https://github.com/microsoft/win32metadata), which doesn't currently have it. They should be able to add it though.

Thank you, Chris. This mess is very confusing: I cannot imagine why they are the different things, but it took some nerve and time to find the difference.

**Comment by mominshaikhdevs** [comment]
@vvoznesensky just transfer it to the [metadata](https://github.com/microsoft/win32metadata/issues) repo.

**Comment by vvoznesensky** [comment]
> @vvoznesensky just transfer it to the [metadata](https://github.com/microsoft/win32metadata/issues) repo.

Thank you. [Done.](https://github.com/microsoft/win32metadata/issues/1731)

**Comment by ChrisDenton** [comment]
Closing this then. Once this is added to metadata, windows-rs will get it automatically (well, after a metadata update and a new version of the crate is published).

**Comment by tim-weis** [comment]
@ChrisDenton Do you happen to know of any rust-lang issues/RFCs dedicated to SEH support? This topic seems to be one of the few instances where Rust cannot currently replace C.

**Comment by ChrisDenton** [comment]
I'm not aware of anything currently. There's been work on "C unwind" but iirc that deliberately avoided handling SEH exceptions for now. @wesleywiser might know if someone is working on this at all.

Tbh, I usually just make small wrappers in C but it would be super nice if I didn't have to.
