### ISSUE TITLE
Example of using PackageManager?

### ISSUE THREAD

**Issue by fanchenio** [microsoft/windows-rs#2697]
### Summary

Are there any examples of usage?

`app.AppInfo().unwrap()` Tip { code: HRESULT(0x80004002), message: "This interface is not supported" }

It may be that Com is not initialized. How does PackageManager initialize Com?

### Crate code

```Rust
se windows::core::HSTRING;
use windows::Management::Deployment::PackageManager;

fn main() {
    let package_manager = PackageManager::new();
    if package_manager.is_err() {
        println!("{:?}", package_manager.err());
        return;
    }
    let package_manager = package_manager.unwrap();
    let packages = package_manager.FindPackagesByUserSecurityId(&HSTRING::default());
    if packages.is_err() {
        return;
    }
    let packages = packages.unwrap();
    for package in packages {
        for app in package.GetAppListEntries().unwrap() {
            println!("{:?}", app.AppInfo().unwrap());
        }
    }
}
```

**Comment by kennykerr** [comment]
That likely means that the `AppInfo` property was added in a more recent version of Windows than you are using. 

https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.applistentry.appinfo?view=winrt-22621#windows-applicationmodel-core-applistentry-appinfo
