### ISSUE TITLE
support `_exec`, `_wexec` family of functions

### ISSUE THREAD

**Issue by fdncred** [microsoft/windows-rs#2698]
### Suggestion

It would be great to support the `_exec`, `_wexec` family of functions.
https://learn.microsoft.com/en-us/cpp/c-runtime-library/exec-wexec-functions?view=msvc-170

I was recently trying to get this to work with libc but thought it might be better and easier with windows-rs.

**Comment by ChrisDenton** [comment]
The libc crate would be a better fit for that. The windows crate provides bindings to the Windows API, not the C std.

Btw, new APIs should be requested in the [win32metadata](https://github.com/microsoft/win32metadata) repo. That provides all the metadata that's used in this repo to generate bindings. Though requests can be transferred.

**Comment by fdncred** [comment]
ok, thanks chris. Just trying to get exec working on windows in nushell and wasn't having much luck and thought i'd check with windows.
