### ISSUE TITLE
Inconsistency between SOCKET types makes WinSock interop with Rust's UdpSocket nontrivial

### ISSUE THREAD

**Issue by recatek** [microsoft/windows-rs#2700]
### Suggestion

This was initially brought up in #1643, but the discussion was focused primarily on HANDLE, and was closed.

Rust's built-in `UdpSocket` has a Windows-only as_raw_socket method that converts it into a `std::os::windows::io::RawSocket`, which is an alias for `std::os::windows::raw::SOCKET`, a `u64`. WinSock methods like `WSAIoctl` require an `IntoParam<SOCKET>` using `windows::Win32::Networking::WinSock::SOCKET`, which wraps a `usize`.

Since the `as_raw_socket` method is Windows-only to begin with, it would be nice if these two types interfaced better or had a consistent representation (perhaps ideally just using `std::os::windows::raw::SOCKET`).

See also https://github.com/rust-lang/rust/issues/76253

**Comment by riverar** [comment]
Interesting. Thanks for bringing this up.

Rust has a Windows-specific socket primitive defined as such:

```rust
#[cfg(target_pointer_width = "32")]
#[doc(cfg(all()))]
#[stable(feature = "raw_ext", since = "1.1.0")]
pub type SOCKET = u32;
#[cfg(target_pointer_width = "64")]
#[doc(cfg(all()))]
#[stable(feature = "raw_ext", since = "1.1.0")]
pub type SOCKET = u64;
```

I'm curious how this missed becoming a `usize`. 🤔 Looks like the last message on https://github.com/rust-lang/rust/issues/76253 was promising, maybe worth also trying to restart those std discussions?

**Comment by recatek** [comment]
Good point, I left a comment there pointing out the inconsistency and including the windows crate version for reference.

**Comment by ChrisDenton** [comment]
The standard library has strong stability guarantees (i.e. we try not to break existing code) and that issue was last active three years ago. I'm doubtful that we can change it now (but it would be good if we could).

**Comment by kennykerr** [comment]
`SOCKET` is defined as `UINT_PTR` which is a pointer-sized unsigned integer, which is what Rust's `usize` is. 

Closing as there's nothing for `windows-rs` to do here, but feel free to keep the conversation going.
