### ISSUE TITLE
Support for WinSock WSA_CMSG_... macros

### ISSUE THREAD

**Issue by recatek** [microsoft/windows-rs#2701]
### Suggestion

WinSock uses a handful of WSA_CMSG_... macros for interacting with control messages on packets. For example, the WSA_CMSG_SPACE macro is used for safely allocating memory for packet control messages in WSARecvMsg. You can see some examples of its usage here:

- https://learn.microsoft.com/en-us/windows/win32/winsock/winsock-ecn
- https://learn.microsoft.com/en-us/windows/win32/winsock/winsock-timestamping

The public-facing list of these macros can be found here: https://learn.microsoft.com/en-us/windows/win32/api/ws2def/ns-ws2def-wsamsg (namely, WSA_CMSG_FIRSTHDR, WSA_CMSG_NXTHDR, WSA_CMSG_DATA, WSA_CMSG_SPACE, WSA_CMSG_LEN) and in ws2def.h.

I can't find an equivalent set of macros or functions in the windows or windows_sys crates, so if these are indeed missing, they would be good to add it to this library. Without them, there is no good way to interact with packet control messages or headers.

**Comment by tim-weis** [comment]
[Where's my favorite macro from the Windows SDK?](https://kennykerr.ca/rust-getting-started/where-are-the-macros.html) explains why they are missing.

If you need this functionality you'll have to replicate it in your Rust code.

**Comment by recatek** [comment]
Is there an open issue for macro generation support in the library?

**Comment by tim-weis** [comment]
@recatek This topic comes up every now and again, but there isn't a dedicated issue requesting code generation derived from C macros.

This would be incredibly useful to have, and just as hard to tackle. I wouldn't even know how to approach this. The metadata driving the code generation contains descriptions for types, functions, and constants only. Getting the same treatment for macros would require engineering a way to describe *code* in metadata.

I don't expect to ever see this happening.
