### ISSUE TITLE
CreateMutex is broken in the windows crate

### ISSUE THREAD

**Issue by DanielT** [microsoft/windows-rs#2710]
### Summary

`CreateMutexW(None, TRUE, w!("MyGlobalMutex"))` always returns an `Ok(_)` status, even it the mutex already exists.
Windows returns a valid handle in this case, but additionally sets the last error code to `ERROR_ALREADY_EXISTS`.
The rust wrapper code checks `result__.is_invalid()` and would only call `GetLastError()` if the handle value was `INVALID_HANDLE_VALUE`.

I wrote a testcase to understand what was going on, using both windows and windows-sys.
The idea is to run it in two shell windows. It should report an error in the second one, while the first instance holds the mutex and loops.

My demo code (crate windows):
```rust
use windows::{Win32::{System::Threading::CreateMutexW, Foundation::*}, core::w};

fn main() {
    let mutex_name = w!("MyGlobalMutex");

    match unsafe { CreateMutexW(None, TRUE, mutex_name) }
    {
        Ok(_) => {
            println!("got the mutex");
            loop {
                // endless
            }
        },
        Err(error) => {
            if error.code() == ERROR_ALREADY_EXISTS.into() {
                println!("mutex already exists");
            } else {
                println!("other mutex error");
            }
            return;
        }
    }
}
```

My demo code (crate windows-sys):
```rust
use windows_sys::{
    w,
    Win32::{Foundation::*, System::Threading::CreateMutexW},
};

fn main() {
    let handle = unsafe { CreateMutexW(std::ptr::null(), TRUE, w!("MyGlobalMutex")) };
    let error = unsafe { GetLastError() };
    println!("handle = {handle}, error = {error}");
    if error == ERROR_ALREADY_EXISTS {
        println!("mutex already exists");
    } else if handle != 0 {
        println!("got the mutex");
        loop {
            // endless
        }
    } else {
        println!("other mutex error");
    }   
}
```

**Comment by riverar** [comment]
The `ERROR_ALREADY_EXISTS` information is ancillary/informational for developers in the _open existing mutex_ scenario. That is, some developers may be expecting to open an existing mutex and would ignore this error. I'm not seeing a bug here, but do acknowledge the awkwardness of the API here.

@kennykerr thoughts?

**Comment by DanielT** [comment]
Right, the "is broken" in the title is a bit too strong.
But: no other rust locking API returns an OK value without holding the lock. That sets the expectation here.

For windows-sys, which which is presented as the thinnest of wrappers around the C API, the behavior is fine, but I honestly expected this function from the windows crate to block.

**Comment by kennykerr** [comment]
The `CreateMutexW` wrapper in the `windows` crate will only return an error if the handle is invalid. This should cover all use cases for this function, so I don't see a problem here.
