### ISSUE TITLE
Documentation no longer lists required features

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#2717]
### Summary

Starting with version 0.52.0, the documentation published [here](https://microsoft.github.io/windows-docs-rs/doc/windows/) no longer lists all/some required features.

For example:

* [`OutputDebugStringW`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/Debug/fn.OutputDebugStringW.html) doesn't list any features
* [`GetMessageW`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/fn.GetMessageW.html) doesn't list the full set of features

It looks like the requirements for the containing module have dropped off.

**Comment by ChrisDenton** [comment]
Probably #2671. I think it no longer adds namespace features to the list of features.

**Comment by kennykerr** [comment]
Yep the docs no longer explicitly include the feature for the enclosing module. This caused a huge amount of redundant doc comments and markup. A bit less intuitive for sure, but a tradeoff I think is worthwhile until I find a long-term replacement for rustdoc...

**Comment by junglie85** [comment]
`OutputDebugStringW` does not show up in [search](https://github.com/search?q=repo%3Amicrosoft%2Fwindows-rs+OutputDebugStringW&type=code) results to be able to find the module to use, it only shows the kernel32.dll.c definition. Maybe an edge case, but that makes it difficult to find which feature to enable.

**Comment by junglie85** [comment]
That's fair - I tend to hunt around the GitHub repo rather than use the published docs.

**Comment by tim-weis** [comment]
The only reason I care about the required features is to copy them into the `features` table of a *Cargo.toml* file. This used to work well when *all* features were listed.

After the change, things are far less convenient. It's not entirely unworkable as long as only the containing module's feature is required. When more features are required the documentation starts to feel very hostile (just go through the number of steps needed to get [`GetMessageW`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/fn.GetMessageW.html)'s features into a *Cargo.toml*).

Someone who knows their way around this crate may merely be inconvenienced. To anyone new, this may be reason enough to look into alternatives.

Reverting this change would be very much appreciated.

**Comment by ChrisDenton** [comment]
I wonder if it would help to remove the explicit need for things like `Foundation` and `Win32_Foundation` and instead make them automatically implied by using the relevant namespaces? They're almost certainly needed and I think they should not add significantly to code size in any case.

**Comment by kennykerr** [comment]
Yes, I'm looking for ways to reduce the feature complexity as simply reverting this change doesn't really solve the problem. Continuing to use rustdoc in this way is just not sustainable.

**Comment by kennykerr** [comment]
`cargo doc` has a new `doc_auto_cfg` feature that finally seems to figure this out based on `cfg` attributes so we don't have to generate the redundant `doc` comments any longer. https://github.com/rust-lang/rust/issues/43781

Unfortunately, formatting is not that great.

![image](https://github.com/microsoft/windows-rs/assets/9845234/243c1c1b-2283-45ea-8174-437ccd14ad5f)

**Comment by kennykerr** [comment]
You also need to combine `doc` into all `cfg` attributes using `#[cfg(any(doc, feature = "Win32"))]` instead of just `#[cfg(feature = "Win32")]`. That's pretty lame.

**Comment by kennykerr** [comment]
> I'm not objecting to that. I'm uncomfortable with having the documentation reflect a potentially simpler future world before it exists. Until we're there, the documentation should reflect the current state, with feature complexity and all.

Sure, but somebody has to support that "current state" until some "future world" where `cargo doc` and https://docs.rs/ supports the `windows` crate and I'm just not sure that should be on the `windows` crate. 😊

**Comment by ChrisDenton** [comment]
> `cargo doc` has a new `doc_auto_cfg` feature that finally seems to figure this out based on `cfg` attributes so we don't have to generate the redundant `doc` comments any longer. [rust-lang/rust#43781](https://github.com/rust-lang/rust/issues/43781)
> 
> Unfortunately, formatting is not that great.
> 
> ![image](https://private-user-images.githubusercontent.com/9845234/287736263-243c1c1b-2283-45ea-8174-437ccd14ad5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDY0OTksIm5iZiI6MTcwMTcwNjE5OSwicGF0aCI6Ii85ODQ1MjM0LzI4NzczNjI2My0yNDNjMWMxYi0yMjgzLTQ1ZWEtODE3NC00MzdjY2QxNGFkNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTYwOTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTIyMWY0MGFkMjQwZTQwMjkxNmFjYjRlZTJmYjI2ZmYxMzExZGQ1MjE4NTQ0NGYwNzE2ZmFlYjEwNDZhZGMzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PuGyMHWZEiTMIVcVg0_sVIlh0_1lIY-nVKwT4ow8XBY)

cc @GuillaumeGomez Improving the formatting seems actionable?

**Comment by ChrisDenton** [comment]
[Done](118615).

**Comment by GuillaumeGomez** [comment]
To be more exact: https://github.com/rust-lang/rust/issues/118615

**Comment by tim-weis** [comment]
> Sure, but somebody has to support that "current state" \[...\] and I'm just not sure that should be on the `windows` crate. 😊

That's understood, and ideally, it shouldn't be. Realistically, though, the `windows` team is the only entity that can make up for the shortcomings at this time. No good deed goes unpunished, they say.

The output generated from the `doc_auto_cfg` feature is a regression compared against even the current state:

* Features aren't enclosed in quotation marks, so we must manually add them.
* Features aren't comma-separated, so more editing is required after copy-pasting them over.
* The list of features is correct as far as the compiler is concerned, but it doesn't much help users: For `OutputDebugStringW` only `"Win32_System_Diagnostics_Debug"` needs to be enabled, with "parent features" getting enabled automatically.

Just to let you know, I'm not asking you to change things or take on responsibility for someone else's shortcomings. I'm just a user providing feedback on what works and what doesn't.

**Comment by riverar** [comment]
@fgimian Working on it, sorry for the delay. Here's a temporary tool you can use to unblock you: https://riverar.github.io/4f76cc1e-88ae-41d3-906e-3591c67d2366/

**Comment by fgimian** [comment]
> @fgimian Working on it, sorry for the delay. Here's a temporary tool you can use to unblock: https://riverar.github.io/4f76cc1e-88ae-41d3-906e-3591c67d2366/
> 
> We're working on standing this up next to the official docs shortly.

Thank you so so much for this mate, really appreciate it!! 😄

**Comment by kennykerr** [comment]
I published the docs for `windows` 0.53.0 with the new feature search link:

https://microsoft.github.io/windows-docs-rs/doc/windows/
