### ISSUE TITLE
Device Path missing bytes

### ISSUE THREAD

**Issue by darkdread** [microsoft/windows-rs#2719]
### Summary

The device path returned from `SetupDiGetDeviceInterfaceDetailW` seems to be missing 8 bytes after the initial 4 bytes.
![image](https://github.com/microsoft/windows-rs/assets/6164353/2d8ae9d6-bc19-4a3b-a28e-02d0788e10b4)

The same issue can be seen even if the string is not wide by using `SetupDiGetDeviceInterfaceDetailA`

![image](https://github.com/microsoft/windows-rs/assets/6164353/ad89d5c5-541a-4661-bfd9-f52e2c3c778b)

Does anyone have any clue what's happening here?

### Crate code

```Rust
let info = SetupDiGetClassDevsW(
        None,
        PCWSTR::null(),
        Foundation::HWND::default(),
        DIGCF_ALLCLASSES | DIGCF_DEVICEINTERFACE | DIGCF_PRESENT
)?;
let mut iface: SP_DEVICE_INTERFACE_DATA =
        SP_DEVICE_INTERFACE_DATA::default();
let mut index = 0;
loop {
        index += 1;
        iface.cbSize = size_of::<SP_DEVICE_INTERFACE_DATA>() as u32;
        let ret = SetupDiEnumDeviceInterfaces(
                info,
                None,
                &GUID_DEVINTERFACE_USB_DEVICE,
                index - 1,
                &mut iface,
        )?;

        let mut details = SP_DEVICE_INTERFACE_DETAIL_DATA_W::default();
        details.cbSize = size_of::<SP_DEVICE_INTERFACE_DETAIL_DATA_W>() as u32;
        let ret = SetupDiGetDeviceInterfaceDetailW(
                info,
                &iface,
                Some(&mut details),
                4 * MAX_PATH,
                None,
                None,
        );

        if ret.is_err() {
                continue;
        }

        let path = String::from_utf16(&details.DevicePath);
        dbg!(path);
}
```

**Comment by tim-weis** [comment]
You got unlucky that things *didn't* go up in flames. The code is writing to random stack memory and thus corrupting the stack.

[`SetupDiGetDeviceInterfaceDetailW`](https://learn.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdigetdeviceinterfacedetailw) takes a (variably-sized) buffer and a size (`DeviceInterfaceDetailData` and `DeviceInterfaceDetailDataSize`). The caller must provide a sufficiently sized buffer and cannot lie about its size.

`4 * MAX_PATH` is a lie, when the provided buffer is of size `mem::size_of::<SP_DEVICE_INTERFACE_DETAIL_DATA_W>`.

**Comment by riverar** [comment]
Looks like Tim identified the issue here (thanks!); closing this issue.

In the future, please consider a more appropriate forum for API-specific questions, such as:
* https://stackoverflow.com/questions/tagged/windows-rs
* https://docs.microsoft.com/en-us/answers/topics/windows-api.html
