### ISSUE TITLE
More traits and missing functions

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#2734]
### Suggestion

Many types have an `is_invalid()` method. Wouldn't this justify a trait like `Validatable`/`Validate`? I became aware of this while writing a helper that needed `Validatable` as a trait bound. In the end, that particular helper didn't seem warranted to me, but wouldn't this still be a better crate structure?

Then there could also be a trait like `Null`, which would require the functions `null()` and `is_null()`, like they're implemented for `PWSTR` etc. `HWND`, e.g., could use some more methods like this. It has neither `is_invalid()` nor `is_null()` nor `null()`, although `NULL` `HWND`s aren't that rare. (Can `HWND`s be invalid in the sense of `-1`?)

**Comment by ChrisDenton** [comment]
Using a trait does add complexity and shouldn't be done too lightly. Traits are useful when the user wants to abstract over similar types, not just because the types happen to have similar methods.

In any case, I think adding such "helper" traits to windows-rs would need a strong motivating example where it would be useful in practice. And even then I'd be minded to say it would be better off in a utility crate.

**Comment by Enyium** [comment]
> In any case, I think adding such "helper" traits to windows-rs would need a strong motivating example where it would be useful in practice.

I just wrote [`ResGuard`](https://docs.rs/windows-helpers/latest/windows_helpers/struct.ResGuard.html) with functions like [`with_mut_acq_and_local_free()`](https://docs.rs/windows-helpers/latest/windows_helpers/struct.ResGuard.html#method.with_mut_acq_and_local_free). First, as I proposed [here](https://github.com/microsoft/windows-rs/issues/2464#issuecomment-1849342833), `PWSTR` should implement `CanInto<HLOCAL>`. Then, `PWSTR` could either implement `Default` or all handle types could implement the new `Null`. I would change the trait bound for the mut-variable initialization from `R: Default` to `R: Null`, if needed, and then you would be able to write the code:

```rust
let string_sid = unsafe {
    ResGuard::with_mut_acq_and_local_free(|pwstr|
        ConvertSidToStringSidW(
            (&*sid_and_attrs_buffer.as_ptr().cast::<SID_AND_ATTRIBUTES>()).Sid,
            pwstr,
        )
    )?
    .to_string()?
};
```

I'd say, because of the drop semantics, this is rustier and a pattern generally more adverse against changes than:

```rust
let mut pwstr_sid = PWSTR::null();
unsafe {
    ConvertSidToStringSidW(
        (&*sid_and_attrs_buffer.as_ptr().cast::<SID_AND_ATTRIBUTES>()).Sid,
        &mut pwstr_sid,
    )?
};
let string_sid = unsafe { pwstr_sid.to_string()? };
let _ = unsafe { LocalFree(HLOCAL(pwstr_sid.0.cast())) };
```

**Comment by tim-weis** [comment]
`CanInto<HLOCAL> for PWSTR` has a fundamental flaw: It attributes the allocator to a type (`PWSTR`) when it really is a property of the specific API (`ConvertSidToStringSidW`) producing the value.

Implementing this trait makes writing correct code more convenient, and it makes writing incorrect code equally convenient. It particularly causes code to become *less* resilient under change. Let's not do that.

**Comment by kennykerr** [comment]
I'm not in favor of implicit conversions in general. I think that `windows-rs` overuses them as it is. There are legitimate cases for such conversions, particularly in COM and WinRT, but convertible handles are pretty dangerous as knowing their correctness requires a great deal of knowledge of the specific API calls that you're making.

I'm going to close this issue, but feel free to keep chatting.

**Comment by Enyium** [comment]
There's inconsistency in the API, though: `HANDLE` defines [`impl From<HWND> for HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HANDLE.html#impl-From%3CHWND%3E-for-HANDLE). This seems to be an outlier.

And shouldn't [`HWND`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HWND.html#) get a verification method like almost 200 other handle types? But `is_invalid()` or `is_null()`? May an HWND be -1?

`HWND::null()` (like `PWSTR::null()`) would also be useful. Say, e.g., for calling [`CreateWindowExW()`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/fn.CreateWindowExW.html#), which also accepts C's `NULL` for two other handle types.

**Comment by riverar** [comment]
> There's inconsistency in the API, though: `HANDLE` defines [`impl From<HWND> for HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.HANDLE.html#impl-From%3CHWND%3E-for-HANDLE). This seems to be an outlier.

See https://github.com/microsoft/win32metadata/issues/1660 for context; this is set in upstream metadata resulting in that `From` trait implementation.

```csharp
[AlsoUsableFor("HANDLE")]
[NativeTypedef]
public struct HWND
{
	public IntPtr Value;
}
```

It's probably not quite right, given the _invalid values_ for each type don't match. But we're not going to solve that here today. Handles are an on-going pain point that we're actively working on, in both projects.
