### ISSUE TITLE
Default Initialization of GdiplusStartupInput Structure in Rust Bindings

### ISSUE THREAD

**Issue by deadash** [microsoft/windows-rs#2737]
### Suggestion

Hello,

I've encountered an issue regarding the initialization of the `GdiplusStartupInput` structure within the Rust bindings for GDI+. In C++, the default constructor of `GdiplusStartupInput` initializes the structure with specific default values: `GdiplusVersion = 1`, `DebugEventCallback = NULL`, `SuppressBackgroundThread = FALSE`, and `SuppressExternalCodecs = FALSE`.

However, in the Rust bindings, the default initialization of `GdiplusStartupInput` using `Default::default()` or `zeroed()` methods results in all fields being set to zero, which is not equivalent to the default constructor behavior in C++.

This discrepancy can lead to unexpected behavior, especially for users transitioning from C++ to Rust or those working in mixed-language environments. The absence of a proper default initialization might require additional boilerplate code to set these values manually, which is not immediately apparent and can be error-prone.

I propose adding a new function or modifying the existing implementation to ensure that `GdiplusStartupInput` is initialized with the same default values as in C++. This change would enhance the usability of the Rust bindings and provide a more consistent experience for developers.

Thank you for considering this feature request.

**Comment by tim-weis** [comment]
[Where's my favorite macro from the Windows SDK?](https://kennykerr.ca/rust-getting-started/where-are-the-macros.html) covers the underlying issue: The [metadata](https://kennykerr.ca/rust-getting-started/how-are-crates-built.html) from which the `windows` crate is generated doesn't contain code, and that includes code for C++ (default) constructors.

A consequence of this is that the code a C++ developer writes to initialize GDI+ is different from the code a Rust developer writes. That should go without saying, and the "surprises" come with sufficient information to devise a solution:

```rust
use core::mem::MaybeUninit;

use windows::{
    core::Result,
    Win32::Graphics::GdiPlus::{self, GdiplusStartup, GdiplusStartupInput},
};

fn main() -> Result<()> {
    let mut token = MaybeUninit::uninit();
    let mut output = MaybeUninit::uninit();

    let status = unsafe {
        GdiplusStartup(
            token.as_mut_ptr(),
            &GdiplusStartupInput::default(),
            output.as_mut_ptr(),
        )
    };

    assert_eq!(status, GdiPlus::Ok);

    Ok(())
}
```

```toml
[package]
name = "gdip"
version = "0.0.0"
edition = "2021"

[dependencies.windows]
version = "0.52.0"
features = ["Win32_Foundation", "Win32_Graphics_GdiPlus"]
```

This program produces the following output:

```none
thread 'main' panicked at src\main.rs:20:5:
assertion `left == right` failed
  left: Status(17)
 right: Status(0)
```

A GDI+ [`Status`](https://learn.microsoft.com/en-us/windows/win32/api/gdiplustypes/ne-gdiplustypes-status) code with value `17` translates to `UnsupportedGdiplusVersion`. This is as clear an error diagnostic as you'll ever see.

I *was* debating with myself whether the code gen should inhibit generation of the `Default` trait here, but I don't think there's anything to be gained: It'd be hard to implement and manage, and it would make writing correct code less convenient. For reference, here's how GDI+ initialization would look currently:

```rust
    let status = unsafe {
        GdiplusStartup(
            token.as_mut_ptr(),
            &GdiplusStartupInput {
                GdiplusVersion: 1,
                ..Default::default()
            },
            output.as_mut_ptr(),
        )
    };
```

I don't see much room for improvement here.
