### ISSUE TITLE
Can I continue to count on `CanInto` and friends?

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#2738]
### Suggestion

For [`ResGuard`](https://docs.rs/windows-helpers/latest/windows_helpers/struct.ResGuard.html#impl-ResGuard%3CR,+fn\(R\)%3E), I use items from the `windows` crate that have the attribute `#[doc(hidden)]`: trait `CanInto`, trait `TypeKind` and struct `CopyType`.

Even if they would be moved, renamed or restructured in a way that `ResGuard` can still make use of them (to generically ensure compatible handle types can be changed into other handle types), can I count on them staying available for me at all?

**Comment by kennykerr** [comment]
They're intentionally hidden as they're only meant for the generated bindings to use internally.
