### ISSUE TITLE
Improve diagnostics when encountering `TypeRef` in metadata

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#2742]
> Note that code gen from `TypeRef` is not a good idea as it implies the `TypeDef` is not available and thus you have no idea what kind of type you're actually generating code for. Usually this implies you're missing metadata. I should have better diagnostics for this in `riddle` soon.

`TypeRef` currently raises an `unimplemented!()` assuming this i something that _could_ be implemented at some point:

https://github.com/microsoft/windows-rs/blob/831b99b240505c8a6b02f1cd8fba5ecc0a32c351/crates/libs/bindgen/src/rust/writer.rs#L173

This is showing when generating (custom) metadata on (top of) `win32metadata` `main` (currently at https://github.com/microsoft/win32metadata/commit/3d65d3752a1a957de011a11c8b9f9745df2ad106):

```
     Running `target\debug\riddle.exe --etc crates/tools/windows/bindings.txt`
thread '<unnamed>' panicked at crates\libs\bindgen\src\rust\writer.rs:173:21:
not implemented: TypeRef(TypeName { namespace: "Windows.UI.Composition", name: "ICompositionTexture" })
```

This is caused by an upstream issue, where metadata is missing for a type that is used by other functions (https://github.com/microsoft/win32metadata/issues/1760). `riddle` needs to understand the type here, and for that the generator should emit a more descriptive diagnostic upon encountering `TypeRef`.

_Originally posted by @MarijnS95 in https://github.com/microsoft/windows-rs/pull/2539#discussion_r1423966610_

**Comment by kennykerr** [comment]
I'm working on some winmd validation. It will be some time before this is available, but its goal is to catch stuff like this.

**Comment by MarijnS95** [comment]
As it turns out the proper fix for https://github.com/microsoft/win32metadata/issues/1760 was simply that the new Win32 winmd I was generating was referencing newer types from the "API contracts" that windows-rs was using. Updating them here (https://github.com/microsoft/windows-rs/pull/2745) allows me to once again regenerate `windows-rs` from newer `Win32` `winmd`.

This means somewhere `TypeRef` gets replaced with `TypeDef` when multiple `winmd`s are loaded, maybe the diagnostics could build off of that process and report any unresolved `TypeRef`s (where required)?

**Comment by kennykerr** [comment]
Yes, I intentionally use TypeRefs in this case so that the panic message gives you a clue of what's missing.

**Comment by MarijnS95** [comment]
Clarifying that precedent in the panic message might be useful, then :)

**Comment by kennykerr** [comment]
#3099 added some further assistance in this regard. I'm not planning on doing anything else right now so I'll just close this old issue. Feel free to report any further pain points.
