### ISSUE TITLE
Please improve docs for `HSTRING::len()`

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#2748]
### Suggestion

Currently, [it says](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.HSTRING.html#method.len):

> `pub fn len(&self) -> usize`
> 
> Returns the length of the string.

Does this mean the number of wide chars (excluding the terminating null)? So, Unicode codepoints above U+FFFF are counted as two? When reading the docs, you should know exactly what's up.

**Comment by tim-weis** [comment]
Would you be fine with

> Returns the length (in code units) of the string.

?

**Comment by kennykerr** [comment]
The length is the number of UTF-16 characters, not including the terminating null character.

**Comment by ChrisDenton** [comment]
Rust's [`String::len`](https://doc.rust-lang.org/std/string/struct.String.html#method.len) is documented as so:

> Returns the length of this `String`, in bytes, not [`char`](https://doc.rust-lang.org/std/primitive.char.html)s or graphemes. In other words, it might not be what a human considers the length of the string.

Change "bytes" for "`u16`s" and it's pretty much the same.

**Comment by Enyium** [comment]
> The length is the number of UTF-16 characters

"characters" doesn't seem to be quite correct and not helpful when trying to understand more than the convention "We just think of all of these units as characters, so they're conveniently the same size."

> Would you be fine with
>
> > Returns the length (in code units) of the string.

Better.

> Rust's [`String::len`](https://doc.rust-lang.org/std/string/struct.String.html#method.len) is documented as so:
> 
> > Returns the length of this `String`, in bytes, not [`char`](https://doc.rust-lang.org/std/primitive.char.html)s or graphemes. In other words, it might not be what a human considers the length of the string.
> 
> Change "bytes" for "`u16`s" and it's pretty much the same.

The best approach.

Combined:

```
Returns the length of the string in `u16`s, i.e., UTF-16 code points, not `char`s or graphemes. It might not be what a human considers the length of the string.
```

**Comment by kennykerr** [comment]
Feel free to contribute something along those lines.

**Comment by kennykerr** [comment]
Agree with Tim. Here's a minor clarification: #2749
