### ISSUE TITLE
ErrorCode property is being ignored when awaiting the async WinRT types

### ISSUE THREAD

**Issue by FreddyDgh** [microsoft/windows-rs#2753]
### Summary

Occasionally, I have noticed some strange/unexpected error codes when calling await on async operations.  It is difficult to reproduce these transient errors, but it looks like this is probably because the implementation of the `Future` trait on the built-in async WinRT types tries to call `GetResults()`, even if the status is not `AsyncStatus::Completed`.  I could be wrong, but my understanding is that `GetResults()` and `ErrorCode` are not intended to be called unconditionally; they should only be called when the `Status` property indicates it's appropriate.

In the event that the status is `AsyncStatus::Error`, the `ErrorCode` property is supposed to have the relevant error code for the problem.  In many cases, that might be the same error code that `GetResults()` also produces, but it's not guaranteed.  I believe one scenario I've seen is where the implementation of `GetResults()` simply returns `HRESULT(0)` and null pointer for the data. My understanding is that the result of the async types is really trying to model something like the following, but in a way that does not require languages to support discriminated unions:
```rust
pub enum AsyncResultKind<T>
{
    Canceled,
    Completed(T),
    Error(HRESULT),
}
```

Because this applies to the `windows` crate, which makes things feel idiomatic to Rust, it could be worth changing the output type of the futures to an async-specific result type that can be properly handled with a match expression, which would be more intuitive for users of Rust. However, for my own scenario, I don't find it necessary to make that breaking change.  Instead I think the implementation of the `Future` trait could be changed to something more like this and it would work well enough:
```rust
fn poll(self: ::std::pin::Pin<&mut Self>, context: &mut ::std::task::Context) -> ::std::task::Poll<Self::Output> {
  match self.Status()?
  {
    AsyncStatus::Started =>
    {
      let waker = context.waker().clone();
      let _ = self.SetCompleted(&AsyncOperationWithProgressCompletedHandler::new(move |_sender, _args| {
	      waker.wake_by_ref();
	      Ok(())
      }));
      ::std::task::Poll::Pending
    },
    AsyncStatus::Completed => ::std::task::Poll::Ready(self.GetResults()),
    AsyncStatus::Canceled => ::std::task::Poll::Ready(Err(E_ABORT.into())),
    AsyncStatus::Error => ::std::task::Poll::Ready(Err(self.ErrorCode()?.into())),
    _ => ::std::task::Poll::Ready(Err(E_UNEXPECTED.into())),
  }
}
```
I am certainly not married to any one particular idea to solve this issue, I am just interested in finding a way for the errors from await calls to be easier to debug and easier to add proper error handling.

**Comment by kennykerr** [comment]
The `ErrorCode` property is just a relic of the WinRT async pattern but is not generally used since it requires an additional query to the `IAsyncInfo` interface and the result is guaranteed to be the same as that of calling `GetResults` on a non-started async object.

**Comment by FreddyDgh** [comment]
@kennykerr I swear that's not what I am seeing in practice.  Not sure how to prove it.  I suppose I'll have to try to take better note of the APIs in the future, but sometimes the failures are not easily able to be reproduced, either.  I seem to recall it happening with one of the PackageManager APIs (when I accidentally called the wrong API by mistake or something of that nature).

When you say that the results are guaranteed to be the same - would that just be for the Windows OS APIs?  Or would that guarantee also apply for a third-party WinRT component?

**Comment by FreddyDgh** [comment]
@kennykerr I am noticing that my original description of the issue doesn't explicitly mention the `AsyncStatus::Canceled` state not being handled by the default await implementation, either.  I apologize for that.  Is there any guarantee on what `GetResults()` returns in this case?  I think one segment of the problems I've had could be related to this - perhaps the status is actually `AsyncStatus::Canceled` and the call to `GetResults()` doesn't produce an error code that indicates it was cancelled.  I don't think that this covers everything I've seen, but certainly could be part of the frustration.

**Comment by kennykerr** [comment]
Async in general is unpredictable and cancellation more so since it is merely a suggestion and the async object may intentionally or unintentionally ignore the request. There is a very specific way that `IAsyncXxx` must be implemented and there are only a handful of valid implementations. The gold standard is the way that WRL and C++/WinRT implement it (identically). I implemented parts parts of the first all of the second, so if you're curious about how it works, I'd look at those implementations.

**Comment by FreddyDgh** [comment]
I am not writing any async implementation myself, but I am using this repo to generate bindings for other WinMD files.  Most of those do come from Microsoft, but if that's considered unsupported by this crate, I can understand. I will try to find something that's reproducible from the Windows API itself.

On the topic of cancellation, maybe I'm barking up the wrong tree, but I did look at other WinRT implementations already.  In particular:
https://github.com/microsoft/cppwinrt/blob/cb674723b42b830215156ccb032533c0e3092c28/strings/base_coroutine_foundation.h#L79C5-L85

Seems like C++/WinRT is going out of its way to throw a predictable hresult for consuming code to handle.  This feels like it is missing from Rust.  However, if your position is that you are only supporting certain gold standard implementations for async types, and if those implementations do return predicable hresults, then perhaps the extra precaution is not needed.

**Comment by kennykerr** [comment]
C++/WinRT and Rust for Windows implement async the same way. If you find a discrepancy, please let me know.

**Comment by FreddyDgh** [comment]
@kennykerr I realize that you think that I am an idiot and am wasting your time.  I do apologize.  However, I really do think there is a legitimate bug _somewhere_.  I'll admit, based on what you've said, it could be outside the scope of this repo.  But, considering that I will likely have to spend some significant time to track it down, could you please provide a clear, direct answer on one last thing: if I do find a reproducible bug in a Microsoft-produced WinRT component that ships *outside* the OS, what should I do?  It sounds like I should not bother reporting it here -- I should basically tell the team producing that component to ship a new version with a proper async implementation, is that correct?

**Comment by kennykerr** [comment]
Which API is it? I may be able to find the owner. If it ships out of band then it's very likely C++/WinRT. Either way, a simple repro in either C++ or Rust will help.

**Comment by FreddyDgh** [comment]
I am 99% sure that I have seen a 'bad' async implementation at some point from a Microsoft product, so perhaps that is causing me to incorrectly conflate separate issues.  My hunch would be that it was in WebView2.  If I can find a simple repro and it's still present with the latest version, I know they have a public repo that I can use for feedback.
