### ISSUE TITLE
Implementation of From/Into traits for windows::core::strings

### ISSUE THREAD

**Issue by SVilgelm** [microsoft/windows-rs#2762]
### Suggestion

Hello,

it would be great to implement the From/Into traits for all string types in `windows::core` crate.

Right now we need to implement own helpers, mostly to convert `&str` to `PCWSTR`, but it will be really helpful to simply use `"foo".into()` instead of `let foo = as_wide("foo"); bar(PCWSTR(foo.as_ptr())`

**Comment by tim-weis** [comment]
For compile-time string literals, you can use the [`w!`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/macro.w.html) macro. For run-time string slices, you'll typically want to use the [`HSTRING`](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.HSTRING.html) type that has `From` implementations for most standard string types. `&HSTRING` implicitly converts to a `PCWSTR`.

**Comment by datner** [comment]
I think this is quite proper to add to the example if not to the documentation.... If I wasted 3.5 hours trying to solve this, I wonder how many other devs have before me and will after. I shudder thinking of the financial price of this time sink
