### ISSUE TITLE
GetPackageSpecificToken returns 0x80010117

### ISSUE THREAD

**Issue by carl-wallace** [microsoft/windows-rs#2769]
### Summary

I am trying to generate an ASHWID using HardwareIdentification::GetPackageSpecificToken but it fails with 0x80010117 (Call context cannot be accessed after call completed). In the snip below I am passing None as the nonce (similar to usage in C# code I am porting) but have also tried with a nonce value. Both fail with the same error. What steps do I need to take to generate an ASHWID? This is on Version 22H2 Build 22621.2861.

### Crate manifest

```TOML
[package]
name = "ashwid_test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = {version = "0.52", features = ["System_Profile", "Storage_Streams"] }
```

### Crate code

```Rust
use windows::System::Profile::HardwareIdentification;
fn main() {
    let token = HardwareIdentification::GetPackageSpecificToken(None);
    print!("Token: {token:?}");
}
```

**Comment by kennykerr** [comment]
The docs say that the "returned ASHWID will be different for each application package." It's possible that it will only work in the context of a packaged application. Here's an example of how to set up such a process:

https://github.com/microsoft/windows-rs/tree/0.52.0/crates/samples/windows/core_app

**Comment by carl-wallace** [comment]
Thanks for the quick reply. That does indeed work, though I am not sure I am going to take that route.

**Comment by kennykerr** [comment]
@jonwis may know if there's a way to do it without requiring a packaged app.

**Comment by riverar** [comment]
Package identity is key to the ASHWID algorithm. If packaging the app is out, you can also build a package with external location (https://learn.microsoft.com/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps). It's effectively an empty package that you ship with your unpackaged app.

**Comment by carl-wallace** [comment]
That looks promising. Thanks for the additional info (and for all your work on this repo).

**Comment by jonwis** [comment]
You might also try https://learn.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification.getsystemidforuser?view=winrt-22621 - I'm not sure the difference between the two, but GetSystemIdForUser does not use the package identity and can be called by a console app.  For example (sorry for the C++/WinRT, I'm still learning Rust...)

```c++
#include "pch.h"
#include <winrt/Windows.System.Profile.h>
#include <winrt/Windows.Security.Cryptography.h>

using namespace winrt;
using namespace Windows::Foundation;
using namespace Windows::System::Profile;

hstring to_base64(const Windows::Storage::Streams::IBuffer& buffer)
{
    return Windows::Security::Cryptography::CryptographicBuffer::EncodeToBase64String(buffer);
}

int main()
{
    init_apartment();
    auto id = SystemIdentification::GetSystemIdForUser(nullptr);
    printf("System ID: %ls\n", to_base64(id.Id()).c_str());
    printf("Source: %d\n", id.Source());
}
```

Gets me an identifier from my TPM, nominally masked with ? in some places...

```
System ID: 9vq??????fJPxIZleO+Mm??????4lZ1h/OdNMv?????=
Source: 1
```

**Comment by carl-wallace** [comment]
I finally doubled back to this. The approach without packaging looks like it will work for me. Here's some Rust code similar to your above. Thanks again for your help.

```rust
use windows::System::Profile::SystemIdentification;

fn main() {
    match SystemIdentification::GetSystemIdForUser(None) {
        Ok(sys_id) => match sys_id.Id() {
            Ok(id) => {
                let id_b64 =
                    windows::Security::Cryptography::CryptographicBuffer::EncodeToBase64String(&id)
                        .unwrap();
                println!("User Base64: {id_b64}");
                let id_hex =
                    windows::Security::Cryptography::CryptographicBuffer::EncodeToHexString(&id)
                        .unwrap();
                println!("User Hex: {id_hex}");
            }
            Err(e) => println!("Id() failed with {e:?}"),
        },
        Err(e) => println!("GetSystemIdForUser() failed with {e:?}"),
    };
    match SystemIdentification::GetSystemIdForPublisher() {
        Ok(sys_id) => match sys_id.Id() {
            Ok(id) => {
                let id_b64 =
                    windows::Security::Cryptography::CryptographicBuffer::EncodeToBase64String(&id)
                        .unwrap();
                println!("Publisher Base64: {id_b64}");
                let id_hex =
                    windows::Security::Cryptography::CryptographicBuffer::EncodeToHexString(&id)
                        .unwrap();
                println!("Publisher Hex: {id_hex}");
            }
            Err(e) => println!("Id() failed with {e:?}"),
        },
        Err(e) => println!("GetSystemIdForPublisher() failed with {e:?}"),
    };
}
```

```toml
[package]
name = "sysid_test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = {version = "0.52", features = [
    "Security_Cryptography_Core",
    "Storage_Streams", "System_Profile",
    ] }
```

**Comment by kennykerr** [comment]
Here's a simple translation of the C++ example that @jonwis presented:

```rust
use windows::{core::*, Security::Cryptography::*, System::Profile::*};

fn main() -> Result<()> {
    let id = SystemIdentification::GetSystemIdForUser(None)?;
    let base64 = CryptographicBuffer::EncodeToBase64String(&id.Id()?)?;

    println!("System ID: {}", base64);
    println!("Source: {}", id.Source()?.0);

    Ok(())
}
```
