### ISSUE TITLE
Transform `[Out]` pointers to return 

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#2770]
### Suggestion

For https://github.com/Tsukisoft/direct-storage-rs/pull/1#discussion_r1434335817

DirectStorage has (for example) the following declaration:

```C#
unsafe void RetrieveErrorRecord([Out] DSTORAGE_ERROR_RECORD* record);
```

Since this is strictly an _`Out`_ pointer, and the type is known (and it should not be a pointer to an array of structures), I expect `bindgen` to turn this into `RetrieveErrorRecord(&self) -> DSTORAGE_ERROR_RECORD;` like some other functions (and locally allocate a `let result__ = MaybeUninit::uninit();`).

As shown in https://github.com/Tsukisoft/direct-storage-rs/pull/1#discussion_r1434242265 a function like https://learn.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandqueue-getdesc has the "same" calling convention in Rust (caller allocates the return type and passes a pointer to it), but is represented in the docs and Winmd to be returning this type ([probably the ABI based on the size of a return structure](https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170#return-values), to let the caller allocate it?): `D3D12_COMMAND_QUEUE_DESC GetDesc();`.

**Comment by riverar** [comment]
Related: https://github.com/microsoft/win32metadata/issues/636

**Comment by MarijnS95** [comment]
Specifically https://github.com/microsoft/win32metadata/issues/636#issuecomment-1280424506 looks like a more elaborate explanation of what I said above about `GetDesc()`.

**Comment by kennykerr** [comment]
See:

https://github.com/microsoft/windows-rs/blob/d214aac12dcbc696daec9b9a01cdd97ae7cba730/crates/libs/bindgen/src/metadata.rs#L140-L143

**Comment by kennykerr** [comment]
So yes, there are structs that are considered too large to return by value as that would be inefficient. Of course, this only applies to out parameters that are not explicitly `retval` parameters.

**Comment by MarijnS95** [comment]
What does "inefficient" mean here? Have you confirmed that Rust performs a full copy for _moved_ large values?

Otherwise closing this seems premature. I had thought of other reasons for pass-by-`mut`.

**Comment by riverar** [comment]
I suspect this is a reasonable optimization around the largest number of bits that can be stuffed into a single register (e.g. `xmm0`).

**Comment by kennykerr** [comment]
It's certainly subjective but again the only reason this code exists is that retval isn't applied uniformly. Prefer to focus on leveraging metadata and applying the attribute as needed. The remaining heuristics are necessarily conservative since they apply to a great deal of code. 

https://github.com/microsoft/windows-rs/blob/d214aac12dcbc696daec9b9a01cdd97ae7cba730/crates/libs/bindgen/src/metadata.rs#L121-L126

**Comment by MarijnS95** [comment]
Note that I'm not the expert on the topic at hand. It sounds like you're suggesting the possibility to annotate this out parameter with `[Retval]` to get the desired outcome - while maintaining ABI?

**Comment by kennykerr** [comment]
Yes, retval is just a suggestion for languages to transform trailing out parameters syntactically but doesn't affect the ABI.

**Comment by MarijnS95** [comment]
Thanks, yeah that gets it working!

https://github.com/Tsukisoft/direct-storage-rs/commit/6a7f8c5d7e8b744bcf6f744ae661f8018528b6bf
