### ISSUE TITLE
GetWindowLong/Ptr functions can fail, but don't return a Result

### ISSUE THREAD

**Issue by qwerty01** [microsoft/windows-rs#2773]
### Suggestion

If we look at the docs for [GetWindowLongPtrA](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlonga) (or any of the A/W Long/LongPtr variants), they all can fail by returning 0, however the generated bindings just return an `isize`: [GetWindowLongPtrA](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/fn.GetWindowLongPtrA.html).

The error handling might not be as simple as checking for 0 and returning a `Result` since a proper return type would be `Result<Option<isize>>`, where it returns `Ok(None)` when the function returns 0 without having an error (for example when `SetWindowLong` has not been called).

I've never actually seen it fail so I'm not entirely sure what the fail conditions vs succeed conditions on a 0 return look like (and the docs aren't very clear), but it would be nice to have the error helpers applied to these functions.

The returned value on the Ptr variants is also a pointer, but it's probably best to keep it as an `isize` since `GetWindowLongPtrA` and `GetWindowLongPtrW` return pseudo-values when the wrong A/W version is called.

**Comment by riverar** [comment]
A developer may also store/retrieve a `0` via `DWL_USER`, making this difficult to handle generically.

**Comment by kennykerr** [comment]
I think this is a case where the caller needs to figure things out since the way that errors are reported is very API specific and cannot be readily inferred through metadata.

**Comment by kennykerr** [comment]
These APIs are already somewhat specialized and problematic (#1932) so I'd rather just leave this as is.
