### ISSUE TITLE
Unclear how to use windows::Win32::Globalization::GetGeoInfoA

### ISSUE THREAD

**Issue by zinovya** [microsoft/windows-rs#2783]
### Summary

Hi there, I'm not sure if that is the right channel to ask a question, if not I would appreciate if you refer me to the right place. 
I'm trying to port some C code that is using WIN API to Rust as part of my rust learning journey. 
I'm trying to use `GetUserGeoID()` and `GetGeoInfoA()` methods. First one is pretty straight forward. The second I cannot understand how to use.
The [documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Globalization/fn.GetGeoInfoA.html#) says that this function has the following signature:
```
pub unsafe fn GetGeoInfoA(
    location: i32,
    geotype: SYSGEOTYPE,
    lpgeodata: Option<&mut [u8]>,
    langid: u16
) -> [i32]
```
`lpgeodata` is meant to be an [output parameter](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getgeoinfoa) but since it passed by value (not as borrowed reference) move occurs and ownership of the `lpgeodata` transferred to `GetGeoInfoA`, which means  `lpgeodata` cannot be used by the caller after `GetGeoInfoA` is called.
Should not `lpgeodata` be declared as something else, e.g. `&mut Option<&mut [u8]>` ? If not, could you please provide an example how `GetGeoInfoA` is meant to be used?

### Crate manifest

```TOML
[dependencies]
windows-sys = "0.52.0"

[dependencies.windows]
version = "0.52"
features = [
    "Win32_Globalization"
]
```

### Crate code

```Rust
fn main() {
    extern crate windows;
    use windows::Win32::Globalization;

    let geo_id = Globalization::GetUserGeoID(Globalization::GEOCLASS_NATION);

    let mut country_code: Option<&mut [u8]> = Default::default();
    let country_code_len = Globalization::GetGeoInfoA(geo_id,
                                                      Globalization::GEO_ISO3,
                                                      country_code,
                                                      0 );

    let cc = country_code.unwrap();
}
```

**Comment by kennykerr** [comment]
It's an optional parameter so that you can first query without a buffer and get the expected length and then call it again with the required buffer. Here's an example:

```rust
use windows::Win32::Globalization::*;

fn main() {
    unsafe {
        let geo_id = GetUserGeoID(GEOCLASS_NATION);

        let len = GetGeoInfoA(geo_id, GEO_ISO3, None, 0);

        let mut country_code = vec![0u8; len as usize];

        GetGeoInfoA(geo_id, GEO_ISO3, Some(&mut country_code), 0);

        let country_code = String::from_utf8_lossy(&country_code);

        println!("{country_code}");
    }
}
```

**Comment by zinovya** [comment]
@kennykerr thank you very much for clarification, I can see now how it works.
