### ISSUE TITLE
GetEnvironmentStrings returns P(W)STR, while FreeEnvironmentStrings expects PC(W)STR.

### ISSUE THREAD

**Issue by WinkelCode** [microsoft/windows-rs#2793]
### Summary

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Environment/fn.GetEnvironmentStrings.html
Returns PSTR
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Environment/fn.FreeEnvironmentStringsA.html
Wants PCSTR

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Environment/fn.GetEnvironmentStringsW.html
Returns PWSTR
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Environment/fn.FreeEnvironmentStringsW.html
Expects PCWSTR

I used the wide variant in a program, there simply taking the pointer from the PWSTR and wrapping it a PCWSTR type worked (or at least `FreeEnvironmentStringsW` didn't return an error).

Is this intended? In the Windows docs the functions return/take LPCH and LPWCH respectively.

**Edit:** Also, typing the value as a `P(C and/or W)STR` in the first place can be misleading, since methods like `.as_wide()` will terminate the string too early due to it being a collection of null terminated strings, which itself is terminated with two nulls.

**Comment by kennykerr** [comment]
The `as_wide` and `as_bytes` methods rely on `strlen` and `wcslen` respectively and are `unsafe` as the pointers are simply assumed to be valid null terminated strings. If you need to handle embedded null characters, you'll need to parse them yourself.

**Comment by WinkelCode** [comment]
> The `as_wide` and `as_bytes` methods rely on `strlen` and `wcslen` respectively and are `unsafe` as the pointers are simply assumed to be valid null terminated strings. If you need to handle embedded null characters, you'll need to parse them yourself.

That's how I've been handling it. I am just wondering why it is presented as a P(W)STR st all, especially given then inconsistency with FreeEnvironmentStrings, and mismatch with the documentation. Why does the crate not just present it as an LP(W)CH?

Although, as I'm writing this, I remember that `QueryDosDeviceW` does the same thing, but officially populates an LPWSTR, not LPWCH as with the EnvironmentStrings functions: https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-querydosdevicew

**Comment by kennykerr** [comment]
That's because `windows-bindgen` has to guess what is `const` since win32metadata doesn't do it reliably. In this case since they're input parameters, they're assumed to be `const`. If they were in/out they would not be `const`.
