### ISSUE TITLE
Separate crate for macros

### ISSUE THREAD

**Issue by RivenSkaye** [microsoft/windows-rs#2798]
### Suggestion

So I was digging around on MSDN to leverage Memory Mapped Files for a project I need them in - all is well and I've managed to get something working now which is great.
What _isn't_ as great is missing some of the utility macros. LOWORD and HIWORD being the first examples I encountered early on due to a fair few calls requiring split upper and lower 32 bit integers.
I already saw #921 and #2273 which state these macros have no place here, and that there is maybe a future for a macro crate there. I'd mostly like to formalize the request for them, along with opening discussion on how this would be best approached and implemented.

The first questions to come to mind are
1. Should it be part of an existing workspace, or a new one?
2. If it were added to an existing workspace as a separate crate, where would the maintenance burden lie?
3. If it has to be a new repo, would it have to be opened by a community member, or should it live within the microsoft org?

Based on the previous interactions surrounding the topic of Windows SDK macros, I'd assume the work would in large part be a community effort, something I'd even be willing to contribute to given the chance. But for this to be feasible, there would have to be a way for contributors to help work on this. Could someone from the SDK maintenance team start working on compiling a list of the macros that don't have manual implementations here? Worst case, we'd get an auto-generated list of macros for which the community would have to filter out the ones actually relevant in Rust code.

Assuming this idea gets some favor and a macros crate does get added over time, it might even be interesting to move (some) existing macros there that were only added in order to accommodate working with the win32 APIs - as a way to get the rest of the crate back to just the metadata described code.

**Comment by kennykerr** [comment]
I can probably find a home for this, but deciding on the list of macros is probably the biggest challenge. I'm not aware of any official list of popular macros. Another option would be to begin collecting that list and at least in some cases simply documenting Rust alternative code snippets on the repo or here: https://kennykerr.ca/rust-getting-started/where-are-the-macros.html

**Comment by RivenSkaye** [comment]
We could just start with a list of macros in general and start implementing them in order of asked here, then the easier ones, and see what the responses and requests are.

Adding snippets and samples to the getting started guide is a great idea, I'll make a modest start on the aforementioned `DWORD` macros in a PR. Would it be better to make new files for that, or is that specific file going to grow bigger for now?

**Comment by riverar** [comment]
Also consider that the majority of Win32 macros exist mainly to make working with C++ easier. It may not make sense to suck down an entire crate where a `(value >> 16 & 0xffff) as _` may do.

I'd be more inclined to back an effort that involves writing a cookbook/docs of common idiomatic replacements.

**Comment by ChrisDenton** [comment]
It needn't be an either/or situation. Starting with a cookbook sounds useful on its own. The popular recipes can later be spun out into a crate if there's sufficient need.

**Comment by RivenSkaye** [comment]
Oh I absolutely agree, hence ordering by requested ones first. Itcs also why I'm happy to make a start on this.

I assume these macros also handle some platform-specifics for developers that'd be nice regardless of the language. Situations like reading UTF-16 BE/LE, arch specific instructions, etc. would definitely be a thing to watch out for and regardless of how these utilitues are provided, it'd be best to include these subtleties as closely mirrored to the C++ macros as possible

**Comment by kennykerr** [comment]
Closing as there's no work for the `windows-rs` project at the moment, but feel free to keep the conversation going.

**Comment by RivenSkaye** [comment]
For anyone who came here through searching the web or a duplicate issue, the decision eventually landed on a [community-effort repository](https://github.com/RivenSkaye/windows-rs-ext) which is currently a blank slate.  
For anyone who would be willing to contribute to a crate for Rust implementations of these header-only definitions, I'd like to point you to the repo linked above. For now it's literally just `minwindef.h` and nothing else as I can't spend paid hours on this.

Anyone more experienced in setting up proper testing and automation pipelines in CI is more than welcome to just PR in the things needed there. I'll start expanding on weekends and evenings if I can find the time, but some extra hands would be much appreciated.

For the folks that expressed a prior interest, have a ping:
@ryancerium @bibhas2 @roblabla @Razordor @jminer @Samuel-B-D @vpopescu @CrendKing @valarauca @andy-westacott @Axel-Reactor
These are all the people actively involved with issues for the same core problems that I could find in this repository. If any of you have any snippets and handrolled implementations lying around for specific macros/header-only functions, I'd love to add them!
