### ISSUE TITLE
Requesting release to include win32metaddata

### ISSUE THREAD

**Issue by LeonarddeR** [microsoft/windows-rs#2811]
### Suggestion

Version [57.0.42](https://github.com/microsoft/win32metadata/releases/tag/v57.0.42-preview) of win32metadata contains [interfaces for SAPI](https://github.com/microsoft/win32metadata/pull/1738) that were missing in the past. I'd like to create a new Rust project based on these interfaces.

**Comment by ChrisDenton** [comment]
If https://github.com/microsoft/win32metadata/issues/1788 is going to find its way into metadata soon then I'd quite like that to be included too. But also I don't want to block a release on that.

**Comment by kennykerr** [comment]
I'm bringing in the latest metadata here #2812. Chris, are the changes you're looking for included?

**Comment by ChrisDenton** [comment]
Oh, I didn't realise that's now closed. I'll take a look...

**Comment by ChrisDenton** [comment]
Yep! That seems to address my issue. Never mind then 🙂

**Comment by kennykerr** [comment]
Sweet! Note that I'm not planning a crates release - #2812 is just for updating the metadata and resulting code gen. Let me know if and when a particular crate release is needed for a production dependency.

**Comment by mikebattista** [comment]
@ChrisDenton I just fixed https://github.com/microsoft/win32metadata/issues/1788 so it's not included in the latest published release.

**Comment by ChrisDenton** [comment]
Oh, hmm... yes you're right. It's in the generated metadata if you generate it manually. But not in the rust docs for #2812. Sorry for getting confused there.

**Comment by kennykerr** [comment]
Happy to suck in another update. Maybe check with @riverar and @ChrisDenton that we have everything we need for the next release.

**Comment by mikebattista** [comment]
I just pushed another update with https://github.com/microsoft/win32metadata/issues/1788.
