### ISSUE TITLE
`IShellFolder2::GetDefaultColumnState`: Type incompatibility between return value and flag enum

### ISSUE THREAD

**Issue by Fulgen301** [microsoft/windows-rs#2820]
### Summary

`IShellFolder2::GetDefaultColumnState` [has `SHCOLSTATEF`](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishellfolder2-getdefaultcolumnstate) as return output value, which is a typedef to `DWORD`. In Rust, this maps to `Result<u32>`. However, the value is supposed to be a combination of `SHCOLSTATE` enumeration flags, which have `i32` as underlying type - so in addition to missing `BitOr` support for `SHCOLSTATE`, code also has to cast the value to `i32`.

I'm opening the issue here because the metadata for both isn't wrong - the underlying type for `SHCOLSTATE` _is_ i32, not u32. However, having to write this does not make for a nice developer experience:

```rs
    fn GetDefaultColumnState(&self, icolumn: u32) -> Result<u32> {
        if icolumn > 0 {
            Err(E_INVALIDARG.into())
        } else {
            Ok((SHCOLSTATE_ONBYDEFAULT.0 | SHCOLSTATE_TYPE_STR.0) as _)
        }
    }
 ```

**Comment by Fulgen301** [comment]
...and tired me probably should have clicked on "Enhancement", apologies for that.

**Comment by riverar** [comment]
Filed a metadata bug to fix the association of that param w/ the enum. I left this issue here to continue the discussion about the developer UX around these warts.

**Comment by kennykerr** [comment]
The enum is also missing the flags attribute.

**Comment by kennykerr** [comment]
Beyond those metadata issues, any remaining friction is down to the enum association issues discussed in #2784 so there isn't much else to say here.
