### ISSUE TITLE
GetMonitorInfoW

### ISSUE THREAD

**Issue by mbwilding** [microsoft/windows-rs#2822]
### Summary

Hello,

It seems we have a GetMonitorInfoW call which uses the struct MONITORINFO, and that works fine.
Issue is we have a struct called MONITORINFOEXW, but no call that uses it, and I'd like to use it.

Am I missing something?

### Crate code

```Rust
unsafe extern "system" fn enumerate_monitors_callback(
        monitor: HMONITOR,
        _: HDC,
        _: *mut RECT,
        userdata: LPARAM,
    ) -> BOOL {
        let monitors = &mut *(userdata.0 as *mut Vec<MONITORINFO>);
        let mut monitor_info = MONITORINFO::default();
        monitor_info.cbSize = size_of::<MONITORINFO>() as u32;

        if GetMonitorInfoW(monitor, &mut monitor_info).as_bool() {
            monitors.push(monitor_info);
        }

        TRUE
    }
```

**Comment by Nerixyz** [comment]
[The documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfow) says:
> A pointer to a [MONITORINFO](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-monitorinfo) or [MONITORINFOEX](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-monitorinfoexa) structure that receives information about the specified display monitor.
> You must set the cbSize member of the structure to sizeof(MONITORINFO) or sizeof(MONITORINFOEX) before calling the GetMonitorInfo function. Doing so lets the function determine the type of structure you are passing to it.)

Thus, you can pass both. I'm unsure what the correct behavior (or rather declaration) would be. Maybe the metadata could provide an overload? This would still be unsafe, as you can set any `cbSize`. In the end, you'd cast the `*mut MONITORINFOEX` to a `*mut MONITORINFO` either way.

**Comment by kennykerr** [comment]
Yes, this API would require a cast. The original definition relies on inheritance but that is not supported in Rust, not does the metadata actually model it that way. As @Nerixyz pointed out, this is unsafe either way but you can simply set the size field and pass the address of the relevant struct.

**Comment by mbwilding** [comment]
`ptr::addr_of!(info) as *mut MONITORINFO`

Thanks guys, final piece was that.
