### ISSUE TITLE
ID3D11View::GetResource should not return Result<T> but just T?

### ISSUE THREAD

**Issue by Zerowalker** [microsoft/windows-rs#2823]
### Suggestion

Looking at the documentation: https://learn.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11view-getresource
From what I can gather I always returns the resource.
But the rust version expects that an error can occur (probably in the meta but couldn't find it)?

Is the documentation wrong and it can actually fail, or is it a miss?

**Comment by riverar** [comment]
I believe an error will occur if the resource is not bound to the pipeline. @damyanp may have more insight here.

**Comment by kennykerr** [comment]
The metadata describes the API as follows:

```C#
void GetResource([Out] ID3D11Resource* ppResource);
```

The implementation can return a null pointer even though the API does not return an error code. `Result` is used to allow for this possibility.

**Comment by damyanp** [comment]
I'm don't think you can create a view that doesn't have a resource.

In d3d11.h the API is:
```
ID3D11View : public ID3D11DeviceChild
    {
    public:
        virtual void STDMETHODCALLTYPE GetResource( 
            /* [annotation] */ 
            _Outptr_  ID3D11Resource **ppResource) = 0;
        
    };
```

IIRC, `_Outptr_` says that it should always expect to receive a value. Does win32metadata sometimes change `_Outptr_`s to `_Out_`?

**Comment by riverar** [comment]
Ah ok, we can probably get that patched up in metadata then. We don't have good coverage of SAL annotations at the moment.

Will transfer over there.

**Comment by kennykerr** [comment]
I'm doubtful the Windows metadata can broadly adopt the concept of a non-null pointer. https://github.com/microsoft/xlang/pull/708

Anyway, this is not specific to `windows-rs` so I'll go ahead and close this issue.
