### ISSUE TITLE
MSRPC support

### ISSUE THREAD

**Issue by zaddach** [microsoft/windows-rs#2835]
### Suggestion

Hi,

Is there currently any support for implementing Microsoft RPC clients and servers in Rust? My understanding is that there should be something, as the technology underpins COM, but I haven't found anything grepping through the `windows-rs` repo.

Ideally I'd like to generate client and server stubs from a description (`.idl` file or other) so that I can call from Rust into C++ or vice versa. I've been able to implement the direction 'Rust client' -> 'C++ Server' by generating a C client stub, writing a wrapper function for my RPC function that takes care of SEH, and then calling this from Rust. Though technically I could do the same for the server side, having the server stub call C functions isn't very ergonomic. I guess I could hack together a nicer interface with `NdrClientCall*` and `NdrServerCall*`, but I'd gladly reuse code to generate the parameter specification (format string) if there is any.

Thanks for any pointers and feedback!

Jonas

**Comment by kennykerr** [comment]
There is growing support for `.idl` files for COM and WinRT definitions but I have no plans for RPC directly.
