### ISSUE TITLE
Feature information was removed from the docs

### ISSUE THREAD

**Issue by rokbok** [microsoft/windows-rs#2873]
### Summary

The docs at https://microsoft.github.io/windows-docs-rs/doc/windows/ used to include information on which features are needed for each crate (e.g. requires "Win32_Graphics_Direct3D_Fxc"). It appears this information has been removed with today's update.

(I'd create an issue at the docs repo at https://github.com/microsoft/windows-docs-rs, but issues are disabled there)

**Comment by riverar** [comment]
Hey @rokbok, 

The generated documentation no longer explicitly includes feature information as it resulted in an enormous amount of redundant doc comments and markup. (See also #2717 #2830 #2864.)

Here's a link to the new feature search app that can pull up that information for you https://microsoft.github.io/windows-rs/features/#/0.53.0. Please feel free to share feedback on that, good or bad.

Closing for now as there's no work to be done here, but feel free to keep the discussion going.
