### ISSUE TITLE
Unable to get the correct process name by using Process32First/Process32Next function

### ISSUE THREAD

**Issue by LegendSaber** [microsoft/windows-rs#2879]
### Summary

When I use Process32First/Process32Next function to get all the PID and process name in my machine. I will get wrong output as below:

> PID=4252,name=svchost.exeexeator64.exe
> PID=4328,name=svchost.exeexeator64.exe
> PID=4436,name=vmware-authd.exetor64.exe
> PID=5608,name=AggregatorHost.exer64.exe
> PID=5712,name=svchost.exest.exer64.exe
> PID=5828,name=svchost.exest.exer64.exe
> PID=1560,name=svchost.exest.exer64.exe
> PID=6072,name=svchost.exest.exer64.exe
> PID=6560,name=svchost.exest.exer64.exe
> PID=6052,name=svchost.exest.exer64.exe
> PID=6900,name=NisSrv.exest.exer64.exe
> PID=7580,name=svchost.exest.exer64.exe
> PID=10256,name=svchost.exest.exer64.exe
> PID=10356,name=SearchIndexer.exer64.exe
> PID=11064,name=SecurityHealthService.exe
> PID=11156,name=svchost.exethService.exe
> PID=13160,name=svchost.exethService.exe

The issue is because Process32Next function will not initialize array PROCESSENTRY32->szExeFile[u8; 260] to 0 before writing a new process name.

The debug result of the issue is below:

The first process name is written into PROCESSENTRY32->szExeFile[u8; 260] after call Process32First. The process name need 16 bytes, so the szExeFile array has value from szExeFile[0] to index szExeFile[15]:
![2](https://github.com/microsoft/windows-rs/assets/59863701/3d51d6de-74fb-49a8-8ffd-31779cbe9996)
The second process name is written in to PROCESSENTRY32->szExeFile[u8; 260] after call Process32Next. The process name only need 6 bytes, so the szExeFile array is written from szExeFile[0] to szExeFile[5], and szExeFile[6] is 0. However, value from szExeFile[7] to szExeFile[15] is not 0 (They are the remainder of first process name).
![3](https://github.com/microsoft/windows-rs/assets/59863701/812c0dfd-7eed-4123-bb79-2dd5cfa585df)
The PROCESSENTRY32->szExeFile[u8; 260] array is using ASCII to represent a process name. And Process32First/Process32Next function write szExeFile array as below:
```cpp
void write_process_name(char szExeFile[], char newProName[]) {
	DWORD dwProNameLen = strlen(newProName);

	for (DWORD i = 0; i < dwProNameLen; i++) {
			szExeFile[i] = newProName[i];
	}
	szExeFile[dwProNameLen] = 0;
}
```
It does not initialize szExeFile array to zero. Althorught I think the code is not suitable, It will be correct when you use ASCII to represent a string. However, Rust use UTF-8 to representing a string(String and str). When use the below code to get process name, it will not consider PROCESSENTRY32->szExeFile[6] as the end of the string(as the above picture show), so you will be get the wrong result.
```rust
let name = String::from_utf8(pe32.szExeFile[..].to_vec()).unwrap_or_else(|e| {
                println!("String::from_utf8 Error: {}", e);
                process::exit(1);
            });

 println!("PID={},name={}", pe32.th32ProcessID, name);
```

If you want to be get the correct result, you need to use the below code to initialize the szExeFile array to 0 before you call Process32Next function:

```rust
for item in pe32.szExeFile.iter_mut() {
     *item = 0;
}
```

It's obvious that other functions with similar logic like Module32First/Module32Next will have the same issue. And, It will be easy to appear bug if other people to use those function to write code.

So, I suggest that do not call the function directly as below code, proper checks and initialization are necessary.

```rust
pub unsafe fn Process32Next<P0>(hsnapshot: P0, lppe: *mut PROCESSENTRY32) -> ::windows_core::Result<()>
where
    P0: ::windows_core::IntoParam<super::super::super::Foundation::HANDLE>,
{
    ::windows_targets::link!("kernel32.dll" "system" fn Process32Next(hsnapshot : super::super::super::Foundation:: HANDLE, lppe : *mut PROCESSENTRY32) -> super::super::super::Foundation:: BOO        L);
    // In the place, you should initialize lppe->szExeFile array to 0
    Process32Next(hsnapshot.into_param().abi(), lppe).ok()
}
```

### Crate manifest

```TOML
[dependencies.windows]
version = "*"
features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
]
```

### Crate code

```Rust
fn test_in_windows() {
    use windows::Win32::System::Diagnostics::ToolHelp::{CreateToolhelp32Snapshot, Process32First, Process32Next, PROCESSENTRY32, TH32CS_SNAPPROCESS};

    unsafe {
        let handle = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0).unwrap_or_else(|e| {
            println!("CreateToolhelp32Snapshot Error: {}", e);
            process::exit(1);
        });

        let mut pe32: PROCESSENTRY32 = PROCESSENTRY32::default();
        pe32.dwSize = size_of_val(&pe32) as u32;

        Process32First(handle, &mut pe32).unwrap_or_else(|e| {
            println!("Process32First Error: {}", e);
            process::exit(1);
        });

        loop {
            let name = String::from_utf8(pe32.szExeFile[..].to_vec()).unwrap_or_else(|e| {
                println!("String::from_utf8 Error: {}", e);
                process::exit(1);
            });

            println!("PID={},name={}", pe32.th32ProcessID, name);
            
            // for item in pe32.szExeFile.iter_mut() {
            //     *item = 0;
            // }

            if let Err(_) = Process32Next(handle, &mut pe32) {
                break;
            }
        }
    }
}
```

**Comment by riverar** [comment]
There doesn't appear to be any bug here. Your program owns the `PROCESSENTRY32` structure and is responsible for ensuring it's ready before calling `Process32Next`.

I don't think we want to do this at the crate level for a number of reasons, such as:
* The crate is automatically generated from metadata and there's no metadata to indicate which buffers should be zeroed before call
* Zeroing out the struct member automatically could be wasteful if the user already zeroed it out
* The caller may want to provide a `szExeFile` padded out with `0x20` (space) characters

I'll leave this open for others to chime in, just in case I'm missing something.

**Comment by LegendSaber** [comment]
> There doesn't appear to be any bug here. Your program owns the `PROCESSENTRY32` structure and is responsible for ensuring it's ready before calling `Process32Next`.
> 
> I don't think we want to do this at the crate level for a number of reasons, such as:
> 
> * The crate is automatically generated from metadata and there's no metadata to indicate which buffers should be zeroed before call
> * Zeroing out the struct member automatically could be wasteful if the user already zeroed it out
> * The caller may want to provide a `szExeFile` padded out with `0x20` (space) characters
> 
> I'll leave this open for others to chime in, just in case I'm missing something.

Well, as I have been mentioned above, the code to write process name to szExeFile array in Process32First/Process32Next as below is not suitable. It will be more correctly to initielize the szExeFile array to 0 before you write the process name to szExeFile array.

```cpp
void write_process_name(char szExeFile[], char newProName[]) {
	DWORD dwProNameLen = strlen(newProName);

	for (DWORD i = 0; i < dwProNameLen; i++) {
			szExeFile[i] = newProName[i];
	}
	szExeFile[dwProNameLen] = 0;
}
```

You say:

> Your program owns the `PROCESSENTRY32` structure and is responsible for ensuring it's ready before calling `Process32Next`

But the introduction of the [[PROCESSENTRY32 (tlhelp32.h) - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/api/tlhelp32/ns-tlhelp32-processentry32)](https://learn.microsoft.com/en-us/windows/win32/api/tlhelp32/ns-tlhelp32-processentry32) only let us to initialize **dwSize** :

> **dwSize**
> 
> Specifies the length, in bytes, of the structure. Before calling the Process32First function, set this member to 
> sizeof(PROCESSENTRY32). If you do not initialize **dwSize**, **Process32First** will fail

It does not tell us to initialize the szExeFile array, and you are not tell us that we should initialize the szExeFile array in the [[PROCESSENTRY32 in windows::Win32::System::Diagnostics::ToolHelp - Rust](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/ToolHelp/struct.PROCESSENTRY32.html)](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/Diagnostics/ToolHelp/struct.PROCESSENTRY32.html). It mean that read the document about those function does not enough to write correct code. we need to check the struct and the function to ensure our code correct, right? I do not think this is suitable.

**Comment by kennykerr** [comment]
Sounds like you have a concern with how this API works. You best bet is to try a forum such as this:

https://docs.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by LegendSaber** [comment]
> > [...] It mean that read the document about those function does not enough to write correct code. we need to check the struct and the function to ensure our code correct, right? I do not think this is suitable.
> 
> Agreed. I can get the docs edited. I'll send you a link when I do that so we can work together on the wording.

Sorry, I get someting wrong. When we call C FFI function, we need to use [std::ffi - Rust](https://doc.rust-lang.org/std/ffi/index.html) to convert the string. Thank you for your time.
