### ISSUE TITLE
``the trait bound `PWSTR: CanInto<PCWSTR>` is not satisfied``

### ISSUE THREAD

**Issue by wuweiran** [microsoft/windows-rs#2887]
### Summary

Windows APIs often expect PCWSTR parameters for read-only input.
By allowing PWSTR to be converted into PCWSTR, Rust code can seamlessly interact with Windows APIs without explicit conversions.

### Crate code

```Rust
let file_path = item.GetDisplayName(SIGDN_FILESYSPATH)?;
MessageBoxW(None, file_path, w!("File Path"), MB_OK);
```

**Comment by kennykerr** [comment]
Seems reasonable. I've added support for this here: #2899
