### ISSUE TITLE
Cannot get typeface name through `windows::Win32::Graphics::Gdi::GetTextFaceW`

### ISSUE THREAD

**Issue by wuweiran** [microsoft/windows-rs#2906]
### Summary

According to [https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-gettextfacew](GetTextFaceW function (wingdi.h)), `GetTextFaceW` should be able to #1 get typeface name or #2 return the size of the name. I think it's better to have it like: `GetTextFaceNameW -> Result<PCWSTR>`.

**Comment by kennykerr** [comment]
The `windows` and `windows-sys` crates are generated from metadata describing the signatures for these APIs. Higher-level wrappers would need to be written by hand. 

https://kennykerr.ca/rust-getting-started/how-are-crates-built.html
