### ISSUE TITLE
Feature search does not list required features for `IDXGIFactory2::CreateSwapChainForHwnd`

### ISSUE THREAD

**Issue by zopsicle** [microsoft/windows-rs#2913]
### Summary

For `IDXGIFactory2::CreateSwapChainForHwnd` to be available, the feature `Win32_Graphics_Dxgi_Common` must be enabled. Neither searching for `IDXGIFactory2` nor `CreateSwapChainForHwnd` on https://microsoft.github.io/windows-rs/features lists `Win32_Graphics_Dxgi_Common` as a required feature.

![Screenshot of search results for `IDXGIFactory2`](https://github.com/microsoft/windows-rs/assets/50083900/3e96de05-820b-420b-8e2e-4cee16b80b2a)

![Screenshot of search results for `CreateSwapChainForHwnd`](https://github.com/microsoft/windows-rs/assets/50083900/b2c689a9-cf12-427c-bcb1-b80b477062e3)

**Comment by riverar** [comment]
The `CreateSwapChainForHwnd` method is missing altogether, hmm.

**Comment by kennykerr** [comment]
I don't think the index currently includes methods at all. The feature requirements indicate what is required to define the particular type. Methods that refer to types in non-parent modules may have additional feature requirements.

**Comment by kennykerr** [comment]
I have no plans to expand the index to cover methods - unless @riverar is interested in this issue I'll probably just close it.

**Comment by riverar** [comment]
This is something we're actively and heavily investigating, so while this issue was closed, rest assured it's very top of mind and the TODO list. Thanks!
