### ISSUE TITLE
Implement `std::io` traits for `IStream`/`ISequentialStream`

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#2923]
### Suggestion

The `Read`/`Write`/`Seek` [traits](https://doc.rust-lang.org/std/io/index.html#traits) in `std::io` form a battle-tested<sup>\[*citation needed*\]</sup> abstraction over (de-)serializing implementations, that roughly map to these COM interfaces:

* [`IStream`](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-istream): `Read`/`Write`/`Seek`
* [`ISequentialStream`](https://learn.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-isequentialstream): `Read`/`Write`

It would be convenient to have those implemented (I can supply a draft PR for discussion if desired).

Ignoring the maintenance burden, the only issue I see is how to deal with the impedance mismatch between the representation of sizes/offsets: `std::io` chooses `[i|u]size` (i.e., pointer precision), whereas the COM interfaces are based on `[U]LARGE_INTEGER` (64-bit quantities).

This could be addressed

* at compile-time (via [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html)), or
* run time (via `Result<>` or `panic!()`)

**Comment by kennykerr** [comment]
Is this related to #1952?

**Comment by tim-weis** [comment]
> Is this related to #1952?

Both issues have the same goal, so yes, they are related. Thanks for digging that up!

A few differences:

* This issue is asking for `Read`/`Write`/`Seek` as opposed to just `Read`
* `IStream`/`ISequentialStream` have a synchronous interface with the WinRT types offering an async interface only

If you're still planning on providing those `std::io` traits I would expect that implementing them for the COM interfaces is easier.

**Comment by kennykerr** [comment]
Closing this old issue - doesn't seem to be much demand for such API support. Let me know if you have thoughts to the contrary. 😊
