### ISSUE TITLE
Need a sample on how to implement COM interfaces

### ISSUE THREAD

**Issue by wuweiran** [microsoft/windows-rs#2925]
### Suggestion

As you are undoubtedly aware, COM is a fundamental component of Windows. Given the growing interest in utilizing Rust for Windows development, I believe that providing guidance and examples on how to effectively implement COM interfaces in Rust would be immensely beneficial.

An example is `windows::Win32::UI::Animation::IUIAnimationTimerEventHandler`. It's hard to implement one instance of it without good knowledge of Rust language, underlying workings of COM objects, virtual table, etc.

**Comment by kennykerr** [comment]
https://kennykerr.ca/rust-getting-started/how-to-implement-com-interface.html
