### ISSUE TITLE
about COM HRESULT `is_ok()`

### ISSUE THREAD

**Issue by zhefenfei** [microsoft/windows-rs#2928]
### Summary

https://learn.microsoft.com/en-us/windows/win32/seccrypto/common-hresult-values

i see here HRESULT = 0x00000000 means S_OK  but in `windows` crate

impl HRESULT {
    /// Returns [`true`] if `self` is a success code.
    #[inline]
    pub const fn is_ok(self) -> bool {
        self.0 >= 0
    }
...

really?????? is a bug right?

**Comment by tim-weis** [comment]
This is not a bug. `HRESULT` values are partitioned into error and success codes, where the most significant bit signifies an error when set. This allows to encode success values other than just `S_OK` (e.g., `S_FALSE`).

`HRESULT::is_ok()` is a Rust implementation of the [`SUCCEEDED()`](https://learn.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-succeeded) macro.

**Comment by kennykerr** [comment]
And the name comes from the Rust Standard Library:

https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.is_ok

**Comment by zhefenfei** [comment]
> This is not a bug. `HRESULT` values are partitioned into error and success codes, where the most significant bit signifies an error when set. This allows to encode success values other than just `S_OK` (e.g., `S_FALSE`).
> 
> `HRESULT::is_ok()` is a Rust implementation of the [`SUCCEEDED()`](https://learn.microsoft.com/en-us/windows/win32/api/winerror/nf-winerror-succeeded) macro.

yea, i see ,so i closed it yesterday,i'm so sorry it's my fault,

i just encounter a 0x00000001 means false is not success,but `is_ok()` return true . so it cause my program some bug.

**Comment by zhefenfei** [comment]
> And the name comes from the Rust Standard Library:
> 
> https://doc.rust-lang.org/stable/std/result/enum.Result.html#method.is_ok

thx bro,i post twice not right infomation, i'm so sorry about that.i will check it be careful more then post.
