### ISSUE TITLE
Generate Link dll name with case matching winmd definition

### ISSUE THREAD

**Issue by youyuanwu** [microsoft/windows-rs#2932]
### Suggestion

Given the function in winmd definition:
```
[DllImport("FabricCommon", ExactSpelling = true, PreserveSig = false)]
public unsafe static extern HRESULT FabricDecryptText([In][Const] PWSTR encryptedText, [In] FABRIC_X509_STORE_LOCATION certStoreLocation, [Out][RetVal] IFabricStringResult* decryptedText);
```
windows-bindgen generates the following code for linking:
```rs
    #[link(name = "fabriccommon")]
    extern "system" {
        pub fn FabricDecryptText(
        ) -> ::windows_core::HRESULT;
    }
```
The link name has lower case "fabriccommon" not matching the case "FabricCommon". This request is to ask to make the name the same by default without changing the casing or add an option to configure this.
The desired code should look like this:
```rs
    #[link(name = "FabricCommon")]
    extern "system" {
        pub fn FabricDecryptText(
        ) -> ::windows_core::HRESULT;
    }
```

On windows there is this does not affect dll look up, but we (sf rust) use the same binding on linux, and the linker is case sensitive and cannot locate the lib. The current work around is to do a string replacement after code generation like this:

https://github.com/Azure/service-fabric-rs/blob/2fef8f1fe56135ddd3e6eea027ba59e34b0d7ad2/CMakeLists.txt#L43

**Comment by riverar** [comment]
I'd prefer we leave this as-is. This is continue being a problem regardless, due to the case-sensitive filesystem in use on a target we don't support.

Related: https://github.com/microsoft/win32metadata/issues/648

**Comment by riverar** [comment]
Perhaps a middle ground option here would be to add a bindgen configuration flag. Although it's not clear how useful that would be for service-fabric as it appears they [do their own gen](https://github.com/Azure/service-fabric-rs/blob/2fef8f1fe56135ddd3e6eea027ba59e34b0d7ad2/crates/tools/fabric-gen/src/gen.rs).

**Comment by kennykerr** [comment]
One option would be to preserve case when not targeting Windows. Something like #2934 but as @riverar points out I'm unclear what that project is doing with code gen so I'm not sure whether that will suffice. Are you moving away from your own code gen? Is that what this issue is about?

**Comment by youyuanwu** [comment]
The custom code gen is irrelevant for this issue. It is auto generating some experimental bindings on top of the windows-bindgen produced code.
Looks like the merged PR above can resolve this issue. I will try once it is released.

**Comment by kennykerr** [comment]
Feel free to take it for a spin by pointing your Cargo dependency to the git repo. 

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
