### ISSUE TITLE
Add GetCurrentProcessToken 

### ISSUE THREAD

**Issue by l420y** [microsoft/windows-rs#2935]
### Suggestion

The original winapi has a method for getting the process token `.GetCurrentProcessToken()`
But in this api for rust, I have to do something like: 
```Rust
let current_process_handle: HANDLE = unsafe { GetCurrentProcess() };
    let token_handle: *mut HANDLE = ptr::null_mut();
    unsafe {
     OpenProcessToken(current_process_handle, TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY, token_handle).unwrap()
      }
 ```
 And also `.GetCurrentProcess()` from the example above always return invalid handle, -1 value. So I can't get current process token. (I know about `.GetCurrentProcessHandle()`)
#
 **My suggestion is to implement `.GetCurrentProcessToken()` in this api, if it doesn't already exist and I'm just dumb**

**Comment by ChrisDenton** [comment]
`GetCurrentProcessToken` isn't a function exported by Windows DLLs. It's just an inline function that always returns `-4`. From the C headers:

```c
HANDLE GetCurrentProcessToken() {
    return (HANDLE)(LONG_PTR) -4;
}
```

**Comment by l420y** [comment]
Sorry, I made a mistake and it looks like this function is not needed, but `GetCurrentProcess` is a similar function that always returns (HANDLE)-1, so...
