### ISSUE TITLE
call `FSCTL_GET_VOLUME_BITMAP`   Incorrect buffer length  

### ISSUE THREAD

**Issue by zhuxiujia** [microsoft/windows-rs#2943]
### Summary

Because rust cannot arrange member variables in order like CPP malloc, it cannot achieve

```c++
auto bitmap = (VOLUME_BITMAP_BUFFER*)malloc(bitmapSize);
```

```rust
pub struct VOLUME_BITMAP_BUFFER{
   pub StartingLcn: i64,
   pub BitmapSize:i64,
   pub Buffer:  [u8; 1],
}

//can't malloc bitmapSize
```

What should I do to obtain the bitmap structure data of the volume use  `DeviceIoControl `and `FSCTL_GET_VOLUME_BITMAP` ???

**Comment by kennykerr** [comment]
This appears to be a general programming question for which this is usually a more appropriate forum:

https://stackoverflow.com/questions/tagged/windows-rs
