### ISSUE TITLE
GetInterfaceDnsSettings only accepts *mut DNS_INTERFACE_SETTINGS

### ISSUE THREAD

**Issue by sean-sqrx** [microsoft/windows-rs#2944]
### Summary

I am trying to get the `ServerProperties` member from a `DNS_INTERFACE_SETTINGS3` struct.

The documentation states to use `GetInterfaceDnsSettings`, and under the `Settings` parameter, it explicitly states that if the `Version` member is 3, the underlying struct should be `DNS_INTERFACE_SETTINGS3`.

If I do a manual type cast, there is no compile error, but the `cServerProperties` member is 0 for my WiFi network adapter even though I have configured DNS over HTTPS (Windows 11 machine).

Any help is greatly appreciated. Thank you.

[GetInterfaceDnsSettings docs](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-getinterfacednssettings)

### Crate manifest

```TOML
[dependencies]
windows = { version = "0.54.0", features = [
    "Devices_WiFi", 
    "Foundation_Collections", 
    "Win32_NetworkManagement_WiFi", 
    "Win32_Security_Cryptography", 
    "Win32_System_Memory", 
    "Win32_NetworkManagement_IpHelper", 
    "Win32_Networking_WinSock", 
    "Win32_System_Com", 
    "Win32_NetworkManagement_WindowsFirewall",
    "Win32_Networking_NetworkListManager",
    "Win32_System_Com_StructuredStorage",
    "Networking_Connectivity",
    "Win32_NetworkManagement_Ndis"
    ] }
```

### Crate code

```Rust
// My GUID is valid and retrieved from GetAdaptersAddresses (and converting the LUID to GUID).

let mut dns_interface_settings: DNS_INTERFACE_SETTINGS3 = Default::default();
dns_interface_settings.Version = DNS_INTERFACE_SETTINGS_VERSION3;

// This has an error: expected raw pointer `*mut DNS_INTERFACE_SETTINGS` found raw pointer `*mut DNS_INTERFACE_SETTINGS3`

let dns_setting_result = GetInterfaceDnsSettings(guid, &mut dns_interface_settings as *mut DNS_INTERFACE_SETTINGS3);

// Or am I meant to do manual type cast?

let dns_setting_result = GetInterfaceDnsSettings(guid, &mut dns_interface_settings as *mut _ as *mut DNS_INTERFACE_SETTINGS);
```

**Comment by kennykerr** [comment]
I'm not familiar with this API but I suspect something like this should work:

```rust
use windows::{core::*, Win32::NetworkManagement::IpHelper::*};

fn main() -> Result<()> {
    let mut settings = DNS_INTERFACE_SETTINGS3 {
        Version: DNS_INTERFACE_SETTINGS_VERSION3,
        ..Default::default()
    };

    unsafe { GetInterfaceDnsSettings(GUID::zeroed(), &mut settings as *mut _ as _).ok()? };
    dbg!(settings);
    Ok(())
}
```

**Comment by sean-sqrx** [comment]
Thanks @kennykerr for the assistance, but it turns out I was setting the DNS over HTTPS setting for a specific network instead of a network adapter in the Windows 11 settings. After correctly configuring it on a network adapter, I am able to retrieve it.
