### ISSUE TITLE
should `windows::Storage::StorageFolder` implement `IntoParam<IStorageFolder>` ?

### ISSUE THREAD

**Issue by ldosen** [microsoft/windows-rs#2946]
### Summary

[This C++ sample](https://github.com/microsoft/Windows-classic-samples/blob/a47da3d4551b74bb8cc1f4c7447445ac594afb44/Samples/CloudMirror/CloudMirror/CloudProviderRegistrar.cpp#L35), illustrates how to set the path field for the StorageProviderSyncRootInfo struct. 

However, trying to set the path field similarly to the sample will fail to compile in Rust due to a trait bound error.

```
error[E0277]: the trait bound `StorageFolder: IntoParam<IStorageFolder, ReferenceType>` is not satisfied
    --> src\root.rs:38:13
     |
37   |           info.SetPath(
     |                ------- required by a bound introduced by this call
38   | /             StorageFolder::GetFolderFromPathAsync(&HSTRING::from(&self.path)
39   | |             )?
40   | |                 .get()?
     | |_______________________^ the trait `IntoParam<IStorageFolder, ReferenceType>` is not implemented for `StorageFolder`
     |
     note: required by a bound in `StorageProviderSyncRootInfo::SetPath`
    --> C:\Users\[user_name]\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-0.54.0\src\Windows\Storage\Provider\mod.rs:1438:13
     |
1436 |     pub fn SetPath<P0>(&self, value: P0) -> ::windows_core::Result<()>
     |            ------- required by a bound in this associated function
1437 |     where
1438 |         P0: ::windows_core::IntoParam<super::IStorageFolder>,
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `StorageProviderSyncRootInfo::SetPath`
```

It seems like this method of setting the sync root path worked in an [older version of this crate](https://github.com/ok-nick/wincs/blob/416d00bb44b356f1fdd0b7a1fe8b822602eed927/src/root/register.rs#L161), though for what it's worth, I have not tried to compile this project.

Any help is appreciated, thanks.

**Comment by riverar** [comment]
The error here is admittedly a bit non-intuitive, but you're probably missing feature `Storage_Search` in `Cargo.toml`. This will bring in the additional implementation of IStorageFolder needed here.

https://github.com/microsoft/windows-rs/blob/4e14f1a744e5d4c0817372e1f3c14cd15ffc26d8/crates/libs/windows/src/Windows/Storage/mod.rs#L3354-L3360

**Comment by kennykerr** [comment]
This is regrettable as the `cfg` here applies to the entire required hierarchy when there's only one required interface that is not from the current namespace.

**Comment by ldosen** [comment]
@riverar 
that did the trick, thanks!

**Comment by riverar** [comment]
I'd like to also add, you shouldn't need to use anything in `Windows.Storage`. Those APIs tend to be brokered and/or have all sorts of gotchas in non "UWP" scenarios. If you can share a bit more about what you're trying to do, we can probably point you to an equivalent Win32 API.

**Comment by kennykerr** [comment]
Also https://jonwis.github.io/notes/winrt-design/system_interfaces.html

**Comment by kennykerr** [comment]
@jonwis may have some ideas.

**Comment by jonwis** [comment]
The `StorageProviderSyncRootManager` interface only thinks in `StorageFile` today.  Consider having your code think in Win32 APIs and paths as much as you care to, then use `StorageFolder.GetFolderFromPathAsync` to convert to the currency the API needs as the last step. Looks like you're already using that, which is as good as it gets.
