### ISSUE TITLE
Published Docs are Out of Date

### ISSUE THREAD

**Issue by Mythra** [microsoft/windows-rs#2949]
### Summary

Hi! I was looking at using this crate, and while trying to browse the documentation published at: <https://microsoft.github.io/windows-docs-rs/> I noticed it was for version 0.53.0, while the latest versions are now 0.54.0 (at least on crates,io), and have been published for a bit.

I specifically got tripped up due to the result change that made it's way into 0.54.0: <https://github.com/microsoft/windows-rs/pull/2890> tripping me up where the docs did not correspond to the actual values.

**Comment by riverar** [comment]
I'll get the docs regenerated. We handle this manually because rustdoc needs ~20GB of memory to complete the operation.

**Comment by Mythra** [comment]
Ah how fun! Thanks for getting the process kicked off 😄

**Comment by riverar** [comment]
Done, https://microsoft.github.io/windows-docs-rs/doc/windows/.
