### ISSUE TITLE
Add Support For Documented Macros as Part of the Windows API

### ISSUE THREAD

**Issue by tmheath** [microsoft/windows-rs#2952]
### Suggestion

Macros such as GetNextWindow declared in user32.h for use by programmers for MS Windows are unimplemented and a useful part of the API.  Is it feasible to autogenerate these from the API JSON?

**Comment by kennykerr** [comment]
https://kennykerr.ca/rust-getting-started/where-are-the-macros.html

**Comment by riverar** [comment]
In this case, it's a particularly silly one:

```
#define GetNextWindow(hWnd, wCmd) GetWindow(hWnd, wCmd)
```

**Comment by kennykerr** [comment]
And `GetWindow` is available. 👍

**Comment by tmheath** [comment]
Thank you for the fast responses, I had been asking about all the documented user macros because I saw in the documentation for this project that they aren't being included but they are a part of the documented API from MSDN.  GetWindow turned out not to be what I needed, and I've run into a couple more macros, trying EnumWindows right now but having trouble collecting values using the callback.  This might just be straight up the wrong place to ask tbh

**Comment by kennykerr** [comment]
For API questions please consider https://stackoverflow.com/questions/tagged/windows-rs
