### ISSUE TITLE
Properly provide MessageBoxResult from Win32 as an enumeration instead of an integer.

### ISSUE THREAD

**Issue by tmheath** [microsoft/windows-rs#2954]
### Suggestion

Currently to use a MessageBoxResult you need to directly use the integer (by looking up on MSDN or otherwise the values).
This type properly is an enumeration and (I think) only used as such.
**Current:**

```
    unsafe {

        let user_result = MessageBoxA(HWND_DESKTOP, "", "", MB_YESNO);

        // If and only if the user hit Yes (Closing the window or hitting No are equivalent).

        return user_result.0 == 6;

    }

```

**Proposed:**

```

    unsafe {

        let user_result = MessageBoxA(HWND_DESKTOP, "", "", MB_YESNO);

        // If and only if the user hit Yes (Closing the window or hitting No are equivalent).

        return match MessageBoxA(HWND_DESKTOP, "", "", MB_YESNO) {

            MB_Result::Yes => true,

            _ => false

        }

````
[Docs](https://learn.microsoft.com/en-us/dotnet/api/system.windows.messageboxresult?view=windowsdesktop-8.0)

**Comment by kennykerr** [comment]
You are looking at the docs for .NET which is unrelated to this crate or the Windows API. `MessageBoxA` is documented here:

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxa

Following the correct docs, you can for example use it as follows in Rust:

```rust
match MessageBoxA(None, s!("Hello"), s!("World"), MB_YESNO) {
    IDYES => panic!("IDYES"),
    other => panic!("{:?}", other),
};
```

**Comment by tmheath** [comment]
Thank you very much...

I see that now, should have been obvious, I've got too many tabs open
Didn't think about looking for literals to compare with either
