### ISSUE TITLE
Are there any examples showing a WinUI application developed using windows-rs?

### ISSUE THREAD

**Issue by tmheath** [microsoft/windows-rs#2971]
### Suggestion

Proceeding from finding this [comment](https://github.com/microsoft/microsoft-ui-xaml/issues/2488#issuecomment-662682179) I looked for an examples directory but didn't see it, is there one?  Background: Trying to get a gui running because it looks like the captureobjectpicker requires a WinUI root window that I haven't seen how to create and not a win32 window to hook it's events into.  I did post an actual question to the Microsoft link from the issues tab for a separate issue which does belong in the Microsoft Q&A but that site is a bit broken.

**Comment by ChrisDenton** [comment]
I think WinUI3 is very much limited to C# in practice (if not in theory)? Maybe it would be easier to create a thin C# UI wrapper that then invokes rust functions?

**Comment by tmheath** [comment]
It doesn't absolutely have to be WinUI3, I just need that new style root window object addressable from the rust code so that I can spot the picker dialog, I saw a single reference of a guy saying he got it running with rust in some comments just a bit ago but the specifics aren't important.  It very well might be easier, I don't have the experience with the interrop there.  Thanks for the response.

**Comment by riverar** [comment]
We went down this road with https://github.com/microsoft/windows-app-rs. To quote from that:

> The windows-app project was an experimental crate letting you call APIs from the Windows App SDK based on the technology from the windows crate. The Windows App SDK is however largely a vehicle for delivering out-of-band releases of Xaml, which is itself designed squarely for C# developers. While every effort has been made to support Rust, the Windows App SDK in its current form is too heavily tied to .NET and Visual Studio to be practically usable with other languages and toolchains. We hope this will change in future but for now this project has been archived.

**Comment by tmheath** [comment]
Thank you for the answer @riverar, are win32 guis the only supported via rust at the moment (assuming they are then for what I'm doing I'm going to see if I can hook into a win32 processing loop for what's needed or as @ChrisDenton mentioned, run C# also)?

**Comment by riverar** [comment]
> It doesn't absolutely have to be WinUI3, I just need that new style root window object addressable from the rust code so that I can spot the picker dialog, [...]

You probably don't need that file picker dialog to begin with. Check out [`GetOpenFileName`](https://learn.microsoft.com/windows/win32/api/commdlg/nf-commdlg-getopenfilenamew), [`SHBrowseForFolder`](https://learn.microsoft.com/windows/win32/api/shlobj_core/nf-shlobj_core-shbrowseforfolderw), or [`CLSID_FileOpenDialog`](https://learn.microsoft.com/windows/win32/learnwin32/example--the-open-dialog-box) for alternatives.

**Comment by riverar** [comment]
@robmikh has a great crate demonstrating usage of Windows.Graphics.Capture (https://github.com/robmikh/screenshot-rs). I suspect this will help!

**Comment by tmheath** [comment]
@riverar 
Thank you very much for that, I already have the window HWNDs so this is completely perfect, just need to find the calls used in there.

For future reference if it's unclear, the answer was that the modern Windows GUI at the time of writing (xaml via WinUI3) only supports C# (I have used it with F# but besides the point).

**Comment by riverar** [comment]
@tmheath Can you also mark the answer I provided on Q&A to close this all out? Thanks!

**Comment by robmikh** [comment]
I'd also like to point out that many WinRT pickers that assume a CoreWindow can be used by QIing for IInitializeWithWindow and providing an HWND before showing the picker. This includes the GraphicsCapturePicker.

**Comment by tmheath** [comment]
> @tmheath Can you also mark the answer I provided on Q&A to close this all out? Thanks!

The microsoft Q&A site?
The question I know I left does not show any answers to me, but I know there was a problem where I had to create twice because the first left me at a 404 page, did you answer the first and I just don't see it or is it not even that one you're talking about?

Will do soon as I see, also thanks


@robmikh, That's really nice for reference somewhere
