### ISSUE TITLE
Expose Interface::IID

### ISSUE THREAD

**Issue by roblabla** [microsoft/windows-rs#2981]
### Suggestion

Currently, Interface::IID is `#[doc(hidden)]`, and the interface IIDs aren't available anywhere else. This makes it impossible to, for instance, check if a riid matches`IClassFactory::IID` in a `DllGetClassObject`.

It'd be nice if `Interface::IID` was exposed so we could write code like `if riid == IClassFactory::IID { /* do things */ }`

**Comment by kennykerr** [comment]
Agreed, this should not be hidden.
