### ISSUE TITLE
Cannot be able to run  this example shown to get window titles 

### ISSUE THREAD

**Issue by yashwanth2804** [microsoft/windows-rs#2985]
### Summary

https://github.com/microsoft/windows-rs/blob/bedd359eac9a58b39faa06d7da1a4f48c0ca7303/crates/samples/windows-sys/enum_windows/src/main.rs#L5

![image](https://github.com/microsoft/windows-rs/assets/8038593/94d21d19-5504-42d9-ab14-d2b36720c4e8)

**Comment by yashwanth2804** [comment]
```
unsafe extern "system" fn enum_windows_proc(window: HWND, _: LPARAM) -> BOOL {
    let mut title = [0u16; 256];
    let len = GetWindowTextW(window, &mut title);
    if len > 0 {
        let title = String::from_utf16_lossy(&title[..len as usize]);
        println!("Window title: {}", title);
    }
    true.into()
}



unsafe {
        let _ = EnumWindows(Some(enum_windows_proc), LPARAM(0));
    }
```


This code is working fine for me

**Comment by kennykerr** [comment]
The sample you refer to depends on the `windows-sys` crate, as the associated `Cargo.toml` file indicates, but you seem to be trying to compile it with the `windows` crate. There are distinct samples for the `windows` and `windows-sys` crates here:

https://github.com/microsoft/windows-rs/tree/master/crates/samples

**Comment by yashwanth2804** [comment]
ok thank you

**Comment by yashwanth2804** [comment]
Sorry for the issue, im new to the rust ecosys , i am trying to learn different things getting confused
