### ISSUE TITLE
Actionable Toast Notifications

### ISSUE THREAD

**Issue by alshival** [microsoft/windows-rs#2993]
### Suggestion

First of all, thanks to everyone putting in work into this project. 

Though there are many packages out there for displaying windows toast notifications, creating toast notifications that are actionable is quite difficult. This is easier to do in Python using packages like windows-toasts than it is to do in Rust. I understand that you have to build a protocol and handlers to get this done, but it shouldn't take so much work to open a URL when a user clicks on a toast.

Even that. Just open a url in the browser. This is what I have in mind:

```
toast
    .title("Example Toast")
    .body("This is a toast.")
    .on_click({
            webbrowser::open(url);
            println!("I opened a url. Yay!");
    })
    .show()
```

It's really hard to do something like that, and if it is easy, I would like to know. Because, yes, I could set up handlers and things, but then you run into issues with requiring admin for changing registries and so forth. I just want to open a url when I click a toast.

**Comment by riverar** [comment]
> Though there are many packages out there for displaying windows toast notifications, creating toast notifications that are actionable is quite difficult [...]

Agree. It's also difficult for Windows developers using C++/C# and is something the Windows App SDK team is trying to resolve (https://github.com/microsoft/WindowsAppSDK/blob/main/specs/AppNotifications/AppNotifications-spec.md) for that audience.

I'm not sure this is something the low-level _windows_ crate can/should provide. Instead, this is probably better served by a new crate built on top of the _windows_ crate.

**Comment by kennykerr** [comment]
Yes, this seems appropriate for a possible `windows-notifications` crate.

**Comment by riverar** [comment]
Closing for now as this is out of scope for the `windows` crate, but we'll definitely put it into `crate-ideas.txt`. Some general guidance can be found in the docs https://learn.microsoft.com/windows/apps/design/shell/tiles-and-notifications/toast-desktop-apps; I'll warn you upfront though, you're not going to like it.
