### ISSUE TITLE
PCWSTR has undocumented undefined behavior on non-windows targets

### ISSUE THREAD

**Issue by tyilo** [microsoft/windows-rs#2996]
### Summary

When using `PWCSTR` and `PWSTR` on non-windows targets, `wcslen` is incorrectly used to determine the length of a null-terminated string.

The `as_wide` implementations needs to be fixed in one of the following ways:
- It could be disabled on non-windows targets
- It could instantly panic on non-windows targets
- It could be fixed to correctly count the non-zero `u16` characters on non-windows targets

### Crate manifest

```TOML
[package]
name = "windows-test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-core = "0.56.0"
```

### Crate code

```Rust
use windows_core::PCWSTR;

fn main() {
    let arr = [b'a' as u16, b'b' as u16, 0, 0];
    let s = PCWSTR::from_raw(&arr as *const u16);
    let slice = unsafe { s.as_wide() };
    // Should output [97, 98]
    // Outputs [97] on Linux
    println!("{:?}", slice);

    let arr = [b'a' as u16, 0];
    let s = PCWSTR::from_raw(&arr as *const u16);
    let slice = unsafe { s.as_wide() };
    // Should output [97]
    // UB on Linux
    println!("{:?}", slice);
}
```

**Comment by kennykerr** [comment]
I can probably disable everything on non-Windows targets, but may I ask why you're "using PWCSTR and PWSTR on non-windows targets"?

**Comment by tyilo** [comment]
> I can probably disable everything on non-Windows targets, but may I ask why you're "using PWCSTR and PWSTR on non-windows targets"?

I'm developing on Linux, so being able to run my tests on Linux would be nice. As my code compiled using a linux target, I assumed the code would also work.

I was only testing some part of the code using windows types, but no win32 API calls.

**Comment by kennykerr** [comment]
Got it, well there are a handful of other functions in `windows-core` that are excluded from non-Windows builds, for testing purposes as well, so I can just add this.

**Comment by kennykerr** [comment]
Actually, this has a bit of a ripple effect. 

Is this also a problem if you use a Windows target as in `--target x86_64-pc-windows-gnu`?

**Comment by kennykerr** [comment]
The `windows-sys` crate provides raw bindings so if you just need the definitions of various Windows types with no run time behavior then that may be more appropriate. 

https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html

**Comment by kennykerr** [comment]
Closing as this appears to be out of scope for windows-rs but feel free to keep the conversation going.
