### ISSUE TITLE
Could  windows_registry::Key expose a raw_handle() API to allow Registry change event using RegNotifyChangeKeyValue

### ISSUE THREAD

**Issue by shanyp** [microsoft/windows-rs#2999]
### Summary

Hi
I would like to be able to get notified on Registry key changes, using RegNotifyChangeKeyValue , but it requires the HKEY and while the widnows-registry::Key doesn't expose its inner HKEY

**Comment by Cinimajig** [comment]
As temp workaround, you could `transmute` it and then use it. This code works for me:
```rust
let key = windows_registry::CURRENT_USER.create(r#"SOFTWARE\windows-rs"#)?;
        
// Transforms the value to HKEY.
let hkey = std::mem::transmute::<_, HKEY>(key);

// Dereference it, to use with Reg-functions.
RegNotifyChangeKeyValue(
    hkey,
    true,
    REG_NOTIFY_CHANGE_NAME | REG_NOTIFY_CHANGE_ATTRIBUTES,
    None,
    false
).ok()?;

// Manually close the key, since the original is out of scope.
RegCloseKey(hkey).ok()?;
```
But yeah, it would be nice to be able to get the underlying HKEY or just a way to use directly, instead of transmuting back and forth.

**Comment by kennykerr** [comment]
I can add a `pub fn as_raw(&self) -> isize` method that would return the raw key value. I have `as_raw` methods on other wrappers in windows-rs and they work well.

**Comment by shanyp** [comment]
@kennykerr sounds perfect !

**Comment by kennykerr** [comment]
Here you go: #3003
