### ISSUE TITLE
`IDWriteTextRenderer::DrawGlyphRun` takes `&self` and `*const c_void`. No pointer to mutable state present.

### ISSUE THREAD

**Issue by david7a68** [microsoft/windows-rs#3002]
### Summary

When implementing `IDWriteTextRenderer`, it makes sense that one would need mutable state _somewhere_, if only to record glyphs. However, the function signature for [IDWriteTextRenderer::DrawGlyphRun](https://learn.microsoft.com/en-us/windows/win32/api/dwrite/nf-dwrite-idwritetextrenderer-drawglyphrun) does not allow mutable access to `self` or the context pointer.

This doesn't prevent an implementation from working, but it certainly is an ergonomic papercut.

### Crate manifest

```TOML
windows-core = "0.56"

[dependencies.windows]
version = "0.56"
features = [
    "implement",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_System_Com",
]
```

**Comment by riverar** [comment]
`&mut self` isn't possible with COM where references can linger around. Instead, try using something like `RefCell`or `RwLock` to coordinate access to mutable state.

Some examples:
* https://github.com/microsoft/windows-rs/issues/2304#issuecomment-1402731360
* https://github.com/microsoft/windows-rs/blob/master/crates/tests/implement/tests/vector.rs

**Comment by kennykerr** [comment]
Right, `&mut self` implies exclusive access which is not compatible with COM where you may have multiple references accessing the same object simultaneously. Using `&self` forces you to be deliberate about this and avoids undefined behavior.

**Comment by david7a68** [comment]
I see. Closing this issue.

Thanks for the clarification!
