### ISSUE TITLE
Release new windows-sys?

### ISSUE THREAD

**Issue by evmar** [microsoft/windows-rs#3006]
### Suggestion

https://crates.io/crates/windows-sys/versions says windows-sys is at 0.52.0, while windows is at 0.56.0 per https://crates.io/crates/windows/versions

**Comment by kennykerr** [comment]
The `windows-sys` crate is not published regularly to avoid version churn.

**Comment by evmar** [comment]
I was hoping specifically for the change in 

https://github.com/microsoft/windows-rs/commit/7219668f80a459b47097bc524af304073c69ec4b#diff-7ed016d28949e2cee1c68a4ad5101d5c9f8d3766fb3e6e8e7310f9d273922d2eL3

which is necessary to use windows-sys when targeting i586-pc-windows-msvc

**Comment by kennykerr** [comment]
I simplified that further in #2973 and that's included with the latest release of the [windows-targets](https://crates.io/crates/windows-targets) crate.

**Comment by evmar** [comment]
Ah I see, I can use windows-sys 0.52.0 but specify windows-targets at 0.52.5 as an additional dependency and windows-sys will pick it up.  Thanks for your help!
