### ISSUE TITLE
Why is `windows-sys` not updating?

### ISSUE THREAD

**Issue by HoShiMin** [microsoft/windows-rs#3028]
### Suggestion

As the `windows-sys` doesn't get new releases, I can't use it due to old critical bugs like microsoft/windows-rs#2612. So, what about new release?

**Comment by ChrisDenton** [comment]
The windows-sys crate is not published regularly to avoid version churn.

You can however request an update.

**Comment by HoShiMin** [comment]
@ChrisDenton,
> to avoid version churn.
But why is it bad? `windows-sys` is very important for development in no-std environments like kernel drivers and we are stuck on legacy version with critical bugs - so, instead of just using Cargo, we have to link it directly as a git repo to use the latest version. And what is the gain?
> You can however request an update.
How could I do that?

**Comment by ChrisDenton** [comment]
> But why is it bad? windows-sys is very important for development in no-std environments like kernel drivers and we are stuck on legacy version with critical bugs - so, instead of just using Cargo, we have to link it directly as a git repo to use the latest version. And what is the gain?

It used to be released regularly. People complained. The trouble is that when a new version of windows-sys is released, every crate that depends on it also has to update otherwise users will get multiple versions in their dependency graph, slowing compile times. Therefore updates are now done on an as-needed basis.

> How could I do that?

You have already done so by making this issue.

**Comment by HoShiMin** [comment]
@ChrisDenton,
> You have already done so by making this issue.

Well, it would be great if it will be updated right after fixing #3029 as it's the only thing for me that prevents the use of `windows-sys`.

**Comment by kennykerr** [comment]
Feel free to circle back when the metadata issues have been resolved and you've tested with windows-rs and are ready for production.
