### ISSUE TITLE
Construct `windows_registry::Key` from `HKEY`

### ISSUE THREAD

**Issue by Legend-Master** [microsoft/windows-rs#3033]
### Suggestion

When using APIs like [`SetupDiOpenDevRegKey`](https://learn.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdiopendevregkey), you get a `HKEY` there, and there's no way to convert it to a `windows_registry::Key`

**Comment by kennykerr** [comment]
Thanks for the reminder - I've been meaning to add the complimentary interop function: #3034
