### ISSUE TITLE
`impl Default for OFSTRUCT` and other similar structs

### ISSUE THREAD

**Issue by anforowicz** [microsoft/windows-rs#3058]
### Suggestion

AFAIU [the `OFSTRUCT` struct](https://docs.rs/windows-sys/latest/windows_sys/Win32/Storage/FileSystem/struct.OFSTRUCT.html) doesn't implement the `Default` trait.  This means that [the user of the struct is forced to spell out all the struct fields during initialization](https://chromium-review.googlesource.com/c/chromium/src/+/5533267/12/build/rust/tests/windows_sys_test/main.rs#13), including `Reserved1` and `Reserved2`, as well as `cBytes`.  Would it be possible to have the `Default` `impl` provided by the `windows-sys` crate?

**Comment by kennykerr** [comment]
The `windows-sys` crate provides a minimal set of traits to minimize build time. The `windows` create does however provide such traits for this struct. 

https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html
