### ISSUE TITLE
convert &IFooBar to ManuallyDrop<Option<IFooBar>>

### ISSUE THREAD

**Issue by nxcy** [microsoft/windows-rs#3062]
### Suggestion

https://github.com/microsoft/windows-rs/blob/dbc3932513ba9ed489c0b99c1bb3aba565d23994/crates/samples/windows/direct3d12/src/main.rs#L496
Is this documented?
Is there a safer way to do the conversion?

**Comment by sivadeilra** [comment]
There is a new type in the `windows_core` crate, called `InterfaceRef`, which serves exactly this purpose now.  It has not yet been published, but I expect that we'll publish a new version of all of the Windows crates within the next 2 weeks.

**Comment by kennykerr** [comment]
It's not quite the right solution as it expects a lifetime parameter which cannot easily be added to structs like `D3D12_RESOURCE_BARRIER`. We also need to figure out a better harmony between `ParamValue`, which doesn't have lifetime, and `InterfaceRef`, which does. And neither are a perfect fit for `windows-bindgen` to use for structs, which would be the requirement to satisfy this issue.
