### ISSUE TITLE
IMMDevice::GetState() requires an out param and returns HRESULT, but the type of the return value is DEVICE_STATE

### ISSUE THREAD

**Issue by docwilco** [microsoft/windows-rs#3067]
### Summary

The Rust IMMDevice::GetState takes an "out" parameter (`pdwstate: *mut u32`), and returns a value of type `DEVICE_STATE`:
```rs
    pub unsafe fn GetState(&self, pdwstate: *mut u32) -> DEVICE_STATE {
        (::windows_core::Interface::vtable(self).GetState)(::windows_core::Interface::as_raw(self), pdwstate)
    }
```

The VTable implementation for that is:
```rs
    pub GetState: unsafe extern "system" fn(*mut ::core::ffi::c_void, *mut u32) -> DEVICE_STATE,
```

This looks wrong to me, as the C++ side of things defines IMMDevice::GetState as:

```cpp
HRESULT GetState(
  [out] DWORD *pdwState
);
```

This makes me think the Rust definition should be:
```rs
    pub unsafe fn GetState(&self) -> DEVICE_STATE {
        let mut result__ = core::mem::zeroed();
        (::windows_core::Interface::vtable(self).GetState)(::windows_core::Interface::as_raw(self), &mut result__).map(|| DEVICE_STATE(result__))
    }
```
With the VTable entry being:
```rs
    pub GetState: unsafe extern "system" fn(*mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
```

I'm not super familiar with the windows-rs crate internals just yet, so I'm not sure if this is generated code where the generator should be updated, or if this is code that should now be updated manually?

**Comment by kennykerr** [comment]
Yep, I'm just waiting for a release of the Win32 metadata.

**Comment by docwilco** [comment]
Oooh, shiny! Thank you! <3
