### ISSUE TITLE
Support ARM64EC?

### ISSUE THREAD

**Issue by Berrysoft** [microsoft/windows-rs#3075]
### Suggestion

Rust starts to support ARM64EC:

https://doc.rust-lang.org/stable/rustc/platform-support/arm64ec-pc-windows-msvc.html

Currently `windows-sys` is lacking some structs like `WSADATA` when targeting arm64ec.

**Comment by ChrisDenton** [comment]
Support for ARM64EC was added in https://github.com/microsoft/windows-rs/pull/2957 but a new version of windows-sys has not yet been released to crates.io.

**Comment by sivadeilra** [comment]
Yes, we'll certainly get ARM64EC supported.  Full credit to @dpaoliello for driving ARM64EC support in Rust and LLVM; either he or I will get this added to the `windows-rs` repo, Real Soon Now.

**Comment by kennykerr** [comment]
Note that this work is already done. It just hasn't been released to crates.io - as Chris noted above. 

Please do give the latest `windows-sys` crate a test drive by taking a dependency on the git repo and let us know if you have any questions/issues.

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories
