### ISSUE TITLE
Different signatures for DLGPROC and WNDPROC

### ISSUE THREAD

**Issue by Ekopalypse** [microsoft/windows-rs#3115]
### Suggestion

Currently [DLGPROC](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/type.DLGPROC.html) is defined to return an isize value, while [WNDPROC](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/WindowsAndMessaging/type.WNDPROC.html) assumes a LRESULT value.
Shouldn't both have identical signatures?
For example, if I want to create a custom dialog class, I need to register WNDCLASSEXW, which requires a WNDPROC, and then call e.g. CreateDialogParamW, which in turn requires a DLGPROC, ... or is there a misunderstanding on my part?

**Comment by tim-weis** [comment]
The declarations are consistent with [`DLGPROC`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-dlgproc) and [`WNDPROC`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-wndproc). While `INT_PTR` and `LRESULT` resolve to the same type at the ABI[^1], window procedures and dialog procedures follow different protocols. To support the dialog manager, a dialog procedure must return not one, but two pieces of information (see [Returning values from a dialog procedure](https://devblogs.microsoft.com/oldnewthing/20031107-00/?p=41923)).

Consequently, window procedures and dialog procedures cannot be used interchangeably.

For the case where you want to create a dialog that's implemented by a custom window class, you have to register a window procedure that delegates unhandled messages to [`DefDlgProc`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-defdlgprocw) (note that `DefDlgProc` is a window procedure, not a dialog procedure). In this scenario, I believe you can call `CreateDialogParam` without passing a dialog procedure; after all, you've already customized dialog behavior via the custom window class.

In essence: `DLGPROC` and `WNDPROC` have the same binary signature but cannot be used interchangeably. The `windows` crate uses the type system to (artificially) make them incompatible. In doing this it prevented you from implementing a bug.

[^1]: Here is the definition for [`LRESULT`](https://docs.rs/windows-sys/0.52.0/windows_sys/Win32/Foundation/type.LRESULT.html) in the `windows-sys` crate.

**Comment by Ekopalypse** [comment]
@tim-weis - thanks for the quick reply and thanks for the advice/explanations.
Regarding not passing the dialog/window procedure, I was of the opinion that this did not work in the sense that the dialog could not be terminated. But it could be that I made a mistake when testing.
I will have another look at this. Have a nice weekend.
