### ISSUE TITLE
`IdleDispatchedHandler` requires a `FnMut` which is too strict

### ISSUE THREAD

**Issue by bdbai** [microsoft/windows-rs#313]
Delegate types require a closure with type `impl FnMut` to construct. The following demo fails to compile.
```rust
winrt::import!(
    dependencies
        os
    types
        windows::ui::core::{CoreDispatcher, IdleDispatchedHandler}
);

use windows::ui::core::*;

#[allow(unused)]
fn dispatch(dispatcher: &CoreDispatcher) {
    let data = vec![0];
    let _ = dispatcher.run_idle_async(IdleDispatchedHandler::new(move |_| {
        // error[E0507]: cannot move out of `data`, a captured variable in an
        // `FnMut` closure
        let _ = data.into_iter();
        //      ^^^^ move occurs because `data` has type `std::vec::Vec<i32>`,
        //           which does not implement the `Copy` trait
        Ok(())
    }));
}
```
Semantically, an `IdleDispatchedHandler` will be dispatched no more than once, and a `FnMut` is too strict than necessary. Given that it is not possible to tell from metadata how many times a delegate object will be called, can we have something like `IdleDispatchedHandler::once` to construct such delegate object with `FnOnce`, plus some runtime check to enforce that the closure cannot be called twice?

**Comment by kennykerr** [comment]
Sorry for the delay - I'm on vacation (mostly camping and offline). That sounds like a reasonable idea. Will look into it further when I'm back.

**Comment by kennykerr** [comment]
Just closing out some old issues I'm unlikely to get to. I think that in general this is not something we can guarantee is correct and the particular use case doesn't seem to be general enough to warrant further investment. Feel to chime in if you disagree.
