### ISSUE TITLE
Send and Sync for Weak reference

### ISSUE THREAD

**Issue by lifers** [microsoft/windows-rs#3137]
### Suggestion

Is there any danger in assuming Send and Sync for types that contain windows_core::Weak? In comparison, std::sync::Weak is Send and Sync.

If it's safe, I'd like it to be implemented directly in the windows_core::Weak definition. Thanks!

**Comment by kennykerr** [comment]
Yep, `IWeakReference` and `IWeakReferenceSource` are designed and implemented to be completely thread safe.
