### ISSUE TITLE
Help needed: How to safely cast GetPrinter [u8] buffer to PRINTER_INFO

### ISSUE THREAD

**Issue by ValentinGrim** [microsoft/windows-rs#3139]
### Summary

Hi,

I'm trying to get the printer info of a printer using GetPrinterW function but I'm stuck casting `PRINTER_INFO_2W` from raw [u8] buffer.

I based my code on [issue 2975](https://github.com/microsoft/windows-rs/issues/2975) that's use EnumPrinters.

I have this (see last line comments):

```rust
unsafe {
    let mut printer_h = HANDLE::default();
    if let Err(e) = OpenPrinterW(self.printer_name.as_pwstr(), &mut printer_h, None) {
        return err!("OpenPrinter", e);
    }

    let mut needed : u32 = 0;
    if let Err(e) = GetPrinterW(printer_h, 2, None, &mut needed) {
        if e.code() != HRESULT::from_win32(ERROR_INSUFFICIENT_BUFFER.0) {
            return err!("GetPrinter", e);
        }
    }

    let mut buffer: Vec<u8> = vec![0; needed as usize];
    if let Err(e) = GetPrinterW(printer_h, 2, Some(&mut buffer), &mut needed) {
        return err!("GetPrinter", e);
    }

    /** Here where I'm lost.
      * The line below is based on issue 2975 but it gave me a Vec, not a single element.
      * I also tried to get the first element but i get STATUS_ACCESS_VIOLATION on various item.
      * What have i missed ?
      **/
    let printer_info: &[PRINTER_INFO_2W] = std::slice::from_raw_parts(buffer.as_ptr() as *const _, needed as usize);

    /* ... */

    if let Err(e) = ClosePrinter(printer_h) {
        return err!("ClosePrinter", e);
    }
}
```

Any help would be apreciated, thank's in advance.
Have a nice day.

**Comment by kennykerr** [comment]
I think you just need to cast the byte pointer to a pointer of the appropriate structure. I'm not sure why you're casting it to an array/slice of structures. The [API docs](https://learn.microsoft.com/en-us/windows/win32/printdocs/getprinter) seem to indicate that it returns a single structure.

**Comment by ValentinGrim** [comment]
Actually, windows-rs is the first crate that I use that made me use raw pointer in Rust.
There is not that much documentation about casting raw pointer and unsafe code in general.

Anyway, I think you mean something like that ?

```rust
let printer_info =  std::ptr::slice_from_raw_parts_mut(buffer.as_mut_ptr(), buffer.len()) as *mut PRINTER_INFO_2W; 
```
