### ISSUE TITLE
crates.io docs still point to 0.56

### ISSUE THREAD

**Issue by Jasper-Bekkers** [microsoft/windows-rs#3149]
### Summary

It looks like the microsoft hosted docs are still pointing to versino 0.56 instead of the recently released 0.58

**Comment by riverar** [comment]
Will get that process started. We handle this manually because rustdoc needs ~20GB of memory to complete the operation and generates ~quarter million files that then need to get checked in.

**Comment by riverar** [comment]
New docs deployed https://microsoft.github.io/windows-docs-rs/doc/windows/, thanks for the heads up.
