### ISSUE TITLE
Make enum variants associated constants on the enum type

### ISSUE THREAD

**Issue by farnoy** [microsoft/windows-rs#3150]
### Suggestion

Compare the generated enum like [`D3D12_BARRIER_SYNC` ](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Direct3D12/struct.D3D12_BARRIER_SYNC.html?search=d3d12_barrier_sync) with a similar enum generated by [`ash`](https://docs.rs/ash/latest/ash/vk/struct.PipelineStageFlags.html). Associated constants (and a richer bitflags API) make it easier to work with and less verbose.

You could then write code like this:

```rust
use D3D12_BARRIER_SYNC as B;
B::DRAW | B::COPY
```

**Comment by kennykerr** [comment]
This is controlled by the metadata definitions for such types. The code generator takes into account whether the original definitions were C-style enums or C++ enum classes and generates the bindings accordingly.

**Comment by riverar** [comment]
This type is currently marked as

```csharp
[Flags]
public enum D3D12_BARRIER_SYNC
...
```

Is there something missing from metadata?

**Comment by riverar** [comment]
Ah this is a C enum, per DirectX headers

```cpp
typedef enum D3D12_BARRIER_SYNC
{
    D3D12_BARRIER_SYNC_NONE                                                     = 0x0,
    D3D12_BARRIER_SYNC_ALL                                                      = 0x1,
    D3D12_BARRIER_SYNC_DRAW                                                     = 0x2,
    D3D12_BARRIER_SYNC_INDEX_INPUT                                              = 0x4,
...
```

Not sure there's anything we can do on the metadata side either, everything looks accurate. If you have a more specific enhancement you'd like to see, please create a new issue with more detail.
