### ISSUE TITLE
Copy descriptions from the MSDN C++ documentation

### ISSUE THREAD

**Issue by TechnoPorg** [microsoft/windows-rs#3159]
### Suggestion

Hi there,

As it stands, `windows-docs-rs` is really helpful for browsing data types and method signatures of the Rust API, but beyond that, there's no detail explaining what things do and how they work. Consequently, I frequently find myself looking up the exact same symbols in `windows-docs-rs` and the C++ API docs on MSDN.

It would be awesome if the descriptions that the community has written for the Windows API on MSDN could also be included in the Rust documentation when docs are being generated. They're already there, and for the most part, quite thorough and informative. Also, it's just not worth it to completely separately document the Rust API wrapper.

A couple problems I can already think of related to this idea:
- There are a few cases where the Rust API doesn't perfectly match up with C++, so it might provide misinformation in a few places.
- There are already concerns with the length of time it takes to build docs, and this would increase it further.
- Would add a lot of network usage to the documentation building process.

The least problematic implementation would just be to link the MSDN page from the associated Rust page, and that would already be a huge improvement. I realise that more than that is a bit of an idealistic suggestion, but I thought I'd put it out there anyways :grin:

Thanks for all your hard work on the crate!

**Comment by kennykerr** [comment]
We'd love to do that but unfortunately, rustdoc is already at the breaking point when it comes to the `windows` crate. Even if that were not an issue, MSDN doesn't even provide permalinks that we can reliably use.

**Comment by TechnoPorg** [comment]
Fair enough. That's good to know, if a little disappointing.

Feel free to close this issue if you like; otherwise, I'll just leave it open in case anything changes in the future.
