### ISSUE TITLE
Inline `windows_result::Error::from_win32`, `windows_result::Error::from_hresult` and `windows_result::HRESULT::from_win32`.

### ISSUE THREAD

**Issue by herabit** [microsoft/windows-rs#3176]
### Suggestion

I noticed that regardless of optimization level, unless link time optimization is enabled, the small functions  `windows_result::Error::from_win32`, `windows_result::Error::from_hresult` and `windows_result::HRESULT::from_win32` are never inlined.

Since they're all very small, it makes sense to inline them to avoid the additional overhead of a function call. Particularly this matters for `Error::from_win32` which is used very frequently in code that uses the `windows` crate.

**Comment by kennykerr** [comment]
Any reason you're not using LTO for this? Note that always inlining these can also lead to code bloat.

**Comment by riverar** [comment]
I don't think we can even guarantee inlining occurs, another indication that LTO is the better path.
