### ISSUE TITLE
InitializeObjectAttributes macro/function

### ISSUE THREAD

**Issue by juliusl** [microsoft/windows-rs#3183]
### Suggestion

There a few functions that require an OBJECT_ATTRIBUTES struct, however there is no [`InitializeObjectAttributes`] function/macro which is typically used in examples. Is it possible to add this?

[`InitializeObjectAttributes`]: https://learn.microsoft.com/en-us/windows/win32/api/ntdef/nf-ntdef-initializeobjectattributes

**Comment by riverar** [comment]
Hey @juliusl,

`InitializeObjectAttributes` is a C++ macro that automates the setting of several fields in an `OBJECT_ATTRIBUTES` structure, as shown below:

```cpp
#define InitializeObjectAttributes( p, n, a, r, s ) { \
    (p)->Length = sizeof( OBJECT_ATTRIBUTES );          \
    (p)->RootDirectory = r;                             \
    (p)->Attributes = a;                                \
    (p)->ObjectName = n;                                \
    (p)->SecurityDescriptor = s;                        \
    (p)->SecurityQualityOfService = NULL;               \
    }
```

A more Rust idiomatic approach would be to leverage the `Default` trait to [initialize the struct](https://doc.rust-lang.org/book/ch05-01-defining-structs.html) with default values while only overriding the fields you need to set explicitly.

```rust
let oa = OBJECT_ATTRIBUTES64 {
    Length: std::mem::size_of::<OBJECT_ATTRIBUTES64>() as _,
    // RootDirectory: ...,
    // Attributes: ...,
    // ObjectName: ...,
    // SecurityDescriptor: ...,
    // SecurityQualityOfService: ...,
    ..Default::default()
};
```

Hope that helps!

**Comment by riverar** [comment]
Regarding the request to include the macro: because it cannot be represented by upstream metadata, it would need to be integrated directly into the crate as some sort of helper. Given the simplicity of the macro, that is unlikely to happen.

See also:
- https://github.com/microsoft/windows-rs/issues/2952
- https://kennykerr.ca/rust-getting-started/where-are-the-macros.html
