### ISSUE TITLE
Questions about windows-rs error handling

### ISSUE THREAD

**Issue by joaoviictorti** [microsoft/windows-rs#3185]
### Summary

Hi guys, I have a question about `windows-rs` and `windows_sys`.

What would be the most idiomatic way to handle errors? I realized that several APIs use Result, but I would like to know how I can improve my code to handle errors efficiently and idiomatically in Rust.

I've seen that in your examples you use the `?` operator a lot for error propagation, but I'd like to know how to deal with situations where, for example, I open a `HANDLE` for a process. If an error occurs, how would I close the handle and display the error in an idiomatic way? Are there any best practices or recommended standards to ensure that resources are released correctly even when failures occur?

Rust has many ways of handling an error with match, expect and so on. And I'd like to know which of them is the “idiomatic” way in a situation where I need to close a resource like `HANDLE` itself.

The issue itself isn't a bug, but I put it in because I couldn't find any other suggestion.

**Comment by joaoviictorti** [comment]
I used to use `unwrap_or_else` a lot, then call `CloseHandle` and trigger a `panic` as an error, but I don't think that would be the idiomatic form

**Comment by kennykerr** [comment]
This is more of a general Rust programming question that may be better geared to a forum like:

https://stackoverflow.com/search?q=windows-rs

As far as windows-rs goes, the `windows` crate attempts to use `Result` types as much as practical. This is driven by [metadata and code generation](https://kennykerr.ca/rust-getting-started/how-are-crates-built.html). There will always be APIs that either don't have clear error handling metadata or just don't map well to `Result`. In such cases, you're left to figure out what's best for you based on the API docs.
