### ISSUE TITLE
A sample for sending HTTP request requests

### ISSUE THREAD

**Issue by borasemiz** [microsoft/windows-rs#3186]
### Suggestion

Hi, could you guys put a sample for creating and sending HTTP requests, with emphasis on how to set request headers. There is a sample for getting RSS feed with syndication client, but there is no example of HTTP. Dealing with HTTP is much more common than dealing with RSS.

**Comment by kennykerr** [comment]
The samples aren't meant to cover every popular API. Rather they're mostly meant to illustrate different kinds of API technology, whether its C-style Win32 APIs, COM APIs, WinRT APIs, and so on. While I'm opposed to such an example, you're probably better off getting some advice from a forum like: https://stackoverflow.com/search?q=windows-rs

I also wrote about various HTTP APIs in the past. It's not Rust-specific but can be ported over pretty easily with the `windows` crate: https://kennykerrca.wordpress.com/articles/
