### ISSUE TITLE
Root level documentation for crates is very sparse

### ISSUE THREAD

**Issue by Nerixyz** [microsoft/windows-rs#3187]
### Suggestion

Most crates have the following documentation at the root on docs.rs (what people see when they open docs.rs/\<crate-name\>):

> Learn more about Rust for Windows here: <https://github.com/microsoft/windows-rs>

However, these crates have documentation in their README, visible on crates.io. The same documentation should be visible on docs.rs.
Having a refresher on the basic concept of a crate and a few links to more documentation/examples is really helpful.

I made a small concept in https://github.com/Nerixyz/windows-rs/commit/9dd956563dcc296dea28c6a7f4b522b898403e61. If that's good enough, I'll open a PR.

**Comment by kennykerr** [comment]
I tried doing this a while back #1429 but couldn't get it to work reliably. If its testable and produces good doc generation then it seems like a reasonable improvement.

**Comment by Nerixyz** [comment]
> I tried doing this a while back #1429 but couldn't get it to work reliably. If its testable and produces good doc generation then it seems like a reasonable improvement.

The tests would need to specify the required features, as rustdoc can't infer them from the doctests. That's only an issue for windows and windows-sys. I've added a `cfg_attr` for the required features. Realistically, documentation for both crates is only ever built with all features or the `docsrs` cfg for windows. All other crates don't require any features for the examples (or they are ignored, like in windows-implement/interface).

**Comment by kennykerr** [comment]
Realize you probably didn't see my 👍 - did you still want to pursue this?

**Comment by Nerixyz** [comment]
Oh, yea I missed that.
