### ISSUE TITLE
Improve interface for MFCreateAttributes and MFEnumDeviceSources

### ISSUE THREAD

**Issue by clouds56** [microsoft/windows-rs#3188]
### Suggestion

Now [`MFCreateAttributes`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Media/MediaFoundation/fn.MFCreateAttributes.html) and [`MFEnumDeviceSources`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Media/MediaFoundation/fn.MFEnumDeviceSources.html) looks like
```rust
pub unsafe fn MFCreateAttributes(
    ppmfattributes: *mut Option<IMFAttributes>,
    cinitialsize: u32,
) -> Result<()>

pub unsafe fn MFEnumDeviceSources<P0>(
    pattributes: P0,
    pppsourceactivate: *mut *mut Option<IMFActivate>,
    pcsourceactivate: *mut u32,
) -> Result<()>
where
    P0: Param<IMFAttributes>
```
In the mean time, many functions begins with "MFCreate" returns a COM object like
```rust
pub unsafe fn MFCreateMediaType() -> Result<IMFMediaType>

pub unsafe fn MFCreateFile<P0>(
    accessmode: MF_FILE_ACCESSMODE,
    openmode: MF_FILE_OPENMODE,
    fflags: MF_FILE_FLAGS,
    pwszfileurl: P0,
) -> Result<IMFByteStream>
where
    P0: Param<PCWSTR>

pub unsafe fn MFCreateMediaEvent(
    met: u32,
    guidextendedtype: *const GUID,
    hrstatus: HRESULT,
    pvvalue: Option<*const PROPVARIANT>,
) -> Result<IMFMediaEvent>
```

I think it's more idiomatic to make `MFCreateAttributes` and `MFEnumDeviceSources` have signature
```rust
pub unsafe fn MFCreateAttributes(
    cinitialsize: u32,
) -> Result<IMFAttributes>

pub unsafe fn MFEnumDeviceSources<P0>(
    pattributes: P0,
) -> Result<EnumView<IMFActivate>>
where
    P0: Param<IMFAttributes>
```

with `EnumView` defined as
```rust
struct EnumView<T> {
    ptr: *mut Option<T>,
    count: u32,
}

impl<T> AsRef<[T]> for EnumView<T> {
    // ...
}

impl<T> Drop for EnumView<T> {
    fn drop(&mut self) {
        CoTaskMemFree(self.ptr)
    }
}
```

I thought it is easy to manually change the code to achieve this, but since most bindings are generated, I wonder why `MFCreateAttributes` and `MFCreateMediaType` differs?

**Comment by tim-weis** [comment]
> I wonder why `MFCreateAttributes` and `MFCreateMediaType` differs?

The Win32 metadata doesn't provide enough information to mark COM interface output parameters. The code generator is thus forced to use heuristics to determine whether it can apply the `Result<ISomeInterface>` transformation. One of the properties it evaluates is the position of the pointer-to-pointer-to-interface `[Out]` parameter. If it isn't the final parameter the generator will keep the explicit `[Out]` parameter and `Result<()>` return type.

The heuristics aren't picked at random. They result from trying different things and observing which ones produce the largest set of transformation candidates without introducing false positives (false positives generally render APIs unusable). This inevitably introduces slight inconveniences for clients, which is fine given how trivially easy a [wrapper](https://github.com/microsoft/windows-rs/blob/a6b49e94f4c6c1781d58e0c3496c8302a3533892/crates/samples/windows/direct2d/src/main.rs#L533C1-L549C1) can be implemented.

**Comment by clouds56** [comment]
Thanks for quick reply.
The idea of heuristics is great. Could we additionally "patch" the generator that we could manually set some function applying the `Result<ISomeInterface>` transformation?

Having a new metadata file like this, which community could contribute.
```
FunctionName,SignatureKind,Position
Win32::Media::MediaFoundation::MFCreateAttributesCopy,SignatureKind::ResultValue,0
Win32::Media::MediaFoundation::MFEnumDeviceSources,SignatureKind::ResultEnumView,-2
```

Add a wrapper to a single function is trivial, but adding a lot of them is not idiomatic way writing rust.
Especially things like `MFEnumDeviceSources`, one might forget to `CoTaskMemFree` (not even mentioned in docs of [rust](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Media/MediaFoundation/fn.MFEnumDeviceSources.html), only in docs of [win32](https://learn.microsoft.com/en-us/windows/win32/api/mfidl/nf-mfidl-mfenumdevicesources)) and thus introduce a memory leak.

**Comment by clouds56** [comment]
I think this might be 2 separate issue (but related)
1. Make returned array owned by COM wrapping with `EnumView`, the heuristics should be check last 2 parameters is `[OUT]` of an array pointer and count (I'm not sure if the metadata indicates who owns the memory). IIRC, this is not the only case that returns a array and `CoTaskMemFree` is necessary.
2. Add ability to specify `SignatureKind` of a specified function that could not be covered by heuristics progress.

Sure these are only suggestions but since we have `windows` over `windows-sys`, I think the former should be more like rust and make user handle as less pointer and ownership as possible.

**Comment by kennykerr** [comment]
While metadata and code generation work great, it can only get us so far. At a certain point it becomes easier to just produce a hand-authored crate that provides a tailored experience for a certain API. 

For best results, I suggest:

* Contribute to the https://github.com/microsoft/win32metadata project to fix bugs and improve the quality of the metadata.
* Write a Media Foundation crate that uses the windows-rs bindings internally and provides a more idiomatic experience for Rust developers.
