### ISSUE TITLE
Inprove `Value` in `windows-registry` crate

### ISSUE THREAD

**Issue by InfyniteHeap** [microsoft/windows-rs#3189]
### Suggestion

Coming from https://github.com/rust-lang/rustup/blob/4207838d962204123f70705ff9f3e73c37b813df/src/cli/self_update/windows.rs#L860-L888. We probably need these two features for `Value`:

- A constructor.
- A pair of trait that allows other types (e.g. `u32`, `&[u8]` and `HSTRING`) be converted to `Value`, and the same on the contrary. The `TryFrom<T>` seems cannot fit the requirements.

The purpose of this code snippet is to store the original registry status and recover the status after testing the registry-relevant test cases, avoiding corrputting the registry items. So, this should hold a `Value`.

In addition, the crate provides `set_value()`, but users cannot pass their own `Value` into it (it's meaningless to pass the `Value` got from `get_value()` into it), so, at least out of this problem, I think this suggestion could be taken into consideration.

**Comment by kennykerr** [comment]
It's not clear from the suggestion above what you're actually struggling with. You can create a `Value` from various types using `try_from` and `try_into` and you can certainly pass your own `Value` to `set_value` as the tests confirm. 

https://github.com/microsoft/windows-rs/blob/master/crates/tests/registry/tests/value.rs

Please provide a minimal repro for any specific bug/feature requests.

**Comment by InfyniteHeap** [comment]
I think this suggestion is no longer needed.
