### ISSUE TITLE
Could we consider setting the `cb` field in the `Default` implementation of the `STARTUPINFOEX` structs?

### ISSUE THREAD

**Issue by abhishekp106** [microsoft/windows-rs#3208]
### Suggestion

When developing my application I spent a bit of time chasing down a bug where I forgot to set the `cb` field on the `STARTUPINFOEXW` struct. It's documented in the "Remarks" section [here](https://learn.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-startupinfoexw#remarks) but I was wondering if the  `Default` implementations for `STARTUPINFOEXA` and `STARTUPINFOEXW` could set this field. In theory, we have all of the information needed to set this field and consumers have to set this field.

It would add one line to each impl:

```
startup_info.StartupInfo.cb = std::mem::size_of::<STARTUPINFOEXW>() as u32;
```

If the maintainers think this is worthwhile, I can go ahead an open up a PR to do this!

**Comment by kennykerr** [comment]
See https://kennykerr.ca/rust-getting-started/how-are-crates-built.html

This isn't well supported by the metadata and thus not supported by windows-rs.

**Comment by riverar** [comment]
[Some structures](https://learn.microsoft.com/windows/win32/api/shellapi/ns-shellapi-notifyicondataw#remarks) support initialization of these fields with a variety of values to support other platforms, opt into other API behaviors, etc. It's probably safer we defer to a higher level wrapper to decide what's best for its users and stay in control of those values.

**Comment by abhishekp106** [comment]
> See https://kennykerr.ca/rust-getting-started/how-are-crates-built.html
> 
> This isn't well supported by the metadata and thus not supported by windows-rs.

That makes sense - it's not trivial to add this information to the metadata.

> [Some structures](https://learn.microsoft.com/windows/win32/api/shellapi/ns-shellapi-notifyicondataw#remarks) support initialization of these fields with a variety of values to support other platforms, opt into other API behaviors, etc. It's probably safer we defer to a higher level wrapper to decide what's best for its users and stay in control of those values.

For many structs like the one you linked I agree that it's better to let the user control how they set it. This behavior is not desirable in structs like that. For `STARTUPINFOEXW` and `STARTUPINFOEXA` my understanding is that there is only one correct way to set the `cb` field - it's always the size of the struct itself. My motivation here was to provide more rust-like bindings but I understand that it's not easy to support given how the crate is built. 

Thank you both for your time!

**Comment by tim-weis** [comment]
> For `STARTUPINFOEXW` and `STARTUPINFOEXA` my understanding is that there is only one correct way to set the `cb` field

That's not correct. The `cb` field of the [`STARTUPINFOW`](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow) structure is used for versioning. [`STARTUPINFOEXW`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-startupinfoexw) is the first structure to make use of this, so now there are *two* correct values for `cb`, not just one.
