### ISSUE TITLE
Translate (`In`-only?) `MemorySize(BytesParamIndex = N)` void pointers to `&[u8]`?

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#3229]
### Suggestion

In `Windows.Win32.Graphics.Direct3D.Fxc` there's this function in the metadata:

```cs
[DllImport("D3DCOMPILER_47.dll", ExactSpelling = true, PreserveSig = false)]
[Documentation("https://learn.microsoft.com/windows/win32/api/d3dcompiler/nf-d3dcompiler-d3dcompile")]
public unsafe static extern HRESULT D3DCompile(
    [In][Const][MemorySize(BytesParamIndex = 1)] void* pSrcData,
    [In] UIntPtr SrcDataSize,
    ...
);
```

[In `windows-rs`](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Graphics/Direct3D/Fxc/fn.D3DCompile.html) that currently takes a raw pointer and a slice:

```rust
pub unsafe fn D3DCompile<P0, P1, P2, P3>(
    psrcdata: *const c_void,
    srcdatasize: usize,
    ...
);
```

Would it be nice to pass a sized slice borrow of `u8` here instead?

https://github.com/microsoft/windows-rs/issues/2106 is perhaps related, but seems to mostly discuss preallocated `out` slices that would have to use `MaybeUninit<u8>` to allow the caller to skip initialization.

**Comment by kennykerr** [comment]
There were some false positives that made this impractical last I checked, but I can check again to see what impact this has.

**Comment by kennykerr** [comment]
An example is a function like `DwmGetWindowAttribute` and its `pvAttribute` parameter that really isn't meant to be treated as a byte array/slice. This parameter is correctly defined as `void*` since it is polymorphic. 

Functions that use `MemorySize` should use a byte parameter type. This signals that they are meant to be treated as byte slices rather than opaque or polymorphic pointer types.

I would suggest that `windows-bindgen` is right to be conservative here and that if you would like to pursue this further that you consider improvements to the Win32 metadata for functions that use `void` when they should be using `byte`. This would then translate to a `&[u8]` or `&mut [u8]` parameter in Rust.

**Comment by kennykerr** [comment]
Ideally, the `MemorySize` attribute would be removed from non-byte parameters like `DwmGetWindowAttribute`. I can't imagine they are useful in any language.

**Comment by MarijnS95** [comment]
Also @kennykerr looking at `DwmGetWindowAttribute()` the documentation, it's annotated to contain the number of bytes at the very least, so if anything these APIs can still be translated to take arbitrary byte slices (users can use `bytemuck` to translate `T` types into them) or `T: Sized` parameters that you can forward using `size_of::<T>()` / `size_of_val(&t_parameter)`?

**Comment by MarijnS95** [comment]
I think I found an answer for both the "how do we know the status" and "how do we tie up the return type to the array" in exactly one of those functions (even if this SAL doesn't seem to be translated into attributes "yet"):

https://github.com/microsoft/win32metadata/blob/a4418f7f3c58becfbb32b448d21ff82023d8bcb9/generation/WinSDK/RecompiledIdlHeaders/um/Psapi.h#L194-L205

The status is quite simply `_Success_(return != 0)`.

The returned length, in case of `GetModuleBaseName*()`/`Get**Name*()` should probably also be annotated with the same:

```cpp
    _When_(return < nSize, _Out_writes_to_(nSize, return + 1))
    _When_(return == nSize, _Out_writes_all_(nSize))
```

And in case of `EnumProcessModules*()`, that should likely become:

```cpp
    _When_(*lpcbNeeded < cb, _Out_writes_to_(cb, *lpcbNeeded))
    _When_(*lpcbNeeded >= cb, _Out_writes_all_(cb))
```
