### ISSUE TITLE
Release 0.60 request

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-rs#3232]
### Suggestion

Hi,

I would like to request a new release with the following update to the metadata:

https://github.com/microsoft/win32metadata/pull/1975

This adds the missing [QueryOptionalDelayLoadedAPI](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi2/nf-libloaderapi2-queryoptionaldelayloadedapi) function (see https://github.com/microsoft/win32metadata/issues/1966).

Thank you!

**Comment by kennykerr** [comment]
First, we'll need a Win32 metadata release to update the generated bindings. I'm not sure when that will be available. 

Second, do you need a release on crates.io or just this updated in windows-rs so that you can develop and test with this API?

**Comment by Alovchin91** [comment]
It’s okay, I’m currently importing the API manually so it can wait for a new metadata release, no rush.

I would prefer it to be a release on crates.io though, if possible.

**Comment by kennykerr** [comment]
Ok, will close for now. Feel free to reach out again if you're blocked.
