### ISSUE TITLE
GetTransactionInformation Inconsistent type

### ISSUE THREAD

**Issue by Nordgaren** [microsoft/windows-rs#3238]
### Suggestion

https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/fn.GetTransactionInformation.html
https://docs.rs/windows-sys/0.59.0/windows_sys/Win32/Storage/FileSystem/fn.GetTransactionInformation.html

I am helping a friend get into Rust, and they are using the windows crate, and we noticed the discrepancy between these two functions, and it reminded me of a problem I have with strings in this crate.

For this one, I think the windows-rs crate probably has the best impl, as `PWSTR` requires a bit of wrapping that is kinda annoying and ugly. I am surprised that it doesn't take a `windows_core::Param<windows_core::PWSTR>` or something, as a lot of functions do that this `Param` trait. 

I understand that it is dangerous to just take a buffer of `u16`s, but most of that time that is what is happening, either directly, as in this function for `GetTransactionInformation` or indirectly, because you have to make some kind of buffer and pass it in or a pointer in to make these types, and there is no checking for a null terminator or anything. I understand that, in this example, the buffer is just being written to, so it shouldn't matter, and the real problem is if the function accepts a string that is going to be read, but, unless you are using a type that enforces a null terminator on your string, you still might run into issue.

All of this to say, is it not possible to implement `windows_core::Param<windows_core::PWSTR>` and  `windows_core::Param<windows_core::PWCSTR>` for u16 slices and Vecs? Maybe even require null terminator in that conversion, especially if it's a string that's being read (I don't know if there's any API functions that mutate strings, so IDK how necessary it is to enforce for the mutable PWSTR)? Those types may be a bit questionable to implement for, but what about `CString` and `CStr`? Surely these types, that enforce null terminator, can have `windows_core::Param<windows_core::PCSTR>` implementations?

I just find working with strings to pass into functions for this crate can get very frustrating. I sometimes feel like I am just writing bad C++ code in Rust, when trying to get things to convert.

I have to do this right now for `CStr` and `CString`, to call something like `CreateFileA`
```
PCSTR(file_name.as_ptr().cast())
```

but really I don't see why they can't be converted to PCSTR safely through the param, since they should already have the guarantees necessary?

Thank you for your time,
Nordgaren

**Comment by tim-weis** [comment]
[`HSTRING`](https://docs.rs/windows-strings/0.1.0/windows_strings/struct.HSTRING.html) is the canonical string representation in the `windows` family of crates. [`from_wide`](https://docs.rs/windows-strings/0.1.0/windows_strings/struct.HSTRING.html#method.from_wide) constructs an `HSTRING` from a `u16` slice, and `&HSTRING` is convertible to `PCWSTR`.

Assuming that `name` is a `&[u16]` you could call `CreateFileW` like this:

```rust
let h = CreateFileW(&HSTRING::from_wide(name), ...)?;
```

Narrow character strings do not get nearly as much attention, and neither do mutable strings (though I've been told that [`HStringBuilder`](https://docs.rs/windows-strings/0.1.0/windows_strings/struct.HStringBuilder.html) offers support for mutable wider-character strings).

**Comment by Nordgaren** [comment]
What about calling `CreateFileA`? Is there a type that is supported for calling that? the macro only works at compile time, so, if I wanted a C style string at runtime, I might make `CString` from a formatted string. Is there a reason why `Param<PCSTR>` can't be implemented for `CString` and `CStr` so that the rust std library plays nice with the windows-rs library? `HSTRING` works fine for wide strings, and I can even use `HSTRING` with format using `HSTRING::from()`, if I really wanted to, but I haven't found a good type for C style strings and the ASCII api functions. 

In my code, I might just have a `CStr` already, because I am interfacing with C strings, and I just want to call some API function that accepts a `P` where `P: windows_core::Param<windows_core::PCSTR>`, and it doesn't accept that. I have to get the pointer, and then since the pointer is not the right type for `PCSTR`, I have to then cast it.

I feel like this type is already compatible with the windows API because of it's guarantees, though. I understand that `HSTRING` is for wide strings, and that is what I use for safe wrapper abstractions to call wide string API functions, but there is no type that I have found for Ascii/`PCSTR` functions. Sure, this would probably just be a the same as the `PCSTR(file_name.as_ptr().cast())` code I posted above, but at least now the type would be compatible with the calls.

**Comment by Permik** [comment]
Could you just call `.into()` and type inference would figure out the rest when calling the function?

If the from traits are not implemented, maybe that should be next on the agenda?

**Comment by Nordgaren** [comment]
> Could you just call `.into()` and type inference would figure out the rest when calling the function?
> 
> If the from traits are not implemented, maybe that should be next on the agenda?

The first thing I try, if the type isn't compatible, is `.into()`. It does not work for `CString` on a generic param that implements `windows_core::Param<windows_core::PCSTR>`

**Comment by kennykerr** [comment]
I created #3254 to consider string parameters.
