### ISSUE TITLE
windows-registry support key metadata query

### ISSUE THREAD

**Issue by amone-bit** [microsoft/windows-rs#3240]
### Suggestion

Sometimes, I need query key's metadata, but I seem not found relative API in windows-registry. I try to define a function that input parameter is Key type that in the windows-registry crate, but HKEY that in the Key type is private. Could you give me a helpful method to solve this problem or maybe you can add a new API to the windows-registry.

**Comment by riverar** [comment]
What metadata are you referring to?

**Comment by amone-bit** [comment]
RegQueryInfoKeyW this API's return metatdata
![image](https://github.com/user-attachments/assets/9633bf84-4003-4b00-b2ca-5ee9c392ae29)

**Comment by kennykerr** [comment]
A lot of those fields aren't directly useful, so it would help to be a bit more specific. 

You can always call `as_raw` to get the underlying handle as illustrated here:

https://github.com/microsoft/windows-rs/blob/master/crates/tests/registry/tests/interop.rs

**Comment by riverar** [comment]
OK, sounds like you want access to a key's:
* security descriptor
* last write time

Until that's added, get the underlying handle per @kennykerr's comment.

**Comment by amone-bit** [comment]
Thanks, actually I want to get these fields:

- values
- last write time

And, I dont understand why need this statement: `std::mem::forget(key);` in https://github.com/microsoft/windows-rs/blob/master/crates/tests/registry/tests/interop.rs
```rust
#[test]
fn windows_interop() -> Result<()> {
    use windows::{core::*, Win32::System::Registry::*};

    let test_key = "software\\windows-rs\\tests\\windows_interop";
    _ = CURRENT_USER.remove_tree(test_key);

    let key = CURRENT_USER.create(test_key)?;
    key.set_u32("1", 1)?;
    key.set_u32("2", 2)?;
    key.set_u32("3", 3)?;

    let raw = HKEY(key.as_raw());
    std::mem::forget(key);
    let owned = unsafe { Key::from_raw(raw.0) };

    let mut count = 0;

    unsafe {
        RegQueryInfoKeyW(
            HKEY(owned.as_raw()),
            PWSTR::null(),
            None,
            None,
            None,
            None,
            None,
            Some(&mut count),
            None,
            None,
            None,
            None,
        )
        .ok()?;
    };

    assert_eq!(count, 3);
    Ok(())
}
```
Maybe manage the key's drop manually is troublesome.Can I write code like this:
```rust
#[test]
fn windows_interop() -> Result<()> {
    use windows::{core::*, Win32::System::Registry::*};

    let test_key = "software\\windows-rs\\tests\\windows_interop";
    _ = CURRENT_USER.remove_tree(test_key);

    let key = CURRENT_USER.create(test_key)?;
    key.set_u32("1", 1)?;
    key.set_u32("2", 2)?;
    key.set_u32("3", 3)?;

    let mut count = 0;

    unsafe {
        RegQueryInfoKeyW(
            HKEY((&key).as_raw()), // If I need use key variable behind. And I only need use underlying handle here.
            PWSTR::null(),
            None,
            None,
            None,
            None,
            None,
            Some(&mut count),
            None,
            None,
            None,
            None,
        )
        .ok()?;
    };

    assert_eq!(count, 3);
    Ok(())
}
```

**Comment by kennykerr** [comment]
`forget` is used to test handle ownership transfer and is not needed for your scenario.

**Comment by amone-bit** [comment]
Thank you.
