### ISSUE TITLE
Bindgen skipping methods

### ISSUE THREAD

**Issue by NuSkooler** [microsoft/windows-rs#3265]
### Summary

Hi all, I'm continuing a conversation from [here](https://github.com/microsoft/com-rs/issues/216#issuecomment-2335864041) before it was recently archived.

I'm attempting to generate Rust bindings for COM RPC following the example from @riverar [here](https://github.com/riverar/washington-rs)

The problem I'm having now is most methods in my interface are skipped in the Rust generated code. The C# code however, looks quite reasonable. Especially odd at least to myself, is only a method named `BaseMethod` works, while anything else is skipped.

Any help greatly appreciated!

### Crate code

Working example:
```
import "wtypesbase.idl";

[
	uuid(6e3125bb-9df7-4c8c-976c-0b5626bc8194),
	version(1.0)
]
interface IBase {
	HRESULT BaseMethod(); // <-- present in all bindings
};
```

Non-working example:

```
import "wtypesbase.idl";

[
	uuid(6e3125bb-9df7-4c8c-976c-0b5626bc8194),
	version(1.0)
]
interface IBase {
	HRESULT OtherMethod(); // <-- not present in the rust generated bindings; it *is* in the .CS however
};
```

```rust
// build.rs
windows_bindgen::bindgen([
                "--in",
                ".windows/winmd/MyProject.Foo.winmd",
                "--out",
                "src/bindings.rs",
                "--filter",
                "MyProject.Foo",
            ])
            .unwrap();
```

**Comment by riverar** [comment]
@NuSkooler My last response from that thread.

Here's an RPC example:

base.idl:
```idl
import "wtypesbase.idl";

[
	uuid(6e3125bb-9df7-4c8c-976c-0b5626bc8194),
	version(1.0)
]
interface IBase {
	HRESULT BaseMethod();
};
```

libmappings.rsp (put next to the .proj file):
```
--with-librarypath
BaseMethod=base_client.dll
```

winmd output:
```csharp
// ...
[DllImport("base_client.dll", ExactSpelling = true, PreserveSig = false)]
public unsafe static extern HRESULT BaseMethod([In][Out] void* IDL_handle);
```

As shown above, you still have the responsibility of compiling the MIDL-generated client stubs (e.g. `base_c.c`) into a DLL you can call into. I chose base_client.dll as an example.

**Comment by NuSkooler** [comment]
@riverar Hi again!

I followed your example with the results described above. If I rename `BaseMethod` in your `base.idl`, to say `BaseMethodTwo`, it is not present in the .rs bindings generated. Same thing if I add any other methods not called `BaseMethod`; they are omitted.

**Comment by riverar** [comment]
@NuSkooler Did you subsequently update `libmappings.rsp` to map the names to a DLL?

```
--with-librarypath
BaseMethod=base_client.dll
BaseMethodTwo=base_client.dll
BaseMethodThree=base_client.dll
...
```

**Comment by NuSkooler** [comment]
> @NuSkooler Did you subsequently update `libmappings.rsp` to map the names to a DLL?
> 
> ```
> --with-librarypath
> BaseMethod=base_client.dll
> BaseMethodTwo=base_client.dll
> BaseMethodThree=base_client.dll
> ...
> ```

Big /facepalm for me! Thanks again with your responses and patience. They are now begin generated!

**Comment by NuSkooler** [comment]
Apologies for re-opening this -- I can create a new issue if needed. It appears I've been going down the wrong path. The above works for generating bindings to `base_client.dll`, however these methods aren't exported in any library or DLL. Instead, they are hosted in an executable managed by COM:

- `myproj.exe`: Hosts COM RPC server
- `myproj.dll` (equiv to `base_client.dll`): Calls *into* the COM RPC server

What I'd like to, is via Rust, also call into the COM server. C++ code generated looks something like this:

```cpp
HRESULT MyMethod( 
    handle_t hbind,
    /* [annotation][out] */ 
    _Out_  PCONTEXT *phContext)
{

    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall4(
                  ( PMIDL_STUB_DESC  )&MyService_StubDesc,
                  (PFORMAT_STRING) &MyService__MIDL_ProcFormatString.Format[0],
                  hbind,
                  phContext);
    return ( HRESULT  )_RetVal.Simple;   
}
```

Is it possible to instruct bindgen to create this type of Rust code for connecting to COM RPC services?
