### ISSUE TITLE
ReportEventW missing arguments

### ISSUE THREAD

**Issue by olsaMG** [microsoft/windows-rs#3280]
### Summary

Hello!

Im currently experimenting with the Rust windows crate.

I have a problem with the ReportEventW function, its returning the message: "The stub received bad data." and i cant figure out what ive done wrong.

Ive opened a question [here](https://learn.microsoft.com/en-us/answers/questions/2068067/rust-reporteventw-returns-the-stub-received-bad-da?page=1&orderby=Helpful&comment=answer-1828526#newest-answer-comment) and one of the answers suggested that there are missing arguments. In the [Win32 api docs](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-reporteventw) this function have 9 arguments but the Rust function only have 8.

Is this a bug or am i doing something wrong in my code?

Maybe there are a helpful soul here that can give me some pointers?

Thanks!

### Crate code

```Rust
fn write_event() -> ::windows_core::Result<()> {
    let eventsource: PCWSTR = w!("Application");
    let handle: HANDLE = unsafe { RegisterEventSourceW(None, eventsource)? };
    let message = w!("Test log");
    let message2 = w!("Test log2");
    let strings = &[message, message2];
    unsafe {
        ReportEventW(
            handle,
            EVENTLOG_INFORMATION_TYPE,
            0,
            1,
            None,
            strings.len() as u32,
            Some(strings),
            None,
        )?;
    }
    unsafe { DeregisterEventSource(handle)? };
    Ok(())
}
```

**Comment by robmikh** [comment]
The wNumStrings and lpStrings parameters are folded in as a single slice in the bindings. Your third to last parameter should be the data size and not the number of strings. I'd consult the binding docs: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/EventLog/fn.ReportEventW.html

**Comment by olsaMG** [comment]
> The wNumStrings and lpStrings parameters are folded in as a single slice in the bindings. Your third to last parameter should be the data size and not the number of strings. I'd consult the binding docs: https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/System/EventLog/fn.ReportEventW.html

Thank you! Been stuck here for a while :heart: 

The third to last parameter should have been dwDataSize and not wNumStrings. :facepalm: 

The correct code:
```Rust
fn write_event() -> ::windows_core::Result<()> {
    let eventsource: PCWSTR = w!("Application");
    let handle: HANDLE = unsafe { RegisterEventSourceW(None, eventsource)? };
    let message = w!("Test log");
    let message2 = w!("Test log2");
    let strings = &[message, message2];
    unsafe {
        ReportEventW(
            handle,
            EVENTLOG_INFORMATION_TYPE,
            0,
            1,
            None,
            0,
            Some(strings),
            None,
        )?;
    }
    unsafe { DeregisterEventSource(handle)? };
    Ok(())
}
```
