### ISSUE TITLE
Should raw-dylibs defined in windows-targets use import_name_type = "undecorated"?

### ISSUE THREAD

**Issue by glandium** [microsoft/windows-rs#3285]
### Summary

In a complex multi-language project, one may end up using both windows-target and the system libraries directly (that's the case of Firefox). When enabling windows-targets's support for raw-dylib, linking fails when using LLVM's lld-link (I haven't tried link.exe, it might actually work, but the result is probably suboptimal too). The cause for the link failure is possibly a bug in lld-link, but it is a manifestation of the fact that the fake import lib that rust creates with raw-dylib does not agree with the real system import lib, wrt symbol names: on 32-bits windows, the system import lib use the `__imp__sym@n` form, while the raw-dylib uses the `__imp_sym` form because of `import_name_type = "undecorated"`.

See https://github.com/llvm/llvm-project/issues/107371#issuecomment-2359947863 for more details.

Removing `import_name_type = "undecorated"` solves the problem.

**Comment by glandium** [comment]
I guess the discussion on the LLVM side points to the problem being on the rust side of raw-dylib.

**Comment by kennykerr** [comment]
@dpaoliello thoughts?

**Comment by kennykerr** [comment]
Anyone know how we might add this...

https://github.com/microsoft/windows-rs/blob/ff6f56df6c9d727c348b3c4cd6d45db59f76fa1b/.github/workflows/raw_dylib.yml#L12-L13

...to a yml strategy/matrix so I can more easily run `raw-dylib` tests across the board? Happy to expand test coverage if there's a gap here.

**Comment by ChrisDenton** [comment]
I did check with `1.71` and it has the same behaviour.

**Comment by kennykerr** [comment]
#3287 passed meaning we have the same testing for `raw-dylib` as non-`raw-dylib`.

**Comment by kennykerr** [comment]
Happy to test rust-lld / lld-link if someone can point me to how that is done. 

I see its enabled by default on Linux but not Windows. Anyone know why?

https://blog.rust-lang.org/2024/05/17/enabling-rust-lld-on-linux.html

**Comment by ChrisDenton** [comment]
There have been compatibility issues in the past. I'm not exactly sure where we are at now but it seems https://github.com/rust-lang/rust/issues/111480 is still open (though might just be that nobody has tested it recently).

**Comment by ChrisDenton** [comment]
> Happy to test rust-lld / lld-link if someone can point me to how that is done.

You can put this in `config.toml`:

```rust
[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
```

Or maybe use RUSTFLAGS with `-C linker=rust-lld`

**Comment by kennykerr** [comment]
Thanks, I've tested this and it seems to work fine.

**Comment by dpaoliello** [comment]
Seems like it's the same issue as <https://github.com/rust-lang/rust/issues/124958>

Essentially, we should be setting `symbol_name` to the decorated name when creating the [`COFFShortExport`](https://docs.rs/ar_archive_writer/latest/ar_archive_writer/struct.COFFShortExport.html), that way the import has both the decorated and undecorated name and should match the real import library.

**Comment by kennykerr** [comment]
> There have been compatibility issues in the past. I'm not exactly sure where we are at now but it seems [rust-lang/rust#111480](https://github.com/rust-lang/rust/issues/111480) is still open (though might just be that nobody has tested it recently).

I also ran `rust-lld` through the windows-rs build gauntlet and everything looks good. #3288

**Comment by glandium** [comment]
I've tried with a tiny testcase, and it seems the side effects of the rust raw-dylib shortcoming is only really visible with `crate-type = ["staticlib"]`, so it's not all that surprising that you don't see failures.

**Comment by kennykerr** [comment]
Well it sounds like this is unrelated to windows-rs so I'm closing this issue.
