### ISSUE TITLE
Is there a GET_XBUTTON_WPARAM macro?

### ISSUE THREAD

**Issue by fanchenio** [microsoft/windows-rs#3290]
### Suggestion

 need to know if clicking the side mouse button is 1 or 2.

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-get_xbutton_wparam

**Comment by tim-weis** [comment]
C preprocessor macros aren't available through the Rust bindings for the Windows SDK (see [Where's my favorite macro from the Windows SDK?](https://kennykerr.ca/rust-getting-started/where-are-the-macros.html#wheres-my-favorite-macro-from-the-windows-sdk) for details).
