### ISSUE TITLE
windows-bindgen release 0.60 request

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/windows-rs#3298]
### Suggestion

Hi,

Previously, I've requested a 0.60 release here: #3232 We've decided back then that it wasn't necessary.

Since then, issue #3242 has been addressed, and a new [0.60 release](https://github.com/microsoft/windows-rs/releases/tag/0.60.0) has been published.

I would like to request a 0.60 release of the `windows-bindgen` crate now (and probably the `windows` crate as well, because it's generated by the newer `bindgen`) since the new release has happened, to incorporate the changes made for #3242.

Thank you!

**Comment by kennykerr** [comment]
Thanks for the official request - I only publish crates as needed to avoid the proliferation of versions. Are you ready for production, tested against the repo?

**Comment by Alovchin91** [comment]
Thank you for such a quick reply! I’ve tested against an earlier version, but my project is extremely small so I can’t say it’s “production” grade. If it’s too much work or for any other reason is an issue, I guess I could say it’s not a big deal for now. It would be important when new win32metadata is released though.

**Comment by kennykerr** [comment]
No problem - ping me when you're back in the office and we can figure something out. Enjoy your vacation!
