### ISSUE TITLE
`windows-bindgen` output ordering

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#3303]
I'm busy revamping `windows-bindgen` to deal with a number of issues and make it a lot more flexible. 

One potential issue is whether we still need to sort function declarations by exporting library to avoid Rust compiler inefficiencies.  

@ChrisDenton do you happen to know if that's still an issue with `raw-dylib`? 

I'll probably still need to support some version of this for `windows-sys` generation, at least for now.

**Comment by ChrisDenton** [comment]
It's not an issue with `raw-dylib`, fortunately.

**Comment by kennykerr** [comment]
That is wonky. 🙂

Hopefully https://github.com/rust-lang/rust/pull/129821 will complete soon and we can get rid of all of this.
