### ISSUE TITLE
Link `windows-core` crate docs from your self-made `windows` crate docs landing page

### ISSUE THREAD

**Issue by Enyium** [microsoft/windows-rs#3308]
### Suggestion

Following #3306, <https://microsoft.github.io/windows-docs-rs/> should provide a link to either <https://crates.io/crates/windows_core> or <https://docs.rs/windows-core>. This could, e.g., be done with the following HTML in your Markdown document:

```md
# Re-exports

<pre>
pub use <a href="https://docs.rs/windows-core">windows_core</a> as core;
</pre>
```

Rendered preview:

# Re-exports

<pre>
pub use <a href="https://docs.rs/windows-core">windows_core</a> as core;
</pre>

**Comment by kennykerr** [comment]
I think this link is omitted because `--no-deps` is used to generate the `windows` docs in an attempt to reduce the bloat produced by `rustdoc` but perhaps that can be revisited.

**Comment by kennykerr** [comment]
Closing for now as there's no immediate action we can take - feel free to keep the conversation going. Thanks for the feedback!
