### ISSUE TITLE
`no_std` support for `windows-rs`

### ISSUE THREAD

**Issue by sagacity** [microsoft/windows-rs#3315]
### Suggestion

I am working in an environment in which I am quite executable size constrained, but I'd still like to use Direct3D11 in order to perform some rendering tasks. Since `windows-sys` has no support for this, I am currently using the `winapi` crate to fill in support for the relevant D3D COM classes I'm using. However, `winapi` has been unmaintained for three years after `windows-rs` ate its lunch :)

I've tried using `windows-bindgen` to generate bindings and patching them up manually, but I couldn't get the generated code to compile properly (after changing things like `std::ptr::null_mut` to `core::ptr::null_mut` and so on). Could this be a more or less valid path to take, though?

What is a good way forward, generally? I wouldn't mind using bindings that are generated by using a manual bindgen step, but ideally I'd just use the `windows` crate since that would also make all other non-COM code simpler and there wouldn't be a manual bindgen step.

(btw, I realize this issue has been brought up before, so feel free to close if this cannot be realized, but I'd like some guidance on how to avoid depending on an unmaintained crate)

**Comment by kennykerr** [comment]
Good is, the `windows` crate can now be compiled with `no_std`. #3047

Just make sure to specify `default-features = false` as this test illustrates:

https://github.com/microsoft/windows-rs/tree/master/crates/tests/misc/no_std

**Comment by sagacity** [comment]
Fair enough! I'd be happy to take a stab at it since most of it is mechanical conversion, but since testing is indeed difficult I'm not sure I'd end up accidentally breaking stuff.
