### ISSUE TITLE
`windows` crate release request

### ISSUE THREAD

**Issue by Adrien-Bodineau** [microsoft/windows-rs#3316]
### Summary

Hello,

When will the 0.60.0 be available on crates.io ?

**Comment by Adrien-Bodineau** [comment]
Ho sorry, I was talking about the `windows` crate

**Comment by kennykerr** [comment]
Thanks, have you tested against the `windows` crate in the repo? Just making sure you're ready for production and there aren't any other issues you may encounter since the last release.

**Comment by Adrien-Bodineau** [comment]
I did not, thus my question about how long would it take for it to be released (currently last version is 0.58.0). But if you tell me that `windows` will not have a release until a few month (for example) I am fine with it too ^^ I am just looking forward for some API changes to make them more safe and more rusty :)

I would also like to thank you and the team for all the efforts put into this :)

**Comment by kennykerr** [comment]
Appreciate it. There will likely be a release coming up soon as there have been a few requests for different things, but I otherwise don't release unless there's a specific need to do so.

**Comment by riverar** [comment]
Recommend testing your crate(s) against `master` to avoid any unforeseen issues at next release.

```toml
# Cargo.toml
[dependencies.windows]
git = "https://github.com/microsoft/windows-rs"
branch = "master"
```

**Comment by kennykerr** [comment]
Closing for now - can reopen if there's a need for another release.
