### ISSUE TITLE
COM interface binding generation fails with HWNDs

### ISSUE THREAD

**Issue by talagrand** [microsoft/windows-rs#3325]
### Summary

This is a regression sometime between 0.48 and 0.58.

Given the following IDL file, compiled with midl + generated winmd, creating Rust bindings fails because the bindings refer to the HWND and HANDLE types which have not been imported or defined.

```
import "objidl.idl";

[ object, uuid(12345661-1223-1232-2233-134344444444), pointer_default(unique) ]
interface IAmAnInterface : IUnknown
{
    HRESULT PopWindow([in, unique] HWND parentWindow);
}
```

A minimal repro is attached. It requires nuget.exe in the path, available from nuget.org, and dotnet.exe (v.8) as well.

[mydk.zip](https://github.com/user-attachments/files/17381449/mydk.zip)

**Comment by kennykerr** [comment]
Please attach the .winmd for the repro.

**Comment by talagrand** [comment]
Attached
[Stuff.Mydk.zip](https://github.com/user-attachments/files/17381630/Stuff.Mydk.zip)

**Comment by kennykerr** [comment]
Thanks, I believe I have this fixed in a working branch but I'll confirm with this repro.

**Comment by kennykerr** [comment]
Ah, I see the repro attempts to generate everything (neat!) but seems to assume that `nuget.exe` is available in the path, which is not the case on my dev box.

**Comment by kennykerr** [comment]
OK, found `nuget.exe` and can confirm the bindings are missing some external references. I think it should work if you remove this:

```rust
"--config",
"flatten",
```

Not sure why you're using those options but "flatten" doesn't quite do what it says - I've already fixed this in a development branch but will need a bit more time to stabilize. #3245

**Comment by kennykerr** [comment]
Sorry for the delay - I've been heads down on a major update to `windows-bindgen`. 😊

**Comment by talagrand** [comment]
Thanks! I was able to migrate with this tip. I can't remember why I'd chosen flatten, maybe a misguided attempt to keep things simple.
