### ISSUE TITLE
On a potential `CONTRIBUTING.md`...

### ISSUE THREAD

**Issue by onkoe** [microsoft/windows-rs#3326]
### Suggestion

Hi there! I'm developing a library using some of the `windows` crate's bindings, and I'd love to add some documentation comments to better clarify their usage. (I was also considering a higher-level API, but maybe that's worth my own crate!)

That said, I wasn't able to find a `CONTRIBUTING.md`/similar. Is there any existing policy on external contributions? (Are they accepted at all?)

Even if my contributions aren't helpful here, I believe having such a file would be invaluable for future participants. Thank you for maintaining this useful crate! :)

**Comment by kennykerr** [comment]
The doc is here: https://github.com/microsoft/windows-rs/blob/master/docs/contributing.md

And there are plenty of contributors: https://github.com/microsoft/windows-rs/graphs/contributors

I just ask you open an issue to discuss any potential contribution before investing in any substantial work. This project has a pretty tight focus and that may not be directly obvious if you're new to windows-rs, an issue will let us discuss that and make known any misconceptions or potential features that are out of scope. 

Thanks for your interest!
