### ISSUE TITLE
Trait `IContextMenu_Impl` not exist

### ISSUE THREAD

**Issue by ajaykumargdr** [microsoft/windows-rs#3327]
### Summary

We are not able to import the trait `windows::Win32::UI::Shell::IContextMenu_Impl` which is shown in the crates.io document. We tried older versions like `0.51.0` and `0.43.0` but in none of the versions we are able to import the `IContextMenu_Impl` trait. 

### Crate manifest

[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_Com",
    "UI",
    "UI_Shell",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging"
]

### Crate code

use windows::Win32::UI::Shell::IContextMenu_Impl;

**Comment by kennykerr** [comment]
You're missing the "implement" feature.

https://kennykerr.ca/rust-getting-started/how-to-implement-com-interface.html

**Comment by ajaykumargdr** [comment]
We were able to successfully import the trait after enabling the `implement` feature as suggested. Thank you for the quick response.
