### ISSUE TITLE
Provide a Changelog

### ISSUE THREAD

**Issue by konstin** [microsoft/windows-rs#3334]
### Suggestion

The update of windows-registry to 0.3.0 had multiple breaking changes (https://github.com/astral-sh/uv/actions/runs/11590087174/job/32266949119?pr=7796), but I can't find any overview over the breaking changed and how to migrate apart from the all-crate commit list. Could each crate provide a changelog, specifically with the breaking changes highlighted?

**Comment by kennykerr** [comment]
Thanks for the feedback. We have release notes here:

https://github.com/microsoft/windows-rs/releases

There you can see, for example, a few changes related to registry support.

**Comment by konstin** [comment]
I have read that changelog, there seemed to be a lot of internal changes listed, but i e.g. didn't see the `Value` enum being converted to a struct with private fields being mentioned, which was the one breaking change we observed.

**Comment by kennykerr** [comment]
That would be #3184.
