### ISSUE TITLE
Projects using windows crate as dependency are failing to build

### ISSUE THREAD

**Issue by ZephyrSquall** [microsoft/windows-rs#3336]
### Summary

I'm trying to compile Bevy on Windows, and I've been facing a problem that I've narrowed down to this dependency. When I run `cargo build` to compile a project that uses this windows crate as a dependency, the compilation will simply stop partway, with no error message, exit message, or any other message. All I see is the console logs from the last moment `cargo build` was running. It looks as though I pressed Ctrl+C while it was compiling to stop it, but I didn't actually press those keys.

I've reproduced the issue in a new project (a standard "hello world" project from `cargo new`) whose only change is adding the windows crate as a dependency. I've tested both 0.52.0 (the version Bevy currently uses) and 0.58.0 (the latest version), and neither have worked.

I've kept a close eye on my memory usage and notice no spikes or any other suspicious patterns, so I'm doubtful this is due to running out of RAM. I've tested with the latest version of Rust, both on stable and nightly, on the `stable-x86_64-pc-windows-msvc` and `nightly-x86_64-pc-windows-msvc` toolchains. I've tested in the normal Windows command prompt, Powershell, and Git Bash. Nothing I've tried seems to have any effect on the outcome of `cargo build`, in every scenario it tries to compile and then suddenly stops when it gets to the windows crate.

The only thing I've noticed that seems odd is that if I run `cargo build --verbose`, the last line before it stops is an absurdly long command. I've attached the console output I get when I run this command, for both the 0.52.0 and 0.58.0 versions, in case it contains any useful information.

Any idea what's causing this problem?

[cargo build verbose logs 0.52.0.txt](https://github.com/user-attachments/files/17603013/cargo.build.verbose.logs.0.52.0.txt)
[cargo build verbose logs 0.58.0.txt](https://github.com/user-attachments/files/17603012/cargo.build.verbose.logs.0.58.0.txt)

### Crate manifest

[package]
name = "dependency_test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = "0.58.0" # or windows = "0.52.0"

**Comment by riverar** [comment]
Does this machine have anti-malware or related system software that could be interfering here perhaps? Have you tried another machine?

**Comment by ZephyrSquall** [comment]
It was indeed my anti-malware causing the problem. I have Trend Micro installed on this machine, and when I tried disabling it, my projects using this windows crate now successfully compile. Thanks!
