### ISSUE TITLE
Is `impl From<IDispatch> for VARIANT` sound?

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#3337]
This `impl` creates a second copy of the `IDispatch` pointer, leaving two `Drop` implementations behind (`IDispatch`'s and `VARIANT`'s):

https://github.com/microsoft/windows-rs/blob/a8e14c75581bb89fc244ad480f98567be972aea2/crates/libs/windows/src/extensions/Win32/System/Variant.rs#L254-L264

Unless I'm missing something, this looks like a double-free. What am I overlooking here?

**Comment by kennykerr** [comment]
> second copy of the IDispatch pointer

What second pointer are you referring to? The `value` argument is moved into the `from` function and then transmuted into the `VARIANT` field. At this point the returned `VARIANT` owns the `IDispatch` reference.

**Comment by tim-weis** [comment]
> The `value` argument is moved \[...\] and then transmuted

Oh, [`transmute`](https://doc.rust-lang.org/stable/core/mem/fn.transmute.html)

> \[...\] then forgets the original.

I wasn't aware of this. That makes sense, thanks for having a look.
