### ISSUE TITLE
mut static hard error early 2025

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#3338]
### Suggestion

@kennykerr This is a Rust thing rather than a windows crate thing Kenny. However, it might be useful to add/amend a sample that shows the use of Box to solve this.

**Comment by kennykerr** [comment]
Please provide a minimal repro as I don't know what you're talking about.

**Comment by MRahilly** [comment]
An example, that I intend to add here on Monday, has a static mut struct instance in a WndProc that is recently generating warnings (I think) ahead of the finalized version of Rust 2024 when (~Feb 2025) it could become an error requring the boxing of the struct object on the heap.

**Comment by ChrisDenton** [comment]
Are you talking about the [`static_mut_refs`](https://doc.rust-lang.org/nightly/edition-guide/rust-2024/static-mut-references.html#summary) lint becoming an error? As the error suggests, if you just want a drop-in replacement then any `&mut VAR` can be a `&raw mut VAR` instead. Similarly `&VAR` can be turned into `&raw const VAR`. The `&raw` syntax creates pointers without going through references, effectively disabling some optimizations that can cause UB even in single threaded applications. But in any case globally shared mutable state is wildly unsafe unless there's some form of synchronization (e.g. atomics, `OnceLock`, `Mutex`, etc). That's true if the memory is in a static, on the heap or anywhere else.

**Comment by MRahilly** [comment]
Yes, that lint is what I was talking about. Many thanks for the &raw suggestion.
