### ISSUE TITLE
FormatMessageW not found

### ISSUE THREAD

**Issue by vitoway** [microsoft/windows-rs#3355]
### Suggestion

Currently, the FormatMessageW function cannot be used directly, it can only be linked through windows_targets.
https://github.com/microsoft/windows-rs/blob/d41381de6f3b10f008b30d81e35f046124ccb75d/crates/libs/result/src/bindings.rs#L9
https://github.com/microsoft/windows-rs/blob/d41381de6f3b10f008b30d81e35f046124ccb75d/crates/libs/result/src/hresult.rs#L89
I wonder if this function will be provided later?

**Comment by riverar** [comment]
Did you add the Win32_System_Diagnostics_Debug feature?

**Comment by vitoway** [comment]
https://github.com/microsoft/windows-rs/blob/d41381de6f3b10f008b30d81e35f046124ccb75d/crates/libs/sys/src/Windows/Win32/System/Diagnostics/Debug/mod.rs#L55
This is the result of the github search interface, which is not the latest file at all. This led to my question. Thank you for your answer.
