### ISSUE TITLE
How can implementation structs with fields be initialized externally?

### ISSUE THREAD

**Issue by Dry-Leaf** [microsoft/windows-rs#3362]
### Suggestion

I want to implement the IInitializeWithStream and IPropertyStore interfaces. The outline of what I have so far:

```rust
#[implement(IInitializeWithStream,IPropertyStore)]
#[derive(Default)]
pub struct PropertyHandler {
   orig_ps: RefCell<Option<IPropertyStore>>,
}

impl IInitializeWithStream_Impl for PropertyHandler_Impl {
...
}

impl IPropertyStore_Impl for PropertyHandler_Impl {
...
}
``` 

In IInitializeWithStream_Impl, the orig_ps field is given the value of a created IPropertyStore. This field is accessed in IPropertyStore_Impl. After compiling this into a DLL, can PropertyHandler be initialized externally? Am I missing something necessary, like a `new` constructor for PropertyHandler?

I haven't found anything in documentation, like [https://kennykerr.ca/index.html](https://kennykerr.ca/index.html) that would address this scenario.

**Comment by riverar** [comment]
In a typical COM scenario, you would expose a _class factory_ (`IClassFactory`) via (exported function) `DllGetClassObject`, allowing external clients to create instances of your object. The class factory would be responsible for properly initializing the object. But there may be other scenarios that require different activation strategy.

See also: https://github.com/microsoft/windows-rs/blob/master/crates/tests/misc/implement/tests/class_factory.rs

This question is better suited for Microsoft Q&A (https://learn.microsoft.com/en-us/answers/tags/224/windows-api-win32) or the Rust community on StackOverflow (https://stackoverflow.com/questions/tagged/rust).

I'll close this issue as there's no crate work needed but feel free to continue the discussion.
