### ISSUE TITLE
Recommend users to enable `windows/docs` feature when building their crate for docs.rs

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#3380]
### Suggestion

Our intradoc links into the `windows` crate don't seem to resolve on for example https://docs.rs/gpu-allocator/0.27.0/x86_64-pc-windows-msvc/gpu_allocator/d3d12/struct.Allocation.html. While I'm not exactly confident that these links are very useful, it would be nice if they resolved.

With some debugging it turns out `rustdoc` omits these links because it knows they are being `hidden`:

https://github.com/microsoft/windows-rs/blob/f8124e8402e34a9081f15be5b923e70cdea0ae21/crates/libs/windows/src/lib.rs#L12

As such, I managed to make the links resolve again locally by building with `cargo doc (--no-deps) -F windows/docs`

Side-note: I thought that `cargo doc --no-deps` would use the `documentation` URL from `Cargo.toml` for target crates, but they are ignored [^1] unless I explicitly tell `rustdoc` where to find the `windows` crate with `RUSTDOCFLAGS="-Zunstable-options --extern-html-root-url=windows=https://microsoft.github.io/windows-docs-rs/doc/" cargo +nightly doc --no-deps`.

[^1]: This appears to be a known limitation described in https://rust-lang.github.io/rfcs/1946-intra-rustdoc-links.html#linking-to-external-documentation.

---

In the end, to solve this when building our crate for docs.rs, I think the following should suffice in our `Cargo.toml`:

```toml
[package.metadata.docs.rs]
features = ["windows/docs"]
```

**Comment by kennykerr** [comment]
Thanks for sharing!

**Comment by MarijnS95** [comment]
Is this something we should document in the readme, the library docs, or some other place where the `docs` feature is described?

**Comment by MarijnS95** [comment]
I'd like for folks to preempt this but it's an obscure feature.

Is this only done because docs.rs builds with all features are slow? In that case you might want to flip the `cfg` so that the docs are only hidden when building for docs.rs (there should be a chapter about detecting docs.rs builds) but not when built locally (assuming folks either pass `--no-deps` or enable a limited set of `windows` crate features anyway). What do you think?

**Comment by kennykerr** [comment]
Issue: #2665
PR: #2676

**Comment by MarijnS95** [comment]
@kennykerr okay, so this used to be a "feature" request for `windows-sys` but it was transitively applied to `windows` as well. Despite the `windows` crate already being guarded by per-module feature flags (hopefully making this less of an issue, but there's a lot more code).

If it's not because of docs.rs but because of local builds being slow, that is unfortunate and breaking local doc builds if users forget to turn on the non-default `docs` feature.

---

Note that your second link doesn't work but it appears to be intended to link to the homepage of this repository.
