### ISSUE TITLE
Implement Sync + Send for HWND

### ISSUE THREAD

**Issue by Ciantic** [microsoft/windows-rs#3399]
### Suggestion

HWND used to be a wrapper of `isize`, like `HWND(pub isize)`, this meant it _was_ also Send+Sync.

Now that HWND is:

```
pub struct HWND(pub *mut core::ffi::c_void);
```

It means it's not automatically Sync + Send. I don't see why it couldn't be Sync+Send because HWNDs are single-use values, and multiple threads and processes already use them.

My suggestion is to do this:

```
unsafe impl Sync for HWND {}
unsafe impl Send for HWND {}
```

Maybe for other handles as well?

**Comment by tim-weis** [comment]
This has been discussed in #3169. In a nutshell, handles are used in too many different ways to mark them all as `Send` and `Sync`. As an example, [`DestroyWindow`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-destroywindow) cannot be called from a thread other than the window's owning thread.
