### ISSUE TITLE
windows 0.60 tag in github, but not in crates.io

### ISSUE THREAD

**Issue by getong** [microsoft/windows-rs#3400]
### Summary

crates.io, windows v0.58, windows-sys v0.59.0
0.60 not found in crates.io

### Crate manifest

```TOML

```

### Crate code

```Rust

```

**Comment by tim-weis** [comment]
The `windows` crate has grown into an entire family of crates, and not every crate receives an update for a new release. The [Releases](https://github.com/microsoft/windows-rs/releases) page documents which crates are affected by each release. Neither 0.60 nor 0.59 updated the `windows` crate and 0.58 is the latest release.
