### ISSUE TITLE
During install, a failure part way through save for a dependency will cause that dependency to be skipped on retry

### ISSUE THREAD

**Issue by danielframpton** [microsoft/windows-rs#348]
I ran into this issue when I had access denied due to #347, but was surprised to see `cargo winrt install` appear to succeed on a second attempt, but skip over trying to make the symlink.

I believe the cause of this is that (when not forcing) we filter by `d.already_saved`, which only checks `Ok(self.directory_path()?.exists())` and not anything downstream of that.

**Comment by rylev** [comment]
This is no longer an issue as the dedicated tool is no longer used.
