### ISSUE TITLE
Error message when module not found is very unhelpful 

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#395]
The error message when a module is not found is not very helpful:

```
error: Module not found
  --> bindings\build.rs:3:25
   |
3  |           windows::mynamespace::{
   |  _________________________^
4  | |             Foo,
5  | |             Bar,
6  | |             Baz,
...  |
40 | |             Qux
41 | |         }
   | |_________^
```

The issue is that the `windows::mynamespace` module itself is missing. The error span should point to that path instead of all the types being imported.

**Comment by kennykerr** [comment]
This should be fixed as of #773 - let me know if you notice any further issues.
