### ISSUE TITLE
Panic when trying to generate non-existing type

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#396]
The error message when trying to generate a type that does not exist is less than ideal:

```
error: proc macro panicked
  --> bindings\build.rs:2:5
   |
2  | /     winrt::build!(
3  | |         windows::foo::{
4  | |             NoExist,
5  | |             Bar,
...  |
41 | |         }
42 | |     );
   | |______^
   |
   = help: message: Could not find type `Windows.Foo.NoExist"
```

Note that in a long list of types, if the non-existing type is not one of the first few, it won't even show in the error message span.

**Comment by sladyn98** [comment]
@kennykerr @rylev I would like to take a shot at this issue. IIUC we need to make the error message more helpful. Is one solution here improving the error message ?

**Comment by kennykerr** [comment]
Thanks for you willingness to help! Yes, the error message could be improved, but more importantly the span that indicates *where* the error occurred needs to be corrected to be the exact sequence of characters that caused the error. Whether it is is a missing module or a missing type, the macro should pinpoint and underline the offending entry.
