### ISSUE TITLE
I've got a simple Visual Layer demo

### ISSUE THREAD

**Issue by Josh015** [microsoft/windows-rs#410]
Not sure if this is useful to you guys, but I have a repo called [hello-composition-rs](https://github.com/Josh015/hello-composition-rs) where I've ported the [Using the Visual Layer with Windows Forms](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-visual-layer-with-windows-forms) example from C# to Rust. The code is really small, so I figured it might be handy to give people a quick example of WinRT in Rust.

**Comment by kennykerr** [comment]
Looks good! That's essentially the same as the Minesweeper sample that I've been using to validate the bindings.

https://github.com/robmikh/minesweeper-rs
