### ISSUE TITLE
Add support for C-style unions

### ISSUE THREAD

**Issue by iainnicol** [microsoft/windows-rs#417]
You might well be aware of this, internally, already. But the type `win32::automation::VARIANT` is not generated correctly.

I think it ends up, in Rust, as a struct containing just a bool called anonymous. Instead, it's an enum of sorts, with some weird named half-anonymous fields.

**Comment by kennykerr** [comment]
Thanks Iain, the metadata and code generation for Win32 is still very experimental and there are various edge cases that aren't yet handled correctly. Structs with C-style unions in particular will take a while to sort out.

**Comment by iainnicol** [comment]
Fair enough! I was just 'jumping the gun' with excitement.

On the off chance you have the time to explain, I'd find it really interesting how you created the win32 metadata.

**Comment by kennykerr** [comment]
Another good example to test is `D3D11_RENDER_TARGET_VIEW_DESC`.

**Comment by kennykerr** [comment]
> On the off chance you have the time to explain, I'd find it really interesting how you created the win32 metadata.

The metadata for Win32 APIs comes from this project: https://github.com/microsoft/win32metadata

**Comment by iainnicol** [comment]
Ah, thanks. I found that via today's blog that you linked earlier.

**Comment by valarauca** [comment]
Apologies to dogpile onto this request, but I hit this issue today as well.

I was (attempting) to write a basic wrapper around metadata handles (`propsys.h` stuff), and the fact the [`PROPVARAINT`](https://docs.microsoft.com/en-us/windows/win32/api/propidlbase/ns-propidlbase-propvariant) who's API expects you'll be able to inspect its tag & fields is represented by an opaque `struct` makes a lot of interactions with the metadata/properties API painful to impossible.

**Comment by kennykerr** [comment]
Got it, I'm going to get to this very soon. I know this is important for many scenarios.

**Comment by kennykerr** [comment]
OK, starting to work on this!

**Comment by kennykerr** [comment]
Types for testing:

- Windows.Win32.WindowsColorSystem.WhitePoint
- Windows.Win32.Automation.VARIANT
- Windows.Win32.Direct3D11.D3D11_RENDER_TARGET_VIEW_DESC
- Windows.Win32.DisplayDevices.DISPLAYCONFIG_VIDEO_SIGNAL_INFO
- Windows.Win32.StructuredStorage.PROPVARIANT
- Windows.Win32.SystemServices.OVERLAPPED

**Comment by nathanvoglsam** [comment]
I would also recommend having `Windows.Win32.Direct3D12.D3D12_INDIRECT_ARGUMENT_DESC` as a test case.

The c definition is
```c
typedef struct D3D12_INDIRECT_ARGUMENT_DESC {
  D3D12_INDIRECT_ARGUMENT_TYPE Type;
  union {
    struct {
      UINT Slot;
    } VertexBuffer;
    struct {
      UINT RootParameterIndex;
      UINT DestOffsetIn32BitValues;
      UINT Num32BitValuesToSet;
    } Constant;
    struct {
      UINT RootParameterIndex;
    } ConstantBufferView;
    struct {
      UINT RootParameterIndex;
    } ShaderResourceView;
    struct {
      UINT RootParameterIndex;
    } UnorderedAccessView;
  };
} D3D12_INDIRECT_ARGUMENT_DESC;
```

This struct has multiple layers of nested types and is currently panicking on the `struct-constants` branch. It fails to find all types that are defined by the anonymous union in `D3D12_INDIRECT_ARGUMENT_DESC`, only finding the type for the `VertexBuffer` anonymous struct. The panic gets triggerd in `Type::read_from_blob` from `TypeKind::Struct(nested[def.name().1].name.clone())`

**Comment by kennykerr** [comment]
Yes I figured out how to get all the nested types. 😊

**Comment by kennykerr** [comment]
Sorry for the delay. The Win32 metadata has necessitated a pretty significant overhaul of the code generation. I'm busy wrapping that up - it should address a number of the open issues including support for unions.

**Comment by kennykerr** [comment]
Wow, that was a lot of work. The good news is that unions are working! 

https://github.com/microsoft/windows-rs/tree/winmd/tests/unions/tests

I have some testing before I can open a PR but it's looking good.

**Comment by iainnicol** [comment]
This is super exciting, Kenny. Thanks for your hard work!

You can tell from the emoji responses, that I am far from the only person looming forward to this.

**Comment by agausmann** [comment]
I checked out the winmd branch this weekend and noticed that the fields in unions are generated with the private `_abi` types instead of the public types. For example, `PROPVARIANT_0` is defined with the field `anonymous: PROPVARIANT_0_0_abi` instead of `anonymous: PROPVARIANT_0_0`, which makes it unusable. Don't know if that has been fixed since, but I wanted to bring it to your attention. 
![image](https://user-images.githubusercontent.com/6611767/110372744-475e5d80-8014-11eb-879e-b9df82ab5dcd.png)

**Comment by kennykerr** [comment]
It depends on whether the union is blittable. Rust doesn't support unions containing fields that need to be dropped. It doesn't affect unions where the fields don't need to be dropped. Those will just refer to the types directly. I'm still exploring options for dealing with this more naturally.

**Comment by kennykerr** [comment]
It may be as simple as wrapping those fields with `std::mem::ManuallyDrop` - I just need to test this to see what issues that may introduce.

**Comment by kennykerr** [comment]
Unions are now supported as of #577 - I'll leave this issue open until I come to some conclusion on unions with fields that should be dropped.

**Comment by kennykerr** [comment]
Here's an example of using OVERLAPPED: 

https://github.com/microsoft/windows-rs/tree/master/examples/overlapped

**Comment by valarauca** [comment]
`PROPVARIANT` is still unusable after these changes. Some fields appear to not exist. For example `IVal` and `uIVal` are [documented here](https://docs.microsoft.com/en-us/previous-versions/aa912007(v=msdn.10)), but don't appear in the generated output.

**Comment by kennykerr** [comment]
`PROPVARIANT` is tricky because it is a union of non-trivially destructible members, which isn't something Rust readily supports. The bindings will however generate `PROPVARIANT_0_0_0` with the right fields but it isn't particularly easy to use.

**Comment by valarauca** [comment]
Yes apologies, I deleted my comment because I was on the wrong level on Anonymous field.
