### ISSUE TITLE
Whenever Kenny Kerr goes silent for a bit...

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#419]
... things are happening.

This is ***awesome*** news! Though I have a few questions: Where does *windows-rs* fit in in terms of the classic Windows API? Specific questions I have:

* Is it a replacement for the raw [winapi crate](https://crates.io/crates/winapi) only?
* Does it go beyond that and provide facilities like the [WIL](https://github.com/microsoft/wil)?
* Or is it even higher level, like a sane MFC/ATL/WTL?

And, of course, like [every one else](https://github.com/microsoft/windows-rs/issues/417#issuecomment-763880184), where does win32.winmd come from?

**Comment by kennykerr** [comment]
Thanks Tim,

> Is it a replacement for the raw winapi crate only?

Yes, I would expect the `windows` crate to gradually replace the `winapi` crate. There may be gaps in API coverage, but we're working hard to get everything covered and work out any kinks. 

> Does it go beyond that and provide facilities like the WIL?

There are basic helpers for things like string and error handling, but I would expect the Rust community to continue developing specific and focused crates for various tasks. Think of the `windows` crate as a foundation building block for more specific or targeted crates that provide richer helpers like those provided by WIL.

> Or is it even higher level, like a sane MFC/ATL/WTL?

The `windows` crate makes the Windows API available to Rust developers. Some APIs, like those based on WinRT, will have rich Rust bindings that don't need any wrappers to make them useful and safe in Rust. Other APIs, like those based on C-style functions often called Win32 APIs, will likely benefit from being wrapped in specific crates to provide a more idiomatic experience in Rust.

> And, of course, like every one else, where does win32.winmd come from?

The metadata for Win32 APIs comes from this project: https://github.com/microsoft/win32metadata

**Comment by rylev** [comment]
Closing as the questions are answered. We're tracking that these questions should be answered in some sort of FAQ in issue #460.
