### ISSUE TITLE
Support loading dll at runtime

### ISSUE THREAD

**Issue by roblabla** [microsoft/windows-rs#421]
Sorry if this is out of scope, but it's a cool idea I had: It'd be nice if windows-rs provided a way to generate stubs that load the dlls at runtime and call the function indirectly (using LoadLibraryEx/GetProcAddress), returning an error if the function does not exist.

This would provide an easy way to target older versions of Windows. I imagine the API would look similar to what [`windows-dll`](https://github.com/thisKai/rust-windows-dll#usage) provides.

**Comment by thisKai** [comment]
I plan to add an option to use this crate in windows-dll under the hood at some point, I'm not sure how much if any extra work it would be to generate windows-rs compatible function signatures though.

**Comment by kennykerr** [comment]
Thanks for the suggestion @roblabla! We could certainly add an option to generate delay load wrappers, perhaps as an option in the `build` macro for all or select functions.

**Comment by l0calh05t** [comment]
Would love to see this too. It even seems `windows-rs` already does this internally for some functions using the `demand_load!` macro.

For performance reasons, I think it would make sense to have it limited to a selected set of functions. Does https://github.com/microsoft/win32metadata also include data on the Windows version in which the corresponding API was introduced? If so, this could potentially be done automatically using a minimum version parameter.

**Comment by l0calh05t** [comment]
> Does https://github.com/microsoft/win32metadata also include data on the Windows version in which the corresponding API was introduced? If so, this could potentially be done automatically using a minimum version parameter.

It seems it does in form of `SupportedOSPlatform`:
![image](https://user-images.githubusercontent.com/1749069/117583830-b1c17600-b109-11eb-9a96-c3ac4403a99b.png)

**Comment by kennykerr** [comment]
Yep, I'm planning to find some way to use the `SupportedOSPlatform` attribute to conditionally delay load. It's very tailored to C# but I'm hopeful I can make it work.

**Comment by l0calh05t** [comment]
> Yep, I'm planning to find some way to use the `SupportedOSPlatform` attribute to conditionally delay load. It's very tailored to C# but I'm hopeful I can make it work.

In the Win32 metadata file we're looking at here, are there any of these version strings that aren't just a version (series of numbers separated by dots) prefixed by "windows"? From a cursory look in ILspy, I couldn't find any, but that wasn't an exhaustive check. I did find several functions that lacked the appropriate metadata, though 😕

**Comment by kennykerr** [comment]
Yes, this is a .NET invention that I'll have to parse. Looks like a reasonably closed [set of possibilities](https://github.com/microsoft/win32metadata/blob/86cb5c17a97c20658d90403c0044a5c5c44844c0/scripts/CreateSupportedOSPlatformRsp.ps1#L8-L34).

**Comment by kennykerr** [comment]
Just circling back to this issue. Any thoughts on using [delay loading](https://github.com/microsoft/windows-rs/issues/1425#issuecomment-1011282564)? That seems to be a simpler solution.

**Comment by roblabla** [comment]
Heh, since opening this issue, we've actually started using delay loading. But the ergonomics aren't great. We have to remember each time we call a function to check whether it is supported uniformly on all versions of windows we target, and version-gate *all* calls to it if they aren't (usually I do this by providing my own wrapper function that internally does the version check).

Also, I'm not 100% sure it works properly when you need to load the DLL anyways for other symbols. Take kernel32 for instance: you may want to call `GetProcessDefaultCpuSets` on win10+. I didn't test, so I may be totally off-base, but wouldn't this still cause an issue on win8.1 as soon as kernel32.dll is loaded, due to trying to link to a symbol that doesn't exist on that windows version? Or are the symbols resolved lazily when you call it?

**Comment by kennykerr** [comment]
That works. Each delay load function has a unique thunk is only replaced the first time you call that function.

**Comment by l0calh05t** [comment]
> Just circling back to this issue. Any thoughts on using [delay loading](https://github.com/microsoft/windows-rs/issues/1425#issuecomment-1011282564)? That seems to be a simpler solution.

A big disadvantage is that it wouldn't work work on any of the `*-windows-gnu` targets, right? Furthermore, if there is no simple, consistent way to check availability (Do we have to implement our own Windows version checks? Can this be automated? Same for knowing which API set to check with `IsApiSetImplemented`) and no clean way to recover from delay load errors, this seems more complex to use than the runtime loading approach

**Comment by kennykerr** [comment]
Unfortunately, with pre-packaged bindings for the `windows` and `windows-sys` crates it's not really practical to build delay loading directly in as that would impact everyone. Typically, a project only needs a handful of functions delay loaded. If you can't use MSVC's delay loading support, then I'd suggest calling `LoadLibrary`/`GetProcAddress` directly.

**Comment by kennykerr** [comment]
Going to close this issue as there's no actionable work here that I can tell. Feel free to reopen or create a new issue if I missed something.
