### ISSUE TITLE
Add support for Win32 struct fields of array type

### ISSUE THREAD

**Issue by thisKai** [microsoft/windows-rs#423]
In the [windows-rs docs](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/windows_and_messaging/struct.NCCALCSIZE_PARAMS.html) the `rgrc` field of `NCCALCSIZE_PARAMS` is a `bool`, but the [microsoft docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-nccalcsize_params) and the [winapi crate docs](https://docs.rs/winapi/0.3.9/winapi/um/winuser/struct.NCCALCSIZE_PARAMS.html) say it should be a `[RECT; 3]`

**Comment by kennykerr** [comment]
Yes, I still need to add support for struct fields of arrays.

**Comment by pravic** [comment]
Why use a wrong type (bool) instead of `todo!()` or something like that? People will struggle to realize what's wrong with their code.

**Comment by DaLynX** [comment]
I'm having the same issue with `bindings::windows::win32::security::TOKEN_PRIVILEGES`.

**Comment by kennykerr** [comment]
Ryan added a tweak to make it easier to identify such APIs. I'll get this fixed asap.

**Comment by kennykerr** [comment]
Sorry for the delay. This is now fixed as of https://github.com/microsoft/windows-rs/pull/608.
