### ISSUE TITLE
Lack of Apache-2.0 license option prevents this from being used by the standard library

### ISSUE THREAD

**Issue by Lokathor** [microsoft/windows-rs#426]
The current crate license is MIT only, with no option for Apache-2.0

However, for a crate to become a dependency of the standard library it has to have `Apache-2.0 OR MIT` as the license (plus possibly other license options, if any).

So, this crate can't become an eventual part of the standard library if the Apache-2.0 license isn't added as an option.

(If that's _not_ a goal of this crate that's fine, but if so that should probably be affirmed somewhere, because if that's the case then `winapi` will need to continue to be used by the standard library)

**Comment by kennykerr** [comment]
That's certainly a goal. 

I had a quick look and it seems we can probably offer Apache License 2.0 as well - I'm just not sure how to add that to the existing MIT license.

**Comment by DK26** [comment]
IMNAL but isn't MIT compatible with Apache 2.0? Which should mean you can use it freely in an Apache 2.0 as long as you comply with its MIT part?

Also, the logic behind MIT or Apache 2.0 doesn't make sense to me. If I violate Apache 2.0, do I go to court saying "But I chose to use its MIT part" and vice versa?

Or, is it MIT + Apache 2.0, which means you have to comply with both?

**Comment by ForNeVeR** [comment]
IMNAL, but, according to my understanding, Apache 2.0 has more grants than MIT (_at least_ w.r.t. "grant of patent license"), so, in general, software licensed under MIT cannot be freely relicensed/reused under Apache 2.0.

**Comment by DK26** [comment]
> 
> 
> IMNAL, but, according to my understanding, Apache 2.0 has more grants than MIT (_at least_ w.r.t. "grant of patent license"), so, in general, software licensed under MIT cannot be freely relicensed/reused under Apache 2.0.

True, but there is no MIT **restriction** for "grant of patent license", which makes the Patent clause bound to local and international laws by default, however it can get explicit when combined (+) with Apache 2.0.

However, if I do not explicitly grant you patent license over my MIT project and you use it in your Apache 2.0 project, I may be able to troll sue you for patents (? big question mark here since I did give it away for free use in any project, and this is free and fair use that doesn't violate the MIT license.).

Either way, engagement is Patent wars will disallow the suing parties to use the Apache 2.0 project, forever.

Do I miss something?

**Comment by DK26** [comment]
IMNAL.

It seems the rational behind licensing `Apache 2.0 or MIT` is that everything is licensed as `Apache 2.0` first, and if `Apache 2.0` is not compatible, then the `MIT` is opted. This was originally created with the goal of being compatible with GPLv2.

Source:
https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952

josh said:

> If we had it to do over again today, I’d suggest the https://opensource.org/licenses/BSDplusPatent license, which is a permissive license with the Apache 2.0 patent grant but retaining GPLv2-compatibility. But that license didn’t exist when Rust was first licensed.

I checked the official `rust` repository, it doesn't seem like there is an explicit condition that says that `Apache 2.0` is first in priority so my best guess is that it is implicit by the order you declare your license. a.k.a `Apache 2.0 or MIT` when `Apache 2.0` is the first and only then `MIT` is accepted (if `Apache 2.0` is not). I'm not sure that this is indeed legally correct but again, IMNAL.

Other than that, the `rust` repository seem to only contain a copy of each license: `LICENSE-APACHE` and `LICENSE-MIT`.
https://github.com/rust-lang/rust

**Comment by DK26** [comment]
IMNAL.

It seems the rational behind licensing `MIT or Apache 2.0` is that everything is licensed as `Apache 2.0` first (the more restrictive license), and if `Apache 2.0` is not compatible, then the less restrictive `MIT` is opted. This was originally created with the goal of using `Apache 2.0` as license however still wanting to be usable/compatible with GPLv2.

Source:
https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952

josh said:

> Requiring both MIT and Apache 2.0 as inbound licenses for contributions means that anyone making a contribution is providing the Apache 2.0 patent grant. And then having MIT and Apache 2.0 as outbound licenses people can use Rust under means that Rust provides widespread compatibility with all sorts of other FOSS licenses, including GPLv2.


> If we had it to do over again today, I’d suggest the https://opensource.org/licenses/BSDplusPatent license, which is a permissive license with the Apache 2.0 patent grant but retaining GPLv2-compatibility. But that license didn’t exist when Rust was first licensed.

I checked the official `rust` repository, it doesn't seem like there is an explicit condition that says that `Apache 2.0` is first in priority so my best guess is that it is implicit by the order from most restrictive to less restrictive license, where the first compatible license is automatically opted, but I'm not sure that this is indeed correct or legally correct, IMNAL.

Other than that, the `rust` repository seem to only contain a copy of each license: `LICENSE-APACHE` and `LICENSE-MIT` to make it `MIT or Apache 2.0`
https://github.com/rust-lang/rust

**Comment by Lokathor** [comment]
It's an `OR`, the license order listed doesn't matter. The end user makes the choice based on whatever criteria they want.

Some crates list "MIT or Apache", some list "Apache or MIT".

I think "Apache or MIT" is more common just for alphabetical reasons.

(not a lawyer)

**Comment by kennykerr** [comment]
I did a bit more digging. According to our open source team ([source](https://docs.opensource.microsoft.com/content/oss-licenses-by-type.html)): 

> The default license preferred by Microsoft for releasing our own code is the MIT License. The MIT license is compatible with other open source licenses, it can be easily used by our customers, and it is rising in use across the industry. Therefore, when we are releasing our own code as OSS, we use the MIT license absent a compelling business reason to do otherwise.

So I'm hoping MIT will be sufficient. If not, I can reach out to our legal folks to see whether we can get an exception.

**Comment by Lokathor** [comment]
I am not on the teams that make this approval.

However, I can say what happened with me: when I had a project that was *even more* permissively licensed than MIT (it was using the Zlib license), this came up. It was requested that the project (`tinyvec`) move to having an `MIT OR Apache2` option if I wanted to stay as part of the rust standard library dependency pile in the long term.

**Comment by DK26** [comment]
BTW, found a detailed article explaining both the rational and HOW-TO:

https://github.com/sfackler/rust-postgres-macros/issues/19

**Comment by DK26** [comment]
> IMNAL, but, according to my understanding, Apache 2.0 has more grants than MIT (_at least_ w.r.t. "grant of patent license"), so, in general, software licensed under MIT cannot be freely relicensed/reused under Apache 2.0.

I don't know about relicensed (depends) on our definition for this?), but you can miz them, they don't contridict. A grand is OK as long as it's not violating an existing restriction.

Again, IMNAL.

**Comment by kennykerr** [comment]
Thanks for the feedback - I received approval and we are now dual licensed.
