### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by Lokathor** [microsoft/windows-rs#427]
It would be nice if the crate were no_std by default, with a cargo feature to enable usage of the standard library (such as to implement traits from `std` that are not in `core`).

Similarly, much of the crate can probably avoid using `alloc` by default, with a cargo feature to enable usage of it.

**Comment by Jasper-Bekkers** [comment]
Relevant: https://github.com/rustsec/advisory-db/pull/1098

**Comment by kennykerr** [comment]
Thanks for the reminder. I can prioritize this work. Our OS team have also asked for this.

**Comment by kennykerr** [comment]
#1297 adds support for `no_std`.

**Comment by Lokathor** [comment]
I *strongly* suggest that you don't include the `std` feature as a default feature. It's very hard to avoid getting default features into your build because every single crate that uses this crate will have to specifically disable their default features, which most people don't do.

Instead, `std` should be off by default, and then whoever actively needs `std` can just enable it.

**Comment by kennykerr** [comment]
Yep good idea - will do.
