### ISSUE TITLE
How to convert windows::BOOL to u32?

### ISSUE THREAD

**Issue by Zymlex** [microsoft/windows-rs#428]
Some functions return BOOL when in fact they have multiple states, such as -1.

**Comment by kennykerr** [comment]
The `BOOL` struct's field is public so you can return `BOOL(123)` if you wish.

https://github.com/microsoft/windows-rs/blob/256538e85f2f9c860c09c318423b3be79b36b9c3/src/result/bool32.rs#L6

**Comment by Zymlex** [comment]
Thanks. I did not notice this, since Clion does not display tips for this crate.
In any case, so far there are more problems than advantages over `winapi`.

**Comment by kennykerr** [comment]
This is an early preview with various known issues - this isn't one of them 😉 - but if you run into specific issues do let me know and I'll be happy to look into them.
