### ISSUE TITLE
BOOL inconsistency

### ISSUE THREAD

**Issue by pravic** [microsoft/windows-rs#433]
It is treated like some kind of a result (see [the docs](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/struct.BOOL.html)) despite being often used as a parameter (like, in [`CreateEvent`](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/system_services/fn.CreateEventW.html)), even an `out` one - which is might be quite confusing.

To contract, there is no any special meaning for [`HANDLE`](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/system_services/struct.HANDLE.html) even though it is used as a result as often as `BOOL`.

**Comment by kennykerr** [comment]
[BOOL](https://docs.rs/windows/0.2.1/windows/struct.BOOL.html) is not unlike an error value or an [Option](https://doc.rust-lang.org/stable/std/option/enum.Option.html) that provide convenience helpers to turn such values into [Result](https://doc.rust-lang.org/stable/std/result/enum.Result.html) to simplify error handling. While it is true that `BOOL` (and `Option`) are not exclusively used for this purpose, it does make working with many Win32 APIs very convenient. 

I plan to provide helpers for the most frequently used types, including the likes of `HANDLE` and `NTSTATUS`, as we do for [ErrorCode](https://docs.rs/windows/0.2.1/windows/struct.ErrorCode.html) (e.g. HRESULT) and [BOOL](https://docs.rs/windows/0.2.1/windows/struct.BOOL.html).
