### ISSUE TITLE
It is not correct to delay GetLastError calls

### ISSUE THREAD

**Issue by pravic** [microsoft/windows-rs#434]
I am talking about [`BOOL::ok()`](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/struct.BOOL.html#method.ok)

https://github.com/microsoft/windows-rs/blob/256538e85f2f9c860c09c318423b3be79b36b9c3/src/result/bool32.rs#L27-L33

For example if it is used as this:

```rust
let valid_handle = todo!();
let invalid_handle = HANDLE::default();

let maybe_closed = CloseHandle(invalid_handle);  // here GetLastError would return ERROR_INVALID_HANDLE, for example
let closed = CloseHandle(valid_handle); // but this call overwrites it via SetLastError(ERROR_SUCCESS)

// the following is okay
assert!(maybe_closed.is_err());
assert!(closed.is_ok());

// however if we delay converting it
if let Err(e) = maybe_closed.ok() {
  let code = e.code();   // error code is 0
  assert!(code.is_ok()); // yep, it is 0 now which is incorrect
}
```

**Comment by kennykerr** [comment]
This is a common problem with error handling in Win32 APIs. The error information is stored on the thread and may be invalidated by subsequent API calls via `SetLastError`. This is something you need to watch out for when using such low-level APIs. I would expect higher-level crates that wrap the low-level Win32 APIs to handle this more idiomatically. 

The `windows` crate's support for WinRT APIs by contrast make this problem go away by carefully managing the lifetime and ownership of error information.

**Comment by Lokathor** [comment]
Yeah, there is unfortunately no *better* way to do it than what the crate is already doing.

**Comment by pravic** [comment]
> This is something you need to watch out for when using such low-level APIs 

The problem is that a primitive type `BOOL` pretends to be high-level while not being safe (even the opposite - it's error-prone).

There's no need in wrapping `BOOL`. The only thing that would make sense here is [customizing the `?` operator](https://doc.rust-lang.org/nightly/std/ops/trait.Try.html):

```rust
CloseHandle(invalid_handle)?;
```

**Comment by Lokathor** [comment]
Nitpick: It's absolutely *safe", you just sometimes get the wrong result if you use it wrong. It's slightly error prone if you're not paying attention, but it's still safe. In Rust, "safe" has a very specific meaning. You cannot cause UB by using `BOOL` improperly, so it's a fully safe type.

**Comment by kennykerr** [comment]
> There's no need in wrapping BOOL.

The reason `BOOL` exists and we don't simply generate `bool` is because the Win32 `BOOL` is a 32-bit value and it would break the ABI if we simply used `bool`. Also, the `Try` trait is not yet stable.
