### ISSUE TITLE
Create IIterable from Vec

### ISSUE THREAD

**Issue by Nerixyz** [microsoft/windows-rs#435]
I'm trying to use the function [`windows::devices::enumeration::DeviceInformation::create_watcher_with_kind_aqs_filter_and_additional_properties`]().

Its signature can be simplified to the following: 
```rust
fn create_watcher_with_kind_aqs_filter_and_additional_properties(
  aqs_filter: HString,
  additional_properties: windows::foundation::collections::IIterable<HString>,
  kind: DeviceInformationKind
)
``` 

Specifying `aqs_filter` and `kind` is pretty straight forward. However, specifying `additional_properties` didn't work as I expected.

I expected it to accept a `Vec<&str>` (or `String`). But it always fails with this error:

```
the trait `From<Vec<&str>>` is not implemented for `bindings::windows::Param<'_, IIterable<HString>>`
```
I've also tried this with a `HString` but it returned the same error.

I'm new to the Windows API so I'd guess I've missed something.

**Comment by kennykerr** [comment]
Sorry about that, you're not missing anything. This is a known issue. https://github.com/microsoft/windows-rs/issues/91

I hope to address this soon.

**Comment by Nerixyz** [comment]
Thanks for mentioning this issue! I guess GitHub didn't list this isue when searching "IIterable".
