### ISSUE TITLE
Generated Debug impls for structs do not support hex formatting

### ISSUE THREAD

**Issue by Hamled** [microsoft/windows-rs#439]
Currently the generated implementation of the `Debug` trait for structures uses an approach that means hex formatting (via `{:x?}` and similar) is not supported.

In particular, [this code](https://github.com/microsoft/windows-rs/blob/master/crates/gen/src/struct.rs#L189-L195) explicitly generates calls to `std::fmt::DebugStruct::field` with the value parameter being the result of a `format!` macro using the default debug formatting.

If using the nested `format!` call is not intentional, I think it can be removed as any value that can be passed to it with the debug format specifier must implement `Debug` and so can be passed directly to the `field` method.

**Comment by kennykerr** [comment]
Not intentional, thanks for the suggestion!
