### ISSUE TITLE
Provide an Executor over the Windows Threadpool

### ISSUE THREAD

**Issue by smj389** [microsoft/windows-rs#440]
It would be good to provide a Rust style wrapper over the Windows Thread Pool, which takes a Rust Future and executes it using CreateThreadPoolWork and SubmitThreadPoolWork with an interface that matches those used in other Rust crates which provide executors e.g. futures or smol.

**Comment by kennykerr** [comment]
I think this is a great suggestion. However, it seems like something that can most effectively be provided as a dedicated crate that makes use of the `windows` crate under the hood.

**Comment by raftario** [comment]
This is still very much a WIP, but it supports the basic `spawn`/`block_on` duo. I'm currently addong support over overlapped file and socket IO and plan to add timers after that. (I chose to stick with `winapi` for the time being to improve build times, but that's apparently already improving) https://github.com/raftario/wae
