### ISSUE TITLE
[Request] macro for defining COM interface not present in winmd.

### ISSUE THREAD

**Issue by chuckries** [microsoft/windows-rs#447]
(as an aside, is there any planned interop between this crate and [com-rs](https://github.com/microsoft/com-rs)?. Does this crate ever hope to replace com-rs?)

My goal: create a Win2D [CanvasSwapChain](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasSwapChain.htm) over an HWND (not CoreWindow) to allow me to use Win2D in a desktop app (as opposed to UWP).

Issue: [CanvasSwapChain can be created directly against a CoreWindow](http://microsoft.github.io/Win2D/html/M_Microsoft_Graphics_Canvas_CanvasSwapChain_CreateForCoreWindow.htm), but to acquire one for an HWD, I can only think of manually creating an [IDXGISwapChain1](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nn-dxgi1_2-idxgiswapchain1) and using [Win2D Interop](http://microsoft.github.io/Win2D/html/Interop.htm) to get the corresponding CanvasSwapChain.

Win2D offers a [native interop header](https://github.com/microsoft/Win2D/blob/master/winrt/published/Microsoft.Graphics.Canvas.native.h) that defines two interfaces for this purpose as well as some helper methods. My goal was to port these helper methods to rust using windows-rs binding, and I found I needed to manually define the interfaces using the building blocks from bindings.

(I'm not even sure if this idea is overall sound, just experimenting).

My attempt:
```rs
#[repr(transparent)]
struct ICanvasResourceWrapperNative(windows::IUnknown);

impl ICanvasResourceWrapperNative {
    fn GetNativeResource() {
        // TODO: figure out param types and invoke vtable method
    }
}

#[repr(C)]
struct ICanvasResourceWrapperNative_vtable(
    pub unsafe extern "system" fn(this: windows::RawPtr, iid: &windows::Guid, interface: *mut windows::RawPtr) -> windows::ErrorCode,
    pub unsafe extern "system" fn(this: windows::RawPtr) -> u32,
    pub unsafe extern "system" fn(this: windows::RawPtr) -> u32,
    pub unsafe extern "system" fn(this: windows::RawPtr, device: windows::RawPtr, dpi: f32, iid: &windows::Guid, *mut windows::RawPtr) -> windows::ErrorCode,
);

unsafe impl windows::Interface for ICanvasResourceWrapperNative {
    type Vtable = ICanvasResourceWrapperNative_vtable;

    const IID: windows::Guid = windows::Guid::from_values(
        0x5F10688D,
        0xEA55,
        0x4D55,
        [0xA3, 0xB0, 0x4D, 0xDB, 0x55, 0xC0, 0xC2, 0x0A],
    );
}
```

It would be nice if windows-rs provide a public macro to define a COM interface that matched the generated bindings.

**Comment by robmikh** [comment]
This won't solve your issue of creating COM interfaces, but there is another way to host your Win2D content. You can create a small visual tree using Windows.UI.Composition, and then create a surface from your swapchain using `Microsoft.Graphics.Canvas.Composition.CanvasComposition`.

Minesweeper creates a visual tree connected to the window here: 
https://github.com/robmikh/minesweeper-rs/blob/master/src/window_target.rs
https://github.com/robmikh/minesweeper-rs/blob/dfe034cdcecddc17030ab7f1982076da189c52dd/src/main.rs#L32

The Win2D Composition sample demonstrates hooking the swapchain surface into the tree (this sample is UWP but the idea is the same):
https://github.com/microsoft/Win2D/blob/0ac546bca974b9b454b99d9d31935071966537ea/samples/CompositionExample/SwapChainRenderer.cs#L61

**Comment by kennykerr** [comment]
Yes, I'd recommend checking out Robert's samples. 

And yes, the `windows` crate will eventually subsume much of what the `com` crate does. 

The ability to author COM interfaces is covered by this issue: #81

**Comment by kennykerr** [comment]
You can now implement many COM interfaces using the Windows crate. Let me know if you have any issues.
