### ISSUE TITLE
Preferred way to get an activation factory

### ISSUE THREAD

**Issue by robmikh** [microsoft/windows-rs#451]
Is there an equivalent to C++\WinRT's `get_activation_factory` helper? I see the `factory` method in factory_cache.rs, but it isn't exported publicly. Is there another facility I should prefer? Otherwise I'm happy to submit a PR making it public.

The need for the activation factory comes from the capture API. We expose a `IGraphicsCaptureItemInterop` interface, that despite its name is an interface you QI for from the item's factory.

**Comment by kennykerr** [comment]
There is and you should be able to write:

```rust
let interop = windows::factory::<GraphicsCaptureItem, IGraphicsCaptureItemInterop>()?;
```

But I just noticed the helper isn't public. This PR makes it public: https://github.com/microsoft/windows-rs/pull/452

**Comment by robmikh** [comment]
Picked up the new change and it works great! Thanks!
