### ISSUE TITLE
Struct size_of()

### ISSUE THREAD

**Issue by Zenthae** [microsoft/windows-rs#454]
```rust
use std::mem::size_of;

use bindings::windows::win32::bluetooth::*;
use bindings::windows::win32::system_services::HANDLE;

fn main() -> windows::Result<()> {
    let mut device_info = BLUETOOTH_DEVICE_INFO_STRUCT::default();
    device_info.dw_size = size_of::<BLUETOOTH_DEVICE_INFO_STRUCT>() as u32;

    let mut handle_radio: HANDLE = HANDLE::default();

    let mut find_radio_params = BLUETOOTH_FIND_RADIO_PARAMS::default();
    find_radio_params.dw_size = size_of::<BLUETOOTH_FIND_RADIO_PARAMS>() as u32;

    let mut radio_info = BLUETOOTH_RADIO_INFO::default();
    radio_info.dw_size = size_of::<BLUETOOTH_RADIO_INFO>() as u32;

    unsafe {
        // Get  handle of local radio
        dbg!(BluetoothFindFirstRadio(
            &find_radio_params,
            &mut handle_radio
        ));

        dbg!(BluetoothGetRadioInfo(handle_radio, &mut radio_info));

        dbg!(BluetoothIsConnectable(handle_radio).is_ok());

        // Get device info
        dbg!(BluetoothGetDeviceInfo(handle_radio, &mut device_info));
    }

    println!("{:#?}", device_info);

    Ok(())
}
```
isn't working,
```bash
BluetoothGetRadioInfo(handle_radio, &mut radio_info) = 1306
BluetoothGetDeviceInfo(handle_radio, &mut device_info) = 1306
```
which mean that both return a `ERROR_REVISION_MISMATCH`

after some tests, i discovered that `size_of()` isn't returning the good value,

```bash
[src\bin\bluetooth.rs:10] size_of::<BLUETOOTH_DEVICE_INFO_STRUCT>() = 60
[src\bin\bluetooth.rs:17] size_of::<BLUETOOTH_FIND_RADIO_PARAMS>() = 4
[src\bin\bluetooth.rs:22] size_of::<BLUETOOTH_RADIO_INFO>() = 16
```

test in question (xD) : 
```rust
        (1..1000).for_each(|x| {
            radio_info.dw_size = x;
            if BluetoothGetRadioInfo(handle_radio, &mut radio_info) == 0 {
                println!("{}", x);
            }
        });
```

here, `size_of()` for `BLUETOOTH_RADIO_INFO` return `16` when the only value that works is `520`

so i don't know how to fix this issue, because i don't believe that hard coding in my program the size of each struct is a good alternative, i'd like to know if i'm the one doing something wrong (if yes, how i can fix it) or is the lib (or rust ?) the issue

**Comment by kennykerr** [comment]
`BLUETOOTH_RADIO_INFO ` includes a field of type `BLUETOOTH_ADDRESS_STRUCT` includes a C-style union. This isn't yet supported. Here's an issue tracking this. #417

**Comment by Zenthae** [comment]
i just got the info from rust discord ^^, but like what's said on #423 the fact that it's not explicitly said anywhere that it wont work made me look everywhere for hours, would be good if all unusable structs could be commented so, or at least the concerned fields

**Comment by kennykerr** [comment]
Sorry about that. The API surface is vast and I am still working through it all so I don't yet know which structs are unusable, but I did pin that issue so hopefully it will be more discoverable.

![image](https://user-images.githubusercontent.com/9845234/106063072-8364e100-60ac-11eb-885d-15a445fe790c.png)
