### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'api-ms-win-core-debug-minidump-l1-1-0.lib'

### ISSUE THREAD

**Issue by DaLynX** [microsoft/windows-rs#457]
Hello,

I can successfully build the samples in https://github.com/kennykerr/samples-rs but am getting the following error trying to build with a binding to the `MiniDumpWriteDump` function:

```= note: LINK : fatal error LNK1181: cannot open input file 'api-ms-win-core-debug-minidump-l1-1-0.lib'```

Would you know how I should proceed to build this?

**Comment by kennykerr** [comment]
I have pinned the following issue describing the problem as it is a common question: https://github.com/microsoft/windows-rs/issues/463

**Comment by kennykerr** [comment]
A more comprehensive [workaround](https://github.com/microsoft/windows-rs/pull/467) is now in place to deal with the [linker issue](https://github.com/microsoft/windows-rs/issues/463). You should now be able to use this function without issue.
