### ISSUE TITLE
Add doc aliases for any renamings

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#458]
As part of the translation to Rust, some items are renamed to better fit into Rust's world of modularized code. For instance `CLSID_UIAnimationTransitionLibrary` is renamed to just `UIAnimationTransitionLibrary`. This is often quite nice but can hurt discoverability. We can use rustdoc's [alias](https://blog.rust-lang.org/2020/11/19/Rust-1.48.html#adding-search-aliases) feature to allow user's to search the untranslated name and get back the translated result.

**Comment by kennykerr** [comment]
There's some renaming going, so it would certainly be helpful to do this. 

Just wanted to point out that the cited example is not such a case. The original API headers include both `CLSID_UIAnimationTransitionLibrary` and `UIAnimationTransitionLibrary` and either can be used to retrieve the `CLSID`. The [win32metadata](https://github.com/microsoft/win32metadata) project however avoids the former and just emits a single constant named `UIAnimationTransitionLibrary`. So in this case, the Rust representation is actually being faithful to the metadata.

**Comment by kennykerr** [comment]
I think I've removed all the renaming. Feel free to create a new issue if you spot something that's still amiss.
