### ISSUE TITLE
Document frequently asked questions

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#460]
Some of the most frequently asked questions that should be documented are:
* [ ] What is the relationship between this crate and `winapi`? `com`? `winrt`?
  * Partial answer in #419  
* [ ] Will this provide higher-level facilities like the [WIL](https://github.com/microsoft/wil)?
  * Answer in #419  
* [ ] Where does the metadata come from? 
  * Answer in #419 
* [ ] Are these *all* the Windows APIs (i.e., win32, COM, WinRT)?
* [ ] Can this be used for making GUI Apps on Windows in Rust?

**Comment by kennykerr** [comment]
Feel free to contribute an FAQ.
