### ISSUE TITLE
AsyncOperation not handling nullpointer

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#464]
When calling `get_results()` on an `AsyncOperation`, the generated code does not handle null pointers. 

The generated code:
```rust
(::windows::Interface::vtable(this).8)( ::windows::Abi::abi(this), &mut result__,).from_abi::<TResult>(result__)
```

Here `result` never gets set to anything even though the call to `.8` on the vtable returns `0` indicating success. `Abi::from_abi` assumes that it is passed a non-null value.

We should use `ErrorCode::and_some` to handle the null case. It also might be good to inject `debug_assert!()` calls into the `Abi::from_abi` implementations that assume non-null values.

**Comment by kennykerr** [comment]
`from_abi` already does the right thing (basically the same as what `and_some` does. Here's how you might use it and handle any async failure:

```rust
match operation.get_results() {
    Ok(value) => {
        println!("value is ready!");
    }
    Err(err) => {
        println!("{:?}", err);
    }
};
```

**Comment by rylev** [comment]
In case anyone finds this issue later, the result being returned was an `ErrorCode` indicating `E_POINTER` which is used when the pointer is `null`. We may want to look into a special custom `ErrorCode` that makes this more explicit.
