### ISSUE TITLE
Windows::Input::Gamepad::GetCurrentReading producing zeroed readings

### ISSUE THREAD

**Issue by ArmsOfSorrow** [microsoft/windows-rs#471]
I'm trying to use the UWP Gamepad API like this:

```rust
mod bindings {
    ::windows::include_bindings!();
}

use bindings::windows::gaming::input::Gamepad;
use windows::foundation::collections::IVectorView;

fn main() {
    let mut gamepads = Gamepad::gamepads().unwrap();
    print_gamepads(gamepads);

    std::thread::sleep(std::time::Duration::from_secs(2));

    gamepads = Gamepad::gamepads().unwrap();
    print_gamepads(gamepads);

    std::thread::sleep(std::time::Duration::from_secs(2));

    gamepads = Gamepad::gamepads().unwrap();
    print_gamepads(gamepads);

    std::thread::sleep(std::time::Duration::from_secs(2));
}

fn print_gamepads(gamepads: IVectorView<Gamepad>) {
    for pad in gamepads {
        println!("Got pad, isWireless: {}", pad.is_wireless().unwrap());

        let reading = pad.get_current_reading().unwrap();
        let left_stick_x = reading.left_thumbstickx;
        println!("Left thumbstick X: {}", left_stick_x);
    }
}
```
My PC has an Xbox 360 controller attached via USB.
However, in `print_gamepads()` the reading I get is a zeroed-out struct. [Ryan Levick](https://twitter.com/ryan_levick/status/1355136882024321025) suggested it might be due to not running with a package identity (this is a console app), though the [docs](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad?view=winrt-19041) say the Gamepad class has the `DualApiPartition`, so in theory it should be usable from Desktop apps too, right?

**Comment by kennykerr** [comment]
@jonwis do you know who might be able to confirm the behavior of this API?

**Comment by kennykerr** [comment]
I can confirm the API picks up a controller but [GetCurrentReading](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad.getcurrentreading?view=winrt-19041) always returns zero values regardless of what buttons are pressed.

**Comment by kennykerr** [comment]
I haven't been able to find someone with knowledge of this API's usage requirements. The bindings produced by the `windows` crate appear to be calling the API correctly. You may have better luck getting an answer on http://stackoverflow.com if you point out that it is not language-specific. Hope that helps.

**Comment by kennykerr** [comment]
@ArmsOfSorrow quick update - I just heard back from the Xbox team. It turns out the API will only report back data if the app has a window (not just a console app) and the window has the focus. 

I gave it a try and sure enough once I used the API from a message loop it started reporting data correctly. The [clock sample](https://github.com/microsoft/windows-rs/tree/master/examples) is a good one to try if you need something to play with.
