### ISSUE TITLE
CoInitializeEx takes u32 instead of COINIT as second argument

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#482]
This is likely an issue with the metadata but the call to `CoInitializeEx` takes a `u32` as its second argument instead of a `COINIT`. This isn't wrong per say but it certainly makes the API more error prone.

**Comment by kennykerr** [comment]
Yes, this is an issue with the metadata. I already reported it here: https://github.com/microsoft/win32metadata/issues/95

**Comment by kennykerr** [comment]
This is fixed as of #658
