### ISSUE TITLE
COM interfaces ABI associated type should be Option<Self>

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#486]
Currently the `Abi` trait is implemented for any type `T` that implements `Interface`. The associated `Abi` type is set to `RawPtr`, but it should be set to `Option<Self>`. Since it is part of the `Interface` trait's contract that it have an FFI safe in-memory representation that is a COM compliant pointer, it is fine to assume `Option<Self>` as the `Abi` type.

**Comment by fghzxm** [comment]
What if we completely ditched the `Abi` trait in favor of `MaybeUninit` and `ManuallyDrop`?  AFAIK the user-facing Rust type of every runtime type is already FFI-safe (all scalar types are, `HString` and objects are all `#[repr(transparent)]` ptrs which are, `GUID` and structs are `#[repr(C)]` structs of other FFI-safe types), so there shouldn't be a need for trait polymorphism from the beginning here?

**Comment by kennykerr** [comment]
> it is fine to assume Option<Self> as the Abi type

The trouble with using Option is that it is implies a Drop trait - the Abi type must be blittable to prevent stack corruption.
