### ISSUE TITLE
Consider marking all COM functions as `#[must_use]`.

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#489]
It's probably always necessary to check the result of a COM method call. In Rust, we can mark COM methods as `#[must_use]` in order to ensure that users check the result from calling the COM method.

**Comment by kennykerr** [comment]
Yes, there are basically two cases here:

1. C-style functions that return an `HRESULT`. `HRESULT` is mapped to `windows::ErrorCode` and this type should have `#[must_use]` to help with diagnostics. 

2. COM interface methods that return `HRESULT` (not all do). These should be remapped to return `Result<T>` where `T` is either `()` or the trailing out parameter type (except where there is a trailing pair). `windows::Result` already has the `#[must_use]` attribute.

**Comment by kennykerr** [comment]
A related question is whether `windows::BOOL` should be `#[must_use]` since it is most often used to indicate the success or failure of some C-style function.
