### ISSUE TITLE
Can't use "enum" variant constants in pattern matching

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#490]
Rust only allows using a constant in a pattern when the underlying type explicitly derives `PartialEq` and `Eq`. This is because pattern matching is actually based on "structural equality" and not the actual implementations of those traits (see [here](https://doc.rust-lang.org/std/marker/trait.StructuralEq.html) and [here](
https://doc.rust-lang.org/std/marker/trait.StructuralPartialEq.html)). You can see this behavior [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3a00de71b7e371b86b0ce8287da1c5c2). Since we are manually implementing these traits for the enum type, we cannot use them in pattern matching and must use if/else checks like below:

```rust
if action == intl::CORRECTIVE_ACTION::CORRECTIVE_ACTION_DELETE {
     // todo
} else if action == intl::CORRECTIVE_ACTION::CORRECTIVE_ACTION_REPLACE {
    // todo
}
```

We can either switching to deriving these traits or wait until this structural mechanism is exposed in stable Rust.

**Comment by kennykerr** [comment]
We can switch back to deriving these for enums (only) until this Rust feature is stabilized.
