### ISSUE TITLE
Add CoCreateInstance wrapper 

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#495]
This is such a common construction function that a wrapper would make a lot of common scenarios a lot simpler.

https://github.com/kennykerr/samples-rs/blob/40f7c8b0ed13ffe370c193365f104e26e862dfbd/clock/src/main.rs#L552-L563

This example looks as follows:

```rust
fn create_manager() -> Result<IUIAnimationManager> {
    unsafe {
        let mut manager: Option<IUIAnimationManager> = None;

        CoCreateInstance(
            &UIAnimationManager,
            None,
            CLSCTX::CLSCTX_INPROC_SERVER.0 as u32,
            &IUIAnimationManager::IID,
            manager.set_abi(),
        )
        .and_some(manager)
    }
}
```

This could be simplified to a safe one-liner:

```rust
let manager: IUIAnimationManager = create_instance(&UIAnimationManager)?;
```

**Comment by rylev** [comment]
I’m very much in favor of this. I do wonder where the line is around convenience functions that will live in windows-rs and ones that should live in another crate (e.g., a COM crate 😀).

**Comment by kennykerr** [comment]
I think the line should be drawn around useful vertical APIs, like spell checking or Direct2D, and leave the low-level functionality that is necessary to even call those APIs inside the `windows` crate. It's certainly a bit subjective.
