### ISSUE TITLE
Consider rethinking the module structure

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#500]
Currently everything in the `windows` crate gets exported at the top level. This certainly makes usage easy as the developer just needs to add `windows::*` to any module and all `windows` types are available to them. This, however, isn't the most idiomatic API approach.

One downside is that documentation will become harder to navigate as more features are added to the `windows` crate. Right now, everything is on one page which can make it hard to understand what's going on.
<img src="https://user-images.githubusercontent.com/1327285/106610915-9de50180-6567-11eb-9821-1d9e3ab9c75e.png" width="500" />

## Possible other approach

Another approach would be to use the "prelude" pattern where items that are useful in almost any use of `windows` (e.g., `Abi`, `Interface`, `ErrorCode`, etc.) are in the `prelude` module. Users normally only import this module `use windows::prelude::*;`. Other items that are only useful in more specialized cases would be in submodules and users would individually import them. For instance, `HString` is only used in certain APIs. We could make the `strings` module public and users would import that type with `use windows::strings::HString;`

### Which types go in `prelude`?

I would propose the following types live in prelude with all other types living in their various submodules:
* `ErrorCode`, `Error`, `Result`
* `IUnknown`, `Object`
* `Abi`, `Interface`, `RuntimeName`, RuntimeType`
* `Array`

Additionally `Error` and `Result` would be re-exported from the top level module and used like so `windows::Result`.

**Comment by ObsidianMinor** [comment]
Don't go too crazy with breaking stuff up. The only thing worse than an endless list of declarations (windows atm isn't that bad actually, it could be [libc](https://docs.rs/libc) after all) is one module for *every declaration* that's impossible to navigate because you have to go two steps into a documentation just to read any item.

**Comment by knopp** [comment]
I seem to have an opposite problem. For every symbol I want to add to build.rs I need to search the documentation  first to see in which module it belongs.

**Comment by kennykerr** [comment]
Going to close this issue as the Windows crate's documentation surface is not expected to get much larger. The public types are mostly limited to those that straddle both WinRT and Win32 and must thus be defined by the Windows crate. Most everything else should be included in the generated bindings as needed.
