### ISSUE TITLE
Intellisense / Code completion does not work for generated code

### ISSUE THREAD

**Issue by BertusGreeff** [microsoft/windows-rs#504]
This issue can easily be reproduced by using latest stable tool chain and opening https://github.com/robmikh/minesweeper-rs in vscode with the Rust extension.

RLS log reports: 
{"message":"proc macro panicked","code":null,"level":"error","spans":[{"file_name":"D:\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\windows-0.2.1\\build.rs","byte_start":16,"byte_end":41,"line_start":2,"line_end":2,"column_start":5,"column_end":30,"is_primary":true,"text":[{"text":"    windows_macros::build!();","highlight_start":5,"highlight_end":30}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"message: Failed to parse `cargo metadata`: Error(\"EOF while parsing a value\", line: 1, column: 0)","code":null,"level":"help","spans":[],"children":[],"rendered":null}],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15m: proc macro panicked\u001b[0m\n\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m--> \u001b[0m\u001b[0mD:\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\windows-0.2.1\\build.rs:2:5\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m|\u001b[0m\n\u001b[0m\u001b[1m\u001b[38;5;14m2\u001b[0m\u001b[0m \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m| \u001b[0m\u001b[0m    windows_macros::build!();\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m| \u001b[0m\u001b[0m    \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;9m^^^^^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m|\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;14m= \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;15mhelp\u001b[0m\u001b[0m: message: Failed to parse `cargo metadata`: Error(\"EOF while parsing a value\", line: 1, column: 0)\u001b[0m\n\n"}

**Comment by kennykerr** [comment]
I don't know that much about these extensions, but I hear [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) is the way to go. I'd also suggest creating an issue at the appropriate repo for the extension you're using so they can take a look at the issue.
