### ISSUE TITLE
WLAN_INTERFACE_INFO_LIST

### ISSUE THREAD

**Issue by spieglt** [microsoft/windows-rs#510]
In C++, the third member of [`WLAN_INTERFACE_INFO_LIST`](https://docs.microsoft.com/en-us/windows/win32/api/wlanapi/ns-wlanapi-wlan_interface_info_list) is `WLAN_INTERFACE_INFO *InterfaceInfo[]` or `WLAN_INTERFACE_INFO InterfaceInfo[1]`, but in the windows-rs [docs](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/native_wi_fi/struct.WLAN_INTERFACE_INFO_LIST.html) it's a bool. Is this function not usable?

**Comment by DaLynX** [comment]
Array types have not been implemented yet, see https://github.com/microsoft/windows-rs/issues/423.

**Comment by rylev** [comment]
Sorry for the confusion! Closing this as it's already being tracked in #423. We will generate new docs soon, and with https://github.com/microsoft/windows-rs/pull/506, this should be less confusing going forward.
