### ISSUE TITLE
Scrape the #defines for constants out of the headers

### ISSUE THREAD

**Issue by BertusGreeff** [microsoft/windows-rs#511]
There is a huge amount of #defines of well know constants, error values, PROPKEYs, DEVPROPKEYs etc. in the Win32 headers.  It would be very valuable to all of that to be available.

If they can't be auto-generated, please establish a process where by the community can contribute their definitions.

**Comment by kennykerr** [comment]
This is already being done by the [win32metadata](https://github.com/microsoft/win32metadata) project. You can browse the [available definitions here](https://microsoft.github.io/windows-docs-rs/). If something is missing, feel free to create an issue here:

https://github.com/microsoft/win32metadata/issues
