### ISSUE TITLE
Document usage of COM interfaces

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#512]
Looking at [IStream](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/structured_storage/struct.IStream.html), the declaration does not say anything about ISequentialStream and IUnknown. The stream object is unusable without ISequentialStream methods and I also need AddRef/Release from IUnknown, is there a workaround for this?

Scenario: I'm getting a pointer of IStream via `IInitializeWithStream::Initialize`, keep it, and read it in `IThumbnailProvider::GetThumbnail`. ([Source currently with winapi-rs](https://github.com/saschanaz/jxl-winthumb/blob/main/src/lib.rs))

**Comment by Nerixyz** [comment]
You can use `.cast::<ISequentialStream>()` which is from the `windows::Interface` trait that's implemented for `IStream`.

To use `AddRef` you call `.clone()` and `Release` is called once the interface is dropped (it implements the `Drop` trait).

**Comment by kennykerr** [comment]
I implemented COM inheritance support a short while back: https://github.com/microsoft/windows-rs/pull/448

I will publish another update to https://crates.io/ and update the documentation soon.

**Comment by rylev** [comment]
We should probably also add some docs to explicitly talk about how COM is handled. We have a two examples now using COM, but some prose that more directly explains things like `QueryInterface` ==  `Interface::cast`, `AddRef` == `Clone::clone`, and `Release` == `Drop` would be good to have.

**Comment by kennykerr** [comment]
[crates.io](https://crates.io/crates/windows) and the [Windows API documentation](https://microsoft.github.io/windows-docs-rs/) has now been updated. For example, you can find the [IStream docs here](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/structured_storage/struct.IStream.html). As you can see, it provides the `ISequentialStream` methods directly (as they're inherited) and provides convertibility for all base interfaces.

**Comment by saschanaz** [comment]
Cool, confirmed that ISequentialStream::Read works 👍

**Comment by saschanaz** [comment]
Hmm, actually reopening for https://github.com/microsoft/windows-rs/issues/512#issuecomment-773461506

**Comment by kennykerr** [comment]
Glad to hear its working. 😀

**Comment by kennykerr** [comment]
Duplicate of #81
