### ISSUE TITLE
Way to prevent drop (or do additional addref?)

### ISSUE THREAD

**Issue by saschanaz** [microsoft/windows-rs#521]
Continuing from https://github.com/microsoft/windows-rs/issues/512#issue-801246533.

So my scenario is:

1. The caller (the Windows kernel) calls `IInitializeWithStream::Initialize` with an `IStream` argument
2. The function tries storing the value
3. The caller doesn't know it stored the value, so it frees the stream

`clone()` does call `AddRef()` internally but it always pairs with `drop()` at the end so the reference count ultimately doesn't change. ~~Is there a workaround for this?~~ `std::mem::forget()` works, but should there be another way?

**Comment by saschanaz** [comment]
This is the code: https://github.com/saschanaz/jxl-winthumb/blob/547883d2d60b598ff4872f93ab5bdf5355ac10d2/src/lib.rs#L58

I somehow feel `forget()` enough, so feel free to close this if you also think so.

**Comment by rylev** [comment]
Is there a reason you're not moving the `IStream` into the call to the [call to `WinStream::from`](https://github.com/saschanaz/jxl-winthumb/blob/547883d2d60b598ff4872f93ab5bdf5355ac10d2/src/lib.rs#L57)? The call to `clone` seems unnecessary.

**Comment by saschanaz** [comment]
It's for addref, or nothing will and it'll be freed.

**Comment by rylev** [comment]
The object gets freed when it its drop implementation is called and the ref count is 0. Moving does not invoke the drop implementation so the COM object will not be freed. If you've run into a situation where you have an `IStream` but the underlying COM pointer has been freed that's a bug in this crates implementation. Are you saying you have an `IStream` but the underlying pointer has been freed?

**Comment by saschanaz** [comment]
Moving does not invoke it, sure, but the caller invokes it after the call. Freeing happens unless the callee increases reference count. I even had to clone this repository add a log in IUnknown drop function to confirm it.

It's also what other thumbnail providers do, I suspect that's what Windows requires.

**Comment by rylev** [comment]
Can you produce a minimal example where you have a COM object that points to already freed memory?

**Comment by saschanaz** [comment]
Storing raw IStream in initialize(), commenting out contents in get_thumbnail() and calling `self.stream.Revert()` would be the most minimal example I can make. The call would cause panic.

**Comment by rylev** [comment]
@saschanaz I can't build your project as it depends on things that are local to your machine.

Can your provide more information on the nature of the exception? You call it a panic but perhaps you mean its a system exception like an access violation and not a Rust panic? 

It sounds like the error is that implementers of `IInitializeWithStream::Initialize` are supposed to call `AddRef` on the incoming handle to the stream. If that's the case then getting an exception makes sense. But this means that technically the signature of `initialize` as you've defined it is incorrect. COM objects that are defined by the `windows` crate are "owned" COM objects and will call `Release` when they are dropped. If the implementor of `initialize` is expected to call `AddRef` on the incoming stream handle then the stream handle is not really owned.

Perhaps a more appropriate signature would be:

```rust
fn initialize(&mut self, stream: std::mem::ManuallyDrop<IStream>, mode: u32) -> ComResult<()>;
```

This is certainly a confusing and potentially we could provide a wrapper type that more clearly models the non-"owned" COM pointer. I'll wait to see what @kennykerr has to say.

**Comment by kennykerr** [comment]
I don't see a bug here in the way the `windows` crate handles COM lifetime. It seems the crate you are using for COM support does not handle lifetime correctly, probably because it was not designed to work with the `windows` crate. Implementation support is coming soon. #81
