### ISSUE TITLE
`NOT_YET_SUPPORTED_TYPE` is constructible via `Default`

### ISSUE THREAD

**Issue by mbilker** [microsoft/windows-rs#523]
According to the comment on `NOT_YET_SUPPORTED_TYPE`, it is not supposed to be constructible by end-users, but it derives from `Default` therefore can still be constructed. The `Default` derive implementation should be removed so it is not constructible.

**Comment by kennykerr** [comment]
Yes, the comment isn't accurate. Doing that would have a cascading effect and the type is just a temporary placeholder so I don't want more effort going into making it "correct".

**Comment by mbilker** [comment]
That makes sense to me. At least the type name shows up very clearly in compile error messages so it definitely got the point across!
