### ISSUE TITLE
Type mismatches

### ISSUE THREAD

**Issue by Serentty** [microsoft/windows-rs#525]
I've been porting over a test application that uses the WinAPI crate to try to get it to work with this. One issue I've run into is that it seems like types don't match in a lot of cases where C would consider the mismatch to be small enough to let slide, but Rust doesn't. For example, the type of ``MB_OK`` is ``i32``, but ``MessageBox`` accepts a ``u32`` where you would pass that in. So so far, compared to the WinAPI crate, I've needed to do a lot of casting. In addition, it offers lots of type aliases that make it easier to follow Windows documentation.

**Comment by kennykerr** [comment]
Thanks for kicking the tires. I have reported many of these issues already. For example: https://github.com/microsoft/win32metadata/issues/130

Feel free to report any additional issues you find with metadata.
