### ISSUE TITLE
CreatePipe should have *mut HANDLE arguments instead of *mut isize

### ISSUE THREAD

**Issue by zaddach** [microsoft/windows-rs#532]
Current `CreatePipe` signature:
```
pub unsafe extern "system" fn CreatePipe(
    h_read_pipe: *mut isize, 
    h_write_pipe: *mut isize, 
    lp_pipe_attributes: *mut SECURITY_ATTRIBUTES, 
    n_size: u32
) -> BOOL
```
I feel that should be instead:
```
pub unsafe extern "system" fn CreatePipe(
    h_read_pipe: *mut HANDLE, 
    h_write_pipe: *mut HANDLE, 
    lp_pipe_attributes: *mut SECURITY_ATTRIBUTES, 
    n_size: u32
) -> BOOL
```

**Comment by DaLynX** [comment]
It's been fixed in commit https://github.com/microsoft/windows-rs/commit/d82a5232fa7ba86b5dec3cfcacc2ac1e0561a9bd after metadata was updated (https://github.com/microsoft/win32metadata/issues/198).

Are you building from the master branch?

**Comment by zaddach** [comment]
I was building off 0.3.1, I'll try with master. Thanks!

**Comment by kennykerr** [comment]
The docs have also been updated. [Here is CreatePipe](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/system_services/fn.CreatePipe.html).
