### ISSUE TITLE
A built in way to parse dates?

### ISSUE THREAD

**Issue by 1Dragoon** [microsoft/windows-rs#543]
Is there or could there be a built in way to handle OLE Automation Date instead of just f64? Basically I'd like to be able to avoid this kind of gobledygook when dealing with dates/times in windows:

```rust
let date: f64 = 44239.92503472222;
let unix_days = date - 25569.;
let unix_secs = unix_days * 86400.;
let secs = unix_secs.trunc() as i64;
let nsecs = (unix_secs.fract().abs() * 1e9) as u32;
let cdate = chrono::NaiveDateTime::from_timestamp_opt(secs, nsecs).unwrap();
```

Not necessarily chrono, but i.e. WinTime::to_unix_epoch() or something

**Comment by kennykerr** [comment]
Sorry for the delay, I'm not a chrono expert. You can probably experiment with functions like `VarI4FromDate` but I don't have anything specific to recommend.
