### ISSUE TITLE
Official support for rust-analyzer?

### ISSUE THREAD

**Issue by Ciantic** [microsoft/windows-rs#550]
Given that Rust-Analyzer is the official LSP implementation for Rust, I think this important.

Win-RT crate [says this](https://crates.io/crates/winrt):

> WinRT is developed with and tested for the rust-analyzer VS Code extension. We want WinRT-rs to work well with rust-analyzer, so if you run into issues, please file a bug report so we can look into it. There are, however, a few things to note about WinRT-rs and rust-analyzer:

Is there similar guarantee for `windows` crate? Right now it's really difficult to use this crate with rust-analyzer. 

- If I write e.g. `WM_USER` and press `CTRL + .` it won't give me auto import. 
- If I hit `CTRL+Space` in `ID2D1Solid` it won't auto complete. 
- If I hit `Ctrl+Mouse Click` it doesn't go to definition on `D2D1_BITMAP_PROPERTIES1`, it won't even show me what struct fields it has.

To me this is so huge downside compared to `winapi` crate, so much so that I can't use `windows` crate over that.

I have this in my `settings.json`:

```
{
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.cargo.loadOutDirsFromCheck": true
}
```

**Comment by kennykerr** [comment]
Our desire is for good `rust-analyzer` support. The `windows` crate is in preview and there is a great deal of work yet to be done. I would expect that we will eventually have more time to focus on IDE support. 

Having said that, many of the problems that I've seen with the `rust-analyzer` extension are actually limitations with the extension itself. So if you would like to contribute or even just report issues then please do so here: https://github.com/rust-analyzer/rust-analyzer/issues
