### ISSUE TITLE
FILE_ACCESS_FLAGS should implement OR operator

### ISSUE THREAD

**Issue by zaddach** [microsoft/windows-rs#552]
`FILE_ACCESS_FLAGS` is a bitflag wrapper, but there is no operator defined to join bitflags. I'd want to use (FILE_ACCESS_FLAGS::FILE_GENERIC_READ | FILE_ACCESS_FLAGS::FILE_GENERIC_WRITE) as argument to  `CreateFileW`.

https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/file_system/struct.FILE_ACCESS_FLAGS.html

**Comment by kennykerr** [comment]
The problem is with the metadata. The flag values are signed when they should be unsigned. I've created an issue for this: https://github.com/microsoft/win32metadata/issues/253
