### ISSUE TITLE
Deprecation of winrt at 0.8.0, not 0.7.3?

### ISSUE THREAD

**Issue by qdot** [microsoft/windows-rs#555]
The winrt crate 0.7.3 has been turned into a deprecation crate, meaning anything that builds on the 0.7 line of winrt will now fail to compile. We had multiple libraries break in CI due to this, with no obvious reason until we figured out it was the upgrade issue.

Can you please yank 0.7.3 and do that release at 0.8.0, maybe with a compile error macro to say why the breakage happens and to move to the new library? Breakage like that is really jarring, and the way you did this deprecation does not make it obvious why anything broke, just that the `winrt` module disappeared

**Comment by qwandor** [comment]
+1, 0.7.3 is a major breaking change, so this goes against the cargo semver conventions.

**Comment by kennykerr** [comment]
So sorry! I didn't realize that would happen. I've yanked 0.7.3.

Thanks for letting me know.
