### ISSUE TITLE
Error 0x80004002 on debug console, but no error propagation in rust

### ISSUE THREAD

**Issue by smw-wagnerma** [microsoft/windows-rs#556]
Some strange error behaviour:

```
fn main() -> windows::Result<()> {
    unsafe {
        RoInitialize(RO_INIT_TYPE::RO_INIT_SINGLETHREADED).ok()?;
    }
    let hid_device_watcher = DeviceInformation::create_watcher()?;

    Ok(())
}
```

The program runs fine, no panic, but on the debug console there is:

Exception thrown at 0x00007FFCC9D2D759 (KernelBase.dll) in cargo_develop.exe: WinRT originate error - 0x80004002 : 'Interface not supported'.

Shouldn't there an error at the create_watcher call?

**Comment by kennykerr** [comment]
This just indicates that an error was recorded internally to the API via the `RoOriginateError` function but was handled automatically and thus did not bubble up out of the API as an error.
