### ISSUE TITLE
Allow access to the Offset fields of the OVERLAPPED structure

### ISSUE THREAD

**Issue by zaddach** [microsoft/windows-rs#569]
For asynchronous IO, the recommended method in Microsoft's documentation ([here](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfilepointer), "To specify the offset for overlapped operations: Use the Offset and OffsetHigh members of the OVERLAPPED structure.") to seek to a certain offset is to manipulate the `Offset` and `OffsetHigh` fields of the OVERLAPPED structure. In `windows-rs`, this field is hidden behind an opaque struct (`anonymous`).

Could you consider either exposing the fields, or providing a getter and setter accessor to manipulate the field safely?

**Comment by kennykerr** [comment]
This is currently unavailable as the offset members are within a nested struct, which is not yet supported. I have a major update coming soon that addresses this issue.

**Comment by kennykerr** [comment]
This has been fixed.

**Comment by kennykerr** [comment]
Here's an example of using OVERLAPPED: 

https://github.com/microsoft/windows-rs/tree/master/examples/overlapped
