### ISSUE TITLE
How to use an ErrorCode from a returned Result<_, Error>?

### ISSUE THREAD

**Issue by zaddach** [microsoft/windows-rs#570]
I'm trying to figure out how to use the returned Error/ErrorCode when I need to check for a certain value. Let's say I'm using `ReadFile`, and I want to check if `GetLastError()` was `ERROR_IO_PENDING` when using overlapped input. How would I do this nicely?

My idea was:
```rust
const ERROR_IO_PENDING: ErrorCode = ErrorCode::from_win32(bindings::windows::win32::system_services::ERROR_IO_PENDING);

let mut overlapped = OVERLAPPED::default();
match ReadFile(_, _, _, _, _, &mut overlapped).ok() {
    Ok(_) => ...,
    Err(e) if e.code() == ERROR_IO_PENDING => ...,
    Err(e) => ...,
}
```
Two drawbacks:
- ErrorCode::from_win32 is crate-only pub, so I need to copy-paste the function into my own code.
- It would be nicer if `windows-rs` could export the `ErrorCode` constants somewhere.

Is this how the ErrorCode is intended to be used?

**Comment by kennykerr** [comment]
A few thoughts.

* We're trying to improve the metadata for error codes. https://github.com/microsoft/win32metadata/issues/159
* Then we'll likely individual types for HRESULT, WIN32, and NTSTATUS that provide common const values for such error codes.
* OVERLAPPED doesn't work yet as it requires nested structs and unions. That should be working in a few days.

**Comment by zaddach** [comment]
Hey, thanks for the pointer to the discussion on the win32metadata repo. Sorry for spamming you a bit with issues, I'm just trying to keep track of everything that doesn't feel ergonomic to me in the windows-rs crate usage right now. The OVERLAPPED thing was just an example, there are other functions like [InitializeProcThreadAttributeList](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-initializeprocthreadattributelist) that return an error on successful operation by API convention which the user should check for. I'll comment that on the other discussion and close the issue here.

**Comment by kennykerr** [comment]
No worries, appreciate the feedback - keep it coming! 😉

**Comment by kennykerr** [comment]
Unions are now supported. Here's an example of using OVERLAPPED: 

https://github.com/microsoft/windows-rs/tree/master/examples/overlapped
