### ISSUE TITLE
Incorrect type returns?

### ISSUE THREAD

**Issue by Master0r0** [microsoft/windows-rs#572]
Writing something that utilizes GetProcAddress and CreateRemoteThread, it seems odd to me that
GetProcAddress returns a `fn() -> i32`
however
CreateRemoteThread requires an Option of `fn() -> u32` for a start address
Is this a mistake or am I missing something?

**Comment by kennykerr** [comment]
This one happens to be correct. The metadata attempts to faithfully preserve the original signatures found in the Windows API. The result of `GetProcAddress` is always cast to something that matches the signature of the function being imported.
