### ISSUE TITLE
Consider making ErrorCode::from_win32 public

### ISSUE THREAD

**Issue by Robo210** [microsoft/windows-rs#576]
There are many Win32 APIs that return error codes as LSTATUS (such as the registry APIs) or DWORD values (such as WaitForSingleObject), and it would be nice to be able to easily convert these into an HRESULT -> ErrorCode.

Currently the only way to do this is to use ErrorCode::from_thread(), which uses the value from GetLastError(), or to write your own From<LSTATUS> that copies what from_win32() is doing. Functions such as RegQueryValue don't explicitly say that they will also call SetLastError() with the error code that they are returning, so the latter option seems like the only safe choice.

This also applies to dealing with NTSTATUS codes, which I'm sure nobody using windows-rs should have any business dealing with, but is nevertheless a type exposed through windows::win32::system_services::NTSTATUS.

**Comment by kennykerr** [comment]
Thanks for the feedback! Yes, I plan to make that public shortly.
