### ISSUE TITLE
PWSTR does not implement Debug/Display

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#580]
This type should implement both debug and display. The `Display` implementation seems obvious (we should just print the string contents). Should the `Debug` implementation be the same? Since `PWSTR` is often used at the ABI barrier, it might make sense to show the value of the ptr itself as well.

**Comment by Lokathor** [comment]
That would be unsound.

**Comment by rylev** [comment]
@Lokathor Why would this be unsound? I think if the ptr is non-null the contents should be fine to read and display.

**Comment by Lokathor** [comment]
that assumes correctly created values, which you cannot do with public fields.

```rust
println!("{}", PWSTR(4 as _)); // gonna be a bad time
```

**Comment by rylev** [comment]
That's very true. We'll probably have to create an unsafe `display` function much like `std::path::Path::display` (which isn't unsafe).

**Comment by kennykerr** [comment]
Going to close this for now. I don't see a reliable way to implement `Debug`/`Display` for `PWSTR` and friends and it seems pretty rare that you'd need to do that.

**Comment by Lokathor** [comment]
This is a solvable problem, and a real problem, particularly for debugging needs, but to solve it you would have to make some large changes to the type.

For example, if you make the type have a private field with an unsafe constructor, and also a lifetime, then it could all end up being safe. However, in practice any values coming back from ffi would have an unbound lifetime that ends up being static, and then you've got subtle lies all over the code.

This is all basically the same design problem that CStr has.

**Comment by kennykerr** [comment]
Yep, that's why I'm reluctant to "solve" this for a narrow use case when the vast majority of developers will run into the "lies". In most cases, developers should only encounter these types as input parameters, so I think this is not a major pain point.
