### ISSUE TITLE
Create PWSTR and PSTR from literals

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#581]
Right now literals need to be copied into new buffers every time one is passed into a function that expects a `PWSTR`. Instead we should provide some type of macro convenience for creating `PSTR` and `PWSTR` from literals. These would encode the literals properly and add a trailing `\0` at the end all at compile time. Bonus points if we can make macro that works for either kind of string pointer.

**Comment by lespea** [comment]
Could something like this work? https://github.com/Lokathor/utf16_lit

**Comment by rylev** [comment]
Yes, I also have my own crate that does this https://github.com/rylev/const-utf16 which introduced const compilation a bit before `utf16_lit` did. I think either one would be fine to use.

**Comment by kennykerr** [comment]
Do we need to use a macro? It would be nice if we could (also) write a const function to do this so you can write something like this:

```rust
let s = PSTR::from("hello");
```

It would somehow have to distinguish between a string literal and a regular string reference. I'm not sure if that's possible.

**Comment by agausmann** [comment]
Any function that takes a `&str`, `&[u8]`, `&[u16]` etc with the goal of null-terminating it or transcoding it (ie. UTF-8 to UTF-16) would have to use another buffer to store the result, because the value can't be modified in-place. To get around that, the idea here is to make a new literal string that gets stored in the program's static storage at compile-time.

Functions cannot distinguish literals in their input (although you can get close with `&'static str`), and furthermore, they cannot create new literals (even if they're `const`). Literals can only be created by using literal syntax, so they have to be written in the code, either directly or by a macro.

For example, to convert a literal `b"abcd"` to one that is null-terminated, we can write a macro to rewrite the literal, syntactically, to `b"abcd\0"`. That's the only way to do so at compile-time.

**Comment by 1Dragoon** [comment]
What's the current idiomatic way of creating a PWSTR from a string literal? I used this but it doesn't appear to work when I give it to a function that needs a pwstr for an input:

```rust
let text = String::from("my pwstr literal").encode_utf16().collect::<Vec<u16>>();
let mypwstr = PWSTR(text.as_mut_ptr());
```

**Comment by kennykerr** [comment]
The API is likely assuming a null terminator.

**Comment by agausmann** [comment]
Yep, I'd recommend using a crate like `widestring`. I use `widestring::U16CString` which automatically converts strings to UTF-16 and  null-terminates them.

**Comment by 1Dragoon** [comment]
The null terminator is no doubt part of it but actually it looks like the trait constraints of the way some functions are now defined don't allow for null pointers when the API expects them in some cases, which is where I was actually stuck (the compiler gave an ambiguous message that made me think I was using the wrong type at first.) Namely this:

https://docs.microsoft.com/en-us/windows/win32/api/adshlp/nf-adshlp-adsopenobject

Where in the example they pass a null pointer to lpzusername and lpzpassword. But in the windows-rs crate it MUST be PWSTR per the type constraints:

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/ActiveDirectory/fn.ADsOpenObject.html

So my previous way of simply passing a ptr::null_mut() doesn't work with the newest version of windows-rs when I want passive authentication. Is there another way of doing that?

Sorry may be off topic, I can create a separate issue if required.

**Comment by kennykerr** [comment]
Here's an example (the last parameter is effectively a null pointer value).

https://github.com/microsoft/windows-rs/blob/87f32117f613e3a1666e3dc7a379ba596789a4dd/examples/event/src/main.rs#L10

**Comment by 1Dragoon** [comment]
Ah I figured that was more analogous to an empty string than a null pointer, but at first glance it seems to work, thanks!

**Comment by wanderer06** [comment]
Might be late to the party, but I got around it using my own impl:
```rust
impl SystemServices::PWSTR {
    fn from(text: &str) -> Self {
        Self(text.encode_utf16().chain(::std::iter::once(0)).collect::<Vec<u16>>().as_mut_ptr())
    }
}
```

Then used it like so:
```rust
let class_name = SystemServices::PWSTR::from("Hello world?");
```

**Comment by Neopallium** [comment]
> Might be late to the party, but I got around it using my own impl:
> 
> ```rust
> impl SystemServices::PWSTR {
>     fn from(text: &'static str) -> Self {
>         Self(text.encode_utf16().chain(::std::iter::once(0)).collect::<Vec<u16>>().as_mut_ptr())
>     }
> }
> ```

That creates a `Vec<u16>` and get a raw pointer `.as_mut_ptr()` to the vec's internal data.  The Vec will be freed and that pointer will not be valid.

**Comment by kennykerr** [comment]
Playing with an implementation of this here: https://github.com/microsoft/windows-rs/compare/utf16?expand=1

**Comment by kennykerr** [comment]
#1891 introduced string literal macros that address this issue.
