### ISSUE TITLE
Support PWSTR and PSTR as out parameters

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#595]
So far I've only plumbed the `PWSTR` and `PSTR` types to support input parameters. That means you can call a function that expects one of these with a simple string literal and it just works. Next up is to add support for more interesting but less common scenarios where these types are used as output parameters so that you can both easily convert to `String` and automatically free the memory (if necessary). There is now metadata that indicates which allocator to use (if any) so we should be able to make this essentially a one-liner. Here's an example:

```rust
use bindings::{
    windows::win32::com::CoTaskMemFree,
    windows::win32::shell::SHGetKnownFolderPath,
    windows::win32::system_services::{HANDLE, PWSTR},
};

fn known_folder_path(id: &windows::Guid) -> windows::Result<String> {
    unsafe {
        let mut path = PWSTR::default();
        SHGetKnownFolderPath(id, 0, HANDLE(0), &mut path).ok()?;

        if path.0.is_null() {
            return Ok(String::new());
        }

        let mut end = path.0;

        while *end != 0 {
            end = end.add(1);
        }

        let result = String::from_utf16_lossy(std::slice::from_raw_parts(
            path.0,
            end.offset_from(path.0) as _,
        ));

        CoTaskMemFree(path.0 as _);
        Ok(result)
    }
}

fn main() -> windows::Result<()> {
    // https://github.com/microsoft/win32metadata/issues/220
    let downloads_id: windows::Guid = "374DE290-123F-4565-9164-39C4925E467B".into();
    
    let path = known_folder_path(&downloads_id)?;

    println!("{}", path);
    Ok(())
}
```

**Comment by BenoitRanque** [comment]
Would this also cover cases where the size of the output buffer must be set before calling the function? For example, from the [docs](https://docs.microsoft.com/en-us/windows/win32/printdocs/getdefaultprinter) of `GetDefaultPrinterW`:
```c++
BOOL GetDefaultPrinter(
  _In_    LPTSTR  pszBuffer,
  _Inout_ LPDWORD pcchBuffer
);
```
>
> pszBuffer [in]
> 
> A pointer to a buffer that receives a null-terminated character string containing the default printer name. If this parameter is > > NULL, the function fails and the variable pointed to by pcchBuffer returns the required buffer size, in characters.
>
> pcchBuffer [in, out]
>
> On input, specifies the size, in characters, of the pszBuffer buffer. On output, receives the size, in characters, of the printer name string, including the terminating null character.
>

The [bindings](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/SystemServices/fn.GetDefaultPrinterW.html) generated by this crate translate `LPTSTR` to `PWSTR`
```rust
pub unsafe fn GetDefaultPrinterW(pszbuffer: PWSTR, pcchbuffer: *mut u32) -> BOOL
```

Maybe a `PWSTR::with_capacity(capacity)` function could be implemented for this purpose? Importantly, the `String::with_capacity(capacity)` method uses bytes as capacity, not character count, so I don't think we can use that.

I'm still very new to this, but I'm happy to help in any way I can. Just unsure which is the way to go here.

For reference, here is some admittedly inelegant code that uses the `winapi` crate.

```rust
    pub fn get_default_printer() -> Result<Option<String>, Error> {
        let mut buffer = vec![0u16; 128]; // default sensible output buffer size. If more size is required the while loop will iterate
        let mut buffer_size = buffer.capacity() as DWORD;

        // note on buffer_size: it is also an output parameter
        // if GetDefaultPrinter fails due to insufficient buffer size, buffer_size will contain the size required
        // if GetDefaultPrinter succeeds, buffer_size will contain the amount of characters written
        // buffer_size is mutable because it will be updated inside GetDefaultPrinter
        while unsafe { GetDefaultPrinterW(buffer.as_mut_ptr(), &mut buffer_size) } == 0 {
            match Error::last_os_error().raw_os_error().unwrap() as u32 {
                ERROR_FILE_NOT_FOUND => return Ok(None),
                ERROR_INSUFFICIENT_BUFFER => buffer = vec![0u16; buffer_size as usize], // set buffer to size required
                _ => return Err(Error::last_os_error()),
            }
        }

        let name = String::from_utf16_lossy(&buffer.as_slice()[..((buffer_size - 1) as usize)]); // remove last item since string is null terminated

        Ok(Some(name))
    }
```

**Comment by kennykerr** [comment]
Yes, there is additional metadata that binds these two parameters together. I still need to plumb that through to Rust so that it can handle such parameter pairs correctly.

**Comment by kennykerr** [comment]
At this point I've applied the transformations that I believe are practical and safe. Some APIs are just not practical to transform into a more natural form. Feel free to keep chatting or open new issues for any outstanding concerns.

**Comment by Enyium** [comment]
`PWSTR::with_capacity(capacity)`, as proposed by @BenoitRanque, sounds like an API worth having. I need it in two steps though when calling `AssocQueryStringW()` twice: In the first step, the function gives me the necessary buffer length; in the second step, it fills the buffer with the desired string.

Currently, I'm first creating the empty buffer with `Vec::<u16>::new()`, which doesn't allocate, call `Vec::resize()` as soon as I know the buffer size, pass it via `PWSTR(buffer.as_mut_ptr())` to be filled, and finally call `OsString::from_wide_null(&buffer)`, which is provided by the undocumented [`wio` crate](https://crates.io/crates/wio) ([source](https://github.com/retep998/wio-rs/blob/master/src/wide.rs#L34)).

Is there a way forward for `PWSTR`, so that the additional `Vec` or any user-handled backing buffer wouldn't be needed? The private `HSTRING::from_wide_iter()` also allocates and stores a pointer in the `HSTRING` struct. I'm not sure who is responsible for that allocated memory to be freed though.

And surely an equivalent to `wio`'s `OsString::from_wide_null()` could be provided.
