### ISSUE TITLE
How to get active user?

### ISSUE THREAD

**Issue by 13r0ck** [microsoft/windows-rs#596]
Using C# getting a the active user is as simple as [Environment.UserName](https://docs.microsoft.com/en-us/dotnet/api/system.environment.username?view=net-5.0).
How do I do the same thing with windows-rs?

Thank you so much!

**Comment by robmikh** [comment]
The windows-rs crate generates bindings for Windows APIs, so you'll want to track down the Win32 or WinRT API that does what you want and then look that API up in the crate documentation. In this case, you'll want the GetUserName(A/W) function:

https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getusernamea
https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/windows_programming/fn.GetUserNameA.html

There's also a set of WinRT APIs that can be used to get user information:
https://docs.microsoft.com/en-us/uwp/api/Windows.System.User?view=winrt-19041

**Comment by robmikh** [comment]
Here's a snippet that does this with WinRT:

```rust
use bindings::windows::{
    foundation::IReference,
    system::{User, UserType, KnownUserProperties},
};
use windows::Interface;

fn main() -> windows::Result<()> {
    windows::initialize_sta()?;

    let users = User::find_all_async_by_type(UserType::LocalUser)?.get()?;
    assert!(users.size()? >= 1);
    let user = users.get_at(0)?;

    let user_name: IReference<windows::HString> = user.get_property_async(KnownUserProperties::account_name()?)?.get()?.cast()?;
    let user_name = user_name.get_string()?;
    println!("User name: {}", user_name);

    Ok(())
}
```

Generally it's preferable to actually use the async pattern instead of blocking using `get` but for this sample it was simpler.

**Comment by kennykerr** [comment]
In this case, you can also use the Rust standard library:

```rust
fn main() {
    let username = env!("USERNAME");
    println!("{}", username);
}
```

**Comment by 13r0ck** [comment]
You all are amazing! Thank you so much!!!!
