### ISSUE TITLE
IDirectSound::CreateSoundBuffer crashing with STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by gaelog** [microsoft/windows-rs#597]
When attempting to create a primary IDirectSoundBuffer via a dynamically loaded DirectSound library, my program crashes with `(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`.

I am not too experienced with COM, so I put together a [minimal crashing example](https://paste.gg/p/anonymous/508b33f231d8411f9fbacfa4118d06f8).
It's completely possible that I messed up something on my end.

Edit: Fiddling with the code and removing the CreateSoundBuffer call, I noticed that IUnknown causes the STATUS_ACCESS_VIOLATION aswell when being `Drop`ped

**Comment by kennykerr** [comment]
That's not what I'd call a minimal repro. 😉 I would say that you're overcomplicating things. I don't know anything about this API but you should be able to use it as follows:

```rust
use bindings::windows::win32::audio::{DirectSoundCreate, DSBUFFERDESC};

fn main() -> windows::Result<()> {
    unsafe {
        let mut sound = None;
        let sound = DirectSoundCreate(std::ptr::null_mut(), &mut sound, None).and_some(sound)?;

        let mut desc = DSBUFFERDESC {
            dw_size: std::mem::size_of::<DSBUFFERDESC>() as u32,
            dw_flags: 1,
            ..Default::default()
        };

        let mut buffer = None;

        let buffer = sound
            .CreateSoundBuffer(&mut desc, &mut buffer, None)
            .and_some(buffer)?;

        buffer.Stop().ok()
    }
}
```

**Comment by gaelog** [comment]
Yes, sorry. I realized soon after posting it that it was excessive, even if the docs suggested that order ^^".
I totally missed what `windows::IntoParam` and `windows::Abi` were doing all this time, thanks a lot!
