### ISSUE TITLE
windows::Error is not Send or Sync

### ISSUE THREAD

**Issue by qwandor** [microsoft/windows-rs#600]
The `windows::Error` type is not `Send` or `Sync`. This means that a `windows::Result<T>` is not `Send` or `Sync` either, even if `T` is. This is a pain both for async code, and for integrating with common error-handling frameworks like `eyre` and `anyhow`. It is possible to work around both of these issues, but they make the API considerably less ergonomic.

It looks like the problem is that `Error` may contain a `bindings::windows::win32::winrt::IRestrictedErrorInfo`. It is not clear from the documentation whether this type is supposed to by thread-safe. Could it at least be made `Send`? That would help with the async issue, and then by wrapping it in a `Mutex` you could make `windows::Error` `Sync` as well.

**Comment by agausmann** [comment]
See also https://github.com/microsoft/windows-rs/issues/424#issuecomment-766528167

**Comment by kennykerr** [comment]
Sorry for the delay. I had a look at the implementation. Yes, it can be both `Send` and `Sync`. 

Does `ErrorCode` also need `Send` and `Sync` or just `Error`? `ErrorCode` seems to work across threads without explicitly being `Send` and `Sync`.

**Comment by laptou** [comment]
`ErrorCode` is automatically `Send + Sync` because it doesn't contain any types that are not `Send + Sync`.

**Comment by qwandor** [comment]
`ErrorCode` is already `Send` and `Sync`, isn't it? It's just a wrapper around a `u32` so the compiler will automatically implement both. You only need to implement them manually for types containing raw pointers or other special types.

**Comment by kennykerr** [comment]
Thanks for confirming! I'll get a PR out shortly.

**Comment by kennykerr** [comment]
Here you go: https://github.com/microsoft/windows-rs/pull/601
