### ISSUE TITLE
Static functions on XamlBinaryWriter don't get generated

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#603]
I was playing around with the [XamlBinaryWriter](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.xamlbinarywriter) to see if I can put together some tooling support for XAML applications. Unfortunately, I wasn't able to get the static [Write](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.xamlbinarywriter.write) method generated using the following minimal example:

Cargo.toml:
```toml
[package]
name = "xbf"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = "0.4.0"

[build-dependencies]
windows = "0.4.0"
```

build.rs:
```rust
fn main() {
    ::windows::build!(windows::ui::xaml::markup::XamlBinaryWriter,)
}
```

src\\main.rs:
```rust
mod bindings {
    ::windows::include_bindings!();
}

use bindings::windows::ui::xaml::markup::XamlBinaryWriter;

fn main() {
    XamlBinaryWriter::write();
}
```

Compiling this crate fails with the error message:

```none
error[E0599]: no function or associated item named `write` found for struct `XamlBinaryWriter` in the current scope
   --> src\main.rs:8:23
    |
8   |     XamlBinaryWriter::write();
    |                       ^^^^^ function or associated item not found in `XamlBinaryWriter`
    | 
   ::: C:\...\xbf\target\debug\build\xbf-d34ba94dc7849efe\out/windows.rs:101:17
    |
101 |                 pub struct XamlBinaryWriter(::windows::Object);
    |                 ----------------------------------------------- function or associated item `write` not found for this
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `write`, perhaps you need to implement one of them:
            candidate #1: `std::io::Write`
            candidate #2: `Hasher`
```

The generated code for `IXamlBinaryWriterStatics_abi` contains a slot in its v-table for the `Write` method, but I was unable to access it through the `XamlBinaryWriter` type. By contrast, the [CoreWindow](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow) type does implement static methods (like `get_for_current_thread`) just fine.

Am I going about this the wrong way, or is there currently a limitation that prevents *windows-rs* from generating the static `Write` method on the `XamlBinaryWriter` type?

---

Note: I replaced the `Windows.UI.Xaml.Markup.XamlBinaryWriter` with the implementation provided by the latest WinUI 3 [NuGet package](https://www.nuget.org/packages/Microsoft.WinUI/) (3.0.0-preview4.210210.4) in the `Microsoft.UI.Xaml.Markup` namespace. Doing so produced the same generated code (modulo the base module name) and ultimately the same build error.

**Comment by tim-weis** [comment]
It turns out, this was just another incarnation of #594. Changing build.rs like so

```rust
fn main() {
    ::windows::build!(
        windows::ui::xaml::markup::{
            XamlBinaryWriter, XamlBinaryWriterErrorInformation, IXamlMetadataProvider
        },
        windows::foundation::collections::IVector,
        windows::storage::streams::IRandomAccessStream,
    )
}
```

provided the code generator with the required type information to produce a `write` function on `XamlBinaryWriter`.

**Comment by kennykerr** [comment]
This is related to #594 that I'm actively working on improving. For now, you just need to make sure you declare all of the types you would like the build macro to generate for you. For example, the `XamlBinaryWriter::write` method refers to a number of different types, but the following build macro should get you unblocked:

```rust
fn main() {
    windows::build!(
        windows::foundation::collections::IVector,
        windows::storage::streams::IRandomAccessStream,

        windows::ui::xaml::markup::{
            IXamlMetadataProvider, XamlBinaryWriter, XamlBinaryWriterErrorInformation,
        },
    );
}
```

**Comment by tim-weis** [comment]
Thanks so much for the quick response, and apologies for the poor timing on my end. Always feels bad to occupy someone else's time only to realize shortly after that it wasn't necessary. Though seeing the same solution was reassuring.

Much appreciated, as always.

**Comment by kennykerr** [comment]
As of 0.12.0 (#896), methods are no longer omitted so this should no longer be an issue.

**Comment by tim-weis** [comment]
Perfect, that's a *huge* ergonomics improvement.

Already moved two of my projects forward to 0.12.0 (both Win32 and WinRT). Things are looking better with every release. Thanks a lot, Kenny!
