### ISSUE TITLE
Crate can't build offline

### ISSUE THREAD

**Issue by 0xngold** [microsoft/windows-rs#606]
### Summary
**Expected behavior**: `windows-rs` builds successfully offline with a local-registry
**Actual behavior**: `windows-rs` build fails with a cryptic error message

It seems there are three sub-bugs here:
* `cargo metadata` doesn't work offline, even if `windows-rs` was supplying `--offline` (see https://github.com/rust-lang/cargo/issues/9273).
* `windows-rs` discards the errors from the `cargo metadata` invocation. This makes debugging tricky.
* Given that `cargo metadata` doesn't currently work offline, is there another place we can get this `workspace_root` from?

### Details

**Error example**
```
error: proc macro panicked
 --> C:\Users\some_user\.cargo\registry\src\-b20c50870c528e96\windows-0.3.1\build.rs:2:5
2 |     windows_macros::build!();
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^

  = help: message: Cargo metadata \\?\C:\src\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe did not contain `workspace_root` key. Got stdout . Got stderr     
          Updating crates.io index
          warning: spurious network error (2 tries remaining): failed to send request: The server name or address could not be resolved
          ; class=Os (2)
          warning: spurious network error (1 tries remaining): failed to send request: The server name or address could not be resolved
          ; class=Os (2)
          error: failed to get `const-sha1` as a dependency of package `windows v0.3.1 (C:\Users\some_user\.cargo\registry\src\-b20c50870c528e96\windows-0.3.1)`

          Caused by:
            failed to load source for dependency `const-sha1`

          Caused by:
            Unable to update registry `https://github.com/rust-lang/crates.io-index`

          Caused by:
            failed to fetch `https://github.com/rust-lang/crates.io-index`

          Caused by:
            failed to send request: The server name or address could not be resolved
            ; class=Os (2)

          .
   Ran from "C:\\Users\\some_user\\.cargo\\registry\\src\\-b20c50870c528e96\\windows-0.3.1"

error: aborting due to previous error
```

**Repro steps**
1. Create a binary crate `C` that depends on `windows-rs`.
2. Use `cargo local-registry` to create a local registry for `C`'s dependencies.
3. Try to build `C` with the local registry replacing `crates.io`. The build should fail with a cryptic error from the `windows-rs` build. To reproduce the error message I have above, modifying [this line](https://github.com/microsoft/windows-rs/blob/7710e15ed669dd33919c6f9b6b963609ad195cae/crates/gen/src/winmd/workspace.rs#L25) inside the local registry's copy of `windows_winmd` crate. There is almost certainly a simpler repro, but a repro shouldn't be strictly necessary to verify this bug has been fixed.

**Comment by kennykerr** [comment]
Unfortunately, I'm not aware of any other way to get the workspace dir. I had hoped there would be an environment variable, as there is for `OUT_DIR`, `CARGO_MANIFEST_DIR`, and so on. Reading the result of `cargo metadata` is certainly not ideal, but that's all I could find.

**Comment by rylev** [comment]
`cargo metadata` has an `offline` flag we can pass it which will not go to the network. It still has the workspace dir available.

**Comment by kennykerr** [comment]
@rylev the original issue mentions that the offline flag doesn't work.

**Comment by rylev** [comment]
Whoops, sorry totally missed that!

**Comment by kennykerr** [comment]
I did however just try running `cargo metadata --format-version=1 --no-deps` without an internet connection and it works fine for me using `cargo 1.52.0-nightly`.

**Comment by kennykerr** [comment]
I have added the `--offline` flag for good measure, but it doesn't appear to make a difference. Anyway, I don't think there's anything else I can do from my end.

**Comment by 0xngold** [comment]
Thanks! Version `0.5.0` fixes the issue for me (the only change there seems to be adding `--format-version=1 --no-deps`; previously I was on `0.3.1`).
