### ISSUE TITLE
D3D12_BLEND_DESC render_target is NOT_YET_SUPPORTED_TYPE

### ISSUE THREAD

**Issue by Ciantic** [microsoft/windows-rs#610]
This is probably known issue, since it says "NOT_YET_SUPPORTED_TYPE". But I couldn't find a way to track when it will be supported so I opened an issue.

[Windows-rs docs link](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/direct3d12/struct.D3D12_BLEND_DESC.html) that says `D3D12_BLEND_DESC` field `render_target` is `NOT_YET_SUPPORTED_TYPE`.

**Comment by kennykerr** [comment]
This should now be fixed as of https://github.com/microsoft/windows-rs/pull/608

I haven't yet updated the docs.
