### ISSUE TITLE
Some types/constants are no longer generated with 0.5.0

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#618]
I just tried moving an application with a GUI to 0.5.0. Both registering a window class and creating a window failed due to missing constants. `WNDCLASS_STYLES` in namespace `Windows.Win32.WindowsAndMessaging` doesn't get generated for me. Likewise, `CW_USEDEFAULT` in namespace `Windows.Win32.WindowsAndMessaging.Apis` is missing.

My *build.rs* looks like this

```rust
fn main() {
    windows::build!(windows::win32::windows_and_messaging::*);
}
```

Am I doing something wrong here, or should the types/constants get generated? For the time being I declared the respective constants, so I'm not immediately blocked on this.

**Comment by kennykerr** [comment]
Hi Tim, the metadata driving the generated bindings is under [active development](https://github.com/microsoft/win32metadata). The main reason I bump the `windows` crate version is to ensure semantic versioning is preserved as breaking changes are introduced. This should stabilize eventually, but for now you can expect changes like this as the metadata is completed and polished. For your scenario, have a look at [the Clock example](https://github.com/microsoft/windows-rs/tree/master/examples/clock) that uses these APIs. I make sure [the examples](https://github.com/microsoft/windows-rs/tree/master/examples) are current and work with the latest version of the `windows` crate.

https://github.com/microsoft/windows-rs/blob/6116e0549cb9a91015a9a4e5923ae38ed2f68271/examples/clock/src/main.rs#L403-L413

**Comment by kennykerr** [comment]
By the way, while those two `win32metadata` bugs have been fixed, the latest build includes [a new regression](https://github.com/microsoft/win32metadata/issues/373) that is blocking me from ingesting the metadata.

**Comment by tim-weis** [comment]
Perfect, thank you!

I was using the *Windows.Win32.winmd* from the latest NuGet package (preview.68) and loaded it up in Visual Studio's Object Browser to find the type names. Those don't seem to agree with the sample code (`WNDCLASS_STYLES` vs. `WINDOWSCLASS_STYLES`), so I guess this crate is using an older version. Could the specific Win32Metadata version be included in the [changelog](https://github.com/microsoft/windows-rs/blob/master/docs/changelog.md)?

**Comment by kennykerr** [comment]
The supported version is [documented here](https://github.com/microsoft/windows-rs/tree/master/crates/gen/default).

The latest version is [broken](https://github.com/microsoft/win32metadata/issues/373), so I'm waiting for a new build.
