### ISSUE TITLE
WNDCLASS_STYLES missing

### ISSUE THREAD

**Issue by knopp** [microsoft/windows-rs#630]
I couldn't get WNDCLASS_STYLES working even though it seems to be present in the metadata.

**Comment by tim-weis** [comment]
It's in `windows::win32::windows_and_messaging`. I think it was in ``windows::win32::system_services` previously, so you have to update the `build!` macro  incocation.

**Comment by kennykerr** [comment]
Have a look at the Clock sample:

https://github.com/microsoft/windows-rs/tree/master/examples/clock

**Comment by knopp** [comment]
I tried it it in windows_and_messaging. But I think it works in 0.6.0.

**Comment by knopp** [comment]
(I'm updating from 0.3.1 and it is a bit of a rough ride :) )

**Comment by kennykerr** [comment]
Sorry, the metadata has changed quite a bit since then. 😜 

Let me know if you get stuck!
