### ISSUE TITLE
Feature request: Implement BitOrAssign for flags

### ISSUE THREAD

**Issue by knopp** [microsoft/windows-rs#633]
It would be nice if I could do flags |= BIT_FLAG instance of flags = flags | BIT_FLAG;

**Comment by Ciantic** [comment]
Also flags has a lot of repetition, e.g.

```rust
D3D12_ROOT_SIGNATURE_FLAGS::from(
	D3D12_ROOT_SIGNATURE_FLAGS::D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT.0 |
	D3D12_ROOT_SIGNATURE_FLAGS::D3D12_ROOT_SIGNATURE_FLAG_DENY_HULL_SHADER_ROOT_ACCESS.0 |
	D3D12_ROOT_SIGNATURE_FLAGS::D3D12_ROOT_SIGNATURE_FLAG_DENY_GEOMETRY_SHADER_ROOT_ACCESS.0 |
	D3D12_ROOT_SIGNATURE_FLAGS::D3D12_ROOT_SIGNATURE_FLAG_DENY_PIXEL_SHADER_ROOT_ACCESS.0
)
```

I could imagine if BitOrAssign is implemented, and some clever shortening it could be just:

```rust
D3D12_ROOT_SIGNATURE_FLAGS::ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT |
	D3D12_ROOT_SIGNATURE_FLAGS::DENY_HULL_SHADER_ROOT_ACCESS |
	D3D12_ROOT_SIGNATURE_FLAGS::DENY_GEOMETRY_SHADER_ROOT_ACCESS |
	D3D12_ROOT_SIGNATURE_FLAGS::DENY_PIXEL_SHADER_ROOT_ACCESS
```

(Notice in that case I also cut out the redundant `D3D12_ROOT_SIGNATURE_FLAG_` from beginning of each flag).

**Comment by kennykerr** [comment]
I've added bitwise assign operators - been meaning to do so (#635).

While removing common prefixes is appealing, it does make it more difficult to correlate to API documentation and port code from other languages. So I'm not sure whether that will ultimately be a good idea. For what its worth, WinRT APIs are generally designed with this in mind and thus don't suffer from all of this redundancy.
