### ISSUE TITLE
SetWindowLongPtr/GetWindowLongPtr missing

### ISSUE THREAD

**Issue by wravery** [microsoft/windows-rs#644]
In Win32 apps, it's common to store a pointer on an `HWND` using `SetWindowLongPtr`, e.g. in `GWL_USERDATA`. On 32-bit targets it's `#defined` to use `SetWindowLong`, and that's what shows up in the [bindings::windows::win32::windows_and_messaging](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/windows_and_messaging/fn.SetWindowLongW.html) module. Trouble is, that's limited to `i32`, and without adding a non-`windows-rs` `PInvoke` there doesn't seem to be a way to access the full width of the window data slot on 64-bit targets.

It's a hack, but I found a workaround I could use for now. On `#[cfg(target_pointer_width = "64")]` I add an extra 4 bytes to [WNDCLASSW::cb_wnd_extra](https://microsoft.github.io/windows-docs-rs/doc/bindings/windows/win32/windows_and_messaging/struct.WNDCLASSW.html#structfield.cb_wnd_extra), and I put the high/low `DWORD` for the pointer in separate slots. This works nicely in Rust with `Box::into_raw()` pointers.

I'm not sure if this is a bug in `win32metadata` or `windows-rs`, but I figured I'd report it here first in case it's specific to the Rust projections. It may be something that `win32metadata` should fixup as a special case while scraping the headers.

**Comment by kennykerr** [comment]
This was recently added to `win32metadata` and is now available in `windows-rs` as of #642. The Clock example makes use of it. 

https://github.com/microsoft/windows-rs/blob/master/examples/clock/src/main.rs
