### ISSUE TITLE
Request for implementations of From/Into to convert between PWSTR/PCWSTR and String/&str

### ISSUE THREAD

**Issue by wravery** [microsoft/windows-rs#645]
Most COM and Win32 apps `#define UNICODE` and prefer the `W` APIs which take `PWSTR` or `PCWSTR`. Rust has built-in `String::encode_utf16` and `String::from_utf16` methods, it would be great if `PWSTR` and `PCWSTR` could implement `From`/`Into` traits to encapsulate that.

It's tricky since it needs extra storage, but maybe the tuple could be extended with an `, Option<Vec<u16>>` to hold the extra allocation, and the `.0` could point to that when this is used.

**Comment by kennykerr** [comment]
This already works for input parameters. You can pass a string to any function expecting a `PSTR` or `PWSTR` and it will create the null-terminated string of the appropriate encoding. For example, the following just works today:

```rust
 SetWindowTextA(handle, "Hello A");
 SetWindowTextW(handle, "Hello W");
```

I'm still working on making it easier for `PWSTR` and `PSTR` output parameters. That is tracked by #595.
