### ISSUE TITLE
Improve traits coverage for "interesting" structs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#656]
Struct that are or contain unions, include complex arrays, are packed or contain nested packed structs, are all very limited in that they don't receive various trait implementations like PartialEq, Eq, Default, and Debug. Some of these are reasonable, but others just need a bit more help. For example, this warning just started firing in nightly builds and needed a workaround for Windows to build cleanly:

https://github.com/rust-lang/rust/issues/82523

Fortunately, the issue mentions a simple way to support it.

**Comment by valarauca** [comment]
Sounds good. I managed to work around it by Creating a vector, and extracting the vector element.
