### ISSUE TITLE
Please support other member methods of LockScreen

### ISSUE THREAD

**Issue by Magicloud** [microsoft/windows-rs#665]
There should 5 as:
- RequestSetImageFeedAsync
- TryRemoveImageFeed
- GetImageStream
- SetImageFileAsync
- SetImageStreamAsync

But 0.7.0 only generates one for `TryRemoveImageFeed`.

**Comment by Nerixyz** [comment]
Related to #594. You need to add all dependencies to your `build.rs` (So `IAsyncOperation`, `SetImageFeedResult`, `Uri`, `IRandomAccessStream`, `IStorageFile` and `IAsyncAction`) so the methods will be generated.

**Comment by Magicloud** [comment]
@Nerixyz Thanks.

**Comment by kennykerr** [comment]
As of 0.12.0 (#896), methods are no longer omitted so this should no longer be an issue.
