### ISSUE TITLE
Documenting or improving the ergonomics of IAudioClient::GetService

### ISSUE THREAD

**Issue by udoprog** [microsoft/windows-rs#668]
Hey,

I was recently trying to figure out how to port an existing piece of code using winapi to windows-rs (awesome project btw). One part that was somewhat under-documented was how to interact with wasapi (a.k.a. CoreAudio).

I noted that the deeper you get into the API, the more mangling you had to do. In particular the only sound way to get an `IAudioRenderClient` client appears to be to transmute the pointer returned from calling `IAudioClient::GetService`. To my understanding this is the correct way to use or wrap the unsafe API, because the returned object is a pointer to an instance of `IAudioRenderClient` with a single refcount. And eventually dropping that object in Rust, should cause it to be released.

```rust
let audio_client = IAudioClient = todo!();

let render_client = unsafe {
    let mut render_client = ptr::null_mut();

    audio_client
        .GetService(
            &IAudioRenderClient::IID,
            &mut render_client
        )
        .ok()?;

    debug_assert!(!render_client.is_null());
    // NB: can this be avoided?
    mem::transmute::<_, core::IAudioRenderClient>(render_client)
};
```

Is this currently the most idiomatic way to use `IAudioClient::GetService`?

# Full Example

Here I'll be posting the more-or-less full code sample in the hopes that others endeavoring to use these APIs have a bit more guidance.

This example opens the default audio device with the default mix format for *rendering*.

```rust
/// bindings - it's a bit superfluous, sorry!

fn main() {
    windows::build!(
        Windows::Win32::CoreAudio::*,
        Windows::Win32::Audio::*,
        Windows::Win32::Multimedia::{
            WAVEFORMATEX,
            WAVEFORMATEXTENSIBLE,
            WAVE_FORMAT_PCM,
            WAVE_FORMAT_IEEE_FLOAT,
            KSDATAFORMAT_SUBTYPE_IEEE_FLOAT,
        },
        Windows::Win32::StructuredStorage::PROPVARIANT,
        Windows::Win32::Com::{CoTaskMemAlloc, CoTaskMemFree, CLSIDFromProgID, CoInitializeEx, CoCreateInstance, CLSCTX},
        Windows::Win32::WindowsAndMessaging::GetForegroundWindow,
    )
}
```

```rust
use bindings::Windows::Win32::CoreAudio as core;
use bindings::Windows::Win32::Multimedia as mm;
use std::mem;
use std::ptr;
use windows::Interface;

pub const CLSCTX_INPROC_SERVER: u32 = 0x1;
pub const CLSCTX_INPROC_HANDLER: u32 = 0x2;
pub const CLSCTX_LOCAL_SERVER: u32 = 0x4;
pub const CLSCTX_REMOTE_SERVER: u32 = 0x10;

// Note: this appears like it's on its way soon:ish
// See: https://github.com/microsoft/win32metadata/issues/203
pub const CLSCTX_ALL: u32 =
    CLSCTX_INPROC_SERVER | CLSCTX_INPROC_HANDLER | CLSCTX_LOCAL_SERVER | CLSCTX_REMOTE_SERVER;

fn main() -> windows::Result<()> {
    windows::initialize_mta()?;

    let enumerator: core::IMMDeviceEnumerator =
        windows::create_instance(&core::MMDeviceEnumerator)?;

    let device = unsafe {
        let mut device = None;

        enumerator
            .GetDefaultAudioEndpoint(core::EDataFlow::eRender, core::ERole::eConsole, &mut device)
            .and_some(device)?
    };

    let audio_client = unsafe {
        let mut audio_client: mem::MaybeUninit<core::IAudioClient> = mem::MaybeUninit::zeroed();

        device
            .Activate(
                &core::IAudioClient::IID,
                CLSCTX_ALL,
                ptr::null_mut(),
                audio_client.as_mut_ptr() as *mut _,
            )
            .ok()?;

        audio_client.assume_init()
    };

    let mix_format = unsafe {
        let mut mix_format = mem::MaybeUninit::<*mut mm::WAVEFORMATEX>::zeroed();
        audio_client.GetMixFormat(mix_format.as_mut_ptr()).ok()?;
        mix_format.assume_init()
    };

    unsafe {
        audio_client
            .Initialize(
                core::AUDCLNT_SHAREMODE::AUDCLNT_SHAREMODE_SHARED,
                core::AUDCLNT_STREAMFLAGS_EVENTCALLBACK,
                0,
                0,
                mix_format,
                ptr::null_mut(),
            )
            .ok()?;
    }

    let render_client = unsafe {
        let mut render_client = ptr::null_mut();

        audio_client
            .GetService(
                &core::IAudioRenderClient::IID,
                &mut render_client
            )
            .ok()?;

        debug_assert!(!render_client.is_null());
        // NB: can this be avoided?
        mem::transmute::<_, core::IAudioRenderClient>(render_client)
    };

    Ok(())
}
```

**Comment by tim-weis** [comment]
This is a common pattern in COM programming. The [clock sample](https://github.com/microsoft/windows-rs/blob/master/examples/clock) illustrates how to retrieve COM interface pointers without having to use `mem::transmute` in client code. As an example, here's the [create_dxfactory](https://github.com/microsoft/windows-rs/blob/443c8265cb53925a1637ecd665b25e51f414170b/examples/clock/src/main.rs#L553) implementation:

```rust
fn create_dxfactory() -> Result<IDXGIFactory2> {
    unsafe {
        let mut dxfactory: Option<IDXGIFactory2> = None;
        CreateDXGIFactory1(&IDXGIFactory2::IID, dxfactory.set_abi()).and_some(dxfactory)
    }
}
```

**Comment by udoprog** [comment]
> This is a common pattern in COM programming. The [clock sample](https://github.com/microsoft/windows-rs/blob/master/examples/clock) illustrates how to retrieve COM interface pointers without having to use `mem::transmute` in client code. As an example, here's the [create_dxfactory](https://github.com/microsoft/windows-rs/blob/443c8265cb53925a1637ecd665b25e51f414170b/examples/clock/src/main.rs#L553) implementation:
> 
> ```rust
> fn create_dxfactory() -> Result<IDXGIFactory2> {
>     unsafe {
>         let mut dxfactory: Option<IDXGIFactory2> = None;
>         CreateDXGIFactory1(&IDXGIFactory2::IID, dxfactory.set_abi()).and_some(dxfactory)
>     }
> }
> ```

Nice! I this was a part I was missing. Thanks for the pointer!
