### ISSUE TITLE
Why is struct DROPFILES packed(1)?

### ISSUE THREAD

**Issue by knopp** [microsoft/windows-rs#669]
This causes warning (borrow of packed field is unsafe and requires unsafe function or block (error E0133)) when accessing fields.

**Comment by tim-weis** [comment]
This has me confused, too. First, the technical reason is that the *ShlObj_core.h* SDK header file has an

```cpp
#include <pshpack1.h>
```

directive right at the top, so the packing winds up in the metadata, and re-surfaces in the generated code. In the specific case of [DROPFILES](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/ns-shlobj_core-dropfiles) it appears, that `packed(1)` doesn't change the layout, at least for Intel's x86 and x86_64 architectures. I'm not sure this holds for all architectures, though I believe it is required by Windows' ABI.

It would certainly be nice to have a more versatile structure definition, in case the stronger packing requirement doesn't change the structure layout. The code generator *could* omit the packing attribute, if it can determine, that it is superfluous. The [Layout](https://doc.rust-lang.org/core/alloc/struct.Layout.html) type seems to provide all the required building blocks to determine this.

Except, there's more to structure packing than packing: `packed(1)` also implies `align(1)` (as hinted to under [Type Layout](https://doc.rust-lang.org/reference/type-layout.html), although there is [quite some confusion](https://internals.rust-lang.org/t/conflation-of-alignment-and-packing/10443) on that topic, and the lack of a formal specification doesn't help much).

I suppose the only safe option here is to follow C, which relaxes the alignment requirements for packed structures [on all 3 major C++ compilers](https://godbolt.org/z/Y67db197r). A corollary of this is that you cannot have references into a packed structure without exhibiting undefined behavior. This [tracking issue](https://github.com/rust-lang/rust/issues/82523) illustrates workarounds.

**Comment by kennykerr** [comment]
Right, the packing comes from metadata. If you can make a case for the packing not affecting the struct's layout you can create an issue here to request this be dropped: 

https://github.com/microsoft/win32metadata

**Comment by kennykerr** [comment]
I also created an issue to improve trait coverage for such types. https://github.com/microsoft/windows-rs/issues/656
