### ISSUE TITLE
How to check if a returned HANDLE is NULL?

### ISSUE THREAD

**Issue by udoprog** [microsoft/windows-rs#670]
Hey,

So a few APIs specify that they return a `NULL` `HANDLE` in case of errors, like:
* `CreateEventA` (<https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventa#return-value>)
* `CreateIoCompletionPort` (<https://docs.microsoft.com/en-us/windows/win32/fileio/createiocompletionport#return-value>).

There currently does not seem to be a `NULL` `HANDLE` available for comparison, and since `HANDLE` wraps a pointer-sized integer there's no safe way to access it (all though it could be transmuted). It might even be nice if `HANDLE` has an `is_null` method.

I expect that long term these API's would also be wrapped with error handling, but in the interim, is there anything that can be used to perform the comparison, or maybe I'm missing something?

Thanks!

**Comment by kennykerr** [comment]
"null" is really just zero and the value that Win32 mostly but not exclusively used to indicate an invalid handle. The other common value is -1 or `INVALID_HANDLE_VALUE`. For the zero value you can just use `HANDLE(0)`. Here's an example of both:

https://github.com/microsoft/windows-rs/blob/master/examples/overlapped/src/main.rs

**Comment by udoprog** [comment]
> "null" is really just zero and the value that Win32 mostly but not exclusively uses to indicate an invalid handle. The other common value is -1 or `INVALID_HANDLE_VALUE`. For the zero value you can just use `HANDLE(0)`. Here's an example of both:
> 
> https://github.com/microsoft/windows-rs/blob/master/examples/overlapped/src/main.rs

Cheers! I didn't realize the field for `HANDLE` was public so you could construct it yourself.

**Comment by rylev** [comment]
@kennykerr what speaks against adding a convenience function `T::null()` for types that can be logically null? This would arguably make code lineup with existing examples and idioms from other languages.

**Comment by kennykerr** [comment]
Yes, we could perhaps add something like that. Perhaps we could add both `NULL` (0) and `INVALID` (-1) constants to the `HANDLE` struct as they are both pretty common.
