### ISSUE TITLE
Don't understand what to pass as parameters to FindWindowA method.

### ISSUE THREAD

**Issue by AyashiNoCeres** [microsoft/windows-rs#672]
I'm trying to use the FindWindowA method, the documentation lists this as the parameters. It could just be my ignorance of rust, but I don't understand what this even means. How do I use this?

pub unsafe fn FindWindowA<'a, T0__: IntoParam<'a, PSTR>, T1__: IntoParam<'a, PSTR>>(
    lpclassname: T0__, 
    lpwindowname: T1__
) -> HWND

**Comment by rylev** [comment]
We should do a better job of naming the generic parameters and of documenting how `IntoParam` works. Essentially if an argument takes some type `T: IntoParam<'a, PSTR>` then you can pass anything that implements `IntoParam<'a, PSTR>` which includes among other things `PSTR` itself and normal Rust `String` and `&str` types.
