### ISSUE TITLE
Consuming collections

### ISSUE THREAD

**Issue by raffaeler** [microsoft/windows-rs#684]
I am trying to consume a very simple component.
If I return a string, it works.
If I change the return value to a collection of strings, the projection fails to be created.
(of course I update the winmd and the binary files after this change, I also deleted the target folder to ensure everything is re-created)

Are collections already supported from custom component (it is a .NET component).

Thank you

**Comment by kennykerr** [comment]
Yes, consuming collections should work fine. Here's [an example](https://github.com/microsoft/windows-rs/blob/master/examples/rss/src/main.rs).

**Comment by kennykerr** [comment]
Feel free to share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by raffaeler** [comment]
I was aware it worked on the winrt libraries.
Not sure instead on the custom components. The problem may be on the cswinrt side of course :)

**Comment by raffaeler** [comment]
@kennykerr 
The following is not a complete example, but probably gives you a better idea:

cppwinrt code [**working**]
```
    cout << "MakeQuerySingle" << endl;
    auto single = cat.MakeQuerySingle(to_hstring(xml), L"year", L"1987", L"title");
    cout << "  > " << to_string(single) << endl << endl;

    cout << "MakeQueryMultiple" << endl;
    auto list = cat.MakeQueryMultiple(to_hstring(xml), L"year", L"1987", L"title");

    for (const auto& item : list)
    {
        cout << "  > " << to_string(item) << endl;
    }
```

windows-rs code [**only one method working**]
``` 
    // this compile and runs successfully
    let title = catalog.make_query_single(xml, "year", "1987", "title")?;

    // this does not compile
    // There is no trace of make_query_multiple in the generated code
    let list = catalog.make_query_multiple(xml, "year", "1987", "title")?;
```

The consumed component is the same (the one in cppwinrt is packaged in nuget)

**Comment by kennykerr** [comment]
If a method is missing its probably just #594. Try adding `Windows::Foundation::Collections::IVectorView` to your build script.

**Comment by kennykerr** [comment]
> make_query_single

You're also using a rather old version of the Windows crate. #646 😉

**Comment by raffaeler** [comment]
Yes! That's it, thank you @kennykerr 
I lost some time because, for some reasons, my winmd make ilspy throw.

> You're also using an old version of the Windows crate. #646 😉
You run too fast :-D ... where do I see the latest available crate version?

Thank you

**Comment by raffaeler** [comment]
Hmm, version `0.7.0` does not compile anymore:

```
   Compiling rust_client_console v0.1.0 (H:\dev.git\Experiments\InteropExperiments\WinRTNativeHosting\NativeToManaged\RustClientConsole)
error[E0432]: unresolved import `bindings::managed_component`
 --> src\main.rs:5:5
  |
5 |     managed_component::*,
  |     ^^^^^^^^^^^^^^^^^ could not find `managed_component` in `bindings`

error[E0433]: failed to resolve: use of undeclared type `Calculator`
```

Is the naming convention changed in some way?
I also got squiggles here:
```
use bindings::{
    managed_component::*,
};
```

> The ILSpy bug was fixed. Just grab a newer build.
Thank you, I trusted in the auto-update feature and didn't see the latest release

**Comment by kennykerr** [comment]
Have a closer look at #646 ...

And then change `managed_component` to `ManagedComponent`. 😉

**Comment by raffaeler** [comment]
> Have a closer look at #646 ...
> 
> And then change `managed_component` to `ManagedComponent`. 😉

oops :)

**Comment by raffaeler** [comment]
After adding all of Windows Foundation in the build script, the event appeared in the intellisense.
I will try to use it miming the behavior of cppwinrt and the rust webview2 example.

**Comment by kennykerr** [comment]
The common event handler types are defined in the Windows.Foundation namespace.
