### ISSUE TITLE
Missing documentation for TypedEventHandler and casting in general

### ISSUE THREAD

**Issue by raffaeler** [microsoft/windows-rs#687]
I successfully subscribed an event from my own component using EventHandler:
```
let eh = EventHandler::<AlarmEventArgs>::new(move |s, a| {
        let u = s.as_ref().unwrap();  // this is an object, not an Alarm
        let arg = a.as_ref().unwrap();  // I am aware this is rough, but it is just a test
        println!("Event!: {:?} {:?}", u, arg.Message());
        Ok(())
    });

... 
let t = alarm.Elapsed(eh);
```

Since `s` is an object and it is not typed I'd like to know how to do the following:
1. cast into an `Alarm` object. I tried `into()` without luck. Does the equivalent of `.as<type>()` of cppwinrt exist?
2. use `TypedEventHandler::<Alarm, AlarmEventArgs>` but I quickly get uncomprehensible (to me) error:
```
the trait bound `bindings::Windows::Foundation::TypedEventHandler<bindings::ManagedComponent::Alarm, bindings::ManagedComponent::AlarmEventArgs>: IntoParam<'_, bindings::Windows::Foundation::EventHandler<bindings::ManagedComponent::AlarmEventArgs>>` is not satisfied
the trait `IntoParam<'_, bindings::Windows::Foundation::EventHandler<bindings::ManagedComponent::AlarmEventArgs>>` is not implemented for `bindings::Windows::Foundation::TypedEventHandler<bindings::ManagedComponent::Alarm, bindings::ManagedComponent::AlarmEventArgs>`
```

Can someone clarify how to do those two things?
Thanks!

**Comment by kennykerr** [comment]
> this is an object, not an Alarm

You can use `TypedEventHandler` instead of `EventHandler` to avoid having to cast inside the handler. 

> cast into an Alarm object

You can use [cast](https://docs.rs/windows/0.7.0/windows/trait.Interface.html#method.cast) for this. 

> use TypedEventHandler but I quickly get incomprehensible (to me) error:

The component you're calling has to make the choice to offer `TypedEventHandler` instead of `EventHandler`. The consumer cannot simply switch to a different type.

**Comment by raffaeler** [comment]
> You can use `TypedEventHandler` instead of `EventHandler` to avoid having to cast inside the handler.

got it

> You can use [cast](https://docs.rs/windows/0.7.0/windows/trait.Interface.html#method.cast) for this.

Great, it is exactly what I was looking for.


> The component you're calling has to make the choice to offer `TypedEventHandler` instead of `EventHandler`. The consumer cannot simply switch to a different type.

Got it, I hoped the template code could directly invoke the QI for me. Even if it has a cost at runtime, it would be very useful as in other languages the sender is always an object.
