### ISSUE TITLE
README link invalid

### ISSUE THREAD

**Issue by evandrix** [microsoft/windows-rs#698]
https://github.com/microsoft/windows-rs/readme.md:
...
A more in-depth getting started guide can also be found [here](https://github.com/microsoft/windows-rs/blob/master/docs/getting-started).
...

~~https://github.com/microsoft/windows-rs/blob/master/docs/getting-started~~ https://github.com/microsoft/windows-rs/blob/master/docs/getting-started.md

**Comment by kennykerr** [comment]
Fixed - thanks!
