### ISSUE TITLE
The example is too easy, I have problem with cargo workspace, need some complex example

### ISSUE THREAD

**Issue by ouliuquan** [microsoft/windows-rs#701]
Hi,
     I have see all the example, but they are too simple, can you tech us how to build a complex example?
It will be nice if there are some lib.rs and serveral workspace, now windows::bindings don't work well in the suition.

Thanks for review my question.

**Comment by rylev** [comment]
@ouliuquan thanks for reporting. Unfortunately, there's too little detail in your comment to know how we can help. There are infinite possible ways to use this crate, and while we can keep adding more examples, there's no way we'll know if it helps in your case.

Please post specific and reproducible errors you are seeing we can address your question.
