### ISSUE TITLE
Should PWSTR/PSTR structs be repr(transparent)?

### ISSUE THREAD

**Issue by Awfa** [microsoft/windows-rs#703]
I was looking at the generated code and saw `PWSTR` was repr(C):
```rust
#[repr(C)]
#[derive(
    :: std :: clone :: Clone,
    :: std :: marker :: Copy,
    :: std :: cmp :: Eq,
    :: std :: fmt :: Debug,
)]
pub struct PWSTR(pub *mut u16);
```

and the functions generated like `QueryFullProcessImageNameW` take them in directly:
```rust
#[link(name = "KERNEL32")]
extern "system" {
    pub fn QueryFullProcessImageNameW(
        hprocess: HANDLE,
        dwflags: QueryFullProcessImageName_dwFlags,
        lpexename: PWSTR, // <-- takes in a PWSTR
        lpdwsize: *mut u32,
    ) -> BOOL;
}
```

From the docs on [`repr(transparent)`](https://doc.rust-lang.org/1.26.2/unstable-book/language-features/repr-transparent.html):
> while repr(C) happens to do the right thing with respect to memory layout, it's not quite the right tool for newtypes in FFI. Instead of declaring a C struct, we need to communicate to the Rust compiler that our newtype is just for type safety on the Rust side. This is what repr(transparent) does.

To guarantee that rustc passes the `PWSTR` just like a `*mut u16` when sending it as a parameter thru the ABI, these newtypes should be generated with `repr(transparent)` right?

I saw this on `PSTR` and `BOOL` as well.

**Comment by rylev** [comment]
Good catch - the way things are currently only guarantees that layout will be correct but if the inner type has different ABI requirements than single field structs, this could lead to problems. This probably works fine now, but this should be changed.
