### ISSUE TITLE
Add NULL to IBindCtx

### ISSUE THREAD

**Issue by ArturKovacs** [microsoft/windows-rs#709]
I have an existing code that I'm converting to use `windows-rs`, but I hit an issue. In my code I use `IShellFolder::BindToObject` which can take a NULL pointer for the `IBindCtx` parameter. However it seems that it's not possible to set that parameter to NULL in `windows-rs`.

This also affects `SHCreateItemFromParsingName`.

**Comment by kennykerr** [comment]
You should be able to pass _None_.

**Comment by ArturKovacs** [comment]
You are correct, I did not realize this, thank you! 😊 As far as I'm concerned the issue is resolved.

**Comment by ArturKovacs** [comment]
Something to consider is to add a sentence or two about this in the readme or the getting started document. If it's already there then I missed it, but a search for "null" doesn't yield any useful match in either of those documents.

**Comment by rylev** [comment]
@kennykerr Is it possible for there to be the following impl on for all COM interfaces?

```rust
impl <'a> IntoParam<'a, ISomeInterface> for *mut ISomeInterfaceVTable {}
```

**Comment by kennykerr** [comment]
All convertible parameters now support `None` - this seems like the most natural way to represent this in Rust. An FAQ entry seems appropriate.

Interfaces are not modeled as pointers in Rust so I don't think adding an `impl` ultimately helps all that much. The vtable type should also be private - its not at the moment but that's a technical limitation that I'd like to fix at some point.
