### ISSUE TITLE
Allowing unsafe callbacks

### ISSUE THREAD

**Issue by ajtribick** [microsoft/windows-rs#711]
Some (perhaps all?) callback types would benefit from their types allowing for `unsafe`. For example I have been doing a small experiment to try to convert Winit to use windows-rs, and there are a couple of places where it sets `lpfnWndProc` on the `WNDCLASSEXW` structure to `Some(DefWindowProcW)`. Unfortunately this is not possible (without transmuting) with windows-rs, as `DefWindowProcW` is unsafe but the `WNDPROC` type is defined without the unsafe keyword. It would be useful to have this type being defined as

```rust
type WNDPROC = unsafe extern "system" fn(param0: HWND, param1: u32, param2: WPARAM, param3: LPARAM) -> LRESULT;
```

A similar thing occurs with the `SUBCLASSPROC` callback in the `SetWindowSubclass` call: this also requires the callbacks to be safe, while the functions used in Winit are using pointers in a way that is correctly flagged as unsafe.

**Comment by rylev** [comment]
I agree that these callbacks should be marked as unsafe.

**Comment by kennykerr** [comment]
I'm not sure I understand the problem. Here's an example of setting the wndproc without transmuting:

https://github.com/microsoft/windows-rs/blob/1997ae9fea45158e7e0e7b346dc03073e81bea97/examples/clock/src/main.rs#L405

**Comment by ajtribick** [comment]
In that case, the `wndproc` function is declared as

```rust
extern "system" fn wndproc(
// parameters omitted
    ) -> LRESULT
```

This is allowed, since the function is not declared as being unsafe. If the function had instead been declared

```rust
unsafe extern "system" fn wndproc(
// parameters omitted
) -> LRESULT
```

it would no longer be possible to do that assignment.

In fact, looking at the implementation there, the latter declaration (which currently does not work) would be the correct one to use: by using a safe signature, this function could be called from outside an `unsafe` block and trigger undefined behaviour if the `lparam.0` field does not correspond to a valid pointer.

**Comment by kennykerr** [comment]
Got it, and an `unsafe` function declaration does not prevent the assignment of a "safe" callback. So that seems reasonable to me. Thanks for the explanation!

**Comment by clemenswasser** [comment]
`WNDPROC` and `DefWindowProcW` are still incompatible (Due to `DefWindowProcW` not being `extern "system"`).
A current workaround would be `std::mem::transmute`, but I don't know if its actually safe.

```
|         lpfnWndProc: Some(DefWindowProcW),
|                           ^^^^^^^^^^^^^^ expected "system" fn, found "Rust" fn
|
= note: expected fn pointer `unsafe extern "system" fn(HWND, _, WPARAM, LPARAM) -> LRESULT`
                  found fn item `unsafe fn(_, _, _, _) -> LRESULT {DefWindowProcW::<'_, _, _, _>}`
```

**Comment by lostmsu** [comment]
> I'm not sure I understand the problem. Here's an example of setting lpfnWndProc without transmuting:

@kennykerr see the example above. I could create a local window proc, and call `DefWindowProcW` from it to avoid transmuting, but I can't directly use `DefWindowProcW` as shown above.

**Comment by kennykerr** [comment]
Sorry folks, I'm prone to miss comments on really old closed issues. If there's an issue with callbacks, please open a new issue with a complete but minimal repro. For reference, here are examples of using window procedures:

For the `windows-sys` crate:

https://github.com/microsoft/windows-rs/blob/0.48.0/crates/samples/windows-sys/create_window/src/main.rs

For the `windows` crate: 

https://github.com/microsoft/windows-rs/blob/0.48.0/crates/samples/windows/create_window/src/main.rs

No `transmute` is required. Hope that helps.

**Comment by lostmsu** [comment]
Created https://github.com/microsoft/windows-rs/issues/2556
