### ISSUE TITLE
The position of a pressed WindowEvent state?

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#716]
The pressed state appears under one arm and the position appears under a different arm. Is there a helper function to find the position of a pressed state?
```rust
    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;
        match event {
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                window_id,
            } if window_id == window.id() => *control_flow = ControlFlow::Exit,
            Event::WindowEvent {
                event: WindowEvent::Resized(size),
                ..
            } => {}
            Event::WindowEvent {
                event: WindowEvent::CursorMoved { position, .. },
                ..
            } => {}
            Event::WindowEvent {
                event: WindowEvent::MouseInput { state, button, .. },
                ..
            } => {
                if state == ElementState::Pressed {}
            }
            _ => (),
        }
    });
```

**Comment by robmikh** [comment]
If you're referring to the [`WM_LBUTTONDOWN`](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-lbuttondown) window message, the LPARAM will contain the coordinates in the low and high word (x and y respectively).

However your snippet seems to show usage of the `winit` crate. If that's what you're using, I'd suggest filing an issue there.

**Comment by MRahilly** [comment]
Thanks and, yes, it is the winit crate. I am trying to turn the minesweeper sample into a Rust version of the Blocks sample. So an interop with classic Win32 is needed then.

**Comment by kennykerr** [comment]
The [Clock example](https://github.com/microsoft/windows-rs/blob/master/examples/clock/src/main.rs) illustrates how to respond to window messages with nothing but the Windows crate.
