### ISSUE TITLE
Events with the Rust Crate for Windows

### ISSUE THREAD

**Issue by MRahilly** [microsoft/windows-rs#721]
Does Rust have its own preferred mouse click event handling so that Win32 and WinRT mouse handling code will need to be replaced in time to be good Rust code rather than using interop?

**Comment by kennykerr** [comment]
There's no UI/event handling standard in Rust that I'm aware of.

**Comment by MRahilly** [comment]
That helps me understand why a sample like Ocr appears to translate to Rust with a smoothness to rival C# while other samples need Win32 interop plumbing. API calls: smooth, message handling: requires plumbing.
