### ISSUE TITLE
default for structs using the "cbSize" pattern doesn't set the correct default

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#722]
For example, WNDCLASSEXA looks like this:

```
            pub struct WNDCLASSEXA {
                pub cbSize: u32,
                ...
```

And the generated default:

```
                fn default() -> Self {
                    Self {
                        cbSize: 0,
                        ...
```

A better default for cbSize would be something like `std::mem::size_of::<WNDCLASSEXA>() as u32`.

**Comment by kennykerr** [comment]
Yes, that would be a great idea. Today, the defaults are basically just zeroed out. The trick is that the metadata provides no information today about this field and how it should be initialized. If the metadata included an attribute to that effect, the Rust bindings could certainly use that to initialize this by default. I'll transfer this issue to the win32 metadata repo for their consideration.

**Comment by kennykerr** [comment]
Hmm, for some reason the transfer feature isn't working. I've created an issue here: https://github.com/microsoft/win32metadata/issues/433

**Comment by damyanp** [comment]
Thanks Kenny!

**Comment by kennykerr** [comment]
Would love a more interesting Win2D example if you have some time. 😉 

https://github.com/microsoft/windows-rs/tree/master/examples

**Comment by damyanp** [comment]
Hmmm…maybe one day….I’m looking into d3d12 samples at the moment…

**Comment by kennykerr** [comment]
I'd love one of those too. 👍
