### ISSUE TITLE
Wildcards for building Win32 APIs don't work in latest git

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#724]
If I depend on `windows = "0.8.0"` then I can generate bindings like this:

```
fn main() {
    windows::build!(
        Windows::Win32::Direct3D12::*,
    );
}
```

If I depend on `windows = { git = "https://github.com/microsoft/windows-rs" }` then I get the following error:

```
error: proc macro panicked
 --> build.rs:2:5
  |
2 | /     windows::build!(
3 | |         Windows::Win32::Direct3D12::*,
4 | |     );
  | |______^
  |
  = help: message: Could not find type def `Windows.Win32.WinRT.IInspectable`
```

Should I expect this to work?

**Comment by kennykerr** [comment]
Ah that's a regression introduced with #719 - I'll get a fix (and test) our shortly.
