### ISSUE TITLE
Many Win32-style enums would be better promoted to module-scope constants

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#727]
Compare the usability of `WM_QUIT` with `D3D12_RESOURCE_BARRIER_TYPE_TRANSITION`:

```
let message = WM_QUIT;
let barrier_type = D3D12_RESOURCE_BARRIER_TYPE::D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
```

The barrier type one is much more awkward to use.  IMO it would be much more convenient to be able to write:

```
let barrier_type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
```

As all the naming conventions were picked with the assumption that no further qualification would be required.

Alternatively, the projection could try and figure out better names:

```
let barrier_type = D3D12_RESOURCE_BARRIER_TYPE::TRANSITION;
```

**Comment by kennykerr** [comment]
Yes, I think that's a good idea. Enums from WinRT APIs tend to already provide scoped names, but Win32 enums are based on C-style enums, as you know. I could make them module-scoped but still preserve their type.

**Comment by kennykerr** [comment]
Blocked on https://github.com/microsoft/win32metadata/issues/442 and https://github.com/microsoft/win32metadata/issues/443

**Comment by MarijnS95** [comment]
If `D3D12_RESOURCE_BARRIER_TYPE` exists as a type used in structs already, I'd prefer simplified variants:

```rust
let barrier_type = D3D12_RESOURCE_BARRIER_TYPE::TRANSITION;
```

Module-scope constants could simply reference those variants I guess?

**Comment by damyanp** [comment]
I was going to propose something like this originally, but there's a couple of drawbacks that it'd be interesting to get your take on.  Firstly, it diverges from what these things are called in other tools or languages.  For example, being able to search for D3D12_RESOURCE_BARRIER_TYPE_TRANSITION and get hits in C++ and Rust is pretty valuable.  Tools such as PIX or the debug layer display the Win32 ABI names for these types, so as it diverges we'll be asking developers to make the translation in their head.

The second issue, which is more of an implementation detail, is that there isn't always a mechanical way to reliably generate the simplified names.  This can be addressed with enough determination :)

**Comment by kennykerr** [comment]
Yes, searchability and portability is very valuable. Having already tried it, there are definitely a lot of edge cases that don't work well when you try to shorten the names. The metadata also doesn't deal with these constants consistently. Some are enums, some are constants, so in the end I'm also looking for more consistency in how this is presented in Rust. Scoping these also means that *all* of them must be generated as bindings. This is very problematic if you refer to an API that say uses `WIN32_ERROR` and suddenly your generated `windows.rs` file has an extra few thousand lines of code.

**Comment by kennykerr** [comment]
Yes, renaming stuff is hard and I ultimately went with preserving (#646) the original names everywhere (the [win32 metadata](https://github.com/microsoft/win32metadata/) project has taken the same originalist approach). The challenge is to make the bindings as rich/useful as possible while letting the developer limit/filter as much as possible to keep build time/complexity under control. That's why I'd like fine-grained filtering and not force huge chunks of code to be generated. The flip side is having pre-generated bindings that include everything (#432) but we're a ways from getting that to work.

**Comment by MarijnS95** [comment]
@kennykerr That's only casing, not stripping/deduplicating enum variant names, right? I agree on keeping the names similar, using original casing wherever possible. Tools like `rust-analyzer` do a good job helping one find symbols, though.

Unless I misunderstood you can still have fine-grained control over generated code if enum variants have the redundant part of the name stripped off? Again, I'm okay with module-level `D3D12_RESOURCE_BARRIER_TYPE_TRANSITION` or associated enum variant `D3D12_RESOURCE_BARRIER_TYPE::TRANSITION` (no need to strip off `D3D12` even if implied by the module, I guess?), but `D3D12_RESOURCE_BARRIER_TYPE::D3D12_RESOURCE_BARRIER_TYPE_TRANSITION` is too verbose for me.

**Comment by damyanp** [comment]
Thanks!  That makes the code so much nicer to read!

It'd be nice if generating bindings for an enum also generated the bindings for all of the enum fields.

For example, if I build "WNDCLASS_STYLES", I'd want to get "CS_HREDRAW" without having to list them manually.

**Comment by MarijnS95** [comment]
@kennykerr What qualifies as "scoped enum"? Just updated a local project to this and it seems `EXCEPTION_DISPOSITION` would be a nice fit for `ScopedEnum` since its variants don't have a prefix equivalent to the enum type?

```cs
// Windows.Win32.System.Kernel.EXCEPTION_DISPOSITION
public enum EXCEPTION_DISPOSITION
{
	ExceptionContinueExecution,
	ExceptionContinueSearch,
	ExceptionNestedException,
	ExceptionCollidedUnwind
}
```

**Comment by kennykerr** [comment]
@MarijnS95 The `ScopedEnum` attribute is required. https://github.com/microsoft/win32metadata/issues/443

**Comment by MarijnS95** [comment]
@kennykerr Sure, just asking whether `EXCEPTION_DISPOSITION` would qualify for that attribute in the first place?

**Comment by MarijnS95** [comment]
@kennykerr Supposedly this enum lives in a `typedef enum` - but the `CamelCase` instead of `SHOUTY_SNAKE_CASE` name seems to differentiate it from module-level constants. However, it's probably not worth the hassle.

Any comment on associated constants in https://github.com/microsoft/windows-rs/issues/727#issuecomment-838261077 though?

**Comment by MarijnS95** [comment]
> I don't really mind either way, but I'm not in favor of removing prefixes as it deviates too much from existing docs and samples in other languages.

I was thinking about having it both ways: a module-level constant, and a prefix-stripped variant aliasing that module-level constant. It's extra lines in `windows.rs` though, and useless if no-one ends up using it. I would use it as I find the `TYPE::Variant` hierarchy nicer to read than `TYPE_VARIANT` despite making it harder for others to search around in my codebase.

> Do you mean use `WNDCLASS_STYLES::*` as a shorthand for all of the constants? A concern is that it deviates from the Rust `use` declaration syntax which may be confusing if developers want to copy it over.

Yeah that wouldn't work in Rust - better not do that then especially if we're not generating associated constants as aliases anyway.

**Comment by roblabla** [comment]
One downside of this is that when generating `        Windows::Win32::System::Diagnostics::Debug::WIN32_ERROR`, none of the associated constants are generated anymore. The only way to get all of them is to generate `Windows::Win32::System::Diagnostics::Debug::*`, which is a bit more than necessary.

**Comment by kennykerr** [comment]
@roblabla yes that's a tradeoff I'm still wrestling with. 

@mikebattista are there plans to reduce the size of the `Windows::Win32::System::Diagnostics::Debug` namespace or move the common `WIN32_ERROR` type to a less cluttered namespace?

> I think when generating a scoped enum, all its module-scope constants should be generated as well.

The trouble is that it is often the case that the particular error code isn't needed where the value is simply checked for success/failure and passed on to some `Result` object for propagation. Such large enums can really clutter up the the generated bindings. Generating all of the WIN32_ERROR constants amounts to over 3,000 extra lines of code.

**Comment by mikebattista** [comment]
@kennykerr we could move WIN32_ERROR and GetLastError to the Foundation namespace. Would that work?

**Comment by roblabla** [comment]
Hmm. While this is true for `WIN32_ERROR`, there are many other enums that are rather small and currently live in very cluttered namespaces too (VER_FLAGS above). Those would have minimal impact in being always generated when the type is present.

Another avenue that could fix it would be giving the ability to have a prefix on wildcard, e.g. `build!(        Windows::Win32::System::WindowsProgramming::VER_*)`. It's a bit of a bandaid though.

**Comment by mikebattista** [comment]
In the latest metadata, VER_FLAGS is currently in a much more scoped Windows.Win32.System.SystemInformation namespace.

The SystemServices and WindowsProgramming namespaces won't exist anymore once we're done refactoring.

**Comment by kennykerr** [comment]
Another option is to treat the scoped enums as follows: if the build macro only includes specific constants like `ERROR_PATH_NOT_FOUND` then only the listed constants are defined, but if the build macro includes the enum type itself like `WIN32_ERROR` then all of its enclosing constants are included. How does that sound? I've been trying to keep as close to Rust syntax and semantics as possible but this sounds like it could be useful.

**Comment by kennykerr** [comment]
Thanks @mikebattista, I'm not sure whether moving it would help. I am curious what the difference is between `Windows::Win32::Foundation` and `Windows::Win32::System` but that's a different topic. 😊

**Comment by mikebattista** [comment]
There's nothing in Windows.Win32.System so I'm not sure what you're referring to there.

**Comment by kennykerr** [comment]
I mean how do you decide whether something is in `Foundation` vs `System::*` or somewhere else? With WinRT, `Windows.Foundation` is for things that are core to WinRT (e.g. collections and async support) without which other APIs could not be defined.

**Comment by mikebattista** [comment]
There is a need to put common shared types like HANDLE, HWND, string types, etc. in a shared namespace. Foundation is currently the plan for that to align with Windows.Foundation. The expectation would be that Foundation would always be included like Windows.Foundation for WinRT or System for .NET. Given that WIN32_ERROR and GetLastError are used with many APIs, it's a possible candidate for that Foundation namespace. The goal is to improve discovery of the basic things you need and minimize needing to add seemingly obscure namespace references just to use APIs in some other completely unrelated namespace.

System.* is for system-level APIs that are mostly self-contained and not as commonly required as Foundation APIs would be: System.Memory, System.Power, System.Threading, etc. If you're using System.Memory you're not necessarily also using System.Power.  If you think APIs like CreateFileMapping and VirtualAlloc should be in Foundation, that would be a separate discussion.

**Comment by kennykerr** [comment]
Ah yes,  I remember us chatting about a common namespace that others could depend on to keep circular references to a minimum.

**Comment by kennykerr** [comment]
So yes, I'd err on the side of keeping it to a minimum and GetLastError doesn't seem like it needs to be there to reduce dependencies.

**Comment by mikebattista** [comment]
Thanks. It's a work in progress so happy to iterate based on feedback on where APIs belong.

For sure, though, I want to get rid of SystemServices and WindowsProgramming.
