### ISSUE TITLE
Win32 nano-COM factory functions should return constructed interface

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#733]
I've found myself writing adapters like this:

```
fn GetDebugInterface<T: Interface>() -> Result<T> {
    let mut interface = None;
    unsafe { D3D12GetDebugInterface(&T::IID, interface.set_abi()).and_some(interface) }
}
```

Used like this:

```
let debug = GetDebugInterface::<ID3D12Debug>()?;
```

Any thoughts on detecting functions that follow this pattern and wrapping them in this way instead?

**Comment by kennykerr** [comment]
Yes I've been meaning to apply this transformation automatically. 😊

**Comment by kennykerr** [comment]
Enjoy!

**Comment by damyanp** [comment]
Awesome, that was super quick :)
