### ISSUE TITLE
GetDefaultAudioEndpoint crashes program

### ISSUE THREAD

**Issue by Axofade** [microsoft/windows-rs#734]
Hey,
I'm trying to get the default audio endpoint but calling GetDefaultAudioEndpoint crashes my program with the following error:
`exit code: 0xc0000005, STATUS_ACCESS_VIOLATION`

I have also uploaded the whole project to github: https://github.com/Axofade/audio

I have tried fixing this issue for quite some time but couldn't get it to work.

```rust
fn main() {
    unsafe {
        let mut res = CoInitialize(std::ptr::null_mut());
        if res.is_err() {
            panic!("Failed to init '{}'", res.message());
        }

        let mut enumerator: *mut IMMDeviceEnumerator = mem::zeroed();
        
        res = CoCreateInstance(&MMDeviceEnumerator, None, CLSCTX::CLSCTX_ALL, &IMMDeviceEnumerator::IID, &mut enumerator as *mut *mut IMMDeviceEnumerator as *mut _ );
        if res.is_err() {
            panic!("Failed to create inst '{}'", res.message());
        }

        let mut endpoint = None;

        let res = (*enumerator).GetDefaultAudioEndpoint(EDataFlow::eAll, ERole::eConsole, &mut endpoint);
    }
}
```

Any thoughts on how to fix this?

**Comment by Nerixyz** [comment]
You should use the functions provided by the crate.
Instead of ` CoInitialize(std::ptr::null_mut())`, you should use `windows::initialize_sta`. And to create an instance you should use `windows::create_instance`.

This is the version I came up with. `EDataFlow::eAll` didn't work, so I used `EDataFlow::eCapture` instead ([Here](https://github.com/dorba/netcoreaudio/blob/d6aa952bdae9849c2a1f9ba91e15d295e730d578/CoreAudioTests/MMDeviceApi/IMMDeviceEnumeratorTest.cs#L56) they say it should always preduce `E_INVALIDARG`.

```rust
use bindings::Windows::Win32::{
    CoreAudio::{EDataFlow, ERole, IMMDeviceEnumerator, MMDeviceEnumerator},
    SystemServices::PWSTR,
};
use windows::{create_instance, initialize_sta, Result};

fn main() -> Result<()> {
    initialize_sta()?;

    let enumerator = create_instance::<IMMDeviceEnumerator>(&MMDeviceEnumerator)?;

    let device = unsafe {
        let mut device = None;
        enumerator
            .GetDefaultAudioEndpoint(EDataFlow::eCapture, ERole::eConsole, &mut device)
            .and_some(device)?
    };

    let mut id = PWSTR::NULL;
    unsafe { device.GetId(&mut id).ok()? };

    println!("ID: {}", unsafe { read_to_string(id) });

    Ok(())
}

/// This function is from the `spellchecker` example:
/// https://github.com/microsoft/windows-rs/blob/master/examples/spellchecker/src/main.rs#L104-L118
unsafe fn read_to_string(ptr: PWSTR) -> String {
    let mut len = 0usize;
    let mut cursor = ptr;
    loop {
        let val = cursor.0.read();
        if val == 0 {
            break;
        }
        len += 1;
        cursor = PWSTR(cursor.0.add(1));
    }

    let slice = std::slice::from_raw_parts(ptr.0, len);
    String::from_utf16(slice).unwrap()
}
```

**Comment by Axofade** [comment]
Sweet, i didn't even know initialize_sta and create_instance existed ty.

**Comment by Axofade** [comment]
@Nerixyz one last question:
What args would you use for https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/CoreAudio/struct.IMMDevice.html#method.Activate

**Comment by Nerixyz** [comment]
This is similar to the implementation of [`create_instance`](https://github.com/microsoft/windows-rs/blob/master/src/runtime/com.rs#L16-L23):

```rust
let client: IAudioEndpointVolume = unsafe {
    let mut client = None;

    device
        .Activate(&IAudioEndpointVolume::IID, CLSCTX::CLSCTX_ALL.0, std::ptr::null_mut(), client.set_abi())
        .and_some(client)?
};
```

You can then print e.g. the channel count:

```rust
let mut channel_count = 0;
unsafe { client.GetChannelCount(&mut channel_count).ok()? }
println!("ChannelCount: {}", channel_count);
```

**Comment by Nerixyz** [comment]
On a sidenote: It seems like `AUDCLNT_E_DEVICE_INVALIDATED`, `AUDCLNT_E_SERVICE_NOT_RUNNING` and other errors are not generated.

**Comment by Axofade** [comment]
Thanks!

**Comment by kennykerr** [comment]
If there any missing API definitions, please report them here: https://github.com/microsoft/win32metadata/issues

**Comment by Nerixyz** [comment]
> 
> 
> If there any missing API definitions, please report them here: https://github.com/microsoft/win32metadata/issues

I opened microsoft/win32metadata#445
