### ISSUE TITLE
Cannot call QueryInterface-like APIs with "NULL" for the ppv parameter

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#737]
For example, many D3D12 APIs, such as D3D12CreateDevice, operate in a mode where the runtime validates parameters if NULL is passed for the ppv parameter.  Apps often use this to probe whether or not a particular adapter meets their needs, but without performing the heavy-weight, driver-loading, work required to construct and then destruct the object.

See for example https://github.com/microsoft/DirectX-Graphics-Samples/blob/cab614fc3b2ac880f1909c40a485423649940b0d/Samples/Desktop/D3D12HelloWorld/src/HelloWindow/DXSample.cpp#L97

**Comment by damyanp** [comment]
I always forget about this case, sorry for not bringing it up earlier before #735 was completed.  I'd be interested what you think right bindings would look like to support this scenario - it's not obvious to me.

**Comment by kennykerr** [comment]
Yikes, I was not aware of this convention. Thanks for letting me know. I'll noodle on that.

**Comment by damyanp** [comment]
In case anyone else encounters it, here is my workaround:

```rust
    // let mut adapter_: Option<IDXGIAdapter1> = ...

    // We need the variant where we pass in NULL for the outparam.
    #[link(name = "d3d12")]
    extern "system" {
        pub fn D3D12CreateDevice(
            padapter: ::windows::RawPtr,
            minimumfeaturelevel: D3D_FEATURE_LEVEL,
            riid: *const ::windows::Guid,
            ppdevice: *mut *mut ::std::ffi::c_void,
        ) -> ::windows::HRESULT;
    }

    // Check to see whether the adapter supports Direct3D 12, but
    // don't create the actual device yet.
    if D3D12CreateDevice(
        adapter.abi(),
        D3D_FEATURE_LEVEL::D3D_FEATURE_LEVEL_11_0,
        &ID3D12Device::IID,
        std::ptr::null_mut(),
    )
    .is_ok()
    {
        return Ok(adapter);
    }
```

```

**Comment by kennykerr** [comment]
As Rust doesn't support overloads, I'm thinking of adding an "overload" with a suffix like `_query` that simply provides the non-generic parameters. So you would be able to call the generic `D3D12CreateDevice` or the non-generic `D3D12CreateDevice_query`.

**Comment by damyanp** [comment]
Bikeshed: maybe `_validate` for this case?

If we're willing to really special case this one, I think we'd still want the generic parameters, so I could write: `D3D12CreateDevice_validate::<ID3D12Device2>(&adapter, D3D_FEATURE_LEVEL_11_0)`

and avoid having to deal with IIDs.

One thing I'm not sure of is how universal this convention is.  QueryInterface, for example, does not behave this way.  We may be looking a another attribute for the metadata to identify functions following this pattern.

**Comment by kennykerr** [comment]
Yeah that's why I don't want to call it something specific like "validate" since that's DX-specific and there's no metadata to say that this is supported on any given API. I basically just want to have a fallback for non-generic/non-specialized call sites. I also plan to support things like `retval` so it may be useful to just have a non-specialized overload, perhaps `_raw`.

**Comment by kennykerr** [comment]
But if you want something more specific like the example above where there's an actual "validate" overload then you'll need to work with the [win32metadata](https://github.com/microsoft/win32metadata/) project to add such an attribute.

**Comment by damyanp** [comment]
Although we don't have enough to know the "validate" versus "some other meaning for null" semantic, the metadata does already indicate that the ppv parameter is `[Optional]`.  If we could come up with a generic word that means "don't return the interface" then maybe we already have enough?

**Comment by kennykerr** [comment]
Ah, I see `CoCreateInstance` and `D2D1CreateDevice` are not optional but `D3D12CreateDevice` is. That might work!
