### ISSUE TITLE
`BSTR` needs a `Clone` implementation

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#738]
https://github.com/microsoft/windows-rs/pull/707#issuecomment-828487160

**Comment by MarijnS95** [comment]
@kennykerr Replying to https://github.com/microsoft/windows-rs/pull/707#issuecomment-828487160 here: I guess `BSTR` is considered an owned type that would need to copy the pointed-to data it actually owns?

**Comment by kennykerr** [comment]
Yes, it implies a special allocator so there is a `Drop` implementation that calls `SysFreeString`. A derived `Clone` implementation would simply copy the pointer, which would cause copies to free the same `BSTR`. A correct `Clone` implementation needs to make a deep copy of the `BSTR` allocation.
