### ISSUE TITLE
Cannot call D3D12CreateDevice, it triggers E0632

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#750]
```rust
        let device = unsafe {
            D3D12CreateDevice::<ID3D12Device>(adapter, D3D_FEATURE_LEVEL::D3D_FEATURE_LEVEL_11_0)?
        };
```

```
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
   --> examples\d3d12\src\main.rs:269:33
    |
269 |             D3D12CreateDevice::<ID3D12Device>(adapter, D3D_FEATURE_LEVEL::D3D_FEATURE_LEVEL_11_0)?
    |                                 ^^^^^^^^^^^^ explicit generic argument not allowed
```

**Comment by kennykerr** [comment]
Sigh, looks like this isn't supported with the (simpler) way I now represent functions with convertible parameters (https://github.com/microsoft/windows-rs/issues/677). I'll probably have to revert https://github.com/microsoft/windows-rs/pull/694 to make this work. 

Note, you can probably work around this by using type inference:

```rust
let device: ID3D12Device = unsafe {
    D3D12CreateDevice(adapter, D3D_FEATURE_LEVEL::D3D_FEATURE_LEVEL_11_0)?
};
```

I'm not sure its worth giving up the simpler syntax unless there's a scenario that doesn't work.

**Comment by damyanp** [comment]
Thanks; this smells to me a bit like me trying to apply C++ expectations to Rust.

**Comment by rylev** [comment]
This is indeed the one difference between traditional generic parameters and the `impl Trait` syntax. I personally think it's worth this cost to keep the much simpler function signatures.

**Comment by damyanp** [comment]
One case I found that doesn't naturally lend itself (or, more likely, I don't know how to do it yet) is using this with `if let`.

For example, this happens to work because D3D12GetDebugInterface doesn't use `impl Trait`:

```rust
if let Ok(debug) = D3D12GetDebugInterface::<ID3D12Debug>() {
    debug.EnableDebugLayer();
}```

I couldn't think of a way to switch this to use type inference and about making an extra variable:


```rust
let debug_ : Result<ID3D12Debug> = D3D12GetDebugInterface();
if let Ok(debug) = debug_ {
    debug.EnableDebugLayer();
}
```

Other than that, type inference has been working fine for me.

**Comment by rylev** [comment]
The way you've handled it, is the right way currently. You don't have to use the a different name for the `debug_` binding since Rust supports variable shadowing. 

There is work in the Rust compiler on making local type inference possible which might make it possible in the future to do something like this:

```rust
if let Ok(debug: ID3D12Debug) = D3D12GetDebugInterface() {
    debug.EnableDebugLayer();
}
````
