### ISSUE TITLE
IMMDeviceEnumerator::RegisterEndpointNotificationCallback

### ISSUE THREAD

**Issue by Axofade** [microsoft/windows-rs#763]
Hey,

I would like to register a client notifcation callback via IMMDeviceEnumerator::RegisterEndpointNotificationCallback.
How would i go about doing this and how do i handle the callbacks?

https://docs.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immdeviceenumerator-registerendpointnotificationcallback

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/CoreAudio/struct.IMMDeviceEnumerator.html#method.RegisterEndpointNotificationCallback

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/CoreAudio/struct.IMMDeviceEnumerator.html

Thanks!

**Comment by kennykerr** [comment]
In this case, the callback is a COM interface that you must implement. This isn't yet supported. #81

**Comment by Axofade** [comment]
Oh alright, is there any way for me to implement this myself?
If so i'm not really sure where to start

Thanks!

**Comment by kennykerr** [comment]
Anything's possible but it is pretty complicated as you have to build up the COM vtable by hand. I'm back focusing on implementation support #81 so hopefully I'll get to this soonish.

**Comment by kennykerr** [comment]
COM implementation support is steadily improving. You should now be able to use the Windows crate to implement interfaces like `IMMNotificationClient`.

**Comment by Subwater** [comment]
My apologize for the grave dig on this one!  

I am currently working on a project that requires the use of this interface and was wondering if you (@Axofade) have figured out how to implement this interface into your code?  I looked at your repos and couldn't find anything regarding this interface.  

Do either of you have any examples on how to properly use `IMMNotificationClient` this interface within the `windows-rs` realm?

**Comment by kennykerr** [comment]
The `windows` crate now supports implementing COM interfaces.
