### ISSUE TITLE
How do I use `HRESULT`?

### ISSUE THREAD

**Issue by ibigbug** [microsoft/windows-rs#765]
Can't find a good match of this type from https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/index.html?search=hresult

So how can I import the type and write a function like this:

```rust
fn return_hresult() -> HRESULT {
  TODO
}
```

**Comment by MarijnS95** [comment]
Those are the docs for the generated bindings, `HRESULT` is implemented and documented in the `windows-rs` crate itself: https://docs.rs/windows/0.9.1/windows/struct.HRESULT.html

That said afaik/imo those types should be reachable/documented from/in the binding docs as well.

**Comment by ibigbug** [comment]
thank you!

agreed, I had an assumption that the binding docs would have everything in there.

**Comment by MarijnS95** [comment]
@ibigbug I've created https://github.com/microsoft/windows-docs-rs/pull/4 for this. Either `windows-docs-rs` should include the `windows` crate, or link to it through unstable `--extern-html-root-url`.
