### ISSUE TITLE
How to convert WIN32_ERROR into human readable string?

### ISSUE THREAD

**Issue by ibigbug** [microsoft/windows-rs#767]
i.e. how to map the number from [`GetLastError()`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Debug/fn.GetLastError.html) into this list https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499- ?

**Comment by MarijnS95** [comment]
@ibigbug I think I linked you the documentation in https://github.com/microsoft/windows-rs/issues/765 where [`HRESULT::from_win32`](https://docs.rs/windows/0.9.1/windows/struct.HRESULT.html#method.from_win32) is documented. You should subsequently be able to `Debug` or [`message()`](https://docs.rs/windows/0.9.1/windows/struct.HRESULT.html#method.message) the `HRESULT` to get something human readable.

**Comment by ibigbug** [comment]
thanks, exactly what I was looking for :)

**Comment by rylev** [comment]
We might want to add this to the FAQ documentation.
