### ISSUE TITLE
No PKEY_* constants

### ISSUE THREAD

**Issue by ashinan** [microsoft/windows-rs#768]
I am trying to get PKEY_Device_FriendlyName property but I cannot  find where the constant is defined.

As a matter of fact, I can find none of PKEY_* series from the documentation: https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/WindowsPropertiesSystem/index.html

code: 
```rust
        let mmd = get_immdevice_somehow();
        let mut props = None;
        let mut props = mmd
            .OpenPropertyStore(STGM_READ as u32, &props)
            .and_some(props)
            .unwrap();

        let name;
        props.GetValue(
            bindings::Windows::Win32::WindowsPropertiesSystem::PKEY_Device_FriendlyName,
            &name,
        );
```

build.rs
```
fn main() {
    windows::build!(
        Windows::Win32::SystemServices::PWSTR,
        Windows::Win32::Audio::*,
        Windows::Win32::CoreAudio::*,
        Windows::Win32::StructuredStorage::*,
        Windows::Win32::WindowsPropertiesSystem::*,
    );
}
```

error:
```
error[E0425]: cannot find value `PKEY_Device_FriendlyName` in module `bindings::Windows::Win32::WindowsPropertiesSystem`
  --> src\main.rs:24:64
   |
24 |             bindings::Windows::Win32::WindowsPropertiesSystem::PKEY_Device_FriendlyName,
   |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^ not found in `bindings::Windows::Win32::WindowsPropertiesSystem`
```

Am I doing something wrong?

**Comment by kennykerr** [comment]
This was fixed a few weeks back in metadata... https://github.com/microsoft/win32metadata/issues/339

But I haven't yet got around to plumbing in support for such constants here:

https://github.com/microsoft/windows-rs/blob/1d7c40e02ef6fbace319865dea6d494ea67cb75a/crates/gen/src/types/constant.rs#L43-L55

**Comment by ashinan** [comment]
@kennykerr 
Is there any workaround for this? As far as I know, it is possible to declare those values by myself in C++ or C#, but I have no idea how to do that in Rust.

**Comment by tim-weis** [comment]
You can construct a `Guid` using its associated [`from_values()`](https://github.com/microsoft/windows-rs/blob/510aab24fe511bfd8b5a26868a5ca99691cf03de/src/runtime/guid.rs#L38-L45) function. That's a `const` function and can be used to define constants. The values for the `PKEY_*` GUIDs can be found in the Windows SDK header file *functiondiscoverykeys_devpkey.h*.

The following defines the `PKEY_Device_FriendlyName` constant:

```rust
        use windows::Guid;
        const PKEY_Device_FriendlyName: Guid = Guid::from_values(
            0xa45c254e,
            0xdf1c,
            0x4efd,
            [0x80, 0x20, 0x67, 0xd1, 0x46, 0xa8, 0x50, 0xe0],
        );
```

**Comment by monax3** [comment]
This was enough for me for these and other missing constants:
```Rust
extern "C" {
    pub static PKEY_DeviceInterface_FriendlyName: PROPERTYKEY;
    pub static PKEY_Device_FriendlyName: PROPERTYKEY;
}
```
I don't know which lib they get pulled in from but they're there.

**Comment by tim-weis** [comment]
@monax3 Those symbols are exported by Uuid.lib.
