### ISSUE TITLE
How to generate different definitions of CONTEXT?

### ISSUE THREAD

**Issue by gladiator** [microsoft/windows-rs#774]
I'm in a situation where I'm using [GetThreadContext](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Debug/fn.GetThreadContext.html) and [SetThreadContext](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Debug/fn.SetThreadContext.html) and it seems that the only version of [CONTEXT](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Debug/struct.CONTEXT.html) being generated is targeted towards ARM64.  What is the recommended way to have my target specific definition generated or is there none at this moment?

**Comment by kennykerr** [comment]
An update to the win32 metadata is about to land that provides arch-specific definitions of such structs. I then just need to update the Windows crate to detect which target is being built and then generate the appropriate definitions.

**Comment by MarijnS95** [comment]
@kennykerr Is this something that ties in with #770 in that `src/bindings.rs` should both be architecture- and platform-agnostic, or be duplicated for every supported architecture and platform?

**Comment by kennykerr** [comment]
Yes, that may be an issue eventually - there's nothing arch specific there at the moment.

**Comment by gladiator** [comment]
It seems like this was resolved in the recent `0.11.0` update!  I don't think anything relates to this specifically so I'll close this, thanks!
