### ISSUE TITLE
ID3D12GraphicsCommandList1::ClearRenderTargetView - array params could possibly be projected better

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#790]
I'm not sure what the best rust projection would be here - and I don't think that win32metadata has everything needed yet, but I figured we should figure out what can be possible in rust first.

Here's the declaration of ClearRenderTargetView:

```c++
virtual void STDMETHODCALLTYPE ClearRenderTargetView( 
            _In_  D3D12_CPU_DESCRIPTOR_HANDLE RenderTargetView,
            _In_  const FLOAT ColorRGBA[ 4 ],
            _In_  UINT NumRects,
            _In_reads_(NumRects)  const D3D12_RECT *pRects) = 0;
```

Notice the ColorRGBA is explicitly an array for 4 elements.  pRects reads the number of rects specified by NumRects.

Here's the rust binding:

```rust
pub unsafe fn ClearRenderTargetView<'a>(
    &self,
    rendertargetview: impl ::windows::IntoParam<'a, D3D12_CPU_DESCRIPTOR_HANDLE>,
    colorrgba: *const f32,
    numrects: u32,
    prects: *const super::super::UI::DisplayDevices::RECT,
)
```

Ideally, I'd be able to specify the color inline.  Maybe that's possible?  This is what I came up with:
```rust
let clear_color: [f32; 4] = [0.0, 0.2, 0.4, 1.0];
command_list.ClearRenderTargetView(rtv_handle, &clear_color[0], 0, std::ptr::null());
```

It's a bit clunky having to take a reference to the first element of the array.

For pRects, I notice that the rust binding isn't make any use of the relationship between prects and numrects.  Maybe there's not anything it could do with it, but I thought I'd mention it while I was here.

**Comment by samlh** [comment]
>For pRects, I notice that the rust binding isn't make any use of the relationship between prects and numrects. Maybe there's not anything it could do with it, but I thought I'd mention it while I was here.

Ideally, that annotation would let you pass a rust [slice](https://doc.rust-lang.org/std/primitive.slice.html) to the prects parameter.

Something like:
```rust
let clear_color: [f32; 4] = [0.0, 0.2, 0.4, 1.0];
let rects: [RECT; _] = [RECT { /*...*/ }, RECT { /*...*/ }]; // or Vec<RECT> and vec![...]
command_list.ClearRenderTargetView(rtv_handle, &clear_color, &rects[..]);
```

**Comment by kennykerr** [comment]
Yes, I still have a ways to go to make the most of the array metadata.

**Comment by damyanp** [comment]
Similar issue for ExecuteCommandLists:

```
unsafe void ExecuteCommandLists([In] uint NumCommandLists, [In][NativeArrayInfo(CountParamIndex = 0)] ID3D12CommandList* ppCommandLists);
```

(mentioning it here so that it shows up in searchs)

**Comment by kennykerr** [comment]
Sorry for the delay, #1562 adds support for Win32 array parameters and fixes this issue.
