### ISSUE TITLE
Generate/provide `bitflags!`-like helper functions 

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#793]
```rust
        if (DXGI_ADAPTER_FLAG::from(desc.Flags) & DXGI_ADAPTER_FLAG_SOFTWARE)
            != DXGI_ADAPTER_FLAG_NONE
```

Windows-rs already emits bitops for these, I really hope we can get an `fn contains()` and `fn intersects()` in there too like the `bitflags!` crate/macro.

_Originally posted by @MarijnS95 in https://github.com/microsoft/windows-rs/pull/791#discussion_r630512211_

---

The bitflags crate provides lots of useful helpers for interacting with bitflags besides the usual bitwise operations: https://docs.rs/bitflags/1.2.1/bitflags/#methods-1. Windows-rs would benefit from those too. Downside is that these are extra lines in generated output - and using `bitflags!` in generated output might even be slower, though it'd be good to profile that.

**Comment by kennykerr** [comment]
While convenient, I'm not sure how widely useful this feature would be so I'm hesitant to add the code gen at this stage.

**Comment by MarijnS95** [comment]
@kennykerr That's the wrong close reason btw.
