### ISSUE TITLE
Could not find namespace 'Windows.Win32.UI.WindowsAndMessaging'

### ISSUE THREAD

**Issue by markonyango** [microsoft/windows-rs#794]
Hello,

I tried the instructions in the "Get started" video and have hit the following obstacle:

When defining the bindings in my build.rs file, I am told that the binding(s) are not found in the namespace.
This only happens when my Cargo.toml file has the dependencies and build-dependencies defined like they are in the video tutorial:

```
[dependencies]
windows = "0.9.1"

[build-dependencies]
windows = "0.9.1"
```

Once I change them to `windows = { git = "https://github.com/microsoft/windows-rs" }` everything works just fine.

Am I missing a crucial step here?

Repo for reproduction: https://github.com/markonyango/message-box
See the actions log to find that the first commit runs `cargo check` just fine but after I change the dependencies, the build is broken.

I am using: rustc 1.52.1 (9bc8c42bb 2021-05-09) on Windows 10.

**Comment by MarijnS95** [comment]
As you noticed the git version is quite a ways ahead of `0.9.1` where a lot of namespaces were shuffled around. I think the "Get started" video was made with longevity in mind and prepares for `0.10`. In that sense there's nothing "crucial" you're missing, just waiting for the next release on crates.io :grin: 

However, the "Getting started" video in the readme clearly links to a video made for `0.9` without `UI::` in the namespace: https://www.youtube.com/watch?v=-oZrsCPKsn4. Is the newer video hidden somewhere?

**Comment by markonyango** [comment]
Wow, thank you for the fast answer. I now see where I obviously went wrong. The missing "UI" was easy to oversee.
Thank you very much. This can obviously be closed.

**Comment by MarijnS95** [comment]
Hehe, it's always a bit of a mix and match when looking at a git repository while using a crate release and vice versa, glad you noticed and solved it :)
