### ISSUE TITLE
How do I find what path is needed for Types?

### ISSUE THREAD

**Issue by Adarma** [microsoft/windows-rs#799]
How do I determine what path to add in 'build.rs' to be able to use a certain type?
For example I bind some functions:

- 'Windows::Win32::Com::CLSIDFromProgID' which needs a `Guid' type.
- 'Windows::Win32::Automation::GetActiveObject' which needs a `IUnknown' type.

I have tried searching https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/index.html, but I don't see how to add them.

**Comment by kennykerr** [comment]
Function dependencies will automatically be included. Here's a simple example:

https://github.com/microsoft/windows-rs/blob/master/examples/message_box/bindings/build.rs

**Comment by Adarma** [comment]
Ah, ok.
Rust Analyzer just kicked in, and now that I get the function signature popup, I can see that I need to prefix them with `::windows::`.
When I do that it is compiling.
