### ISSUE TITLE
IDispatch and calling methods on IUnknown

### ISSUE THREAD

**Issue by Adarma** [microsoft/windows-rs#803]
Struggling to port this C++ COM code to rust:
I'm not sure how to create an `IDispatch` variable, and how to call `QueryInterface` and `Release` from an `IUnknown`.

```c++
int GetApplication(wchar_t *ProgId, bool AttachToRunning, IDispatch **App)
{
	CLSID ClsId;
	HRESULT HResult = CLSIDFromProgID(ProgId, &ClsId);
	if (FAILED(HResult)) {
		return -1;
	}
	if (AttachToRunning) {
		// NOTE: Get Running Application
		IUnknown *pUnk = NULL;
		HResult = GetActiveObject(ClsId, NULL, &pUnk);
		if (SUCCEEDED(HResult)) {
			HResult = pUnk->QueryInterface(IID_IDispatch, (void **)App);
			if (pUnk) pUnk->Release();
		}
	} else {
		HResult = CoCreateInstance(ClsId, NULL, CLSCTX_LOCAL_SERVER, IID_IDispatch, (void **)App);
	}
	if (FAILED(HResult)) {
		return -2;
	}
	return 0;
}
```

This is my `main.rs` attempt at porting it.
I'm returning to rust after a while away, so I may be doing stupid things.
Can you see what needs to be changed?
Maybe there is a better way to do COM automation in rust.

```rust
use bindings::{
    Windows::Win32::Automation::GetActiveObject,
    Windows::Win32::Com::{
        CLSCTX,
        CoInitialize,
        CLSIDFromProgID,
        CoCreateInstance,
        CoUninitialize,
    },
};

fn main() {
    unsafe {
        let hresult = CoInitialize(std::ptr::null_mut());
        let result = get_application("Excel.Application", true); // Excel for example
        CoUninitialize();
    }
}

fn get_application(prog_id: &str, attach_to_running: bool) -> Result<::windows::IDispatch, ::windows::HRESULT>
{
    let app: ::windows::IDispatch; // I don't know the Type
    unsafe {
        let clsid: *mut ::windows::Guid = std::ptr::null_mut();
        CLSIDFromProgID(prog_id, clsid).ok()?;
        if attach_to_running {
            let punk: *mut Option<::windows::IUnknown> = std::ptr::null_mut();
            GetActiveObject(clsid, std::ptr::null_mut(), punk).ok()?;
            if let Some(unk) = *punk {
                unk.QueryInterface(ID_IDispatch, *app); // I don't know how to call QueryInterface
                unk.Release(); // I don't know how to call Release
            }
        } else {
            let unknown: ::windows::IUnknown;
            app = CoCreateInstance(clsid, unknown, CLSCTX::CLSCTX_LOCAL_SERVER)?; // Different signature to the Win32 docs
        }
    }
    Ok(app)
}
```

**Comment by MarijnS95** [comment]
```rust
            let punk: *mut Option<::windows::IUnknown> = std::ptr::null_mut();
            GetActiveObject(clsid, std::ptr::null_mut(), punk).ok()?;
```

This is wrong. `IUnknown` is already a pointer internally, and - as in your C example - you have to pass a valid pointer to a variable holding a pointer to `IUnknown`. In other words:

```rust
let mut unk = None; // GetActiveObject takes a *mut Option<IUknown, no need to specify that explicitly!
let unk = GetActiveObject(clsid, ..., &mut unk)
    .and_some(unk)?; // and_some unwraps the option and returns E_POINTER if it wasn't assigned to
```

Then, `QueryInterface` is safely implemented through [`fn cast()`](https://microsoft.github.io/windows-docs-rs/doc/windows/trait.Interface.html#method.cast) for every `Interface`:

```rust
let app = unk.cast::<bindings::Windows::Win32::System::OleAutomation::IDispatch>();
```

Finally, all interface objects _own_ an `IUnknown`, which has a `Drop` handler that calls `Release()` when it goes out of scope:

https://github.com/microsoft/windows-rs/blob/7ad7655d19587ab09c5eaf011388a215060c6faf/src/interfaces/unknown.rs#L38-L44

**Comment by Adarma** [comment]
Thanks. 
Since asking I have upgraded to 0.10 from 0.9 and made a little progress, but get an error for the cast:

    let app = unk.cast::<bindings::Windows::Win32::System::OleAutomation::IDispatch>();
                     ^^^^ method not found in `windows::IUnknown`

I'm also not sure how to pass a null `pUnkOuter` to `CoCreateInstance`.

    app = CoCreateInstance(&clsid, std::ptr::null(), CLSCTX_LOCAL_SERVER)?;
                                   ^^^^^^^^^^^^^^^^ the trait `windows::IntoParam<'_, windows::IUnknown>` is not implemented for `*const _`

Any tips on those two points?
Thanks.

I set clsid to `windows::Guid::zeroed()` to prevent a `use of possibly-uninitialized 'clsid'` error.

```rust
use bindings::{
    Windows::Win32::System::OleAutomation::GetActiveObject,
    Windows::Win32::System::OleAutomation::IDispatch,
    Windows::Win32::System::Com::{
        CLSCTX_LOCAL_SERVER,
        CoInitialize,
        CLSIDFromProgID,
        CoCreateInstance,
        CoUninitialize,
    },
};

fn main() {
    unsafe {
        let hresult = CoInitialize(std::ptr::null_mut());
        let result = get_application("Excel.Application", true);
        CoUninitialize();
    }
}

unsafe fn get_application(prog_id: &str, attach_to_running: bool) -> Result<IDispatch, ::windows::HRESULT> {
    let mut clsid = windows::Guid::zeroed();
    CLSIDFromProgID(prog_id, &mut clsid).ok()?;
    let app;
    if attach_to_running {
        let mut unk = None;
        let unk = GetActiveObject(&clsid, std::ptr::null_mut(), &mut unk).and_some(unk)?;
        // let app = unk.cast::<IDispatch>();
        let app = unk.cast::<bindings::Windows::Win32::System::OleAutomation::IDispatch>();
    } else {
        app = CoCreateInstance(&clsid, std::ptr::null(), CLSCTX_LOCAL_SERVER)?;
    }
    Ok(app)
}
```

**Comment by MarijnS95** [comment]
> Since asking I have upgraded to 0.10 from 0.9 and made a little progress

Great news, `0.10` includes lots of nice improvements and some good namespace refactoring :tada: 

> but get an error for the cast:
> 
> ```
> let app = unk.cast::<bindings::Windows::Win32::System::OleAutomation::IDispatch>();
>                  ^^^^ method not found in `windows::IUnknown`
> ```

You managed to omit the acutally relevant bit the compiler spits out for you. Keep in mind that `rustc` is friendly and tries to help you, saying _exactly what you need to do_:

```rust
   |
28 |         let app = unk.cast::<bindings::Windows::Win32::System::OleAutomation::IDispatch>();
   |                       ^^^^ method not found in `IUnknown`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use windows::Interface;
   |
```

You don't need me to repeat that :grin: 
This crate works like a prelude, it's common to just include everything with `use windows;:*`.

> I set clsid to `windows::Guid::zeroed()` to prevent a `use of possibly-uninitialized 'clsid'` error.

Yes, you always have to initialize variables in Rust. There's an unsafe way to get around that if you know the function is going to write the data anyway, using https://doc.rust-lang.org/std/mem/union.MaybeUninit.html.

**Comment by Adarma** [comment]
Can't believe I overlooked that part of the message!

Adding `use windows::*;` really makes things easier.

Thanks, all working now
