### ISSUE TITLE
MemoryBuffer example is potentially unsafe

### ISSUE THREAD

**Issue by Boddlnagg** [microsoft/windows-rs#809]
I see some potential issues in the MemoryBuffer example which was added in https://github.com/microsoft/windows-rs/pull/756:

1) If I get a mutable slice (like it's done in the example) then I must ensure that no one else accesses the memory at the same time. Nobody stops me from calling `as_slice` twice on the same `IMemoryBufferReference` ... so the `as_slice` function should be marked unsafe. Unfortunately even changing the input to `&mut IMemoryBufferReference` doesn't help, because WinRT types themselves are just references and I can easily get another one referencing the same underlying object ...
2) Even if I change the output to an immutable slice (and in my case I only need read access, so I modified the code accordingly), I would need to make sure that no one else writes to the buffer at the same time while my immutable slice exists. Is there a guarantee for `IMemoryBufferReference` that the contents don't change while I hold the reference? Does `IMemoryBufferReference` come with any guarantees by itself, or does that depend on where I got the `IMemoryBufferReference` from? (Note that there is a similar issue with `mmap`-like APIs, so e.g. [this wrapper function](https://docs.rs/memmap/0.7.0/memmap/struct.Mmap.html#method.map) is marked `unsafe`.)
3) Lastly, I'm not sure from the documentation of https://docs.microsoft.com/en-us/windows/win32/winrt/imemorybufferbyteaccess-getbuffer whether the pointer to the data might be `NULL` if the buffer is empty. But I don't see any indication that it cannot, so you need to make sure that `NULL` is not passed to `std::slice::from_raw_parts[_mut]` because [that is not allowed](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html). `NonNull::dangling()` can be used instead (when the length is 0).

**Comment by kennykerr** [comment]
You're right of course. I've updated (#822) the example.
