### ISSUE TITLE
Defining and Implementing Win32/COM/WinRT types in Rust

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#81]
Authoring support is part of the next major milestone - stay tuned!

**Comment by kennykerr** [comment]
Rust presents both unique challenges and unique opportunities when it comes to creating a language projection for the Windows Runtime. Defining and implementing COM and WinRT types in Rust highlights how this language’s rich metaprogramming facilities allow developers rather ingenious flexibility to hook compilation for both importing and exporting type information. 

Today, Rust/WinRT lets you import WinRT types from metadata. The resulting imported types are projected as Rust types that are callable in an idiomatic way. This however only covers consumption of types. Now it's time to explore how Rust/WinRT is being extended to allow COM and WinRT types to be defined in Rust, for local consumption and optionally for export as well, and to allow Rust implementations of both imported or locally defined types. 

The problem can be broken down as follows:

* Declare WinRT and COM types in Rust 
* Implement WinRT and COM classes in Rust 
* Export the metadata representation of those types as a winmd file

Today, a Rust project imports types using either the `winrt::import` or `winrt::build` macros. Either way, a set of winmd files are gathered and the aggregate of all types are available for import into the Rust type system. This acts as a sort of cache of metadata that is at the Rust project’s disposal. This is important because the `import`/`build` macros don’t know ahead of time what types might need to be implemented by the project. Breaking down the problem like this is useful because you can quickly see how the solution comes together. Locally declared WinRT and COM types are immediately exported to a winmd file that is then added to the metadata cache that is then available to any COM and WinRT implementations within the Rust project. The winmd file can then be shared with other projects as needed.

To complement the winrt `import`/`build` macros, Rust/WinRT adds the `winrt::implements` attribute macro to implement any previously declared COM or WinRT classes and interfaces. This macro draws information from the metadata cache to fill in the scaffolding and boilerplate code necessary to implement the desired types in Rust. 

Here is an example of how the build macro might be used (and updated) to both import existing type information and declare new project-specific types.

```rust
winrt::build! {
    [import]
    nuget = Microsoft.Windows.SDK.Contracts
 
    [filter]
    windows::foundation::*
    windows::data::xml::dom::*
 
    [export]
    pub mod microsoft {
        pub mod windows {
            pub struct StructType { x: i32, y: i32 };
 
            pub interface IInterfaceType {
                fn method(&self) -> Result<StructType>;
            }
 
            pub class ClassType : IInterfaceType;
        }
    }
}
```

Then inside the project, any of the classes may be implemented using the `winrt::implements` macro:

```rust
#[winrt::implements(microsoft::windows::ClassType)]
pub struct ClassType {
    fields: u32
}

impl ClassType {
    pub method(&self) -> Result<StructType> {
        Ok(StructType{ x: 1, y: 2 })
    }
}
```

Because the type information is available to the `implements` macro, the developer doesn’t need to tell it which interfaces to implement or which methods to expect from the struct implementation. The `implements` macro also has enough information to build up the necessary vtable pointers and slots to support the COM object at run time. 

The `implements` macro in its simplest form may be used simply to implement an existing WinRT class:

```rust
#[winrt::implements(windows::foundation::Uri)]
pub struct Uri { ... }
```

The implementation will automatically include the `windows::foundation::Uri` class’ required interfaces, including `IUriRuntimeClass`, `IUriRuntimeClassWithAbsoluteCanonicalUri`, and `IStringable` in this case. The `Uri` struct will be expected to provide implementations for the methods of all of these interfaces.

The `implements` macro may also be used to implement a loose set of interfaces:

```rust
#[winrt::implements(IFrameworkViewSource, IFrameworkView)]
pub struct App { ... }
```

In this case, the struct will implement the indicated interfaces and nothing more. This is useful for implementations that don’t necessarily correspond to a WinRT class. Generic and polymorphic implementations of `IVector<T>` and other collection interfaces may be implemented in this manner as well.

Finally, the `implements` macro may be used to implement a combination of classes and interfaces:

```rust
#[winrt::implements(windows::foundation::SomeClass, ISomethingWinRT, ISomethingCom)]
pub struct Uri { ... }
```

In this case, the struct will implement all of the interfaces required by `SomeClass` as well as the loose interfaces indicated by the attribute.

**Comment by robmikh** [comment]
I think this all sounds great! I have some questions, hopefully they aren't too in the weeds:

1. The whole exporting bit is very interesting. And I'm assuming that most people who want to export types/metadata will use that path. Do you see that part also handling exporting `DllGetActivationFactory` and the like? I'm mainly asking because I think versioning might still be easier by authoring an idl, but that's a much narrower scenario (in fact it might only matter to the system). It might be useful to "export" types from existing metadata.

2. In the last example, where you can implement a COM/non-WinRT interface, I'm guessing that includes arbitrary types that implement the `ComInterface` trait?

**Comment by kennykerr** [comment]
Yes, export implies both the production of the winmd file directly from the Rust build as well as the `DllGetActivationFactory` implementation that provides access to all of the public WinRT classes that the Rust project implements, allowing you to create a DLL. You can of course still use IDL and then simply import the resulting winmd file and implement some of the existing WinRT classes. Either way (whether the WinRT class is declared locally or imported) there needs to be a step that gathers up all of the public WinRT classes and exports them via `DllGetActivationFactory`. 

I'd like to support the same kind of versioning support that IDL affords directly from Rust. While I think using IDL is fine, I don't want developers to resort to IDL merely because Rust lacks support for versioned interfaces (or anything else). We should be able to easily use attributes to declare interfaces as being `required`, `static`, and `activatable` interfaces of a given WinRT class just as you can in IDL today with all of the same attributes for versioning, noexcept, overloads, renames, properties, and so on.

The trouble with your second question is that a procedural macro like `implements` doesn't have access to the compilation unit as a whole that may declare other interfaces via something like a `ComInterface` trait. It only works as I've described above because the `implements` macro can look at the metadata that was previously collected and synthesized by the `build` macro. The assumption for COM interfaces is that they too will be imported or declared via the `build` macro.

**Comment by rylev** [comment]
I'm not sure that this can work since it would need to be guaranteed that the `winrt::build!` macro runs before all the `winrt::implements` macros which I don't think we can guarantee. 

Where does the exported metadata end up? If I take a dependency on a project that exports certain types, how do I read the metadata from that dependency? 

Other than that I like idea. Granted I don't think that this type of solution has too much precedent, but I think it largely avoids most of the bad practices you sometimes encounter in proc_macros (e.g., network access).

**Comment by kennykerr** [comment]
@rylev 

The assumption is that the build macro runs in a sub crate, as is the norm anyway. That should ensure that it runs before hand. [Here's an example](https://github.com/kennykerr/samples-rs/tree/master/build).

Exporting metadata (and implementations) produces a WinRT component, not a Rust library crate. The resulting build artifacts would distributed as a nuget package so that any language, not just Rust, can consume that WinRT component.

**Comment by Maan2003** [comment]
This one looks more like Rust.
```rust
#[winrt(class)]
pub struct ClassType {
    fields: i32,
}

#[winrt]
impl ClassType {
    pub fn method() {}
}

#[winrt]
pub trait IInterfaceType {
    fn imethod();
}

#[winrt]
impl IInterfaceType for ClassType {
    fn imethod() {}
}
```
`wasm-bindgen` also export types to javascript(and typescript), maybe their approach could help.

**Comment by rylev** [comment]
@Maan2003 thanks for the feedback. An issue with this is that Interfaces are not traits and so it might be confusing for users to define a trait that ends up becoming a struct. That's why we decided for the custom syntax in `class` and `interface`.

**Comment by Maan2003** [comment]
I don't have understanding of interfaces then 😅. But declaring the public api separate really looks like C header. To be explicit we could have `#[winrt(interface)]`

**Comment by kennykerr** [comment]
@Maan2003 the trouble is that would require us to pre-process the entire Rust crate looking for WinRT types since Rust procedural macros don't have have access to the entire AST for the crate but only the token stream that represents the macro input. At any rate, it's generally preferred to design ABI-stable APIs up front where the API is declared and implemented separately. This is also not something you'd need to think too much about unless you were defining a WinRT component.

**Comment by kennykerr** [comment]
I'm back from vacation and will be focusing on this issue. Thanks for everyone's patience.

**Comment by kylone** [comment]
> I don't have understanding of interfaces then 😅. But declaring the public api separate really looks like C header. To be explicit we could have `#[winrt(interface)]`

I'm doing a bit of research here to understand the vision of what this issue is about. The key insight I had was that Windows has an ABI that's a higher level than the C ABI that's common to so many languages: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/interop-winrt-abi

**Comment by kennykerr** [comment]
@kylone This crate already implements the WinRT ABI to the extent that you can, as a _consumer_ or caller, use WinRT components via this binary interface. This issue is about extending that to also act as the _producer_ or callee of such WinRT components by implementing the other side of this binary interface.

**Comment by kennykerr** [comment]
Just a quick update: I've been working flat-out on this. In the process, I've made many improvements to WinRT support to better handle many aspects of COM and WinRT in Rust. Today I hit a mini-milestone where fully generic authoring support worked for the first time: 

```rust
fn main() -> Result<()> {
    let t = Thing("hello".to_string());

    let s: IStringable = Thing::into_box(t);
    println!("{}", s.to_string()?);

    let c: IClosable = s.cast()?;
    c.close()?;

    Ok(())
}

#[implements(windows::foundation::IStringable, windows::foundation::IClosable)]
struct Thing(String);

impl Thing {
    fn to_string(&self) -> Result<HString> {
        Ok(HString::from(&self.0))
    }

    fn close(&self) -> Result<()> {
        Ok(())
    }
}
```

I hope to have a PR out soon.

**Comment by kennykerr** [comment]
#354 doesn't yet implement everything described in this issue but does allow the example above to work. 😉

**Comment by lukechu10** [comment]
Since #[implement] is implemented now (😄), should this issue be resolved?

**Comment by kennykerr** [comment]
It isn't quite done. It does support basic scenarios involving WinRT interfaces, but lacks support for COM interfaces, and lacks some of the other capabilities necessary for feature complete.

**Comment by nbdd0121** [comment]
Is it possible to place `#[implement]` on `impl` block rather than on struct definition, so it will be more similar to trait implementation?
```rust
#[implement]
struct Thing(String);

#[implement(windows::foundation::IStringable)]
impl Thing {
    fn to_string(&self) -> Result<HString> {
        Ok(HString::from(&self.0))
    }
}

#[implement(windows::foundation::IClosable)]
impl Thing {
    fn close(&self) -> Result<()> {
        println!("world");
        Ok(())
    }
}
```
or maybe even
```rust
#[implement]
struct Thing(String);

#[implement]
impl windows::foundation::IStringable for Thing {
    fn to_string(&self) -> Result<HString> {
        Ok(HString::from(&self.0))
    }
}

#[implement]
impl windows::foundation::IClosable for Thing {
    fn close(&self) -> Result<()> {
        println!("world");
        Ok(())
    }
}
```

I peeked into the implementation and I think the only issue that prevents doing so is the QueryInterface function, but I suppose there could be a way around that using something like https://docs.rs/inventory?

**Comment by fghzxm** [comment]
I'm concerned about the implicitly-boxing conversion from impl types to runtime types:
```
::windows::build!(
    [export]
    pub interface I1 {}
    pub interface I2 {}
    pub class C : I1, I2;
);

#[implement(C)]
struct C(i32);

let c = C(0); // 1) creates a C on the stack
let i1 = I1::from(c); // 2) copies and boxes
let i2 = I2::from(c); // 3) copies and boxes again
```
This can be confusing to a user familiar with C++/WinRT, who might interpret 1) as creating a heap-allocated `C` and returning a class-type smart pointer, and 2) 3) as doing nothing more than QI.  The user would incorrectly think that `c`, `i1` and `i2` all point to the same implementation object.

In actuality, 1) creates a naked `C` object on the stack, which is an operation that rarely makes sense.

**Comment by fghzxm** [comment]
My incomplete personal wishlist of features that might be of your interest:
1. Support for using `self: Pin<&mut Self>` and `self: Pin<&Self>` in impl methods;
2. Support for using smart pointer types other than `Box<_, Global>` for allocating COM objects;
3. Equivalent of C++/WinRT's `final_release`;
4. Support for DSTs as impl types (may depend on rust-lang/rust#81513).

**Comment by nbdd0121** [comment]
I looked into the implementation of the `implement!` macro again and believed that a wrapper shouldn't be instantiated for each struct, but rather one for all Rust types. This could be achieved by:
* Define a trait, e.g. `RustInspectable` which contains the implementation of QueryInterfaces, GetIids and GetRuntimeClassName, as well as a associate type for VTABLE.
* Have a wrapper, e.g. `ComBox` with generic `<T: RustInspectable>`.
* Redirect all methods calls to the trait.

**Comment by kennykerr** [comment]
Thanks for the feedback! I'm just in the middle of overhauling the code gen. Once that's wrapped up I plan to return my focus to this issue.

**Comment by fghzxm** [comment]
@nbdd0121 Looks like this idea can be extended to other COM and WinRT interfaces and classes as well: give every interface and exported class a trait (class traits are empty), so that every type implementing those traits can be used to instantiate a COM or WinRT object with the corresponding interfaces.

**Comment by kennykerr** [comment]
With weak references now supported (#745 and #718) I'm now working on supporting overridable interfaces for Xaml. I'll probably add generalized support for implementing partial interfaces so that you can, for example, implement Xaml's `IApplicationOverride` but only provide an implementation of the `OnLaunched` method. This is going to require a lot better parsing within the `implement` macro to detect this and stub out the remaining methods to return `E_NOTIMPL` but I think it will be worth it.

**Comment by kennykerr** [comment]
```rust
#[extends(Windows::UI::Xaml::Application)]
struct App {
}

#[overrides(Windows::UI::Xaml::Application)]
impl App {
    fn OnLaunched(&self, _: &LaunchActivatedEventArgs) -> Result<()> {
        let window = Window::Current()?;
        window.SetContent(TextBox::new()?)?;
        window.Activate()
    }
}
```

**Comment by kennykerr** [comment]
Continuing to make good progress here. I can now derive from Xaml's `Application` class (or any other open composable type). Keep in mind that Rust lacks inheritance. 😉 

```rust
#[implement(extend Windows::UI::Xaml::Application)]
struct MyApp();

fn main() -> Result<()> {
   let app: Application = MyApp().new()?;

    Ok(())
}
```

This takes `MyApp` and wraps it inside a COM/WinRT object that logically extends `Application`, internally involving COM aggregation, by calling `Application`'s composable constructor to stitch the two objects together.

**Comment by kennykerr** [comment]
And this just started working:

```rust
#[implement(
    extend Windows::UI::Xaml::Application,
    override OnLaunched
)]
struct MyApp();

#[allow(non_snake_case)]
impl MyApp {
    fn OnLaunched(&self, _: &Option<LaunchActivatedEventArgs>) -> Result<()> {
        let window = Window::Current()?;
        window.SetContent(TextBox::new()?)?;
        window.Activate()
    }
}

fn main() -> Result<()> {
    initialize_mta()?;
    Application::Start(ApplicationInitializationCallback::new(|_| {
        MyApp().new()?;
        Ok(())
    }))
}
```

![image](https://user-images.githubusercontent.com/9845234/119549430-0f7dd100-bd4c-11eb-9d0f-ace2b9514d74.png)

A few loose ends to clean up but a basic Xaml app now works! 😊

**Comment by simonbuchan** [comment]
It's slightly beside the point, but `Application` / `Window` still requires a UWP context, right?

**Comment by kennykerr** [comment]
Yes, this particular example requires an appx. Xaml also works in a standard executable process, it just requires more code to bootstrap, and that should also work just fine.

**Comment by MRahilly** [comment]
Would it make any sense to wrap Xaml markup in an implementation .winmd?

**Comment by MRahilly** [comment]
Is the appx needed for deployment and not needed to build the project?

**Comment by kennykerr** [comment]
Yes, the appx is only needed for deployment and the appx is only needed if you want to publish a packaged/store app rather than a regular executable that you can xcopy. All of the appx tech is beyond the scope of the `Windows` crate, which is focused on building the project.

**Comment by mwcampbell** [comment]
Looking forward to stable support for implementing COM interfaces. I'd especially like to be able to implement the UI Automation provider interfaces in Rust.

**Comment by kennykerr** [comment]
With the dependency tracking and usability work done (#896), I'm back working on implementations! Starting with generic interfaces.

**Comment by mwcampbell** [comment]
@kennykerr How far off do you think you are from supporting non-WinRT COM interfaces in the implement macro? I'm planning to start implementing the UI Automation provider interfaces in a Rust crate soon (within the next few weeks), and I'll write the glue code myself if needed, but it would be great if I didn't have to. In any case, thanks for the update.

**Comment by kennykerr** [comment]
Much of #896 was to deal with blocking issues for implementations in general. I hope to get both remaining interface types working soon.

**Comment by FreddyD-GH** [comment]
@kennykerr Am I correct that the work so far only allows for implementing WinRT types in Rust, and does not yet have any support for authoring WinRT types for consumption from other languages?

**Comment by kennykerr** [comment]
You can technically export types but you will have to write the export functions (and metadata) yourself. Complete component authoring is still to come.

**Comment by drewcrawford** [comment]
In [this example](https://github.com/microsoft/windows-rs/issues/81#issuecomment-848110943) the expression

```rust
MyApp().new()? 
```

is of type `Windows::UI::Xaml::Application`.  Is there a cast/lens to to get the (inner?) `MyApp`, `&MyApp` or similar Rust type so as to call the non-COM methods?

**Comment by kennykerr** [comment]
Generic interface implementations are finally starting to work! That means I'll soon be able to close #91. Here's a peek at what this looks like. Notice both `IVectorView` and `IIterable` are generic, or parameterized, interfaces whose projected and ABI signatures change depending on the provided generic parameters. This is critical in implementing and even calling many WinRT APIs. 

```rust
use bindings::*;
use windows::*;
use Windows::Foundation::Collections::*;

#[implement(
    Windows::Foundation::Collections::IVectorView<i32>,
    Windows::Foundation::Collections::IIterable<i32>,
)]
struct Thing();

#[allow(non_snake_case)]
impl Thing {
    pub fn GetAt(&self, index: u32) -> Result<i32> {
        Ok(index as _)
    }

    pub fn Size(&self) -> Result<u32> {
        Ok(123)
    }

    pub fn IndexOf(&self, value: i32, index: &mut u32) -> Result<bool> {
        *index = 456;
        Ok(true)
    }

    pub fn GetMany(&self, startindex: u32, items: &mut [i32]) -> Result<u32> {
        Ok(789)
    }

    fn First(&self) -> Result<IIterator<i32>> {
        panic!();
    }
}

fn main() -> Result<()> {
    let v: IVectorView<i32> = Thing().into();
    println!("GetAt {}", v.GetAt(123)?);

    Ok(())
}
```

**Comment by kennykerr** [comment]
Just a quick update. I've done a bunch refactoring and I'm now close to getting support for implementing COM interfaces up and running. Stay tuned, I know this is something that a lot of folks are waiting for. Thanks for your patience.

**Comment by MRahilly** [comment]
IDispatch Excel automation from Rust should be possible.

**Comment by kennykerr** [comment]
A contrived but fun example illustrating both COM and WinRT interfaces working side-by-side:

```rust
#[implement(
    Windows::Foundation::IStringable,
    Windows::Win32::System::WinRT::ISwapChainInterop
)]
struct Thing();

#[allow(non_snake_case)]
impl Thing {
    fn ToString(&self) -> Result<HSTRING> {
        Ok("hello world!".into())
    }

    fn SetSwapChain(&self, unknown: &Option<IUnknown>) -> Result<()> {
        if let Some(unknown) = unknown {
            let s: IStringable = unknown.cast()?;
            println!("{}", s.ToString()?);
        }

        Ok(())
    }
}

fn main() -> Result<()> {
    let stringable: IStringable = Thing().into();

    let interop: ISwapChainInterop = stringable.cast()?;

    unsafe { interop.SetSwapChain(&stringable)? };

    Ok(())
}
```

```
C:\git\scratch>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target\debug\scratch.exe`
hello world!
```

**Comment by bdbai** [comment]
Hi @kennykerr, is it possible to derive a WinRT type from other custom types for now? The use case is that our `Application` subclass should derive from `XamlMetaDataProvider` so that `Frame.Navigate(typeof(MainPage))` will know how to instantiate a `MainPage` object. Thanks!

**Comment by wravery** [comment]
Little bit of encouragement, I pulled from master and tried `#[implement]` as a replacement for the COM interfaces in `windows-samples-rs/webview2_win32`: https://github.com/wravery/windows-samples-rs/commit/3eb3994043ac8d067ec1d2bc6780414cc2105a92. Looks a lot better already, IMO. 😃 

Bit of feedback, I had to include `use bindings::Windows::{self, ...};` (and the same for `bindings::Microsoft` in this specific case) to get the type name resolution in `#[implement]` to work with a separate bindings crate. It would be nice if there were a way to avoid that, or to add a module path prefix somewhere in the macro arguments.

**Comment by knopp** [comment]
OMG, [this actually works now](https://github.com/nativeshell/nativeshell/commit/7bf6ca258e8e28a1d0a49294d9b68b13c21361c6#diff-08619efc94a05e7f7b1c72991b1afc2c269517396b215986e6160e53faba0c62R273) :) @kennykerr, thank you so much!

**Comment by kennykerr** [comment]
@wravery generally the `implement` macro expects that you include `use bindings::*` and then everything should work as expected. I'd like to not require this specific `use` path but that's beyond what Rust can manage at the moment.

**Comment by saschanaz** [comment]
> I'd like to not require this specific `use` path but that's beyond what Rust can manage at the moment.

Is there a related Rust tracking issue for that? 👀

**Comment by knopp** [comment]
@kennykerr, I managed to implement all interfaces that I needed except for `Windows::Win32::System::Com::IDataObject`. It's possible that I'm doing something wrong, but tried it with same method signatures as generated `IDataObject` but it didn't compile. Some of the errors, i.e.
```
casting `&*mut STGMEDIUM_abi` as `*const STGMEDIUM_abi` is invalid
```
would suggest that maybe there is a problem with code generation?

**Comment by knopp** [comment]
In case it helps, here's the code:
```rust
#[implement(Windows::Win32::System::Com::IDataObject)]
pub struct DataObject {}

#[allow(non_snake_case)]
impl DataObject {
    pub fn new() -> Self {
        Self {}
    }

    fn GetData(&self, pformatetc_in: *mut FORMATETC) -> ::windows::Result<STGMEDIUM> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn GetDataHere(
        &self,
        pformatetc: *mut FORMATETC,
        pmedium: *mut STGMEDIUM,
    ) -> ::windows::Result<()> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn QueryGetData(&self, pformatetc: *mut FORMATETC) -> ::windows::Result<()> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn GetCanonicalFormatEtc(&self, pformatectin: *mut FORMATETC) -> ::windows::Result<FORMATETC> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn SetData<'a>(
        &self,
        pformatetc: *mut FORMATETC,
        pmedium: *mut STGMEDIUM,
        frelease: impl ::windows::IntoParam<'a, BOOL>,
    ) -> ::windows::Result<()> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn EnumFormatEtc(&self, dwdirection: u32) -> ::windows::Result<IEnumFORMATETC> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn DAdvise<'a>(
        &self,
        pformatetc: *mut FORMATETC,
        advf: u32,
        padvsink: impl ::windows::IntoParam<'a, IAdviseSink>,
    ) -> ::windows::Result<u32> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn DUnadvise(&self, dwconnection: u32) -> ::windows::Result<()> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }

    fn EnumDAdvise(&self) -> ::windows::Result<IEnumSTATDATA> {
        Err(Error::fast_error(DATA_E_FORMATETC))
    }
}
```

And the error message:
```
error[E0308]: mismatched types
   --> nativeshell\src\shell\platform\win32\drag_com.rs:198:1
    |
198 | #[implement(Windows::Win32::System::Com::IDataObject)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
    |
    = note: expected raw pointer `*mut Com::STGMEDIUM`
                 found reference `&Com::STGMEDIUM`
    = note: this error originates in the attribute macro `implement` (in Nightly builds, run with -Z macro-backtrace for more info)
help: parentheses are required to parse this as an expression
    |
198 | (#[implement(Windows::Win32::System::Com::IDataObject)])
    | +                                                      +

error[E0606]: casting `&*mut STGMEDIUM_abi` as `*const STGMEDIUM_abi` is invalid
   --> nativeshell\src\shell\platform\win32\drag_com.rs:198:1
    |
198 | #[implement(Windows::Win32::System::Com::IDataObject)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `implement` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by wravery** [comment]
@knopp I think the issue is the signature for `SetData`. If the parameter is an in/const type, it will generate a binding that passes it as a reference. The first note is telling you that it can't convert that to a `*mut` pointer. The second error mentioning the `_abi` is more of the same.

**Comment by kennykerr** [comment]
Yeah... please don't use `IntoParam`.  Ever. 😉 

That's only for the generated bindings to make it easier to call Windows APIs from Rust. When you are implementing an interface/function in Rust you need to simply use the parameter types directly.

**Comment by knopp** [comment]
@kennykerr, @wravery, I removed the IntoParam (I just had it there because I copied the signature from generated window.rs, I wasn't planning on leaving it there :). I did try changing the `SetData` signature to pass `STGMEDIUM` by const reference but it didn't make any difference. The `STGMEDIUM` error is still there.  The other method that takes `STGMEDIUM` (`STGMEDIUM`) is out so I assume `*mut` should be correct, right?

**Comment by kennykerr** [comment]
Note that there are a few (known) scenarios for COM implementations that are not yet covered. I am working through those now. I'll test IDataObject next.

Unlike WinRT where there is a pretty limited and well-known type system that is easily tested, COM is the wild west of method signatures and providing a high percentage of test coverage is challenging.

**Comment by mwcampbell** [comment]
@kennykerr While you're at it, can you please make sure `VARIANT`s are covered, ideally with a wrapper like the one we already have for `BSTR`? That will be important for implementing the UI Automation provider interfaces.

**Comment by aWeinzierl** [comment]
How are you supposed to deal with generic structs (not interfaces), like the following one?

```Rust
use bindings::*;
use windows::*;

#[implement(
    Windows::Foundation::IStringable,
)]
pub struct Test<Gen>{
    _item: Gen,
}
```

```
error[E0107]: this struct takes 1 generic argument but 0 generic arguments were supplied
  --> src\view_models\router_view_model.rs:9:1
   |
9  | / #[implement(
10 | |     Windows::Foundation::IStringable,
11 | | )]
   | |__^ expected 1 generic argument
   |
note: struct defined here, with 1 generic parameter: `Gen`
  --> src\view_models\router_view_model.rs:12:12
   |
12 | pub struct Test<Gen>{
   |            ^^^^ ---
   = note: this error originates in the attribute macro `implement` (in Nightly builds, run with -Z macro-backtrace for more info)
help: add missing generic argument
   |
9  | #Gen[implement(
   |  ^^^
```

**Comment by agausmann** [comment]
Seems that generics aren't supported in the current implementation. And recovering the concrete type of the generic parameter would definitely be non-trivial, if it's even possible. According to `cargo expand`, the Rust value is stored and accessed as a type-erased raw pointer.

(Aside: It might be possible if the generic parameter is required to implement `Any`, then a `TypeId` could be stored and checked before casting.)

**Comment by kennykerr** [comment]
Yes, the `implement` macro doesn't attempt to figure out whether the implementation struct is generic. It does assume it is generic when you [implement a generic interface](https://github.com/microsoft/windows-rs/blob/master/tests/implement/tests/generic_generic.rs), like `IVector<T>`, but that's about it. 

I do plan to support this eventually.

**Comment by 1Dragoon** [comment]
If it weren't for this, I probably never would have used the win32 api
