### ISSUE TITLE
How to publish a crate using windows-rs bindings?

### ISSUE THREAD

**Issue by zaddach** [microsoft/windows-rs#819]
Hi,

I've tried to publish a crate that is using a local "bindings" sub-crate to crates.io (see here: https://github.com/zaddach/clamav-rs/blob/master/Cargo.toml#L21). `cargo publish --dry-run` isn't happy with the crate, because the bindings crate obviously doesn't exist on crates.io. 

Is there a way to handle this elegantly (e.g., tell cargo to package the nested crate into the parent)? Or do I have to create a new package for my bindings, .e.g. `clamav-rs-bindings`, and publish it to crates.io? Or should I go and inline the dependency crate into my parent crate?

**Comment by kennykerr** [comment]
The usual way to deal with this is to publish the bindings crate as a dependency. So, first publish `clamav-rs-bindings` and then publish `clamav-rs`.

**Comment by zaddach** [comment]
okay, I'll follow that pattern. Thanks!
