### ISSUE TITLE
Consider using curly braces in `windows::build!` macro calls for easy autoformatting

### ISSUE THREAD

**Issue by MarijnS95** [microsoft/windows-rs#827]
Hi! There's a little trick we might want to do to make it much easier to automate formatting and format-checking of the `windows::build!` macro calls for consistency and to make them look more like the `use bindings::...` import blocks at the top of files. Wrapping paths inside curly braces (with trailing semicolon!) instead of parentheses looks like this: `windows::build! { ... some paths ... };`, and allows us to perform the following substitution:

```sh
sed -i 's/windows::build! {/use Foo::{/' **/build.rs
```

`Foo::` here is necessary so that `rustfmt` doesn't collapse the block (EDIT: `Foo::` can be any word, perhaps `bindings::` is more in place even though it has no meaning). Now if `rustfmt` is ran all the blocks are reformatted, sorted, trailing commas are added etc. Then, we can simply convert back to the original:

```sh
sed -i 's/use Foo::{/windows::build! {/' **/build.rs
```

Is this something you'd like, and something you'd want on the CI? It's common to print `git diff --exit-code` here, failing the CI but giving contributors a helpful diff showing what changes need to be made to appease the job (can be copy-pasted and applied locally through `patch -p1` or similar tools).

Note that we should probably add a similar case specifically for `let tokens = windows_macros::generate!` in `crates/bindings/src/main.rs`.

**Comment by kennykerr** [comment]
Neat, so is this something that we'd simply add to the existing build.yml? I think that provided the error diff is really easy to apply it could be really beneficial.

**Comment by MarijnS95** [comment]
@kennykerr yes it can fit right in there. Alternatively a separate script could be added that's easy to invoke locally.

`patch -p1` isn't the easiest to work with given that you need to paste the diff or pipe it from a file. And it's a Unix tool, don't know if git-for-Windows makes it available by default. We could also provide the diff as artifact or apply-able patch through `git am` instead.

On the other hand this is only going to matter for an initial format pass, and new examples (or minor changes to existing examples) over time. The changes are small and trivial for the most part to copy-paste or apply by hand.

Nevertheless I'll get an initial PR set up to show how this works. It can always be rejected or reverted over time if it turns out to be more of a barrier than an improvement.

**Comment by kennykerr** [comment]
Ideally it wouldn't require additional dependencies and would "just work" on Windows. It would have to work as part of the Windows CI build.

**Comment by MarijnS95** [comment]
@kennykerr The idea was to throw the two Unix commands listed above in the CI, but understandably you want this to run on Windows - I'll gladly take on the challenge to write this in PowerShell! That immediately solves the problem of applying the diff one way or another, or figure out how to run the commands locally: we check in a script that performs the operation, and simply ask the contributor to run that locally. The CI still displays the diff too, for convenience.

No problem for Linux either, since PowerShell Core runs like a dream here :ok_hand:
