### ISSUE TITLE
How to `MAKELANGID` ?

### ISSUE THREAD

**Issue by ibigbug** [microsoft/windows-rs#829]
[`FormatMessageW`](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Diagnostics/Debug/fn.FormatMessageW.html) needs an `dwlanguageid`

It seems [someone ](https://github.com/zenria/serialport-rs/blob/7204d064381177ec878c0c7c2959108ac56643ab/src/windows/error.rs#L34)uses this https://docs.rs/winapi/0.2.6/x86_64-pc-windows-msvc/winapi/winnt/fn.MAKELANGID.html to build the langid

What's the recommended way to use `FormatMessageW` with `windows-rs`?

thank you

**Comment by kennykerr** [comment]
As `MAKELANGID` is a macro in the original source, it is not included by the metadata producing the APIs in Rust. 

```C++
#define MAKELANGID(p, s)       ((((USHORT)(s)) << 10) | (USHORT)(p))
```

You could just write a helper function to calculate the value for you based on the original macro. Here's what `windows::HRESULT` does:

https://github.com/microsoft/windows-rs/blob/510aab24fe511bfd8b5a26868a5ca99691cf03de/src/result/error_code.rs#L104-L114

**Comment by ibigbug** [comment]
very helpful, thanks!

(feel free to close the issue)
