### ISSUE TITLE
SYSTEM_INFO does not implement Default

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/windows-rs#839]
implementing Default would be useful since GetSystemInfo requires a SYSTEM_INFO out pointer. Without Default this is more difficult to produce.

**Comment by kennykerr** [comment]
This is a known limitation for some of the more interesting structs (mostly unions and structs containing unions). I plan to fix this. #656

**Comment by Ben-Lichtman** [comment]
Ah I didn't think of that, in retrospect that makes a lot of sense... I'll close this issue and just use MaybeUninit::zeroed().assume_init() as as stopgap for now.
