### ISSUE TITLE
Automate docs publishing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#851]
Every time I publish a new release of the Windows crate, I need to manually republish the [docs](https://github.com/microsoft/windows-docs-rs). This is a tedious and error-prone process that should be automated. The docs publishing also weeds out issues in the Windows crate as it builds all of the APIs. This should ideally be used to validate CI builds (with `cargo check`) to avoid surprises after release. 

This was unavoidable before as the Rust compiler was way too slow and used too much memory to build the docs in a VM. But a lot has improved since then and hopefully it can now be done.

**Comment by knopp** [comment]
Has the documentation been updated for 0.11? I'm getting errors for [STREEM_SEEK_END](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Com/constant.TYMED_HGLOBAL.html?search=STREAM_SEEK_END), [TYMED_HGLOBAL](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/Com/constant.TYMED_HGLOBAL.html?search=TYMED_HGLOBAL) and possibly others.

**Comment by knopp** [comment]
I guess there are bunch of enum values that were made top level in 0.10 by https://github.com/microsoft/windows-rs/pull/787 (i.e. STREAM_SEEK_END| and now in 0.11 are back to being scoped?

**Comment by kennykerr** [comment]
I don't think I'm going to get to this any time soon. The build is also still pretty slow so I doubt the CI build VMs will support it either.

**Comment by tim-weis** [comment]
Is this something I could working on? If only to identify current issues that would need to be resolved, and collecting prerequisites for fully automating this task, to determine when it's time to do so.

Could you quickly summarize what's required for this, and comment on whether this can be done outside of Microsoft/in a forked repository? I mean, I'd *love* to free you up some time to invest into [more relevant areas](https://github.com/microsoft/windows-rs/issues/81), establishing quality gates along the way as a bonus.

**Comment by kennykerr** [comment]
Sure I'd love the help. The challenge is just to come up with a more sustainable story for API docs. I set up this repo:

https://github.com/microsoft/windows-docs-rs

Out of which I publish documentation here:

https://microsoft.github.io/windows-docs-rs/

This uses GitHub Pages for hosting. 

This is just an experiment but some developers have expressed that this is a very valuable tool. So part of the challenge is to figure out whether this is the right approach for Windows API documentation in Rust and if so improving the quality of the experience, from automating the publishing/validation all the way to profiling end to end to figure out how we can make it work more efficiently/reliably. There are performance bottlenecks in rustc, cargo-doc, and in the Windows crate itself. Then there's #931 and whether we can find a way to weave in actual documentation, not just API signatures.

**Comment by kennykerr** [comment]
Oh, and there's #432 that may impact this as well.

**Comment by tim-weis** [comment]
I hadn't realized how complex this process was. Thanks for having gone through this for every release in the past.

Now personally, I find the generated documentation to be extremely helpful. It makes it easy to discover which module any given API or type gets generated into. The information is presented using a familiar color theme and layout, and allows for quick navigation. ILSpy solves the discoverability aspect, though it is very CLR-centric and fails on all the other points. Plus, it necessarily cannot know the final signature of the Rust projection.

With all that, I don't see the need for this type of documentation going away anytime soon. I will invest time into finding ways to automate the process as much as possible, even if it cannot be run as part of a CI workflow for the foreseeable future. Profiling is another area that would certainly benefit from being easy to do. I'm not sure how to go about that yet, without getting the respective Rust teams involved (e.g. in providing public symbol information for their Windows binaries).

#931 is likely to open up much more impactful ways to streamline everyday development tasks. Having access to API documentation right from within any given IDE would be a massive quality-of-life improvement. Though, as I understand, this would require code generator involvement, adding rust-doc comments as needed (correct me if I'm wrong, or overlooking alternatives). If I can I will try to see if that can be made to work, and gather estimates on the impact this might have on code generation. Maybe this will have to wait until there is some more progress on #432.

I will leave comments here whenever I make progress, and ask questions in the meantime, if you don't mind.

**Comment by jyn514** [comment]
> There are performance bottlenecks in rustc, cargo-doc, and in the Windows crate itself.

@kennykerr do you happen to have on hand exactly what's slow? I'm still interested in improving rustdoc's performance :)

**Comment by kennykerr** [comment]
Were you able to build the bindings crate on windows-docs-rs? That does a great job demonstrating the performance woes. 😉

**Comment by jyn514** [comment]
@kennykerr no, I responded on https://github.com/microsoft/windows-docs-rs/pull/6

**Comment by kennykerr** [comment]
Now that the pre-packaged APIs are available I really need to find a way to document which features to enable for each API.

**Comment by jyn514** [comment]
@kennykerr you can replicate that "requires the following crate features to be activated" text with `doc(cfg(feature = "AbortSignal"))`. If you have `cfg(...)` already, rustdoc will autogenerate the doc(cfg(...))) automatically as long as you have `feature(doc_cfg)` in the crate root.

**Comment by kennykerr** [comment]
Thanks!

**Comment by kennykerr** [comment]
The docs have now been updated to indicate which features a particular API requires:

https://microsoft.github.io/windows-docs-rs/doc/windows/
