### ISSUE TITLE
Find and validate profile timing

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#852]
I haven't found a way to profile Rust code on Windows. Specifically, the `TypeReader` takes almost a second to construct due to the sheer size of the default (mostly Win32) metadata. I already spotted some obvious bottlenecks ([here](https://github.com/microsoft/windows-rs/blob/master/crates/gen/src/workspace.rs#L29), [here](https://github.com/microsoft/windows-rs/blob/master/crates/gen/src/workspace.rs#L83-L84), and switching to HashMap [here](https://github.com/microsoft/windows-rs/pull/841)), but proper profiling is needed to dig deeper. 

As a bonus, having some profile timing that the CI build can measure and guard against regressions would be nice.

**Comment by tim-weis** [comment]
Visual Studio comes with a Profiler, that doesn't need anything more than a binary and debug symbols (Debug -> Performance Profiler...). Have you tried using that already?

You will need to instruct the compiler to generate debug symbols. This can be done by adding the following to your Cargo.toml file:

```toml
[profile.release]
debug = true
```

The profiler can be [run from the command line](https://docs.microsoft.com/en-us/visualstudio/profiling/profile-apps-from-command-line) as well, which might be useful for the CI task, though I don't have any experience with that.

**Comment by kennykerr** [comment]
Have you got that to work? I tried it yesterday and it complained that the executable produced by the Rust compiler was not supported.

**Comment by kennykerr** [comment]
Never mind, I only tried the command line tools. The Visual Studio IDE via Debug -> Performance Profiler seems to work. Thanks for the tip!

**Comment by tim-weis** [comment]
Do you happen to recall the exact error message you were getting, Kenny?

While trying to move #851 forward, I, too, ran into issues with the profiler. At this time it looks as though rustc produces (partially) incorrect PDBs. I've filed a [bug report](https://github.com/rust-lang/rust/issues/88721) with the compiler team. Do the quoted error diagnostics read familiar?

**Comment by kennykerr** [comment]
Yes, that's the same error. I'll mention your bug report to some internal tooling folks. Perhaps they can shed some light.

**Comment by kennykerr** [comment]
Tim, does this still work for you? I just tried using the IDE and I get this errror:

```
Exception of type 'Microsoft.DiagnosticsHub.Diagnostics.CollectionStartFailedHubException' was thrown.
```

**Comment by tim-weis** [comment]
Profiling from the IDE in CPU sampling mode still works for me. I've verified this for:

* Visual Studio 2017 15.9.44
* Visual Studio 2019 16.11.10
* Visual Studio 2022 17.1.0 Preview 5.0

The target was compiled (release configuration with debug symbols) using Rust 1.58.1.

I wonder if a [recent fix](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#new-release-icon-15944-visual-studio-2017-version-15944) for Visual Studio 2017 is in any way related to the failure.
