### ISSUE TITLE
error: `Windows.Win32.System.Memory.MEM_RELEASE` not found in metadata

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/windows-rs#857]
I am trying to add MEM_RELEASE into the build script, however when I try to do it I get the error:

```
error: `Windows.Win32.System.Memory.MEM_RELEASE` not found in metadata
  --> build.rs:51:13
   |
51 |             MEM_RELEASE,
   |             ^^^^^^^^^^^
```

**Comment by tim-weis** [comment]
You will want to use `Windows.Win32.System.Memory.VIRTUAL_FREE_TYPE` in your build script, which then provides the symbol `bindings::Windows::Win32::System::Memory::MEM_RELEASE` (assuming your bindings are generated into a module or crate called `bindings`).
