### ISSUE TITLE
D3D12 descriptor creation functions (eg CreateRenderTargetView) should have optional first parameters

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#863]
Functions such as ID3D12Device::CreateRenderTargetView can accept null as the first parameter.  The current signature is `presource: impl ::windows::IntoParam<'a, ID3D12Resource>,` .

**Comment by kennykerr** [comment]
You should be able to use `None` - does that work?

**Comment by damyanp** [comment]
Ah! So it does.  Thanks!
