### ISSUE TITLE
Build issue for windows crate bindings

### ISSUE THREAD

**Issue by galenb-msft** [microsoft/windows-rs#864]
I am not able to build the bindings needed for my app using the 0.11 version of the windows crate.  I have built a minimal repro at: https://github.com/galenb-msft/minimal_repro.git

Doing a cargo build in this repo should reproduce the error.

**Comment by kennykerr** [comment]
@galenb-msft I have transferred the issue. 

In future, please use https://github.com/microsoft/windows-rs for issues specific to the Windows crate and https://github.com/microsoft/win32metadata/ for issues specific to Win32 metadata.

**Comment by kennykerr** [comment]
When I build this repro I get the following error:

```
C:\git\minimal_repro>cargo build
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.73
   Compiling windows_gen v0.11.0
   Compiling const-sha1 v0.2.0
   Compiling quote v1.0.9
   Compiling windows_macros v0.11.0
   Compiling windows v0.11.0
   Compiling windows_bindings v0.1.0 (C:\git\minimal_repro\lib\deployment\bindings)
   Compiling minimal_repro v1.0.0 (C:\git\minimal_repro\lib\deployment)
error: couldn't read lib\deployment\minimal_repro.rs: The system cannot find the file specified. (os error 2)

error: aborting due to previous error

error: could not compile `minimal_repro`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

This is unrelated to the Windows crate. It appears you have a configuration issue. Check your toml files. For more general Rust help, you may want to try https://stackoverflow.com/

**Comment by galenb-msft** [comment]
After seeing that you could not repro what always repro'd for me to the only possibility of which I could think -- my compiler is out-of-date.  I updated my compiler and the issue went away.  Thanks for your help!
