### ISSUE TITLE
The SpellChecker sample appears to be leaking memory

### ISSUE THREAD

**Issue by tim-weis** [microsoft/windows-rs#865]
It is my understanding that [`ISpellChecker::Suggest`](https://docs.microsoft.com/en-us/windows/win32/api/spellcheck/nf-spellcheck-ispellchecker-suggest) returns an [`IEnumString`](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nn-objidl-ienumstring) interface. The official documentation for the interface's [`IEnumString::Next`](https://docs.microsoft.com/en-us/windows/win32/api/objidl/nf-objidl-ienumstring-next) method is a [fair bit cryptic](https://stackoverflow.com/q/67999012/1889329).

Under the premise that callers of `IEnumString::Next` do acquire ownership of the pointed-to memory, this [section of code](https://github.com/microsoft/windows-rs/blob/fdf168ddd6f4e22b21f3940228e6b2ac800be22e/examples/spellchecker/src/main.rs#L83-L97) would need to be updated with a call to [`CoTaskMemFree`](https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-cotaskmemfree) (I guess) to free resources.

**Comment by kennykerr** [comment]
Yes, that's right - I wrote about that here: https://visualstudiomagazine.com/articles/2013/08/01/using-the-c-spell-checking-api.aspx

**Comment by tim-weis** [comment]
Should I prepare a pull request fixing those issues (both from the `IEnumString` iterator as well as the `get_Replacement` call)?

**Comment by kennykerr** [comment]
Thanks, that would be great!
