### ISSUE TITLE
Remove need for cloning collection interfaces when creating iterators 

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#87]
Currently, all iterators over collection interfaces take ownership of those collections. This is not strictly necessary and causes us to have to perform a clone (ref count) on the collections when we only have access to references to the collections.

We need to create iterators that only have references to the collections being iterated.

**Comment by kennykerr** [comment]
I don't see a way to do this without making `VectorViewIterator` and friends a whole lot more complicated, perhaps storing an `enum` that's either a reference or a value depending on what the iterator is created from. But this doesn't seem like a high priority issue at the moment so I'll just close and we can revisit if this becomes a performance concern.
