### ISSUE TITLE
HINSTANCE is apparently not in metadata.

### ISSUE THREAD

**Issue by LollipopFt** [microsoft/windows-rs#871]
```rust
   Compiling bindings v0.1.0 (C:\Users\lollipopft\rust\projects\winapi\window\bindings)                         
error: `Windows.Win32.Foundation.HINSTANCE` not found in metadata
 --> bindings\build.rs:4:25
  |
4 |             Foundation::HINSTANCE,
  |                         ^^^^^^^^^

error: aborting due to previous error

error: could not compile `bindings`
```

it gives me this error when my build.rs is
```rust
fn main() {
    windows::build!(
        Windows::Win32::{
            Foundation::HINSTANCE,
            UI::WindowsAndMessaging::{WNDCLASSW, WNDCLASS_STYLES, CS_OWNDC, CS_HREDRAW, CS_VREDRAW, DefWindowProcW}
        }
    );
}
```

am i doing anything wrong?

**Comment by kennykerr** [comment]
These types having recently moved around due to changes in the [Win32 metadata](https://github.com/microsoft/win32metadata). As of `0.11.0`, it can be found here: 

`Windows::Win32::Foundation::HINSTANCE`

https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/Foundation/struct.HINSTANCE.html

Perhaps double check which version of the Windows crate you're using.

**Comment by LollipopFt** [comment]
hi, may i ask how to check which version i am running if i use ```windows={git="https://github.com/microsoft/windows-rs.git"}``` and what cargo command do i use to update it?
thank you!

**Comment by kennykerr** [comment]
It depends on what you've asked for in your cargo.toml file. This is documented here:

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

If you point to GitHub then you get the latest development version, which isn't necessarily stable. If you ask for the latest version as illustrated here - https://crates.io/crates/windows - then you get the latest stable version, which is currently 0.11.0.

You should just remove `CS_OWNDC, CS_HREDRAW, CS_VREDRAW` from your build script. They should be included as necessary.

**Comment by LollipopFt** [comment]
i see, thank you!

**Comment by LollipopFt** [comment]
well turns out i do need CS_OWNDC, ran with proper crate:
```rust
C:\Users\lollipopft\rust\projects\winapi\window>cargo run
   Compiling proc-macro2 v1.0.27
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.73
   Compiling windows_gen v0.11.0
   Compiling const-sha1 v0.2.0
   Compiling quote v1.0.9
   Compiling windows_macros v0.11.0
   Compiling windows v0.11.0
   Compiling bindings v0.1.0 (C:\Users\lollipopft\rust\projects\winapi\window\bindings)
error: `Windows.Win32.UI.WindowsAndMessaging.CS_OWNDC` not found in metadata
 --> bindings\build.rs:5:67
  |
5 |             UI::WindowsAndMessaging::{WNDCLASSW, WNDCLASS_STYLES, CS_OWNDC, CS_HREDRAW, CS_VREDRAW, DefWindowProcW}
  |                                                                   ^^^^^^^^

error: aborting due to previous error

error: could not compile `bindings`
```

my cargo.toml:
```rust
[dependencies]
windows="0.11.0"

[build-dependencies]
windows="0.11.0"
```

rip

**Comment by tim-weis** [comment]
Adding `WNDCLASS_STYLES` to *build.rs* should be sufficient to have the code generator generate the constants of that type (such as `CS_OWNDC`). This was the result of #843.

In other words, you should replace
```rust
UI::WindowsAndMessaging::{WNDCLASSW, WNDCLASS_STYLES, CS_OWNDC, CS_HREDRAW, CS_VREDRAW, DefWindowProcW}
```
with
```rust
UI::WindowsAndMessaging::{WNDCLASSW, WNDCLASS_STYLES, DefWindowProcW}
```

The individual style constants (e.g. `CS_OWNDC`) are then generated into `bindings::Windows::Win32::UI::WindowsAndMessaging`, allowing you to import them like this:

```rust
use bindings::Windows::Win32::UI::WindowsAndMessaging::CS_OWNDC;
```

**Comment by LollipopFt** [comment]
oh it works thanks!
