### ISSUE TITLE
Support Rust using WinUI3+ProjectReunion

### ISSUE THREAD

**Issue by clemenswasser** [microsoft/windows-rs#875]
On top of the [impl_inner](https://github.com/microsoft/windows-rs/tree/impl_inner) branch, I am trying to build [a sample](https://github.com/clemenswasser/winui3) that uses WinUI3+ProjectReunion. For that I have used the [xaml_app](https://github.com/microsoft/windows-rs/tree/impl_inner/examples/xaml_app) and [reunioncppdesktopsampleapp](https://github.com/microsoft/Project-Reunion-Samples/tree/main/HelloWorld/reunioncppdesktopsampleapp) as a basis. My Application already partially works. I am able to generate bindings for the WinUI3 winmd files (which I extracted from the ProjectReuinion NuGet package) and then use these to implement `Microsoft.UI.Xaml.Application` and override `OnLaunch` (Really much like the `xaml_app` example). However the app crashes with an internal exception from WinUI3: `Exception thrown at 0x00007FFD11A73B19 (KernelBase.dll) in winui3.exe: WinRT originate error - 0x80004005 : 'WinUI: Error creating an UWP Window. Creating an UWP window is not allowed.'.`
The exception comes from a separate Thread (i.e. not the Main Rust thread and probably internally from within the WinUI3 implementation) with the following StackTrace:
```
KernelBase.dll!RaiseException()	Unknown
combase.dll!SendReport(HRESULT error, unsigned int cchMax, const wchar_t * message, unsigned short pSid, void * pExceptionObject, IUnknown *) Line 438	C++
combase.dll!RoOriginateError(HRESULT error, HSTRING__ * message) Line 590	C++
Microsoft.ui.xaml.dll!DirectUI::Window::Window(void)	Unknown
Microsoft.ui.xaml.dll!ctl::ComObject<class DirectUI::Window>::ComObject<class DirectUI::Window>(struct IInspectable *)	Unknown
Microsoft.ui.xaml.dll!DirectUI::Window::Create()	Unknown
Microsoft.ui.xaml.dll!DirectUI::DXamlCore::InitializeInstance()	Unknown
Microsoft.ui.xaml.dll!DirectUI::DXamlCore::InitializeImpl(enum InitializationType,bool)	Unknown
Microsoft.ui.xaml.dll!DirectUI::FrameworkView::Initialize()	Unknown
twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::CreateAndInitializeFrameworkView()	Unknown
twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationViewAgileContainer::InitializeView()	Unknown
twinapi.appcore.dll!<lambda>(void)()	Unknown
SHCore.dll!_WrapperThreadProc()	Unknown
kernel32.dll!BaseThreadInitThunk()	Unknown
ntdll.dll!RtlUserThreadStart()	Unknown
```
I have also compared my Application with the [reunioncppdesktopsampleapp](https://github.com/microsoft/Project-Reunion-Samples/tree/main/HelloWorld/reunioncppdesktopsampleapp) one written in C++ (from which I already use the Appxmanifest and other things) but I am unable to find any differences (except that the C++ one uses a single threaded apartment, which when used in Rust gives the following exception: `Exception thrown at 0x00007FFD11A73B19 (KernelBase.dll) in winui3.exe: WinRT originate error - 0x8001010E : 'The Application Object must initially be accessed from the multi-thread apartment.'.` 🤔).

**Comment by kennykerr** [comment]
Neither ProjectReunion nor WinUI officially support Rust at the moment so I'll just transfer this issue to the windows-rs repo in order to make the topic more searchable.

**Comment by kennykerr** [comment]
We're working on the [windows-app](https://github.com/microsoft/windows-app-rs) crate to make it easier to use the Windows App SDK from Rust. This includes what was formerly known as Project Reunion and WinUI.

**Comment by kennykerr** [comment]
Close this issue as I don't believe there is any further actionable work here for the Windows crate. Ongoing support for the Windows App SDK (including WinUI) will come from the [windows-app](https://github.com/microsoft/windows-app-rs) crate. I will of course continue to improve the underlying language support via issues like #81.
