### ISSUE TITLE
Nano COM interfaces do not implement "Send"

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#878]
Nano COM interfaces, such as the DirectX ones, don't implement Send.  I think that this makes it impossible, or at least very awkward, to use async functions with D3D.

**Comment by kennykerr** [comment]
This is where we may need some attribute on these interfaces to indicate that they're meant to be thread-safe. There's nothing that tells me that these are inherently thread-safe at compile-time. Presumably they implement IAgileObject but that isn't known at compile-time (when code is generated for Send/Sync). Perhaps we can suggest/hint to the win32 metadata generator that these have some kind of thread-safe attribute.
