### ISSUE TITLE
Consider renaming `and_some` to something else potentially make this easier?

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#880]
Just as a thought - would renaming `and_some` to something else potentially make this easier? The closest equivalent in `std` IMO is `Option::and`. Is `result.and(error)?` any clearer?

_Originally posted by @rylev in https://github.com/microsoft/windows-rs/pull/870#discussion_r654240786_

**Comment by tim-weis** [comment]
The implemented pattern of `and_some()` is a conjunction of a `Result` and an attempt to `unwrap()` an `Option`.

How about `and_try_unwrap()`?

**Comment by fghzxm** [comment]
I prefer `and_some` as is.  The intuition is that for `p: Result<P>` and `q: Result<Q>`, the type of "`p` and `q`" is isomorphic to `Result<(P, Q)>`.

Therefore, if an `.and()` method must be added, it should take a `Result<T>`, not a `T`, in my opinion, whereas `.and_some()` takes a `T`, implying that `r.and_some(t) == r.and(Some(t))`.

**Comment by kennykerr** [comment]
This has now been completed as of #909. Most COM methods and functions now provide a far superior calling experience. There's thus very little need to use `and_some` directly so I'm not going to worry about its name.
