### ISSUE TITLE
Cannot Call Windows Runtime Component Within Rust

### ISSUE THREAD

**Issue by alexjgreig** [microsoft/windows-rs#883]
Hey,

I have created A Windows Runtime Component in C++/WinRT which creates an empty IVector, however when I attempt to use it in Rust this error occurs:
`Error { code: 0x80040154, message: "Class not registered" }` 

The .cpp file is:
`
namespace winrt::CreateIVectorWRC::implementation
{
    IVector<hstring> CreateIVector::CreateVector()
    {
        IVector<hstring> vec{ single_threaded_vector<hstring>() };
        return vec;
    }
}
`
and calling the function in Rust is done by:
`let empty_ivector: IVector<HSTRING> = CreateIVector::CreateVector().unwrap();`

I have also made sure that I included the .winmd file in the .windows/winmd folder and have included the .dll file in both x64 and x86 folders.

Thanks.

**Comment by kennykerr** [comment]
You should be able to hook up a debugger and find out why it fails to load. Perhaps you failed to include DLL dependencies, such as the particular CRT the component depends on (prefer static linking). That would prevent the component from loading (`LoadLibrary` would fail).

**Comment by alexjgreig** [comment]
Thanks @kennykerr  for your quick response, Where would the DLL Dependencies be located when I build a Windows Runtime Component, especially the CRT? In conjunction to this how would I setup static linking?

**Comment by sylveon** [comment]
After helping them on Discord, I found that the issue here was that the component actually wasn't registered at all, using registration free activation solved the issue:

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <file name="CreateIVectorWRC.dll" hashalg="SHA1" xmlns:winrt="urn:schemas-microsoft-com:winrt.v1">
        <winrt:activatableClass name="CreateIVectorWRC.CreateIVector" threadingModel="both" />
    </file>
</assembly>
```

To embed this manifest into a Rust executable: `mt.exe -nologo -manifest "myapp.manifest" -outputresource:"myapp.exe;#1"` in a VS Developer Command prompt (replacing `myapp` with appropriate values)
