### ISSUE TITLE
How to mix and match Result<>s from windows-rs and standard crates

### ISSUE THREAD

**Issue by damyanp** [microsoft/windows-rs#884]
For example, if I have a function that starts with:

```rust
    fn new(device: &ID3D12Device, descriptor_heap: &CbvSrvUavDescriptorHeap) -> Result<Resources> {
        let file = std::fs::File::open(DATA_FILE_NAME)?;
```

Then this fails to compile because the open returns `io::Result<File>`, because there's no From for this.

Am I missing something?  Or instead should I be asking about implementing `<windows::Error as From<io::Error>>`?

**Comment by Nerixyz** [comment]
You're essentially facing the problem of multiple error types.

In the [Rust by Example](https://doc.rust-lang.org/rust-by-example/error/multiple_error_types.html) book they show multiple ways of handling this.

The simplest way of handling this is to use a library like [anyhow](https://docs.rs/anyhow), but you have to understand what it does and more importantly what it disregards about the original error.

**Comment by damyanp** [comment]
In many cases I think that we could convert the io::Result into a windows::Result, using `Error::raw_os_error` - and possibly back again?  I think that cppwinrt does something similar to this with HRESULTs and some other know C++ error types.

**Comment by Nerixyz** [comment]
You could convert the results this way but I think it's common for libraries to define their wrapper-error. This way users can handle the different errors (possibly) on their own. 

I feel like converting with `Error::raw_os_error` and `Error::from_raw_os_error` is relying on implementation-detail.

**Comment by kennykerr** [comment]
@rylev thoughts?

**Comment by tim-weis** [comment]
Doesn't

```rust
-> result::Result<Resources, Box<dyn error::Error>>
```

work?

**Comment by kennykerr** [comment]
Yes, that should work given that `windows::Error` implements `std::error::Error`.

**Comment by rylev** [comment]
The best way to handle this as an application is probably to have your functions return `Result<T, Box<dyn std::error::Error>>` as @tim-weis suggests. 

For a library I would define a custom type that easily allows converting from `windows::Error` and `std::io::Error` to that custom type. You can use [`thiserror`](https://crates.io/crates/thiserror) to help with that. 

```rust
#[derive(thiserror::Error, Debug)]
enum MyError {
  IoError(#[from] std::io::Error),
  WindowsError(#[from] windows::Error)
}
```
