### ISSUE TITLE
CloseHandle not found in metadata

### ISSUE THREAD

**Issue by 74wny0wl** [microsoft/windows-rs#888]
It's not possible to use CloseHandle function. 

### Steps to reproduce ###

After using CloseHandle in build.rs:

```
fn main() {
    windows::build!(
        Windows::Win32::Foundation::CloseHandle,
   )
}
```

there is an error:

```
error: `Windows.Win32.Foundation.CloseHandle` not found in metadata
 --> bindings\build.rs:3:37
  |
3 |         Windows::Win32::Foundation::CloseHandle,
  |                                     ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `bindings`

```

**Comment by tim-weis** [comment]
I cannot reproduce the issue using the *windows* crate version 0.11.0. Which version are you using?

**Comment by 74wny0wl** [comment]
Ok, it was an error releted with different versions in main project and bindings
