### ISSUE TITLE
documentation for version 0.8.0 doesn't exist?

### ISSUE THREAD

**Issue by AyashiNoCeres** [microsoft/windows-rs#895]
I love using this library however the updates to versions break so many things that I'd prefer to just stick with an old version until the changes no longer break everything as I find myself unable to update existing projects to the later versions.

Problem I am having is I can't seem to find documentation for anything but the latest version which isn't very helpful...
am I just looking in the wrong place?

not being able to find documentation for older versions also makes it more challenging to upgrade to later versions

**Comment by kennykerr** [comment]
The Windows crate is still in its initial development phase, hence the 0.x version numbers, and will continue to change substantially as major improvements are made both to the metadata that drives the code generation as well as the code transformation itself. Certainly, feel free to skip some updates for stability. 

Regarding documentation, it depends on what you mean. The docs for the Windows crate include previous versions here:

https://docs.rs/windows/0.11.0/windows/

![image](https://user-images.githubusercontent.com/9845234/122937293-b5f6cb00-d326-11eb-98d6-cbb561933759.png)

For the experimental documentation for the APIs themselves, only the latest is available from what I can tell:

https://github.com/microsoft/windows-docs-rs

It's hosted on GitHub Pages and it doesn't seem to preserve older snapshots. You can always use something like [ILSpy](https://github.com/icsharpcode/ILSpy) to view the metadata for the version you happen to be using.

**Comment by AyashiNoCeres** [comment]
Ah yes it was the experimental documentation I was looking at. I did wonder why sometimes I'd find things and sometimes I couldn't. Didn't even realise there were two versions.

How do I use the above documentation? 
Eg I'm trying to look for info on GetCursorPos, but that documentation returns no information (the experimental documentation does...)

**Comment by kennykerr** [comment]
The documentation for the Windows crate (https://docs.rs/windows/0.11.0/windows/) only contains the documentation for the types in the crate itself (e.g. hand-written code). This does not include the generated bindings as that depends on what metadata and APIs you've chosen to generate. Once we have pre-generated bindings (#432), we should be able to publish stable and versioned documentation for APIs as well.

**Comment by AyashiNoCeres** [comment]
ah okay thank you that clears up a lot of the confusion

Is there any like changelog or process that helps in updating between versions or is a case of just figuring it out somehow? 

I think this documentation trap is a bit of an issue as in my case it results in the project being frozen in time. No older documentation means I can't figure out how to do things in 0.8.0 any more so I can't keep using it and makes it so I can't figure out how to upgrade somethings to 0.11.0.

I'll try and figure out how to use ILSpy to get the old version of the experimental documentation, hopefully i can figure it out. Is there no way of downloading the documentation for offline use to avoid this problem in the future.

**Comment by kennykerr** [comment]
You can generate the documentation yourself, but its easier just to use ILSpy. The Rust docs also don't scale well at the moment with the sheer size of the Windows API, making ILSpy quite a lot faster for searching. Generally, you just update your toml file to the latest version and rebuild. It may tell you that it cannot find certain APIs. You then search ILSpy to find out where they've gone and then update the paths in the build script etc. I did a bunch of work to improve the error reporting from the build script recently so that should also be easier than before. There was a lot of churn in the [metadata](https://github.com/microsoft/win32metadata) recently, but hopefully the bulk of that is now behind us.
