### ISSUE TITLE
implement macro does not know Rust namespace rules?

### ISSUE THREAD

**Issue by drewcrawford** [microsoft/windows-rs#903]
I realize I'm *super* early to the party where a lot of things are still in flux.  I'm mostly opening this so there's some search result for `use of undeclared type: Microsoft` and `error: bindings.Microsoft.UI.Xaml.Application not found in metadata` that discusses the `#[implement()]` derive macro and its expectations.

I noticed when playing around with `implement` that it is quite opinionated about paths.  e.g.

```rust
#[implement(
    extend bindings::Microsoft::UI::Xaml::Application,
)]
```

does not work, I guess because it expects a path from the root of winmd metadata, not a detailed comprehension of what's in scope at the macro site.  Based on that theory, I tried

```rust
//shouldn't need this to look up the root of winmd, right?
//use bindings::Microsoft; 
#[implement(
    extend Microsoft::UI::Xaml::Application,
)]
```

which also does not work, because it must be in-scope at the macro site, not just at the root of winmd.

I'm guessing something like these constraints are an undocumented limitation of the macro.

**Comment by kennykerr** [comment]
Indeed, the implement macro is limited (like any macro) in that it cannot see the context within which is is executing. It can only see the input token stream and that does not include any effective use declarations or module scopes that may apply. As a result, the use paths must be relative to metadata not Rust. I'd love a way to solve this but I haven't found any yet.

**Comment by drewcrawford** [comment]
Should there be a syntax to specify rust and winmd name separately?  I guess it’s unlikely that two separate things to insist on calling themselves Microsoft, but it becomes more likely given that one thing does

**Comment by kennykerr** [comment]
It only needs to support names from metadata.

**Comment by drewcrawford** [comment]
It requires that the name in the metadata match an imported rust name, when for various reasons they might not. (Programmer error, in my case. But alternatively, any other macro that wants to name its things in a way that shadows any windows API).
