### ISSUE TITLE
D2D1CreateFactory handled unsatisfactorily

### ISSUE THREAD

**Issue by fghzxm** [microsoft/windows-rs#911]
The function `D2D1CreateFactory` from `d2d1.h` has the nonstandard signature
```c++
HRESULT D2D1CreateFactory(
  D2D1_FACTORY_TYPE          factoryType,
  REFIID                     riid,
  const D2D1_FACTORY_OPTIONS *pFactoryOptions, // boo
  void                       **ppIFactory
);
```
After #909, its Rust projection becomes
```rust
pub unsafe fn D2D1CreateFactory(
    factorytype: D2D1_FACTORY_TYPE,
    riid: *const Guid,
    pfactoryoptions: *const D2D1_FACTORY_OPTIONS,
    ppifactory: *mut *mut std::ffi::c_void,
) -> Result<()>
```
with a `Result<()>` replacing the old `HRESULT` in the return type, precluding the old `and_some` idiom even if I want to use it.

**Comment by kennykerr** [comment]
The new support for COM function signatures (#909) detects most of the common signature patterns but there are some wonky APIs that don't follow normal conventions. Most functions that return a queryable interface have a trailing pair of parameters - `GUID*, void**` -  and those are transformed naturally but `D2D1CreateFactory` inexplicably has a parameter in between. `D3D11CreateDevice` is another example where the pattern is broken. While the previous `and_some` method doesn't apply as that was a method on `HRESULT`, the `Result` type can do something similar with its `map` method. Here are some examples from the Clock sample.

https://github.com/microsoft/windows-rs/blob/907b7a6aff1a2e671d98b994a605082c677797b4/examples/clock/src/main.rs#L510-L520

https://github.com/microsoft/windows-rs/blob/907b7a6aff1a2e671d98b994a605082c677797b4/examples/clock/src/main.rs#L546-L562

It's not quite the same but should get you unblocked for now while I continue to improve the experience for COM developers.
