### ISSUE TITLE
`Microsoft::UI::Xaml::Controls::Grid` attached property getters and setters not properly generated

### ISSUE THREAD

**Issue by rylev** [microsoft/windows-rs#919]
I might be missing something, but it seems that the attached property getters and setters of `Microsoft::UI::Xaml::Controls::Grid` are not properly generated:

```rust
pub fn SetColumn<'a>(
    element: impl ::windows::IntoParam<'a, super::FrameworkElement>,
    value: i32,
) -> ::windows::Result<()> {
    Self::IGridStatics(|this| unsafe {
        (::windows::Interface::vtable(this).18)(
            ::windows::Abi::abi(this),
            element.into_param().abi(),
            value,
        )
        .ok()
    })
}
```

I would expect this to be a method on `Grid` and no an associated function. Is this incorrectly defined or am I just missing how this is supposed to be used?

**Comment by kennykerr** [comment]
It sure sounds like it should be a method but the metadata says otherwise. This is the in-box version but its basically the same. Notice that in C# it is a static method:

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.grid.setcolumn?view=winrt-20348
