### ISSUE TITLE
Add Win32 Macros

### ISSUE THREAD

**Issue by ryancerium** [microsoft/windows-rs#921]
I'm porting my tiny window manager from winapi-rs and had to create inline functions for the bit manipulation macros.  I'm sure I'm missing tons more, but I can't find a single point of reference in the API docs.  Many of them seem to be defined in `minwindef.h` and `winbasex.h`

```C
MAKEWORD
MAKELONG
LOWORD
HIWORD
LOBYTE
HIBYTE
GET_X_LPARAM
GET_Y_LPARAM
```

**Comment by kennykerr** [comment]
The win32 metadata, where most of the API definitions come from, doesn't include macros.

https://github.com/microsoft/win32metadata

**Comment by ryancerium** [comment]
Are you going to add non-metadata things or would that end up in a separate crate?  I'd open a PR to add some of these things if you know where you want to put them.

**Comment by kennykerr** [comment]
I would think this could live in a separate crate as a set of inline helper functions.

**Comment by ryancerium** [comment]
But _should_ they live in another crate?  Those macros are pretty integral to Win32 programming, distasteful as the byte-level manipulations are in Rust.

**Comment by kennykerr** [comment]
It's certainly debatable. You'll have to forgive me for being a little cautious as there are thousands of macros in the Windows SDK. 😉 

Deciding which are "integral" is going to be an uphill battle.

**Comment by ryancerium** [comment]
Yeah...  At this stage of development I think getting the architecture-specific struct packing in is more important than `MAKEWORD` :-D

Separately, how are you evaluating best practices for Win32 programming in Rust?  The fast-and-loose nature of DWORD/INT_PTR/WPARAM conversions is hard.  My tiny program has a big chunk of `as u32` and `as usize` in it already, but maybe that just gets abstracted away in a framework at some point.

**Comment by ryancerium** [comment]
I forgot about all the `SendMessage` macros for UI elements... yeesh...

**Comment by kennykerr** [comment]
Yep... the WinRT APIs are mostly idiomatic and directly usable. The Win32 APIs are mostly going to stay faithful to the original definitions and will likely need various specialized hand-written crates wrapping the different APIs to provide a more idiomatic developer experience.
