### ISSUE TITLE
Having to manually use each enum item

### ISSUE THREAD

**Issue by 1Dragoon** [microsoft/windows-rs#925]
Not sure what version introduced this change, but I've noticed that in the 0.13 release, when I try to import Windows::Win32::Networking::ActiveDirectory::ADS_AUTHENTICATION_ENUM for example, I can't then just reference to the items as (for example) ADS_AUTHENTICATION_ENUM::ADS_SECURE_AUTHENTICATION. Instead, I have to add bindings::Windows::Win32::Networking::ActiveDirectory::ADS_SECURE_AUTHENTICATION to the using statements for each enum item that I want to use, and indeed every enum under the ActiveDirectory module has all of its items added to the parent as constants.

Is there any way to get the previous behavior?

**Comment by kennykerr** [comment]
You're running into: #843 #787

Some duplicates that may help explain the new behavior: #727 #854 #893 #810

**Comment by 1Dragoon** [comment]
Ah ok that makes sense, yeah the enums I've been using all have the scope in their name. I suppose the ideal thing to do is to bring all of the super into scope (i.e. bindings::Windows::Win32::Networking::ActiveDirectory::*) and just use them directly.

Thanks to you and Microsoft for this project by the way, makes creating win32 applications so much easier. :)
