### ISSUE TITLE
`Windows.Networking.ServiceDiscovery.Dnssd` not found in metadata

### ISSUE THREAD

**Issue by r4nd0m1z3r** [microsoft/windows-rs#926]
I copied this API from MSDN, and it appears to be non-existent in metadata. Or is it a wrong API? Then, please, tell me where I should look for correct API names.

**Comment by kennykerr** [comment]
Adding this namespace to a build script produces bindings for me using version `0.13.0` of the `windows` crate:

```rust
fn main() {
    windows::build! {
        Windows::Networking::ServiceDiscovery::Dnssd::*,
    };
}
```

**Comment by r4nd0m1z3r** [comment]
Oh, so Dnssd also appears to be namespace? Thank you very much, now it compiles.
