### ISSUE TITLE
Interfacing with third-party COM libraries

### ISSUE THREAD

**Issue by alexkirsz** [microsoft/windows-rs#928]
Hey,

I have a third-party COM interface in the form of a `.tlb` file and MIDL-generated `.h` and `i.c` files. I'm currently planning on either using `bindgen` to generate C bindings, or `cxx` to generate C++ bindings.

Is there a way to interface with it using the `windows` crate directly? Or can I use the `bindgen`-generated types with this crates' capabilities?

**Comment by kennykerr** [comment]
The Win32 and COM definitions are currently produced by the Win32 metadata project where there is an issue to support 3rd party libraries - https://github.com/microsoft/win32metadata/issues/66 - I believe they're working on a tool to make that possible.

The Windows crate itself should eventually support this directly (without external tools) once the #81 is complete.

**Comment by alexkirsz** [comment]
@kennykerr Thanks for the quick reply! I'm not seeing any mention of `.tlb` in this thread, I take it it's covered by `.winmd` support?

As per [your comment](https://github.com/microsoft/windows-rs/issues/81#issuecomment-669389588), #81 seems to be about defining COM/WinRT types in Rust to be consumed elsewhere. Here I'm really trying to do the inverse: consume arbitrary types defined elsewhere in Rust. Am I understanding this correctly?

**Comment by kennykerr** [comment]
> I'm not seeing any mention of .tlb in this thread

I don't have any plans to support the TLB format. 

> Here I'm really trying to do the inverse: consume arbitrary types defined elsewhere in Rust

#81 will let you define APIs both for consuming in Rust as well as for implementing in Rust. So while you may not be able to generate bindings from a TLB, you would be able to declare the APIs in Rust and then call them directly.
