### ISSUE TITLE
Consider adding (optional) support for generating Rust docs from Windows docs

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#931]
@kennykerr @marler8997 @timsneath this PR updated C#/Win32 to use the new [Microsoft.Windows.SDK.Win32Docs](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Docs/0.1.4-alpha) package to provide Intellisense sourced from our documentation. The package uses [MessagePack](https://msgpack.org/) as the format which supports parsers for many languages including yours (just search for `msgpack-<LANG>` on GitHub).

https://github.com/microsoft/win32metadata/pull/548 and https://github.com/microsoft/win32metadata/pull/548/files#diff-db362395805d75d149824342c0c4117c5475893dccaff9fae75bf18337a8fd84 go into a bit more detail about the package and the schema. This PR serves as a reference implementation.

If you get a chance, would appreciate any feedback you could give on how your experience is consuming it to add better documentation/Intellisense to your projections. Is MessagePack an appropriate format? Is it easy to parse using the existing parsers that exist for your language? Do you have any performance concerns?

Let us know. Thanks!

_Originally posted by @mikebattista in https://github.com/microsoft/CsWin32/issues/309#issuecomment-870086742_

**Comment by kennykerr** [comment]
One concern is that this only covers the Win32 APIs. @mikebattista, any thoughts on publishing the same format for WinRT APIs? Otherwise we'd only have docs for half the Windows API surface in Rust. And then there's new APIs like the Windows App SDK (and WinUI). We'd really need to see broader support for this format before it would make sense to adopt something like this.

**Comment by mikebattista** [comment]
If we can validate the approach with the Win32Docs package and MessagePack format first we could extend coverage to more areas yes.

**Comment by PhoNoTheSky** [comment]
I have tried doing this at https://github.com/PhoNoTheSky/docs-windows-rs/blob/master/src/lib.rs
The current Win32Docs doesn't really provide any information of what type something is, which probably could be found within windows-rs itself

**Comment by kennykerr** [comment]
Rust docs are just way too slow at the moment to support adding even more content. I'm going to leave this for now.
