### ISSUE TITLE
IIterable is not implemented for Vec

### ISSUE THREAD

**Issue by r4nd0m1z3r** [microsoft/windows-rs#933]
I want to pass props to function DeviceInformation::CreateWatcherWithKindAqsFilterAndAdditionalProperties.
I got "IIterable is not implemented for Vec" when tried to pass Vec of HSTRINGS. Then I googled and found that WinRT has its own collection. But, strangle thing, they dont have methods to be created from rust slice or to push stuff into them (except ConstBuffer, but when you use push_slice(), it takes ownership of itself, preventing successful compilation).

**Comment by Nerixyz** [comment]
`windows-rs` doesn't support the creation of collections yet. This is tracked in #91.
