### ISSUE TITLE
IcmpCreateFile returns wrong handle

### ISSUE THREAD

**Issue by jackyzy823** [microsoft/windows-rs#942]
in generated code
```rust
                pub unsafe fn IcmpCreateFile() -> IcmpHandle {
                    #[cfg(windows)]
                    {
                        #[link(name = "IPHLPAPI")]
                        extern "system" {
                            fn IcmpCreateFile() -> IcmpHandle;
                        }
                        IcmpCreateFile()
                    }
                    #[cfg(not(windows))]
                    unimplemented!("Unsupported target OS");
                }

```
and [doc](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/NetworkManagement/IpHelper/fn.IcmpCreateFile.html).  `IcmpCreateFile` returns `IcmpHandle` which can not be used in `IcmpCloseHandle` and others.

maybe it should  return `HANDLE` and generate like this 
```rust
unsafe fn IcmpCreateFile<'a>() -> HANDLE {
    #[cfg(windows)]
    {
        #[link(name = "IPHLPAPI")]
        extern "system" {
            fn IcmpCreateFile() -> HANDLE;
        }
        IcmpCreateFile()
    }
    #[cfg(not(windows))]
    unimplemented!("Unsupported target OS");
}
```

`Icmp6CreateFile` has the same problem.

Please let me know if i am misunderstanding. Thanks.

Ref: 
https://docs.microsoft.com/en-us/windows/win32/api/icmpapi/nf-icmpapi-icmpcreatefile

**Comment by jackyzy823** [comment]
maybe we should blame on https://github.com/microsoft/win32metadata/blob/58a4e118f2d658b97a52ac25d4dbc9e9ab223fdd/generation/emitter/remap.rsp#L206

**Comment by riverar** [comment]
@jackyzy823 Agreed. I filed a bug on your behalf to get things going. https://github.com/microsoft/win32metadata/issues/565 Will close out this issue in favor of that one.

In the meantime, you can access the underlying _isize_ via the `.0` field and construct a HANDLE (e.g. `let handle = HANDLE(icmp_handle.0)`.

**Comment by riverar** [comment]
Fixed in the next win32metadata release (after v10.2.118-preview) https://github.com/microsoft/win32metadata/commit/a166484a00695139f37e9df16dd95fd7b85ad832
