### ISSUE TITLE
Add filter to what gets copied out of .windows

### ISSUE THREAD

**Issue by riverar** [microsoft/windows-rs#950]
Right now, we indiscriminately copy everything in `.windows/[arch]` to the target location. But this location is also used for storage of libs, e.g. for static linkage https://github.com/microsoft/windows-rs/pull/947, so copying those files is unnecessary.

**Comment by kennykerr** [comment]
Is there some harm in copying them? I'm concerned about adding extra configuration overhead for the developer and without knowing how the crate is being used it would be difficult to figure it out automatically.

**Comment by kennykerr** [comment]
Perhaps we could have a `<arch>\!publish` subfolder but yeah probably wait until we have a real use case to validate against.
