### ISSUE TITLE
windows-gen build script loops forever if OUT_DIR does not have a Cargo.toml in its tree

### ISSUE THREAD

**Issue by monax3** [microsoft/windows-rs#953]
If you set the Cargo target-dir to somewhere other than a sub directory of the project this snippet will never complete:

https://github.com/microsoft/windows-rs/blob/734794414fb4c4d8695bce3c6dda1fe8be6f46a2/crates/gen/build.rs#L9-L26

Presumably other stuff would fail too since the expected directory structure isn't there.

**Comment by kennykerr** [comment]
I'm working on this. The trouble is that there's no reliable way to find the target directory.

https://github.com/rust-lang/docs.rs/issues/1444#issuecomment-875226861

https://github.com/rust-lang/cargo/issues/9661

This didn't work: https://github.com/microsoft/windows-rs/pull/951

**Comment by kennykerr** [comment]
This should be fixed as of 0.17.0
