### ISSUE TITLE
Structs missing in metadata

### ISSUE THREAD

**Issue by Justfr33z** [microsoft/windows-rs#958]
`MEMORY_BASIC_INFORMATION`
`MEMORY_BASIC_INFORMATION32`
`MEMORY_BASIC_INFORMATION64`
located in `Windows::Win32::System::SystemServices` are missing after version `0.13.0`

```
error: `Windows.Win32.System.SystemServices.MEMORY_BASIC_INFORMATION` not found in metadata
  --> bindings\build.rs:13:17
   |
13 |                 MEMORY_BASIC_INFORMATION,
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^
```

[MEMORY_BASIC_INFORMATION](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/SystemServices/struct.MEMORY_BASIC_INFORMATION.html)
[MEMORY_BASIC_INFORMATION32](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/SystemServices/struct.MEMORY_BASIC_INFORMATION32.html)
[MEMORY_BASIC_INFORMATION64](https://microsoft.github.io/windows-docs-rs/doc/bindings/Windows/Win32/System/SystemServices/struct.MEMORY_BASIC_INFORMATION64.html)

**Comment by kennykerr** [comment]
These moves to the `Windows.Win32.System.Memory` namespace as of https://github.com/microsoft/windows-rs/pull/943.

**Comment by kennykerr** [comment]
I've published updated docs. Sorry for the confusion.
