### ISSUE TITLE
Version 0.17 "Failed to resolve: Could not find `Windows` in bindings" but not <=0.14

### ISSUE THREAD

**Issue by ivan0051** [microsoft/windows-rs#987]
In order to learn how to use the Windows api for Rust, I am following Kevin Kerr's video guide linked at: https://docs.microsoft.com/en-us/windows/dev-environment/rust/rust-for-windows

This video is admittedly a bit outdated despite being just a handful of months back, as the dependencies use 0.9. However, not only do versions 0.9 through 0.14 succeed to perform the tasks in the tutorial, but as well, the usage mirrors examples on this repository's README through all versions, usage unchanged according to crates.io. This built the assumption that the guidance was in fact as relevant as possible, and no substantial changes in code would be needed.

However, as soon as I change the dependencies to 0.17.x, it breaks with the error "Failed to resolve: Could not find `Windows` in bindings" in the project's main.rs. It makes it appear that substantial usage changes **were** in fact made. As stated, in 0.9 through 0.14, the project functions without a hitch.

However, there is a seemingly _benign_ issue in those earlier versions that might be worth attention, as it could hint to the culprit. The lower level Cargo.toml (not the one for bindings) has a persistent error (visible as red underlines in VS Code but not when actually compiled) in those versions: "failed to run custom build command for `bindings v0.1.0 (\path\theproject\bindings)`". The red underlines there were not found in Kevin Kerr's demonstration. To clarify, when I switch to 0.17, those lines disappear entirely, but the project instead fails for the reason stated earlier.

Please let me know if there is any additional information I can supply. It is possible that this is a user-end issue since I am not a long experienced programmer, but I am quite confident that I can follow a guided tutorial to the letter and swap some version numbers, and the difference in versions implies a genuine impacting change, as well as the other, benign error message implying a separate possible issue lurking somewhere.

**Comment by kennykerr** [comment]
Feel free to share a specific repro if you can't figure out how to proceed. 

Although the Windows crate is in early development and continues to improve and change, it shouldn't be too difficult to follow the tutorial and get it to work with the latest version. I just raced through it and it seems to work fine.

**Comment by kennykerr** [comment]
There is also a working version of the RSS tutorial sample here:

https://github.com/microsoft/windows-samples-rs

**Comment by ivan0051** [comment]
I found the only discernible difference between my project and the provided link, and added it in (with the version changed to 0.17), and then removed it when I saw it didn't change the result. Then I noticed there were fewer files in the linked project compared to mine, so I deleted my target folder to make it reproduce it, on a whim... And the newer version number suddenly works.

I'm really not sure what went wrong, but it must have been reusing some kind of broken build.

Worth noting, it still says the same non-impacting error about "failed to run custom build command" but I think that's just the RLS not being perfect, since the project does entirely work.

**Comment by kennykerr** [comment]
Its useful to run `cargo clean` when experiencing mysterious build issues. It may be that the build system hasn't cleaned up properly. 

Everyone seems to be rallying around the `rust-analyzer` extension. I hear its way better than RLS.

**Comment by ivan0051** [comment]
I've been avoiding rust-analyzer because it explicitly says it's not fully supported yet, which I took to mean it's newer and therefore still catching up on various stuff that RLS has already implemented. But I'll take your advisement and try it out a bit.
