### ISSUE TITLE
How to use the structure?

### ISSUE THREAD

**Issue by dosgo** [microsoft/windows-rs#988]
May I ask how to call such structures as Struct bindings::Windows::Networking::Vpn::IVpnPlugIn without the new method? I haven't seen any relevant examples.

The bindings::Windows::Networking::Vpn::VpnChannel::ProcessEventAsync method parameter requires this class. .

Thank you

**Comment by kennykerr** [comment]
You can use the `implement` macro to implement the `IVpnPlugIn` interface. Here's an example:

https://github.com/microsoft/windows-samples-rs/blob/master/core_app/src/main.rs

**Comment by dosgo** [comment]
Compilation failed！
cannot find attribute `implement` in this scope？
![image](https://user-images.githubusercontent.com/9545458/126362311-ecf8d749-3fa6-470a-96a3-332b1e3dd31d.png)

**Comment by kennykerr** [comment]
```rust
use windows::*;
```

**Comment by dosgo** [comment]
![image](https://user-images.githubusercontent.com/9545458/126368314-f06e49a4-41dd-4bd6-b557-14a5cbadf74c.png)
![image](https://user-images.githubusercontent.com/9545458/126368379-f761de5d-64b4-4459-b0c1-5b70ae8683d7.png)

**Comment by riverar** [comment]
@dosgo Did you forget to update your build script (`build.rs`) as well?

**Comment by dosgo** [comment]
![image](https://user-images.githubusercontent.com/9545458/126370018-868aa3c9-b74c-46f5-b300-1f876e1fd105.png)

**Comment by riverar** [comment]
@dosgo Review your _[use declarations](https://doc.rust-lang.org/reference/items/use-declarations.html)_ at the top of the file. The Windows module doesn't exist in the paths you specified. I don't have a full picture of your crate configuration but you likely want `use bindings::*`.

The sample demonstrates this, please review:
https://github.com/microsoft/windows-samples-rs/blob/master/core_app/src/main.rs#L3-L4

**Comment by dosgo** [comment]
Thank you! I see, the use statement is hierarchical.
